### ISSUE TITLE
[已恢复] 2018.2.4 服务器炸了（集中讨论）

### ISSUE THREAD

**Issue by ipcjs** [ipcjs/bilibili-helper#100]
## 描述

@esterTion 
服务器经常不能访问，即使能打开了，获取视频地址的接口依然会返回`null`

视频地址：https://www.bilibili.com/bangumi/play/ss21680#183802

PS. 刚想提issue，貌似又好了？发生了什么😂
PS2. 顺便求个能访问港澳台的VPN，脚本不行了后才发现，要找个港澳台的VPN居然这么难😢

**Comment by yang343** [comment]
刚刚看又好了，应该是人太多了

**Comment by zqyde2012** [comment]
现在似乎又好了。。

**Comment by ipcjs** [comment]
[esterTion](https://weibo.com/lcz970?refer_flag=1005055010_&is_all=1#1517683289200)半夜爬起来写了个缓存😅

**Comment by esterTion** [comment]
这个点已经没人了，之后我还得写下逻辑改进，估计下周还得爆炸

上次这么爆炸是哪个来着

**Comment by ipcjs** [comment]
从脚本的安装量来看是最多的一次😣
算史无前例吧，热播中的动画突然被封，只剩港澳台还在播

**Comment by WoadZS** [comment]
@ipcjs @esterTion 是否有捐赠通道，毕竟这样下去服务器成本可能会激增吧？算是支持下大佬工作。

**Comment by ipcjs** [comment]
@WoadZS 
estertion有捐赠通道，[在这里](https://www.biliplus.com/?about)

**Comment by WoadZS** [comment]
@ipcjs 已通过 Paypal 捐了10刀，聊表心意，祝好！ @esterTion

**Comment by Chronostasis14** [comment]
大佬好像又炸了......而且是直接加载不了播放视频的页面
P.S. 好像是不会自动导向番剧页面了，如果直接从bangumi的页面进入就没问题

**Comment by ipcjs** [comment]
6.5.0版加了个“使用B站接口获取视频地址”的选项，如果服务器崩了，可以开启这个选项先用着

缺点是只对部分视频有效，没有1080P

TODO: 
- [x] 改成回退策略

**Comment by AeroHand** [comment]
看不了 换了服务器也不行 Orz

**Comment by zqyde2012** [comment]
现在好像又不行了

**Comment by zqyde2012** [comment]
![default](https://user-images.githubusercontent.com/36111403/36067696-6da6de12-0efd-11e8-9c07-159eb74c910f.png)

**Comment by cyanlink** [comment]
@ipcjs 捐赠链接无法打开（国内裸连、加全局代理均无响应）

**Comment by ipcjs** [comment]
@LinkEscapist @zqyde2012 @AeroHand 
详见：#129

**Comment by Wingsnail** [comment]
请问下，使用脚本突破限制的情况下，页面上所有连接包括视频的流量都是从设定的代理服务器走的吗？这是不是意味着选择更高的画质会消耗代理服务器更多资源？用户是否手动选择清晰度较低但能接受的画质更好？

**Comment by ipcjs** [comment]
不会
