### ISSUE TITLE
配合userscripts可以在iPad/iPhone/macOS Safari上使用

### ISSUE THREAD

**Issue by wenshunb** [ipcjs/bilibili-helper#1001]
不知道应不应该单独开个issue，今天想起来顺手测试了一下，脚本在iPad Safari也能工作。

测试环境
iPadOS: 15.4/iOS 16 Beta 1/macOS Safari 16.0 (18614.1.14.1.15)
[userscripts](https://github.com/quoid/userscripts): 1.2.0 [苹果商店地址](https://apps.apple.com/us/app/userscripts/id1463298887)
[bilibili-helper](https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6): 8.2.22

和桌面浏览器一样设置完成后即可使用。有时可能要多刷新几下。iOS下由于universal link相对比较麻烦，我是横屏+桌面版网站，反复刷新多次后可用。

另外@ipcjs可以添加个其他赞助二维码吗？支付宝好像限制了国外向国内直接转账。 

#935

**Comment by saddit** [comment]
我Mac safari用不了捏

**Comment by wenshunb** [comment]
@838239178 能多提供一些信息吗？比如是无法载入脚本，还是番剧页面没有设置图标之类的。
由于Safari的限制，需要直接下载这个js文件https://github.com/ipcjs/bilibili-helper/raw/user.js/scripts/bilibili_bangumi_area_limit_hack.user.js 并放入相应的文件夹中。具体参考[userscripts](https://github.com/quoid/userscripts)的说明吧。

**Comment by saddit** [comment]
我成功了 url可以保存了

**Comment by liuluyu6** [comment]
> @838239178 能多提供一些信息吗？比如是无法载入脚本，还是番剧页面没有设置图标之类的。
> 由于Safari的限制，需要直接下载这个js文件https://github.com/ipcjs/bilibili-helper/raw/user.js/scripts/bilibili_bangumi_area_limit_hack.user.js 并放入相应的文件夹中。具体参考[userscripts](https://github.com/quoid/userscripts)的说明吧。

您好，我用的最新ipad os 15.5 按教程都设置好了，现在能进到番剧播放页面，但会显示：

## 拉取视频地址失败
原因: {"code":-10403,"message":"抱歉您所在地区不可观看！"}

而且电脑上我可以点账号授权，ipad点了就关闭设置页面了没其他反应，目前就卡在这两个问题看不了
