### ISSUE TITLE
为什么会被解析服务器拉入黑名单

### ISSUE THREAD

**Issue by gwwydsb** [ipcjs/bilibili-helper#1005]
脚本问题：@ipcjs

## 描述
尝试了很多解析服务器都说被拉黑名单

- 问题网址：
https://www.bilibili.com/bangumi/play/ep96703?from_spmid=666.19.0.0

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.23 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep96703?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"不背完cfop不改名","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=96703
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?cid=11234402&qn=112&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=8908f9f47af315b93c9e7f9dccabce4f&module=bangumi&area=tw&access_key={{access_key}}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?cid=11234402&qn=112&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=8908f9f47af315b93c9e7f9dccabce4f&module=bangumi&area=&access_key=f8db00c587cd37232d1f9c6678758e61
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?cid=11234402&qn=112&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=8908f9f47af315b93c9e7f9dccabce4f&module=bangumi&area=cn&access_key=f8db00c587cd37232d1f9c6678758e61
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://東雪蓮.我爱你/intl/gateway/v2/ogv/playurl?access_key=f8db00c587cd37232d1f9c6678758e61&appkey=7d089525d3611b1c&area=th&build=1001310&cid=11234402&ep_id=96703&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=112&ts=1655645823&sign=43417b4df93d3ad7e714ac57c88a9c79
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?cid=11234402&qn=112&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=8908f9f47af315b93c9e7f9dccabce4f&module=bangumi&area=hk&access_key=f8db00c587cd37232d1f9c6678758e61
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=112&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=82a23207e6f9afb9e59e818546f39c3a&module=bangumi&balh_ajax=1&area=tw&access_key=f8db00c587cd37232d1f9c6678758e61
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=112&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=82a23207e6f9afb9e59e818546f39c3a&module=bangumi&balh_ajax=1&area=&access_key=f8db00c587cd37232d1f9c6678758e61
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=112&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=82a23207e6f9afb9e59e818546f39c3a&module=bangumi&balh_ajax=1&area=cn&access_key=f8db00c587cd37232d1f9c6678758e61
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://東雪蓮.我爱你/intl/gateway/v2/ogv/playurl?access_key=f8db00c587cd37232d1f9c6678758e61&appkey=7d089525d3611b1c&area=th&build=1001310&cid=11234402&ep_id=96703&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=112&ts=1655645826&sign=1271f846b0c2e7b1faecd9fd9eccfa56
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://東雪蓮.我爱你/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=112&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=82a23207e6f9afb9e59e818546f39c3a&module=bangumi&balh_ajax=1&area=hk&access_key=f8db00c587cd37232d1f9c6678758e61
debug: /x/web-interface/nav {"uname":"不背完cfop不改名","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44

## 其他

1. 浏览器版本：Edge
2. 国家/地区：台湾

**Comment by Kal-tsit63** [comment]
你的UID呢？

**Comment by gwwydsb** [comment]
> 你的UID呢？

UID351193800

**Comment by Kal-tsit63** [comment]
请加tg群

**Comment by Kal-tsit63** [comment]
新封锁
UID: 351193800
用户空间: 不背完cfop不改名
原因: 回复 @窥藍Ai :漫游泰服也进不去，不知道是不是解析服务器的问题
来源: 
Time: 2021-04-22 17:58:59
Text: 回复 @窥藍Ai :漫游泰服也进不去，不知道是不是解析服务器的问题

**Comment by gwwydsb** [comment]
> 请加tg群

tg群是啥

**Comment by david082321** [comment]
因为你用的是哔哩漫游的公共解析服务器。

有个独立的黑名单，可以提供公共解析服务器的任何人接入。

只要你 宣传漫游 / 宣传解析服务器 / 泰区评论 / 宣传油猴脚本(由于油猴脚本的README写了link到漫游的公共解析服务器)，然后被人举报给我们，就直接拉黑。

接入了黑名单的解析服务器都会拉黑你，但是你仍然可以使用不需要解析服务器的功能。

详细拉黑规则可至漫游的QQ频道查看。
解封可至漫游QQ频道或是漫游TG群。

ps. 喜欢在叔叔眼皮底下宣传是吧？

**Comment by gwwydsb** [comment]
> 因为你用的是哔哩漫游的公共解析服务器。
> 
> 有个独立的黑名单，可以提供公共解析服务器的任何人接入。
> 
> 只要你 宣传漫游 / 宣传解析服务器 / 泰区评论 / 宣传油猴脚本(由于油猴脚本的README写了link到漫游的公共解析服务器)，然后被人举报给我们，就直接拉黑。
> 
> 接入了黑名单的解析服务器都会拉黑你，但是你仍然可以使用不需要解析服务器的功能。
> 
> 详细拉黑规则可至漫游的QQ频道查看。 解封可至漫游QQ频道或是漫游TG群。
> 
> ps. 喜欢在叔叔眼皮底下宣传是吧？

啊这，原来是这样

**Comment by MrAccelerator** [comment]
> > 因为你用的是哔哩漫游的公共解析服务器。
> > 有个独立的黑名单，可以提供公共解析服务器的任何人接入。
> > 只要你 宣传漫游 / 宣传解析服务器 / 泰区评论 / 宣传油猴脚本(由于油猴脚本的README写了link到漫游的公共解析服务器)，然后被人举报给我们，就直接拉黑。
> > 接入了黑名单的解析服务器都会拉黑你，但是你仍然可以使用不需要解析服务器的功能。
> > 详细拉黑规则可至漫游的QQ频道查看。 解封可至漫游QQ频道或是漫游TG群。
> > ps. 喜欢在叔叔眼皮底下宣传是吧？
> 
> 啊这，原来是这样

请问你解决了吗，我也被拉黑了，我都不知道什么我什么时候评论过

**Comment by ZJR-max** [comment]
> 请加tg群

请问怎么加tg群啊？我也被拉黑了UID8531035
