### ISSUE TITLE
为什么代理服务器状态正常但脚本无法使用

### ISSUE THREAD

**Issue by lotaQAQ** [ipcjs/bilibili-helper#1006]
脚本问题：@ipcjs

## 描述

- 问题网址：https://www.bilibili.com/bangumi/media/md28237178
 相同页面相同代理服务器，另一台设备可以正常访问，本设备显示拉取视频地址失败原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.23 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28237178
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=41469&access_key={{access_key}}
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"とある堕落の珈百璃","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":4,"follow":1,"follow_status":2,"login":1,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":476222,"last_ep_index":"8","last_time":1353},"real_price":"0","sponsor":0,"vip_info":{"due_date":1660752000000,"status":1,"type":2}}}
debug: setAreaLimitSeason 000 true
debug: fetch https://api.bilibili.com/x/web-interface/search/default {"params":{},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: /x/web-interface/nav {"uname":"とある堕落の珈百璃","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=0&article_offset=0 {"params":{"alltype_offset":0,"video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=0&article_offset=0 {"params":{"alltype_offset":0,"video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: atRun: 2, complete
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: season41469 {"code":0,"message":"success","result":{"actor":[{"actor":"江口拓也","actor_id":0,"role":"勞埃德·福傑"},{"actor":"種崎敦美","actor_id":0,"role":"阿尼亞·福傑"},{"actor":"早見沙織","actor_id":0,"role":"約爾·福傑"}],"alias":"SPY X FAMILY,間諜過家家","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"6029","bangumi_title":"SPY×FAMILY 間諜家家酒（僅限港澳台地區）","brief":"每個人都有不可告人的一面。\n\n這是一個世界各國均暗地裡進行激烈情報戰的時代。東國（Ostania）與...","business_type":1,"coins":"0","copyright":"bilibili","cover":"https://i0.hdslb.com/bfs/bangumi/image/abf7d5a6a48391386060e083bc1114a5c550c82b.png","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"937816126","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/8a0207011c27f810368a1a7641b733343247511a.jpg","danmaku":"564496393","episode_id":"478668","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV2","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-07 20:00:00.0"},{"av_id":"810336642","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0fe358dd64a6e30723e05dde6a6195f54d9b8de3.jpg","danmaku":"564496357","episode_id":"478466","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-06 14:20:01.0"},{"av_id":"596269983","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0f6bb5c6a4014fa5242d957483fc5545a435f0bd.jpg","danmaku":"713964626","episode_id":"509565","episode_status":2,"episode_type":0,"from":"bangumi","index":"第二集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-07 23:30:07.0"},{"av_id":"553827981","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/875745e1c74159033d82030664c46b774b906e2b.jpg","danmaku":"713964482","episode_id":"509566","episode_status":2,"episode_type":0,"from":"bangumi","index":"第三集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-07 23:30:01.0"},{"av_id":"770074602","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/674ff6bd558ee591d46952a6daf740ad13d3fb50.png","danmaku":"749766424","episode_id":"476225","episode_status":2,"episode_type":0,"from":"bangumi","index":"11","index_title":" 任務11 <星>","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-06-18 23:00:01.0"},{"av_id":"426329656","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/edfe236932ca89dbbc501f840f531c4794f75987.jpg","danmaku":"713964654","episode_id":"509567","episode_status":2,"episode_type":0,"from":"bangumi","index":"第四集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-07 23:30:01.0"},{"av_id":"727465605","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/6cd550e90d7ee030127d507250642d45e31bb63d.png","danmaku":"743933571","episode_id":"476224","episode_status":2,"episode_type":0,"from":"bangumi","index":"10","index_title":"任務10 躲避球大作戰","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-06-11 23:00:01.0"},{"av_id":"342241456","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/c9b517a90ebed2b46a0ebe46256a3733fa603d65.png","danmaku":"737725936","episode_id":"476223","episode_status":2,"episode_type":0,"from":"bangumi","index":"9","index_title":"任務9 假裝恩愛","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-06-04 23:00:01.0"},{"av_id":"981286847","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d53fb1834c2b6af1442c1883eb62af536c2214f1.jpg","danmaku":"713964721","episode_id":"509568","episode_status":2,"episode_type":0,"from":"bangumi","index":"第五集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-07 23:30:01.0"},{"av_id":"256905818","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f73cb92870e8494d0ee87ffdb7184f218dfc09a8.png","danmaku":"731872523","episode_id":"476222","episode_status":2,"episode_type":0,"from":"bangumi","index":"8","index_title":"對秘密警察偽裝行動","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-28 23:00:01.0"},{"av_id":"638770214","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/caa6404f7e2a8431533d98e6afe33797c0d1d96d.jpg","danmaku":"713964682","episode_id":"509569","episode_status":2,"episode_type":0,"from":"bangumi","index":"第六集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-07 23:30:01.0"},{"av_id":"981769558","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e8b6b21e8f4d273bb17cbb5110853977cf566b81.png","danmaku":"725721105","episode_id":"476221","episode_status":2,"episode_type":0,"from":"bangumi","index":"7","index_title":"任務7 目標的次子","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-21 23:00:01.0"},{"av_id":"769093078","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d6eead3b245c5d95bfbd7a08fe85142481581d53.jpg","danmaku":"719344727","episode_id":"511181","episode_status":2,"episode_type":0,"from":"bangumi","index":"第七集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-14 23:30:01.0"},{"av_id":"426677573","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/89ad6c8fcfb5aabdb08371affdd105785885acbe.jpg","danmaku":"725072466","episode_id":"512082","episode_status":2,"episode_type":0,"from":"bangumi","index":"第八集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-21 23:30:01.0"},{"av_id":"256572306","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/36f8ae5dd8153fccc13d293ff56e3674be0b16ab.png","danmaku":"719894108","episode_id":"476220","episode_status":2,"episode_type":0,"from":"bangumi","index":"6","index_title":"任務6 交友行動","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-14 23:00:01.0"},{"av_id":"384478016","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/37deaa748e0c0e625b12962f638144fe45ba9e20.jpg","danmaku":"731186101","episode_id":"513786","episode_status":2,"episode_type":0,"from":"bangumi","index":"第九集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-28 23:30:01.0"},{"av_id":"853858641","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e7773dd2a53027954ec958ca4e07ff691a897b56.png","danmaku":"713377696","episode_id":"476219","episode_status":2,"episode_type":0,"from":"bangumi","index":"5","index_title":"任務5 能否合格 ","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-05-07 23:00:01.0"},{"av_id":"854653744","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/ee0aaf57179844336106469b0b4b3c5c227a217c.jpg","danmaku":"737046523","episode_id":"515146","episode_status":2,"episode_type":0,"from":"bangumi","index":"第十集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-06-04 23:30:00.0"},{"av_id":"511112614","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/62a0e1e740032147ebf1b402ad186e2e7f75d7fd.png","danmaku":"587923466","episode_id":"476218","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"任務4 名門學校面試","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-30 23:00:01.0"},{"av_id":"727474501","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/66ac9370e6f13c5084aae38f503ffdd54f1f0a23.jpg","danmaku":"742882054","episode_id":"516110","episode_status":2,"episode_type":0,"from":"bangumi","index":"第十一集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-06-11 23:31:31.0"},{"av_id":"980938048","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/c1bde4b19f4243c00dff61544e0c62eca2cef204.png","danmaku":"582947406","episode_id":"476217","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"任務3 準備考試","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-23 23:00:00.0"},{"av_id":"470050764","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/58d65dd3997f0493f6c5967b188a2763b8eef0f6.jpg","danmaku":"749048201","episode_id":"517473","episode_status":2,"episode_type":0,"from":"bangumi","index":"第十二集預告","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-06-19 13:10:00.0"},{"av_id":"980727468","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/31b5a78c7ba2abf16497a2662d502b1bbb518a7d.png","danmaku":"576435351","episode_id":"476216","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"任務2 尋找妻子","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-16 23:00:00.0"},{"av_id":"895561702","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a93871df2f7e57ce2ea44bf5588a63ae257205ee.png","danmaku":"571334963","episode_id":"476215","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"任務1 <梟>行動","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-09 23:00:00.0"}],"evaluate":"每個人都有不可告人的一面。\n\n這是一個世界各國均暗地裡進行激烈情報戰的時代。東國（Ostania）與西國（Westalis）的冷戰狀態已經持續數十年。\n\n<黃昏>是西國情報局東國對策科<WISE>的一名優秀間諜。為調查威脅東西兩國和平的人物——東國國家統一黨總裁多諾萬·德斯蒙，上級給予了他一個絕密任務。\n\n任務名為：<梟（Strix）>行動。\n\n內容是“一周之內組建家庭，潛入德斯蒙兒子就讀的名門學校的聯誼會”。\n\n於是<黃昏>扮演成精神科醫生勞埃德·福傑，開始組建家庭。\n然而，他找來的女兒阿尼亞是個能讀心的超能力者，妻子約爾是個殺手！\n三人利害關係一致，便互相隱瞞身份，開始了共同生活。\n世界的和平，就掌握在這意外不斷的臨時一家人手中。\n","favorites":"0","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"SPY X FAMILY","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/abf7d5a6a48391386060e083bc1114a5c550c82b.png","episode_index":{"index_show":"连载中, 每週六更新"},"media_id":28237178,"publish":{"is_finish":0,"is_started":1},"title":"SPY×FAMILY 間諜家家酒（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"476225","newest_ep_index":"11","origin_name":"SPY X FAMILY","play_count":"0","pub_string":"","pub_time":"2022-04-09 23:00:00","pub_time_show":"4月9日 23:00 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"41469","season_status":2,"season_title":"TV","seasons":[{"bangumi_id":"6029","cover":"https://i0.hdslb.com/bfs/bangumi/image/abf7d5a6a48391386060e083bc1114a5c550c82b.png","is_finish":"0","is_new":"1","newest_ep_id":"476225","newest_ep_index":"11","season_id":"41469","season_status":2,"title":"TV"}],"share_url":"http://bangumi.bilibili.com/anime/41469/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/1b3aedf05ccaf873265a5cafc63cbdd647586997.png","staff":"原作：遠藤達哉（連載于集英社「少年JUMP+」）\n導演：古橋一浩\n角色設計：島田和晃\n音樂製作：(K)NoW_NAME\n製作：WIT STUDIO×CloverWorks\n","tag2s":[],"tags":[],"title":"SPY×FAMILY 間諜家家酒（僅限港澳台地區）","update_pattern":"每週六更新","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug:   =>  ks3
debug:   =>  
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}

## 其他

1. 浏览器版本：Edge 100.0.1185.36
2. 国家/地区：中国大陆

**Comment by lotaQAQ** [comment]
我有三个星期没有用了，这次打开之后发现脚本里存储的数据全部消失了，主站登录状态也失效，在重新登录并重新填写代理服务器之后出现此问题

**Comment by AisukaYuki** [comment]
无效日志，提供ep播放页日志

**Comment by lotaQAQ** [comment]
> 无效日志，提供ep播放页日志

没事了，就是结尾加了个/脚本识别不出来
