### ISSUE TITLE
脚本获取视频地址方式错误

### ISSUE THREAD

**Issue by lotaQAQ** [ipcjs/bilibili-helper#1008]
脚本问题：@ipcjs

## 描述

观看台湾地区番剧使用了其他代理解析服务器，代理服务器本身支持台湾地区，先前使用可以正常观看
- 问题网址：https://www.bilibili.com/bangumi/play/ep476244?from_spmid=666.19.0.0

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.23 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep476244?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"とある堕落の珈百璃","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=476244
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://xn--2br335f.icu/pgc/player/web/playurl?cid=582135788&qn=0&type=&otype=json&fourk=1&bvid=BV1DB4y127tx&ep_id=476244&fnver=0&fnval=80&session=491319be7c01cb602258ad0718d5616f&module=bangumi&area=tw&access_key={{access_key}}
debug: /x/web-interface/nav {"uname":"とある堕落の珈百璃","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?cid=582135788&qn=0&type=&otype=json&fourk=1&bvid=BV1DB4y127tx&ep_id=476244&fnver=0&fnval=80&session=491319be7c01cb602258ad0718d5616f&module=bangumi&area=&access_key=6a89c36029cb5b51f0fb81d3db516561
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?cid=582135788&qn=0&type=&otype=json&fourk=1&bvid=BV1DB4y127tx&ep_id=476244&fnver=0&fnval=80&session=491319be7c01cb602258ad0718d5616f&module=bangumi&area=hk&access_key=6a89c36029cb5b51f0fb81d3db516561
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?cid=582135788&qn=0&type=&otype=json&fourk=1&bvid=BV1DB4y127tx&ep_id=476244&fnver=0&fnval=80&session=491319be7c01cb602258ad0718d5616f&module=bangumi&access_key=6a89c36029cb5b51f0fb81d3db516561
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://xn--2br335f.icu/pgc/player/web/playurl?avid=undefined&cid=582135788&bvid=BV1DB4y127tx&qn=0&type=&otype=json&ep_id=476244&fourk=1&fnver=0&fnval=80&session=15328100eefb991fa701db701bdb84a2&module=bangumi&balh_ajax=1&area=tw&access_key=6a89c36029cb5b51f0fb81d3db516561
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?avid=undefined&cid=582135788&bvid=BV1DB4y127tx&qn=0&type=&otype=json&ep_id=476244&fourk=1&fnver=0&fnval=80&session=15328100eefb991fa701db701bdb84a2&module=bangumi&balh_ajax=1&area=&access_key=6a89c36029cb5b51f0fb81d3db516561
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?avid=undefined&cid=582135788&bvid=BV1DB4y127tx&qn=0&type=&otype=json&ep_id=476244&fourk=1&fnver=0&fnval=80&session=15328100eefb991fa701db701bdb84a2&module=bangumi&balh_ajax=1&area=hk&access_key=6a89c36029cb5b51f0fb81d3db516561
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=582135788&bvid=BV1DB4y127tx&qn=0&type=&otype=json&ep_id=476244&fourk=1&fnver=0&fnval=80&session=15328100eefb991fa701db701bdb84a2&module=bangumi&balh_ajax=1&access_key=6a89c36029cb5b51f0fb81d3db516561
debug: /x/web-interface/nav {"code":0,"message":"0","ttl":1,"data":{"following":99,"follower":8,"dynamic_count":27}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44

## 其他

1. 浏览器版本：Edge 102.0.1245.44 (正式版本) (64 位)
2. 国家/地区：中国大陆

**Comment by JasonKhew96** [comment]
解析服务器问题 @LiuluOfficial

**Comment by LiuluOfficial** [comment]
tw寄了，暂时没有复活赛可打
tw换个服务器即可

**Comment by lotaQAQ** [comment]
> tw寄了，暂时没有复活赛可打 tw换个服务器即可

okok，换了一个服务器可以了，但那个服务器快到期了还不打算续费

**Comment by AisukaYuki** [comment]
笑死 不会是我的吧（

**Comment by lotaQAQ** [comment]
> 笑死 不会是我的吧（

哈哈哈是你的还有370多天，属于是提前担忧了（
