### ISSUE TITLE
关于解决无法连接服务器的问题

### ISSUE THREAD

**Issue by MrDian** [ipcjs/bilibili-helper#101]
今天才用上这个插件，但是遇到了无法连接服务器的问题，原因好像是www.biliplus.com这个地址访问有问题，可以想办法搞个vpn只要能访问www.biliplus.com就行了，我这里是自己搭建的ss

**Comment by Nial4** [comment]
嗯，的确，我把biliplus.com添加到规则里走SS就好了

**Comment by ZeroKingHao** [comment]
我走的全局也进不去biliplus貌似是挂了
