### ISSUE TITLE
部分番剧过于卡顿

### ISSUE THREAD

**Issue by 1943330611** [ipcjs/bilibili-helper#1013]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by 1943330611** [comment]
例如进击的巨人第三季part2和普通攻击是全体二连击

**Comment by JasonKhew96** [comment]
见 https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/README.md#%E6%92%AD%E6%94%BE%E5%8D%A1%E9%A1%BF
