### ISSUE TITLE
区域限制解除失效了 没有拉取视频的动作

### ISSUE THREAD

**Issue by saddit** [ipcjs/bilibili-helper#1014]
![image](https://user-images.githubusercontent.com/55338151/176889986-e3f7ba19-d8aa-48ae-be0b-cd6ecf0491e9.png)
没有拉取的消息了 失效了

_Originally posted by @838239178 in https://github.com/ipcjs/bilibili-helper/issues/1000#issuecomment-1172267385_

**Comment by valllwj** [comment]
我今天也是这样，除了点过追番的能进，从番剧出差那的都跳不过去了

**Comment by hihopkc** [comment]
我也是

**Comment by hihopkc** [comment]
可能今天7.1

**Comment by JasonKhew96** [comment]
可能是 biliplus 爆炸了，建议 md 页面进去

**Comment by BYSora** [comment]
现在从出差的动态页进去的视频地址前缀是BV，要ss前缀的才能解析跳转。我的解决方法是点进番剧评论区，从发过评论的账号一个个点进他们的空间，找到他们的追番，如果有的话就能从这个追番的入口进去。然后你自己顺手点个追番，方便自己下次进去

**Comment by saddit** [comment]
> 现在从出差的动态页进去的视频地址前缀是BV，要ss前缀的才能解析跳转。我的解决方法是点进番剧评论区，从发过评论的账号一个个点进他们的空间，找到他们的追番，如果有的话就能从这个追番的入口进去。然后你自己顺手点个追番，方便自己下次进去

啊这，以后都要这样了吗

**Comment by dizzyauto** [comment]
> 现在从出差的动态页进去的视频地址前缀是BV，要ss前缀的才能解析跳转。我的解决方法是点进番剧评论区，从发过评论的账号一个个点进他们的空间，找到他们的追番，如果有的话就能从这个追番的入口进去。然后你自己顺手点个追番，方便自己下次进去

不至于，下个港澳台的b站里面就能点追番了，还找用户点。。

**Comment by Tiger1998** [comment]
我也一样，不自动跳转了

**Comment by 11Ye** [comment]
> > 现在从出差的动态页进去的视频地址前缀是BV，要ss前缀的才能解析跳转。我的解决方法是点进番剧评论区，从发过评论的账号一个个点进他们的空间，找到他们的追番，如果有的话就能从这个追番的入口进去。然后你自己顺手点个追番，方便自己下次进去
> 
> 不至于，下个港澳台的b站里面就能点追番了，还找用户点。。

看上去网页端只能这么操作了

**Comment by 11Ye** [comment]
从greasyfork的反馈中看到一条有帮助的评论：
[链接](https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6/discussions/140178)
解决无法拉取的一个简易方法：点开“视频不见了？”页面之后，在地址栏的地址尾部随意打几个字符，跳转，就可以拉取了。

**Comment by JasonKhew96** [comment]
~~那就是 浏览器/Tampermonkey/Violentmonkey 的问题了，更新更坏了~~

看了一眼，大概知道问题所在，我修修

**Comment by JasonKhew96** [comment]
破案了，因为页面是热加载的，油猴脚本运行的时候，没有检测到 "视频不见了"，所以罢工了

**Comment by JasonKhew96** [comment]
@ipcjs 我不会修...，怕影响到普通视频

**Comment by ipcjs** [comment]
从关注里面点进去就没问题，都不点追番的吗🥲

**Comment by ipcjs** [comment]
直接跳转应该没影响吧，有影响再说喽🤔
https://github.com/ipcjs/bilibili-helper/commit/0c106c9d2a4d794c0bc1e3ac3ffe2913d409dca7

**Comment by saddit** [comment]
> 直接跳转应该没影响吧，有影响再说喽🤔
> 
> https://github.com/ipcjs/bilibili-helper/commit/0c106c9d2a4d794c0bc1e3ac3ffe2913d409dca7

修一修吧 求求了

**Comment by JasonKhew96** [comment]
> > 直接跳转应该没影响吧，有影响再说喽thinking
> > [0c106c9](https://github.com/ipcjs/bilibili-helper/commit/0c106c9d2a4d794c0bc1e3ac3ffe2913d409dca7)
> 
> 修一修吧 求求了

亲测能用，你自己设置里 检查更新

**Comment by saddit** [comment]
已经修复了啦
