### ISSUE TITLE
有关于iOS用户的一些问题

### ISSUE THREAD

**Issue by 06185413** [ipcjs/bilibili-helper#1016]
好！请问考虑支持Safari浏览器吗，iOS现在可以用油猴了但浏览器加在扩展后没有小星球图标，目前问题可以解决吗，感谢！

**Comment by saddit** [comment]
我买了个油猴插件 结果这个脚本用不了 没法配置代理服务器地址 每次设置完点开又是空的

Edit：可以用了 重开了一下浏览器

**Comment by ipcjs** [comment]
@838239178 那你找卖家去呀😅

**Comment by wenshunb** [comment]
@06185413 确认脚本已加载的情况下（有时iCloud会删本地文件），在桌面版/移动版网站切换+刷新一下吧。设置图标可以正常显示的。
![fcab478de56081fbf5366df51427d33](https://user-images.githubusercontent.com/8833466/178183849-7d322238-0941-43bb-bc65-a3e13af0025b.jpg)

**Comment by Pyramind-RJ** [comment]
我用userscripts（商店搜得到，类似油猴的脚本管理软件）加载的脚本，可以使用，但是港澳台番剧点进去都是只有360p，换过代理服务器

**Comment by Pyramind-RJ** [comment]
> 我用userscripts（商店搜得到，类似油猴的脚本管理软件）加载的脚本，可以使用，但是港澳台番剧点进去都是只有360p，换过代理服务器

IPhone6s safari iOS:15.4.1

**Comment by 06185413** [comment]
> 

我是Xr的iOS:15.5，您说的这个软件我也试了不过不知道为什么还是不行，原来用的是stay2，其他的插件都可以正常使用但是这个小图标就出不了就挺有意思的。

**Comment by liuluyu6** [comment]
> @06185413 确认脚本已加载的情况下（有时iCloud会删本地文件），在桌面版/移动版网站切换+刷新一下吧。设置图标可以正常显示的。
> ![fcab478de56081fbf5366df51427d33](https://user-images.githubusercontent.com/8833466/178183849-7d322238-0941-43bb-bc65-a3e13af0025b.jpg)

您好，我用的最新ipad os 15.5 按教程都设置好了，现在能进到番剧播放页面，但会显示：

拉取视频地址失败

原因: {"code":-10403,"message":"抱歉您所在地区不可观看！"}

而且电脑上我可以点账号授权，ipad点了就关闭设置页面了没其他反应，目前就卡在这两个问题看不了

**Comment by wenshunb** [comment]
@liuluyu6 第一个问题是不是服务器的问题，换几个试试？第二个我没碰到过，我记得和电脑上类似，跳转到mcbbs之后关闭窗口。要确认的话可能只有连电脑看log了。
@06185413 我又试了几次好像有时是刷不出设置图标。不太熟悉js大概看了一下console。可能和Safari下`DOMContentLoaded`有关，反正我是解决不了。除了多刷新几次只能关了设备再开吧。我在iPad上试了几次，好像开机之后第一次总能加载出设置图标，不知道是不是偶然。
```
warn:
"解除B站区域限制 interactive 加载时机不太对, 不能保证正常工作

1. 尝试刷新页面, 重载脚本
2. 若依然出现该提示, 请尝试'硬性重新加载'(快捷键一般为ctrl+f5)
3. 若还是出现该提示, 请尝试关闭再重新打开该页面
4. 若反复出现该提示, 那也没其他办法了_(:3」∠)_
"
```
