### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by logc242** [ipcjs/bilibili-helper#1021]
@ipcjs

## 描述
<## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}>

- 问题网址：https://www.bilibili.com/bangumi/play/ss42122/?spm_id_from=333.999.0.0

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss42122/?spm_id_from=333.999.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"LDEG-V","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=42122
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ss42122 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?cid=761836079&qn=116&type=&otype=json&fourk=1&bvid=BV1ja411X7Ba&ep_id=526802&fnver=0&fnval=80&session=30fee17126d03487614a91b2c363e5cd&module=bangumi&area=&access_key={{access_key}}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=undefined&cid=761836079&bvid=BV1ja411X7Ba&qn=116&type=&otype=json&ep_id=526802&fourk=1&fnver=0&fnval=80&session=c0ae6f045cb4dcd921eca244b63d50e4&module=bangumi&balh_ajax=1&area=&access_key=7b35b8e6d6517553ad9574341d15fb71
debug: /x/web-interface/nav {"uname":"LDEG-V","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

1. 浏览器版本：Chrome 103.0.5060.114
2. 国家/地区：香港

**Comment by JasonKhew96** [comment]
这解析服务器跑路了，换一个

**Comment by logc242** [comment]
> 这解析服务器跑路了，换一个

可以分享一个吗，感谢

**Comment by thanksshu** [comment]
可以看看[这个](https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8)

**Comment by ChangPtR** [comment]
> 可以看看[这个](https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8)

都不好使呀，我试了好几个都报错
```
## 拉取视频地址失败
原因: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
```
