### ISSUE TITLE
解析服务器能否不强制https

### ISSUE THREAD

**Issue by Leanisme** [ipcjs/bilibili-helper#1023]
我在本地docker搭建了一个反代服务，往插件里填ip的时候发现总是自动补全为https地址，本地代理也不好申请ssl证书

**Comment by Leanisme** [comment]
算了自签名证书也不是很难😂

**Comment by AisukaYuki** [comment]
本地为什么不直接走规则代理？#915

**Comment by Leanisme** [comment]
哈哈，瞎折腾的。我这边机场比较卡，如果用小猫咪的规则代理会使得全部流量都走代理，刷B站体验很差。用脚本只有港澳台番剧跳转会慢一点。

**Comment by Leanisme** [comment]
> 本地为什么不直接走规则代理？#915

哈哈，瞎折腾的。我这边机场比较卡，如果用小猫咪的规则代理会使得全部流量都走代理，刷B站体验很差。用脚本就只有港澳台番剧跳转会慢一点。

**Comment by AisukaYuki** [comment]
> > 本地为什么不直接走规则代理？#915
> 
> 哈哈，瞎折腾的。我这边机场比较卡，如果用小猫咪的规则代理会使得全部流量都走代理，刷B站体验很差。用脚本就只有港澳台番剧跳转会慢一点。

clash 只要代理api.bilibili.com就好了啊 upos缓冲直接放行直连

**Comment by Leanisme** [comment]
> 

哦还可以这样的，我去试试，谢谢你
