### ISSUE TITLE
被拉进了黑名单

### ISSUE THREAD

**Issue by CX009** [ipcjs/bilibili-helper#1024]
脚本问题：@ipcjs

## 描述

被拉进了黑名单，好像在脚本使用初期不懂操作遂询问过路人（
uid：107636596
麻烦佬帮忙查看一下并请您告知一下解决方法
谢谢您
- 问题网址：

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss41483/?spm_id_from=333.999.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"希xixixixi酱_","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=41483
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?cid=570481957&qn=116&type=&otype=json&fourk=1&bvid=BV1794y1Z7kM&ep_id=478568&fnver=0&fnval=80&session=02b37ec9ad0fee32fa1ab535a745955e&module=bangumi&area=hk&access_key={{access_key}}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?cid=570481957&qn=116&type=&otype=json&fourk=1&bvid=BV1794y1Z7kM&ep_id=478568&fnver=0&fnval=80&session=02b37ec9ad0fee32fa1ab535a745955e&module=bangumi&area=&access_key=991c2a2f7116f7953c2bf41731182e71
debug: /x/web-interface/nav {"uname":"希xixixixi酱_","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?cid=760896265&qn=116&type=&otype=json&fourk=1&bvid=BV1Y3411w7UU&ep_id=479420&fnver=0&fnval=80&session=94de51454800826c6e866e6b3a840e5e&module=bangumi&area=hk&access_key=991c2a2f7116f7953c2bf41731182e71
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?cid=760896265&qn=116&type=&otype=json&fourk=1&bvid=BV1Y3411w7UU&ep_id=479420&fnver=0&fnval=80&session=94de51454800826c6e866e6b3a840e5e&module=bangumi&area=&access_key=991c2a2f7116f7953c2bf41731182e71
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=570481957&bvid=BV1794y1Z7kM&qn=116&type=&otype=json&ep_id=478568&fourk=1&fnver=0&fnval=80&session=25d07fc7fc2eebb2abb5965874ca8758&module=bangumi&balh_ajax=1&area=hk&access_key=991c2a2f7116f7953c2bf41731182e71
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=undefined&cid=570481957&bvid=BV1794y1Z7kM&qn=116&type=&otype=json&ep_id=478568&fourk=1&fnver=0&fnval=80&session=25d07fc7fc2eebb2abb5965874ca8758&module=bangumi&balh_ajax=1&area=&access_key=991c2a2f7116f7953c2bf41731182e71
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?cid=570481957&qn=116&type=&otype=json&fourk=1&bvid=BV1794y1Z7kM&ep_id=478568&fnver=0&fnval=80&session=02b37ec9ad0fee32fa1ab535a745955e&module=bangumi&area=tw&access_key=991c2a2f7116f7953c2bf41731182e71
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=undefined&cid=570481957&bvid=BV1794y1Z7kM&qn=116&type=&otype=json&ep_id=478568&fourk=1&fnver=0&fnval=80&session=25d07fc7fc2eebb2abb5965874ca8758&module=bangumi&balh_ajax=1&area=tw&access_key=991c2a2f7116f7953c2bf41731182e71
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?cid=760896265&qn=116&type=&otype=json&fourk=1&bvid=BV1Y3411w7UU&ep_id=479420&fnver=0&fnval=80&session=94de51454800826c6e866e6b3a840e5e&module=bangumi&area=tw&access_key=991c2a2f7116f7953c2bf41731182e71
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=760896265&bvid=BV1Y3411w7UU&qn=116&type=&otype=json&ep_id=479420&fourk=1&fnver=0&fnval=80&session=86fb977980fb30f6e570ccd3683c1451&module=bangumi&balh_ajax=1&area=hk&access_key=991c2a2f7116f7953c2bf41731182e71
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=undefined&cid=760896265&bvid=BV1Y3411w7UU&qn=116&type=&otype=json&ep_id=479420&fourk=1&fnver=0&fnval=80&session=86fb977980fb30f6e570ccd3683c1451&module=bangumi&balh_ajax=1&area=&access_key=991c2a2f7116f7953c2bf41731182e71
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=undefined&cid=760896265&bvid=BV1Y3411w7UU&qn=116&type=&otype=json&ep_id=479420&fourk=1&fnver=0&fnval=80&session=86fb977980fb30f6e570ccd3683c1451&module=bangumi&balh_ajax=1&area=tw&access_key=991c2a2f7116f7953c2bf41731182e71
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：edge
2. 国家/地区：

**Comment by aoesun** [comment]
我也被拉入黑名单了，不知道为什么

**Comment by bilibili2233a** [comment]
来tg群找管理

**Comment by bilibili2233a** [comment]
> 我也被拉入黑名单了，不知道为什么

去tg群找管理

**Comment by bilibili2233a** [comment]
> 来tg群找管理

重新看了一下，不是晚上7点就解禁了？

**Comment by bilibili2233a** [comment]
重新看了一遍时间：4天前，回复错了

**Comment by xiaopebaka** [comment]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep508404?from_spmid=666.25.episode.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: wcs flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"-迷-子-","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep508404 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=641107054&cid=738021601&qn=120&fnver=0&fnval=4048&fourk=1&ep_id=508404&session=c95a33b8f8298133cb8e8f226cbe1e10&module=bangumi&area=&access_key={{access_key}}
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=641107054&cid=738021601&qn=120&fnver=0&fnval=4048&fourk=1&ep_id=508404&session=c95a33b8f8298133cb8e8f226cbe1e10&module=bangumi&area=hk&access_key=04634901b344e9a03adf9624e6d13f71
debug: fetch https://api.bilibili.com/x/web-interface/search/default {"params":{},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: /x/web-interface/nav {"uname":"-迷-子-","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=686101917235937300&article_offset=681262477040681000 {"params":{"alltype_offset":0,"video_offset":"686101917235937300","article_offset":"681262477040681000"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/web-interface/pcdn/v1 {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=686101917235937300&article_offset=681262477040681000 {"params":{"alltype_offset":0,"video_offset":"686101917235937300","article_offset":"681262477040681000"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62


我好像也被拉了

**Comment by AisukaYuki** [comment]
> debug: atRun: -1, loading debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep508404?from_spmid=666.25.episode.0 debug: window.**playinfo** debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true} info: mode: default blocked_vip: server: https://www.biliplus.com upos_server: wcs flv_prefer_ws: remove_pre_ad: generate_sub: Y enable_in_av: readyState: loading isLogin: true isLoginBiliBili: true debug: atRun: 0, interactive debug: atRun: 1, interactive debug: set jQuery -> function(a,b){return new e.fn.init(a,b,h)} debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)} debug: /x/web-interface/nav {"uname":"-迷-子-","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false} debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"} debug: setAreaLimitSeason ep508404 true debug: season_type: 1 info: player msg: 从自定义服务器拉取视频地址中... info: player msg: 使用首选代理服务器拉取视频地址... debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)} debug: ajax: [https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=641107054&cid=738021601&qn=120&fnver=0&fnval=4048&fourk=1&ep_id=508404&session=c95a33b8f8298133cb8e8f226cbe1e10&module=bangumi&area=&access_key={{access_key}}](https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=641107054&cid=738021601&qn=120&fnver=0&fnval=4048&fourk=1&ep_id=508404&session=c95a33b8f8298133cb8e8f226cbe1e10&module=bangumi&area=&access_key=%7B%7Baccess_key%7D%7D) info: player msg: 使用香港代理服务器拉取视频地址... debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)} debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=641107054&cid=738021601&qn=120&fnver=0&fnval=4048&fourk=1&ep_id=508404&session=c95a33b8f8298133cb8e8f226cbe1e10&module=bangumi&area=hk&access_key=04634901b344e9a03adf9624e6d13f71 debug: fetch https://api.bilibili.com/x/web-interface/search/default {"params":{},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"signal":{}} debug: fetch https://api.bilibili.com/x/web-show/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956"},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: /x/web-interface/nav {"uname":"-迷-子-","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false} debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=686101917235937300&article_offset=681262477040681000 {"params":{"alltype_offset":0,"video_offset":"686101917235937300","article_offset":"681262477040681000"},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: fetch https://api.bilibili.com/x/web-interface/pcdn/v1 {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=686101917235937300&article_offset=681262477040681000 {"params":{"alltype_offset":0,"video_offset":"686101917235937300","article_offset":"681262477040681000"},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, _/_"},"credentials":"include","signal":{}} debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62
> 
> 我好像也被拉了

设置都没填对，换服务。
