### ISSUE TITLE
解除地区限制: 无法搜索到仅限港澳台的番剧

### ISSUE THREAD

**Issue by ChangPtR** [ipcjs/bilibili-helper#1025]
如题，打开b站之后搜索不到港澳台的番剧，如果有播放链接倒是能解析。

**Comment by JasonKhew96** [comment]
@ChangPtR 
这脚本不处理搜索，请用这个:

https://github.com/gamekingv/bilibili-oversea-search/blob/main/bilibili-oversea-search_new.user.js

安装点这个:

https://github.com/gamekingv/bilibili-oversea-search/raw/main/bilibili-oversea-search_new.user.js

**Comment by ChangPtR** [comment]
明白了，谢谢
