### ISSUE TITLE
进击的巨人第一季无法观看

### ISSUE THREAD

**Issue by Mlijiatu** [ipcjs/bilibili-helper#1029]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss37757/?spm_id_from=333.999.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=543778525&cid=285277818&qn=112&fnver=0&fnval=4048&fourk=1&ep_id=379656&session=e97fbaf7e78efbd576ef3d5ec8630d8e&module=bangumi&area=hk&access_key={{access_key}}
debug: /x/web-interface/nav {"uname":"0吃瓜群众01","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: fetch https://api.bilibili.com/x/web-interface/search/default {"params":{},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: /x/web-interface/nav {"uname":"0吃瓜群众01","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=687436170300227600&article_offset=0 {"params":{"alltype_offset":0,"video_offset":"687436170300227600","article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/web-interface/pcdn/v1 {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=687436170300227600&article_offset=0 {"params":{"alltype_offset":0,"video_offset":"687436170300227600","article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: atRun: 2, complete
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}

**Comment by JasonKhew96** [comment]
https://github.com/ipcjs/bilibili-helper/issues/906
