### ISSUE TITLE
提示拉取视频地址失效，原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

### ISSUE THREAD

**Issue by hmylol** [ipcjs/bilibili-helper#1039]
脚本问题：@ipcjs

## 描述
提示拉取视频地址失效，原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}
前几个月还是能正常使用的，更新了脚本切换了几个代理都无法打开视频

- 问题网址：https://www.bilibili.com/bangumi/play/ss42082?spm_id_from=666.4.top_right_bar_window_history.content.click

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss42082?spm_id_from=666.4.top_right_bar_window_history.content.click
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss42082?spm_id_from=666.4.top_right_bar_window_history.content.click
debug: __playinfo__ get
debug: window.__playinfo__ 
debug: __playinfo__ get
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=42082
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=42082
debug: atRun: 1, interactive
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"一人一伞一街角","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"一人一伞一街角","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://afdian.net/@qmswf/?cid=764280550&qn=120&type=&otype=json&fourk=1&bvid=BV1of4y1o7pc&ep_id=527214&fnver=0&fnval=80&session=9295c9785b25eeeb339ac0410bebac8b&module=bangumi&access_key={{access_key}}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://afdian.net/@qmswf/?cid=764280550&qn=120&type=&otype=json&fourk=1&bvid=BV1of4y1o7pc&ep_id=527214&fnver=0&fnval=80&session=9295c9785b25eeeb339ac0410bebac8b&module=bangumi&access_key=485c98dcd46afa1330c16811f7e0ba81
debug: atRun: 2, complete
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /pgc/player/web/playurl origin block: false {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://afdian.net/@qmswf/?avid=undefined&cid=764280550&bvid=BV1of4y1o7pc&qn=120&type=&otype=json&ep_id=527214&fourk=1&fnver=0&fnval=80&session=329a8be7c60b0cef161bd96617293110&module=bangumi&balh_ajax=1&access_key=485c98dcd46afa1330c16811f7e0ba81
debug: /x/web-interface/nav {"uname":"一人一伞一街角","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"一人一伞一街角","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 12_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by JasonKhew96** [comment]
明显是你解析服务器地址填错

**Comment by hmylol** [comment]
> 

啊，是我的问题，是和翻墙代理冲突了，当时我没反应过来，我一个一个服务器的试都没成功，正确地址我都填过，然后没效果就乱试，结果只是我的翻墙没关，不是脚本和服务器的问题，是我的问题😂
