### ISSUE TITLE
被拉黑名单了，求大佬帮我解封拜托了

### ISSUE THREAD

**Issue by ZJR-max** [ipcjs/bilibili-helper#1044]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ZJR-max** [comment]
UID8531035

**Comment by bilibili2233a** [comment]
黑名单了别找油猴，解析服务器的uban指令拔了，解不了



新封锁
UID: 8531035
用户空间: 亚悲筋华猪肉人
原因: 请问是油猴吗？
来源: 
Text: 请问油猴要怎么看啊[笑哭]
Location: https://b23.tv/av247401289#reply4376808045

Text: 请问是油猴吗？
Location: https://b23.tv/av247401289#reply4376777027

Text: 怎么看啊现在？油猴只能看到黑屏
Location: https://b23.tv/av586585312#reply4080242761

**Comment by bilibili2233a** [comment]
唯一的解决方法：换号或者注销重开

**Comment by ZJR-max** [comment]
注销什么？不是有什么TG群可以给人解封的吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ipcjs/bilibili-helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ipcjs/bilibili-helper] 被拉黑名单了，求大佬帮我解封拜托了 (Issue #1044)





 
唯一的解决方法：换号或者注销重开

**Comment by ZJR-max** [comment]
> 黑名单了别找油猴，解析服务器的uban指令拔了，解不了
> 
> 新封锁 UID: 8531035 用户空间: 亚悲筋华猪肉人 原因: 请问是油猴吗？ 来源: Text: 请问油猴要怎么看啊[笑哭] Location: https://b23.tv/av247401289#reply4376808045
> 
> Text: 请问是油猴吗？ Location: https://b23.tv/av247401289#reply4376777027
> 
> Text: 怎么看啊现在？油猴只能看到黑屏 Location: https://b23.tv/av586585312#reply4080242761

是油猴，一开始原来的那些个脚本用不了就问别人怎么翻的，结果一个都不回我，也不告诉我会被封

> 黑名单了别找油猴，解析服务器的uban指令拔了，解不了
> 
> 新封锁 UID: 8531035 用户空间: 亚悲筋华猪肉人 原因: 请问是油猴吗？ 来源: Text: 请问油猴要怎么看啊[笑哭] Location: https://b23.tv/av247401289#reply4376808045
> 
> Text: 请问是油猴吗？ Location: https://b23.tv/av247401289#reply4376777027
> 
> Text: 怎么看啊现在？油猴只能看到黑屏 Location: https://b23.tv/av586585312#reply4080242761

是油猴，一开始原来的那些个脚本用不了就问别人怎么翻的，结果一个都不回我，也不告诉我会被封

**Comment by BraveSail** [comment]
> 

https://user-images.githubusercontent.com/49320262/185947251-20b933ee-8d0d-4dab-ae5b-f3c3a05df2a2.mp4

**Comment by bilibili2233a** [comment]
以前可以，现在不行了，Uban指令拨了
就算我现在给你tg群的链接：https://t.me/biliroaming_chat  ，也解不了黑名单

**Comment by ZJR-max** [comment]
注销是什么意思啊？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ipcjs/bilibili-helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ipcjs/bilibili-helper] 被拉黑名单了，求大佬帮我解封拜托了 (Issue #1044)





 
以前可以，现在不行了，Uban指令拨了
 就算我现在给你tg群的链接：https://t.me/biliroaming_chat，也解不了黑名单

**Comment by BraveSail** [comment]
> 注销是什么意思啊？

注销是什么意思是怎么回事呢？注销相信大家都很熟悉，但是是什么意思是怎么回事呢？下面就让小编带大家一起了解吧。 

注销是什么意思，其实就是是什么意思了。那么注销为什么会是什么意思，相信大家都很好奇是怎么回事。大家可能会感到很惊讶，注销怎么会是什么意思呢？但事实就是这样，小编也感到非常惊讶。那么这就是关于注销是什么意思的事情了，大家有没有觉得很神奇呢？

看了今天的内容，大家有什么想法呢？欢迎在评论区告诉小编一起讨论哦。

**Comment by ZJR-max** [comment]
是退出B站账号还是怎么样啊？试过了啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ipcjs/bilibili-helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 晚上10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ipcjs/bilibili-helper] 被拉黑名单了，求大佬帮我解封拜托了 (Issue #1044)





  
注销是什么意思啊？
  
注销是什么意思是怎么回事呢？注销相信大家都很熟悉，但是是什么意思是怎么回事呢？下面就让小编带大家一起了解吧。
 
注销是什么意思，其实就是是什么意思了。那么注销为什么会是什么意思，相信大家都很好奇是怎么回事。大家可能会感到很惊讶，注销怎么会是什么意思呢？但事实就是这样，小编也感到非常惊讶。那么这就是关于注销是什么意思的事情了，大家有没有觉得很神奇呢？
 
看了今天的内容，大家有什么想法呢？欢迎在评论区告诉小编一起讨论哦。

**Comment by bilibili2233a** [comment]
没有小号，可以注册小号看
有小号就用小号
什么都没有的话，注销帐号重开新号

UID：8531035
昵称：亚悲筋华猪肉人
头像：http://i1.hdslb.com/bfs/face/f20dd2ebeeed1466e8158f29f5883cf88f3c0b72.jpg
硬币数：559.1
注册时间：UTC+8 2015-02-27 20:52:27
等级：LV6
现有经验：45704
空间跳转：https://space.bilibili.com/8531035

**Comment by ZJR-max** [comment]
这号舍不得注销啊，没别的办法吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 晚上11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ipcjs/bilibili-helper] 被拉黑名单了，求大佬帮我解封拜托了 (Issue #1044)





 
没有小号，可以注册小号看
 有小号就用小号
 什么都没有的话，注销帐号重开新号
 
UID：8531035
 昵称：亚悲筋华猪肉人
 头像：http://i1.hdslb.com/bfs/face/f20dd2ebeeed1466e8158f29f5883cf88f3c0b72.jpg
 硬币数：559.1
 注册时间：UTC+8 2015-02-27 20:52:27
 等级：LV6
 现有经验：45704
 空间跳转：https://space.bilibili.com/8531035

**Comment by bilibili2233a** [comment]
那你还是直接用clash或者v2ary代理港澳台节点，直接就能看港澳台的番剧，还不受黑名单限制
东南亚的bilibili网页版： bilibili.tv ，代理：新加坡、泰国

有能力的话：自建服务器，还不受气
自建解析服务器教程：
https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by ZJR-max** [comment]
……请问有视频教程吗大佬？字都能看懂连在一起不太能理解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ipcjs/bilibili-helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ipcjs/bilibili-helper] 被拉黑名单了，求大佬帮我解封拜托了 (Issue #1044)





 
那你还是直接用clash或者v2ary代理港澳台节点，直接就能看港澳台的番剧，还不受黑名单限制
 东南亚的bilibili网页版： bilibili.tv ，代理：新加坡、泰国
 
有能力的话：自建服务器，还不受气
 自建解析服务器教程：
 https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by bilibili2233a** [comment]
![Screenshot_20220822_232119_com.github.android.jpg](https://user-images.githubusercontent.com/99982054/185957995-ec847646-dc16-4968-8612-9a20bf208de4.jpg)哪里字粘在一起了？

**Comment by bilibili2233a** [comment]
简单来说：
方法一（最简单）：用代理：港澳台限定的番剧（香港、澳门、台湾节点），东南亚的番剧：不在主站bilibili.com，而是在bilibili.tv，所以用（新加坡、泰国这些东南亚节点才可以）（代理应用：clash 、v2ray）

方法二：自建解析服务器（有能力的话）

https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by bilibili2233a** [comment]
视频教程：没有
如果是自建服务器，哔哩漫游tg群有手把手教程

**Comment by ZJR-max** [comment]
……自建服务器我下载了几个没有EXE文件的东西后愣是看不懂该干嘛……请问代理的办法详细是要怎么办呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 晚上11:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ipcjs/bilibili-helper] 被拉黑名单了，求大佬帮我解封拜托了 (Issue #1044)





 
简单来说：
 方法一（最简单）：用代理：港澳台限定的番剧（香港、澳门、台湾节点），东南亚的番剧：不在主站bilibili.com，而是在bilibili.tv，所以用（新加坡、泰国这些东南亚节点才可以）（代理应用：clash 、v2ray）
 
方法二：自建解析服务器（有能力的话）
 
https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by bilibili2233a** [comment]
你还是用代理应用好了，

clash for window的使用文档：
https://docs.cfw.lbyczf.com/contents/quickstart.html#启动

**Comment by ZJR-max** [comment]
Clash下载完了，可是URL啥的我没有啊……该怎么才能代理呀？
------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 晚上11:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ipcjs/bilibili-helper] 被拉黑名单了，求大佬帮我解封拜托了 (Issue #1044)





 
简单来说：
 方法一（最简单）：用代理：港澳台限定的番剧（香港、澳门、台湾节点），东南亚的番剧：不在主站bilibili.com，而是在bilibili.tv，所以用（新加坡、泰国这些东南亚节点才可以）（代理应用：clash 、v2ray）
 
方法二：自建解析服务器（有能力的话）
 
https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by ZJR-max** [comment]
> 视频教程：没有 如果是自建服务器，哔哩漫游tg群有手把手教程

我下好了Clash了，可是URL或者港澳台节点什么的要咋弄啊？
