### ISSUE TITLE
问下，目前被封大会员还能用吗

### ISSUE THREAD

**Issue by logc242** [ipcjs/bilibili-helper#1045]
我账号无缘无故的显示高危，大会员功能封了，找客服半天没啥用，脚本被永封的大会员要登录代理服务器，但biliplus被屏蔽了，问下还能用吗？

**Comment by ipcjs** [comment]
这个功能基本上没维护了，应该不能

logc242 ***@***.***> 于2022年8月21日周日 19:17写道：
