### ISSUE TITLE
放个假，刚回来就进黑名单了，能让我死个明白吗？

### ISSUE THREAD

**Issue by sunjunnan79** [ipcjs/bilibili-helper#1046]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by sunjunnan79** [comment]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.26 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep653791?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=653791
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"可惜不过","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep653791 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?cid=784925681&qn=120&type=&otype=json&fourk=1&bvid=BV1Pa411T7wM&ep_id=653791&fnver=0&fnval=80&session=c654764e978820f8aa4f1a056505c443&module=bangumi&area=hk&access_key={{access_key}}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?cid=784925681&qn=120&type=&otype=json&fourk=1&bvid=BV1Pa411T7wM&ep_id=653791&fnver=0&fnval=80&session=c654764e978820f8aa4f1a056505c443&module=bangumi&area=&access_key=4f52bcce9c858c2ea185328c7c3d1381
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?cid=784925681&qn=120&type=&otype=json&fourk=1&bvid=BV1Pa411T7wM&ep_id=653791&fnver=0&fnval=80&session=c654764e978820f8aa4f1a056505c443&module=bangumi&area=tw&access_key=4f52bcce9c858c2ea185328c7c3d1381
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=undefined&cid=784925681&bvid=BV1Pa411T7wM&qn=120&type=&otype=json&ep_id=653791&fourk=1&fnver=0&fnval=80&session=e90f8301c9a7f58b97b207b3f413c664&module=bangumi&balh_ajax=1&area=hk&access_key=4f52bcce9c858c2ea185328c7c3d1381
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=784925681&bvid=BV1Pa411T7wM&qn=120&type=&otype=json&ep_id=653791&fourk=1&fnver=0&fnval=80&session=e90f8301c9a7f58b97b207b3f413c664&module=bangumi&balh_ajax=1&area=&access_key=4f52bcce9c858c2ea185328c7c3d1381
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://atri.ink/pgc/player/web/playurl?avid=undefined&cid=784925681&bvid=BV1Pa411T7wM&qn=120&type=&otype=json&ep_id=653791&fourk=1&fnver=0&fnval=80&session=e90f8301c9a7f58b97b207b3f413c664&module=bangumi&balh_ajax=1&area=tw&access_key=4f52bcce9c858c2ea185328c7c3d1381
debug: /x/web-interface/nav {"uname":"可惜不过","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Comment by sunjunnan79** [comment]
UID671120553

**Comment by bilibili2233a** [comment]
![IMG_20220824_145455_160.png](https://user-images.githubusercontent.com/99982054/186351132-3cf2e2ff-3589-4ce6-9058-511341d3fade.png)

**Comment by skytianle** [comment]
你好，请问一下，这个账号的个人空间的公告是啥啊，看不懂欸

**Comment by sunjunnan79** [comment]
原来是这样啊，应该是复制的时候复制错了，本来应该是daringintheFRANXX的。

**Comment by sunjunnan79** [comment]
这还有办法解吗

**Comment by sunjunnan79** [comment]
本来是想提醒自己补番的，这下把号贴进去了

**Comment by WindSakura** [comment]
![image](https://user-images.githubusercontent.com/64851207/186886758-dd377d6c-334b-4394-91c5-3cc989c64428.png)
“啥也没干”
