### ISSUE TITLE
提示“error:[object XMLHttpRequest]”是什么情况

### ISSUE THREAD

**Issue by Willow871** [ipcjs/bilibili-helper#1049]
![QQ截图20220903152113](https://user-images.githubusercontent.com/112804842/188308840-e300ba98-5ea5-4f0c-b50f-62ede9ab6830.png)

脚本问题：@ipcjs

## 描述

- 问题网址：所有港澳台番剧

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Cent Browser版本 4.3.9.248（正式版本） （32 位） (Chromium 86.0.4240.198)
2. 国家/地区：

**Comment by JasonKhew96** [comment]
建议别从 BV 号进 番剧，这个页面 锁区，得请求 `biliplus` 解析，但这个 数据 也不是 即时 的，而且 `biliplus` 炸的时候还没法用
推荐用 MD / EP / SS 页面

**Comment by pyb2000** [comment]
> 建议别从 BV 号进 番剧，这个页面 锁区，得请求 `biliplus` 解析，但这个 数据 也不是 即时 的，而且 `biliplus` 炸的时候还没法用 推荐用 MD / EP / SS 页面
> 
> Do not enter the BV from the BV, this page, lock, have to request biliplus parsing, but this, data, is not, immediately, and biliplus is not available when the explosion, recommend using MD/EP/SS Page

出差帐号动态里只能访问到BV号,请问如何获取番剧页面呢

**Comment by pyb2000** [comment]
> > 建议别从 BV 号进 番剧，这个页面 锁区，得请求 `biliplus` 解析，但这个 数据 也不是 即时 的，而且 `biliplus` 炸的时候还没法用 推荐用 MD / EP / SS 页面Do not enter the BV from the BV, this page, lock, have to request biliplus parsing, but this, data, is not, immediately, and biliplus is not available when the explosion, recommend using MD/EP/SS Page
> > Do not enter the BV from the BV, this page, lock, have to request biliplus parsing, but this, data, is not, immediately, and biliplus is not available when the explosion, recommend using MD/EP/SS Page不要从 BV 进入 BV，这个页面，锁，必须要求 biliplus 解析，但这个，数据，不是，立即，而 biliplus 是不可用的，爆炸时，建议使用 MD/EP/SS 页面
> 
> 出差帐号动态里只能访问到BV号,请问如何获取番剧页面呢
> 
> Business account dynamic can only access the BV number, how to get the play page

找到方法了,分享给大家
https://github.com/gamekingv/bilibili-oversea-search
