### ISSUE TITLE
各位用这个脚本有导致蓝屏吗

### ISSUE THREAD

**Issue by djjia** [ipcjs/bilibili-helper#1050]
外接显示器，typec转hdmi。以前一直正常使用，最近突然莫名其妙地只要看港澳台，页面跳转后就必定蓝屏，重新拔插hdmi线后恢复正常，切换其他集也有一定概率蓝屏。看不需要这个脚本的视频好像从来没出现过该情况。

**Comment by JasonKhew96** [comment]
有没有可能是你 硬解 有问题？

**Comment by djjia** [comment]
> 有没有可能是你 硬解 有问题？

似乎是独显直连的锅。。。不开独显直连好像就没问题了，很迷
