### ISSUE TITLE
简繁转换失效，勾选简繁转换后字幕不显示

### ISSUE THREAD

**Issue by a1156883061** [ipcjs/bilibili-helper#1051]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Microsoft Edge 105.0.1343.27
2. 国家/地区：中国

**Comment by JasonKhew96** [comment]
简繁转换的服务器关机了 cc @zjns

**Comment by zjns** [comment]
> 简单转换的服务器关机了 cc @zjns

跑路了，跑路了

**Comment by a1156883061** [comment]
如果不能使用了，建议把这个功能去掉或者做个回退机制
现在开启这个功能会导致没字幕
很难找到没字幕的原因是这个开关

**Comment by SF-AD** [comment]
我前几天发现了这个问题  今天抽空写了一个接口
具体使用 只需要替换下原脚本 第3091行 内容，将原内容替换为：
subtitle_url: `//video1.beijcloud.com/sub/t2cn/?sub_url=${origSubUrl}&sub_id=${encSubId}`,
接口写了缓存措施  第一次加载时间较慢 后续可以直接加载.
暂未对接口做任何限制措施，请各位合理使用，否则将会关闭.

**Comment by zjns** [comment]
> 我前几天发现了这个问题 今天抽空写了一个接口 具体使用 只需要替换下原脚本 第3091行 内容，将原内容替换为： subtitle_url: `//video1.beijcloud.com/sub/t2cn/?sub_url=${origSubUrl}&sub_id=${encSubId}`, 接口写了缓存措施 第一次加载时间较慢 后续可以直接加载. 暂未对接口做任何限制措施，请各位合理使用，否则将会关闭.

你可以看情况 PR 上去，不然我要撤回相关的 commit 了。

**Comment by ZZZ-zero** [comment]
> 我前几天发现了这个问题 今天抽空写了一个接口 具体使用 只需要替换下原脚本 第3091行 内容，将原内容替换为： subtitle_url: `//video1.beijcloud.com/sub/t2cn/?sub_url=${origSubUrl}&sub_id=${encSubId}`, 接口写了缓存措施 第一次加载时间较慢 后续可以直接加载. 暂未对接口做任何限制措施，请各位合理使用，否则将会关闭.

这个貌似也失效了

**Comment by ZZZ-zero** [comment]
我目前的方案是关闭插件自带的转换，使用了独立CC字幕转换插件：
[](https://greasyfork.org/zh-CN/scripts/431021)
（侵权删）

**Comment by ZZZ-zero** [comment]
我目前的方案是关闭插件自带的转换，使用了独立CC字幕转换插件：
[https://greasyfork.org/zh-CN/scripts/431021](url)
（侵权删）

**Comment by ZZZ-zero** [comment]
我目前的方案是关闭插件自带的转换，使用了独立CC字幕转换插件：
[https://greasyfork.org/zh-CN/scripts/431021-bilibili-b%E7%AB%99-%E7%95%AA%E5%89%A7cc%E5%AD%97%E5%B9%95%E8%87%AA%E5%8A%A8%E8%BD%AC%E6%8D%A2-%E7%BF%BB%E8%AF%91-%E7%B9%81%E4%BD%93%E8%BD%AC%E7%AE%80%E4%BD%93](url)
（侵权删）

**Comment by ZZZ-zero** [comment]
我目前的方案是关闭插件自带的转换，使用了独立CC字幕转换插件：
`https://greasyfork.org/zh-CN/scripts/431021`
（侵权删）

**Comment by JasonKhew96** [comment]
https://user-images.githubusercontent.com/29531167/190855158-8fabdf82-af78-4b8a-ba61-a243dd08a7e7.webm

**Comment by ZZZ-zero** [comment]
> 173963711-1-64.webm

？

**Comment by ZZZ-zero** [comment]
> 173963711-1-64.webm

我才发现我使用的代理服务器是您提供的，感谢感谢！

**Comment by SF-AD** [comment]
应该好了吧  之前https出问题了(

**Comment by ZZZ-zero** [comment]
> 应该好了吧 之前https出问题了(

现在确实好了，感谢
