### ISSUE TITLE
{"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}一直是这个错误

### ISSUE THREAD

**Issue by TheZhouGod** [ipcjs/bilibili-helper#1062]
info: mode: default blocked_vip: undefined server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: undefined generate_sub: Y enable_in_av: undefined readyState: loading isLogin: true isLoginBiliBili: true
userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=5dcad529-0368-49c9-9011-a253a291fb93:252 info: player msg: 从自定义服务器拉取视频地址中...
userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=5dcad529-0368-49c9-9011-a253a291fb93:252 info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
ep96703:1 Access to XMLHttpRequest at 'https://bili.azurstar.tk/pgc/player/web/playurl?cid=11234402&qn=80&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=77004bbcc459be49815f3b320c7d7d3e&module=bangumi&area=tw&access_key=7415953125b2ae6eb7938433c1f83991' from origin 'https://www.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=5dcad529-0368-49c9-9011-a253a291fb93:252 info: player msg: 使用首选代理服务器拉取视频地址...
bili.azurstar.tk/pgc/player/web/playurl?cid=11234402&qn=80&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=77004bbcc459be49815f3b320c7d7d3e&module=bangumi&area=tw&access_key=7415953125b2ae6eb7938433c1f83991:1          Failed to load resource: net::ERR_FAILED
ep96703:1 Access to XMLHttpRequest at 'https://bili.azurstar.tk/pgc/player/web/playurl?cid=11234402&qn=80&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=77004bbcc459be49815f3b320c7d7d3e&module=bangumi&area=&access_key=7415953125b2ae6eb7938433c1f83991' from origin 'https://www.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
bili.azurstar.tk/pgc/player/web/playurl?cid=11234402&qn=80&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=77004bbcc459be49815f3b320c7d7d3e&module=bangumi&area=&access_key=7415953125b2ae6eb7938433c1f83991:1          Failed to load resource: net::ERR_FAILED
userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=5dcad529-0368-49c9-9011-a253a291fb93:252 info: player msg: 从自定义服务器拉取视频地址中...
userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=5dcad529-0368-49c9-9011-a253a291fb93:252 info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
video.d78d6e85da752e622f857a963ae79be916fe4c01.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 1.0.0. Powered by jinkela-core 2.4.8.         \/            \/
12video.d78d6e85da752e622f857a963ae79be916fe4c01.js:1 premiereid: undefined
ep96703:1 Access to XMLHttpRequest at 'https://bili.azurstar.tk/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=80&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=60019e54fdc7d5d290b531660a3e9350&module=bangumi&balh_ajax=1&area=tw&access_key=7415953125b2ae6eb7938433c1f83991' from origin 'https://www.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=5dcad529-0368-49c9-9011-a253a291fb93:252 info: player msg: 使用首选代理服务器拉取视频地址...
bili.azurstar.tk/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=80&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=60019e54fdc7d5d290b531660a3e9350&module=bangumi&balh_ajax=1&area=tw&access_key=7415953125b2ae6eb7938433c1f83991:1          Failed to load resource: net::ERR_FAILED
ep96703:1 Access to XMLHttpRequest at 'https://bili.azurstar.tk/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=80&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=60019e54fdc7d5d290b531660a3e9350&module=bangumi&balh_ajax=1&area=&access_key=7415953125b2ae6eb7938433c1f83991' from origin 'https://www.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
bili.azurstar.tk/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=80&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=60019e54fdc7d5d290b531660a3e9350&module=bangumi&balh_ajax=1&area=&access_key=7415953125b2ae6eb7938433c1f83991:1          Failed to load resource: net::ERR_FAILED
ep96703:1          Failed to load resource: the server responded with a status of 404 ()
2DevTools 无法加载来源映射：无法加载 https://s1.hdslb.com/bfs/seed/jinkela/header-v2/international-header-3686edefbb1f66d8c6374e85a33db5d70f11451e-header.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE

换了代理服务器也没用不知道咋整

**Comment by ZZZ-zero** [comment]
服务器挂了，换个服务器

**Comment by JasonKhew96** [comment]
`{"code":-10403,"message":"服务器迁移,更换为 伊蕾娜.我爱你","ttl":1}`
