### ISSUE TITLE
哔哩哔哩出差页面打开是空白

### ISSUE THREAD

**Issue by genicse** [ipcjs/bilibili-helper#1063]
脚本问题：@ipcjs

## 描述
哔哩哔哩出差页面打开是空白，换了几个服务器了还是一样

- 问题网址：https://space.bilibili.com/11783021?from=search&seid=7516247474480473056&spm_id_from=333.337.0.0

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
 日志太长了，放不下
```
 
</details>

![2022-09-17](https://user-images.githubusercontent.com/109225385/190851265-63620ab9-1cd0-4a3d-a2d5-09773d02fdca.png)

## 其他

1. 浏览器版本：Microsoft Edge
版本 105.0.1343.33 (正式版本) (64 位)
2. 国家/地区：大陆

**Comment by ZZZ-zero** [comment]
试试这个
`https://api.qiu.moe`

**Comment by JasonKhew96** [comment]
与 解析服务器 无关，建议 尝试 换 浏览器 或者 油猴/爆猴
