### ISSUE TITLE
进了黑名单，怎么解除

### ISSUE THREAD

**Issue by tidyxiong** [ipcjs/bilibili-helper#1064]
## 拉取视频地址失败
原因: {"code":-403,"message":"黑名单"}
UID 2624341

**Comment by bilibili2233a** [comment]
新封锁
UID: 2624341
用户空间: Tidy熊
来源: https://b23.tv/ep520060
说明: 插件!

解封方法:无解[IMG_20220930_213006_809.jpg](https://user-images.githubusercontent.com/99982054/193280602-a39560a9-526a-4f28-a065-31164b00ec23.jpg)
