### ISSUE TITLE
账号授权页面，网页拒绝访问 8.3.1版

### ISSUE THREAD

**Issue by klayzhank** [ipcjs/bilibili-helper#1068]
打开视频报错：
## 拉取视频地址失败
原因: {"code":-101,"message":"帐号未登录","ttl":1}

去进行账号授权则：
账号授权页面，网页拒绝访问
![image](https://user-images.githubusercontent.com/106233293/192428064-1a26907f-392a-49d3-8a17-d5b35f7fbc7a.png)

日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28234736
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y generate_sub: Y enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=39044
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"Mikasa_kk","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"login":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":414712,"last_ep_index":"1","last_time":0},"real_price":"0","sponsor":0,"vip_info":{"due_date":1734019200000,"status":1,"type":2}}}
debug: setAreaLimitSeason 000 true
debug: fetch https://api.bilibili.com/x/web-interface/search/default {"params":{},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: season39044 {"code":0,"message":"success","result":{"actor":[{"actor":"大空直美","actor_id":0,"role":"賈希大人"},{"actor":"茅野愛衣","actor_id":0,"role":"店長"},{"actor":"日笠陽子","actor_id":0,"role":"房東"},{"actor":"花澤香菜","actor_id":0,"role":"桃樂希"},{"actor":"小松未可子","actor_id":0,"role":"薩露瓦"},{"actor":"上阪堇","actor_id":0,"role":"魔法少女"},{"actor":"小倉唯","actor_id":0,"role":"心"}],"alias":"ジャヒー様はくじけない,迦希大人不气馁","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"5613","bangumi_title":"賈希大人不氣餒！（僅限港澳台地區）","brief":"在魔界，地位僅次於魔王的迦希大人。\n被魔族們所畏懼，任性妄為揮霍無度，享受自己的人生之春天——本該是...","business_type":1,"coins":"0","copyright":"dujia","cover":"https://i0.hdslb.com/bfs/bangumi/image/5820400c449b3468864e01b53ed0264e9648c326.png","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"507450667","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f0bfc629c055d7fa816533b0e89b1cac280022f8.png","danmaku":"463004909","episode_id":"417169","episode_status":13,"episode_type":0,"from":"bangumi","index":"20","index_title":"迦希女王不會放棄！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-12-19 02:00:00.0"},{"av_id":"807209132","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/04759f5178fde4d9298987306c9799bb8d5e985e.png","danmaku":"458201505","episode_id":"417168","episode_status":13,"episode_type":0,"from":"bangumi","index":"19","index_title":"魔王陛下不留情!?","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-12-12 02:00:00.0"},{"av_id":"719571168","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e9786065bca153e870fa46edcc31c6f742e5b418.png","danmaku":"453839616","episode_id":"417167","episode_status":13,"episode_type":0,"from":"bangumi","index":"18","index_title":"薩露瓦小姐不會輸！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-12-05 02:00:00.0"},{"av_id":"336999716","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/261ff86ae83b9667f40442fb6b930fd2c92ffb74.png","danmaku":"449348887","episode_id":"417166","episode_status":13,"episode_type":0,"from":"bangumi","index":"17","index_title":"迦希大人睡不著…","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-11-28 02:00:00.0"},{"av_id":"634294632","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/122ea922ca0381af6b7c5ce5dc77a61bde44d3d1.png","danmaku":"445028461","episode_id":"417165","episode_status":13,"episode_type":0,"from":"bangumi","index":"16","index_title":"魔王陛下不客氣！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-11-21 02:00:00.0"},{"av_id":"891691053","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a9bb61c69cb0dd6df5c1697d67f137fd90f8233c.png","danmaku":"440849220","episode_id":"417164","episode_status":13,"episode_type":0,"from":"bangumi","index":"15","index_title":"店長無法決定！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-11-14 02:00:00.0"},{"av_id":"506424282","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/44254c0fef512cc5447f9d798bba1cb885771b9d.png","danmaku":"436689846","episode_id":"417163","episode_status":13,"episode_type":0,"from":"bangumi","index":"14","index_title":"魔法少女不戰鬥！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-11-07 02:00:00.0"},{"av_id":"933807381","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d9fcd31b3b20506fdb32a8ac14be00c0a618288b.png","danmaku":"432730010","episode_id":"417162","episode_status":13,"episode_type":0,"from":"bangumi","index":"13","index_title":"桃樂希小姐不高興！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-31 02:00:00.0"},{"av_id":"506152617","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a1ec0c376fa1284cda982d19bf9f64a3bb6ff15c.png","danmaku":"429036557","episode_id":"417161","episode_status":13,"episode_type":0,"from":"bangumi","index":"12","index_title":"小心不會背叛？","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-24 02:00:00.0"},{"av_id":"676097183","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/8f2b9a500a656827295f8e868d494313415ce5df.png","danmaku":"425416466","episode_id":"417160","episode_status":13,"episode_type":0,"from":"bangumi","index":"11","index_title":"房東回不去…","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-17 02:00:00.0"},{"av_id":"335993228","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/ed741534d1293771bd305b80c051c0b0784581d9.png","danmaku":"421779286","episode_id":"417159","episode_status":13,"episode_type":0,"from":"bangumi","index":"10","index_title":"復興計劃其十 魔法少女不能輸！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-10 02:00:00.0"},{"av_id":"633325540","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e7719f7731e431b05c06a71bb3bd055d01df3c07.png","danmaku":"417539980","episode_id":"417158","episode_status":13,"episode_type":0,"from":"bangumi","index":"9","index_title":"復興計劃其九 薩露瓦小姐無法治愈…","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-03 02:00:00.0"},{"av_id":"890700540","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/ea28e0c00aa1698eb9d3efe627a63eafb79583ef.png","danmaku":"413699340","episode_id":"417157","episode_status":13,"episode_type":0,"from":"bangumi","index":"8","index_title":"復興計劃其八 迦希大人不能洗澡！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-09-26 02:00:00.0"},{"av_id":"378061017","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f67fdb2a93263eed6757984708a9755f5550b607.png","danmaku":"409682210","episode_id":"417156","episode_status":13,"episode_type":0,"from":"bangumi","index":"7","index_title":"復興計劃其七 迦希大人不玩樂！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-09-19 02:00:00.0"},{"av_id":"762998931","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/1e9ca3f0c2f6391ca6fd3ccd8c8f08b962a2cc39.png","danmaku":"406772323","episode_id":"417155","episode_status":13,"episode_type":0,"from":"bangumi","index":"6","index_title":"復興計劃其六 迦希大人打不贏…","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-09-12 02:00:00.0"},{"av_id":"377782013","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a7d31fcb89ccad693973657e5184e69773925c80.png","danmaku":"401965618","episode_id":"417154","episode_status":13,"episode_type":0,"from":"bangumi","index":"5","index_title":"復興計劃其五 迦希大人不可疑!?","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-09-05 02:00:00.0"},{"av_id":"505168292","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/18283cee351387a8f6077be9f78438020a0ae758.png","danmaku":"397731895","episode_id":"414734","episode_status":13,"episode_type":0,"from":"bangumi","index":"4","index_title":"复兴计划其四 萨露瓦小姐不疏忽？","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-08-29 02:00:00.0"},{"av_id":"759843112","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/dd079d99103dba24dc71df157e37beeb1674fe57.png","danmaku":"388212070","episode_id":"414733","episode_status":13,"episode_type":0,"from":"bangumi","index":"3","index_title":"复兴计划其三 迦希大人不能炫耀…","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-08-15 02:00:00.0"},{"av_id":"292209253","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a2c563d693d309833541fe120b987daf3a83b390.png","danmaku":"383632533","episode_id":"414732","episode_status":13,"episode_type":0,"from":"bangumi","index":"2","index_title":"复兴计划其二 桃乐希小姐不怀疑！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-08-08 02:00:00.0"},{"av_id":"974425743","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/76afde3cc2d9eb8f389e1e0251eafda7f826d4b7.png","danmaku":"379234182","episode_id":"414712","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"復興計劃其一 賈希大人回不去！","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-08-01 02:00:00.0"}],"evaluate":"在魔界，地位僅次於魔王的迦希大人。\n被魔族們所畏懼，任性妄為揮霍無度，享受自己的人生之春天——本該是這樣\n然而因為魔法少女的襲擊，來到了人間。\n\n魔力之源的魔石破碎，權利與美貌都被奪走，變成了嬌小可愛的姿態。\n被迫開始了貧窮生活，住在沒有浴室的4疊半大小的房子，開始了在居酒屋打工的日子。\n不需要同情也不想管房租的催促，目標是「魔界復興」！","favorites":"0","has_unfollow":0,"is_finish":"1","is_guide_follow":1,"jp_title":"ジャヒー様はくじけない","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/5820400c449b3468864e01b53ed0264e9648c326.png","episode_index":{"index_show":"连载中"},"media_id":28234736,"publish":{"is_finish":0,"is_started":1},"title":"賈希大人不氣餒！（僅限港澳台地區）","type_id":1,"type_name":"番剧"},"newest_ep_id":"417169","newest_ep_index":"20","origin_name":"ジャヒー様はくじけない","payment":{"price":"0","promotion":"","tip":"大会员专享观看特权哦~","vip_promotion":"成為大會員搶先看"},"play_count":"0","pub_string":"","pub_time":"2021-08-01 00:00:01","pub_time_show":"8月1日 00:00 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"39044","season_status":13,"season_title":"TV","seasons":[{"bangumi_id":"5613","cover":"https://i0.hdslb.com/bfs/bangumi/image/5820400c449b3468864e01b53ed0264e9648c326.png","is_finish":"1","newest_ep_id":"417169","newest_ep_index":"20","season_id":"39044","season_status":13,"title":"TV"}],"share_url":"http://bangumi.bilibili.com/anime/39044/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/433d3e990c5267df69b2e895c50e1c9fc2bf6470.png","staff":"原作：昆布わかめ（揭載《月刊GANGAN JOKER》）\n監督：湊未來\n系列構成：橫手美智子\n角色設計、總作畫監督：仲敷沙織\n音樂：藤本コウジ (Sus4 Inc.)、佐佐木收\n動畫製作：SILVER LINK.","tag2s":[],"tags":[],"title":"賈希大人不氣餒！（僅限港澳台地區）","update_pattern":"","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: /x/web-interface/nav {"uname":"Mikasa_kk","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=0&article_offset=0 {"params":{"alltype_offset":0,"video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/web-interface/pcdn/v1 {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=0&article_offset=0 {"params":{"alltype_offset":0,"video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: atRun: 2, complete
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.50
debug: fetch https://manga.bilibili.com/twirp/comic.v1.Comic/Recommend?device=pc&platform=web {"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"body":"{\"JsonData\":\"[{\\\"pool_id\\\":500003,\\\"num\\\":4}]\"}","method":"POST","credentials":"include","signal":{}}
debug: fetch https://manga.bilibili.com/twirp/comic.v1.Comic/HomeHot?device=pc&platform=web {"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"body":"{\"type\":0}","method":"POST","credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}

**Comment by Pingdimu** [comment]
+1

**Comment by feiyax** [comment]
Dup: https://github.com/ipcjs/bilibili-helper/issues/1103#issuecomment-1335986140
