### ISSUE TITLE
可能导致的误解

### ISSUE THREAD

**Issue by esterTion** [ipcjs/bilibili-helper#107]
有人将“被永封的大会员”理解为脚本会导致封禁
因为你自用，建议删除该选项

**Comment by ipcjs** [comment]
我一直在等和我一样被封的人出现呐😅

上次也有人问过我这个问题。。。
可能是我的说明没写清楚，待会我改下说明吧

**Comment by esterTion** [comment]
你这个需求真的没有，你可以说明页留一行代码，ui的选项还是删了吧

**Comment by ipcjs** [comment]
B站这么多会员，说不定哪天就又封了个呐😅

再说理解错的也就那一两个不看说明文档的，不想因为他们把脚本的“重要功能”隐藏掉😣

**Comment by esterTion** [comment]
你不去掉就算了吧

说个其他的，playurl的cid可以不用改`|bangumi`了，我加了module识别并且优先级高于这种格式
说到底这个格式是为了flash播放才整的，现在我那边flash都死透了

**Comment by ipcjs** [comment]
en，那我下次删掉|bangumi吧
