### ISSUE TITLE
可以进入加载界面，但会出现拉取视频失败，以前看的好好的昨天突然就不能看了，代理服务器也换了好几个都不行，换账号也不行，打开脚本编辑器前面有感叹号，不知道是不是这个问题

### ISSUE THREAD

**Issue by haopy2333** [ipcjs/bilibili-helper#1075]
![IMG_20221005_132415](https://user-images.githubusercontent.com/115027414/193988281-3515cf39-b215-49f8-9913-75b8f6a37803.jpg)
![IMG_20221005_132423](https://user-images.githubusercontent.com/115027414/193988299-137e89ef-b4fa-4a68-b4bf-1c60876778c9.jpg)
![IMG_20221005_132433](https://user-images.githubusercontent.com/115027414/193988309-1ec4b65d-1294-42be-b41f-2148957224d2.jpg)
![IMG_20221005_132433](https://user-images.githubusercontent.com/115027414/193988307-8aea2a1d-3312-4434-a5c9-a027c90bb70c.jpg)
![IMG_20221005_132423](https://user-images.githubusercontent.com/115027414/193988339-c9abc254-cf08-486a-9c55-ac7475c4acd6.jpg)
![IMG_20221005_132415](https://user-images.githubusercontent.com/115027414/193988352-3c0bd030-577e-4bd6-95c5-d9e64eaf487a.jpg)

脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：
![Uploading IMG_20221005_132433.jpg…]()

**Comment by JasonKhew96** [comment]
@haopy2333 你觉得你服务器的框里填的什么链接？我没看懂

**Comment by haopy2333** [comment]
> @haopy2333 你觉得你服务器的框里填的什么链接？我没看懂

对不起，是我眼神不好（哭笑），是我犯傻了，谢谢你的解答，非常感谢，话说大佬你是常驻的吗

**Comment by haopy2333** [comment]
@JasonKhew96 对不起，是我眼神不好（哭笑），是我犯傻了，谢谢你的解答，非常感谢，话说大佬你是常驻的吗
