### ISSUE TITLE
脚本报错提示-10403

### ISSUE THREAD

**Issue by J-Wen** [ipcjs/bilibili-helper#1076]
脚本问题：@ipcjs

## 描述
脚本提示-10403 "抱歉您所在地区不可观看”，已经尝试过更换不同服务器，除了碰到失效的服务器之外都提示这个错误，已经按照帮助里的排查方法检查一遍，但依旧有相同的问题

- 问题网址：
https://www.bilibili.com/bangumi/media/md5551

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep96703?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: false
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"code":-101,"message":"账号未登录","ttl":1,"data":{"isLogin":false}}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=96703
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bilibil-unblock-bilibilermonkey-exltkztayj.cn-hangzhou.fcapp.run/pgc/player/web/playurl?cid=11234402&qn=0&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=038e6fb5d037f3d74c6150a88eb66e9f&module=bangumi&area=
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?cid=11234402&qn=0&type=&otype=json&fourk=1&bvid=BV1Ds411x7MC&ep_id=96703&fnver=0&fnval=80&session=038e6fb5d037f3d74c6150a88eb66e9f&module=bangumi
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bilibil-unblock-bilibilermonkey-exltkztayj.cn-hangzhou.fcapp.run/pgc/player/web/playurl?avid={{access_key}}&cid=11234402&bvid=BV1Ds411x7MC&qn=0&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=f6f2a6e633e86768990445e5b8afd147&module=bangumi&balh_ajax=1&area=
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=11234402&bvid=BV1Ds411x7MC&qn=0&type=&otype=json&ep_id=96703&fourk=1&fnver=0&fnval=80&session=f6f2a6e633e86768990445e5b8afd147&module=bangumi&balh_ajax=1
debug: /x/web-interface/nav {"code":-101,"message":"账号未登录","ttl":1,"data":{"isLogin":false}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

## 其他

1. 浏览器版本：Chrome 106.0.5249.91
2. 国家/地区：中国大陆

**Comment by kawatabi** [comment]
我也遇到了同样的问题（也是最近几天才出现的），同求解答

**Comment by kawatabi** [comment]
楼主试一下重新账号授权（我重新授权之后就OK了）
