### ISSUE TITLE
简体转繁体接口以失效

### ISSUE THREAD

**Issue by CC-zuo** [ipcjs/bilibili-helper#1088]

**Comment by ipcjs** [comment]
@SF-AD 提供的接口

**Comment by SF-AD** [comment]
![image](https://user-images.githubusercontent.com/50227138/199643877-7ba24488-21f7-44ed-beb8-6564afafebf2.png)
![20221103114019](https://user-images.githubusercontent.com/50227138/199644024-f27365f5-9cec-4798-871d-6321f63bd7f2.png)
![20221103114037](https://user-images.githubusercontent.com/50227138/199643553-207d5c2f-0682-40d6-ae20-be721fec401a.png)
经过测试 接口没有问题 为了防止接口滥用 我进行了一些限制 具体规则如下:
![20221103114409](https://user-images.githubusercontent.com/50227138/199643784-8f59c418-c449-4c80-abf5-f57183f3dd08.png)

**Comment by SF-AD** [comment]
如果 @CC-zuo  经过测试仍无法正常使用 请及时反馈 我会修改限制规则以保证最佳可用性.

**Comment by zjns** [comment]
应该是没更新脚本吧

**Comment by CC-zuo** [comment]
看了一下我的这个，根据提供的过滤规则，好像是http_referer字段出了问题
![无标题](https://user-images.githubusercontent.com/82815559/199904780-a6bcc929-794c-4f3b-b8db-7922c2b0f36c.png)
我为什么是这个 @SF-AD

**Comment by CC-zuo** [comment]
好像是我的edge的问题，标头referer总是不正确，chrome就正常，查了半天也没找到什么解决办法，就这样吧，不用这功能了。
