### ISSUE TITLE
服务器连接不上。

### ISSUE THREAD

**Issue by xiaojier** [ipcjs/bilibili-helper#109]
log: [解除B站区域限制 v6.5.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183802
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"虽败犹荣丶杰","isLogin":true,"level":4,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":1}}}
log: setAreaLimitSeason ep183802 true
log: Redirected request: bangumi playurl ->  https://biliplus.ipcjs.win/BPplayurl.php?cid=31144490|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=4a65be8ff99d467844b221b21bceed44
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by ipcjs** [comment]
换成第二个服务器

**Comment by xiaojier** [comment]
又显示突破黑洞失败了

**Comment by ipcjs** [comment]
那个弹窗不止”突破黑洞失败“这几个字吧？

**Comment by xiaojier** [comment]
好了已经
，谢谢
