### ISSUE TITLE
特定番剧无法访问

### ISSUE THREAD

**Issue by IcewaveLJW** [ipcjs/bilibili-helper#1098]
特定番剧访问会失败。

![943a418499984e203593d5fedf3304e](https://user-images.githubusercontent.com/73431851/203749411-64e2b87b-c8bd-4f5d-97d3-1944e0f15ec3.png)

![33eead00d141ae32a3b343997be6617](https://user-images.githubusercontent.com/73431851/203748803-fe21b441-77e7-465a-8c1f-f620591a0ebc.png)

地区： 日本/
浏览器：Chrome版本 107.0.5304.107（正式版本）

**Comment by AisukaYuki** [comment]
下午我服务器断网了。刚刚恢复

**Comment by IcewaveLJW** [comment]
> 下午我服务器断网了。刚刚恢复

Thanks~
