### ISSUE TITLE
看不了

### ISSUE THREAD

**Issue by endlessZS** [ipcjs/bilibili-helper#110]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```
log: [解除B站区域限制 v6.5.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep115386
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"哪年星空哪年情","isLogin":true,"level":0,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: Redirected request: bangumi playurl ->  https://biliplus.ipcjs.win/BPplayurl.php?cid=30217997|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=a298075ce3cca390bf3ecd5de7f3d171
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by azhanglihao** [comment]
刚才还好好的.我就关机出去吃个饭回来就不行了。
服务器连接不上，授权也是502错误。啊啊啊我想看魔法使的新娘QAQ

**Comment by mzoff7** [comment]
我也是，DitF看完第四集想再看一遍前面的，一刷新发现不能用了
