### ISSUE TITLE
求大佬们解决问题

### ISSUE THREAD

**Issue by MychCcc** [ipcjs/bilibili-helper#111]
## 日志

```
log: [解除B站区域限制 v6.5.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183801
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":1390}}}
log: Redirected request: bangumi playurl ->  https://interface.bilibili.com/playurl?cid=30670211&player=1&qn=112&quality=112&ts=1517931362&sign=4082901804594ee20398d1269a18832e
log: xml2obj {"location":null} => {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by MychCcc** [comment]
log: [解除B站区域限制 v6.5.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183801
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"账号名","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":1390}}}
log: Redirected request: bangumi playurl ->  https://interface.bilibili.com/playurl?cid=30670211&player=1&qn=112&quality=112&ts=1517931362&sign=4082901804594ee20398d1269a18832e
log: xml2obj {"location":null} => {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by ipcjs** [comment]
5.7.0，已经把使用B站接口的选项去掉了，不会再有这问题了😅

**Comment by ipcjs** [comment]
是6.7.0
