### ISSUE TITLE
希望可以支持一下手机版的网页

### ISSUE THREAD

**Issue by kzw200015** [ipcjs/bilibili-helper#112]
在手机上看每次都要切换到电脑版的网页，而且手机看电脑版网页有一堆乱七八糟的问题，希望能支持一下

**Comment by ipcjs** [comment]
手机上不支持油猴脚本

**Comment by kzw200015** [comment]
不，手机支持油猴脚本，yandex浏览器支持chrome扩展，我切换成电脑版网页，可以正常使用插件

**Comment by ipcjs** [comment]
。。。这么牛逼的吗😅

**Comment by kzw200015** [comment]
所以大佬能不能考虑一下呢？

**Comment by ipcjs** [comment]
手机上的请求接口和电脑上的不一样，要改也应该能改；

不过，手机网页版不是只能播放6分钟么？感觉意义不大呀

**Comment by kzw200015** [comment]
确实，这我倒是没有考虑过。如果大佬会安卓开发的话，可以使用xposed模块的方式修改应用的播放接口

**Comment by ipcjs** [comment]
暂时没有做Android版的计划

**Comment by ipcjs** [comment]
@esterTion 可以给服务器加个 m.bilibili.com 的跨域么？想试下手机上用脚本😅

**Comment by esterTion** [comment]
done

**Comment by ipcjs** [comment]
@esterTion `/BPplayurl.php`接口返回的视频url是验证`User-Agent`的😂，只能在pc上播放，手机上会报`465`

@kzw200015 所以还是不能播~~

**Comment by qjzcj2008** [comment]
@kzw200015 其实如果你手机可用xposed的话，还有另一个思路可用试试看，你可以考虑用vpn service或者是其他的代理手段（毕竟都xposed了，不一定要用这个方法了），然后再用xposed解决客户端的ssl证书强校验，然后直接伪造response，不过可能用`/BPplayurl.php`接口返回的视频url数据还是逃不过ua验证的问题_(:з」∠)_但理论上后期再处理一下应该是可以解决问题的

**Comment by ipcjs** [comment]
改成从` /api/h5play.php`查找播放地址了
在最新的yandex上测试有效

首先要把代理服务器设为`默认代理服务器`才有效（设置按钮在页面的最下方，一个很小的球形，仔细看😆）

虽然能播但因为手机网页版不支持flv，只能播mp4，清晰度很低；
手机网页版的默认的6分钟限制，貌似被解除了；

不保证这个功能以后也能用😅

**Comment by LotusBornInSummer** [comment]
大神，这个好像确实解除了区域限制，但是视频还是无法播放。
这个番我电脑版的可以解除限制并且播放，手机版解除了区域限制，但是不可以播放。
https://m.bilibili.com/bangumi/play/ss26163
提示：## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-400,\"message\":\"invalid cid\"}","code":-400}

可以考虑进行如下尝试:
1. 多刷新几下页面
2. 进入设置页面更换代理服务器
3. 耐心等待代理服务器端修复问题

**Comment by PC3500** [comment]
前面的,既然都能用扩充了,用User Agent Switcher伪装成Windows不香吗?亲测有用

**Comment by Freddd13** [comment]
> 前面的,既然都能用扩充了,用User Agent Switcher伪装成Windows不香吗?亲测有用

这样观看界面不是电脑版吗？

**Comment by Freddd13** [comment]
现在手机yandex browser还能以手机ua看吗，知道的朋友指导下~

**Comment by SashiRin** [comment]
其实这个插件适合PC和平板用，手机太小很多时候不会被认为是电脑从而打不开番剧的PC版页面。安卓平板的话，Yandex是比较好，但是UI使用啥的还是差点。最理想的其实firefox，但是不知道为啥安卓版的firefox+violentmonkey装上死活用不了。总是显示下载错误。唉。

**Comment by ManyullynSword** [comment]
手机还是老老实实用漫游版吧，解析服务器是通用的

**Comment by ManyullynSword** [comment]
安卓有个挺好的浏览器叫“Kiwi Browser”，在平板上的UI和Chrome基本无异，也支持所有Chromium的插件

**Comment by ManyullynSword** [comment]
甚至原生支持US插件（但兼容性不如篡改猴）
