### ISSUE TITLE
授权mcbbs访问被拒

### ISSUE THREAD

**Issue by 23ms11** [ipcjs/bilibili-helper#1124]
脚本问题：@ipcjs

## 描述
授权的时候提示mcbbs访问被拒，无法开高画质

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：意大利

**Comment by Zpcin** [comment]
一样mcbbs 403

**Comment by feiyax** [comment]
FYI, workaround here worked for me: https://github.com/ipcjs/bilibili-helper/issues/1103

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/issues/1103#issuecomment-1335986140
