### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

### ISSUE THREAD

**Issue by doggewzb** [ipcjs/bilibili-helper#1128]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep562694?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"这是压缩毛巾","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=562694
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://hk.dogge.ga/pgc/player/web/playurl?cid=774887957&qn=80&type=&otype=json&fourk=1&bvid=BV1v34y1n7bT&ep_id=562694&fnver=0&fnval=80&session=3268a0130b9e76b27b44f91c367d78a6&module=bangumi&area=hk&access_key={{access_key}}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://hk.dogge.ga/pgc/player/web/playurl?cid=774887957&qn=80&type=&otype=json&fourk=1&bvid=BV1v34y1n7bT&ep_id=562694&fnver=0&fnval=80&session=3268a0130b9e76b27b44f91c367d78a6&module=bangumi&area=&access_key=55fc2b1873c9adcab15f409e9dfaceb1
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://hk.dogge.ga/pgc/player/web/playurl?avid=undefined&cid=774887957&bvid=BV1v34y1n7bT&qn=80&type=&otype=json&ep_id=562694&fourk=1&fnver=0&fnval=80&session=34836fd32bb6cce3250dcdb2d12d69b6&module=bangumi&balh_ajax=1&area=hk&access_key=55fc2b1873c9adcab15f409e9dfaceb1
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://hk.dogge.ga/pgc/player/web/playurl?avid=undefined&cid=774887957&bvid=BV1v34y1n7bT&qn=80&type=&otype=json&ep_id=562694&fourk=1&fnver=0&fnval=80&session=34836fd32bb6cce3250dcdb2d12d69b6&module=bangumi&balh_ajax=1&area=&access_key=55fc2b1873c9adcab15f409e9dfaceb1
debug: /x/web-interface/nav {"uname":"这是压缩毛巾","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: balh_mode  =>  default
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54

**Comment by JasonKhew96** [comment]
`hk.dogge.ga` 证书到期
