### ISSUE TITLE
自动生成简体中文字幕功能失效

### ISSUE THREAD

**Issue by dieterminator** [ipcjs/bilibili-helper#1136]
![image](https://user-images.githubusercontent.com/52268813/212456856-4486f94b-39ff-4a56-b460-ff68cc76e615.png)
![QQ截图20230114131101](https://user-images.githubusercontent.com/52268813/212457008-fde865e4-a23a-409e-825a-3852d5127c63.jpg)

发生了跨域，请求返回状态200，但无法加载响应数据

**Comment by Guochengjie** [comment]
我已经请求修复，请查看pull request https://github.com/ipcjs/bilibili-helper/pull/1138  
随便写了一个API，去调用繁化姬，然后处理了一下格式  
在正式修复之前，大家可以手动替换
```
subtitle_url: `//video1.beijcloud.com/sub/t2cn/?sub_url=${origSubUrl}&sub_id=${encSubId}`,
```
为：
```
subtitle_url: `//zhconvert.geecloud.eu/hans2cn?source_url=${origSubUrl}&sub_id=${encSubId}`,
```
