### ISSUE TITLE
是不是不支持edge和safari上的temparmonkey？

### ISSUE THREAD

**Issue by Azarealice** [ipcjs/bilibili-helper#114]
## 描述
Mac+Safari+temparmonkey 脚本没有生效

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
没有mac，没法测

**Comment by ipcjs** [comment]
控制台截图看看？

**Comment by oilbottle** [comment]
是不是也不支持edge的tampermonkey?

**Comment by ipcjs** [comment]
edge上我试了，是没问题的 @oilbottle

**Comment by oilbottle** [comment]
次奥，好奇怪。我的windows版本是最新的，但是edge上的都没有显示设置。按照wiki里，这种情况是要升级浏览器……

**Comment by ipcjs** [comment]
@oilbottle
你把控制台截图+edge的版本号，发过来我看下

**Comment by oilbottle** [comment]
[cid:image002.png@01D3A2CA.9F02F120]

这个吗？
辛苦开发者啦！

**Comment by oilbottle** [comment]
![default](https://user-images.githubusercontent.com/19664570/36071184-235928da-0ebf-11e8-8dda-a98bc6115e2e.png)
emmmm上一个没显示图片，试试这个

**Comment by ipcjs** [comment]
@oilbottle 你的Tampermonkey版本号是多少？
我的是4.5.5648，没问题

**Comment by oilbottle** [comment]
4.5.5648，和你一样

**Comment by ipcjs** [comment]
@oilbottle 你试试卸载掉Tampermonkey，再重装

**Comment by oilbottle** [comment]
卸载重装还是不行。又测试了chrome上的，正常……此处是不是应该骂一下微软不争气……

**Comment by ipcjs** [comment]
@oilbottle 那就用chorme吧
环境一样，脚本的运行时机却不一样，这个edge真是坑😓

**Comment by oilbottle** [comment]
奇怪的是你的能用QAQ这个和所在地区会有关系吗…

**Comment by ipcjs** [comment]
@oilbottle 没关系，纯粹是脚本加载时机的问题

脚本要替换掉浏览器的网络请求接口，需要在页面加载之前执行
但你电脑的edge上却是在页面加载之后执行了脚本

**Comment by xingcoo** [comment]
我试了下 Safari下是可用的 只是不太稳定 有时候需要刷新页面才行 看了下Safari的console 估计也是加载时机的锅
![image](https://user-images.githubusercontent.com/3954137/36291812-2c9d96ee-1282-11e8-8890-1b531696c74c.png)
我用的是Safari 11.0.3, macOS 10.13.3

**Comment by MephistoSatanDevil** [comment]
安装了adblock/adblock plus扩展吧？

**Comment by oilbottle** [comment]
安装了uBlock Orign, 但卸载后也用不了。Edge应该是能用的，前段时间突然能用了，但是后来又用不了了。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by simon300000** [comment]
你好，我不知道是什么情况，但是我Safari用这个插件两年多了，感谢作者。
个人测试来看，和tampermonkey一起用，两年间支持都挺好的，没有遇到什么问题。
唯一需要注意的就是不能在后台打开页面，这样加载时机不对。
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/12656264/57413919-9ffe1d00-7228-11e9-8fc7-6a3ab3fb0b89.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/12656264/57413926-a5f3fe00-7228-11e9-8ffe-928d0a2ae612.png">

**Comment by MrThanlon** [comment]
@simon300000 新版播放器已经可以用了吗？safari我在后台打开页面也可以加载，多刷新几次就行了

**Comment by simon300000** [comment]
@MrThanlon 新版播放器我这里似乎没有什么问题。后台打开的确要多刷新一次就行

**Comment by ipcjs** [comment]
safari上还有这样的问题： #407

**Comment by simon300000** [comment]
#407 这个就很玄学了。。。
