### ISSUE TITLE
账号授权的链接显示该网页无法正常运作

### ISSUE THREAD

**Issue by Mikakakakaka** [ipcjs/bilibili-helper#1147]
脚本问题：@ipcjs

## 描述

无法账号授权
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep476239?spm_id_from=444.41.list.card_pgc.click
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y generate_sub:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"何事秋风画背扇","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: {{access_key}} {"code":6002003,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.plus/pgc/player/web/playurl?support_multi_audio=true&avid=391710546&cid=934160938&qn=112&fnver=0&fnval=4048&fourk=1&ep_id=476239&session=c69a505b53482abd1b804a7cee668670&from_client=BROWSER&drm_tech_type=2&module=bangumi&area=hk
info: player msg: 读取番剧地区缓存，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://出差.xyz/pgc/player/web/playurl?support_multi_audio=true&avid=391710546&cid=934160938&qn=112&fnver=0&fnval=4048&fourk=1&ep_id=476239&session=c69a505b53482abd1b804a7cee668670&from_client=BROWSER&drm_tech_type=2&module=bangumi&area=tw
debug: fetch https://api.bilibili.com/x/web-interface/wbi/search/default?w_rid=0a5af81130b0dfa6b92a5dfef9645810&wts=1675292947 {"params":{"w_rid":"0a5af81130b0dfa6b92a5dfef9645810","wts":"1675292947"},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/wbi/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956,5672&w_rid=ebc3ac37952ee15797658b351309b42a&wts=1675292947 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956,5672","w_rid":"ebc3ac37952ee15797658b351309b42a","wts":"1675292947"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: /x/web-interface/nav {"uname":"何事秋风画背扇","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=757841168492920800&article_offset=754050846973493200 {"params":{"alltype_offset":0,"video_offset":"757841168492920800","article_offset":"754050846973493200"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/web-interface/pcdn/v1 {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=757841168492920800&article_offset=754050846973493200 {"params":{"alltype_offset":0,"video_offset":"757841168492920800","article_offset":"754050846973493200"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: /pgc/player/web/playurl proxy {"code":0,"result":{"accept_format":"hdflv2,flv,flv720,flv480,mp4","code":0,"seek_param":"start","is_preview":0,"fnval":4048,"video_project":true,"fnver":0,"type":"DASH","bp":0,"result":"suee","seek_type":"offset","from":"local","video_codecid":7,"record_info":{"record_icon":"","record":""},"is_drm":false,"no_rexcode":0,"format":"flv480","support_formats":[{"display_desc":"1080P","superscript":"高码率","need_login":true,"codecs":["av01.0.08M.08.0.110.01.01.01.0","avc1.640032","hev1.1.6.L150.90"],"format":"hdflv2","description":"高清 1080P+","need_vip":true,"quality":112,"new_description":"1080P 高码率"},{"display_desc":"1080P","superscript":"","need_login":true,"codecs":["av01.0.08M.08.0.110.01.01.01.0","avc1.640032","hev1.1.6.L150.90"],"format":"flv","description":"高清 1080P","quality":80,"new_description":"1080P 高清"},{"display_desc":"720P","superscript":"","need_login":true,"codecs":["av01.0.08M.08.0.110.01.01.01.0","avc1.640028","hev1.1.6.L120.90"],"format":"flv720","description":"高清 720P","quality":64,"new_description":"720P 高清"},{"display_desc":"480P","superscript":"","codecs":["av01.0.08M.08.0.110.01.01.01.0","avc1.64001F","hev1.1.6.L120.90"],"format":"flv480","description":"清晰 480P","quality":32,"new_description":"480P 清晰"},{"display_desc":"360P","superscript":"","codecs":["av01.0.08M.08.0.110.01.01.01.0","avc1.64001E","hev1.1.6.L120.90"],"format":"mp4","description":"流畅 360P","quality":16,"new_description":"360P 流畅"}],"message":"","accept_quality":[112,80,64,32,16],"quality":32,"timelength":1450174,"has_paid":false,"dash":{"duration":1451,"minBufferTime":1.5,"min_buffer_time":1.5,"video":[{"start_with_sap":1,"bandwidth":237769,"sar":"640:639","backupUrl":[],"codecs":"avc1.64001F","base_url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938_nb3-1-30032.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=14e4d6357d8d64632f49024ed98b5a9b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=2ab2ff58dc8c988e0add9425bd6f3974b52548664573c2557f2747f25286ea8d&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=29721&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-997","indexRange":"998-4485","initialization":"0-997","index_range":"998-4485"},"mimeType":"video/mp4","frame_rate":"24.390","SegmentBase":{"Initialization":"0-997","indexRange":"998-4485","initialization":"0-997","index_range":"998-4485"},"frameRate":"24.390","codecid":7,"baseUrl":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938_nb3-1-30032.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=14e4d6357d8d64632f49024ed98b5a9b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=2ab2ff58dc8c988e0add9425bd6f3974b52548664573c2557f2747f25286ea8d&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=29721&logo=80000000","size":43096600,"mime_type":"video/mp4","width":852,"startWithSAP":1,"id":32,"height":480,"md5":"","start_with_s_a_p":1},{"start_with_sap":1,"bandwidth":200194,"sar":"640:639","backupUrl":[],"codecs":"hev1.1.6.L120.90","base_url":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938-1-30033.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=495ed26e81319d9f08d0aafcf33d65f6&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=25024&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-1062","indexRange":"1063-4550","initialization":"0-1062","index_range":"1063-4550"},"mimeType":"video/mp4","frame_rate":"23.810","SegmentBase":{"Initialization":"0-1062","indexRange":"1063-4550","initialization":"0-1062","index_range":"1063-4550"},"frameRate":"23.810","codecid":12,"baseUrl":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938-1-30033.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=495ed26e81319d9f08d0aafcf33d65f6&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=25024&logo=80000000","size":36285956,"mime_type":"video/mp4","width":852,"startWithSAP":1,"id":32,"height":480,"md5":"","start_with_s_a_p":1},{"start_with_sap":1,"bandwidth":191754,"sar":"640:639","backupUrl":[],"codecs":"av01.0.08M.08.0.110.01.01.01.0","base_url":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938-1-100023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=f21d8367821403cfbf9d26de849eeac5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=24185&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-1022","indexRange":"1399-4910","initialization":"0-1022","index_range":"1399-4910"},"mimeType":"video/mp4","frame_rate":"23.976","SegmentBase":{"Initialization":"0-1022","indexRange":"1399-4910","initialization":"0-1022","index_range":"1399-4910"},"frameRate":"23.976","codecid":13,"baseUrl":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938-1-100023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=f21d8367821403cfbf9d26de849eeac5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=24185&logo=80000000","size":35069098,"mime_type":"video/mp4","width":852,"startWithSAP":1,"id":32,"height":480,"md5":"","start_with_s_a_p":1},{"start_with_sap":1,"bandwidth":139469,"sar":"1:1","backupUrl":[],"codecs":"hev1.1.6.L120.90","base_url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938-1-30011.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=7390442a3ddce445270ddd037b3665ad&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=ab6d8f6e33185536e872e72c534fef604f0434bff507e1b6137a4f2538848023&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=17434&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-1057","indexRange":"1058-4545","initialization":"0-1057","index_range":"1058-4545"},"mimeType":"video/mp4","frame_rate":"23.810","SegmentBase":{"Initialization":"0-1057","indexRange":"1058-4545","initialization":"0-1057","index_range":"1058-4545"},"frameRate":"23.810","codecid":12,"baseUrl":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938-1-30011.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=7390442a3ddce445270ddd037b3665ad&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=ab6d8f6e33185536e872e72c534fef604f0434bff507e1b6137a4f2538848023&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=17434&logo=80000000","size":25279423,"mime_type":"video/mp4","width":640,"startWithSAP":1,"id":16,"height":360,"md5":"","start_with_s_a_p":1},{"start_with_sap":1,"bandwidth":139921,"sar":"1:1","backupUrl":[],"codecs":"avc1.64001E","base_url":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938_nb3-1-30016.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=a0b5e70ce668456873841c5b1ff82d8c&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=17490&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-1001","indexRange":"1002-4489","initialization":"0-1001","index_range":"1002-4489"},"mimeType":"video/mp4","frame_rate":"24.390","SegmentBase":{"Initialization":"0-1001","indexRange":"1002-4489","initialization":"0-1001","index_range":"1002-4489"},"frameRate":"24.390","codecid":7,"baseUrl":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938_nb3-1-30016.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=a0b5e70ce668456873841c5b1ff82d8c&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=17490&logo=80000000","size":25361379,"mime_type":"video/mp4","width":640,"startWithSAP":1,"id":16,"height":360,"md5":"","start_with_s_a_p":1},{"start_with_sap":1,"bandwidth":147457,"sar":"1:1","backupUrl":[],"codecs":"av01.0.08M.08.0.110.01.01.01.0","base_url":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938-1-100022.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=38f124a2712f6a8a5e91824f4ba73a58&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=18648&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-1022","indexRange":"1399-4910","initialization":"0-1022","index_range":"1399-4910"},"mimeType":"video/mp4","frame_rate":"23.976","SegmentBase":{"Initialization":"0-1022","indexRange":"1399-4910","initialization":"0-1022","index_range":"1399-4910"},"frameRate":"23.976","codecid":13,"baseUrl":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938-1-100022.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=38f124a2712f6a8a5e91824f4ba73a58&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=18648&logo=80000000","size":27040031,"mime_type":"video/mp4","width":640,"startWithSAP":1,"id":16,"height":360,"md5":"","start_with_s_a_p":1}],"audio":[{"start_with_sap":0,"bandwidth":187731,"sar":"","backupUrl":[],"codecs":"mp4a.40.2","base_url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=3c3508c6b2dd405392c032ca5027e755&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=9c270793a35ce83549068dfb05fc6b543c644de75a4b0b923f939329426b74ae&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=23467&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-945","indexRange":"946-4469","initialization":"0-945","index_range":"946-4469"},"mimeType":"audio/mp4","frame_rate":"","SegmentBase":{"Initialization":"0-945","indexRange":"946-4469","initialization":"0-945","index_range":"946-4469"},"frameRate":"","codecid":0,"baseUrl":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=3c3508c6b2dd405392c032ca5027e755&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=9c270793a35ce83549068dfb05fc6b543c644de75a4b0b923f939329426b74ae&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=23467&logo=80000000","size":34027867,"mime_type":"audio/mp4","width":0,"startWithSAP":0,"id":30280,"height":0,"md5":"","start_with_s_a_p":0},{"start_with_sap":0,"bandwidth":43111,"sar":"","backupUrl":[],"codecs":"mp4a.40.5","base_url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938_nb3-1-30216.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=99e13f00318618544f6f5bf32779e3fc&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=6b98187eaf8e621e98746038113b431f2a2dd7c7245fdaeca725419e23d6d03b&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=5389&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-955","indexRange":"956-4479","initialization":"0-955","index_range":"956-4479"},"mimeType":"audio/mp4","frame_rate":"","SegmentBase":{"Initialization":"0-955","indexRange":"956-4479","initialization":"0-955","index_range":"956-4479"},"frameRate":"","codecid":0,"baseUrl":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/38/09/934160938/934160938_nb3-1-30216.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=akam&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=99e13f00318618544f6f5bf32779e3fc&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675300148~hmac=6b98187eaf8e621e98746038113b431f2a2dd7c7245fdaeca725419e23d6d03b&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=5389&logo=80000000","size":7814771,"mime_type":"audio/mp4","width":0,"startWithSAP":0,"id":30216,"height":0,"md5":"","start_with_s_a_p":0},{"start_with_sap":0,"bandwidth":102829,"sar":"","backupUrl":[],"codecs":"mp4a.40.2","base_url":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938_nb3-1-30232.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=3841b63f120e69c39d11d8d6688ca7e1&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=12854&logo=80000000","backup_url":[],"segment_base":{"Initialization":"0-945","indexRange":"946-4469","initialization":"0-945","index_range":"946-4469"},"mimeType":"audio/mp4","frame_rate":"","SegmentBase":{"Initialization":"0-945","indexRange":"946-4469","initialization":"0-945","index_range":"946-4469"},"frameRate":"","codecid":0,"baseUrl":"https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/38/09/934160938/934160938_nb3-1-30232.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1675300148&gen=playurlv2&os=cosovbv&oi=3743041994&trid=9cb747ecc89f491a9a1b635bf30991a2p&mid=0&platform=pc&upsig=3841b63f120e69c39d11d8d6688ca7e1&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&buvid=&build=0&agrr=0&bw=12854&logo=80000000","size":18638756,"mime_type":"audio/mp4","width":0,"startWithSAP":0,"id":30232,"height":0,"md5":"","start_with_s_a_p":0}],"dolby":{"audio":[],"type":0}},"clip_info_list":[],"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":2},"message":"0"}
debug: atRun: 2, complete
debug: __playinfo__ get
debug: __playinfo__ get
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://manga.bilibili.com/twirp/comic.v1.Comic/Recommend?device=pc&platform=web {"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"body":"{\"JsonData\":\"[{\\\"pool_id\\\":500003,\\\"num\\\":4}]\"}","method":"POST","credentials":"include","signal":{}}
debug: fetch https://manga.bilibili.com/twirp/comic.v1.Comic/HomeHot?device=pc&platform=web {"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json"},"body":"{\"type\":0}","method":"POST","credentials":"include","signal":{}}
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：英国

**Comment by wuhuqifeilo** [comment]
一样

This page isn’t workingIf the problem continues, contact the site owner.
HTTP ERROR 514

**Comment by chriszhang1** [comment]
同样的问题，请修复一下，谢谢！
