### ISSUE TITLE
设置不显示（浏览器最新版本）

### ISSUE THREAD

**Issue by mrcq** [ipcjs/bilibili-helper#115]
## 描述

设置经常刷新不出来，已经升到谷歌浏览器最新版本，脚本最新版本，有时候番剧界面非常抱歉，有时候播放界面非常抱歉，番剧界面显示正常时一刷新就可能非常抱歉。

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```
log: [解除B站区域限制 v6.6.2 (Tampermonkey)] run on: https://bangumi.bilibili.com/anime/21680
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /season_area {"code":0,"message":"success","result":{"play":0,"ban_area_show":1}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

## 其他

1. 浏览器版本：版本 64.0.3282.140（正式版本） （64 位）
2. 国家/地区：中国大陆

**Comment by 0713** [comment]
播放不出来。。

**Comment by ipcjs** [comment]
贴播放界面的log，番剧列表的kog看不出什么东西
