### ISSUE TITLE
脚本解析问题

### ISSUE THREAD

**Issue by Tian9912** [ipcjs/bilibili-helper#1150]
脚本问题：@ipcjs

## 描述
脚本会错误解析大陆番剧纪录片等相关页面

- 问题网址：

https://www.bilibili.com/bangumi/play/ep720289?from_spmid=666.19.0.0
## 日志

<details>
<summary>Verbose 日志</summary>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28386016/?spm_id_from=666.25.b_6d656469615f6d6f64756c65.2
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=44081&access_key={{access_key}}
debug: atRun: 1, interactive
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":1,"follow_status":2,"login":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":720288,"last_ep_index":"4","last_time":1403},"real_price":"0","sponsor":0,"vip_info":{"due_date":1793721600000,"status":1,"type":2}}}
debug: fetch https://api.bilibili.com/x/web-interface/wbi/search/default?w_rid=31b3b4042ccb02aa929241d53935b726&wts=1675508659 {"params":{"w_rid":"31b3b4042ccb02aa929241d53935b726","wts":"1675508659"},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/wbi/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956,5672&w_rid=e4cf3983aa8e274891b60fbe491a6182&wts=1675508659 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956,5672","w_rid":"e4cf3983aa8e274891b60fbe491a6182","wts":"1675508659"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: /x/web-interface/nav {"uname":"晓天_辛_天哓","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"晓天_辛_天哓","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=757337312995573800&article_offset=0 {"params":{"alltype_offset":0,"video_offset":"757337312995573800","article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/web-interface/pcdn/v1 {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=757337312995573800&article_offset=0 {"params":{"alltype_offset":0,"video_offset":"757337312995573800","article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: season44081 {"code":0,"message":"success","result":{"actor":[{"actor":"楠木灯","actor_id":0,"role":"莉泽洛特·里芬施塔尔"},{"actor":"中村悠一","actor_id":0,"role":"西格瓦尔德·菲岑哈根"},{"actor":"石川界人","actor_id":0,"role":"远藤碧人"},{"actor":"花泽香菜","actor_id":0,"role":"小林诗帆乃"},{"actor":"富田美忧","actor_id":0,"role":"菲内"}],"alias":"ツンデレ悪役令嬢リーゼロッテと実況の遠藤くんと解説の小林さん,傲娇反派千金莉洁洛特与实况主远藤同学及解说员小林同学","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"6337","bangumi_title":"反派大小姐莉泽洛特与实况解说","brief":"「傲劲好冲！傲劲好冲啊，莉泽洛特！」\n王太子西格瓦尔德因突然听见的神之声而困惑不已。\n神说，西格瓦尔...","business_type":1,"copyright":"dujia","cover":"https://i0.hdslb.com/bfs/bangumi/image/6fac18d05ea12b8009a621c1caf392611e5a73d6.png","danmaku_count":"-1","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"523779796","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0c690fc1c69872fed0abbd78487f75b86c137429.png","danmaku":"991060404","episode_id":"720289","episode_status":13,"episode_type":0,"from":"bangumi","index":"5","index_title":"母女和姐妹和初次约会","is_new":"1","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2023-02-04 01:55:01.0"},{"av_id":"735829236","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/8b1ef4331cef160b221f1a5816f06716cab1cebd.jpg","danmaku":"985494320","episode_id":"720288","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"夏天和归省和思念之情","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2023-01-28 01:55:01.0"},{"av_id":"307875361","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e4408aef76084e7a7df152e3387650e6e58d4539.jpg","danmaku":"985494272","episode_id":"719187","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"缎带和学长和恋慕之心","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2023-01-21 01:55:01.0"},{"av_id":"735148986","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/4572915733ca48d1e626813cf9ac4098f8ccf8cf.jpg","danmaku":"985494248","episode_id":"719186","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"魔杖和满级和神之宠爱","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2023-01-14 02:10:01.0"},{"av_id":"306604096","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/72c5d721a39839b83ac7d4139d2fba241b18fd6a.png","danmaku":"933286137","episode_id":"710547","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV2","index_title":"","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-12-23 10:59:01.0"},{"av_id":"434757666","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a80a885ad0cc51cec3c58de540ab5b2aaeaed22c.jpg","danmaku":"985493552","episode_id":"719185","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"傲娇和王子和神之声","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2023-01-07 02:25:01.0"},{"av_id":"221532449","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/c9029fd466f572e9e145e06b8ef96f13d8327d16.png","danmaku":"933286105","episode_id":"710546","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV1","index_title":"","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-12-23 10:59:01.0"}],"evaluate":"「傲劲好冲！傲劲好冲啊，莉泽洛特！」\n王太子西格瓦尔德因突然听见的神之声而困惑不已。\n神说，西格瓦尔德的未婚妻莉泽洛特是“傲娇”，\n似乎将会迎来“毁灭”？\n她刻薄的言行，都是在掩饰自己的害羞？！\n神明所讲解的她的真实想法是如此可爱，令西格瓦尔德独自心动难耐，但有一件事他无从得知。\n事实上神明的真面目，竟不过是做游戏实况与解说的普通高中生…\n游玩乙女游戏《魔恋》时，负责实况的远藤和负责解说的小林发现，游戏中的攻略对象西格瓦尔德竟能听到自己的声音了。二人想要解救无论选择哪条支线都会迎来毁灭的莉泽洛特，时而精准判断，时而为莉泽洛特的“傲娇”而心动不已，并为西格瓦尔德进行着实况解说。\n依靠神谕（※游戏实况解说）拯救未婚妻吧！\n想要藏起来的真心话暴露无遗的反派千金能否避开坏结局？！\n现实中的高中生所做的实况解说，作为“神之声”传入了乙女游戏？！\n这是现实与游戏世界交汇的奇幻恋爱故事。","favorites":"-1","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"ツンデレ悪役令嬢リーゼロッテと実況の遠藤くんと解説の小林さん","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/6fac18d05ea12b8009a621c1caf392611e5a73d6.png","episode_index":{"index_show":"连载中, 每周六 01:55更新"},"media_id":28386016,"publish":{"is_finish":0,"is_started":1},"rating":{"count":1989,"score":9.6},"title":"反派大小姐莉泽洛特与实况解说","type_id":1,"type_name":"动画"},"newest_ep_id":"720289","newest_ep_index":"5","origin_name":"ツンデレ悪役令嬢リーゼロッテと実況の遠藤くんと解説の小林さん","payment":{"price":"0","promotion":"","tip":"大会员专享观看特权哦~","vip_promotion":"成为大会员抢先看"},"play_count":"-1","pub_string":"","pub_time":"2023-01-07 02:25:00","pub_time_show":"1月7日 02:25 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"44081","season_status":13,"season_title":"TV","seasons":[{"bangumi_id":"6337","cover":"https://i0.hdslb.com/bfs/bangumi/image/6fac18d05ea12b8009a621c1caf392611e5a73d6.png","is_finish":"0","is_new":"1","newest_ep_id":"720289","newest_ep_index":"5","season_id":"44081","season_status":13,"title":"TV","total_count":"12"}],"share_url":"http://bangumi.bilibili.com/anime/44081/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/a3c119129c85bc55861bfa6b42b59b2121367e4c.png","staff":"原作：惠之岛铃（角川BOOKS）\n原作插画：Eihi\n漫画：逆木Lumiwo（B's-LOG COMICS）\n导演：吉村文宏\n剧本统筹：金春智子\n角色设计：片山美雪\n音乐：斋木达彦、田渊夏海、青木沙也果、中岛纯子、佐久间奏\n动画制作：手冢PRODUCTIONS","tag2s":[],"tags":[],"title":"反派大小姐莉泽洛特与实况解说","total_count":"12","update_pattern":"每周六 01:55更新","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 13_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
debug: balh_mode  =>  default
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Chrome  109.0.5414.120
2. 国家/地区：中国大陆

**Comment by ipcjs** [comment]
#1166
