### ISSUE TITLE
无法看东南亚的，港澳台的都行

### ISSUE THREAD

**Issue by chunner** [ipcjs/bilibili-helper#1153]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss35591?spm_id_from=333.337.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad: Y generate_sub: Y enable_in_av: Y readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"与-天-争-锋","isLogin":true,"level":3,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=35591
debug: atRun: 1, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/view/app/season?access_key={{access_key}}&appkey=7d089525d3611b1c&area=th&build=1001310&force_host=2&mobi_app=bstar_a&platform=android&s_locale=zh_SG&season_id=35591&ts=1675945140&sign=4e10f51dcc0cd149a7bae05564461b92
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/playurl?access_key=9ee8616b2a38aa5040c7dcbbb0e73621&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=367282&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=120&ts=1675945141&sign=e40162e07a3e3afe85a412d9ad80925a
debug: /pgc/player/web/playurl origin block: true {"code":-404,"message":"啥都木有"}
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"format":"flv720","type":"DASH","result":"suee","video_codecid":7,"no_rexcode":0,"code":0,"message":0,"timelength":1421004,"quality":120,"accept_format":"hdflv2,flv,flv720,flv480,mp4","accept_quality":[112,80,64,32,16,6,5],"accept_description":["1080P(HD)","1080P","720P","480P","360P","240P","144P"],"support_formats":[{"description":"1080P(HD)","display_desc":"1080P(HD)","intact":false,"need_login":true,"need_vip":true,"new_description":"1080P(HD)","no_rexcode":false,"quality":112},{"description":"1080P","display_desc":"1080P","intact":false,"need_login":true,"need_vip":true,"new_description":"1080P","no_rexcode":false,"quality":80},{"description":"720P","display_desc":"720P","intact":false,"need_login":true,"need_vip":false,"new_description":"720P","no_rexcode":false,"quality":64},{"description":"480P","display_desc":"480P","intact":false,"need_login":false,"need_vip":false,"new_description":"480P","no_rexcode":false,"quality":32},{"description":"360P","display_desc":"360P","intact":false,"need_login":false,"need_vip":false,"new_description":"360P","no_rexcode":false,"quality":16},{"description":"240P","display_desc":"240P","intact":false,"need_login":false,"need_vip":false,"new_description":"240P","no_rexcode":false,"quality":6},{"description":"144P","display_desc":"144P","intact":false,"need_login":false,"need_vip":false,"new_description":"144P","no_rexcode":false,"quality":5}],"dash":{"duration":1421,"minBufferTime":1.5,"min_buffer_time":1.5,"audio":[{"backup_url":[],"bandwidth":194228,"base_url":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2d1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=5280cf6ef1519c2d51a89e43659d7edf&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=bff9df5eef311552410f18da1f8bfceef44cb53bc867cbc854813fa0f346b0c7&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":0,"id":30280,"md5":"","size":34501221,"backupUrl":[],"baseUrl":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2d1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=5280cf6ef1519c2d51a89e43659d7edf&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=bff9df5eef311552410f18da1f8bfceef44cb53bc867cbc854813fa0f346b0c7&bvc=vod&nettype=0&orderid=0,2&logo=00000000","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"codecs":"mp4a.40.2","mimeType":"audio/mp4","mime_type":"audio/mp4","frameRate":"","frame_rate":"","height":0,"width":0},{"backup_url":[],"bandwidth":104600,"base_url":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2c1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=daabd3ec48d0cc976bc03650249b0407&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=cea6d9858f291d9dfa0a4396f95278f7859cec0a6ed392e6ead1d3586f72e6e9&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":0,"id":30232,"md5":"","size":18580464,"backupUrl":[],"baseUrl":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2c1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=daabd3ec48d0cc976bc03650249b0407&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=cea6d9858f291d9dfa0a4396f95278f7859cec0a6ed392e6ead1d3586f72e6e9&bvc=vod&nettype=0&orderid=0,2&logo=00000000","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"codecs":"mp4a.40.2","mimeType":"audio/mp4","mime_type":"audio/mp4","frameRate":"","frame_rate":"","height":0,"width":0},{"backup_url":[],"bandwidth":45687,"base_url":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2a1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=bc1d226ebd7949fc98b8dcd11bb06e00&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=bf27455802d52452bc1e94ee86289afb5501407bb4de2bb480527e5448d1c8c1&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":0,"id":30216,"md5":"","size":8115966,"backupUrl":[],"baseUrl":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2a1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=bc1d226ebd7949fc98b8dcd11bb06e00&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=bf27455802d52452bc1e94ee86289afb5501407bb4de2bb480527e5448d1c8c1&bvc=vod&nettype=0&orderid=0,2&logo=00000000","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"codecs":"mp4a.40.2","mimeType":"audio/mp4","mime_type":"audio/mp4","frameRate":"","frame_rate":"","height":0,"width":0}],"video":[{"audio_id":30280,"backup_url":[],"bandwidth":1901699,"base_url":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-261210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=f677dc53e5decd688bae50ea37f31e60&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=4baa144ad2a587261f242150003eac4f48e597f78b6436cca6729fed8fa92543&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":7,"md5":"","size":337790120,"backupUrl":[],"baseUrl":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-261210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=f677dc53e5decd688bae50ea37f31e60&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=4baa144ad2a587261f242150003eac4f48e597f78b6436cca6729fed8fa92543&bvc=vod&nettype=0&orderid=0,2&logo=00000000","id":112,"codecs":"avc1.640028","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"width":1920,"height":1080,"mimeType":"video/mp4","mime_type":"video/mp4","frameRate":"16000/672","frame_rate":"16000/672","sar":"1:1","startWithSAP":1,"start_with_sap":1,"start_with_s_a_p":1},{"audio_id":30232,"backup_url":[],"bandwidth":1215954,"base_url":"https://upos-sz-mirroralibstar1.bilivideo.com/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-251210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=alibstar1bv&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=066b94126252622f818f61c0090db469&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":7,"md5":"","size":215984289,"backupUrl":[],"baseUrl":"https://upos-sz-mirroralibstar1.bilivideo.com/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-251210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=alibstar1bv&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=066b94126252622f818f61c0090db469&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000","id":80,"codecs":"avc1.640028","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"width":1920,"height":1080,"mimeType":"video/mp4","mime_type":"video/mp4","frameRate":"16000/672","frame_rate":"16000/672","sar":"1:1","startWithSAP":1,"start_with_sap":1,"start_with_s_a_p":1},{"audio_id":30232,"backup_url":[],"bandwidth":341684,"base_url":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-241210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=e2df176020ef0c2714e4c60c647b4d80&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=e5adedc0d5d497b9b5e447fddb98b597ee6e48b9bede9346d06214d6e38d3508&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":7,"md5":"","size":60691888,"backupUrl":[],"baseUrl":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-241210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=e2df176020ef0c2714e4c60c647b4d80&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=e5adedc0d5d497b9b5e447fddb98b597ee6e48b9bede9346d06214d6e38d3508&bvc=vod&nettype=0&orderid=0,2&logo=00000000","id":64,"codecs":"avc1.64001F","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"width":1280,"height":720,"mimeType":"video/mp4","mime_type":"video/mp4","frameRate":"16000/672","frame_rate":"16000/672","sar":"1:1","startWithSAP":1,"start_with_sap":1,"start_with_s_a_p":1},{"audio_id":30216,"backup_url":[],"bandwidth":189690,"base_url":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-231210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=7868c17c699d526a19e20117e18a9082&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=891dc952d0207dbf373c3b73025387587ce22e0691ae133766d6007bd3535f70&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":7,"md5":"","size":33693911,"backupUrl":[],"baseUrl":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-231210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=7868c17c699d526a19e20117e18a9082&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=891dc952d0207dbf373c3b73025387587ce22e0691ae133766d6007bd3535f70&bvc=vod&nettype=0&orderid=0,2&logo=00000000","id":32,"codecs":"avc1.64001E","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"width":852,"height":480,"mimeType":"video/mp4","mime_type":"video/mp4","frameRate":"16000/672","frame_rate":"16000/672","sar":"1:1","startWithSAP":1,"start_with_sap":1,"start_with_s_a_p":1},{"audio_id":30216,"backup_url":[],"bandwidth":130155,"base_url":"https://upos-sz-mirroralibstar1.bilivideo.com/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-211210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=alibstar1bv&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=1747c58da097604ec7a31d6c483f5101&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":7,"md5":"","size":23118869,"backupUrl":[],"baseUrl":"https://upos-sz-mirroralibstar1.bilivideo.com/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-211210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=alibstar1bv&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=1747c58da097604ec7a31d6c483f5101&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000","id":16,"codecs":"avc1.64001E","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"width":640,"height":360,"mimeType":"video/mp4","mime_type":"video/mp4","frameRate":"16000/672","frame_rate":"16000/672","sar":"1:1","startWithSAP":1,"start_with_sap":1,"start_with_s_a_p":1},{"audio_id":30216,"backup_url":[],"bandwidth":74575,"base_url":"https://upos-sz-mirroralibstar1.bilivideo.com/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2e1210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=alibstar1bv&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=cef6156eb5019bfbacd5b9f00315279d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":7,"md5":"","size":13246534,"backupUrl":[],"baseUrl":"https://upos-sz-mirroralibstar1.bilivideo.com/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2e1210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=alibstar1bv&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=cef6156eb5019bfbacd5b9f00315279d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000","id":6,"codecs":"avc1.64001E","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"width":426,"height":240,"mimeType":"video/mp4","mime_type":"video/mp4","frameRate":"16000/672","frame_rate":"16000/672","sar":"1:1","startWithSAP":1,"start_with_sap":1,"start_with_s_a_p":1},{"audio_id":30216,"backup_url":[],"bandwidth":37829,"base_url":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2f1210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=b85a32759557331599e13dde7b0d6d18&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=9520defac08158fcbe1c26e690870e67591acf9baaed5617ddf24e8ee76cff22&bvc=vod&nettype=0&orderid=0,2&logo=00000000","codecid":7,"md5":"","size":6719518,"backupUrl":[],"baseUrl":"https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/xa/nh/n230114a2tl3rtfhe7k02lzvb5wxnhxa-1-2f1210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1675952162&gen=playurlv2&os=akam&oi=3108939111&trid=b365697a3dcd46c7963f7d9d7d2117cbi&mid=1189125371&platform=android&upsig=b85a32759557331599e13dde7b0d6d18&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1675952162~hmac=9520defac08158fcbe1c26e690870e67591acf9baaed5617ddf24e8ee76cff22&bvc=vod&nettype=0&orderid=0,2&logo=00000000","id":5,"codecs":"avc1.64001E","segment_base":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"SegmentBase":{"Initialization":"0--5.5","indexRange":"-4.5--5.5","initialization":"0--5.5","index_range":"-4.5--5.5"},"width":256,"height":144,"mimeType":"video/mp4","mime_type":"video/mp4","frameRate":"16000/672","frame_rate":"16000/672","sar":"1:1","startWithSAP":1,"start_with_sap":1,"start_with_s_a_p":1}]},"fnval":80,"fnver":0,"status":2,"vip_status":1,"vip_type":2,"seek_param":"start","seek_type":"offset","bp":0,"from":"local","has_paid":false,"is_preview":0},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/playurl?access_key=9ee8616b2a38aa5040c7dcbbb0e73621&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=367282&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=120&ts=1675945144&sign=19e1164214106b102088d35709e49d0e
debug: /x/web-interface/nav {"uname":"与-天-争-锋","isLogin":true,"level":3,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/playurl?access_key=9ee8616b2a38aa5040c7dcbbb0e73621&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=367282&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=120&ts=1675945145&sign=cd7a3e3d9af51f237623b6cf55562ab5
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/playurl?access_key=9ee8616b2a38aa5040c7dcbbb0e73621&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=367282&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=120&ts=1675945152&sign=6faaf31d46308601574748d51f9187c7
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/ogv/playurl?access_key=9ee8616b2a38aa5040c7dcbbb0e73621&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=367282&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=16&ts=1675945154&sign=279ad0a68bf9c8892e33651c7b413c4b
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.plus/intl/gateway/v2/app/subtitle?cid=0&aid=0&bvid=undefined&season_id=35591&ep_id=367282
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78

**Comment by JasonKhew96** [comment]
#906
