### ISSUE TITLE
不知为何突然开始对大陆番剧生效，导致页面错误

### ISSUE THREAD

**Issue by Adiwon** [ipcjs/bilibili-helper#1166]
如题，打开大陆普通番剧似乎也会生效，导致页面错误（已经有人反映过评论区消失），标签页标题出现【A站独播】前缀，我还碰到了视频同时播放正常音频和该视频另一时间点开始的音频，以及暂停视频后还会继续播放那个不同时间点开始的音频的诡异问题。
- 问题网址：
https://www.bilibili.com/bangumi/play/ep736320  （其中一例，实际上对所有大陆番剧都生效）

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.3.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md979/?spm_id_from=666.25.b_6d656469615f6d6f64756c65.1
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=979&access_key={{access_key}}
debug: atRun: 1, interactive
debug: fetch https://api.bilibili.com/x/web-interface/wbi/search/default?w_rid=c935f7a4438960f8f42d931ee70472a4&wts=1677255476 {"params":{"w_rid":"c935f7a4438960f8f42d931ee70472a4","wts":"1677255476"},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/wbi/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956,5672&w_rid=2ed70481f28551485d75b206af72a191&wts=1677255476 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956,5672","w_rid":"2ed70481f28551485d75b206af72a191","wts":"1677255476"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"xxxx","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":1,"follow_status":2,"login":1,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":87415,"last_ep_index":"12","last_time":184},"real_price":"0","sponsor":0,"vip_info":{"due_date":1699718400000,"status":1,"type":2}}}
debug: setAreaLimitSeason 000 false
debug: /x/web-interface/nav {"uname":"xxxx","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=766289266112200772&video_offset=0&article_offset=0 {"params":{"alltype_offset":"766289266112200772","video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/web-interface/pcdn/v1 {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=766289266112200772&video_offset=0&article_offset=0 {"params":{"alltype_offset":"766289266112200772","video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}

## 其他

1. 浏览器版本：版本 5.0.1002.295（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)
2. 国家/地区：中国大陆

**Comment by SagarZhang** [comment]
我也遇到了大陆番剧也会跳转的问题，即便是暂停播放，后台仍然会继续播放声音。
而且自动跳过片头、片尾这种功能对后台的声音也是有效的。

**Comment by ouyen** [comment]
+1

**Comment by ouyen** [comment]
我猜测是b站的相关检测接口改了 这边没有适配, 希望能改成基于名称的规则

**Comment by bin3826246** [comment]
同样的问题，似乎是在正常打开大陆番剧后，脚本又重新打开了一个播放页面，后一个页面会显示A站独播并且评论区无法显示。应该是脚本把大陆番剧也代理了，希望作者大大能尽快修复一下。

**Comment by ouyen** [comment]
在退出账户 情理cookie之后用一些插件改了UA: 
```
{
"https://www.bilibili.com/*":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
}
```

之后就正常了, 猜测是B站对一些UA开始了一些测试性功能

**Comment by ouyen** [comment]
或许和UA没关系 清除所有浏览数据& 重新登录就可以?

**Comment by superpowermeatball** [comment]
> 或许和UA没关系 清除所有浏览数据& 重新登录就可以?

我清除了一个月之前的cookie以及重新登录，也没用，為什麼我改UA也沒用（倒地）

**Comment by Cancanneed16** [comment]
看弹幕的版本感觉是到泰国/东南亚区去了，而且背后的原页面也没被关掉（等于叠了两），随便按按键后面的就从头开始放了，所以会碰到两段重叠播放的问题

**Comment by SNOCEI** [comment]
+1

**Comment by SNOCEI** [comment]
我觉得应该是大陆的页面正常播放时同时对番剧进行了解析跳转导致同时有两路视频播放，但原来的那一路因为被解析后的界面覆盖导致我们没法控制所以出现了暂停后还有声音等，嘛，要人家来解决才知道是什么问题，我在这也只能猜

**Comment by LiXuefei007** [comment]
+1

**Comment by luckyuptop** [comment]
+1

**Comment by JasonKhew96** [comment]
经过调查，B站 web 页面 改版 了，非常棒，我不是很想修这个，依赖这个的 远古代码 很多

**Comment by ipcjs** [comment]
😂，我刚开始看问题，依赖哪个？

**Comment by JasonKhew96** [comment]
> 😂，我刚开始看问题，依赖哪个？

`__initial_state__` 没了，好多都针对这个判断

**Comment by ipcjs** [comment]
那就判断有没有这个变量😎️
只要不报错就行（

**Comment by ipcjs** [comment]
姑且算是跳过新页面了，有什么新问题再看👀️
b1043f64a4f9ae4afc3892ac5c52c4fc83c0f969

**Comment by JasonKhew96** [comment]
> 姑且算是跳过新页面了，有什么新问题再看👀️
> b1043f64a4f9ae4afc3892ac5c52c4fc83c0f969

不对呀，他好像是个 `<script />`

**Comment by ipcjs** [comment]
页面里面有代码会读取它，变成window的一个属性（

**Comment by superpowermeatball** [comment]
> 页面里面有代码会读取它，变成window的一个属性（

更新了之后确实不会跳转A站了可是也没运行了是怎么回事？是需要额外设置一些东西吗

**Comment by ipcjs** [comment]
@superpowermeatball 😄️，发链接来看下

**Comment by superpowermeatball** [comment]
> @superpowermeatball 😄️，发链接来看下

https://www.bilibili.com/bangumi/play/ep736811?from_spmid=666.19.0.0 
我是翻回去看大陸番剧的，点开好几个了都是没有设置页面，脚本也没有在运行，麻烦大大看一下

**Comment by ipcjs** [comment]
@superpowermeatball 8.4.0 能跑了，还有什么问题，下次再说吧（

**Comment by superpowermeatball** [comment]
> 

太強了，感謝感謝，辛苦了！！

**Comment by alleles-squall** [comment]
从8.3.10开始翻回大陆/港澳台就失效了，显示无法正常播放，页面没有悬浮按钮，8.4.0和8.4.1也是一样
https://www.bilibili.com/bangumi/play/ss42105
https://www.bilibili.com/bangumi/play/ep745300

自己测试了一下，问题在新加的` && !window.__NEXT_DATA__`，没有触发改写页面的方法，新页面的方法看起来还不是很完善啊（

其实完全改写页面的方法还能用，8.3.9只是不能显示评论区，还有些字符乱码但无伤大雅，评论区的问题我在 #1165 写了个暂时的方法，或许能加一个选项强制使用改写页面？
