### ISSUE TITLE
突然对电影和大陆番剧生效

### ISSUE THREAD

**Issue by d-s-blade** [ipcjs/bilibili-helper#1174]
脚本问题：如题 @ipcjs

## 描述

突然开始对大陆番剧和电影生效了，评论区加载不出来，而且长按→加速视频的功能也无法使用了
- 问题网址：
https://www.bilibili.com/bangumi/play/ss42105/?spm_id_from=333.999.0.0
举个栗子
## 日志
日志太长了提交不了
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by 15938791776** [comment]
我一样啊，昨天下午突然

**Comment by qbdiamond** [comment]
有时甚至会对直播生效，会出现无法加载直播播放器的问题

**Comment by tempurai** [comment]
我也是，还会有双重播放

**Comment by ipcjs** [comment]
#1166
