### ISSUE TITLE
能不能改进一下脚本？

### ISSUE THREAD

**Issue by haoxiaoyueh** [ipcjs/bilibili-helper#1181]
脚本问题：@ipcjs

## 描述

无法查看泰区，能不能改进一下脚本，我填了东南亚的接口但是看不了，能不能改成我填了接口脚本就能自己解析
我看了另一个提出这个问题的和解决方法，但是……我看不懂啊，所以能不能改进一下脚本，话说明明有一个东南亚的接口api，但是为什么填了也用不了啊～
- 问题网址：
https://www.bilibili.com/bangumi/play/ep379275

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

![无法加载](https://user-images.githubusercontent.com/113106402/225362071-dadb4622-7a24-4ffb-a1fb-7446ad6875d9.png)
## 其他

1. 浏览器版本：Microsoft Edge版本 110.0.1587.69 (正式版本) (64 位)
2. 国家/地区：中国/江苏

**Comment by bilibili2233a** [comment]
油猴脚本不会用是怎么回事呢？油猴脚本相信大家都很熟悉，但是不会用是怎么回事呢？下面就让小编带大家一起了解吧。 

油猴脚本不会用，其实就是不会用了。那么油猴脚本为什么会不会用，相信大家都很好奇是怎么回事。大家可能会感到很惊讶，油猴脚本怎么会不会用呢？但事实就是这样，小编也感到非常惊讶。那么这就是关于油猴脚本不会用的事情了，大家有没有觉得很神奇呢？

看了今天的内容，大家有什么想法呢？欢迎在评论区告诉小编一起讨论哦。

**Comment by haoxiaoyueh** [comment]
> 油猴脚本不会用是怎么回事呢？油猴脚本相信大家都很熟悉，但是不会用是怎么回事呢？下面就让小编带大家一起了解吧。
> 
> 油猴脚本不会用，其实就是不会用了。那么油猴脚本为什么会不会用，相信大家都很好奇是怎么回事。大家可能会感到很惊讶，油猴脚本怎么会不会用呢？但事实就是这样，小编也感到非常惊讶。那么这就是关于油猴脚本不会用的事情了，大家有没有觉得很神奇呢？
> 
> 看了今天的内容，大家有什么想法呢？欢迎在评论区告诉小编一起讨论哦。

逆天，正经一点啊!
