### ISSUE TITLE
番剧页面看不到设置按钮

### ISSUE THREAD

**Issue by CyclonicPinna** [ipcjs/bilibili-helper#1184]
脚本为8.4.0版本，在B站番剧页面右下角看不到设置按钮。原本是有的，不清楚是脚本原因还是B站番剧页面有更新。浏览器版本为Chrome 109.0.5414.120。目前可以解除区域限制，说明脚本应该还在工作，但因为没有设置按钮所以无法修改设置或导出log。

另外在尝试期间发现ss+数字形式的番剧页面似乎无法解除限制（例如：www.bilibili.com/bangumi/play/ss44081），但同一部番剧如果换成ep+数字形式的页面就可以解除限制（例如：www.bilibili.com/bangumi/play/ep719185）。

**Comment by tkp206093** [comment]
+1

**Comment by hen0920** [comment]
+1 开控制台时显示【解除B站区域限制 interactive 加载时机不太对, 不能保证正常工作】

另外在已经解除限制的番剧页可以正常显示设置按钮（对于新用户来说没法设置又怎么进港澳台页面呢orz）

**Comment by CyclonicPinna** [comment]
> +1 开控制台时显示【解除B站区域限制 interactive 加载时机不太对, 不能保证正常工作】
> 
> 另外在已经解除限制的番剧页可以正常显示设置按钮（对于新用户来说没法设置又怎么进港澳台页面呢orz）

我这边是已经解除限制的番剧页也不显示设置按钮，但因为以前设置过所以目前暂时还能用。

**Comment by Energy0124** [comment]
+1, 看不到设置按钮
`info: mode: default blocked_vip: undefined server: https://www.biliplus.com upos_server: undefined flv_prefer_ws:  remove_pre_ad: undefined generate_sub: undefined enable_in_av: undefined readyState: loading isLogin: false isLoginBiliBili: true`

**Comment by ipcjs** [comment]
京吹页面也看不到设置按钮？
https://www.bilibili.com/bangumi/media/md5551

**Comment by SNL0** [comment]
> 京吹页面也看不到设置按钮？ https://www.bilibili.com/bangumi/media/md5551

番剧总页面都可以看到设置按钮，但是视频播放页面的右下角按钮没有了。

**Comment by CyclonicPinna** [comment]
> 京吹页面也看不到设置按钮？ https://www.bilibili.com/bangumi/media/md5551

番剧信息页面（例如：www.bilibili.com/bangumi/media/md5551）能看到设置按钮，但点进实际播放页面（例如第二季第一话：www.bilibili.com/bangumi/play/ep96703）页面右下角就看不到设置按钮了。

**Comment by yuanyao56** [comment]
> 京吹页面也看不到设置按钮？ https://www.bilibili.com/bangumi/media/md5551

同样看不到。console里有user script的error log
```
userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:252` warn: danmukuBox not found!
(anonymous) @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:252
(anonymous) @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:2258
(anonymous) @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:682
Fp @ bili-footer.umd.js:1
__awaiter @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:678
(anonymous) @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:2062
(anonymous) @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:693
(anonymous) @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:1380
dcl @ userscript.html?name=%25E8%25A7%25A3%25E9%2599%25A4B%25E7%25AB%2599%25E5%258C%25BA%25E5%259F%259F%25E9%2599%2590%25E5%2588%25B6.user.js&id=bda5e156-008f-4911-b8de-108e4d5c20f9:1380
```

**Comment by CyclonicPinna** [comment]
更新了8.4.1版本，目前设置按钮的问题还是一样，番剧信息页面（例如京吹：www.bilibili.com/bangumi/media/md5551）能看到设置按钮，但点进实际播放页面（例如第二季第一话：www.bilibili.com/bangumi/play/ep96703）页面右下角就看不到设置按钮了。

另外部分ss+数字形式的番剧页面似乎可以解除限制（例如柯南：www.bilibili.com/bangumi/play/ss33378），也有部分仍然无法解除限制（例如反派大小姐莉泽洛特与实况解说：www.bilibili.com/bangumi/play/ss44081）。ep+数字形式的页面可以解除限制（例如同一集反派大小姐莉泽洛特与实况解说：www.bilibili.com/bangumi/play/ep719185）。

**Comment by tkp206093** [comment]
> 更新了8.4.1版本，目前设置按钮的问题还是一样，番剧信息页面（例如京吹：www.bilibili.com/bangumi/media/md5551）能看到设置按钮，但点进实际播放页面（例如第二季第一话：www.bilibili.com/bangumi/play/ep96703）页面右下角就看不到设置按钮了。
> 
> 另外部分ss+数字形式的番剧页面似乎可以解除限制（例如柯南：www.bilibili.com/bangumi/play/ss33378），也有部分仍然无法解除限制（例如反派大小姐莉泽洛特与实况解说：www.bilibili.com/bangumi/play/ss44081）。ep+数字形式的页面可以解除限制（例如同一集反派大小姐莉泽洛特与实况解说：www.bilibili.com/bangumi/play/ep719185）。

+1

**Comment by 10000tao** [comment]
+1，目前我都是F12在console里用以下命令来打开设置。
```
bangumi_area_limit_hack.showSettings()
```
