### ISSUE TITLE
A 站独播视频的弹幕字号异常

### ISSUE THREAD

**Issue by NagatoYukiZero** [ipcjs/bilibili-helper#1186]
脚本问题：@ipcjs

## 描述

A 站独播视频的弹幕比正常的视频的弹幕大

正常情况
![image](https://user-images.githubusercontent.com/66565221/226109208-6a23a98c-8434-4d7a-ab2a-e229d926763e.png)

异常情况
![image](https://user-images.githubusercontent.com/66565221/226109172-1bae60a8-a2a0-4c07-84bb-d7c7a4d00cc8.png)

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
2. 国家/地区：中国大陆

**Comment by DarknessLeaf** [comment]
我这里这个问题已经很长时间了QAQ

**Comment by haoxiaoyueh** [comment]
这个问题好久了，一般我是直接调成60%就会和正常情况100%一样大了，可以这么先用着

**Comment by ipcjs** [comment]
没感觉呀，哪部？网址放下？

**Comment by NagatoYukiZero** [comment]
> 没感觉呀，哪部？网址放下？

您这那边测试不出来吗,我这边只要是 A站独播 的视频弹幕字号都很大

正常国内视频: https://www.bilibili.com/bangumi/play/ss1547/
异常港澳台视频: https://www.bilibili.com/bangumi/play/ss43175/

正常:
![image](https://user-images.githubusercontent.com/66565221/236184189-fe0589a1-0c74-4df0-8c93-43d871f32bd5.png)

异常:
![image](https://user-images.githubusercontent.com/66565221/236184117-164ca2bf-ccb3-4be2-a928-1478dc5a9cc8.png)

**Comment by JasonKhew96** [comment]
播放器 版本 不一样啊（因为 重建页面 用的 老版本
