### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

### ISSUE THREAD

**Issue by 1364012873** [ipcjs/bilibili-helper#1196]
脚本问题：@ipcjs

## 描述

- 问题网址：
https://www.bilibili.com/bangumi/play/ss44959

## 日志
debug: atRun: -1, loading debug: [解除B站区域限制 v8.4.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss44959 debug: window.__playinfo__  debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true} info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: ali flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)} debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)} debug: /x/web-interface/nav {"uname":"1364012873","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false} debug: atRun: 0, interactive debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)} debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=44959 debug: atRun: 1, interactive debug: __playinfo__ get debug: /pgc/player/web/playurl debug: season_type: 1 info: player msg: 从自定义服务器拉取视频地址中... info: player msg: 使用首选代理服务器拉取视频地址... debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)} debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?cid=1084814623&qn=112&type=&otype=json&fourk=1&bvid=BV1Nc411W7Pc&ep_id=743312&fnver=0&fnval=80&session=b514d3386a13af27af82ad41b2873590&module=bangumi&area=&access_key={{access_key}} debug: atRun: 2, complete debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"} debug: __playinfo__ set debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)} debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)} debug: __playinfo__ get debug: __playinfo__ get debug: __playinfo__ get debug: __playinfo__ get debug: __playinfo__ get debug: __playinfo__ get debug: __playinfo__ get debug: season_type: 1 debug: playurl add 'module=bangumi' param info: player msg: 从自定义服务器拉取视频地址中... info: player msg: 使用首选代理服务器拉取视频地址... debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)} debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=undefined&cid=1084814623&bvid=BV1Nc411W7Pc&qn=112&type=&otype=json&ep_id=743312&fourk=1&fnver=0&fnval=80&session=b7e3d9b3888d3c6ba51e43b1c0a5f059&module=bangumi&balh_ajax=1&area=&access_key=c042facc1762656ae267663f237d8341 debug: /x/web-interface/nav {"uname":"1364012873","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false} debug: /bfs/subtitle https://i0.hdslb.com/bfs/subtitle/b38b1fcea7cbe50a8eede2ca44b0fedd85487d6e.json debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ConstasJ** [comment]
最近好像不少人都遇到了这个问题……光issue就开了4个
@ipcjs 作者不考虑来修一下吗？
我觉得可能是Roaming的服务器改了什么东西
