### ISSUE TITLE
作者是弃坑了吗。。。

### ISSUE THREAD

**Issue by XuuChannel** [ipcjs/bilibili-helper#1199]
## 描述
番剧播放页没有设置按钮
任何服务器都无法解析番剧 返回 {"code":-1,"error":{"readyState":0,"status":0,"statusText":"error"}}
集数为ss格式的番剧播放页中脚本直接失效
edge浏览器&tampermonkey均为最新版本

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.4.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md20202282
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=45000&access_key={{access_key}}
debug: atRun: 1, interactive
debug: fetch https://api.bilibili.com/x/web-interface/wbi/search/default?w_rid=82db519f37034296869f23f879d7ea6e&wts=1681551955 {"params":{"w_rid":"82db519f37034296869f23f879d7ea6e","wts":"1681551955"},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"signal":{}}
debug: fetch https://api.bilibili.com/x/web-show/wbi/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956,5672&w_rid=7ac7933b58dc90a96f0f9a065ee8c24e&wts=1681551955 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956,5672","w_rid":"7ac7933b58dc90a96f0f9a065ee8c24e","wts":"1681551955"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: /x/web-interface/nav {"uname":"XuuChannel","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":4,"follow":1,"follow_status":2,"login":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":744510,"last_ep_index":"2","last_time":0},"real_price":"0","sponsor":0,"vip_info":{"due_date":1682697600000,"status":1,"type":2}}}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"XuuChannel","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=784391316315308200&article_offset=0 {"params":{"alltype_offset":0,"video_offset":"784391316315308200","article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=784391316315308200&article_offset=0 {"params":{"alltype_offset":0,"video_offset":"784391316315308200","article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}
debug: season45000 {"code":0,"message":"success","result":{"actor":[],"alias":"マッシュル","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"6583","bangumi_title":"肌肉魔法使-MASHLE-（僅限港澳台地區）","brief":"在這眾人都會魔法的世界，魔力高低成為了衡量地位的標準，而不會使用魔法的人則會遭到處決。馬修天生不會使...","business_type":1,"copyright":"bilibili","cover":"https://i0.hdslb.com/bfs/bangumi/image/6f7005db11c98463e3d5098dee4c639e1a41dc4d.png","danmaku_count":"-1","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"354925287","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0905cfee85bec7b086ba8aafdac42f16b5557c67.png","danmaku":"1095272696","episode_id":"744510","episode_status":13,"episode_type":0,"from":"bangumi","index":"2","index_title":"馬修·班迪德與神奇迷宮","is_new":"1","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2023-04-15 00:30:01.0"},{"av_id":"439644678","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/1e321924a8426c44f9c2713e22b096fd2aa8fd08.png","danmaku":"1085863450","episode_id":"744509","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"馬修·班迪德與千錘百鍊的肌肉","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2023-04-08 00:30:01.0"}],"evaluate":"在這眾人都會魔法的世界，魔力高低成為了衡量地位的標準，而不會使用魔法的人則會遭到處決。馬修天生不會使用魔法，被養父藏匿起來照顧。他為了自己跟家人能平安生活，決定用長年鍛煉出來的一身肌肉與世界抗衡。","favorites":"-1","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"マッシュル","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[],"cover":"https://i0.hdslb.com/bfs/bangumi/image/6f7005db11c98463e3d5098dee4c639e1a41dc4d.png","episode_index":{"index_show":"连载中"},"media_id":20202282,"publish":{"is_finish":0,"is_started":1},"title":"肌肉魔法使-MASHLE-（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"744510","newest_ep_index":"2","origin_name":"マッシュル","payment":{"price":"0","promotion":"","tip":"大会员专享观看特权哦~","vip_promotion":"成为大会员抢先看"},"play_count":"-1","pub_string":"","pub_time":"2023-04-08 00:30:00","pub_time_show":"4月8日 00:30 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"45000","season_status":13,"season_title":"TV","seasons":[{"bangumi_id":"6583","cover":"https://i0.hdslb.com/bfs/bangumi/image/6f7005db11c98463e3d5098dee4c639e1a41dc4d.png","is_finish":"0","is_new":"1","newest_ep_id":"744510","newest_ep_index":"2","season_id":"45000","season_status":13,"title":"TV","total_count":"24"}],"share_url":"http://bangumi.bilibili.com/anime/45000/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/014d2ec963258e5fe3e5847d95e7b349fd978005.png","staff":"","tag2s":[],"tags":[],"title":"肌肉魔法使-MASHLE-（僅限港澳台地區）","total_count":"24","update_pattern":"","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.34
debug:   =>  
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include","signal":{}}

**Comment by catnotgo** [comment]
你自己搜索公共解析服务器有能用的，
我也有一个问题，开这个脚本进港澳台时不能长按3倍数了，请问是b站港澳台本身就没有这功能吗
