### ISSUE TITLE
在观看东南亚番剧时无法拉取视频地址：拉取视频地址失败 原因：{}

### ISSUE THREAD

**Issue by luobo156** [ipcjs/bilibili-helper#1221]
脚本问题：@ipcjs

## 描述

脚本在拉取东南亚视频地址的时候无法拉取地址，并且没有原因与错误代码，判断是脚本问题，以下是脚本拉取东南亚番剧《我推的孩子》第8集的日志，可以看出解析服务器返回的地址是可以看到视频地址的（替换地址upos可以下载到dash视频并播放），而脚本没有正常播放，已使用upos重定向将泰区upos替换，另外，脚本在重建泰区番剧页时大概率卡在银魂的缓存页面（详细见截图）少概率正常
- 问题网址：https://www.bilibili.com/bangumi/play/ss2080019

## 日志

<details>
<summary>Verbose 日志</summary>

```

<!--点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标） -->

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.4.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss2080019?spm_id_from=333.337.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"萝卜小小_","isLogin":true,"level":6,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=2080019
debug: atRun: 1, interactive
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.mahiro-kawaii.me/intl/gateway/v2/ogv/view/app/season?access_key={{access_key}}&appkey=7d089525d3611b1c&area=th&build=1001310&force_host=2&mobi_app=bstar_a&platform=android&s_locale=zh_SG&season_id=2080019&ts=1686566156&sign=dc5d30eb6a27bdc345642b0e49408893
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-404,"message":"啥都木有"}
debug: setAreaLimitSeason ss2080019 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.mahiro-kawaii.me/intl/gateway/v2/ogv/playurl?access_key=ae61655f8b03f276803a83d7ade6a551&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=12785555&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=120&ts=1686566160&sign=fb0549e28ec7f834ab78d2a826620816
debug: /x/web-interface/nav {"uname":"萝卜小小_","isLogin":true,"level":6,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: /pgc/player/web/playurl origin block: undefined {"code":-404,"message":"啥都木有"}
debug: setAreaLimitSeason ep12786203 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.mahiro-kawaii.me/intl/gateway/v2/ogv/playurl?access_key=ae61655f8b03f276803a83d7ade6a551&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=12786203&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=120&ts=1686566166&sign=be1dbc50bbf3ab1210e7390bcb8a76c5
debug: {"code":-404,"message":"啥都木有"}
debug: setAreaLimitSeason ep12786203 true
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.mahiro-kawaii.me/intl/gateway/v2/ogv/playurl?access_key=ae61655f8b03f276803a83d7ade6a551&appkey=7d089525d3611b1c&area=th&build=1001310&cid=0&ep_id=12785555&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=120&ts=1686566166&sign=158ef27879dd646066913230f8b36ed0
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15

```

</details>

控制台截图＆番剧页正常截图：
![屏幕截图 2023-06-11 210110](https://github.com/ipcjs/bilibili-helper/assets/91001447/a0c00aeb-6b34-4e52-8fdf-3f53fc965aa2)
![屏幕截图 2023-06-11 210347](https://github.com/ipcjs/bilibili-helper/assets/91001447/1043194f-e175-4419-909b-5822b1dd2b9c)

番剧页不能正常重建截图：
![屏幕截图 2023-06-11 210211](https://github.com/ipcjs/bilibili-helper/assets/91001447/e28ea01f-ba54-4fb4-877c-7f33cc086cd9)

解析服务器返回数据截图：
![屏幕截图 2023-06-11 205921](https://github.com/ipcjs/bilibili-helper/assets/91001447/a5dc109c-49d1-4f3c-b621-a3c7d5152308)
![屏幕截图 2023-06-11 205930](https://github.com/ipcjs/bilibili-helper/assets/91001447/e12db2f9-aea7-481e-8c22-5849d8b65606)
![屏幕截图 2023-06-11 205940](https://github.com/ipcjs/bilibili-helper/assets/91001447/7b85d077-5284-4de4-a1e5-b6d22ba006e5)
![屏幕截图 2023-06-11 205952](https://github.com/ipcjs/bilibili-helper/assets/91001447/f4f350c3-cde0-406c-b8d1-5c25704dd203)

## 其他

1. 浏览器版本：Microsoft Edge 114.0.1823.43
2. 国家/地区：中国

**Comment by luobo156** [comment]
我超什么时候能用了？是服务器修复了？因为今天发现我用的那个解析服务器泰区移动端也看不了，就换了个服务器，结果居然能用了？？？服务器是：melusine.moe
![屏幕截图 2023-06-14 191443](https://github.com/ipcjs/bilibili-helper/assets/91001447/e1d654ad-fcf1-4567-bc6a-b2a93bcfad80)

**Comment by luobo156** [comment]
这是我自己改的upos替换脚本，要安装modheader，将upos替换为了华为的upos，另外将泰区所有已知upos服务器都添加进去了
(https://modheader.com/profile/d2fe2632-f8d0-4286-8577-4f4a955566cf)

**Comment by anibuta** [comment]
感谢大佬，大佬多研究点
试了下同一服务器，up提供的字幕pc不显示，老旧的番连官方字幕都不显示
说下modheader是可搞永久pro的

**Comment by luobo156** [comment]
> 
字幕问题我也遇到了，这个有点玄学，有时候有，有时候又没有，现在不知道怎么解决

**Comment by luobo156** [comment]
> 感谢大佬，大佬多研究点 试了下同一服务器，up提供的字幕pc不显示，老旧的番连官方字幕都不显示 说下modheader是可搞永久pro的

字幕问题我也遇到了，这个有点玄学，有时候有，有时候又没有，现在不知道怎么解决
现在的问题是这样的：不能切集，否则字幕会消失（大概率）而且如果直接输入番剧的ep号会弹出一个403的提示（进不了番剧页）
至于modheader我直接用没有会员的旧版，用的十分舒服

**Comment by luobo156** [comment]
另外番剧页不能正常重建的问题，我试了一下清除缓存，然后就正常了

**Comment by luobo156** [comment]
这些是可以成功解析东南亚番剧的服务器：
陈睿.我爱你 （最高4k）
api.mahiron.moe （最高4k）
伊蕾娜.我爱你 （最高720p）
melusine.moe （最高4k）
姬坂乃爱.我爱你 （最高480p）
hk.xifeng.cf （最高480p）
api.mahiro-kawaii.me （最高4k）
cherry.icu.cnmobile.link （最高4k）
除此之外好像就没几个了（另外这些服务器都是新加坡的，不能看全部的东南亚番剧）

**Comment by anibuta** [comment]
就很神奇😂

**Comment by luobo156** [comment]
> 就很神奇😂

陈睿.我爱你 这个服务器好像没有字幕问题，你试试

**Comment by anibuta** [comment]
> > 就很神奇😂
> 
> 陈睿.我爱你 这个服务器好像没有字幕问题，你试试

移动端是有up提供字幕的，比如带机翻或者字幕组的。泰区pc以前也是有的，这个还是没有，不过用插件自己加字幕也一样

**Comment by WeiRi** [comment]
> 这些是可以成功解析东南亚番剧的服务器： 陈睿.我爱你 （最高4k） api.mahiron.moe （最高4k） 伊蕾娜.我爱你 （最高720p） melusine.moe （最高4k） 姬坂乃爱.我爱你 （最高480p） hk.xifeng.cf （最高480p） 除此之外好像就没几个了（另外这些服务器都是新加坡的，不能看全部的东南亚番剧）

感谢分享服务器，现在能正常看港澳台的了

**Comment by anibuta** [comment]
报！！！3月10号后的更新的集数都看不了，大致是一个番剧的第10，11,12集。请大佬出山拯救东南亚orz

**Comment by anibuta** [comment]
> 报！！！3月10号后的更新的集数都看不了，大致是一个番剧的第10，11,12集。请大佬出山拯救东南亚orz

@luobo156

**Comment by anibuta** [comment]
https://github.com/ipcjs/bilibili-helper/issues/1321#issue-2177625576
