### ISSUE TITLE
BV番剧页面无法跳转

### ISSUE THREAD

**Issue by CyclonicPinna** [ipcjs/bilibili-helper#1228]
脚本问题：@ipcjs

## 描述
今天开始出现的问题，从BV番剧页面无法自动跳转至EP/SS页面。例如：www.bilibili.com/video/BV1jk4y1M7U2/，打开该页面提示“获取番剧页Url中...”，稍后会跳转到一个空的播放器页面（网址不变），然后循环报错。但是如果手动打开EP/SS页面则正常（例如上述BV页面对应的EP页面为：www.bilibili.com/bangumi/play/ep743310）。

- 问题网址：
BV番剧页面，例如：www.bilibili.com/video/BV1jk4y1M7U2/

## 日志
在上述的空播放器页面导出日志会卡死，似乎生成了大量可能重复的日志，不知道是否是循环报错的原因。因内容太长目前只能复制到记事本并以附件上传（记事本也会卡死一段时间）。另外上述的空播放器页面截图也放到附件中了。

[日志.txt](https://github.com/ipcjs/bilibili-helper/files/11901858/default.txt)

![跳转错误页面](https://github.com/ipcjs/bilibili-helper/assets/47832345/9ec03bd3-e0b5-447d-87b7-c189c4d9b773)

## 其他
脚本版本：8.4.3
浏览器版本：Chrome 109.0.5414.120

**Comment by cakesa** [comment]
我也出现了这个问题，而且发现如果重新进行账号授权的话，会出现“存储失败：网络错误”的问题，而且是这两天才出现的，以前用的好好地

**Comment by creasting** [comment]
@ipcjs 您好，我这边也出现了同样的情况，包括重新授权的错误提示也是一样的

**Comment by JasonKhew96** [comment]
早上 0931 UTC+8 biliplus API 被停了，现在 bv av 都没法转 ep 了

EDIT: 感觉是 biliplus 后端爆炸了

**Comment by JasonKhew96** [comment]
biliplus 修了，可以 close 了

**Comment by CyclonicPinna** [comment]
> biliplus 修了，可以 close 了

嗯，今天看正常了。
