### ISSUE TITLE
最近阿B好像更新了番剧页面导致脚本无法应用在新版页面上的样子（不过目前可以返回旧版）

### ISSUE THREAD

**Issue by RustDesert** [ipcjs/bilibili-helper#1238]
脚本问题：@ipcjs

## 描述
最近阿B好像是出了一个新的番剧页面，脚本貌似无法在新版页面使用的样子（右下角没有土星标签）。不过目前还有返回旧版的按钮所以可以回旧版看。旧版用起来是没有问题的。

1. 浏览器版本：Edge116.0.1938.69
2. 国家/地区：美国

**Comment by ShiratsuYudachi** [comment]
感谢提醒，通过返回旧版解决了x
