### ISSUE TITLE
总是播放“非常抱歉” 且无法授权账号

### ISSUE THREAD

**Issue by nokbokdy** [ipcjs/bilibili-helper#1243]
总是“非常抱歉”，同时浏览器不会弹出服务器请求错误的信息，目前也无法授权或取消账号

控制台显示：

warn: 解除B站区域限制 interactive 加载时机不太对, 不能保证正常工作

1. 尝试刷新页面, 重载脚本
2. 若依然出现该提示, 请尝试'硬性重新加载'(快捷键一般为ctrl+f5)
3. 若还是出现该提示, 请尝试关闭再重新打开该页面
4. 若反复出现该提示, 那也没其他办法了_(:3」∠)_

浏览器版本：Edge 117.0.2045.41
国家/地区：香港

**Comment by misakamisakamisakamisaka** [comment]
同
而且安卓（华为，鸿蒙3）那边（https://github.com/yujincheng08/BiliRoaming/wiki）也挂了：
请求解析中 服务器发生错误；

似乎有点关联

**Comment by Cancanneed16** [comment]
试试换成旧版？我就是这样解决的

**Comment by Mostilv** [comment]
同样遇到新版bilibili视频页面无法走代理，回到旧版后可以
