### ISSUE TITLE
账号无法授权

### ISSUE THREAD

**Issue by TTTTTTMDR** [ipcjs/bilibili-helper#1248]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by cxw620** [comment]
![image](https://github.com/ipcjs/bilibili-helper/assets/70561268/3d275764-bceb-4cd1-839c-9a8317fac6d1)

B 站已经停用了账号授权依赖的关键 API, 短时间内是没有任何方法解决此问题了, 各回各家各找各妈吧.

**Comment by JasonKhew96** [comment]
方法是有，但没人想修，除了登录部分，很多功能都半残废了，~~目前这脚本也没有修复的价值~~

**Comment by KurosakiRei** [comment]
七年B站海外党表示，B站现在这B样，而且还准备换新版UI和播放器，这脚本不修也罢，大会员都没准备续了

**Comment by cxw620** [comment]
那就都摆了, 服务端没需求也不用弄() 
新版 UI 啊, 加广告的 UI 吧...

**Comment by Jieryshark** [comment]
> ![image](https://user-images.githubusercontent.com/70561268/278666274-3d275764-bceb-4cd1-839c-9a8317fac6d1.png)
> 
> B 站已经停用了账号授权依赖的关键 API, 短时间内是没有任何方法解决此问题了, 各回各家各找各妈吧.

寄了
