### ISSUE TITLE
账号授权问题，临时解决方案

### ISSUE THREAD

**Issue by yxok200** [ipcjs/bilibili-helper#1249]
我最近不小心点了首页的试用新版，为了用回旧版就清除了cookie，然后也遇到了账号无法授权QAQ
通过翻阅过往lssuse#1103，虽然不是很懂原理，找到了一个比较简单的解决方案，能来到这的人，应该都能懂吧？

首先是根据lssuse#1103，我们可以得到如下手动授权命令  localStorage.access_key = "access_key" （F12  Console内使用）
然后就是access_key在哪里找的问题了，该脚本是通过mcbbs做的跳转，现在失效了，于是想起了biliplus也是授权登录

接下来就简单了，在biliplus授权登录，然后F12去cookie找access_key，把access_key的所有参数，一模一样的ctrlCV到B站去
然后回到之前失败的番剧页面，F12执行localStorage.access_key = "access_key"，就完事了

**Comment by AndrewOkiya** [comment]
感谢喵~

**Comment by YourDeepEnd** [comment]
游泳门槛再次提高

**Comment by AckerMikasa** [comment]
用这个授权出现"服务器内部错误: APPKEY失效"

**Comment by abpolars** [comment]
感谢佬，等了一下午，我还以为是网的问题

**Comment by MYuuuMY** [comment]
感谢，还以为这脚本没救了

**Comment by Suigetsusama** [comment]
还真是，牛的，谢谢大佬

**Comment by UesugiSun** [comment]
大佬，按照你说的去弄了access_key依旧没用，有没有联系方式可以远程一下，谢谢了

**Comment by jiangjiale884883** [comment]
感谢大佬，解决了，新机刚装完拷贝资料时发现脚本失效了，幸好自己懂点计算机。accesskey这一看相当于你的身份证号，每个人都是唯一的，虽然作者说B站停用了这个接口，但是已经存在的不影响（之前授权过的），我旧电脑里有着授权过得，按照楼主的方法把你自己的key从cookie中获取到，后面在新电脑上还是用楼主说的F12执行localStorage.access_key = "自己的key"就能正常用了，说不好用的一看就是key值=undefined（跟null一样）肯定是不好用的

**Comment by kkjzio** [comment]
上到去了，感谢！没想到是和biliplus一样的授权方式。。。

**Comment by ahshy1996** [comment]
解决了 感谢

**Comment by ahshy1996** [comment]
解决了 感谢

**Comment by 2yzjn** [comment]
呜，大佬我还真不懂localStorage.access_key是sm找不到

**Comment by 2yzjn** [comment]
大佬我还真不懂localStorage.access_key是什么，找不到

**Comment by 2yzjn** [comment]
> 我最近不小心点了首页的试用新版，为了用回旧版就清除了cookie，然后也遇到了账号无法授权QAQ 通过翻阅过往lssuse#1103，虽然不是很懂原理，找到了一个比较简单的解决方案，能来到这的人，应该都能懂吧？
> 
> 首先是根据lssuse#1103，我们可以得到如下手动授权命令 localStorage.access_key = “access_key” （F12 Console内使用） 然后就是access_key在哪里找的问题了，该脚本是通过mcbbs做的跳转，现在失效了，于是想起了biliplus也是授权登录
> 
> 接下来就简单了，在biliplus授权登录，然后F12去cookie找access_key，把access_key的所有参数，一模一样的ctrlCV到B站去 然后回到之前失败的番剧页面，F12执行localStorage.access_key = “access_key”，就完事了

大佬我还真不懂localStorage.access_key是什么，找不到

**Comment by 2yzjn** [comment]
大佬我还真不懂localStorage.access_key是什么，找不到

**Comment by 2yzjn** [comment]
> 大佬我还真不懂localStorage.access_key是什么，找不到

有在详细一点的教程吗

**Comment by DivineCandle** [comment]
同样出现code":-500,"message":"服务器内部错误: APPKEY失效

**Comment by DivineCandle** [comment]
> 同样出现code":-500,"message":"服务器内部错误: APPKEY失效

不使用biliplus而是使用mcbbs倒是很方便，在cookie中寻找一个带auth授权字样的就是access_key

**Comment by jayphone17** [comment]
牛逼

**Comment by paco2003123** [comment]
大佬能教學一下嗎 0程碼基礎看不明白

**Comment by SsseduDenEiketsu** [comment]
解决了。楼主说的很简洁明白了。
只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。
番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。

**Comment by Jarvan6666** [comment]
牛逼啊大佬，解决了

**Comment by paco2003123** [comment]
> 解决了。楼主说的很简洁明白了。 只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。 番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。

大佬你是用什麼插件把key扒出来來的?

**Comment by SsseduDenEiketsu** [comment]
> > 解决了。楼主说的很简洁明白了。 只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。 番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。
> 
> 大佬你是用什麼插件把key扒出来來的?

edit this cookie很简单好用的插件，任何人不用教程就会用。这个实际上原来是用来浏览器上跳过熊猫图在E站看本子用的插件。
登录biliplus后，点开插件直接就有一个项目叫做access_key，点开来里面就是一串key，直接复制就可以了。这个key应该是绑定账号不会变的，所以保存成文本文件在自己电脑里，以后就不用再重复所有这些操作了。

**Comment by Accelerator888** [comment]
> > > 解决了。楼主说的很简洁明白了。 只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。 番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。
> > 
> > 
> > 大佬你是用什麼插件把key扒出来來的?
> 
> edit this cookie很简单好用的插件，任何人不用教程就会用。这个实际上原来是用来浏览器上跳过熊猫图在E站看本子用的插件。 登录biliplus后，点开插件直接就有一个项目叫做access_key，点开来里面就是一串key，直接复制就可以了。这个key应该是绑定账号不会变的，所以保存成文本文件在自己电脑里，以后就不用再重复所有这些操作了。
大哥在biliplus复制后再返回番剧页面后再重复一遍操作把复制来的key替换吗😖

**Comment by Accelerator888** [comment]
> > > 解决了。楼主说的很简洁明白了。 只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。 番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。
> > 
> > 
> > 大佬你是用什麼插件把key扒出来來的?
> 
> edit this cookie很简单好用的插件，任何人不用教程就会用。这个实际上原来是用来浏览器上跳过熊猫图在E站看本子用的插件。 登录biliplus后，点开插件直接就有一个项目叫做access_key，点开来里面就是一串key，直接复制就可以了。这个key应该是绑定账号不会变的，所以保存成文本文件在自己电脑里，以后就不用再重复所有这些操作了。

大哥在biliplus复制后再返回番剧页面后再重复一遍操作把复制来的key替换吗😖

**Comment by SsseduDenEiketsu** [comment]
> > > > 解决了。楼主说的很简洁明白了。 只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。 番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。
> > > 
> > > 
> > > 大佬你是用什麼插件把key扒出来來的?
> > 
> > 
> > edit this cookie很简单好用的插件，任何人不用教程就会用。这个实际上原来是用来浏览器上跳过熊猫图在E站看本子用的插件。 登录biliplus后，点开插件直接就有一个项目叫做access_key，点开来里面就是一串key，直接复制就可以了。这个key应该是绑定账号不会变的，所以保存成文本文件在自己电脑里，以后就不用再重复所有这些操作了。
> 
> 大哥在biliplus复制后再返回番剧页面后再重复一遍操作把复制来的key替换吗😖

emmm确实复制操作要进行两次，一次复制代码，一次复制key，不过并没有重复操作，我猜你可能还是没完全搞对。
我来从头到尾缕一遍：
打开番剧页面（此时脚本已经失效），按F12，在console下面的空白输入栏里面粘贴下面这一行
localStorage.access_key = ""
然后放着这个页面暂时不管，打开另一个页面biliplus，登录你的b站账号，登录成功后用插件也好别的方法也好从cookies里找出你的access_key，是一串很长的数字和字母。然后复制key，回到刚才的番剧页面，把key粘贴到右边的双引号里面，按一下回车。然后刷新页面，脚本就重新生效了。

**Comment by jayphone17** [comment]
1.登录biliplus.com
2.登录你的b站账号
3.按f12
4.找到Application --> Cookies --> https://www.biliplus.com/ --> access_key
5.复制access_key 的 value（很长一串）
6.回到bilibili某个港澳台番剧页面
7.按f12，到console那一栏
8.输入localStorage.access_key = "access_key"，回车。（access_key是刚才 4. 复制的）
9.刷新

**Comment by Accelerator888** [comment]
> 1.登录biliplus.com 2.登录你的b站账号 3.按f12 4.找到Application --> Cookies --> https://www.biliplus.com/ --> access_key 5.复制access_key 的 value（很长一串） 6.回到bilibili某个港澳台番剧页面 7.按f12，到console那一栏 8.输入localStorage.access_key = "access_key"，回车。（access_key是刚才 4. 复制的） 9.刷新

太吊了大哥 实测能用

**Comment by Accelerator888** [comment]
> > > > > 解决了。楼主说的很简洁明白了。 只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。 番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。
> > > > 
> > > > 
> > > > 大佬你是用什麼插件把key扒出来來的?
> > > 
> > > 
> > > edit this cookie很简单好用的插件，任何人不用教程就会用。这个实际上原来是用来浏览器上跳过熊猫图在E站看本子用的插件。 登录biliplus后，点开插件直接就有一个项目叫做access_key，点开来里面就是一串key，直接复制就可以了。这个key应该是绑定账号不会变的，所以保存成文本文件在自己电脑里，以后就不用再重复所有这些操作了。
> > 
> > 
> > 大哥在biliplus复制后再返回番剧页面后再重复一遍操作把复制来的key替换吗😖
> 
> emmm确实复制操作要进行两次，一次复制代码，一次复制key，不过并没有重复操作，我猜你可能还是没完全搞对。 我来从头到尾缕一遍： 打开番剧页面（此时脚本已经失效），按F12，在console下面的空白输入栏里面粘贴下面这一行 localStorage.access_key = "" 然后放着这个页面暂时不管，打开另一个页面biliplus，登录你的b站账号，登录成功后用插件也好别的方法也好从cookies里找出你的access_key，是一串很长的数字和字母。然后复制key，回到刚才的番剧页面，把key粘贴到右边的双引号里面，按一下回车。然后刷新页面，脚本就重新生效了。

太吊了大哥 实测能用

**Comment by kledi26** [comment]
可以试试这个插件https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5
授权接口可以正常使用，能获得key，也有解除区域限制功能

**Comment by mengshanasi** [comment]
用这个方法成功了，但是变成国番看不了，不知道是我操作错了？还是咋样。有同样情况的吗？

**Comment by RYX-3212103383** [comment]
补充一下我个人遇到的问题及解决方法
仅供edge修改完
localStorage.access_key = "xxxx"
后仍然无效参考
在dege的快捷方式里暂时禁用web安全
--disable-web-security
重新打开打开港澳台后就解决

**Comment by Mishseven** [comment]
> > > > > 解决了。楼主说的很简洁明白了。 只是biliplus登录后的cookie我不知道去f12后的哪个tab里面找，用我另外安装的读取cookies插件把key给扒出来了。 番剧页面的操作倒是很简单，就是粘贴一行代码，替换一下key，敲一下回车再刷新就行了。
> > > > 
> > > > 
> > > > 大佬你是用什麼插件把key扒出来來的?
> > > 
> > > 
> > > edit this cookie很简单好用的插件，任何人不用教程就会用。这个实际上原来是用来浏览器上跳过熊猫图在E站看本子用的插件。 登录biliplus后，点开插件直接就有一个项目叫做access_key，点开来里面就是一串key，直接复制就可以了。这个key应该是绑定账号不会变的，所以保存成文本文件在自己电脑里，以后就不用再重复所有这些操作了。
> > 
> > 
> > 大哥在biliplus复制后再返回番剧页面后再重复一遍操作把复制来的key替换吗😖
> 
> emmm确实复制操作要进行两次，一次复制代码，一次复制key，不过并没有重复操作，我猜你可能还是没完全搞对。 我来从头到尾缕一遍： 打开番剧页面（此时脚本已经失效），按F12，在console下面的空白输入栏里面粘贴下面这一行 localStorage.access_key = "" 然后放着这个页面暂时不管，打开另一个页面biliplus，登录你的b站账号，登录成功后用插件也好别的方法也好从cookies里找出你的access_key，是一串很长的数字和字母。然后复制key，回到刚才的番剧页面，把key粘贴到右边的双引号里面，按一下回车。然后刷新页面，脚本就重新生效了。

大佬请问可以有偿请您远程一下嘛，我弄到key了，也替换了，还是不行，求拯救下

**Comment by Benjamin23333** [comment]
> localStorage.access_key = "access_key"

刚试了，成功了，感谢大佬，第六点里的这一步可以不用打开港澳台的番剧页面，打开大陆的番剧页面也可以用这个方法

**Comment by Benjamin23333** [comment]
> 1.登录biliplus.com 2.登录你的b站账号 3.按f12 4.找到Application --> Cookies --> https://www.biliplus.com/ --> access_key 5.复制access_key 的 value（很长一串） 6.回到bilibili某个港澳台番剧页面 7.按f12，到console那一栏 8.输入localStorage.access_key = "access_key"，回车。（access_key是刚才 4. 复制的） 9.刷新

刚试了下，成功了，感谢大佬，第六步打开大陆的番剧页面也可以，不一定要打开港澳台的番剧

**Comment by Hhhhhhhhhhi** [comment]
> 1.登录biliplus.com 2.登录你的b站账号 3.按f12 4.找到Application --> Cookies --> https://www.biliplus.com/ --> access_key 5.复制access_key 的 value（很长一串） 6.回到bilibili某个港澳台番剧页面 7.按f12，到console那一栏 8.输入localStorage.access_key = "access_key"，回车。（access_key是刚才 4. 复制的） 9.刷新

Biliplus授权登陆的链接显示“请在哔哩哔哩客户端内打开“，网页端不行的吗，而且打开了客户端后什么也没发生诶。没有access_key就算打开console也没用。求助

**Comment by SephyrZ** [comment]
解决了 谢谢喵

**Comment by Mishseven** [comment]
code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"
请问这个是哪一步出了问题嘛

**Comment by Benjamin23333** [comment]
> code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error" 请问这个是哪一步出了问题嘛

换一个解析服务器试试？

**Comment by Mishseven** [comment]
> > code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error" 请问这个是哪一步出了问题嘛
> 
> 换一个解析服务器试试？

行了行了，感谢

**Comment by KUMORIII** [comment]
> 1.登录biliplus.com 2.登录你的b站账号 3.按f12 4.找到Application --> Cookies --> https://www.biliplus.com/ --> access_key 5.复制access_key 的 value（很长一串） 6.回到bilibili某个港澳台番剧页面 7.按f12，到console那一栏 8.输入localStorage.access_key = "access_key"，回车。（access_key是刚才 4. 复制的） 9.刷新

成功了，感谢大佬

**Comment by ScheniCode** [comment]
感谢大佬  已解决

**Comment by GouSheng622** [comment]
> localStorage.access_key = "access_key"

成功了，感谢大佬

**Comment by mingkd** [comment]
成功了 NB  我用的是火狐 在存储那一栏找的Cookie

**Comment by Mishseven** [comment]
请问有大佬遇到这种情况嘛？
{"readyState":4,"responseText":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.17.5</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"statusText":"Internal Server Error"}

**Comment by BrikeX** [comment]
> r
AN ERROR REPORTED:
`{"readyState":4,"responseText":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.17.5</center>\r\n</body>\r\n</html>\r\n","status":500,"statusText":"Internal Server Error"}`

**Comment by ChiotOnAGE** [comment]
前一阵子这个方法可行，现在会遇到 `通过自定义代理服务器获取ep信息失败`, 还是无法播放。

**Comment by kielour** [comment]
试过了但还是不成功，有没有大佬指点一下
![Uploading [1703243214260.jpg…]()](url)

**Comment by landall** [comment]
其实Chrome开发者工具的LocalStore，是可以直接Edit Value的，把biliplus里获得的那个value填进去，就能正常访问大会员了。
