### ISSUE TITLE
解决3秒跳转首页

### ISSUE THREAD

**Issue by pujie1216** [ipcjs/bilibili-helper#1258]
现在新页面多了个3秒跳转首页,脚本一般在3秒内无法解析跳转到正确番页,这里给一行小代码,可以自动点击 **取消跳转**
首先油猴打开脚本编辑页面,查找 **获取番剧页Url中** 这几个字,在该行代码的上一行插入以下代码,保存即可
`document.querySelector('.big-btn.go-home.go-whatever').click();`

**Comment by ipcjs** [comment]
为啥不提个PR？🤔️

**Comment by pujie1216** [comment]
想着或许你还有更好的方法，我只是笨人操作😏
