### ISSUE TITLE
哔哩哔哩番剧出差打开不了

### ISSUE THREAD

**Issue by Rxstar-sq** [ipcjs/bilibili-helper#1261]
脚本问题：@ipcjs 哔哩哔哩番剧出差打开不了

## 描述
如题，可以观看番剧出差的番，但是无法打开哔哩哔哩番剧出差的主页，
- 问题网址：https://space.bilibili.com/11783021/dynamic

</details>
![image](https://github.com/ipcjs/bilibili-helper/assets/87178985/91331755-b257-4dff-9c83-7d7efdf4a367)

## 其他

1. 浏览器版本：Chrome 119.0.6045.160
2. 国家/地区：美国

**Comment by chengqiqqyy** [comment]
一样无法打开哔哩哔哩番剧出差的主页 
国家/地区：日本

**Comment by landall** [comment]
这个页面是B站自己关闭的吧，我用wget好像也获得不了了。
