### ISSUE TITLE
无法获取到视频地址

### ISSUE THREAD

**Issue by GitHubandChina** [ipcjs/bilibili-helper#127]
## 描述

无法获取到视频地址
## 日志

log: [解除B站区域限制 v6.7.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183803
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"我的世界专业搞笑","isLogin":true,"level":3,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183803,"last_ep_index":"5","last_time":6}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=31692630|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=941b80840ac7b4af52d84f6d43ef6e8a
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=31692630&player=1&qn=80&quality=80&ts=1518311046&sign=a5ea37224a092a914a04e9bdeb09cf4d
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

## 其他
1. 浏览器版本：火狐58.0.2（64位）
2. 国家/地区：China

**Comment by toNyLInL** [comment]
都是这个问题，b站是按上面的要求做了反制措施么？
今天的这集上的偏迟啊

**Comment by ZeroKingHao** [comment]
应该是biliplus挂了

**Comment by GitHubandChina** [comment]
没办法，上头管的太严，我还是老老实实的科学上网了

**Comment by toNyLInL** [comment]
有大佬试过挂个港澳台的VPN么？

**Comment by GitHubandChina** [comment]
我试过

**Comment by GitHubandChina** [comment]
不只是港澳台

**Comment by GitHubandChina** [comment]
还有一些奇奇怪怪的国家

**Comment by toNyLInL** [comment]
哎，这就很僵了啊

**Comment by ZeroKingHao** [comment]
我自己搭的ss是上不去，难受的一匹

**Comment by GitHubandChina** [comment]
是不是你配置ss的时候配置错误

**Comment by ZeroKingHao** [comment]
不应该啊，google 油管什么的都能上去啊

**Comment by toNyLInL** [comment]
你的服务器物理地址是哪里的？@zeroKingHao

**Comment by GitHubandChina** [comment]
可能ss所处的国家B站禁止访问

**Comment by ZeroKingHao** [comment]
45.63.51.86

**Comment by ZeroKingHao** [comment]
美国的服务器

**Comment by GitHubandChina** [comment]
美国连没有限制的都访问不了

**Comment by ZeroKingHao** [comment]
本来想弄个日本的，后来懒得折腾了

**Comment by GitHubandChina** [comment]
日本有些地方也不行

**Comment by toNyLInL** [comment]
还这么刁难人的么？

**Comment by ZeroKingHao** [comment]
安安心心用这个吧，搭ss也不是纯粹为了看番的

**Comment by GitHubandChina** [comment]
是

**Comment by toNyLInL** [comment]
恩

**Comment by marswow** [comment]
你自己搭建的SS如果服务器不是台湾就肯定无法正常看片。

**Comment by ZeroKingHao** [comment]
香港服务器贵啊
