### ISSUE TITLE
无法打开设置页面了

### ISSUE THREAD

**Issue by yogurt7771** [ipcjs/bilibili-helper#1271]
脚本问题：@ipcjs

## 描述

无法打开设置页面
 
![image](https://github.com/ipcjs/bilibili-helper/assets/22412010/2dc6dbb0-6bc2-4165-af2a-d4984eb88919)

- 问题网址：
https://bangumi.bilibili.com/anime/5551

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Edge Version 119.0.2151.97 (Official build) (64-bit)
2. 国家/地区：

**Comment by thomaswqin** [comment]
在.../anime/... 网址下打不开设置界面,
但在.../bangumi/media/... 网址下打开番剧界面还是可以看见设置按钮的.
比如 https://www.bilibili.com/bangumi/media/md20140807


<img width="562" alt="image" src="https://github.com/ipcjs/bilibili-helper/assets/14259771/4a222700-06a8-450f-a065-3f3dccc74d26">
