### ISSUE TITLE
设置页面打不开了

### ISSUE THREAD

**Issue by GouSheng622** [ipcjs/bilibili-helper#1273]
脚本问题：@ipcjs

## 描述
设置页面打不开了

刚才还能打开的，但是遇到了授权页面无法正常打开的问题，于是想各种办法试试，然后手欠在设置页面里把关闭脚本选项打了勾，然后就再也进不去设置页面了，重装脚本无用，清空cookies也无用，打开港澳台番剧BV页面能看到跳转提示，但是到https://www.bilibili.com/bangumi/play/ep****** 就显示找不到页面，低音号的那个页面也看不到设置图标了。

浏览器版本是chrome最新版，求大大救救

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by yogurt7771** [comment]
前两天我刚问过，看这个里面有答案
https://github.com/ipcjs/bilibili-helper/issues/1271

**Comment by GouSheng622** [comment]
真的可以，谢谢大佬！
