### ISSUE TITLE
服务器是崩了么

### ISSUE THREAD

**Issue by fennuxiaomeng** [ipcjs/bilibili-helper#1277]
## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":4,"responseText":"{{\"code\":61000,\"message\":\"无效的用户态, 请尝试重新登陆Bilibili\"}}","status":200,"statusText":"parsererror"}}

点击账号授权弹出的页面没有任何反应。
测试页面：https://biliplus.ipcjs.top/api/bangumi?season=5551
打开也是500 手动挂港澳台代理也打不开这页面。。

是我自己这边的问题吗？

**Comment by mingkd** [comment]
我今天也用不了了

**Comment by xrz-cloud** [comment]
旧access_key获取API失效导致无法刷新，是该脚本的问题。  
解决方法已经有人发过了：https://github.com/ipcjs/bilibili-helper/issues/1249#issuecomment-1805222328
