### ISSUE TITLE
修复无法授权的问题的方法(B站更新了相关API)

### ISSUE THREAD

**Issue by xrz-cloud** [ipcjs/bilibili-helper#1278]
脚本问题：@ipcjs

## 描述

不会写油猴脚本，但下面是可用的方法(已测可行)  
该脚本[此处](https://github.com/ipcjs/bilibili-helper/blob/f3997dda10470c3ec61c2be707828730f5f0ad17/packages/unblock-area-limit/src/feature/bili/biliplus_login.ts#L43)用Cookies获取access_key的API已失效，可用[这个新的API(来自SocialSisterYi/bilibili-API-collect)](https://github.com/SocialSisterYi/bilibili-API-collect/issues/861)代替。  
请求逻辑可以参考[这里(biliroaming-ts-server-vercel)](https://github.com/bili-vd-bak/biliroaming-ts-server-vercel/blob/daaf1fcb4fce9dda983a9063a10bb57bb606c4e5/src/utils/_bili.ts#L109)

用户的临时解决方法已经有人发过了 [链接](https://github.com/ipcjs/bilibili-helper/issues/1249#issuecomment-1805222328)  

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by 0JsJ0** [comment]
怎么通过新API获取ccess_key啊？ 看不明白，能否解释一下。谢谢
