### ISSUE TITLE
脚本无法运行，是和b站新版页面有关吗

### ISSUE THREAD

**Issue by syr-123** [ipcjs/bilibili-helper#1279]
## 描述
现在b站是不是默认都是新版页面了。昨天以前，虽然是新版播放页面但是脚本会自己跳转到成旧版（？）然后正常播放。
但是今天刚刚打开的时候完全不反应了，然后显示“您所在的地区无法观看本片”。
并且在播放页面没有设置的小地球标志。

![脚本无法运行截图](https://github.com/ipcjs/bilibili-helper/assets/58761458/88ffd0ec-63a2-4197-9fa3-c5c5e432af2a)

- 问题网址：https://www.bilibili.com/bangumi/play/ss46356?spm_id_from=333.999.0.0

## 日志
播放页面没有设置的小地球按钮，但是作品介绍页面有。

## 其他

1. 浏览器版本：Google Chrome 120.0.6099.110（正式版本） （64 位）
2. 国家/地区：日本

**Comment by Baninn** [comment]
相同问题，港澳台也强制新版了
![QQ截图20231219222807](https://github.com/ipcjs/bilibili-helper/assets/20103484/477e9d0c-8077-4219-83fc-7bb8cba8cb0e)
