### ISSUE TITLE
不支持新版播放页面的临时解决方法

### ISSUE THREAD

**Issue by paigupai** [ipcjs/bilibili-helper#1283]
脚本问题：@ipcjs

## 描述
使用网页端的新版页面会导致无法正常播放

## 临时解决方法

安装[Bilibili 旧播放页](https://greasyfork.org/ja/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5)，关闭解除B站区域限制脚本，随便打开一个非版权视频确认成功显示Bilibili 旧播放页，然后重新打开B站区域限制脚本，就可以正常观看港澳台动画片

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by qiuyuyang910** [comment]
![image](https://github.com/ipcjs/bilibili-helper/assets/60593418/cad319f6-54f2-437c-be89-cafa79648224)
并不行

**Comment by qingqingyingying** [comment]
不好用，同上一层的界面

**Comment by tyq0330** [comment]
可以用，要先打开一个非番剧的视频， 再回来看番剧
![番剧](https://github.com/ipcjs/bilibili-helper/assets/61796387/23d90fd3-9e4e-4cd2-bb43-799992ef2648)

**Comment by Wenbobobo** [comment]
> 可以用，要先打开一个非番剧的视频， 再回来看番剧 ![番剧](https://private-user-images.githubusercontent.com/61796387/291979075-23d90fd3-9e4e-4cd2-bb43-799992ef2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMzMDksIm5iZiI6MTcwMzE3MzAwOSwicGF0aCI6Ii82MTc5NjM4Ny8yOTE5NzkwNzUtMjNkOTBmZDMtOWU0ZS00Y2QyLWJiNDMtNzk5OTkyZWYyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjZhY2VhMDc0MTBjNDkyOGE2NjJmZjJhZGFjNTgyYTQzNjJmZTkwMDJmOWMzNzE2OGQ1NmUwZDA5MGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU4wP2z_wjlCJSIVHLEYlHMsqCJkIUkW3E5TUyv5A5g)

麻烦可以再详细说下步骤嘛，谢谢！

**Comment by tyq0330** [comment]
> > 可以用，要先打开一个非番剧的视频， 再回来看番剧 ![番剧](https://private-user-images.githubusercontent.com/61796387/291979075-23d90fd3-9e4e-4cd2-bb43-799992ef2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMzMDksIm5iZiI6MTcwMzE3MzAwOSwicGF0aCI6Ii82MTc5NjM4Ny8yOTE5NzkwNzUtMjNkOTBmZDMtOWU0ZS00Y2QyLWJiNDMtNzk5OTkyZWYyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjZhY2VhMDc0MTBjNDkyOGE2NjJmZjJhZGFjNTgyYTQzNjJmZTkwMDJmOWMzNzE2OGQ1NmUwZDA5MGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU4wP2z_wjlCJSIVHLEYlHMsqCJkIUkW3E5TUyv5A5g)
> 
> 麻烦可以再详细说下步骤嘛，谢谢！

就是按照临时解决办法说的 安装bilibili 旧播放页， 然后再油猴里关闭解除B站区域限制脚本。刷新B站主页，随便点一个推荐视频，就会发现页面是旧版的B站。然后再打开解除B站区域限制脚本，就可以看番剧了。

**Comment by Wenbobobo** [comment]
> > > 可以用，要先打开一个非番剧的视频， 再回来看番剧 <img alt="番剧" width="44" height="21" src="https://private-user-images.githubusercontent.com/61796387/291979075-23d90fd3-9e4e-4cd2-bb43-799992ef2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMzMDksIm5iZiI6MTcwMzE3MzAwOSwicGF0aCI6Ii82MTc5NjM4Ny8yOTE5NzkwNzUtMjNkOTBmZDMtOWU0ZS00Y2QyLWJiNDMtNzk5OTkyZWYyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjZhY2VhMDc0MTBjNDkyOGE2NjJmZjJhZGFjNTgyYTQzNjJmZTkwMDJmOWMzNzE2OGQ1NmUwZDA5MGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU4wP2z_wjlCJSIVHLEYlHMsqCJkIUkW3E5TUyv5A5g">
> > 
> > 
> > 麻烦可以再详细说下步骤嘛，谢谢！
> 
> 就是按照临时解决办法说的 安装bilibili 旧播放页， 然后再油猴里关闭解除B站区域限制脚本。刷新B站主页，随便点一个推荐视频，就会发现页面是旧版的B站。然后再打开解除B站区域限制脚本，就可以看番剧了。

![image](https://github.com/ipcjs/bilibili-helper/assets/78262508/f5ef9419-6d35-42ec-82f3-2c1fa0005638)
我这里一直是这个样子

**Comment by tyq0330** [comment]
> > > > 可以用，要先打开一个非番剧的视频， 再回来看番剧 <img alt="番剧" width="44" height="21" src="https://private-user-images.githubusercontent.com/61796387/291979075-23d90fd3-9e4e-4cd2-bb43-799992ef2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMzMDksIm5iZiI6MTcwMzE3MzAwOSwicGF0aCI6Ii82MTc5NjM4Ny8yOTE5NzkwNzUtMjNkOTBmZDMtOWU0ZS00Y2QyLWJiNDMtNzk5OTkyZWYyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjZhY2VhMDc0MTBjNDkyOGE2NjJmZjJhZGFjNTgyYTQzNjJmZTkwMDJmOWMzNzE2OGQ1NmUwZDA5MGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU4wP2z_wjlCJSIVHLEYlHMsqCJkIUkW3E5TUyv5A5g">
> > > 
> > > 
> > > 麻烦可以再详细说下步骤嘛，谢谢！
> > 
> > 
> > 就是按照临时解决办法说的 安装bilibili 旧播放页， 然后再油猴里关闭解除B站区域限制脚本。刷新B站主页，随便点一个推荐视频，就会发现页面是旧版的B站。然后再打开解除B站区域限制脚本，就可以看番剧了。
> 
> ![image](https://private-user-images.githubusercontent.com/78262508/292368988-f5ef9419-6d35-42ec-82f3-2c1fa0005638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMTc3NDUsIm5iZiI6MTcwMzIxNzQ0NSwicGF0aCI6Ii83ODI2MjUwOC8yOTIzNjg5ODgtZjVlZjk0MTktNmQzNS00MmVjLTgyZjMtMmMxZmEwMDA1NjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAzNTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzY3NTZlMDYyYWZlMTY5Y2RkZTRmNWVhNDRlYmI0MjAzY2M4NWQ1OWM5M2QzMjIxMjlmMzFmNzA5MTgyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9n4q9OZTsZInhV46QureQ-AU8bfYaP6VtUr37Ay2n8) 我这里一直是这个样子

换一个番剧也是吗？那我就不清楚了。 感觉不像是插件的问题

**Comment by yzholic** [comment]
> > > > 可以用，要先打开一个非番剧的视频， 再回来看番剧 <img alt="番剧" width="44" height="21" src="https://private-user-images.githubusercontent.com/61796387/291979075-23d90fd3-9e4e-4cd2-bb43-799992ef2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMzMDksIm5iZiI6MTcwMzE3MzAwOSwicGF0aCI6Ii82MTc5NjM4Ny8yOTE5NzkwNzUtMjNkOTBmZDMtOWU0ZS00Y2QyLWJiNDMtNzk5OTkyZWYyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjZhY2VhMDc0MTBjNDkyOGE2NjJmZjJhZGFjNTgyYTQzNjJmZTkwMDJmOWMzNzE2OGQ1NmUwZDA5MGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU4wP2z_wjlCJSIVHLEYlHMsqCJkIUkW3E5TUyv5A5g">
> > > 
> > > 
> > > 麻烦可以再详细说下步骤嘛，谢谢！
> > 
> > 
> > 就是按照临时解决办法说的 安装bilibili 旧播放页， 然后再油猴里关闭解除B站区域限制脚本。刷新B站主页，随便点一个推荐视频，就会发现页面是旧版的B站。然后再打开解除B站区域限制脚本，就可以看番剧了。
> 
> ![image](https://private-user-images.githubusercontent.com/78262508/292368988-f5ef9419-6d35-42ec-82f3-2c1fa0005638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjQyNzMsIm5iZiI6MTcwMzIyMzk3MywicGF0aCI6Ii83ODI2MjUwOC8yOTIzNjg5ODgtZjVlZjk0MTktNmQzNS00MmVjLTgyZjMtMmMxZmEwMDA1NjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA1NDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNzIzMDE3YjQxNjg0ZjYzMmQyYzkxOWY3MDEyYzMyNDQwZjM2ZWViMGFjZDU5YjRjZjU1ZTczNWU1NmJkYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mMCpNHHkh-t6yNwCZwRogpxFepZp7U75tXPeibRnW4A) 我这里一直是这个样子

我的也是这样子，试了好多个番都这样

**Comment by Yui-QAQ** [comment]
> > > 可以用，要先打开一个非番剧的视频， 再回来看番剧 ![番剧](https://private-user-images.githubusercontent.com/61796387/291979075-23d90fd3-9e4e-4cd2-bb43-799992ef2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMzMDksIm5iZiI6MTcwMzE3MzAwOSwicGF0aCI6Ii82MTc5NjM4Ny8yOTE5NzkwNzUtMjNkOTBmZDMtOWU0ZS00Y2QyLWJiNDMtNzk5OTkyZWYyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjZhY2VhMDc0MTBjNDkyOGE2NjJmZjJhZGFjNTgyYTQzNjJmZTkwMDJmOWMzNzE2OGQ1NmUwZDA5MGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU4wP2z_wjlCJSIVHLEYlHMsqCJkIUkW3E5TUyv5A5g)
> > 
> > 
> > 麻烦可以再详细说下步骤嘛，谢谢！
> 
> 就是按照临时解决办法说的 安装bilibili 旧播放页， 然后再油猴里关闭解除B站区域限制脚本。刷新B站主页，随便点一个推荐视频，就会发现页面是旧版的B站。然后再打开解除B站区域限制脚本，就可以看番剧了。

我是把这些步骤都弄完后也是卡在即将开播页面，然后挂了个梯子又能进去页面了，大多数人应该情况和我一样，做完这几个步骤后建议再挂个梯子的

**Comment by Yui-QAQ** [comment]
> > > > 可以用，要先打开一个非番剧的视频， 再回来看番剧 ![番剧](https://private-user-images.githubusercontent.com/61796387/291979075-23d90fd3-9e4e-4cd2-bb43-799992ef2648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzMzMDksIm5iZiI6MTcwMzE3MzAwOSwicGF0aCI6Ii82MTc5NjM4Ny8yOTE5NzkwNzUtMjNkOTBmZDMtOWU0ZS00Y2QyLWJiNDMtNzk5OTkyZWYyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE1MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjZhY2VhMDc0MTBjNDkyOGE2NjJmZjJhZGFjNTgyYTQzNjJmZTkwMDJmOWMzNzE2OGQ1NmUwZDA5MGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QU4wP2z_wjlCJSIVHLEYlHMsqCJkIUkW3E5TUyv5A5g)
> > > 
> > > 
> > > 麻烦可以再详细说下步骤嘛，谢谢！
> > 
> > 
> > 就是按照临时解决办法说的 安装bilibili 旧播放页， 然后再油猴里关闭解除B站区域限制脚本。刷新B站主页，随便点一个推荐视频，就会发现页面是旧版的B站。然后再打开解除B站区域限制脚本，就可以看番剧了。
> 
> 我是把这些步骤都弄完后也是卡在即将开播页面，然后挂了个梯子又能进去页面了，大多数人应该情况和我一样，做完这几个步骤后建议再挂个梯子的

好吧又实验了几次，直接挂梯子就能进去，和前面步骤无关，看的时候把区域限制脚本打开就行

**Comment by Wenbobobo** [comment]
emmmm如果挂的是港澳台那不用脚本也可以（（

Yui-QAQ ***@***.***> 于 2023年12月22日周五 15:56写道：

**Comment by Seukieee** [comment]
我这边梯子（非港澳台）+旧版页面+接触区域限制三者同时打开才能看，且大会员内容好像看不了。咒术回战第二季仅第一集免费的可以后面的都不行，提示——原因: {"code":6002105,"message":"开通大会员观看"}。
![image](https://github.com/ipcjs/bilibili-helper/assets/76165686/f77563b7-3e49-48b3-a6b7-1fc1a934597c)
![image](https://github.com/ipcjs/bilibili-helper/assets/76165686/9319a459-cae9-4739-bf81-97f69dbed7f3)

**Comment by Hanserping** [comment]
我也不行

**Comment by landall** [comment]
我这里搞不定，那个脚本自己都不一定能正常工作。有的时候成，有的时候界面完全构建失败。
