### ISSUE TITLE
无法进入播放页面并弹窗

### ISSUE THREAD

**Issue by yezhe11** [ipcjs/bilibili-helper#1285]
![截图20231221022815](https://github.com/ipcjs/bilibili-helper/assets/154462185/658f26c1-6d56-4173-b57e-34874f4d7a67)
[弹窗的内容.txt](https://github.com/ipcjs/bilibili-helper/files/13730972/default.txt)
![截图20231221023328](https://github.com/ipcjs/bilibili-helper/assets/154462185/52b3c27a-2647-4bb7-8d78-d7fa8906cbe7)

**Comment by yezhe11** [comment]
{"readyState":4,"responseText":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.17.5</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"statusText":"Internal Server Error"}

**Comment by yezhe11** [comment]
[弹窗的内容.txt](https://github.com/ipcjs/bilibili-helper/files/13730986/default.txt)

**Comment by yezhe11** [comment]
[日志.txt](https://github.com/ipcjs/bilibili-helper/files/13731046/default.txt)

**Comment by 117649** [comment]
biliplus炸了和脚本没关系

你们得敲这里：
https://weibo.com/lcz970
https://twitter.com/esterTion
https://space.bilibili.com/5282663

**Comment by syr-123** [comment]
> biliplus炸了和脚本没关系
> 
> 你们得敲这里： https://weibo.com/lcz970 https://twitter.com/esterTion https://space.bilibili.com/5282663
![QQ图片20231222005707](https://github.com/ipcjs/bilibili-helper/assets/58761458/af4b9f0d-a1c2-41b2-af77-27b09eeaadf0)
ran'h
然后那边说和biliplus没关系......

**Comment by 117649** [comment]
> > biliplus炸了和脚本没关系
> > 你们得敲这里： https://weibo.com/lcz970 https://twitter.com/esterTion https://space.bilibili.com/5282663
> > ![QQ图片20231222005707](https://private-user-images.githubusercontent.com/58761458/292254421-af4b9f0d-a1c2-41b2-af77-27b09eeaadf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxOTI5OTQsIm5iZiI6MTcwMzE5MjY5NCwicGF0aCI6Ii81ODc2MTQ1OC8yOTIyNTQ0MjEtYWY0YjlmMGQtYTFjMi00MWIyLWFmNzctMjdiMDllZWFhZGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDIxMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ODc1NDc5OTc3NzI5Mzc2ZTU2ODdhZjNjZjhhZTUyOGFlZjA5NjE0MmIyODhhZDQ3NGZkZGZmZjNhMTg1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ce_y46zVOdABtnBEPnzNSUedRhdu3qQrW7tKyjW1exQ)
> > ran'h
> > 然后那边说和biliplus没关系......

自己按f12看看报500的那个链接是哪里的呗
