### ISSUE TITLE
脚本无法使用

### ISSUE THREAD

**Issue by starfish122** [ipcjs/bilibili-helper#1287]
脚本问题：@ipcjs

## 描述
脚本无法使用，bilibili显示：{"readyState":4,"responseText":"<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body>\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.17.5</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","status":500,"statusText":"Internal Server Error"}

- 问题网址：
https://www.bilibili.com/bangumi/play/ss46161?from_spmid=666.4.mylist.7

## 日志

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by hangtian15** [comment]
我的是显示 “无法查询到ep信息, 请先刷新动画对应的www.bilibili.com/bangumi/media/md页面”，所有外面的番剧都这样

**Comment by landall** [comment]
我遇到了一样的问题，去刷新md页面也没用。
