### ISSUE TITLE
 [已恢复] 2018.2.11 服务器遭受物理攻击 （集中讨论）

### ISSUE THREAD

**Issue by PROUDsuse** [ipcjs/bilibili-helper#129]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```
log: [解除B站区域限制 v6.7.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss21680#183803
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"素色苍穹","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":1422}}}
log: setAreaLimitSeason ss21680 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=31692630|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=881f98189ed9c2a8b5f72ce1d2e5044d
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=31692630&player=1&qn=112&quality=112&ts=1518312526&sign=4be9d2f60d3ec929ecce65c290f7e227
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by PROUDsuse** [comment]
浏览器版本：360安全浏览
国家/地区：中国

**Comment by ipcjs** [comment]
破案了：
![screenclip 2](https://user-images.githubusercontent.com/4396864/36070336-4b6990f2-0f33-11e8-860e-2ffaf302e3c0.png)

**Comment by bili-guigui** [comment]
我好奇问一下 物理攻击的来源出于哪？

**Comment by ipcjs** [comment]
@Chinaguigui 你上面那条呀，被显示器砸了

**Comment by CNife** [comment]
这个 BUG 意想不到

**Comment by jdxccz** [comment]
您好，我想请问一下，视频加载出错，code31X，是什么情况？是Microsoft edge浏览器

**Comment by ipcjs** [comment]
@jdxccz 不知道，试下账号授权？

**Comment by jdxccz** [comment]
我应该是已经默认授权过的，没有跳出授权页面@ipcjs

**Comment by ipcjs** [comment]
@jdxccz 那就不知道了，把完整log，贴上来看下？

**Comment by jdxccz** [comment]
不好意思大佬，我不是计算机相关专业的，不太知道怎么找到log日志@ipcjs

**Comment by jdxccz** [comment]
![image](https://user-images.githubusercontent.com/36372058/36075169-c071f8f6-0f85-11e8-83f4-da8fec4d509f.png)
请问是这个吗

**Comment by jdxccz** [comment]
大佬，我换了个浏览器就好了
![image](https://user-images.githubusercontent.com/36372058/36075280-a10f9908-0f87-11e8-9066-c11ccd5b30d1.png)
是不是这个的原因

**Comment by ipcjs** [comment]
@jdxccz 不是。
换浏览器能行，那就换个浏览器呗。Edge连微软自己人都不用😅

**Comment by YixuanJing** [comment]
又这样了：
拉取视频地址失败
{"readyState":0,"responseText":"","status":0,"statusText":"error"}
浏览器为最新Chrome ，macOS

**Comment by ZizhuangZhou** [comment]
还是用不了，
拉取视频地址失败
{"readyState":0,"responseText":"","status":0,"statusText":"error"}
浏览器为最新Chrome，Windows10
比较奇怪的是国家队第四集可以看，其他集都看不了，还有这种操作的吗

**Comment by irokun** [comment]
番剧依然打不开orz，遇到如下问题，浏览器为chrome：
log: [解除B站区域限制 v6.7.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep172124
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"SeiIrokun","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":172123,"last_ep_index":"5","last_time":-1}}}
log: setAreaLimitSeason ep172124 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=31694559|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=64&module=bangumi&season_type=1&qn=64&sign=f859507245de029256b664509755a2df
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=31694559&player=1&qn=64&quality=64&ts=1518395588&sign=a1899007345a72f660cd3304986cecc5
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=31694559|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=64&module=bangumi&season_type=1&qn=64&sign=f859507245de029256b664509755a2df
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=31694559&player=1&qn=64&quality=64&ts=1518395614&sign=4968b316b8a12278f2c66ce09f08c582
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
log: balh_server  =>  https://www.biliplus.com

**Comment by ipcjs** [comment]
@ZizhuangZhou 第四集能播大概是因为脚本的回退机制：当代理服务器不可用时换用B站接口请求数据
这个B站接口只对部分视频有效。

**Comment by jaegeryan** [comment]
我现在只能不断刷新
![image](https://user-images.githubusercontent.com/33188918/36086303-584a5980-0f80-11e8-94d1-f5f7631822d4.png)

**Comment by ipcjs** [comment]
@jaegeryan 日志呢？一个截图啥也看不出来
