### ISSUE TITLE
[Feature Request]增加一个验证大会员有效性和转发服务器有效性的按钮

### ISSUE THREAD

**Issue by landall** [ipcjs/bilibili-helper#1292]
我发现很多次脚本失效，都是因为大会员的cookie过期。
还有一次遇到的问题是台湾的转发服务器没有续费。

这两个问题在目前的脚本界面上都缺乏有效的展示手段。对于不太熟悉网络原理的人而言，会一头雾水不知道哪里不对劲了。

不如把当前那个测速按钮，直接升级成全面检测按钮，把各种可能的要素都查一遍。这样不用大改界面的情况下，基本能把问题定位清楚。

**Comment by zangliu2077** [comment]
没必要吧，毕竟服务器也是网友用爱发电分享出来的，时而抽风很正常，有问题临时复制粘贴别的服务器去用就行了，作者本身不提供服务器，不支持这种切换也很正常

**Comment by zangliu2077** [comment]
没必要吧，毕竟服务器也是网友用爱发电分享出来的，时而抽风很正常，有问题临时复制粘贴别的服务器去用就行了，作者本身不提供服务器，不支持这种切换也很正常
