### ISSUE TITLE
2018.2.11 DARLING in the FRANXX（僅限港澳台地區）

### ISSUE THREAD

**Issue by wwwzzzcom1** [ipcjs/bilibili-helper#130]
log: [解除B站区域限制 v6.7.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183803
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"挣扎着","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":4}}}
log: setAreaLimitSeason ep183803 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=31692630|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=881f98189ed9c2a8b5f72ce1d2e5044d
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=31692630&player=1&qn=112&quality=112&ts=1518314068&sign=3a82631d2090f3f6da55b6ac2035af8b
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by CNife** [comment]
同样的问题

**Comment by PhilCity** [comment]
+1
