### ISSUE TITLE
更新了8.5.1后看港澳台还是提示无法查询到ep信息

### ISSUE THREAD

**Issue by yxok200** [ipcjs/bilibili-helper#1301]
更新了8.5.1后看港澳台还是提示无法查询到ep信息

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.5.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md5551
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av: Y readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=5551&access_key={{access_key}}
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"欧尼酱是个吃货","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: setAreaLimitSeason 000 false
debug: /x/web-interface/nav {"uname":"欧尼酱是个吃货","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: season5551 {"code":0,"message":"success","result":{"activity":{"head_bg_url":"","id":0,"title":""},"actors":"加藤葉月：朝井彩加\n川島綠輝：豊田萌絵\n高坂麗奈：安済知佳\n黃前久美子：黒沢ともよ\n黃前麻美子：沼倉愛美\n松本美知恵：久川綾\n瀧升：櫻井孝宏\n長瀨梨子：小堀幸\n後藤卓也：津田健次郎","alias":"","areas":[{"id":2,"name":"日本"}],"bkg_cover":"","cover":"https://i0.hdslb.com/bfs/bangumi/18a9dc72417d9c25717f7bdc7e8f1577557f2b96.jpg","enable_vt":false,"episodes":[{"aid":6556317,"badge":"","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":""},"badge_type":0,"bvid":"BV1Ds411x7MC","cid":11234402,"cover":"https://i0.hdslb.com/bfs/archive/02aa588f9cd7cbaeff459064130440c4d53c3e2f.jpg","dimension":{"height":0,"rotate":0,"width":0},"duration":2861323,"enable_vt":false,"ep_id":96703,"from":"bangumi","id":96703,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96703","long_title":"盛夏的號角齊鳴","pub_time":1475683200,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第1话 盛夏的號角齊鳴","share_url":"https://www.bilibili.com/bangumi/play/ep96703","short_link":"https://b23.tv/ep96703","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":2,"subtitle":"已观看101.9万次","title":"1","vid":"vupload_11234402"},{"aid":6650172,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1us41147pW","cid":11234416,"cover":"https://i2.hdslb.com/bfs/archive/0ab64582a2541e3f682e1604b1ee286664c451d8.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96704,"from":"bangumi","id":96704,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96704","long_title":"困惑的長笛","pub_time":1476288010,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第2话 困惑的長笛","share_url":"https://www.bilibili.com/bangumi/play/ep96704","short_link":"https://b23.tv/ep96704","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"2","vid":"vupload_11234416"},{"aid":6743207,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1Bs41147vP","cid":10995505,"cover":"https://i2.hdslb.com/bfs/archive/628fbdc83a12d0e6a1a20f447df48953ae834f01.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96705,"from":"bangumi","id":96705,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96705","long_title":"煩惱的夜曲","pub_time":1476892810,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第3话 煩惱的夜曲","share_url":"https://www.bilibili.com/bangumi/play/ep96705","short_link":"https://b23.tv/ep96705","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"3","vid":"vupload_10995505"},{"aid":6838313,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1xs411s7tj","cid":11139687,"cover":"https://i2.hdslb.com/bfs/archive/c30ee4d9d6764e625b38fa76512eba744db437e6.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96706,"from":"bangumi","id":96706,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96706","long_title":"覺醒的雙簧管","pub_time":1477497610,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第4话 覺醒的雙簧管","share_url":"https://www.bilibili.com/bangumi/play/ep96706","short_link":"https://b23.tv/ep96706","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"4","vid":"vupload_11139687"},{"aid":6933063,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1Rs411s7v9","cid":11299462,"cover":"https://i2.hdslb.com/bfs/archive/bd64626c7b18d1166cbfe8aa2a5c218b85247917.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96707,"from":"bangumi","id":96707,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96707","long_title":"奇跡的和聲","pub_time":1478102410,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第5话 奇跡的和聲","share_url":"https://www.bilibili.com/bangumi/play/ep96707","short_link":"https://b23.tv/ep96707","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"5","vid":"vupload_11299462"},{"aid":7030092,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1xs411x7wo","cid":11571816,"cover":"https://i0.hdslb.com/bfs/archive/92e973ede5d124117ee1851e56c57ad005d7666b.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96708,"from":"bangumi","id":96708,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96708","long_title":"雨中的指揮家","pub_time":1478707210,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第6话 雨中的指揮家","share_url":"https://www.bilibili.com/bangumi/play/ep96708","short_link":"https://b23.tv/ep96708","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"6","vid":"vupload_11571816"},{"aid":7127268,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV15s411W7qT","cid":11624834,"cover":"https://i0.hdslb.com/bfs/archive/ff0e7b9ff1143454421412ecacd4eb204de38a57.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96709,"from":"bangumi","id":96709,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96709","long_title":"車站大廈演奏會","pub_time":1479312010,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第7话 車站大廈演奏會","share_url":"https://www.bilibili.com/bangumi/play/ep96709","short_link":"https://b23.tv/ep96709","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"7","vid":"vupload_11624834"},{"aid":7226337,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV11s411W7Pg","cid":11815072,"cover":"https://i2.hdslb.com/bfs/archive/428c436553a1e206c88a66d41aa6a51df95915bb.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96710,"from":"bangumi","id":96710,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96710","long_title":"感冒狂想曲","pub_time":1479916810,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第8话 感冒狂想曲","share_url":"https://www.bilibili.com/bangumi/play/ep96710","short_link":"https://b23.tv/ep96710","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"8","vid":"vupload_11815072"},{"aid":7326174,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV15s411s7hc","cid":11976131,"cover":"https://i0.hdslb.com/bfs/archive/2f488528c04960472c914d4a588909a3b055b2a0.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96711,"from":"bangumi","id":96711,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96711","long_title":"吹響吧！上低音號","pub_time":1480521610,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第9话 吹響吧！上低音號","share_url":"https://www.bilibili.com/bangumi/play/ep96711","short_link":"https://b23.tv/ep96711","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"9","vid":"vupload_11976131"},{"aid":7427576,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1Ss411Y7SA","cid":12145643,"cover":"https://i0.hdslb.com/bfs/archive/16d4c4c03db92cd6100221f35899bf1ad61f96be.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1420000,"enable_vt":false,"ep_id":96712,"from":"bangumi","id":96712,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96712","long_title":"放學後的伴奏","pub_time":1481126410,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第10话 放學後的伴奏","share_url":"https://www.bilibili.com/bangumi/play/ep96712","short_link":"https://b23.tv/ep96712","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"10","vid":"vupload_12145643"},{"aid":7529879,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1Hs411e7jj","cid":12320164,"cover":"https://i1.hdslb.com/bfs/archive/a5504f373789a208f26fb3e233179b930fb0aa2f.jpg","dimension":{"height":478,"rotate":0,"width":850},"duration":1420000,"enable_vt":false,"ep_id":96713,"from":"bangumi","id":96713,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96713","long_title":"初戀的小號","pub_time":1481731210,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第11话 初戀的小號","share_url":"https://www.bilibili.com/bangumi/play/ep96713","short_link":"https://b23.tv/ep96713","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"11","vid":"vupload_12320164"},{"aid":7634645,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV13s411a7Ep","cid":12506979,"cover":"https://i0.hdslb.com/bfs/archive/9707826da17883071fae71a8ec3732a3e5dfcc81.jpg","dimension":{"height":478,"rotate":0,"width":850},"duration":1420000,"enable_vt":false,"ep_id":96714,"from":"bangumi","id":96714,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep96714","long_title":"最後的競演會","pub_time":1482336010,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第12话 最後的競演會","share_url":"https://www.bilibili.com/bangumi/play/ep96714","short_link":"https://b23.tv/ep96714","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"12","vid":"vupload_12506979"},{"aid":7738842,"badge":"会员","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员"},"badge_type":0,"bvid":"BV1Rs411a75u","cid":12686262,"cover":"https://i0.hdslb.com/bfs/archive/3ee4a4eaf92d2adc8613a61deb30b8264121fc28.jpg","dimension":{"height":360,"rotate":0,"width":640},"duration":1419000,"enable_vt":false,"ep_id":98553,"from":"bangumi","id":98553,"is_view_hide":false,"link":"https://www.bilibili.com/bangumi/play/ep98553","long_title":"初春的終曲","pub_time":1482940810,"pv":0,"release_date":"","rights":{"allow_demand":0,"allow_dm":1,"allow_download":0,"area_limit":0},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》第13话 初春的終曲","share_url":"https://www.bilibili.com/bangumi/play/ep98553","short_link":"https://b23.tv/ep98553","showDrmLoginDialog":false,"skip":{"ed":{"end":0,"start":0},"op":{"end":0,"start":0}},"status":13,"subtitle":"已观看101.9万次","title":"13","vid":"vupload_12686262"}],"evaluate":"吹奏樂競賽京都府大賽。\n在那裡漂亮地取得金獎的北宇治高中吹奏樂部，\n向著下一個舞台·強豪雲集的關西大賽發起挑戰……！","freya":{"bubble_show_cnt":0,"icon_show":0},"hide_ep_vv_vt_dm":1,"icon_font":{"name":"playdata-square-line@500","text":"101.9万"},"jp_title":"","link":"http://www.bilibili.com/bangumi/media/md5551/","media_id":5551,"mode":2,"new_ep":{"desc":"已完结, 全13话","id":98553,"is_new":0,"title":"13"},"payment":{"discount":100,"pay_type":{"allow_discount":0,"allow_pack":0,"allow_ticket":0,"allow_time_limit":0,"allow_vip_discount":0,"forbid_bb":0},"price":"0.0","promotion":"","tip":"大会员专享观看特权哦~","view_start_time":0,"vip_discount":100,"vip_first_promotion":"","vip_price":"0","vip_promotion":"成為大會員搶先看"},"play_strategy":{"strategies":["common_section-formal_first_ep","common_section-common_section","common_section-next_season","formal-finish-next_season","formal-end-other_section","formal-end-next_season","ord"]},"positive":{"id":22587,"title":"正片"},"publish":{"is_finish":1,"is_started":1,"pub_time":"2016-10-06 00:00:00","pub_time_show":"2016年10月06日00:00","unknow_pub_date":0,"weekday":0},"rating":{"count":1342,"score":9.6},"record":"","rights":{"allow_bp":0,"allow_bp_rank":0,"allow_download":0,"allow_review":1,"area_limit":0,"ban_area_show":4,"can_watch":1,"copyright":"dujia","forbid_pre":0,"freya_white":0,"is_cover_show":0,"is_preview":1,"only_vip_download":0,"resource":"","watch_platform":0},"season_id":5551,"season_title":"吹響！上低音號 第二季（僅限台灣地區）","seasons":[{"badge":"会员抢先","badge_info":{"bg_color":"#FB7299","bg_color_night":"#BB5B76","text":"会员抢先"},"badge_type":0,"cover":"https://i0.hdslb.com/bfs/bangumi/8ae2dba7fdb53bcbeba2aada800160cff3215178.jpg","enable_vt":false,"horizontal_cover_1610":"","horizontal_cover_169":"","icon_font":{"name":"playdata-square-line@500","text":"5.4万"},"media_id":5930,"new_ep":{"cover":"https://i0.hdslb.com/bfs/archive/8e9764bd3ca9901d3c59b437ebf0f2ed8fa3e0f9.jpg","id":101791,"index_show":"全1话"},"season_id":5930,"season_title":"劇場版","season_type":1,"stat":{"favorites":25207,"series_follow":136464,"views":54008,"vt":0}},{"badge":"独家","badge_info":{"bg_color":"#00C0FF","bg_color_night":"#0B91BE","text":"独家"},"badge_type":1,"cover":"https://i0.hdslb.com/bfs/bangumi/18a9dc72417d9c25717f7bdc7e8f1577557f2b96.jpg","enable_vt":false,"horizontal_cover_1610":"","horizontal_cover_169":"","icon_font":{"name":"playdata-square-line@500","text":"101.9万"},"media_id":5551,"new_ep":{"cover":"https://i0.hdslb.com/bfs/archive/3ee4a4eaf92d2adc8613a61deb30b8264121fc28.jpg","id":98553,"index_show":"全13话"},"season_id":5551,"season_title":"第二季","season_type":1,"stat":{"favorites":129422,"series_follow":136464,"views":1018646,"vt":0}}],"series":{"display_type":0,"series_id":4544,"series_title":"吹響！上低音號（僅限港澳台等地區）"},"share_copy":"《吹響！上低音號 第二季（僅限台灣地區）》","share_sub_title":"","share_url":"https://www.bilibili.com/bangumi/play/ss5551","show":{"wide_screen":0},"show_season_type":1,"square_cover":"https://i0.hdslb.com/bfs/bangumi/9edbd9d3b1c073c1642e8cf9994e2c548e6836de.jpg","staff":"原作：武田綾乃「響け！ユーフォニアム 北宇治高校吹奏楽部へようこそ」(寶島社文庫)\n原作插畫：アサダニッキ\n監督：石原立也\n系列構成：花田十輝\n系列演出：山田尚子\n角色設計 / 總作畫監督：池田晶子\n美術監督：篠原睦雄\n3D美術：鵜ノ口穣二\n色彩設計：竹田明代\n樂器設定：髙橋博行\n攝影監督：髙尾一也\n編集：重村建吾\n音響監督：鶴岡陽太\n音響製作：楽音舎\n音樂：松田彬人\n音樂製作：ランティス\n動畫製作：京都アニメーション（京都動畫）\n製作協力：アニメーションDo（Animation Do）","stat":{"coins":5350,"danmakus":24535,"favorite":229,"favorites":129422,"follow_text":"13.6万系列追番","likes":1481,"reply":5054,"share":595,"views":1018646,"vt":0},"status":13,"styles":["音乐","校园","恋爱","社团"],"subtitle":"已观看101.9万次","title":"吹響！上低音號 第二季（僅限台灣地區）","total":13,"type":1,"user_status":{"area_limit":0,"ban_area_show":0,"follow":0,"follow_status":0,"login":0,"pay":0,"pay_pack_paid":0,"sponsor":0}}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.160 Safari/537.36

**Comment by yxok200** [comment]
![1](https://github.com/ipcjs/bilibili-helper/assets/23090472/908bf6e7-dab0-465d-9381-300c2291fac4)
![2](https://github.com/ipcjs/bilibili-helper/assets/23090472/3ea591fe-f0ec-4d2f-9663-444e60438ff7)

**Comment by Howard20181** [comment]
提供一下页面链接、地区和解析服务器地址

**Comment by yxok200** [comment]
> 提供一下页面链接、地区和解析服务器地址

https://www.bilibili.com/bangumi/media/md5551随便点一集
地区广东东莞
解析服务器地址：
自定义首选https://melusine.moe
台湾https://伊蕾娜.我爱你
香港https://api.mahiron.moe
大陆https://bili.rikko.moe
东南亚https://bili.rikko.moe

**Comment by Howard20181** [comment]
![image](https://github.com/ipcjs/bilibili-helper/assets/40033067/086a1ac2-4999-40cb-99ae-06a29bd12527)
无法复现，试试重新获取 access token?

**Comment by yxok200** [comment]
是取消账号授权，再重新授权吗？这个之前试过了还是不行

**Comment by Howard20181** [comment]
你看看番剧页 F12 那里，网络请求，过滤一下 `season`
看看内容
![image](https://github.com/ipcjs/bilibili-helper/assets/40033067/c5d1ff62-ead9-4d47-989a-c9918178ba70)
![image](https://github.com/ipcjs/bilibili-helper/assets/40033067/33e72363-522b-4dc5-bd8a-2d3f420cd0f8)

**Comment by Howard20181** [comment]
还有 `section`
这两个一起拼凑出来番剧信息的，有一个获取不到就不行
![image](https://github.com/ipcjs/bilibili-helper/assets/40033067/9840d005-c5df-4855-b2a3-56c84dcac135)

**Comment by yxok200** [comment]
啊，抱歉了大佬，问题已解决了，我的锅，我之前恢复旧版B站首页的时候，手动写入的key，导致现在key不会更新了，刚才手动删掉key也不更新，原因不明，最后清理浏览器，重登B站恢复了

**Comment by Howard20181** [comment]
好吧，你关掉这个 issue 吧
