### ISSUE TITLE
pc版访问

### ISSUE THREAD

**Issue by huxia86465** [ipcjs/bilibili-helper#1312]
脚本问题：@ipcjs

## 描述

pc上访问不了其他地区，试过**清理缓存和cookie**也是无法访问清除 试过“**重定向代理**”无法连接 在开启**upos**或者关闭了也是一样的
![屏幕截图 2024-01-26 100431](https://github.com/ipcjs/bilibili-helper/assets/70738910/b87e30d7-a4ab-40f9-ad31-131338d6f272)
![image](https://github.com/ipcjs/bilibili-helper/assets/70738910/d934e8f0-59db-4631-aa42-92d1ec1b7d4e)

- 问题网址：
- https://www.bilibili.com/bangumi/media/md5551

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：edge
2. 国家/地区：

**Comment by Howard20181** [comment]
未填写服务器地址

**Comment by huxia86465** [comment]
> 未填写服务器地址

谢谢，原来问题在这里
