### ISSUE TITLE
[Feature Request] B站最新限制，没有实名认证不能看直播

### ISSUE THREAD

**Issue by ShikyC** [ipcjs/bilibili-helper#1332]
## 描述

没有实名认证的用户大部分游戏区主播都不让看了（就很离谱，不是开播，连看都不让了），少部分主播（海外主播和少数国内主播）还能继续看，不确定筛选的条件是什么。

实际上所有直播间的视频流其实是可以正常接收的，但在加载直播间组件的时候如果发现用户没有实名认证就会掐掉视频流并弹出提示“请完善账号实名信息后再尝试观看”，不知道能不能绕过这层检测让视频流不被中断。

**Comment by LozyLL** [comment]
同问

**Comment by CornerStone7** [comment]
如果只是想看直播的话 可以用这个方法 https://github.com/LuckyPuppy514/Play-With-MPV

**Comment by ningsibuqu** [comment]
> 如果只是想看直播的话 可以用这个方法 https://github.com/LuckyPuppy514/Play-With-MPV

能在网页上看吗 因为有弹幕

**Comment by ningsibuqu** [comment]
https://greasyfork.org/zh-CN/scripts/486358

装这个脚本

**Comment by Mercymmm** [comment]
> https://greasyfork.org/zh-CN/scripts/486358
> 
> 装这个脚本

而你 我的朋友 你 才是真正的英雄

**Comment by yangmq123** [comment]
应该是防止机器人刷流量的
