### ISSUE TITLE
在Win版Chrome上使用遇到的一些问题及其解决

### ISSUE THREAD

**Issue by Shiming-Liang** [ipcjs/bilibili-helper#1336]
问题：播放窗口显示“非常抱歉，根据版权方要求 您所在的地区无法观看本片”，且没有报错弹窗
~~解决：原因是插件只在B站旧版界面运行。需要安装：User-Agent Switcher for Chrome插件，然后切换成很旧的浏览器，比如说IE6~~
08/26/2024更新：该方法已失效，目前bilibili旧播放页插件可用，详见 #1333 。

问题： {“code”:-1,”error”:{}}
解决：api.mahiron.moe用不了，要换服务器

问题：{“code”:403,”message”:”解析服务器: 地区限制！”}
解决：不能只填代理服务器，要把各个地区的都填上

希望有帮助。

**Comment by ironyx217** [comment]
请问怎么账号授权？每次一点就显示请用最新版扫码登录，而且账号自动退出登录

**Comment by ironyx217** [comment]
原因: {"code":401,"message":"解析服务器: 账号未登录！"}

**Comment by Shiming-Liang** [comment]
我貌似没碰到过这个问题。只能转发别人的反馈了。建议翻一下本仓库的issues（包括closed的）还有脚本主页的[反馈](https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6/feedback)。
![image](https://github.com/user-attachments/assets/20b47ba8-30e2-4020-8452-614a036bcad3)

**Comment by zhufyaxel** [comment]
这个方法已经失效了。具体可以看隔壁的#issue 1333的后续评论。

**Comment by Shiming-Liang** [comment]
确实。已修改issue。

**Comment by Kevin-Aznable-Deikun** [comment]
那么无法播放的问题究竟要怎么解决呢？
