### ISSUE TITLE
拉去视频地址失败，代理服务器无法访问

### ISSUE THREAD

**Issue by sixteenmetre** [ipcjs/bilibili-helper#155]
## 描述

无法观看番剧，包括大陆以及港澳台特供
弹窗提示拉取失败
![100](https://user-images.githubusercontent.com/18755613/36078033-aec454f8-0f82-11e8-9e0e-d156d00b3167.png)

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```
log: [解除B站区域限制 v6.7.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss21680#183803
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"16m","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":-1}}}
log: setAreaLimitSeason ss21680 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=31692630|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=64&module=bangumi&season_type=1&qn=64&sign=cad6a07d667aa5f7d0e937751ef852ef
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=31692630&player=1&qn=64&quality=64&ts=1518380271&sign=4c5fdcb121938d793c9bff0b735e3f59
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

## 其他

1. 浏览器版本：Google Chrome  64.0.3282.140（正式版本） （64 位）
2. 国家/地区：俄罗斯
![099](https://user-images.githubusercontent.com/18755613/36077986-3cc329ec-0f82-11e8-8202-51071ad90c2b.png)

**Comment by ipcjs** [comment]
弹窗的第三条。耐心等待。。。

**Comment by sixteenmetre** [comment]
唔，我以为是我这边出了什么问题……
那我……等待并心怀希望吧

**Comment by cyanlink** [comment]
服务器又又又又下线了，两个网址（biliplus和ipcjs）均无法访问（明显这个脚本的查询服务和博客服务运行在同一机器上），且脚本功能无法使用

**Comment by ipcjs** [comment]
@LinkEscapist 目前biliplus貌似是在局域网里的，公网ip地址经常变，所以才会经常连不上😫
@esterTion

**Comment by cyanlink** [comment]
凉凉。。。何不如开放一波捐赠（我paypal无法用银联支付给个人），把相应服务扔到vps上。。。

**Comment by esterTion** [comment]
我放在这个地方是为了速度，他这个稳定的时候速度很快，换ip是路由器爆炸才会换
上周炸得有点多，之前没这么炸

**Comment by INBreezefall** [comment]
崩溃！


log: [解除B站区域限制 v6.7.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183799
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"在微风中飘落","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183799,"last_ep_index":"1","last_time":628}}}
log: setAreaLimitSeason ep183799 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=29892777|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=0409ce62cbc48d3f3d317993cd6784ba
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=29892777&player=1&qn=112&quality=112&ts=1518607985&sign=10878c77467831c18f6fedd72917e61f
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}

**Comment by esterTion** [comment]
看了一眼群，刚刚的问题是路由器死机，目前已经恢复

**Comment by ipcjs** [comment]
@INBreezefall 我这边会有点延迟，你换第二个服务器（biliplus）

**Comment by ipcjs** [comment]
@esterTion 这路由器太不给力了😅

**Comment by esterTion** [comment]
5gb wan路由器，其实还行，死机也是推测而已
wan口灯不闪了，然后重启了一下好了，迷幻

**Comment by cyanlink** [comment]
等等，你说为了速度，难道视频流量全走的你那里？？按我理解不是这样啊

**Comment by esterTion** [comment]
之前vultr 1/4打不开1/4慢到死

**Comment by cyanlink** [comment]
vultr 延迟情况的确堪忧，但是日本机房速度还是可以啊

**Comment by esterTion** [comment]
日本机房我之前开了一个，1/3时间谁都连不上

**Comment by cyanlink** [comment]
这可就恐怖了，这锅vultr本身应该不背。。

**Comment by baekhosuga** [comment]
无法观看番剧

log: [解除B站区域限制 v6.7.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss23356/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip: Y server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"うえのじゅり","isLogin":true,"level":3,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":187713,"last_ep_index":"1","last_time":4}}}
log: setAreaLimitSeason ss23356 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=29990252&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=a7a72245ce06cd9012597a03ce3d2243
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=29990252&player=1&qn=80&quality=80&ts=1520853811&sign=19c361988dd127b18a047a69ac1253f4
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by ipcjs** [comment]
@baekhosuga 换主机的时候忘了改A记录。。。
等一下，DNS解析生效需要点时间

**Comment by Malpaca** [comment]
无法观看视频，放的是b站视频无法播放的那31秒视频
log: [解除B站区域限制 v6.7.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep80133
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Malpaca","isLogin":true,"level":2,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":80133,"last_ep_index":"1","last_time":0}}}
log: setAreaLimitSeason ep80133 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=4987089&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=bc6f60201db43dcdf1ad47966a396779
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=4987089&player=1&qn=16&quality=16&ts=1521321876&sign=3ee124e3b1053accc754ade14153c0a3
log: xml2obj {"location":null} => {"result":"suee","timelength":1440000,"format":"mp4","accept_format":"flv,flv720,mp4","accept_quality":[80,64,16],"quality":16,"from":"local","seek_param":"start","seek_type":"second","durl":[{"order":1,"length":1440000,"size":38308154,"url":"http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/89/70/4987089/4987089-1-16.mp4?um_deadline=1521329075&platform=pc&rate=1000&oi=3494992811&um_sign=b7f957f47f17c2acbd712fe8f21d3f9e&gen=playurl&os=cos","backup_url":"http://ws.acgvideo.com/0/82/4987089-1.mp4?wsTime=1521329075&platform=pc&wsSecret2=ade1487ddc38bdfed4e929aaf5a05e20&oi=3494992811&rate=1"}]}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

**Comment by mingl0280** [comment]
log: [解除B站区域限制 v6.7.10 (Greasemonkey.injector)] run on: https://www.bilibili.com/bangumi/play/ep183807
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"泡面蟹","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183808,"last_ep_index":"10","last_time":0}}}
log: setAreaLimitSeason ep183807 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=33712259|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=e3cf0cedd9b53522702166a2bbd3ba95
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=33712259&player=1&qn=112&quality=112&ts=1521333138&sign=288cbc3d82ada6a3c363403992895aa2
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

Console log:
指向“https://www.biliplus.com/login?act=expiretime”的 <script> 加载失败。
已拦截跨源请求：同源策略禁止读取位于 https://data.bilibili.com/v/flashplay/h5_player_op?pname=1&mid=372999&statue=3&playmethod=2&avid=20604893&eventparam=from%3A3%2Ccode%3A3001&progress=0&displayid=1521333128196&eventid=video_error&trackerid=&cid=33712259&fver=HTML5Player+6b8deee3&seasonid=21680&epid=183807&videotype=1&fid=web_player 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。
已拦截跨源请求：同源策略禁止读取位于 https://data.bilibili.com/v/flashplay/h5_player_op?pname=1&mid=372999&statue=3&playmethod=2&avid=20604893&eventparam=&progress=0&displayid=1521333128196&eventid=web_load_danmuku&trackerid=&cid=33712259&fver=HTML5Player+6b8deee3&seasonid=21680&epid=183807&videotype=1&fid=web_player 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。
是不是代理又炸了……

**Comment by StrikeArmor** [comment]
log: [解除B站区域限制 v6.7.13 (Violentmonkey)] run on: https://www.bilibili.com/bangumi/play/ss21680#183808
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"サフラン","isLogin":true,"level":2,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183807,"last_ep_index":"9","last_time":-1}}}
log: setAreaLimitSeason ss21680 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=34221660&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=a3858a6d763f5ed6d0e524ecb3e6cded
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=34221660&player=1&qn=112&quality=112&ts=1521365309&sign=d90791a43a503a12d5e9c5d584f46e08
log: player msg: 服务器错误: {"code":"-5009","message":"video is hidden"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

怎么都开不开了。

**Comment by ShemneGUI** [comment]
log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss21680/?from=search&seid=8499138648764474042
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"shenmengui","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183799,"last_ep_index":"1","last_time":4}}}
log: setAreaLimitSeason ss21680 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=29892777&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=0cc6b0e4d7378b45613e030f2fdab37e
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=29892777&player=1&qn=116&quality=116&ts=1523371911&sign=41af1697a07de17ad6f06985d101885f
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by 88UFO88** [comment]
debug: [解除B站区域限制 v7.8.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep284763
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function (a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: /x/web-interface/nav {"uname":"88UFO88","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1593964800000,"status":1,"type":2},"watch_progress":{"last_ep_id":284763,"last_ep_index":"1","last_time":11}}}
debug: setAreaLimitSeason ep284763 true
debug: /x/web-interface/nav {"uname":"88UFO88","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 4
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=68351435&cid=118466622&qn=64&type=&otype=json&ep_id=284763&fnver=0&fnval=16&session=30da7d89c0c56522082f8d6561bb748e&module=bangumi&balh_ajax=1
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"88UFO88","mid":18012433,"level":5,"vip_expire":1593964800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"88UFO88\",\"mid\":18012433,\"level\":5,\"vip_expire\":1593964800000}}","code":-404}
info: player msg: 尝试使用非番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=68351435&cid=118466622&qn=64&type=&otype=json&ep_id=284763&fnver=0&fnval=16&session=30da7d89c0c56522082f8d6561bb748e&balh_ajax=1
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"88UFO88","mid":18012433,"level":5,"vip_expire":1593964800000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by 88UFO88** [comment]
debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep292240
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function (a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function (a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=74043069&cid=126663920&qn=64&type=&otype=json&ep_id=292240&fourk=1&fnver=0&fnval=16&session=2342108408864c9b194aed8b1436655b
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":5968028195,"length":7756050,"url":"https://video-ru.biliplus.com/file/3dc5f64ec2e18c62123bd4a50812af4c/1574687338/238075402/1l1WVGMQnSu10P_2kkWiIM2T_HTFx_DpY/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"88UFO88","mid":18012433,"level":5,"vip_expire":1649692800000}},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function (a,b){return new e.fn.init(a,b,h)} -> function (e,i){return new l.fn.init(e,i,t)}
debug: injectAjax at: function (e,i){return new l.fn.init(e,i,t)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=74043069&cid=126663920&qn=64&type=&otype=json&ep_id=292240&fourk=1&fnver=0&fnval=16&session=b388c0a55029fbb53e6b1209274a4fae&balh_ajax=1
debug: /x/web-interface/nav {"uname":"88UFO88","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":5968028195,"length":7756050,"url":"https://video-ru.biliplus.com/file/4c84b4c6fda1adde11e36510e60c677f/1574687339/238075402/1l1WVGMQnSu10P_2kkWiIM2T_HTFx_DpY/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"88UFO88","mid":18012433,"level":5,"vip_expire":1649692800000}}
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=74043069&cid=126663920&qn=16&type=&otype=json&ep_id=292240&fourk=1&fnver=0&fnval=16&session=b388c0a55029fbb53e6b1209274a4fae&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":5968028195,"length":7756050,"url":"https://video-ru.biliplus.com/file/85b0800e9ca17fa164acc821cdd716f2/1574687347/238075402/1l1WVGMQnSu10P_2kkWiIM2T_HTFx_DpY/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"88UFO88","mid":18012433,"level":5,"vip_expire":1649692800000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
