### ISSUE TITLE
从代理服务器拉取视频地址失败

### ISSUE THREAD

**Issue by xiaojier** [ipcjs/bilibili-helper#156]
log: [解除B站区域限制 v6.7.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep4403
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"鸡儿小杰瑞","isLogin":true,"level":4,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":4404,"last_ep_index":"3","last_time":1316}}}
log: setAreaLimitSeason ep4403 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=24866478|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=ce1e81cb691fc3ac73954c779be80086
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by ipcjs** [comment]
#155
