### ISSUE TITLE
脚本无效，显示 error:[object Object]

### ISSUE THREAD

**Issue by Zheng9710** [ipcjs/bilibili-helper#157]
## 描述
脚本无效，显示 error:[object Object]

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

![image](https://user-images.githubusercontent.com/36422659/36118525-a2ff1a02-103d-11e8-93b2-086cff7b3ea5.png)

## 其他

1. 浏览器版本：Google Chrome 
版本 64.0.3282.140（正式版本） （64 位）
2. 国家/地区：德国

**Comment by ipcjs** [comment]
日常抽风而已😣

**Comment by ipcjs** [comment]
是这个视频吗？ https://www.biliplus.com/video/av19459268/
biliplus好像也不能播放呀

**Comment by Zheng9710** [comment]
是这个视频。
是因为视频被删了才不能看的么？


ipcjs <notifications@github.com> 于2018年2月13日周二 上午11:37写道：

**Comment by ipcjs** [comment]
6.7.9修复

B站日剧貌似也会归类到番剧里了，但通过biliplus的番剧查询接口却并不能找到番剧信息，于是出错了~~

**Comment by ipcjs** [comment]
话说你是在哪找到这个视频的？
有没有像动画一样的番剧页面？

**Comment by Zheng9710** [comment]
没有的，我是在其他视频底下的推荐里找到的

ipcjs <notifications@github.com> 于 2018年2月13日周二 下午12:33写道：

**Comment by ipcjs** [comment]
好吧，看来B站还在改版中，过段时间应该会上日剧的番剧页面

**Comment by Zheng9710** [comment]
嗯 问题不大，我现在去其他地方找资源好了。

ipcjs <notifications@github.com> 于 2018年2月13日周二 下午12:42写道：
