### ISSUE TITLE
同一番剧最新一集无法播放

### ISSUE THREAD

**Issue by chen185102** [ipcjs/bilibili-helper#158]
## 描述
日剧 unnatural 第七集无法播放，而之前的都可以播放

## 日志
第七集日志如下

log: [解除B站区域限制 v6.7.10 (Violentmonkey)] run on: https://www.bilibili.com/video/av20175371/
VM45:174 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: undefined readyState: loading isLogin: false isLoginBiliBili: false

而之前的比如第一集

log: [解除B站区域限制 v6.7.10 (Violentmonkey)] run on: https://www.bilibili.com/video/av18402853/
VM40:174 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: undefined readyState: loading isLogin: false isLoginBiliBili: false
VM40:895 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
value @ VM40:895
VM40:174 log: av18402853属于番剧23769, 但却不能找到番剧页的信息, 试图直接创建播放器
VM60:174 log: [解除B站区域限制 v6.7.10 (Violentmonkey)] run on: https://www.bilibili.com/blackboard/html5player.html?cid=30037308&aid=18402853&player_type=1
VM60:174 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: undefined readyState: loading isLogin: false isLoginBiliBili: false
VM60:174 log: player msg: 从代理服务器拉取视频地址中...

## 其他

1. 浏览器版本：Chromium 64.0.3282.140
2. 国家/地区：中国大陆

**Comment by ipcjs** [comment]
日志没复制全吧？剩下的部分呐

**Comment by chen185102** [comment]
> The SSL certificate used to load resources from <URL> will be distrusted in M<XX>. Once distrusted, users will be prevented from loading these resources. See <URL> for more information.
VM122:174 log: [解除B站区域限制 v6.7.10 (Violentmonkey)] run on: https://www.bilibili.com/video/av20175371/
VM122:174 debug: XMLHttpRequest的描述符: {value: ?, writable: true, enumerable: false, configurable: true}
VM122:174 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: undefined readyState: loading isLogin: false isLoginBiliBili: false
video.c855d50da196cc6d527c0daa2883e998d6f09f2d.js:1                      //
         \\         //
          \\       //
    ##DDDDDDDDDDDDDDDDDDDDDD##
    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___
    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \
    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \
    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \
    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \
    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\
    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|
    ## MMMMMMMMMMMMMMMMMMMM ##
    ##MMMMMMMMMMMMMMMMMMMMMM##                                        Release 1.13.8. Powered by 主站前端.
         \/            \/
video.c855d50da196cc6d527c0daa2883e998d6f09f2d.js:1 {__ob__: Ki}
(index):1 The resource https://s1.hdslb.com/bfs/static/jinkela/videoplay/images/2233_1080p.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
(index):1 The resource https://s1.hdslb.com/bfs/static/jinkela/videoplay/images/sp2.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
(index):1 The resource https://s1.hdslb.com/bfs/static/jinkela/videoplay/images/wh2.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.

这个就是全部了，小电视那个我觉得无关所以删了。。

**Comment by ipcjs** [comment]
6.7.11 修复
