### ISSUE TITLE
時間軸無法拖動

### ISSUE THREAD

**Issue by ageryuu** [ipcjs/bilibili-helper#161]
## 描述
只要開啟此script，時間軸就無法拖動。

## 其他

1. 浏览器版本：Firefox 58.0.2 (64-bit)
2. 国家/地区：臺灣

**Comment by ipcjs** [comment]
时间轴和脚本还会有关系？日志发上来看看？

**Comment by ageryuu** [comment]
問題解決了，感覺是 Greasemonkey 的問題，換成 Tampermonkey 就沒問題了，抱歉打擾了orz

**Comment by ipcjs** [comment]
我用firefox+油猴试了下没问题呀
