### ISSUE TITLE
EDGE不显示设置图标

### ISSUE THREAD

**Issue by Suzushina** [ipcjs/bilibili-helper#162]
## 描述

![image](https://user-images.githubusercontent.com/37187315/37162284-d515e69c-232f-11e8-9747-c76703b0ae4f.png)

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

![image](https://user-images.githubusercontent.com/37187315/37162552-79696552-2330-11e8-9b3e-577c72fea5d2.png)

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
EDGE上的问题是脚本加载时机的问题，详见： #114 
这个加载时机，要重构起来很麻烦，目前没这个打算，推荐你还是换用Chrome、Firefox吧
