### ISSUE TITLE
视频播放失败/unnatural

### ISSUE THREAD

**Issue by pipukaka** [ipcjs/bilibili-helper#163]
## 日志

```
<!--error: 
Object { code: 1, message: "该视频不能播放,cid:30037308" }
userscript.html:175:17
log: player msg: 服务器错误: {"code":1,"message":"该视频不能播放,cid:30037308"}
userscript.html:175:17
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
userscript.html:175:17
debug: ajax: https://interface.bilibili.com/playurl?cid=30037308&player=1&qn=80&quality=80&ts=1520653076&sign=79d432308ea1d4c42114db512e22a609
userscript.html:175:17
log: xml2obj 
XMLDocument {  }
 => 
Object { result: "suee", timelength: 3529064, format: "flv", accept_format: "flv,flv720,flv480,mp4", accept_quality: […], quality: 80, from: "local", seek_param: "start", seek_type: "offset", durl: […] }
userscript.html:175:17
 -->
```

## 其他

1. 浏览器版本：firefox 58.0.2
2. 国家/地区：大陆四川

**Comment by ipcjs** [comment]
好像拉到了B站接口呀，还是不能播吗？

**Comment by ipcjs** [comment]
还有视频链接，放下

**Comment by pipukaka** [comment]
https://www.bilibili.com/bangumi/play/ep197630
要么就是小电视要么就是和谐界面，刷新多少次都不行TVT
![tim 20180310113142](https://user-images.githubusercontent.com/37232616/37237988-69223cfa-2457-11e8-9446-b752b9e9c170.png)

**Comment by pipukaka** [comment]
还需要提供什么别的嘛？确认是HTML5，也不是已知错误提示。两个代理服务器都试过，一样的结果。是我哪里操作不对嘛？

**Comment by ipcjs** [comment]
😅这问题得 @esterTion

**Comment by ipcjs** [comment]
喷了，这个地址可以播：https://www.bilibili.com/video/av18652954/

**Comment by pipukaka** [comment]
咦好神奇……土下座跪谢！（这问题算是解决了嘛233）

**Comment by ipcjs** [comment]
我记得av页面和bangumi页面唯一的不同就是cid参数后面是否有加`|bangumi`，大概是这个参数依然在发挥着某种神奇的作用😅
@esterTion

**Comment by pipukaka** [comment]
就是用番剧搜索结果的链接就无法播放但是单独点每一集的AV号进去就可以吼！

**Comment by esterTion** [comment]
code1表示不是番剧，不允许用番剧module

**Comment by esterTion** [comment]
注意检查`window.__INITIAL_STATE__.mediaInfo.season_type`，动画为1，电视剧为5，限制季度类型添加module

---
```
season_type = [
  1, //动画
  2, //电影
  5  //电视剧
]
//其他未知
```

---
确认了下不同season_type只有`bangumi.bilibili.com/view/api/season`支持，我可能需要计划一下更换api，之后再看看
[season_v5](http://bangumi.bilibili.com/api/season_v5?appkey=27eb53fc9058f8c3&build=12540&platform=ios&season_id=21542&sign=99c79367669ff768774e4b54cda47fbc)
[view/api/season（同一季度）](http://bangumi.bilibili.com/view/api/season?appkey=27eb53fc9058f8c3&build=12540&platform=ios&season_id=21542&season_type=1&sign=83bac8b4168c2a9dca5d5dedfedd6dc8)
[view/api/season（电影）](http://bangumi.bilibili.com/view/api/season?appkey=27eb53fc9058f8c3&build=12540&platform=ios&season_id=12044&season_type=2&sign=95d8899b05186ad1e5fbe1169a6d761d)

---
新接口少一些信息，想了下我可以设置有season_type参数的时候走新口这样，我网页上还要显示cast staff的

**Comment by ipcjs** [comment]
@esterTion 以前的`|bangumi`已经不使用的，现在是通过`module=bangumi`，判断是否是番剧视频吗？

**Comment by esterTion** [comment]
两个同时生效，不过module判断位置靠后所以优先级高
（|movie&module=bangumi，bangumi生效）

**Comment by ipcjs** [comment]
也就是说，我可以把`|bangumi`删了，只管`module=bangumi`就行了😅

**Comment by ipcjs** [comment]
@pipukaka 6.7.13 代码改了，不需要点进av页面了

**Comment by pipukaka** [comment]
感恩！【比心ღ( ´･ᴗ･` )】

**Comment by Lynx1091** [comment]
一部分国内的番剧可以播放，但是很多都是
## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"BeeKJ\",\"mid\":322884370,\"level\":3,\"vip_expire\":0}}","code":-404}

可以考虑进行如下尝试:
1. 多刷新几下页面
2. 进入设置页面更换代理服务器
3. 耐心等待代理服务器端修复问题

然后我不管怎么更换代理服务器都没有用

**Comment by Lynx1091** [comment]
@esterTion

**Comment by Lynx1091** [comment]
debug: [解除B站区域限制 v7.8.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep114687?from=search&seid=6786443800787367804
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: /x/web-interface/nav {"uname":"BeeKJ","isLogin":true,"level":3,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1565539200000,"status":0,"type":1},"watch_progress":{"last_ep_id":114687,"last_ep_index":"1","last_time":0}}}
debug: setAreaLimitSeason ep114687 true
debug: /x/web-interface/nav {"uname":"BeeKJ","isLogin":true,"level":3,"vipType":1,"vipStatus":0,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 4
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=15138420&cid=46481703&qn=0&type=&otype=json&ep_id=114687&fnver=0&fnval=16&session=7355756eb1513c47f5f6006d7b9d2960&module=bangumi&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=46481703&otype=json&ts=1570588015&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&access_key=775025e4000335c539ec77df90ffcba1&qn=112&sign=176742014d6b48712267cd093c1fdfcc","loginStatus":{"isLogin":true,"uname":"BeeKJ","mid":322884370,"level":3,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=46481703&otype=json&ts=1570588015&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&access_key=775025e4000335c539ec77df90ffcba1&qn=112&sign=176742014d6b48712267cd093c1fdfcc\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"BeeKJ\",\"mid\":322884370,\"level\":3,\"vip_expire\":0}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
