### ISSUE TITLE
请求支持 B 站直播间……

### ISSUE THREAD

**Issue by xdxdy** [ipcjs/bilibili-helper#164]
## 描述
B 站直播映评馆分类，海外无法观看😂。您看是不是能支持支持。十分感谢

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
😅 直播和动画页面完全不一样，没有支持的打算
