### ISSUE TITLE
猎豹浏览器使用问题

### ISSUE THREAD

**Issue by dododoi** [ipcjs/bilibili-helper#166]
## 描述

我使用的是猎豹浏览器，脚本在番剧合集页面可以运行https://bangumi.bilibili.com/anime/21680/，但是在番剧播放页面就不会运行https://www.bilibili.com/bangumi/play/ep183808。同样脚本在chrome浏览器就可以正常使用。。。两个浏览器我都是用完全相同的方法安装脚本的，浏览器均为默认的设置

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
猎豹浏览器v6.5.115.18552
2. 国家/地区：
中国

**Comment by dododoi** [comment]
![123](https://user-images.githubusercontent.com/37523441/37575571-d6d7799c-2b62-11e8-8fb7-388358c0ccb7.png)
![1234](https://user-images.githubusercontent.com/37523441/37575572-d70f45e8-2b62-11e8-9c13-e5ddf1c8ad34.png)

**Comment by dododoi** [comment]
![123](https://user-images.githubusercontent.com/37523441/37575617-0e60ffa0-2b63-11e8-9815-a240e65fab46.png)
![1234](https://user-images.githubusercontent.com/37523441/37575618-0e9312b0-2b63-11e8-887c-ba189f8db6c1.png)

**Comment by dododoi** [comment]
这个脚本之前是可以正常使用的

**Comment by ipcjs** [comment]
控制台日志

**Comment by dododoi** [comment]
打扰了dalao，我把页面模式调了下就好了。
