### ISSUE TITLE
能不能做一個全局替換的版本

### ISSUE THREAD

**Issue by i9602097** [ipcjs/bilibili-helper#172]
## 描述
能不能做一個全局替換的版本
(即是連普通投稿也改用B+接口)
最近B站不知道又發了什麼瘋
直接限速到1X碼率
快進根本不可能
即使是1X倍速看遇上動態碼率較高的地方也會卡頓
但是改用B+看是正常的
還是和以往一樣限千多KB/s左右
看番時因為一早被腳本替換為B+接口
因而出現看番比看普通投稿更流暢的奇怪體驗
希望能做一個全替換版本不再用B站垃圾接口
真是再不能忍受B站限到百多KB/s的做法

**Comment by ipcjs** [comment]
应该只要改下几个判断就行呗，自己改下吧

**Comment by i9602097** [comment]
不行，看不懂，求指導

**Comment by ipcjs** [comment]
按这个提交记录的说明进行操作: 865cfc12accb56e5f74cbe70f1c3b22d5edf261e

**Comment by i9602097** [comment]
感謝
還以為是從頁面地址上找
本身水平不夠真看不出沒有對interface.bilibili.com的接口進行處理
明天看看自己能不能做個選項出來
能就提交pull request上來吧
___________________________________________________
補圖
太感動了
看少戰終於不卡了
![screenshot-www bilibili com-2018 03 24-02-06-07](https://user-images.githubusercontent.com/18757629/37846291-20443da6-2f08-11e8-84ce-2d561df1b4bf.png)

**Comment by ipcjs** [comment]
目前除你之外没人有这样的需求😅。所以没做成选项

**Comment by i9602097** [comment]
那就我做吧！
知道要改那裏就好做多了

**Comment by i9602097** [comment]
想問一下一定要開永封大會員嗎
只開重定向不行？

**Comment by i9602097** [comment]
交了PR
去 #174 看看吧

**Comment by ipcjs** [comment]
没必要再加个和“重定向”一样的模式，我改成“在AV页面启用”的选项了；

勾选“重定向” + “在AV页面启用”，就是你要的效果

**Comment by i9602097** [comment]
因為邏輯上需要重定向才能在投稿頁啟用
為了避免使用者沒使用重定向
才另設一模式直接是重定向加在投稿頁啟用
以確保這設定有效
這是我一開始的想法

**Comment by esterTion** [comment]
这么刺激的吗，限速居然又改回1x了（

>~重新算sign把参数加个`npcybs=1`是同样的效果，不过可能还有cdn加成吧。我记得说是自建是按关键帧限速的~

**Comment by esterTion** [comment]
紧张刺激的TypeError来了
```
TypeError: one_api.asyncAjax(...).compose is not a function                av20792512:998:25
injectAjax/$.ajax                          https://www.bilibili.com/video/av20792512/:998:25
```

**Comment by ipcjs** [comment]
。。。这是什么情况

**Comment by i9602097** [comment]
@esterTion 百多K要人怎看！哭哭
幸好你這裡沒問題
![screenshot-www bilibili com-2018 03 25-03-42-28](https://user-images.githubusercontent.com/18757629/37868277-b2a590f6-2fde-11e8-9731-a6aa6e5331e1.png)

**Comment by ipcjs** [comment]
@esterTion 简直有毒，页面中有代码会替换掉window.Promise，导致找不到我给window.Promise添加的方法

**Comment by Grft** [comment]
万万没想到这个两年前的issue一举解决了我在海外看b站二倍速只敢720的问题，看来b站真的是一点长进都没有，感谢各位的贡献！

**Comment by MC-dusk** [comment]
*挖坟抱歉*
我终于看明白了，`在AV页面启用`指普通的用户投稿。
楼主应该是在海外，用B+反代会流畅些？
18年只有av号，但现在有BV号了。。
建议改名：`在普通视频启用`

**Comment by owwkmidream** [comment]
现在这个功能似乎失效了...？

**Comment by SekiBetu** [comment]
B站作妖，现在普通视频都很卡，这个功能还有效吗

**Comment by blueset** [comment]
最近的 `playurl` 接口路径变成了 `https://api.bilibili.com/x/player/wbi/playurl`，但是 Bilibili-helper 的脚本没有跟上更新，而且好像也没有反代服务器放行了这个接口

**Comment by WorldlineChanger** [comment]
而且最近两天B站不知道又在搞什么，境外IP不能加载一些分区的直播了，比如星际公民和守望先锋，不知能否实现在直播页面启用？

**Comment by WorldlineChanger** [comment]
> 而且最近两天B站不知道又在搞什么，境外IP不能加载一些分区的直播了，比如星际公民和守望先锋，不知能否实现在直播页面启用？

经测试，直播也是通过国内节点获取地址后，即可正常观看了
