### ISSUE TITLE
无限的突破黑洞失败，登录多次也没用

### ISSUE THREAD

**Issue by Miloxing** [ipcjs/bilibili-helper#175]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
log: [解除B站区域限制 v6.8.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss12538/?from=search&seid=15066814423626711625
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"叶子绘","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: setAreaLimitSeason ss12538 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=30972867&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=movie&season_type=2&qn=80&sign=aa1b22b7b777df11e710bc5a6758991f
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=30972867&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=movie&season_type=2&qn=16&sign=0e916a9e7ca0a06606ad038ab43e342c
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
log: balh_flv_prefer_ws  =>  
error: >>area limit
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
貌似是playurl的问题
@esterTion

**Comment by DagleLK** [comment]
我是无法抓取视频 failed to load resource

<
log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep173296
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 debug: XMLHttpRequest的描述符: Object
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: undefined readyState: loading isLogin: true isLoginBiliBili: true
https://data.bilibili.com/a/www.js?_=1521950745082 Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 log: /x/web-interface/nav Object
login?act=expiretime:1 Uncaught SyntaxError: Unexpected identifier
2https://data.bilibili.com/log/web?0000141521950745901https%3A%2F%2Fwww.bili…F21542|666.10.0.0|1521950745926|1481466680|1920x925|1|{%22sort%22:%220%22} Failed to load resource: the server responded with a status of 503 ()
ep173296:1 XMLHttpRequest cannot load https://data.bilibili.com/log/web?0000141521950745901https%3A%2F%2Fwww.bili…2F21542|666.10.0.0|1521950745926|1481466680|1920x925|1|{%22sort%22:%220%22}. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.bilibili.com' is therefore not allowed access. The response had HTTP status code 503.
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":173295,"last_ep_index":"10","last_time":-1}}}
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 log: setAreaLimitSeason ep173296 true
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 log: player msg: 从代理服务器拉取视频地址中...
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=34529031&appkey=84956560bc028eb7…&module=bangumi&season_type=1&qn=112&sign=186efa48cd64ee3134fe728121902724
2https://data.bilibili.com/log/web?0000161521950745901https%3A%2F%2Fwww.bili…21950745996|1920x925|1|{%22num%22:1,%22name%22:%22report-scroll-module%22} Failed to load resource: the server responded with a status of 503 ()
ep173296:1 XMLHttpRequest cannot load https://data.bilibili.com/log/web?0000161521950745901https%3A%2F%2Fwww.bili…521950745996|1920x925|1|{%22num%22:1,%22name%22:%22report-scroll-module%22}. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.bilibili.com' is therefore not allowed access. The response had HTTP status code 503.
2https://data.bilibili.com/log/web?0000161521950745901https%3A%2F%2Fwww.bili…21950745996|1920x925|1|{%22num%22:3,%22name%22:%22report-scroll-module%22} Failed to load resource: the server responded with a status of 503 ()
ep173296:1 XMLHttpRequest cannot load https://data.bilibili.com/log/web?0000161521950745901https%3A%2F%2Fwww.bili…521950745996|1920x925|1|{%22num%22:3,%22name%22:%22report-scroll-module%22}. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.bilibili.com' is therefore not allowed access. The response had HTTP status code 503.
https://cn-zjjh4-dx-v-05.acgvideo.com/vg2/upgcxcode/34/88/16638834/16638834…MTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=9178762553b640469ab54af71e72bddb Failed to load resource: the server responded with a status of 460 ()
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 log: player msg: 从代理服务器拉取视频地址中...
userscript.html?id=0ab03fca-6644-494a-bbb3-2667e5cfaa4b:175 debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=34529031&appkey=84956560bc028eb7…6&module=bangumi&season_type=1&qn=16&sign=1e45cbbc939d35a8a75ab708a32edcdd
https://cn-zjjh4-dx-v-05.acgvideo.com/vg2/upgcxcode/34/88/16638834/16638834…MTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=e3bcac5a36cb482d82a1e45181ffebae Failed to load resource: the server responded with a status of 460 () 
>

什么时候开始的不知道，最近忙好几天没上

顺带一提，播放的是《紫罗兰永恒花园》第十一集失败，但是第十集可以正常抓取播放，不像是炸了服务器的样子，像是新一集用了新算法。

**Comment by esterTion** [comment]
仅限hk还行，暂时懒的加判断了，这些也没个地方获取地区

**Comment by pakasas** [comment]
目前仅限港澳台的番剧还能看，但是大陆限定的番剧，海外完全看不了了
下边是日志


log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25739/?spm_id_from=333.334.b_62696c695f62616e67756d69.16
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"Pakasas","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586966400000,"status":1,"type":2},"watch_progress":{"last_ep_id":250467,"last_ep_index":"8","last_time":0}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=02ed6e26c1a87dd17867ada07a34ed09
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=49e99e7cf820b2d47224a8e08e763f1f
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by esterTion** [comment]
这视频什么毛病，其他视频没问题 比如 弦音 -风舞高中弓道部- cid 63748037
这个我本地可以，服务器不行
？？？

---
似乎分发爆了？本地没刷出112以外的清晰度

**Comment by ipcjs** [comment]
不知道，脚本这边看不出来，貌似下午开始的（
