### ISSUE TITLE
为什么提示要下载flash插件？

### ISSUE THREAD

**Issue by jackport** [ipcjs/bilibili-helper#177]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by jackport** [comment]
![default](https://user-images.githubusercontent.com/37954320/38162499-bf7b98e4-3514-11e8-9265-2fbede63faf3.png)

**Comment by jackport** [comment]
g: mode: redirect blocked_vip: Y server: "https://www.biliplus.com" flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true  userscript.html:175:17
所用的 getPreventDefault() 已不赞成使用。请使用 defaultPrevented 替代。  jquery.min.js:3:7108
所用的 Mutation Events 已不赞成使用。请使用 MutationObserver 替代。  ss21680:351:4
log: /x/web-interface/nav Object { uname: "1806938340", isLogin: true, level: 3, vipType: 0, vipStatus: 0 }  userscript.html:175:17
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183806,"last_ep_index":"8","last_time":1}}}  userscript.html:175:17
App Initialized.  no-flash-tips.min.js:9:1380
无法播放媒体。没有相应格式的解码器：video/mp4; codecs="avc1.42001E mp4a.40.2"

**Comment by cyanlink** [comment]
@jackport 视频av号？使用的平台及浏览器？linux下firefox需要安装gstreamer全套，chrome需要安装一个freeworld的解码器包，否则不支持mp4播放

**Comment by jackport** [comment]
视频DARLING in the FRANXX（僅限港澳台地區） 平台bilibili 浏览器火狐

**Comment by jackport** [comment]
小白一枚，后面的没看懂

**Comment by cyanlink** [comment]
linux还是windows？ @jackport

**Comment by jackport** [comment]
windows

**Comment by cyanlink** [comment]
@jackport b站播放器切换为html5了没，Windows下不该有解码器问题

**Comment by jackport** [comment]
https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6
脚本首页 @LinkEscapist

**Comment by jackport** [comment]
主要是不会切换2333 @LinkEscapist

**Comment by cyanlink** [comment]
![html5](https://user-images.githubusercontent.com/14952800/38162632-44a8bbf8-3517-11e8-9331-aac33a4f1739.PNG)

**Comment by jackport** [comment]
我的怎么是这样的
    @LinkEscapist ![default](https://user-images.githubusercontent.com/37954320/38162653-9f70e1f0-3517-11e8-8430-00f0ff8f97cb.png)

**Comment by cyanlink** [comment]
@jackport 请问firefox浏览器版本？

**Comment by jackport** [comment]
请问在哪里能看到|？ @LinkEscapist

**Comment by jackport** [comment]
![default](https://user-images.githubusercontent.com/37954320/38162724-2685865e-3519-11e8-8b3a-d4ff39dddd05.png)
找到了

**Comment by cyanlink** [comment]
windows10 64bit，firefox 59（最新版本），能够选择html5播放器并正确播放，请安装最新版本  https://www.mozilla.org/en-US/firefox/new/ （另：win xp已经绝对不该再继续使用，请找办法至少升级到win7）

**Comment by jackport** [comment]
大佬还在吗 @LinkEscapist

**Comment by jackport** [comment]
winXP不能用呀

**Comment by jackport** [comment]
尴尬了

**Comment by cyanlink** [comment]
@ipcjs close掉吧，与本项目不相关问题

**Comment by jackport** [comment]
好吧我知道了
谢谢大佬 @LinkEscapist

**Comment by jackport** [comment]
最后一个问题

**Comment by jackport** [comment]
怎么close掉。。。。。

**Comment by jackport** [comment]
实在不会玩233

**Comment by cyanlink** [comment]
@jackport 这个需要维护者来关掉

**Comment by ipcjs** [comment]
你这是哪找来的xp😅
