### ISSUE TITLE
拉取视频地址失败，无法使用备用服务器

### ISSUE THREAD

**Issue by lyflyflxf** [ipcjs/bilibili-helper#178]
已经按常见问题的解决方案走了一遍
## 描述

1.刷新了三四遍，仍然不行
2.备用服务器也无法使用
![](https://i.loli.net/2018/04/01/5ac01c8dc1766.png)

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

脚本没有崩溃，但我没找到导出插件本身日志的方法，囧
下面是控制台日志
![](https://i.loli.net/2018/04/01/5ac01e117eac7.png)
## 其他

1. 浏览器版本：Chrome 65 X64
2. 国家/地区：中国大陆

**Comment by Virace** [comment]
两个 biliplus 都打不开了，等网站修复吧
