### ISSUE TITLE
[解除B站区域限制] 測試

### ISSUE THREAD

**Issue by FlandreDaisuki** [ipcjs/bilibili-helper#18]
## 描述
1. 不知道上面的 title 能不能 template ?
2. 為什麼不直接新增一個新 repository ?
感覺這個專案的 title / 裡面的 scripts / 這個 issue template 都對不起來
3. 為什麼要 `Object.defineProperty(ret, 'name', Object.getOwnPropertyDescriptor(func, 'name'))` ?

## 日志

```
log: [解除B站区域限制 v6.1.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep115311
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://www.biliplus.com flv_prefer_ws:  readyState: loading
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0}}
    log: [解除B站区域限制 v6.1.0 (Tampermonkey)] run on: https://www.bilibili.com/blackboard/html5player.html?cid=28646766&aid=17544713&season_type=1&lastplaytime=0&has_next=0&player_type=1&urlparam=module%253Dbangumi%2526season_type%253D1&seasonId=6434&episodeId=115311&p=1&crossDomain=true
    debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
    log: mode: redirect blocked_vip: Y server: https://www.biliplus.com flv_prefer_ws:  readyState: loading
    log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=28646766|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=77594e410846b69425b74779e9985174
debug: userAgent Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
```

## 其他

1. 浏览器版本：上面的ua其實就比這個清楚了阿(雖然可以替換)
2. 国家/地区：台灣

**Comment by ipcjs** [comment]
1. 标题不能设模板，GitHub有另外一套tag系统，不需要靠标题区分
2. 新增仓库要拆分提交记录。。。好麻烦_(:3」∠)_
2. `Object.defineProperty(ret, 'name', Object.getOwnPropertyDescriptor(func, 'name'))`,不是用来修改函数名的吗，函数名属性不能直接修改，在有些脚本引擎里面会报错，但可以修改描述符，达到修改的目的
3. 浏览器版本是个重要信息，如果复制日志失败，就看不到了

**Comment by FlandreDaisuki** [comment]
> 新增仓库要拆分提交记录

從 6.0 當個全新的開始就好啦 😂

> 不是用来修改函数名的吗

其實我的疑問就是，為什麼要去修改函式名？
不是問修改的手段，而是目的
我看了一下大部分傳進去的都是匿名函式
為什麼要對匿名函式修改函式名？

> 如果复制日志失败

我都忘了確實要處理這件事 😂

**Comment by ipcjs** [comment]
> 為什麼要對匿名函式修改函式名？

代码我也是抄别人的，就是那个Yet_Another_Weibo_Filter，他里面复制了函数名。
不过函数名这个属性，各浏览器实现上都不一致，不知道他那边怎么没人报bug的

> 從 6.0 當個全新的開始就好啦

改了半天，没动力了😫

**Comment by FlandreDaisuki** [comment]
> 代码我也是抄别人的，就是那个Yet_Another_Weibo_Filter，他里面复制了函数名。

我當初看程式的時候一直很納悶這段到底想幹麻
原來沒有特別意思zzz
那我覺得可以刪掉這個(函式改名)行為，那行刪掉後我沒噴什麼異常

因為那邊論壇有個因為 descriptor 被丟 exception 導致 script 被中斷的 Edge 使用者
~~但我不確定是不是真的只有差在這段就是了，懶得開虛擬機跑 Windows~~ \_(:3」∠)_

**Comment by ipcjs** [comment]
是的，垃圾Edge，匿名函数获取的name是空字符串，获取到的name的描述符却是undefined😤
我做了个判断，应该不会报错了
