### ISSUE TITLE
突然不好使了

### ISSUE THREAD

**Issue by abbotye** [ipcjs/bilibili-helper#183]
## 描述

今天看更新的wixoss发现无法解锁限制了,前几天刚更新银英的时候还可以用.现在都打不开了,报错信息一样,然后重复提示账号授权点击同意以后提示超时三次验证失败

## 日志

```
log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep200307
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"翼在天","isLogin":true,"level":5,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: setAreaLimitSeason ep200307 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=35885135&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=7e225607f64cafce41fead274a285d38
error: {"code":-502,"message":"无法连接到playurl"}
log: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\"}","code":-502}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=35885135&player=1&qn=112&quality=112&ts=1523035919&sign=05626c1a5df6ceff9c3dfc63cb0beeac
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```

## 其他

1. 浏览器版本：Chrome最新版
2. 国家/地区：大陆

**Comment by MITVIP** [comment]
log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep173336
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":173335,"last_ep_index":"9","last_time":242}}}
log: /x/web-interface/nav {"uname":"我就是哈哈","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=35161582&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=c6f1534abacd74203239e33188aa1088
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
error: {"code":-502,"message":"无法连接到playurl"}
log: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\"}","code":-502}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=35161582&player=1&qn=116&quality=116&ts=1523047409&sign=c4688ac23c5a898a25f6a24d872671af
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: balh_mode  =>  default
log: balh_enable_in_av  =>
