### ISSUE TITLE
拉取视频失败，并且无法打开代理服务器上的链接

### ISSUE THREAD

**Issue by syz0610** [ipcjs/bilibili-helper#188]
## 描述

拉取视频失败，按照上面的帮助页面尝试打开代理服务器上的链接（https://biliplus.ipcjs.win/api/bangumi?season=5551），结果报错504 Gateway Timeout

尝试在页面中更换代理设置，仍然失败

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss1089/?from=search&seid=823472731442091658
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: /x/web-interface/nav Object
2data.bilibili.com/e/p Failed to load resource: the server responded with a status of 503 ()
?from=search&seid=823472731442091658:1 Failed to load https://data.bilibili.com/e/p: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.bilibili.com' is therefore not allowed access. The response had HTTP status code 503.
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":34424,"last_ep_index":"64","last_time":0}}}
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: setAreaLimitSeason ss1089 true
comment.min.js:2 Uncaught TypeError: Cannot read property 'length' of undefined
    at a.init (comment.min.js:2)
    at new a (comment.min.js:2)
    at e.loadPage (comment.min.js:1)
    at comment.min.js:2
    at dispatch (jquery.min.js:3)
    at i (jquery.min.js:3)
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: player msg: 从代理服务器拉取视频地址中...
2data.bilibili.com/v/flashplay/h5_player_op?pname=1&mid=&statue=3&playmethod=1&avid=12521979&eventparam=&progress=0&displayid=1523107414908&eventid=enter&trackerid=&cid=23446441&fver=HTML5Player+2bfb6159&seasonid=1089&epid=34424&videotype=1&fid=web_player Failed to load resource: the server responded with a status of 503 ()
?from=search&seid=823472731442091658:1 Failed to load https://data.bilibili.com/v/flashplay/h5_player_op?pname=1&mid=&statue=3&playmethod=1&avid=12521979&eventparam=&progress=0&displayid=1523107414908&eventid=enter&trackerid=&cid=23446441&fver=HTML5Player+2bfb6159&seasonid=1089&epid=34424&videotype=1&fid=web_player: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.bilibili.com' is therefore not allowed access. The response had HTTP status code 503.
www.biliplus.com/BPplayurl.php?cid=23446441&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=5485dbb0709c093a310d9e833a9bbaa4 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
www.biliplus.com/login?act=expiretime Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
?from=search&seid=823472731442091658:1 Uncaught (in promise) undefined
userscript.html?id=6a5c9fc7-aba5-477d-94a3-4604d350b4d8:175 log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
api.bilibili.com/x/web-show/res/loc?pf=0&id=160&aid=12521979&jsonp=jsonp Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
?from=search&seid=823472731442091658:1 The resource https://s1.hdslb.com/bfs/static/bangumi/play/js/bangumi-play.06d96b09.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
?from=search&seid=823472731442091658:1 The resource https://s1.hdslb.com/bfs/static/bangumi/play/js/manifest.06d96b09.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
?from=search&seid=823472731442091658:1 The resource https://s1.hdslb.com/bfs/static/bangumi/play/js/vendor.06d96b09.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
bilibiliPlayer.min.js?v=2bfb6159:1534 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ bilibiliPlayer.min.js?v=2bfb6159:1534
setTimeout (async)
b.zL @ bilibiliPlayer.min.js?v=2bfb6159:1534
b.Qb @ bilibiliPlayer.min.js?v=2bfb6159:1533

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：65.0.3325.181（正式版本） （64 位）
2. 国家/地区： 日本

**Comment by slipingblue** [comment]
+1，同样的问题，而且授权页面的登陆按钮没有作用
log如下：
`log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep200307
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"****","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: setAreaLimitSeason ep200307 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=35885135&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=3da00c134eb4bd12f98a52458dac07d9
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=35885135&player=1&qn=80&quality=80&ts=1523111227&sign=f013852ad4f52c5ad0429bb78a3cf904
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}`

**Comment by syz0610** [comment]
这会儿似乎恢复正常了～

**Comment by YaozhongZhang** [comment]
刚才还可以 突然就不行了

log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183811
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"犭良","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183811,"last_ep_index":"13","last_time":0}}}
log: setAreaLimitSeason ep183811 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=35955160&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=191bca9d200bfb38e28efcf1dcc228b9
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=35955160&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=08c0fbd0771ceeffb8e146cde3b9c6c0
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
