### ISSUE TITLE
这个网址可以解除限制吗？

### ISSUE THREAD

**Issue by Miku039** [ipcjs/bilibili-helper#192]
## 描述

动画疯的网址这个限制可以解除吗？

## 日志

```
https://ani.gamer.com.tw/   台湾地址 但是只有台湾地区可以观看，大陆这边有办法吗
```

## 其他

1. 浏览器版本：Google Chrome 
                          版本 65.0.3325.181（正式版本） （32 位）
2. 国家/地区：中国

**Comment by ipcjs** [comment]
不可以，只支持B站

**Comment by Miku039** [comment]
动画疯很难找到代理服务器的  你们有办法解除这样的限制么  上面好多番剧都不错的 有些国内是没有的
