### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by TRIEW** [ipcjs/bilibili-helper#194]
## 描述

拉取视频地址失败
## 日志

log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss23868
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip: Y server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Serpent","isLogin":true,"level":6,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":199772,"last_ep_index":"2","last_time":-1}}}
log: setAreaLimitSeason ss23868 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=36112988&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=77a54911321cfeb654874570675bf4f0
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=36112988&player=1&qn=112&quality=112&ts=1523429664&sign=2e9e76297fa9b34c2767cae915ffecdc
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

## 其他

1. 浏览器版本：Google Chrome 65.0.3325.181
2. 国家/地区：中国大陆

**Comment by syukouyuu** [comment]
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":199974,"last_ep_index":"2","last_time":-1}}}
userscript.html?id=07dbbb14-45a3-4c11-8599-fe92830c2c40:175 log: setAreaLimitSeason ep199974 true
userscript.html?id=07dbbb14-45a3-4c11-8599-fe92830c2c40:175 log: player msg: 从代理服务器拉取视频地址中...
www.biliplus.com/BPplayurl.php?cid=36199845&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=b8a88a3ed14c6b821b95403ccf068133 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
userscript.html?id=07dbbb14-45a3-4c11-8599-fe92830c2c40:175 log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
userscript.html?id=07dbbb14-45a3-4c11-8599-fe92830c2c40:175 log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
userscript.html?id=07dbbb14-45a3-4c11-8599-fe92830c2c40:175 log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
ep199974:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'length' of undefined
    at Object.m.handlePlayUrl (chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/bilibili_injected.min.js:1:3358)
    at chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/bilibili_injected.min.js:1:5896
www.biliplus.com/login?act=expiretime Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
ep199974:1 Uncaught (in promise) undefined

**Comment by syukouyuu** [comment]
服务器超时错误

**Comment by lilipeipei** [comment]
log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep199683
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"RasieL","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":199682,"last_ep_index":"2","last_time":-1}}}
log: setAreaLimitSeason ep199683 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=36039362&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=3173a52b981f48f495bebc4681820584
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=36039362&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=514e1b7974bf1eac30acd96502bd1779
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by lilipeipei** [comment]
好像最近几天都连不上

如果是服务器土豆的问题的话，可以考虑开捐助嘛

**Comment by zhangcoming** [comment]
多刷新几次，运气好就连上了

**Comment by amostang** [comment]
兩天了還是不行

**Comment by G535681092** [comment]
一直都是error:[object Object]是什么情况啊
