### ISSUE TITLE
授权无效，看不了大会员视频

### ISSUE THREAD

**Issue by HCrSn** [ipcjs/bilibili-helper#197]
## 描述

现在我没办法大会员授权，看不到大会员先看的动画。其他的都没有问题。
点击授权以后提示成功，但是并没有效果
试图取消授权时显示 “感谢使用，正在为您清除登录cookie
访问key删除失败，错误：[403]undefined”

## 日志

log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss23859#199922
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"mtymty","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":199922,"last_ep_index":"2","last_time":-1}}}
log: setAreaLimitSeason ss23859 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=36355561&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=257ecc9e68c7027fd4396ed7ff1b6cb4
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=36355561&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=df6d07362d1446b21862748cca4d7b88
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

## 其他

1. 浏览器版本：Chrome 65.0.3325.181
2. 国家/地区：美国TWC

**Comment by polar2031** [comment]
Got same issue here
