### ISSUE TITLE
2018-4-14 21:23:17  B站darling in the frankxx看不了了

### ISSUE THREAD

**Issue by Eviill** [ipcjs/bilibili-helper#202]
log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss21680/?from=search&seid=12124923439634730557
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"","isLogin":true,"level":5,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183807,"last_ep_index":"9","last_time":-1}}}
log: setAreaLimitSeason ss21680 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=33712259&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=185c3ad21ec5f22d19e867a60ac38586
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=33712259&player=1&qn=0&quality=0&ts=1523711957&sign=c218c3e043828354104ec6495ba21053
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: balh_server  =>  https://www.biliplus.com

**Comment by ipcjs** [comment]
你们提issue之前都不看下已有的issue吗？

**Comment by Eviill** [comment]
啊啊啊啊抱歉，只看了1天之内的提问，他们的提问也都没回复我觉得我的情况可能不一样QAQ，抱歉抱歉
