### ISSUE TITLE
恭喜，服务器貌似每周六炸一次

### ISSUE THREAD

**Issue by 13z79** [ipcjs/bilibili-helper#203]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：Chrome
2. 国家/地区：美帝

**Comment by arthurlee30** [comment]
这么有规律的吗？23333

**Comment by 1043987** [comment]
原来不是我一个人炸

**Comment by huochaitny** [comment]
biliplus挂了，没办法的

**Comment by arthurlee30** [comment]
还能不能看上DITF第14集=V=

**Comment by 1043987** [comment]
233333我也是在等14

**Comment by 1417163886** [comment]
14+1

**Comment by arthurlee30** [comment]
现在好了没？|｡･㉨･)っ

**Comment by WoadZS** [comment]
前面的千万别看14集，胃疼的要死，等下周一起看可能会好很多。

**Comment by lazyZ** [comment]
都在等第14集呀

**Comment by arthurlee30** [comment]
虽然能看了，但是听了楼上的不看，剧情又喂屎了ᖗ( ᐛ )ᖘ

**Comment by 13z79** [comment]
又一次挂了，卡在了从代理服务器拉取视频地址中。

**Comment by amostang** [comment]
看不了啊！所有要大會員特權的番不能看了

**Comment by Viel0320** [comment]
今天也日常炸了

**Comment by LilHayah** [comment]
恩 biliplus.ipcjs.win 又炸了。 周六了

**Comment by rbqscp** [comment]
![default](https://user-images.githubusercontent.com/38126397/39647543-ff38fc02-5011-11e8-89e2-754ff7bde9d8.png)

**Comment by WANGJIEKE** [comment]
果然又炸了

**Comment by rbqscp** [comment]
╮(╯-╰)╭是啊，无奈

**Comment by rbqscp** [comment]
这爆炸的还真是有规律······

**Comment by clsteam** [comment]
每周六炸一次，相当有规律！！

**Comment by david082321** [comment]
恩，真有规律

**Comment by krimeshu** [comment]
原来如此

**Comment by amostang** [comment]
為什麼大家是炸？而我是看不了啊！所有要大會員特權的番不能看了

**Comment by KrisuC** [comment]
现在又炸了

**Comment by makerhxc** [comment]
日常周六炸服务器

**Comment by popoyupopo** [comment]
又炸了

**Comment by yuan3747** [comment]
原来是日常啊2333

**Comment by amostang** [comment]
這不是炸啊朋友們！！！所有要大會員特權的番不能看了！！

**Comment by rbqscp** [comment]
抱歉，就是炸了。(￣▽￣)"

**Comment by amostang** [comment]
可是我已經超過一個月不能看齊木楠雄和一些大會員搶先的番了

**Comment by yuan3747** [comment]
@amostang  你有授权给插件吗 我试过没问题哦
![image](https://user-images.githubusercontent.com/26738148/39706113-f2ae1ee4-5242-11e8-8ac6-e8d33e6c3d3b.png)
