### ISSUE TITLE
想看孤独的美食家

### ISSUE THREAD

**Issue by SolarTorch** [ipcjs/bilibili-helper#21]
## 描述
我是说。。。能不能 加入看剧

**Comment by ipcjs** [comment]
biliplus支持吗？

**Comment by SolarTorch** [comment]
不知道为什么 我的功能正常但是一直没有浮窗 所以改不了

**Comment by ipcjs** [comment]
是这个页面吗？
https://www.bilibili.com/video/av8075425
这个页面是支持的，上次改出bug来了，6.3.2版修复了，你试试

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/commit/6ee8b26dc506de5c9d3b11632ce28c7088e8de00

**Comment by SolarTorch** [comment]
https://www.bilibili.com/video/av17807697/

error:{"code":-403,"message":"访问权限不足","ttl":1}

**Comment by ipcjs** [comment]
看脚本的帮助文档

**Comment by ipcjs** [comment]
@esterTion `/api/view`接口最近改了什么东西吗？
调用 https://biliplus.ipcjs.win/api/view?id=17807697 能正常获取数据。
调用 https://biliplus.ipcjs.win/api/view?id=17807697&update=true 却返回如下数据：
```
{"code":-403,"message":"访问权限不足","ttl":1}
```

**Comment by esterTion** [comment]
因为视频已被删除

**Comment by esterTion** [comment]
嗯？地区剧？

app开了下以为删了，白天看

**Comment by esterTion** [comment]
你服务器设置host是什么，请求没到我服务器
改好改成`proxy_set_header Host www.biliplus.com;`

**Comment by ipcjs** [comment]
(-_-#)居然是我这里配置错了

**Comment by esterTion** [comment]
我刚改了后提交发现你那边没修复，然后我就上vu把其他域名全部403了
主服务器搬了，vu做v6入口
