### ISSUE TITLE
解除港澳台区域限制失败

### ISSUE THREAD

**Issue by haorhea** [ipcjs/bilibili-helper#216]
## 描述

解除港澳台视频（日剧区）区域限制失败，页面显示无此视频

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

![qg y 7b mlboto kl dftn](https://user-images.githubusercontent.com/12350695/38885560-5a2c20c8-4241-11e8-9509-0d853b9342be.png)

## 其他

1. 浏览器版本：62.0.3202.89（正式版本） （32 位）
2. 国家/地区：美国/NJ

**Comment by ipcjs** [comment]
最近的版本修复了这个问题。

顺带，下次别就截个图，请贴下有问题的网址
