### ISSUE TITLE
拉取地址失败

### ISSUE THREAD

**Issue by shxhmy** [ipcjs/bilibili-helper#218]
## 描述

再次出现连接不上，重新授权无效。服务器又炸了嘛，还是我这出了问题。。。

## 日志

log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep199947
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"（我删了username）","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":199946,"last_ep_index":"2","last_time":-1}}}
log: setAreaLimitSeason ep199947 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=36918511&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=129b8e938a3a4a29352f899b4ff8c5ce
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=36918511&player=1&qn=80&quality=80&ts=1524185452&sign=7b6e9bf833e468ef8671c7547c95d77d
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

## 其他

1. 浏览器版本：上面有
2. 国家/地区：美东

**Comment by irokun** [comment]
同样问题，也是美东，难道是被封印了？？
