### ISSUE TITLE
请求开放服务端源码

### ISSUE THREAD

**Issue by ziqizh** [ipcjs/bilibili-helper#219]
## 描述
每周末例行服务器爆炸。请问能不能发一下服务端代码，这样就能搭建自己的服务器给官方服务器减轻点压力了呢？谢谢！

## 日志
并没有日志

## 其他
并没有其他

1. 浏览器版本：Chrome Version 65.0.3325.181 (Official Build) (64-bit) MacOS
2. 国家/地区：美东

**Comment by ipcjs** [comment]
选“备选代理服务器”不是挺好的吗，没碰到啥爆炸呀
