### ISSUE TITLE
国家宝藏无法观看

### ISSUE THREAD

**Issue by david082321** [ipcjs/bilibili-helper#228]
## 描述

国家宝藏无法观看

https://www.bilibili.com/bangumi/play/ss21715/ 
提示：非常抱歉，根据版权方要求，您所在的地区无法观看本片 ~
https://www.bilibili.com/video/av16924077
提示：啊叻？视频不见了？

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
2. 国家/地区：台灣

**Comment by ipcjs** [comment]
6.8.3 试试
