### ISSUE TITLE
Error running script: 解除B站区域限制 

### ISSUE THREAD

**Issue by kdjsf049** [ipcjs/bilibili-helper#229]
## 描述
脚本加载失败
新版firefox v59无法加载成功，试了重新安装脚本也不行
老版v56是可以

## 日志
Error running script: 解除B站区域限制 
Error: Permission denied to access object Permission denied to access object

## 其他

1. 浏览器版本：Firefox 59.0.2
2. 国家/地区：china

**Comment by DenGenkai** [comment]
哇，你在中国也要这个?
