### ISSUE TITLE
B站页面改版，脚本已失效

### ISSUE THREAD

**Issue by Viel0320** [ipcjs/bilibili-helper#230]
需要自行添加一行
`// @include      *://www.bilibili.com/bangumi/media/*  `

**Comment by VielVonEinzbern** [comment]
需要一行自行添加
`// @include      *://www.bilibili.com/bangumi/media/*  `

**Comment by brianal** [comment]
亲测有效。非常感谢！！

**Comment by Verlaski** [comment]
有效

**Comment by ipcjs** [comment]
有哪个页面是这个链接？

**Comment by Viel0320** [comment]
番剧详情页面啊，新改版了，地址也换了

**Comment by brianal** [comment]
似乎又不行了。

**Comment by ipcjs** [comment]
6.8.5 修复

**Comment by ipcjs** [comment]
@VielVonEinzbern 我看的动画都点了追番，不存在要点 番剧详细页面 的问题(;¬_¬)
