### ISSUE TITLE
Qiufeng125

### ISSUE THREAD

**Issue by Qiufeng125** [ipcjs/bilibili-helper#239]
## 描述

log: [解除B站区域限制 v6.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep200308
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"赫墨拉wel","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: setAreaLimitSeason ep200308 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=36422359&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=08735dba5435f62736864a84469bc1fe
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
- 问题网址：
https://www.bilibili.com/bangumi/play/ep200308

## 日志

<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v6.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep200308
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"赫墨拉wel","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=36422359&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=08735dba5435f62736864a84469bc1fe
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Firefork Quantum 59.0.3(64位)
2. 国家/地区：中国山东

**Comment by Qiufeng125** [comment]
视频拉取失败

**Comment by lbldknight** [comment]
每个周六日常崩溃
