### ISSUE TITLE
拉取视频地址失败，而且Biliplus也上不去了

### ISSUE THREAD

**Issue by TRIEW** [ipcjs/bilibili-helper#241]
## 描述

- 问题网址：https://www.bilibili.com/bangumi/play/ep183815

## 日志

<details>
<summary>Verbose log: [解除B站区域限制 v6.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183815
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip: Y server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Serpent","isLogin":true,"level":6,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183815,"last_ep_index":"16","last_time":80}}}
log: setAreaLimitSeason ep183815 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=38263183&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=5b798ab18b3471be7ddb90e92c9ad759
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36</summary>

1. 浏览器版本：Google Chrome 66.0.3359.139
2. 国家/地区：中国大陆

**Comment by Lz1y** [comment]
看了下，两个服务器都无法访问了，怕是宕机还是没流量了。。。

**Comment by simon300000** [comment]
应该和#242 #243 是同一个问题，我也遇到了。。。

**Comment by simon300000** [comment]
http://biliplus.ipcjs.win:
504 Gateway Time-out
怕不是崩了

**Comment by simon300000** [comment]
www.biliplus.com 迷的不得了，在大陆不能访问，开vpn不能访问。
ssh到vpn服务器上用lynx就能访问。
