### ISSUE TITLE
使用脚本之后正常视频也出现无限加载地址然后小电视的情况，卸载无效

### ISSUE THREAD

**Issue by Chumang** [ipcjs/bilibili-helper#244]
## 描述

- 问题网址：

## 日志

log: [解除B站区域限制 v6.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss22843/?spm_id_from=333.334.bili_bangumi.7
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"爱吃咸蛋的完蛋","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: setAreaLimitSeason ss22843 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=30590429&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=dd9772e27358b333298e094afffccb56
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64; rv:59.0) Gecko/20100101 Firefox/59.0

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：火狐
2. 国家/地区：中国上海

**Comment by Chumang** [comment]
然而不限港澳台的番剧能看，直播也能正常观看，唯独普通的非番剧视频会出现加载视频地址并出现小电视的情况，确认过不是B站和本人自身的问题。

**Comment by SEKKOO** [comment]
log: [解除B站区域限制 v6.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183815
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"疾风小王子","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183814,"last_ep_index":"SP","last_time":1418}}}
log: setAreaLimitSeason ep183815 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=38263183&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=080ce63595d43919056810fe2c90e571
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64; rv:59.0) Gecko/20100101 Firefox/59.0

登不上

**Comment by Chumang** [comment]
是的，无论怎么尝试..除了番剧和直播以外的所有视频都是无限加载然后小电视，很烦，我还以为是B站的问题但别人都没这个迹象而且已经一天了，重启过电脑也清理过缓存还换过DNS，所有可能的问题我都试了，包括换播放器

**Comment by Chumang** [comment]
更正一下，似乎是因为会员授权的问题

**Comment by Chumang** [comment]
更新，脚本服务器恢复正常后使用AV所有视频拉取可恢复正常，但无法使用大会员1080P60FPS

**Comment by wutou** [comment]
log: [解除B站区域限制 v6.8.4 (Violentmonkey)] run on: https://www.bilibili.com/bangumi/play/ep96703
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"無頭","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=11234402&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=142e490fd225471b6816ce173fd20786
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-1.flv?wsTime=1526237084&platform=pc&wsSecret2=51619ed6c4577a4f404cf628cfd2152f&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-2.flv?wsTime=1526237084&platform=pc&wsSecret2=c71bd851cc251f1996b4c22d77c4ce60&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-3.flv?wsTime=1526237084&platform=pc&wsSecret2=d860ca4a6edbee8d817d6746da469e4e&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-4.flv?wsTime=1526237084&platform=pc&wsSecret2=682bdd787194c90db6f10f7d658e4a86&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-5.flv?wsTime=1526237084&platform=pc&wsSecret2=17dced8de96d8aa923811a55b9e513f4&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-6.flv?wsTime=1526237084&platform=pc&wsSecret2=792c1cef3a9c216d888b2f694b6ca03c&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-7.flv?wsTime=1526237084&platform=pc&wsSecret2=1c750fb5c223ce58cdba45a82f86e878&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-8.flv?wsTime=1526237084&platform=pc&wsSecret2=a2067a1f24180d60533381b8d9543ae8&oi=2356152436&rate=1200&trid=e931f5224ef44e9f8047182e6245f00f
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=11234402&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=cb618c9e48b4b21290adac14aaff32e7
log: flv prefer use: http://ws.acgvideo.com/1/75/11234402-1.mp4?wsTime=1526237086&platform=pc&wsSecret2=9e9091059de7ecc5ac25f0cc2fac5ad9&oi=2356152436&rate=1200&trid=3fea99d110434734bf4b3fa7714995d5
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

我现在也是同样的问题，现在火狐打开什么视频都是小电视，关掉其他脚本跟拦截广告啥的插件依然这样。但是更换Chrome则正常使用没有问题，dalao能帮忙看是什么问题么……

**Comment by ipcjs** [comment]
@Chumang 现在还是不行？
