### ISSUE TITLE
代理服务器无法拉取视频地址

### ISSUE THREAD

**Issue by shimarenzo** [ipcjs/bilibili-helper#245]
log: [解除B站区域限制 v6.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss22843/?spm_id_from=333.334.bili_bangumi.7
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"izayoisakiya","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":173319,"last_ep_index":"15","last_time":-1}}}
log: setAreaLimitSeason ss22843 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=37096972&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=2715f9b6cc05c0fd4f5de6340cd90466
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
log: balh_server  =>  https://www.biliplus.com
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=37096972&player=1&qn=80&quality=80&ts=1525597215&sign=92eaab10f0ca52197c3b43c59a858b77
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=37096972&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=2715f9b6cc05c0fd4f5de6340cd90466
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=37096972&player=1&qn=80&quality=80&ts=1525597237&sign=3896f18459bfe4cfb08fe4ceae32cd1b
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=37096972&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=2715f9b6cc05c0fd4f5de6340cd90466
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=37096972&player=1&qn=80&quality=80&ts=1525597258&sign=3224c5eb27a5aaa11824acf3f72ab00d
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=37096972&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=2715f9b6cc05c0fd4f5de6340cd90466
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=37096972&player=1&qn=80&quality=80&ts=1525597258&sign=3224c5eb27a5aaa11824acf3f72ab00d
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=37096972&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=2715f9b6cc05c0fd4f5de6340cd90466
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=37096972&player=1&qn=80&quality=80&ts=1525597279&sign=dbf4dddbb57d46bc5cab56f2cb7c94fa
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}

**Comment by Eririf** [comment]
biliplus服务器似乎凉了？

**Comment by hamiguazzz** [comment]
貌似？ 我也不行

**Comment by strygwyr76** [comment]
日常爆炸
