### ISSUE TITLE
win10系统，最近一次更新后，无论是谷歌浏览器还是火狐，油猴显示脚本运行，但是不论是有区域限制还是无区域限制的番都没有了设置按钮，5月4日前确认能用。

### ISSUE THREAD

**Issue by zwwkldw** [ipcjs/bilibili-helper#246]
## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by zwwkldw** [comment]
谷歌和火狐都是最新的，火狐还是最新版新下的，都用不了。是不是要在WIN10代理中设置脚本地址？

**Comment by zwwkldw** [comment]
区域限制的番现在打开就和没装脚本一样，显示视频不见了

**Comment by namezzt** [comment]
服务器抽风状态，但是这次时间有点久呀

**Comment by karajan1999** [comment]
试着将脚本移除重新安装一下就好了。。。。我是这样解决的，不知是否有帮助
