### ISSUE TITLE
能否添加对safari的支持

### ISSUE THREAD

**Issue by ghost** [ipcjs/bilibili-helper#248]
## 描述

safari上脚本不稳定，经常会不能用
![image](https://user-images.githubusercontent.com/28450264/39684439-f0611574-5189-11e8-9bab-6d259449c5ff.png)
![image](https://user-images.githubusercontent.com/28450264/39684452-fc369ed2-5189-11e8-9cb9-d7e92915885c.png)
![image](https://user-images.githubusercontent.com/28450264/39684523-661b0cf2-518a-11e8-8b3c-85cff49748f3.png)

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
不会，脚本只适配Chrome、Firefox的最新版
