### ISSUE TITLE
要凉啊

### ISSUE THREAD

**Issue by 0x00Finch** [ipcjs/bilibili-helper#252]
## 描述

哎呀 这个插件要凉啊  都不维护了呢
- 问题网址：https://www.bilibili.com/bangumi/play/ss23838/?spm_id_from=333.334.bili_bangumi.23

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
我还没凉呐😐

**Comment by Lexington1925** [comment]
我的uc看哔哩哔哩视频已经乱码了，改不回来了

**Comment by ipcjs** [comment]
😥，bilibili乱码还是脚本乱码？
