### ISSUE TITLE
biliplus504了，插件解析地址也失效

### ISSUE THREAD

**Issue by uu551** [ipcjs/bilibili-helper#257]
## 描述

biliplus上不去是服务器问题吗？是的话就算了
- 问题网址：

## 日志

<details>
<summary>log: [解除B站区域限制 v6.8.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep113538
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"---","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":113547,"last_ep_index":"10","last_time":1328}}}
log: setAreaLimitSeason ep113538 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=19893066&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=bc6829c63026deaa3fe0844bddc703dc
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by jouiymo** [comment]
好像是代理服务器bilipuls崩了····是不是凉了啊

**Comment by uu551** [comment]
哦，是biliplus故障了。。


因内部问题，BiliPlus暂停服务
恢复时间未知
2018-05-29
某个人把硬盘分区表干掉了

分区表干掉了还行

**Comment by FlandreDaisuki** [comment]
[更新]

因内部问题，BiliPlus暂停服务
恢复时间未知
2018-05-29
我们服务器的硬盘不转啦

**Comment by ipcjs** [comment]
。。。

**Comment by uu551** [comment]
刚才看可以用了
5.30  2020Hours
