### ISSUE TITLE
现在除了银河英雄传说貌似都看不了了

### ISSUE THREAD

**Issue by huaxiaowu** [ipcjs/bilibili-helper#258]
## 描述
如果从哔哩哔哩番剧出差的个人页面点击视频观看限制番剧，会显示视频不见了

- 问题网址：https://www.bilibili.com/video/av24117456

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by kombgd** [comment]
我连银河英雄传都看不了了

**Comment by jackelchen** [comment]
银英都看不了+1
error:[object Object]
