### ISSUE TITLE
区域限制破解失败

### ISSUE THREAD

**Issue by Ryan6666** [ipcjs/bilibili-helper#260]
log: [解除B站区域限制 v6.8.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep173294
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"枫凌祭夜","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":173294,"last_ep_index":"9","last_time":-1}}}
log: setAreaLimitSeason ep173294 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=33480964&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=9b2568855a7c3d06375f5e7ca439d53c
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by steven7851** [comment]
换 server ?
```
log: [解除B站区域限制 v6.8.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep173294
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"羽葵ouo","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":173298,"last_ep_index":"13","last_time":-1}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=33480964&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=d85d6729877218b39419d82d53daaffb
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-1-112.flv?wsTime=1527871048&platform=pc&wsSecret2=5007d85acee22207d35ebefd25e26382&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-2-112.flv?wsTime=1527871048&platform=pc&wsSecret2=88c996640518606b5fcbef9045c389df&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-3-112.flv?wsTime=1527871048&platform=pc&wsSecret2=7eab8c6f7f4a889deefb05bbec20ccc9&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-4-112.flv?wsTime=1527871048&platform=pc&wsSecret2=8629e37e384a6009aee542d262cd9f8f&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
```

**Comment by Ryan6666** [comment]
提示的方法包括换服务器和授权都试过，看的是“紫罗兰永恒花园”，有大会员，一直提示黑洞突破失败。发自我的iPhone------------------ 原始邮件 ------------------发件人: steven7851  <notifications@github.com>发送时间: 2018年6月1日 15:41收件人: ipcjs/bilibili-helper <bilibili-helper@noreply.github.com>抄送: Ryan6666 <fenglingjiye@gmail.com>, Author <author@noreply.github.com>主题: 回复：[ipcjs/bilibili-helper] 区域限制破解失败 (#260)换 server ?
log: [解除B站区域限制 v6.8.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep173294
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"羽葵ouo","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":173298,"last_ep_index":"13","last_time":-1}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=33480964&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=d85d6729877218b39419d82d53daaffb
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-1-112.flv?wsTime=1527871048&platform=pc&wsSecret2=5007d85acee22207d35ebefd25e26382&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-2-112.flv?wsTime=1527871048&platform=pc&wsSecret2=88c996640518606b5fcbef9045c389df&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-3-112.flv?wsTime=1527871048&platform=pc&wsSecret2=7eab8c6f7f4a889deefb05bbec20ccc9&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
log: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-4-112.flv?wsTime=1527871048&platform=pc&wsSecret2=8629e37e384a6009aee542d262cd9f8f&oi=3400792070&rate=1200&trid=514059ef8ea94945bc2b53c0a1a4ef13
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/ipcjs/bilibili-helper/issues/260#issuecomment-393901834","url":"https://github.com/ipcjs/bilibili-helper/issues/260#issuecomment-393901834","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ipcjs/bilibili-helper","title":"ipcjs/bilibili-helper","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ipcjs/bilibili-helper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@steven7851 in #260: 换 server ?\r\n```\r\nlog: [解除B站区域限制 v6.8.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep173294\r\ndebug: XMLHttpRequest的描述符: {\"writable\":true,\"enumerable\":false,\"configurable\":true}\r\nlog: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true\r\nlog: /x/web-interface/nav {\"uname\":\"羽葵ouo\",\"isLogin\":true,\"level\":5,\"vipType\":2,\"vipStatus\":1}\r\nlog: /season/user/status: {\"code\":0,\"message\":\"success\",\"result\":{\"area_limit\":1,\"ban_area_show\":1,\"follow\":1,\"paster\":{\"aid\":0,\"allow_jump\":0,\"cid\":0,\"duration\":0,\"type\":0,\"url\":\"\"},\"pay\":0,\"pay_pack_paid\":0,\"sponsor\":0,\"watch_progress\":{\"last_ep_id\":173298,\"last_ep_index\":\"13\",\"last_time\":-1}}}\r\nlog: player msg: 从代理服务器拉取视频地址中...\r\ndebug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=33480964\u0026appkey=84956560bc028eb7\u0026otype=json\u0026type=\u0026quality=116\u0026module=bangumi\u0026season_type=1\u0026qn=116\u0026sign=d85d6729877218b39419d82d53daaffb\r\nlog: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-1-112.flv?wsTime=1527871048\u0026platform=pc\u0026wsSecret2=5007d85acee22207d35ebefd25e26382\u0026oi=3400792070\u0026rate=1200\u0026trid=514059ef8ea94945bc2b53c0a1a4ef13\r\nlog: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-2-112.flv?wsTime=1527871048\u0026platform=pc\u0026wsSecret2=88c996640518606b5fcbef9045c389df\u0026oi=3400792070\u0026rate=1200\u0026trid=514059ef8ea94945bc2b53c0a1a4ef13\r\nlog: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-3-112.flv?wsTime=1527871048\u0026platform=pc\u0026wsSecret2=7eab8c6f7f4a889deefb05bbec20ccc9\u0026oi=3400792070\u0026rate=1200\u0026trid=514059ef8ea94945bc2b53c0a1a4ef13\r\nlog: flv prefer use: https://ws.acgvideo.com/4/ba/33480964-4-112.flv?wsTime=1527871048\u0026platform=pc\u0026wsSecret2=8629e37e384a6009aee542d262cd9f8f\u0026oi=3400792070\u0026rate=1200\u0026trid=514059ef8ea94945bc2b53c0a1a4ef13\r\ndebug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/ipcjs/bilibili-helper/issues/260#issuecomment-393901834"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [ipcjs/bilibili-helper] 区域限制破解失败 (#260)",
"sections": [
{
"text": "",
"activityTitle": "**steven7851**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@steven7851",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ipcjs/bilibili-helper\",\n\"issueId\": 260,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ipcjs/bilibili-helper\",\n\"issueId\": 260\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ipcjs/bilibili-helper/issues/260#issuecomment-393901834"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 341253632\n}"
}
],
"themeColor": "26292E"
}

**Comment by steven7851** [comment]
参数设置 -> 帐号授权
