### ISSUE TITLE
无法解析港澳台番剧？？

### ISSUE THREAD

**Issue by zerowl** [ipcjs/bilibili-helper#261]
# 描述
从6月开始就没办法解析港澳台番剧，例如这个https://www.bilibili.com/video/av24281876/，它进入页面后提示的是error:[object Object]，不知道和你们硬盘坏了有没有关系，下面日志是进入其他番剧复制出来的。

- 问题网址：
https://www.bilibili.com/video/av24281876/

## 日志

llog: [解除B站区域限制 v6.8.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep200328/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"GIN先生","isLogin":true,"level":5,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":200326,"last_ep_index":"7","last_time":179}}}
log: setAreaLimitSeason ep200328 false
log: {"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"accept_format":"hdflv2,flv,flv720,flv480,flv360","accept_quality":[112,80,64,32,15],"bp":0,"code":0,"durl":[{"backup_url":["http://cn-jsnt-dx-v-05.acgvideo.com/vg4/upgcxcode/28/04/40730428/40730428-1-80.flv?expires=1528012200&platform=pc&ssig=Ubz8iCuO39JrDEEFfWWWpA&oi=245177023&nfa=BpfiWF+i4mNW8KzjZFHzBQ==&dynamic=1&hfa=2032181484&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=d6abd7a4334e4e939d1f94711cc5cf69","http://upos-hz-mirrorkodo.acgvideo.com/upgcxcode/28/04/40730428/40730428-1-80.flv?e=ig8euxZM2rNcNbhjhz4VhoMahbujhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IB5QK==&deadline=1528012243&dynamic=1&gen=playurl&oi=245177023&os=kodo&platform=pc&rate=363800&trid=d6abd7a4334e4e939d1f94711cc5cf69&uipk=5&uipv=5&um_deadline=1528012243&um_sign=1f7385afcda255aaf48a36328af62b72&upsig=5437c0823d96a515e8acae05aff26990"],"length":195107,"order":1,"size":41863237,"url":"http://cn-jxjj-dx-v-05.acgvideo.com/vg4/upgcxcode/28/04/40730428/40730428-1-80.flv?expires=1528012200&platform=pc&ssig=Ubz8iCuO39JrDEEFfWWWpA&oi=245177023&nfa=BpfiWF+i4mNW8KzjZFHzBQ==&dynamic=1&hfa=2032181484&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=&trid=d6abd7a4334e4e939d1f94711cc5cf69"}],"format":"flv","from":"local","has_paid":false,"quality":80,"result":"suee","seek_param":"start","seek_type":"offset","status":2,"timelength":195107,"vip_status":0,"vip_type":1}
log: setAreaLimitSeason ep200328 false
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

```
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->
![qq 20180603135420](https://user-images.githubusercontent.com/6571492/40883680-a95508f4-6735-11e8-9ccb-b51e48195a41.png)

## 其他

1. 浏览器版本：Google Chrome 已是最新版本
版本 67.0.3396.62（正式版本） （64 位）
2. 国家/地区：广东顺德

**Comment by hayerer** [comment]
我也面对同样问题 ，也是error [object object]这样的 啊叻 视频不见了

难道b站封了？

**Comment by MoreLightDo** [comment]
我也是error [object object]

**Comment by huaxiaowu** [comment]
我也是，从哔哩哔哩番剧出差的投稿页面就不能看，番剧列表上的限制番剧就能看

**Comment by Brainor** [comment]
我也是这样...

<details>
    <summary>所有港澳台区域限制的番剧会显示下图</summary>

![error](https://user-images.githubusercontent.com/5477995/41204650-cce11b5c-6d19-11e8-9ff5-7dd6313ba7d0.png)

</details>


<details>
    <summary>Console是这样的.</summary>

![error2](https://user-images.githubusercontent.com/5477995/41204663-febee1c2-6d19-11e8-8a7e-bab7a69fbdf8.png)

</details>

是biliplus接口的问题, 还是我的特殊情况呢?

**Comment by ghost** [comment]
Biliplus最近炸了，难道跟这个有关？

**Comment by Brainor** [comment]
@zxmk-II 应该不是
因为试了一下之后发现, 同一个港澳台限定番剧的某一集是有`https://www.bilibili.com/bangumi/play/ep*/` 的网址和`https://www.bilibili.com/video/av*/` 两种.
其中前者可以正常观看, 但是后者就无法自动跳转成前者, 因此无法播放, which 之前是可以自动跳转的.
也就是说, 现在`av*`链接无法自动跳转到番剧`bangumi`链接, 大家也有这种情况么?

**Comment by ipcjs** [comment]
服务器只恢复了playurl接口，av页面要用到的view接口并没有恢复，所以是用不了的

**Comment by Brainor** [comment]
原来是这样. 多谢, 所以大家如果在[连载动画](https://www.bilibili.com/v/anime/serial/)页面上的特供番剧无法观看的话, 就直接搜索该番剧名称, 从`https://www.bilibili.com/bangumi/media/md*/` 页面进去就可以看了.

**Comment by ipcjs** [comment]
直接点击 追番 就行了，动态页面的链接直接可以用

**Comment by Acemeal** [comment]
把flash播放换成htlm5播放  突然就好了。

**Comment by huaxiaowu** [comment]
我一直就是html5


发送自 Windows 10 版邮件应用

发件人: Acemeal
发送时间: 2018年6月11日 14:00
主题: Re: [ipcjs/bilibili-helper] 无法解析港澳台番剧？？ (#261)

把flash播放换成htlm5播放 突然就好了。
