### ISSUE TITLE
用的是mac的Safari浏览器……试过很多次都不行 以前用Windows都很好用的

### ISSUE THREAD

**Issue by LolesszzZZZ** [ipcjs/bilibili-helper#265]
log: [解除B站区域限制 v6.8.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md9192/?spm_id_from=666.10.bangumi_media.1
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"葭花千顷水微茫","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":216075,"last_ep_index":"23","last_time":1439}}}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15

**Comment by ipcjs** [comment]
换chrome

**Comment by LolesszzZZZ** [comment]
换用Chrome之后我甚至连油猴都装不了……每次下载的时候都会跳到chrome.google.com/webstore然后被墙

**Comment by ipcjs** [comment]
脚本说明页面有扩展的网盘链接

**Comment by LolesszzZZZ** [comment]
里面好像有三个 请问是哪一个呢 最新的那个嘛 还是三个都要

**Comment by LolesszzZZZ** [comment]
然后我的chrome文件夹里也没有chrome://extensions/ 😢
