### ISSUE TITLE
哔哩哔哩最近更新了新版本的页面希望针对新版本做出修改支持

### ISSUE THREAD

**Issue by marswow** [ipcjs/bilibili-helper#266]
新版本把flash完全去掉了
也就是说以后用新版本的话啊就不需要神庙flash 鸟

**Comment by ipcjs** [comment]
不喜欢新版的UI，等B站把旧版全关掉再说吧

**Comment by ipcjs** [comment]
尝试支持了下，机制改了，不一定能行`(-_-#)`
59c0bdc02997096f6ece18fd3cc8834d636fa15b
