### ISSUE TITLE
能不能设置不要每次询问打开h5播放器  用extensionStorage啊

### ISSUE THREAD

**Issue by Jemair** [ipcjs/bilibili-helper#271]
## 描述

如题 每次打开番剧页面都会alert  造成了很大的困扰

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
脚本不在h5播放器下用不了
还是说你当前已经是h5播放器了，但它还是不断在弹提示？

**Comment by Jemair** [comment]
嗯  是的  原来不会提示吗  是不是因为用的新版播放器

**Comment by ipcjs** [comment]
那就换成旧版试试呗

**Comment by Jemair** [comment]
好像现在没有了

**Comment by Jemair** [comment]
先关了吧  我看看具体是什么情况下会出现
之前我以为你没有做判断

**Comment by Jemair** [comment]
试了下
好像是因为我经常大刷.→→

**Comment by ipcjs** [comment]
刷新还会影响cookie？
