### ISSUE TITLE
请问是不是不支持edge浏览器的呢

### ISSUE THREAD

**Issue by ryanxia0226** [ipcjs/bilibili-helper#272]
## 描述

请问是不是不支持edge浏览器，土星图标都不会出现，也没有出现授权的页面，后期会不会支持edge呢
- 问题网址：https://www.bilibili.com/bangumi/play/ep234661

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Microsoft Edge 42.17134.1.0
2. 国家/地区：中国

**Comment by ipcjs** [comment]
是的
https://github.com/ipcjs/bilibili-helper/issues/114

**Comment by ryanxia0226** [comment]
好的。谢谢回复，如果后期有计划支持就好了。

**Comment by ipcjs** [comment]
没计划😅

好像有人说过，跟adblock有关，你可以试下：https://github.com/ipcjs/bilibili-helper/issues/227

**Comment by ryanxia0226** [comment]
也试了  不过谢谢了

**Comment by ipcjs** [comment]
那就换Chrome或Firefox吧

**Comment by ryanxia0226** [comment]
嗯 只能换回chrome了
