### ISSUE TITLE
港澳台番剧全灭，其他非港澳台版权番和正版番都能正常观看

### ISSUE THREAD

**Issue by himesamarose** [ipcjs/bilibili-helper#275]
## 描述
港澳台番剧一个都看不了了，无法连接服务器

加载视频地址...[完成]
播放器初始化...[完成]
[解除B站区域限制] 从代理服务器拉取视频地址中...
加载视频内容...[失败]
无法连接服务器 ([NetworkError] Exception: Failed to fetch)
[解除B站区域限制] 从代理服务器拉取视频地址中...
加载视频内容...[失败]
无法连接服务器或服务器返回异常 ([NetworkError] Exception：3104 Failed to fetch)

- 问题网址：

https://www.bilibili.com/bangumi/play/ep234664

## 日志

log: [解除B站区域限制 v6.8.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep234664
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"月之式-Rose","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":234664,"last_ep_index":"7","last_time":0}}}
log: {"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1535925000&platform=ios&ssig=4i2aJx5TrLrLQ0Q6P4peEw&oi=3078818617&nfa=7VMUDqBQpI8VGBbhQ1faUQ==&dynamic=1&hfa=2042585796&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=5fb7aa16f64d44baa01ef7d0dcd1154c&nfc=1"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=54068195&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=15b9cc604a43d12266a333c602d918c2
log: {"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1535925000&platform=ios&ssig=wZTeX1tDGjf5ThlBDgjApg&oi=3078818617&nfa=7VMUDqBQpI8VGBbhQ1faUQ==&dynamic=1&hfa=2042585807&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=70ceebfb548447c6859c21637cbb0181&nfc=1"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=54068195&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=09c5db16232ac9642cb16ebed736f887
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
```
 


## 其他

1. 浏览器版本：Chrome
2. 国家/地区：美国/纽约

**Comment by initialnull** [comment]
遇到了同样的问题

**Comment by himesamarose** [comment]
也有可能是日常抽风，有时能用有时不能用的，目前可以看了
