### ISSUE TITLE
港台速度被限制在200K其他番剧正常

### ISSUE THREAD

**Issue by yxok200** [ipcjs/bilibili-helper#276]
log: [解除B站区域限制 v6.8.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep234664
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"秒天秒地日神仙のyxok","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":234664,"last_ep_index":"7","last_time":9}}}
log: setAreaLimitSeason ep234664 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=54068195&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=7638ed3217ac4484c7b3b540ca7b753a
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
log: balh_flv_prefer_ws  =>  Y
log: balh_flv_prefer_ws  =>  

1. 浏览器版本：360极速  63.0.3239.132
2. 国家/地区：大陆上港台
问题：速度被限制在200K其他番剧正常

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/issues/268
