### ISSUE TITLE
使用脚本以后看港澳台非常的卡，点了快进以后显示无法连接到服务器

### ISSUE THREAD

**Issue by SHENfff** [ipcjs/bilibili-helper#277]
## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/issues/276

https://github.com/ipcjs/bilibili-helper/issues/268
