### ISSUE TITLE
海外用户看非番剧视频被限速

### ISSUE THREAD

**Issue by lzy0702** [ipcjs/bilibili-helper#278]
## 描述

- 问题网址：任意非番剧av
例如
https://www.bilibili.com/video/av22881237
https://www.bilibili.com/video/av31059596

试着选过ws替换列表里所有服务器，都被限速

## 日志

<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v6.8.6 (Violentmonkey)] run on: https://www.bilibili.com/bangumi/media/md2580/?spm_id_from=666.10.bangumi_detail.1
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"贝雅特丽齐的但丁","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":65561,"last_ep_index":"7","last_time":16}}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36 Maxthon/5.2.4.2000
</details>

##B站新版播放器的日志
<details>
<summary>B站新版播放器日志</summary>
[Info] > 18 : 22 : 45: 487  User Initialized 
[Info] > 18 : 22 : 45: 490  Toast Initialized 
[Info] > 18 : 22 : 45: 490  Tracker Initialized 
[Info] > 18 : 22 : 45: 491  LoadingPanel Initialized 
[Info] > 18 : 22 : 45: 558  Controller Initialized 
[Info] > 18 : 22 : 45: 566  Load video buffer 
[Info] > 18 : 22 : 45: 566  Load video playurl 
[Info] > 18 : 22 : 45: 567  Load video playurl finished   2651 ms
[Info] > 18 : 22 : 45: 567  Load video data 
[Info] > 18 : 22 : 45: 567  Load video data finished   2650 ms
[Info] > 18 : 22 : 45: 569  ModeSelection Constructed 
[Info] > 18 : 22 : 45: 573  SendModule Initialized 
[Info] > 18 : 22 : 45: 585  Load video config 
[Info] > 18 : 22 : 45: 608  Block Initialized 
[Info] > 18 : 22 : 46: 140  VideoTop Initialized 
[Info] > 18 : 22 : 46: 144  Load video danmaku 
[Info] > 18 : 22 : 46: 172  Danmaku Initialized 
[Info] > 18 : 22 : 46: 246  
<ip>71.224.51.236</ip>
<zoneid>29360128</zoneid>
<zoneip></zoneip>
<country>美国</country>
<login>true</login>
<time>1536099766</time>
<name>贝雅特丽齐的但丁</name>
<user>282934</user>
<user_hash>cd668bf2</user_hash>
<money>765.50</money>
<face>//static.hdslb.com/images/member/noface.gif</face>
<isadmin>false</isadmin>
<permission>10000,1001</permission>
<level></level>
<level_info>{"current_level":5,"current_min":10800,"current_exp":14513,"next_exp":28800}</level_info>
<vip>{"vipType":2,"vipDueDate":1559836800000,"dueRemark":"","accessStatus":0,"vipStatus":1,"vipStatusWarn":""}</vip>
<official_verify>{"type":-1,"desc":""}</official_verify>
<block_time>0</block_time>
<lastplaytime>0</lastplaytime>
<lastcid>38017856</lastcid>
<aid>22881237</aid>
<typeid>17</typeid>
<vtype>vupload</vtype>
<oriurl></oriurl>
<suggest_comment>false</suggest_comment>
<server>chat.bilibili.com</server>
<maxlimit>6000</maxlimit>
<click>249330</click>
<fw_click>715</fw_click>
<chatid>38017856</chatid>
<pid>1</pid>
<duration>56:10</duration>
<arctype>Original</arctype>
<allow_bp>false</allow_bp>
<bottom>0</bottom>
<shot>false</shot>
<sinapi>1</sinapi>
<acceptguest>false</acceptguest>
<acceptaccel>true</acceptaccel>
<cache>true</cache>
<broadcast_tcp>broadcast.chat.bilibili.com:4080</broadcast_tcp>
<broadcast_ws>broadcast.chat.bilibili.com:4090</broadcast_ws>
<broadcast_wss>broadcast.chat.bilibili.com:4095</broadcast_wss>
<default_dm>0</default_dm>
<dm_host>0://comment.bilibili.com,1://comment.bilibili.com/rc</dm_host>
<role>0</role>
<has_next>0</has_next>
<online_count>6</online_count>
<dm_mask></dm_mask>
<enable_gray_dash_playback>500</enable_gray_dash_playback>
<new_broadcast>1</new_broadcast>
<realtime_dm>1</realtime_dm>
 
[Info] > 18 : 22 : 46: 246  Load video config finished   661 ms
[Info] > 18 : 22 : 46: 251  Auxiliary Initialized 
[Info] > 18 : 22 : 47: 184  Load video danmaku finished time:753,analyzeTime:33,addTime:65,num:6000   1040 ms
[Info] > 18 : 23 : 35: 861  Load video buffer finished   50295 ms

</details>

## 其他

1. 浏览器版本：Maxthon 5.2.4.2000 和 Chrome 68.0.3440.106
2. 国家/地区：美国东部，ISP：Comcast

**Comment by ipcjs** [comment]
试试“在av页面启用脚本”选项
新版播放器，没适配过，用旧版

**Comment by acatcat86** [comment]
请教一下楼上 "在av页面启用脚本"在哪里设置？我刚刚学着用油猴，在这个脚本下没看到设置的地方。。。本人chrome浏览器

**Comment by lzy0702** [comment]
楼上找个番剧的页面就能看到设置的按钮了

**Comment by lzy0702** [comment]
话说新旧版HTML5播放器除了外观不一样还有什么改变么？

**Comment by acatcat86** [comment]
原来如此 感谢ls
即使这样我的速度也没快多少-,-

主要看av的综艺啊之类的 坐标美东NJ，Verizon Fios，普通无线能上100mb/s, 有大会员，但是基本上只能看480p不卡顿。。。

**Comment by lzy0702** [comment]
乎看“稍后观看”列表里的视频无法触发脚本的匹配，求更新

**Comment by ipcjs** [comment]
@acatcat86 对了，用biliplus也有这情况吗？

**Comment by acatcat86** [comment]
> @acatcat86 对了，用biliplus也有这情况吗？

后来我按照这样设置之后倒是至少480p很流畅了，没法达到一直1080p 流畅，但是480能保证，720大部分也ok。。感觉是主要强制重定向之后变得流畅起来

![2018-09-22_18-56-01](https://user-images.githubusercontent.com/17970685/45922407-57604200-be99-11e8-9a0a-b2e488a169de.jpg)
