### ISSUE TITLE
视频无法快进

### ISSUE THREAD

**Issue by NinelieAimer** [ipcjs/bilibili-helper#279]
## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by edison0354** [comment]
B站评论里都有解决方案啦
右下角土星图标，设置进去把UPOS服务器替换掉就可以了
