### ISSUE TITLE
B站av页面的头部和评论区会消失

### ISSUE THREAD

**Issue by bob9692** [ipcjs/bilibili-helper#281]
## 描述
B站av页面的头部和评论区会消失，只剩下播放器和页脚，切换到新版播放器可以暂时解决这个问题

## 日志
<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v6.8.6 (Violentmonkey)] run on: https://www.bilibili.com/bangumi/play/ep231949
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"宫泽三叶","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":231947,"last_ep_index":"9","last_time":242}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=55825579&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=4b0edeca03ddc9daf7536af64b94d712
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
log: balh_flv_prefer_ws  =>  Y 

## 其他
1. 浏览器版本：Chrome63
2. 国家/地区：上海电信

**Comment by ipcjs** [comment]
哪个av？

**Comment by steven7851** [comment]
不要勾选`在AV页面启用`就好

**Comment by ipcjs** [comment]
**，debug了半天不知道啥原因，把设置按钮屏蔽就没问题了(;¬_¬)
https://github.com/ipcjs/bilibili-helper/commit/fe82d6c4ba0e907c7881a2819cb8dad1d58cff1a
