### ISSUE TITLE
HK failed to load user script in some bangumis

### ISSUE THREAD

**Issue by legendtang** [ipcjs/bilibili-helper#283]
## 描述

- 问题网址：https://www.bilibili.com/bangumi/play/ss25739

## 日志

<details>
<summary>ERROR: Execution of script '解除B站区域限制' failed! unit_init must run at loading, current is interactive
userscript.html:2:260

scriptSource

https://www.bilibili.com/bangumi/play/ep250460:2:496

eval code
eval@[native code]
https://www.bilibili.com/bangumi/play/ep250460:2:496
b@https://www.bilibili.com/bangumi/play/ep250460:1:411
E_u@https://www.bilibili.com/bangumi/play/ep250460:3:157

ka
create
e
run

forEach@[native code]
https://www.bilibili.com/bangumi/play/ep250460:2:496
b@https://www.bilibili.com/bangumi/play/ep250460:1:411

TM_back
anonymous
https://www.bilibili.com/bangumi/play/ep250460:2:496
exec_fn@https://www.bilibili.com/bangumi/play/ep250460:1:107
https://www.bilibili.com/bangumi/play/ep250460:11:233
R@https://www.bilibili.com/bangumi/play/ep250460:10:10
dispatchEvent@[native code]
send@safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/content.js:8:83
next@safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/content.js:13:186
safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/content.js:28:184
safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/content.js:24:411
run@safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/rea/common.js:4:76
safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/rea/common.js:7:160
safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/rea/common.js:4:451
forEach@[native code]
run@safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/rea/common.js:4:437
safari-extension://net.tampermonkey.safari-G3XV72R5TC/59f4d9f/rea/common.js:4:233

</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

<img width="645" alt="image" src="https://user-images.githubusercontent.com/1352729/46490255-19b8cd00-c83a-11e8-9b0d-bbeb2da2943e.png">

## 其他

1. 浏览器版本：Safari 12.0 Tampermonkey 最新
2. 国家/地区：HK

很多番剧无此问题，有的也有这个问题

**Comment by ipcjs** [comment]
换chrome或Firefox
