### ISSUE TITLE
underscore 支持 https 了

### ISSUE THREAD

**Issue by ivysrono** [ipcjs/bilibili-helper#284]
https://github.com/ipcjs/bilibili-helper/blob/user.js/underscore_toggle_sidebar.user.js#L7
加个https适配的事，我就不提PR了。

**Comment by ipcjs** [comment]
ok https://github.com/ipcjs/bilibili-helper/commit/1a0f1b74e566829c80984a8a9c6460195c349487

**Comment by ivysrono** [comment]
https://rawgit.com 我连不上，去测了下好多地方都连不上：
http://tool.chinaz.com/speedtest.aspx?host=rawgit.com
换个cdn吧，比方说 https://www.bootcdn.cn/snap.js/

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/commit/75c2f6080a47d39fc0af4db7aff3c163ec3646dd

**Comment by ivysrono** [comment]
原谅我啊，最后啰嗦一次。
我上面写  bootcdn 是随手搜出来的，没注意他提供的居然不是自建而是 cloudflare.com 的。
CloudFlare在国内被干扰很严重的，用站长工具测速以下就知道，就算能连上延迟也很高。
而且这个地址 https://cdnjs.cloudflare.com/ajax/libs/snap.js/1.9.3/snap.min.js 说起来是 1.9.3，实际上打开看下就还是 1.9.2，这样我们还不如用官方原版了：
https://github.com/jakiestfu/Snap.js/raw/develop/snap.min.js
反正脚本都放在 Github 了，依赖库也用 Github 上的呗。
反复打扰，非常抱歉。

**Comment by ipcjs** [comment]
我记得直接用GitHub上的链接，MIME不对，识别不了

**Comment by ivysrono** [comment]
我自己的经验是没问题：
https://github.com/ivysrono/Scripts/blob/master/Travis-CI-Linkify-Plus-Plus-Style.user.js#L9

**Comment by ipcjs** [comment]
那可能是我记错了
https://github.com/ipcjs/bilibili-helper/commit/0d2352ff5d930e2b55e935fdaedfed3b6845f358

**Comment by ivysrono** [comment]
我都觉得自己罗嗦了……
最好设置成 https://github.com/jakiestfu/Snap.js/raw/develop/snap.min.js 而非跳转过后的 https://raw.githubusercontent.com/jakiestfu/Snap.js/develop/snap.min.js
前者肯定没墙，后者很可能被解析为亚马逊云被干扰被阻断……

**Comment by ipcjs** [comment]
前者不是每次都会跳转到后者吗？
后者被墙的话，不还是被墙

（所以说，PR是个好东西

**Comment by ivysrono** [comment]
不是的，如果作为网址直接访问，前者会跳转到后者。
但如果是下载或者作为资源引用，是不跳转的，后者被干扰，前者基本没有。
相信我真的有关系，不然我不会在自己的所有项目里的引用地址都用前者的样式——被坑多了啊。

**Comment by ivysrono** [comment]
给个证明：
https://github.com/ivysrono/Scripts
随便点一个链接，暴力猴会跳出安装界面如下：
![default](https://user-images.githubusercontent.com/2649544/46581998-5b808800-ca73-11e8-9d2f-5fd37963b90d.png)

真的不跳转。

**Comment by ipcjs** [comment]
你说的这个场景，加载js是在扩展管理器的background.html里面，是有跳转的（302的那个请求）
![screenclip 13](https://user-images.githubusercontent.com/4396864/46582061-16a92100-ca74-11e8-93aa-4ee24e3a20d2.png)

**Comment by ivysrono** [comment]
难道是 Firefox 和 chrome 表现不一样？
Firefox完全可以在 raw.githubusercontent.com 挂掉的情况下获取 GitHub 的对应资源。
我测了下，把 raw.githubusercontent.com 丢进 uBlock 禁掉，还是可以正常获取对应的 github.com 的 js

**Comment by ipcjs** [comment]
一样的，也有个302的请求
在`about:debugging#addons`，勾选“启用附加组件调试”，然后点暴力猴的“调试”，可以看到
![screenclip 14](https://user-images.githubusercontent.com/4396864/46582458-c2a13b00-ca79-11e8-978f-155ef1cd9b45.png)

**Comment by ivysrono** [comment]
原来是我弄错了( ╯□╰ )
下次再能重现一联通一被墙的话再说把ヾ(•ω•`)o
