### ISSUE TITLE
腳本無法正常運行,右下無地球圖標

### ISSUE THREAD

**Issue by jazz00040** [ipcjs/bilibili-helper#285]
## 描述

腳本無法正常運行,右下無64位元瀏覽器,安装后脚本无法使用，不能看到设置图标
右上角的功能列,油猴顯示腳本運行中
右下角沒有地球圖標(设置按钮看不到)地球圖標
- 问题网址：
https://www.bilibili.com/video/av873027/?spm_id_from=333.788.videocard.0

擷取圖片 https://drive.google.com/file/d/151Tf0ZfsoSNg6Gz4GYlNMo_b9s18lf_o/view?usp=sharing

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Google Chrome 目前是最新版本
版本 69.0.3497.100 (正式版本) (64 位元)
2. 国家/地区：台灣

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/issues/278

另外，av页面现在是没土星图标的，上次有个这样的buh：https://github.com/ipcjs/bilibili-helper/issues/281
之后就把av页面的图形图标删了😅

**Comment by ipcjs** [comment]
好像改了设置也没用😥
等我有时间看下吧

**Comment by jazz00040** [comment]
感谢,原来是图标删了,难怪都找不到土星图标...(原本以为是64位元浏览器匹配的问题)
不能看的情况大概发生一~两个月了,自从bilibili改新版的拨放器以后就变得怪怪的
加油,好东西不能沉

**Comment by ipcjs** [comment]
那换回旧版播放器试试？

**Comment by jazz00040** [comment]
切換舊版畫面 https://drive.google.com/file/d/1F_h1Wl1sbCG7AKswO6omCKEbTr19m8uk/view?usp=sharing

**Comment by jazz00040** [comment]
後台有個x
不知道是不是這原因
https://drive.google.com/open?id=1PT2y6g6qkPx1lx5eZaKMAA_H3L5fxD95

**Comment by ipcjs** [comment]
这个视频，内地也看不了呀，应该是被up主删了吧

**Comment by ipcjs** [comment]
8687e668c16cc665edfd8eaf9d81036b99ce3565

@esterTion 
不知为何，这个视频的playurl只返回这些字段，B站播放器播不了
我在脚本里手动加上`"from": "local", "result": "suee",`之后就可以播了
```json
{
    "code": 0,
    "flvjsType": "flv",
    "format": "gdrive_mp4",
    "accept_quality": [
        10
    ],
    "durl": [
        {
            "order": 1,
            "size": 44393412,
            "length": 1385859,
            "url": "https://us.biliplus-vid.win/file/f834bbb5953acb7eb9922035fd06626b/1539024505/3698331761/0BwUwphrGneOxUzY5Mk8wMml4bDQ/videoplayback.mp4"
        }
    ]
}
```

**Comment by esterTion** [comment]
怎么触发到输出转存了，这视频删了吗

**Comment by esterTion** [comment]
又是傻逼逼站逻辑
划分到bangumi下，interface不可以用，然后av号没跳转
mdzz

```JSON
{
  "code": 10004,
  "message": "稿件已经被删除",
  "ttl": 1,
  "data": {
    "from": "",
    "result": "error",
    "message": "Video is hidden.",
    "quality": 0,
    "format": "",
    "timelength": 0,
    "accept_format": "",
    "accept_description": null,
    "accept_quality": null,
    "video_codecid": 0,
    "seek_param": "",
    "seek_type": ""
  }
}
```

**Comment by ipcjs** [comment]
返回的居然是biliplus的地址 `(ﾟДﾟ≡ﾟдﾟ)!?`
我直接把它丢到播放器播去了(-_-#)

这种情况我们要怎么处理呀🤔

**Comment by esterTion** [comment]
要么你就直接播放，要么就跳转一下番剧页
反正服务器也无所谓，用来代理视频的机子不限流量

**Comment by ipcjs** [comment]
从av页，重定向到bangumi页还挺麻烦的(-_-#)
你这个“输出转存”功能，输出的是缓存吗？视频内容是怎么拿到的？

**Comment by esterTion** [comment]
转存服务了解一下
https://bg.biliplus-vid.win/
![qq 20181009000124](https://user-images.githubusercontent.com/7265411/46620141-7bd54300-cb56-11e8-8b67-69658892578d.png)

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/commit/c7acde9e2a7b216864aefc4465d1768cefc7dc64
直接播转存的视频+提示说明情况
就这样吧👌

**Comment by esterTion** [comment]
哦对了，还有个事
你没复制Popup的css
[acfun_html5.js:684](https://github.com/esterTion/AcFun-HTML5-Player/blob/master/src/acfun_html5.js#L684)

**Comment by ipcjs** [comment]
复制了的，全在util_ui_pop里面，缩进成一行了

**Comment by esterTion** [comment]
emmmmm
我瞎了
