### ISSUE TITLE
突破黑洞失败……无限重新登陆

### ISSUE THREAD

**Issue by CC79** [ipcjs/bilibili-helper#286]
## 描述
无限重登……
黑洞突破失败，重启好几次也没用。。

- 问题网址：https://www.bilibili.com/bangumi/play/ss25689/?spm_id_from=333.334.bili_bangumi.5

## 日志

<details>
<summary>Verbose 日志</summary>

log: [解除B站区域限制 v6.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25689/?spm_id_from=333.334.bili_bangumi.5
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win upos_server: cos flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"死透了的错刀零","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586620800000,"status":1,"type":2},"watch_progress":{"last_ep_id":251255,"last_ep_index":"1","last_time":1389}}}
log: setAreaLimitSeason ss25689 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=57985532&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=a0f2076f2f5f326d3d119780f0bfc197
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=57985532&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=a58c143394e2364248bd6bfb8e7af977
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
error: >>area limit
```
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by Eastre** [comment]
我也是。今天试的

**Comment by wingfall** [comment]
+1，我也是，这是日志，无限授权，无限突破黑洞失败

log: [解除B站区域限制 v6.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25689/?spm_id_from=333.334.bili_bangumi.4
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://biliplus.ipcjs.win upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"风之年华233","isLogin":true,"level":3,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1553184000000,"status":1,"type":2},"watch_progress":{"last_ep_id":251256,"last_ep_index":"2","last_time":322}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=3afa2b05219cf9bdc4ff2987ca051b53
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=b1e75c8e67f9a93056da10e77ed746cb
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=58843042&player=1&qn=16&quality=16&ts=1539316099&sign=c68647c74540ad06832848dedfa5d52f
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=b1e75c8e67f9a93056da10e77ed746cb
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=58843042&player=1&qn=16&quality=16&ts=1539316107&sign=ee7d2cca3ebcf7e38a8b751e5a9332a9
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=b1e75c8e67f9a93056da10e77ed746cb
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.6756.400 QQBrowser/10.3.2473.400

**Comment by wingfall** [comment]
我也是，无限授权，无限突破黑洞失败，以下脚本日志

log: [解除B站区域限制 v6.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25689/?spm_id_from=333.334.bili_bangumi.4
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://biliplus.ipcjs.win upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"风之年华233","isLogin":true,"level":3,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1553184000000,"status":1,"type":2},"watch_progress":{"last_ep_id":251256,"last_ep_index":"2","last_time":322}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=3afa2b05219cf9bdc4ff2987ca051b53
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=b1e75c8e67f9a93056da10e77ed746cb
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=58843042&player=1&qn=16&quality=16&ts=1539316099&sign=c68647c74540ad06832848dedfa5d52f
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=b1e75c8e67f9a93056da10e77ed746cb
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=58843042&player=1&qn=16&quality=16&ts=1539316107&sign=ee7d2cca3ebcf7e38a8b751e5a9332a9
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=58843042&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=b1e75c8e67f9a93056da10e77ed746cb
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.6756.400 QQBrowser/10.3.2473.400

**Comment by aceliuchanghong** [comment]
so am i!!!today!

**Comment by geilykotz233** [comment]
我也是，我要看佐贺偶像啊

**Comment by wingfall** [comment]
另外我以为是网络或者是COOKIE问题，结果完全不是这两个问题，只能是脚本的问题

**Comment by aceliuchanghong** [comment]
> 我也是，我要看佐贺偶像啊

好伤心!刚打开就不行!结果去进击的巨人也不行了

**Comment by autapomorphy** [comment]
同，似乎只有港澳台番剧有这个问题，别的番没报错

**Comment by ipcjs** [comment]
@geilykotz233 看佐贺去A站呀

**Comment by wingfall** [comment]
佐贺只能去那边了，但是其他站会员的，B站有港澳台那就蛋疼了

**Comment by bleach040** [comment]
log: [解除B站区域限制 v6.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep251168
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://biliplus.ipcjs.win upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"丝袜太郎","isLogin":true,"level":6,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1601568000000,"status":1,"type":2},"watch_progress":{"last_ep_id":251167,"last_ep_index":"1","last_time":1444}}}
log: {"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1539324900&platform=ios&ssig=OqVL9vKIspZo6bz-8VyhZA&oi=3078818617&nfa=7VMUDqBQpI8VGBbhQ1faUQ==&dynamic=1&hfa=2045968420&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=bc3e9e56589b4033a03d656ec6b7ecfc&nfc=1"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.win/BPplayurl.php?cid=57365641&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=cf76e8534403baa9a12387bbe6e6e257
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=57365641&player=1&qn=112&quality=112&ts=1539317983&sign=9eea6a153baa2ba87b570b4b456c8163
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3559.6 Safari/537.36
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
我也是，看来不止我一个，我还重新装了脚本和油猴

**Comment by ipcjs** [comment]
服务器日常崩溃，没啥好大惊小怪的，等biliplus修复呗

**Comment by autapomorphy** [comment]
> @geilykotz233 看佐贺去A站呀

A站也有地域限制啊……

**Comment by brendan0524** [comment]
同样的问题

**Comment by wingfall** [comment]
+1，本来之前看的好好的，因为中途网络原因刷新下，就登不上去了，以为是网络问题，搞了一个钟

**Comment by xiangxin0277** [comment]
难受啊  怎么办啊  巨人也不能用了

**Comment by brendan0524** [comment]
好像是b站的问题，我挂港澳台的v好像也看不了了

**Comment by bling2h** [comment]
同样的问题！无限次重新登陆，也没法看了……试了香港和台湾的VPN也不行

**Comment by xiangxin0277** [comment]
那怎么办 是B站出问题了？

**Comment by MOLLIN0** [comment]
各位好消息！B站正常了，确定脚本已经生效，可以正常看了！！！

**Comment by wingfall** [comment]
半个钟之前已解决

**Comment by bleach040** [comment]
噢噢能看了，虽然我已经去a站看完了
