### ISSUE TITLE
报错error:ReferenceError: $ is not defined请问是脚本失效了吗

### ISSUE THREAD

**Issue by Strangestranger** [ipcjs/bilibili-helper#287]
## 描述

今天早上开始在看b站新番的时候碰到如下错误 （jojo、终将等）
有大会员，登陆了，也能正常查看动态之类
error:ReferenceError: $ is not defined
![image](https://user-images.githubusercontent.com/44108269/46901545-b1d14900-cf01-11e8-9dc4-15a246a4ac7d.png)

部分新番(千岁等)能看但那个设置土星不见了
![image](https://user-images.githubusercontent.com/44108269/46901616-b3e7d780-cf02-11e8-83f6-2fa7d0234227.png)

biliplus可以正常访问，登录之后再从b站打开新番一样报错。

- 问题网址：https://www.bilibili.com/video/av33701057/

## 日志
土星没了...

```
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->
![image](https://user-images.githubusercontent.com/44108269/46901675-9ebf7880-cf03-11e8-882f-cb009e733979.png)
![image](https://user-images.githubusercontent.com/44108269/46901682-ac74fe00-cf03-11e8-9119-37a030193f95.png)



## 其他

1. 浏览器版本：Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
2. 国家/地区：澳大利亚 悉尼

**Comment by Strangestranger** [comment]
突然又好了...

**Comment by tomatofrommars** [comment]
我也出现了一样的问题

**Comment by tomatofrommars** [comment]
![image](https://user-images.githubusercontent.com/16113120/46904377-bbfd4280-cf15-11e8-9db1-bdae308105b0.png)
问题网址 https://www.bilibili.com/video/av33488613
系统 macOS 10.13.6 (17G65)
chrome 69.0.3497.100

**Comment by ipcjs** [comment]
新版B站改了jQuery的加载时机，切换成旧版就没问题

尝试适配了下新版，详见：
https://github.com/ipcjs/bilibili-helper/issues/266
