### ISSUE TITLE
脚本崩溃，显示error:ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by hmshzh** [ipcjs/bilibili-helper#289]
## 描述
大会员有的，也是登录状态。老番的港澳台依然能看，新番系列脚本崩溃。土星当然也没有啦。
![default](https://user-images.githubusercontent.com/44127796/46911905-f0671200-cf9a-11e8-8d7b-5509042564a0.png)

- 问题网址：
https://www.bilibili.com/video/av33608754/

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

![default](https://user-images.githubusercontent.com/44127796/46911880-af6efd80-cf9a-11e8-84d6-8e26d5ed0592.png)
![default](https://user-images.githubusercontent.com/44127796/46911888-c01f7380-cf9a-11e8-9e5f-88ce3a84fd0f.png)

## 其他

1. 浏览器版本：Firefox 62.0.3
2. 国家/地区：中国大陆/上海

**Comment by ipcjs** [comment]
新版B站改了jQuery的加载时机，切换成旧版就没问题

尝试适配了下新版，详见：
https://github.com/ipcjs/bilibili-helper/issues/266
