### ISSUE TITLE
年度大会员授权登录了还是没办法获取1080P画质

### ISSUE THREAD

**Issue by Noriyako** [ipcjs/bilibili-helper#29]
## 描述

授权登录了还是没办法获取1080P画质，我是年度大会员。只有在刷新那一瞬间看到有1080P的的画质，刷新视频全部载入之后最高画质就只有超清了。

## 日志

```
log: [解除B站区域限制 v6.3.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss6438#115372#reply575749170
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading
log: /x/web-interface/nav {"code":0,"data":{"isLogin":true,。。。,"vipStatus":1,"vipType":2,。。。}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":115373,"last_ep_index":"2","last_time":0}}}
log: setAreaLimitSeason ss6438 true
log: Redirected request: bangumi playurl ->  https://biliplus.ipcjs.win/BPplayurl.php?cid=24711122|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=e00064ff1ddb35e54c356cd0640dfe28
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

## 其他

1. 浏览器版本：Chrome版本 62.0.3202.94（正式版本） （32 位）【其实我电脑是64位的但Chrome自动更新到32位】
2. 国家/地区：大陆

**Comment by Noriyako** [comment]
话说那么多关于我个人的信息贴出来真的呆胶布？个人虽然不会编程之类的东西，可是英文还是看得懂的，但是我又不知道删除了应不影响大大你看哪里出了问题。。。。

**Comment by ipcjs** [comment]
(-_-#)，用户信息都打印出来了，这部分是没有必要的，待会我改下，不打印它们吧

**Comment by ipcjs** [comment]
要么你再授权一遍？
原因看不出来(-_-#)，我这里是正常的

**Comment by Noriyako** [comment]
@ipcjs 其实我重新授权好多遍了，还是没用。不过没关系，我并不是要看1080P的视频，高清已经足够了，只不过是想测试一下到底能不能加载出1080P而已。

**Comment by ipcjs** [comment]
换用www.biliplus.com这个服务器，重新授权试试。或者直接进 https://biliplus.ipcjs.win/login ，使用帐号密码登录。

@esterTion 貌似授权登录在biliplus.ipcjs.win上有问题。。。
https://biliplus.ipcjs.win/login?act=expiretime 会返回`Not Allowed.`
https://www.biliplus.com/login?act=expiretime 能够正常返回

**Comment by esterTion** [comment]
这应该是你的配置问题啊（甩锅）
  
---
我好像知道了，cookie设置域是`biliplus.com`
你可以选择编译lua模块然后修改`Set-Cookie`里的域名（

**Comment by ipcjs** [comment]
除了要配置 `    proxy_set_header     Host www.biliplus.com;` 还要配置其他的东西么？

(´･_･`)

**Comment by ipcjs** [comment]
> 我好像知道了，cookie设置域是biliplus.com

这样说的话，果然，还是不能要这句：`proxy_set_header Host www.biliplus.com;`🤔

设置了这个之后，你那边获取到的域名就是假的了

**Comment by ipcjs** [comment]
改回成：`proxy_set_header Host $host;`了，看起来没啥问题，就这样跑吧😅

**Comment by Noriyako** [comment]
@ipcjs 然后今天打开B站看到提示授权什么的，授权之后可以加载1080P了～于是来报告一下～～谢谢大大了～
