### ISSUE TITLE
番剧从av页无法调到番剧页

### ISSUE THREAD

**Issue by PhilCity** [ipcjs/bilibili-helper#290]
番剧从av页无法调到番剧页

- 问题网址：https://www.bilibili.com/video/av33378228

![iUJtj1.png](https://s1.ax1x.com/2018/10/14/iUJtj1.png)

**Comment by ipcjs** [comment]
新版B站改了jQuery的加载时机，切换成旧版就没问题

尝试适配了下新版，详见：
https://github.com/ipcjs/bilibili-helper/issues/266
