### ISSUE TITLE
好像彻底失效了？

### ISSUE THREAD

**Issue by Ouroboros** [ipcjs/bilibili-helper#292]
## 描述
打开链接不停地刷新, 只能看到下面两行日志

两台代理服务器都试过

账号已授权

随便找了其他几个仅限港澳台的都是一样

- 问题网址：https://www.bilibili.com/video/av33871218/

## 日志

<details>
<summary>Verbose 日志</summary>

```
log: [解除B站区域限制 v7.0.2 (Tampermonkey)] run on: https://www.bilibili.com/video/av33871218/
log: mode: default blocked_vip: undefined server: https://biliplus.ipcjs.win upos_server: undefined flv_prefer_ws:  remove_pre_ad: undefined readyState: loading isLogin: true isLoginBiliBili: true

debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

```
 
</details>

## 其他

0. 操作系统: Windows 10 1709
1. 浏览器版本：Chrome/69.0.3497.100
2. 国家/地区：中国大陆
3. 插件版本: 7.0.2

**Comment by ipcjs** [comment]
截个图看看？

**Comment by Ouroboros** [comment]
![output](https://user-images.githubusercontent.com/2263045/47058166-7af77d80-d1f6-11e8-85d5-62b70e186d41.gif)

**Comment by ipcjs** [comment]
复现不了(-_-#)

**Comment by Ouroboros** [comment]
之前弹了个框说是否切回旧版，我点是，好像那时开始就坏掉了

**Comment by ipcjs** [comment]
那你试试换成新版？🤔

**Comment by Ouroboros** [comment]
不知道在哪换回去

**Comment by ipcjs** [comment]
av页面的右边，有个“试用新版”按钮

**Comment by ipcjs** [comment]
av页面的右边，有个“试用新版”按钮

**Comment by ipcjs** [comment]
直接进：https://www.bilibili.com/bangumi/play/ss24629#234669
能正常播吗？

**Comment by Ouroboros** [comment]
> 直接进：https://www.bilibili.com/bangumi/play/ss24629#234669
> 能正常播吗？

这个可以播

**Comment by Ouroboros** [comment]
https://greasyfork.org/scripts/372516-bilibili-merged-flv-mp4-ass-enhance/code/bilibili%20merged%20flv+mp4+ass+enhance.user.js

找到原因了, 应该是跟这个脚本冲突了, 禁用他之后就正常了

**Comment by ipcjs** [comment]
这是他脚本的问题呀`(-_-#)`
你去他那提个issue吧
