### ISSUE TITLE
新版播放器评论区点击回复无法弹出输入框

### ISSUE THREAD

**Issue by miyouzi** [ipcjs/bilibili-helper#297]
## 描述
无法在楼层下评论，但可以回复楼层子评论

## 日志
![image](https://user-images.githubusercontent.com/24269465/47790389-02de9b00-dd52-11e8-8eb4-828226c067fb.png)

## 其他

1. 浏览器版本：Google Chrome 70.0.3538.77（正式版本） （64 位）

## GIF
![gif](https://user-images.githubusercontent.com/24269465/47790596-91ebb300-dd52-11e8-93bc-1e2459733a58.gif)

**Comment by ipcjs** [comment]
你确定这个跟脚本有关系？

**Comment by miyouzi** [comment]
我是这么排查的……
![gif2](https://user-images.githubusercontent.com/24269465/47791020-9ebcd680-dd53-11e8-9f5c-9f9e8b051f35.gif)

**Comment by ipcjs** [comment]
。。。我待回看看

**Comment by ipcjs** [comment]
你这个录gif感觉好厉害，用的啥软件？

**Comment by miyouzi** [comment]
GifCam

**Comment by ipcjs** [comment]
3cea87bba27429ba75f6a9a06fe5505f38590d35

怼了一堆if-else上去，大概能用了吧`Σ( ￣□￣||)`

**Comment by miyouzi** [comment]
BUG解除，Nice！

**Comment by esterTion** [comment]
好，问题复出了
![qq 20181204142234](https://user-images.githubusercontent.com/7265411/49422776-19a06380-f7d0-11e8-9f77-c104e5622a4a.png)

---
split草
大概`(e.data||'').split`就行了吧
~话说破逼为什么用postMessage展开回复……~
想了想不对，这个不是展开问题的报错，不过这个也解决一下比较好

**Comment by ipcjs** [comment]
脚本的日志收集也是用message做的`(-_-#)`

8709e8d180c072c8e7ec898820b74086d6d8bd8a
