### ISSUE TITLE
无限的突破黑洞失败，登录多次也没用 bug

### ISSUE THREAD

**Issue by Hammer0707** [ipcjs/bilibili-helper#300]
## 描述

无限的突破黑洞失败
- 问题网址：https://www.bilibili.com/bangumi/play/ep250467/?spm_id_from=333.334.b_62696c695f62616e67756d69.12

## 日志
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250467/?spm_id_from=333.334.b_62696c695f62616e67756d69.12
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: bos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"老婆泉此方","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1552320000000,"status":1,"type":2},"watch_progress":{"last_ep_id":250466,"last_ep_index":"7","last_time":1396}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=15&module=bangumi&season_type=1&qn=15&sign=a34ad4ff24bb7c17e159d27a44e06efd
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=49e99e7cf820b2d47224a8e08e763f1f
error: >>area limit
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：谷歌浏览器70.0.3538.110（正式版本） （32 位）
2. 国家/地区：加拿大多伦多

**Comment by Hammer0707** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250467
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: bos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"老婆泉此方","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1552320000000,"status":1,"type":2},"watch_progress":{"last_ep_id":250466,"last_ep_index":"7","last_time":1396}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=15&module=bangumi&season_type=1&qn=15&sign=a34ad4ff24bb7c17e159d27a44e06efd
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by Hammer0707** [comment]
我测试了一下，只有今天更新的新番有问题，剩下的都ok。可能是服务器炸了。

**Comment by Hammer0707** [comment]
不仅是新番，部分老番也出现随机性无法观看如魔法少女小圆

log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep63481?from=search&seid=4514576803782467066
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: bos flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"老婆泉此方","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1552320000000,"status":1,"type":2}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=16471774&appkey=84956560bc028eb7&otype=json&type=&quality=15&module=bangumi&season_type=1&qn=15&sign=3a11e60102d3109e5413e847ca813257
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=16471774&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=e40683ff491bef19304b6f73223cd337
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=16471769&appkey=84956560bc028eb7&otype=json&type=&quality=15&module=bangumi&season_type=1&qn=15&sign=9b9b34f3555e95ec63b04fac575407d4
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=16471774&appkey=84956560bc028eb7&otype=json&type=&quality=15&module=bangumi&season_type=1&qn=15&sign=3a11e60102d3109e5413e847ca813257
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=16471774&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=e40683ff491bef19304b6f73223cd337
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by HachanprprJK** [comment]
今天下午开始以后番剧全都没法看了，打开后就是黑洞

**Comment by wefanqs** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250440
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"Sergey Brin","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1553270400000,"status":1,"type":2},"watch_progress":{"last_ep_id":250439,"last_ep_index":"6","last_time":-1}}}
log: setAreaLimitSeason ep250440 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63355113&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=9827fb9363d601f24a52c67c61387b8a
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63355113&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=6502386be7bacff85d93a298c1213b97
error: >>area limit
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36


测试位置：台湾。一样的“无限的突破黑洞失败”

**Comment by Richard1Chen** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250464
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"无名的咸鱼之王","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1599494400000,"status":1,"type":2},"watch_progress":{"last_ep_id":250463,"last_ep_index":"4","last_time":-1}}}
log: setAreaLimitSeason ep250464 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=61103378&appkey=84956560bc028eb7&otype=json&type=&quality=74&module=bangumi&season_type=1&qn=74&sign=de22ab35eb5aedbb117f014e92063828
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=61103378&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=0dc3862161ca397bd058acceee8303db
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
error: >>area limit

**Comment by Richard1Chen** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250841
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: bos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"无名的咸鱼之王","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1599494400000,"status":1,"type":2},"watch_progress":{"last_ep_id":250840,"last_ep_index":"5","last_time":-1}}}
log: setAreaLimitSeason ep250841 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=62593379&appkey=84956560bc028eb7&otype=json&type=&quality=74&module=bangumi&season_type=1&qn=74&sign=ab53df166383cbba5f0891e646be0e6d
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=62593379&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=40ca3a9dcb29a174d892b5da839deaa2
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
尝试了多个不同页面，还是失败

**Comment by pakasas** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25739/?spm_id_from=333.334.b_62696c695f62616e67756d69.16
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"Pakasas","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586966400000,"status":1,"type":2},"watch_progress":{"last_ep_id":250467,"last_ep_index":"8","last_time":0}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=02ed6e26c1a87dd17867ada07a34ed09
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=49e99e7cf820b2d47224a8e08e763f1f
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by pakasas** [comment]
新番都看不了了，不管是史莱姆还是刀剑

**Comment by leoouyang** [comment]
看不了+1 
加拿大多伦多

**Comment by pakasas** [comment]
日本东京，看来海外党大家都出问题了……

**Comment by BenJohn620** [comment]
香港也不行，應該是服務器問題

**Comment by ipcjs** [comment]
确实看不了，大概是服务器问题？@esterTion

**Comment by Aspire1Inspire2** [comment]
确实是看不了……证实此bug的严重性

**Comment by tyker1** [comment]
突然就无限黑洞了。。。。

**Comment by xiexp3** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss10126/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1561651200000,"status":1,"type":2},"watch_progress":{"last_ep_id":116302,"last_ep_index":,"last_time":22}}}
log: setAreaLimitSeason ss10126 true
log: /x/web-interface/nav {"uname":"","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=7606362&appkey=84956560bc028eb7&otype=json&type=&quality=15&module=movie&season_type=2&qn=15&sign=812dc1712dfa1e34f78b2c6618f5cab0
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=7606362&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=movie&season_type=2&qn=16&sign=f168c25c170a44b5aa22bab4bef2f0b7
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
反复授权，看不了

**Comment by esterTion** [comment]
草，我想到原因了
早上再改

**Comment by ChuangSheep** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss441#8206
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"wangcy001","isLogin":true,"level":3,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":0,"status":0,"type":0},"watch_progress":{"last_ep_id":8206,"last_ep_index":"1","last_time":1243}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=27475956&appkey=84956560bc028eb7&otype=json&type=&quality=64&module=bangumi&season_type=1&qn=64&sign=87ac737ef7e33edc841cca3915577a96
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
error: >>area limit

德国也是

**Comment by JohnNongHuang** [comment]
英国这边也出问题了，刚开始是部分加载不出来，有的还能看，后来就全是黑洞了。。。。。。

**Comment by aceliuchanghong** [comment]
看不了!!!

**Comment by esterTion** [comment]
已修复
我是纸张

**Comment by pakasas** [comment]
感谢作者大佬，放学回家试试去！

**Comment by bobai-ding** [comment]
澳大利亚也不行了。部分资源可以，但有的一直失败

**Comment by Thomasgithubonly** [comment]
地区美国纽约，从今天下午开始也不行了😂，一开始还以为是自己的账号问题。

**Comment by HachanprprJK** [comment]
谢谢纸张大佬！

**Comment by wefanqs** [comment]
谢谢！台湾测试1080p和大会员新番都没问题了

**Comment by pakasas** [comment]
感谢大佬！岛国表示已经可以正常看了

**Comment by Richard1Chen** [comment]
坐标英国，已修复

**Comment by JohnNongHuang** [comment]
感谢大佬

**Comment by Aspire1Inspire2** [comment]
太感谢了！！无限感激！
