### ISSUE TITLE
bilibili failed

### ISSUE THREAD

**Issue by XJuie** [ipcjs/bilibili-helper#301]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep216153
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"沉迷咸鱼的桐人菌","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1585584000000,"status":1,"type":2},"watch_progress":{"last_ep_id":216153,"last_ep_index":"16","last_time":4}}}
log: setAreaLimitSeason ep216153 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=44291685&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=3c03d14d03288681e748203ea2ec0d7e
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=44291685&player=1&qn=116&quality=116&ts=1542808732&sign=f8a3b7590b91a5185e848896957ff8ad
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=44291685&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=3c03d14d03288681e748203ea2ec0d7e
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=44291685&player=1&qn=116&quality=116&ts=1542808763&sign=2c6ee6f1fd8473056845b027f8a3aa34
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=44291685&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=3c03d14d03288681e748203ea2ec0d7e
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36

**Comment by XJuie** [comment]
测试地点：China AnHui中国安徽

**Comment by ipcjs** [comment]
#303
