### ISSUE TITLE
拉取视屏地址失败

### ISSUE THREAD

**Issue by mjy09981** [ipcjs/bilibili-helper#302]
## 描述

拉取视频地址失败
- 问题网址：https://www.bilibili.com/bangumi/play/ep103130

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep103130
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"曼德拉稀","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1558022400000,"status":1,"type":2},"watch_progress":{"last_ep_id":103130,"last_ep_index":"1","last_time":1309}}}
log: {"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1542817800&platform=ios&ssig=KznS0np851VFyFihn9eAWw&oi=3078818617&nfa=7VMUDqBQpI8VGBbhQ1faUQ==&dynamic=1&hfa=2043063060&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=e6544d6875614f8eb78ee47321491e40&nfc=1"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=15679864&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=7a9455c14a75cdb8465dfc53701fd9b6
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by Hammer0707** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250592/?spm_id_from=333.334.b_62696c695f62616e67756d69.24
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.top upos_server: bos flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"老婆泉此方","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1552320000000,"status":1,"type":2},"watch_progress":{"last_ep_id":250591,"last_ep_index":"7","last_time":1328}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=63889852&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=2c85ebd14e61e90715365e0f49c290f2
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=63889852&player=1&qn=112&quality=112&ts=1542850625&sign=7b9e11b73cc7c23d1e538d8ea46434ba
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=63889852&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=2c85ebd14e61e90715365e0f49c290f2
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=63889852&player=1&qn=112&quality=112&ts=1542850626&sign=8387c743c8d4ef3eb703f3ce0860cd5f
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=63889852&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=2c85ebd14e61e90715365e0f49c290f2
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=63889852&player=1&qn=112&quality=112&ts=1542850628&sign=c1a497ec368af0793bd6e73fc67b5ee9
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=63889852&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=2c85ebd14e61e90715365e0f49c290f2
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=63889852&player=1&qn=112&quality=112&ts=1542850630&sign=135e233844d81ab7c48ef12c74ca882d
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=63889852&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=2c85ebd14e61e90715365e0f49c290f2
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=63889852&player=1&qn=112&quality=112&ts=1542850631&sign=490cf4c613edee4e94d0b1893a3a2694
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by ipcjs** [comment]
#303
