### ISSUE TITLE
无法授权账号

### ISSUE THREAD

**Issue by pockytea** [ipcjs/bilibili-helper#303]
* 提交bug前，先看“帮助>脚本无效？”，绝大多数问题都是能直接解决的！！（直达链接：https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.md#%E8%84%9A%E6%9C%AC%E6%97%A0%E6%95%88）
* 服务器抽风的问题，别再重复提交issue了，我这里没法解决。
* 请仔细填写问题相关的信息，信息不足的直接关闭。
-->

## 描述

我有大会员，也一直在用这个脚本。昨天开始连接不上，之后点击授权账号并输入账号密码后，显示服务器认证失败
- 问题网址：https://www.bilibili.com/bangumi/play/ss25739#250467

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25739#250467
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: bos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"長門","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1616774400000,"status":1,"type":2},"watch_progress":{"last_ep_id":250467,"last_ep_index":"8","last_time":1}}}
log: setAreaLimitSeason ss25739 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=63778357&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=02ed6e26c1a87dd17867ada07a34ed09
log: playurl的result缺少必要的字段: {"code":-403,"message":"没有观看此付费视频的权限　Video requires payment"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36<!--** 
```
 
</details>

## 其他

1. 浏览器版本：chrome 70.0.3538.110
2. 国家/地区：japan

**Comment by shimarenzo** [comment]
log: [解除B站区域限制 v7.0.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep113112?from=search&seid=17369178115418026272
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"izayoisakiya","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":0,"status":0,"type":0},"watch_progress":{"last_ep_id":113112,"last_ep_index":"7","last_time":3}}}
log: setAreaLimitSeason ep113112 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=21785463&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=30c35fd83964d231223b86343a3e9b11
log: playurl的result缺少必要的字段: {"code":-403,"message":"Restricted Area"}
log: balh_server  =>  https://biliplus.ipcjs.top
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
log: balh_remove_pre_ad  =>  
log: balh_server  =>  https://www.biliplus.com

**Comment by shimarenzo** [comment]
授权不了，一直显示错误

**Comment by lzy0702** [comment]
授权的链接返回404，不晓得为什么

**Comment by ipcjs** [comment]
试下直接去biliplus登录

**Comment by ipcjs** [comment]
@esterTion 这次是帐号授权问题`_(:3」∠)_`

**Comment by ipcjs** [comment]
修复前，先直接去代理服务器登录：https://www.biliplus.com/login

**Comment by esterTion** [comment]
链接授权死了？
以后必须密码登录了，用户数可以开个根号了
![qq 20181123130353](https://user-images.githubusercontent.com/7265411/48929087-3e6b2000-ef20-11e8-95c2-f5accf179646.png)

**Comment by ipcjs** [comment]
可以减轻服务器压力😅

**Comment by esterTion** [comment]
减轻压力还行
看不懂这个操作，估计一堆人也不愿意输密码

**Comment by pockytea** [comment]
> 修复前，先直接去代理服务器登录：https://www.biliplus.com/login

好，多谢了。能看就知足。

**Comment by esterTion** [comment]
修改思路：
你去看一下能不能拦截biligame登陆地址里的accesskey，不过那个好像是302
或者看看其他地址，反正如果能拦截再手动跳转到登录

**Comment by ipcjs** [comment]
是说，想办法获取网页里面的access_key吗？但我点了半天，没看到网页里哪个接口用了access_key呀

**Comment by esterTion** [comment]
不是，他的链接授权在biligame论坛也是用的，你看看那个跳转路径里面，有没有可能注入拦截，可以的话就可以操作了

**Comment by ipcjs** [comment]
bbs.biligame.com ？
系统维护中😂

**Comment by esterTion** [comment]
喷了……看了眼mcbbs也没了
你慢慢试着生成几个b站域名地址看能不能用接口，不能的话就凉透

就代码里已有的md5过程

**Comment by ipcjs** [comment]
不行🤔
算了，就用帐号密码登录吧`_(:3」∠)_`

**Comment by esterTion** [comment]
试了下确实输入什么都报错
你改iframe把，我把postMessage加上了，应该不用改额外代码
```JavaScript
if(parent != window)
	parent.postMessage('BiliPlus-Login-Success', '*');
else
	setTimeout(function(){location.href=json.visiturl},1e3);
```

**Comment by ipcjs** [comment]
51ece1e22150e366561c43719243869f10b63b14

B站这是彻底不让第三方登录了？

**Comment by esterTion** [comment]
大概吧，要不就是代码改错了

但是没有别人用了，就算是bug也不会有人修，就像我那边动态里面的简介一样
![qq 20181124234225](https://user-images.githubusercontent.com/7265411/48970066-9d28ba80-f042-11e8-8468-59eb9162c645.png)

**Comment by indefined** [comment]
或许可以试一下抓这个链接，三次转跳可以得到access_key，不过似乎要拦截起来挺蛋疼的，最后会转跳入反馈论坛
http://passport.bilibili.com/login/appSuccess?api=http%3A%2F%2Flink.acg.tv%2Fbilibili_connect.php%3Fmod%3Dauth%26op%3Dcallback&appkey=8907c61e930c789c&sign=4774633fd585a2477d9f329105d7f1e7&mhash=3443f717e612927165b6579f3d6c5be3&confirm=1

**Comment by esterTion** [comment]
行吧，link.acg.tv 可以获取key
域名白名单还行吧

https://passport.bilibili.com/login?appkey=27eb53fc9058f8c3&api=https%3A%2F%2Flink.acg.tv%2Fforum.php&sign=2f608fb85b7df558e2c5b8cb2059577d

---
考虑新登录模型
- 直接在任意页面GET `https://passport.bilibili.com/login/app/third?appkey=27eb53fc9058f8c3&api=https%3A%2F%2Flink.acg.tv%2Fforum.php&sign=2f608fb85b7df558e2c5b8cb2059577d` （跨域b站目前底层会自动添加，不需要考虑特权xhr）
- 隐藏iframe加载`response.data.confirm_uri`
- 注入`http://link.acg.tv/forum.php`，检测到地址的access_key时`postMessage`发送给父页面（因为那边没有cookie的配置信息）

想到的问题
- 会导致 mixed content
- 同上，理想情况应该直接xhr get的

如果需要可以把授权地址换成比如`/static/`，可能会被搞，但相比加载首页会少很多流量需求
简单测试只有link.acg.tv，这白名单怕是只有一个域名

**Comment by SerCom-KC** [comment]
🤔
如果不强求 `access_key` ，Cookie 也能接受的话，扫码登录大概是最后的方案了…… ~~不过这个方案肯定会触发懒癌晚期~~

**Comment by ipcjs** [comment]
扫码登录才是最恶心的吧😒

**Comment by SerCom-KC** [comment]
🌚 ~~如果你吐槽的是扫码这个行为本身的话其实可以做一个私信 bot 直接发送链接让用户在客户端点~~
反正都是下下策🤣

**Comment by ipcjs** [comment]
没必要越搞越复杂

esterTion 已经写了获取access key的功能了

https://github.com/ipcjs/bilibili-helper/pull/308

**Comment by SerCom-KC** [comment]
我知道，只是顺便提一下，而且 #308 大概也只能用于 userscript 这种而无法用到 biliplus 本身上（吧

**Comment by esterTion** [comment]
要用输密码，不用再见，就这态度（直球）

---
作为脚本应该是扩展型，不应该再输一次密码，体验极差。
作为另外单独网站就和这个无关了，本身独立功能
