### ISSUE TITLE
其他一切正常，只有史莱姆突破黑洞失败

### ISSUE THREAD

**Issue by Richard1Chen** [ipcjs/bilibili-helper#305]
服务器问题：@esterTion

## 描述
试验了多个动画
只有转生史莱姆突破黑洞失败，其他都正常
清理过cookie，更换服务器也不能解决
- 问题网址：
https://www.bilibili.com/bangumi/play/ep250468

## 日志

log: [解除B站区域限制 v7.0.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250468
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"无名的咸鱼之王","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1599494400000,"status":1,"type":2},"watch_progress":{"last_ep_id":250467,"last_ep_index":"8","last_time":-1}}}
log: setAreaLimitSeason ep250468 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=64660848&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=e9d1429a6865611a94c287a2314bdfeb
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=64660848&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=53a1c27e0e1a5d4e397cca5c5a2f0e28
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
## 其他

1. 浏览器版本：chrome70.0.3538.110 (Official Build) (64-bit)
2. 国家/地区：英国

**Comment by yiwenzhang92** [comment]
Same issue @ USA Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by esterTion** [comment]
已处理
怎么还有被错误添加到跨区缓存cid的

**Comment by yiwenzhang92** [comment]
嗯 我这里可以看了

**Comment by Richard1Chen** [comment]
已经解决
