### ISSUE TITLE
一直弹拉去地址失败 换upos保存失败

### ISSUE THREAD

**Issue by NaixHw** [ipcjs/bilibili-helper#306]
log: [解除B站区域限制 v7.0.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep251084/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"pikopaka","isLogin":true,"level":5,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"dialog":{"btn_right":{"title":"成为大会员","type":"vip"},"desc":"","title":"开通大会员抢先看"},"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1485187200000,"status":0,"type":1},"watch_progress":{"last_ep_id":251082,"last_ep_index":"7","last_time":-1}}}
log: {"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1543461000&platform=ios&ssig=_uDh4Kbmm-wg2TMSTaWA-Q&oi=3078818617&nfa=7VMUDqBQpI8VGBbhQ1faUQ==&dynamic=1&hfa=2043443991&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=e441d339f0b0466e8fa19eda6ee91d83&nfc=1"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=64641038&appkey=84956560bc028eb7&otype=json&type=&quality=64&module=bangumi&season_type=1&qn=64&sign=f6303b4be9542188ee61a067c2837cd5
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
log:   =>  ks3
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=64641038&player=1&qn=64&quality=64&ts=1543453975&sign=9226e673b3682a2240f2c599ba16d338
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: {"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1543461000&platform=ios&ssig=DPJ1zaJkQGq5VxBWsbklkQ&oi=3078818617&nfa=7VMUDqBQpI8VGBbhQ1faUQ==&dynamic=1&hfa=2043443980&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM=&trid=2d3856db4760446980cad8e5428c2111&nfc=1"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=64641038&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=9d31cad42f1c78aa87c3ed44dbbbeef8
log:   =>  ks3
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=64641038&player=1&qn=16&quality=16&ts=1543453994&sign=1d96e21d2ce94b6a13f6e5ec228a9d14
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}

**Comment by ipcjs** [comment]
登陆了代理服务器？

**Comment by esterTion** [comment]
没事，我刚跟服务器商在扯皮
挂了好几次，现在应该稳定了

**Comment by esterTion** [comment]
对了，服务器ip变了，你看看是不是需要重启

**Comment by ipcjs** [comment]
没问题，好久之前就配了
（那个配置真的太反自觉，域名一定要写成变量才会去解析😓
