### ISSUE TITLE
无限提示 突破黑洞失败

### ISSUE THREAD

**Issue by DemiurgeZ** [ipcjs/bilibili-helper#310]
脚本问题：@ipcjs

## 描述

无限弹窗“突破黑洞失败” 授权、换服务器都没用
看的是《南极料理人》 据评论区所说是要香港ip。。。
![2018-12-14_171937](https://user-images.githubusercontent.com/44410173/49994652-0312bd00-ffc5-11e8-9312-7cb57bc87185.png)
![2018-12-14_171833](https://user-images.githubusercontent.com/44410173/49994683-19b91400-ffc5-11e8-9351-966460520ac5.png)

- 问题网址：https://www.bilibili.com/bangumi/play/ss12538?from=search&seid=13825718040285873973

## 日志

<details>
<summary>Verbose 日志</summary>

log: [解除B站区域限制 v7.1.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss12538?from=search&seid=13825718040285873973
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"MasterDemiurge","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":-1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1617724800000,"status":1,"type":2}}}
log: setAreaLimitSeason ss12538 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=30972867&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=movie&season_type=2&qn=116&sign=ae6fc8db3ba9854660e38c7dc9526c47
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=30972867&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=movie&season_type=2&qn=16&sign=0e916a9e7ca0a06606ad038ab43e342c
error: >>area limit
 
</details>

## 其他

1. 浏览器版本：Chrome 70.0.3538.110（正式版本） （64 位）
2. 国家/地区：中国

**Comment by jackjieS** [comment]
别问 服务器商家跑路了https://www.zhujiceping.com/34921.html

**Comment by jackjieS** [comment]
> 脚本问题：@ipcjs
> 
> ## 描述
> 无限弹窗“突破黑洞失败” 授权、换服务器都没用
> 看的是《南极料理人》 据评论区所说是要香港ip。。。
> ![2018-12-14_171937](https://user-images.githubusercontent.com/44410173/49994652-0312bd00-ffc5-11e8-9312-7cb57bc87185.png)
> ![2018-12-14_171833](https://user-images.githubusercontent.com/44410173/49994683-19b91400-ffc5-11e8-9351-966460520ac5.png)
> 
> * 问题网址：https://www.bilibili.com/bangumi/play/ss12538?from=search&seid=13825718040285873973
> 
> ## 日志
> Verbose 日志
> ## 其他
> 1. 浏览器版本：Chrome 70.0.3538.110（正式版本） （64 位）
> 2. 国家/地区：中国
别问 服务器商家跑路了
https://www.zhujiceping.com/34921.html
