### ISSUE TITLE
嘿朋友，b站上弹出窗口说你跑路了是怎么回事？

### ISSUE THREAD

**Issue by AlfredChairman** [ipcjs/bilibili-helper#315]
服务器问题：@esterTion

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
是 ”服务器提供商“跑路
不是”服务器“跑路
末尾不是给了链接吗？别再建新的issue了。

**Comment by esterTion** [comment]
把这个模版下了吧…巨烦

**Comment by ipcjs** [comment]
ok

**Comment by AlfredChairman** [comment]
我

> 是 ”服务器提供商“跑路
> 不是”服务器“跑路
> 末尾不是给了链接吗？别再建新的issue了。

哦哦，抱歉我刚才没有看清楚。。。

**Comment by ipcjs** [comment]
模板关了，回复过的问题貌似会自动订阅，你手动取消下订阅吧

**Comment by AlfredChairman** [comment]
> 模板关了，回复过的问题貌似会自动订阅，你手动取消下订阅吧

嗯嗯，对GitHub还不是很熟悉0.0
