### ISSUE TITLE
怎么设置都看不了，坐标意大利

### ISSUE THREAD

**Issue by KenWuqianghao** [ipcjs/bilibili-helper#316]
log: [解除B站区域限制 v7.1.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep251086
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by ipcjs** [comment]
#311
