### ISSUE TITLE
建议菊苣开捐助吧~认领一个汉堡钱

### ISSUE THREAD

**Issue by KeiNagase** [ipcjs/bilibili-helper#317]
rt，辛苦菊苣了，服务器商也得花钱吧

**Comment by ipcjs** [comment]
a24bd310a497dd55e87d808adadfcf4c3c192789

设置页面加了个跳转到服务器的捐赠页面的链接。

@esterTion 捐赠二维码可以加个id么？这样就可以直接跳转过去了，不用向下翻页`_(:3」∠)_`

**Comment by esterTion** [comment]
其实都没啥必要，就目前捐赠频度已经抵费用了
（今天还有个美帝壕直接$100）

作为猴子注入页面的地方挂是不是比较那啥，或者只是我观念问题🤔

**Comment by ipcjs** [comment]
捐赠，在网站里本来就是有的，只是给个链接而已，省的总有人问
