### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by HachanprprJK** [ipcjs/bilibili-helper#319]
番剧全崩 坐标东京

**Comment by Chrishaokai** [comment]
无限拉取失败

**Comment by leafhonor** [comment]
坐标佛罗里达，拉取失败

**Comment by zeroNIz** [comment]
坐标国内，upos替换保存失败，拉取失败

**Comment by StargazerYi** [comment]
坐标麻省，无限拉取失败

**Comment by Glorybow** [comment]
脚本问题：@ipcjs

## 描述


- 问题网址：
https://www.bilibili.com/bangumi/play/ep258942

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

log: [解除B站区域限制 v7.1.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep258942
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: kodo flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Glorybow","isLogin":true,"level":6,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1637424000000,"status":1,"type":2},"watch_progress":{"last_ep_id":258943,"last_ep_index":"2","last_time":-1}}}
log: setAreaLimitSeason ep258942 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68821403&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=7cb8fc44b507b58b20fa0071f8cf438f
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68821403&player=1&qn=116&quality=116&ts=1545992845&sign=36373eea339b5a2ce959f973d6bd27c9
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68821403&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=7cb8fc44b507b58b20fa0071f8cf438f
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68821403&player=1&qn=116&quality=116&ts=1545992845&sign=36373eea339b5a2ce959f973d6bd27c9
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68821403&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=7cb8fc44b507b58b20fa0071f8cf438f
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68821403&player=1&qn=116&quality=116&ts=1545992846&sign=99b1fd1f25ffcefa9f8fbfb0472f04f1
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68821403&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=7cb8fc44b507b58b20fa0071f8cf438f
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68821403&player=1&qn=116&quality=116&ts=1545992847&sign=869ed1af7c8e60c23b72fb149522cd6f
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68821403&appkey=84956560bc028eb7&otype=json&type=&quality=116&module=bangumi&season_type=1&qn=116&sign=7cb8fc44b507b58b20fa0071f8cf438f
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68821403&player=1&qn=116&quality=116&ts=1545992848&sign=610f1d1c75ed59f6776394551e8dfe9a
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
log:   =>  oss

```
 
</details>



## 其他

1. 浏览器版本：Chrome/71.0.3578.98
2. 国家/地区：美国 纽约

**Comment by dickdick88** [comment]
## 描述
不能播放bilibili視頻

- 问题网址：
https://www.bilibili.com/bangumi/play/ss25733/?spm_id_from=333.334.b_62696c695f62616e67756d69.28

## 日志

<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v7.1.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25733/?spm_id_from=333.334.b_62696c695f62616e67756d69.28
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"純淨的我","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1557590400000,"status":1,"type":2},"watch_progress":{"last_ep_id":251087,"last_ep_index":"12","last_time":-1}}}
log: setAreaLimitSeason ss25733 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68836110&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=683c7fefd142c598e9f59dd0171e1ac0
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68836110&player=1&qn=112&quality=112&ts=1546011280&sign=3e97a9306cb78c3372b5508947769f8d
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68836110&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=683c7fefd142c598e9f59dd0171e1ac0
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68836110&player=1&qn=112&quality=112&ts=1546011311&sign=ad6dd087b3e2c628588de5f7c22e12be
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68836110&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=683c7fefd142c598e9f59dd0171e1ac0
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68836110&player=1&qn=112&quality=112&ts=1546011328&sign=7b3c932caaa2a35f4dffc5e177ecf278
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68836110&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=683c7fefd142c598e9f59dd0171e1ac0
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68836110&player=1&qn=112&quality=112&ts=1546011332&sign=7d3ca46842e052f01e71bf931ad9c80e
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=68836110&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=683c7fefd142c598e9f59dd0171e1ac0
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=68836110&player=1&qn=112&quality=112&ts=1546011334&sign=4fa0ef50814e2708398926f0a956a799
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36



## 其他

1. 浏览器版本：Chrome 71.0.3578.98
2. 国家/地区：香港

**Comment by leafhonor** [comment]
坐标美国西海岸，今早发现又不可以拉取视频了
问题网址：https://www.bilibili.com/bangumi/play/ep250662
https://www.bilibili.com/bangumi/play/ep250446

**Comment by xe5700** [comment]
hosts里加
118.89.227.130 www.biliplus.com

**Comment by Amadeus-AI** [comment]
加完hosts後成功了，感謝

**Comment by leafhonor** [comment]
成功了，谢谢！

**Comment by ipcjs** [comment]
这回是DNS崩了吗😂

**Comment by maxhuoji** [comment]
请问怎么加这个hosts啊，电脑白痴完全不知道怎么办

**Comment by maxhuoji** [comment]
> hosts里加
> 118.89.227.130 [www.biliplus.com](http://www.biliplus.com)

麻烦问一下怎么加呀，对这些东西完全不懂，求帮助

**Comment by Amadeus-AI** [comment]
C:\Windows\System32\drivers\etc\hosts
用記事本打開 打上那行即可
有時B站速度慢也是可以用hosts解決的

**Comment by maxhuoji** [comment]
> C:\Windows\System32\drivers\etc\hosts
> 用記事本打開 打上那行即可
> 有時B站速度慢也是可以用hosts解決的

感谢感谢，果然好了

**Comment by ipcjs** [comment]
biliplus的DNS解析已经恢复正常了
把hosts改回去吧
