### ISSUE TITLE
脚本无效 

### ISSUE THREAD

**Issue by vvvaga** [ipcjs/bilibili-helper#326]
无法破解视频，提示所在地区无法观看
已经改过hosts，但是没用
代理服务器的链接也点不开，更换服务器也不行
- 问题网址：

https://www.bilibili.com/bangumi/play/ss26303/?spm_id_from=333.334.b_62696c695f62616e67756d69.13

log: [解除B站区域限制 v7.1.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26303/?spm_id_from=333.334.b_62696c695f62616e67756d69.13
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
```
 
1. 浏览器版本：Cent Browser
2. 国家/地区：澳大利亚

**Comment by ipcjs** [comment]
biliplus的DNS解析已经正常了，把hosts改回去
