### ISSUE TITLE
腳本無效，連bilibili首頁都無法進入

### ISSUE THREAD

**Issue by raitokuma** [ipcjs/bilibili-helper#327]
安裝腳本後
我按這張圖設置
![image](https://user-images.githubusercontent.com/26527043/50726069-b1340180-1142-11e9-8bc9-b9bc70134876.png)

在修改host後發現沒有效果甚至無法載入bilibili首頁，於是把Host又改回去並移除腳本
但是問題依舊存在，且使用其他電腦能順利瀏覽bilibili。
請問該如何解決或是完整移除腳本
瀏覽器:chrome

**Comment by ipcjs** [comment]
禁用脚本就行了，脚本会在b站的cookie里存些配置，但不会影响b站，访问不了，你看下是不是你网络的问题。
还有别改hosts了，biliplus的IP地址经常会换的
