### ISSUE TITLE
playurl新地址

### ISSUE THREAD

**Issue by esterTion** [ipcjs/bilibili-helper#330]
`https://api.bilibili.com/pgc/player/web/playurl?avid=40320527&cid=70815691&qn=112&type=&otype=json&ep_id=259818&fnver=0&fnval=16&session=ae34542735cbffb1460078efafdbc4f7`

重构api（1/1）

**Comment by esterTion** [comment]
另外你考不考虑把这个repo独立出去，和原fork差太远了

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub support.
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

**Comment by ipcjs** [comment]
还可以直接独立吗？我试试

**Comment by ipcjs** [comment]
直接替换url：https://www.biliplus.com/BPplayurl.php?avid=40320527&cid=70815691&qn=112&type=&otype=json&ep_id=259818&fnver=0&fnval=16&session=ae34542735cbffb1460078efafdbc4f7
貌似只能获取到这样的数据：
```
{"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":1045900070,"length":1421609,"url":"https://video-sg.biliplus.com:1520/file/444908a8fd1eb28a9b3f27f3b711e5d2/1547143644/2892623181/1YnTP3H4VzINsGG_QNU-gnRxQ9t1ktYa-/videoplayback.mp4"}]}
```

**Comment by ipcjs** [comment]
试了下直接替换，拉到的是你服务器的文件`(-_-#)`
先推到`dev`分支了（感觉发布出去的话，你服务器会爆炸
158cbd0fa055bf71cfa8d293d55be3dbd44ba43a

**Comment by esterTion** [comment]
因为参数没有module了
emmm，我没看电影那边，怎么区别的
按理说电影也叫pgc

保险起见可以读页面地址判断？

**Comment by ipcjs** [comment]
我手动加个`module=bangumi`进去？

**Comment by esterTion** [comment]
可以，你确认下电影页面？

**Comment by ipcjs** [comment]
现在貌似没有`/movie`的页面了？找了半天没找到

**Comment by ipcjs** [comment]
8c05351acd0bf25d1d33d534c5e681c4578c7e26

**Comment by esterTion** [comment]
这就独立了，还挺快

**Comment by ipcjs** [comment]
昨天就独立了，效率超高🤣
