### ISSUE TITLE
非常抱歉 本视频可能由于以下原因导致无法正常拨放 => 请更新到7.2.1以上版本

### ISSUE THREAD

**Issue by Zorz4** [ipcjs/bilibili-helper#331]
脚本问题：@ipcjs

## 描述
就快看完结了，结果出错是真的难受，好像有区域限制的都不能看

- 问题网址：https://www.bilibili.com/bangumi/play/ep259731

## 日志

<details>
<summary>Verbose 日志</summary>

```
log: [解除B站区域限制 v7.1.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep259727
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"Zorz4","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1578758400000,"status":1,"type":2},"watch_progress":{"last_ep_id":259731,"last_ep_index":"9","last_time":2}}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by lbldknight** [comment]
复议，出现了同样的问题

**Comment by DeepTwilight** [comment]
我也出现了同样的问题
### https://www.bilibili.com/bangumi/play/ep96710
吹响吧！悠风号 第二季第8集

**Comment by sixteenmetre** [comment]
感觉是B站采用了新的对海外党宝具

**Comment by sixteenmetre** [comment]
因为我使用了其他的翻墙插件也是一样的提示，16秒警告

**Comment by bobleer** [comment]
同样在看revisions...突然就出现这个...
现其他番剧也都无法播放
unblock_youku 插件出现同样16秒提示...

**Comment by GuoHM** [comment]
同樣問題

**Comment by BBBiggod** [comment]
想看佐贺结果16s......难受呀

**Comment by lolicon1997** [comment]
一样的问题，所有新番都看不了了

**Comment by yhm5311709** [comment]
新番都看不了（16秒提示），unblock是一样的情况
老番是可以的，看来B站针对海外用户进行了新番限制

**Comment by winters468** [comment]
难受，求教大神怎么回事，昨晚刚看佐贺，今天就这样了

**Comment by Hs096** [comment]
刚刚在看番  一集看完以后想看前几季的  然后发现就16s了  我还以为就一这一部番是这样 结果看了下所有番都是这样的

**Comment by ljf4103** [comment]
附议
坐标UK
全军覆没

**Comment by hl500** [comment]
同上 基本上番剧都不看了了。本来想把revisions追完的呜呜呜呜！！！
![capture](https://user-images.githubusercontent.com/46568864/50977897-3b70c280-14c1-11e9-9f43-7f1f1d209a4a.PNG)

**Comment by skyblue35** [comment]
https://www.bilibili.com/bangumi/play/ep250688
我表示永封的大会员不能用了么，其他的有的会员专用可以用，有的就显示不能播放，这个主楼的那个我倒是能看，为啥这个就显示不行……？直接登陆大会员的账号倒是没任何问题……？

**Comment by aruruwoo** [comment]
坐标UK 
昨天还能看，今天都打不开
我就想知道我也是花钱的大会员啊（凭什么海外就不能看咯，那我花的钱意义何在？

**Comment by Energy0124** [comment]
同樣問題
国家/地区： Hong Kong

**Comment by LittleNightmare** [comment]
同样的问题坐标CA
https://www.bilibili.com/bangumi/play/ss25739/?spm_id_from=333.334.b_62696c695f62616e67756d69.41

**Comment by Hs096** [comment]
地区日本  补一个日志
log: [解除B站区域限制 v7.1.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26286/?spm_id_from=333.334.b_62696c695f62616e67756d69.4
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"ShisukonHachiman","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1589299200000,"status":1,"type":2},"watch_progress":{"last_ep_id":259731,"last_ep_index":"9","last_time":4}}}
log: setAreaLimitSeason ss26286 true
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36

**Comment by Zorz4** [comment]
> 坐标UK
> 昨天还能看，今天都打不开
> 我就想知道我也是花钱的大会员啊（凭什么海外就不能看咯，那我花的钱意义何在？

今天刚储的年度会员，要是不能看是真的气:(

**Comment by sixteenmetre** [comment]
看隔壁的 issue，造成这种状况的原因好像是B站更变了playurl，安心等作者修改插件吧

**Comment by ipcjs** [comment]
7.2.1 版，改好了

**Comment by sixteenmetre** [comment]
> 7.2.1 版，改好了

辛苦了！

**Comment by hl500** [comment]
辛苦了! 已经可以看了! 非常感谢！

**Comment by pakasas** [comment]
log: [解除B站区域限制 v7.1.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26283
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Pakasas","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586966400000,"status":1,"type":2}}}
log: setAreaLimitSeason ss26283 false
log: balh_mode  =>  redirect
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36





一样，不知道怎么回事

**Comment by ipcjs** [comment]
@pakasas 更新版本呀(;¬_¬)

**Comment by skyduo** [comment]
表示升到7.2.2还是不行啊

**Comment by ipcjs** [comment]
不行，给log呀

**Comment by yhm5311709** [comment]
> 7.2.1 版，改好了

作者辛苦了，感谢有你！

**Comment by DeepTwilight** [comment]
> 7.2.1 版，改好了

作者幸苦了

**Comment by avegetables** [comment]
7.2.2版本又死亡了 坐標香港

**Comment by Hs096** [comment]
日本  无法加载视频
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep15499
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"ShisukonHachiman","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1589299200000,"status":1,"type":2},"watch_progress":{"last_ep_id":15499,"last_ep_index":"1","last_time":65}}}
log: setAreaLimitSeason ep15499 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=39629588&cid=69614000&qn=112&type=&otype=json&ep_id=15499&fnver=0&fnval=16&session=a886fd17c404bd66361592b20d8bdba5&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=69614000&player=1&qn=112&quality=&ts=1547395701&sign=1ba65d44fa116e8ef9a6d36c2e621bf1
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=39629588&cid=69614000&qn=112&type=&otype=json&ep_id=15499&fnver=0&fnval=16&session=a886fd17c404bd66361592b20d8bdba5&module=bangumi
