### ISSUE TITLE
所有正版番剧全部看不了

### ISSUE THREAD

**Issue by himesamarose** [ipcjs/bilibili-helper#332]
脚本问题：@ipcjs

## 描述
在B站番剧页面中打开所有正版番剧全部都是【非常抱歉  本视频可能由于以下原因导致无法正常播放】
换服务器也没用
在plus里面可以正常观看

- 问题网址：例：
![qq 20190111040011](https://user-images.githubusercontent.com/13597498/50993780-715f8680-1555-11e9-954a-1221b500e429.png)
https://www.bilibili.com/bangumi/play/ep250757/

## 日志

<details>
<summary>Verbose 日志</summary>

```
log: [解除B站区域限制 v7.1.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250757/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: ks3 flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"月之式-Rose","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1593705600000,"status":1,"type":2},"watch_progress":{"last_ep_id":250757,"last_ep_index":"13","last_time":0}}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

```
 
</details>

## 其他

1. 浏览器版本：Google Chrome 版本 71.0.3578.98（正式版本） （64 位）
2. 国家/地区：美国

**Comment by Yuureiyoo** [comment]
我这里也是一样

**Comment by himesamarose** [comment]
> 我这里也是一样

我是昨天准备看revisions就有的，然后我还以为是抽风还是什么，就没管，今天打开其他新番还是一样

**Comment by kirk4049** [comment]
+1

**Comment by MrWhoami** [comment]
发现同样问题，日志：
log: [解除B站区域限制 v7.1.9 (Violentmonkey)] run on: https://www.bilibili.com/bangumi/play/ss26283/?spm_id_from=333.334.b_62696c695f62616e67756d69.5
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"智慧的酒姬民","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1555776000000,"status":1,"type":2},"watch_progress":{"last_ep_id":259083,"last_ep_index":"1","last_time":-1}}}
log: setAreaLimitSeason ss26283 true
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by ipcjs** [comment]
先把脚本更新到最新版
