### ISSUE TITLE
拉取失敗 測速提示拉取失敗高ping 坐標香港 

### ISSUE THREAD

**Issue by avegetables** [ipcjs/bilibili-helper#334]
https://biliplus.ipcjs.top:
	初次连接：30169ms
	复用连接：30063ms
https://www.biliplus.com:
	初次连接：21844ms
	复用连接：164ms

**Comment by Hs096** [comment]
我也是 加载不出视频  本来之前回帖说了的  结果转头发现又能看了  就删了回复 然后换一个番 又用不了了
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep259083
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"ShisukonHachiman","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1589299200000,"status":1,"type":2},"watch_progress":{"last_ep_id":259083,"last_ep_index":"1","last_time":231}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=70942418&player=1&qn=112&quality=&ts=1547395982&sign=68f47516fbb261964fb351888ee96094
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=70942418&player=1&qn=112&quality=&ts=1547396014&sign=bd53587d14b2f6eb267c73e3ddabf86b
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=70942418&player=1&qn=112&quality=&ts=1547396085&sign=461bc67762dd942236d5f6b8c1a8a365
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi

**Comment by mystery00ou** [comment]
突然开不了biliplus。。。。

**Comment by ljf4103** [comment]
英国也是，已经更新到7.2.2了，难道是biliplus服务器炸了？

> 我也是 加载不出视频 本来之前回帖说了的 结果转头发现又能看了 就删了回复 然后换一个番 又用不了了
> log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep259083
> debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
> log: mode: redirect blocked_vip: server: https://www.biliplus.com upos_server: flv_prefer_ws: remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
> log: /x/web-interface/nav {"uname":"ShisukonHachiman","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
> log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1589299200000,"status":1,"type":2},"watch_progress":{"last_ep_id":259083,"last_ep_index":"1","last_time":231}}}
> log: player msg: 从代理服务器拉取视频地址中...
> debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi
> debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36
> log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
> log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
> debug: ajax: https://interface.bilibili.com/playurl?cid=70942418&player=1&qn=112&quality=&ts=1547395982&sign=68f47516fbb261964fb351888ee96094
> log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
> log: player msg: 从代理服务器拉取视频地址中...
> debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi
> log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
> log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
> debug: ajax: https://interface.bilibili.com/playurl?cid=70942418&player=1&qn=112&quality=&ts=1547396014&sign=bd53587d14b2f6eb267c73e3ddabf86b
> log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
> log: player msg: 从代理服务器拉取视频地址中...
> debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi
> log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
> log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
> debug: ajax: https://interface.bilibili.com/playurl?cid=70942418&player=1&qn=112&quality=&ts=1547396085&sign=461bc67762dd942236d5f6b8c1a8a365
> log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
> log: player msg: 从代理服务器拉取视频地址中...
> debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40391547&cid=70942418&qn=112&type=&otype=json&ep_id=259083&fnver=0&fnval=16&session=37608e1c158f1a39336ee43c41e7ea95&module=bangumi

**Comment by LUOCHENGyuki** [comment]
日本也炸了哦
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep259727
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"落城の雪季","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1592323200000,"status":1,"type":2},"watch_progress":{"last_ep_id":259726,"last_ep_index":"4","last_time":-1}}}
log: setAreaLimitSeason ep259727 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40338295&cid=70846152&qn=112&type=&otype=json&ep_id=259727&fnver=0&fnval=16&session=b8865210f0168b6ab3940e447c96f424&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=70846152&player=1&qn=112&quality=&ts=1547397054&sign=9bd592ad9c033b5eb384a193f3b22600
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40338295&cid=70846152&qn=112&type=&otype=json&ep_id=259727&fnver=0&fnval=16&session=b8865210f0168b6ab3940e447c96f424&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=70846152&player=1&qn=112&quality=&ts=1547397067&sign=f6e9b7ec0e8a34f729e51d7e4d0be6a6
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40338295&cid=70846152&qn=112&type=&otype=json&ep_id=259727&fnver=0&fnval=16&session=b8865210f0168b6ab3940e447c96f424&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=70846152&player=1&qn=112&quality=&ts=1547397071&sign=a3c06a5027336aa494b84cdcd21f0531
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3664.3 Safari/537.36
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40338295&cid=70846152&qn=112&type=&otype=json&ep_id=259727&fnver=0&fnval=16&session=b8865210f0168b6ab3940e447c96f424&module=bangumi

**Comment by Pyclone** [comment]
坐标美东 同样拉取失败 BilibiliPlus打不开

**Comment by Pyclone** [comment]
美东表示已经好了

**Comment by Hs096** [comment]
日本OK  应该是B+服务器没问题了

**Comment by LUOCHENGyuki** [comment]
我也好了

**Comment by mystery00ou** [comment]
马来西亚 这边也ok了
