### ISSUE TITLE
两个服务器都不能拉视频

### ISSUE THREAD

**Issue by ghost** [ipcjs/bilibili-helper#336]
脚本问题：@ipcjs

## 描述

- 问题网址：
两个服务器都是挂的

## 日志
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep92685
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"アーキッド","isLogin":true,"level":2,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":0,"status":0,"type":0},"watch_progress":{"last_ep_id":92685,"last_ep_index":"12","last_time":433}}}
log: setAreaLimitSeason ep92685 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=6403601&cid=10991780&qn=64&type=&otype=json&ep_id=92685&fnver=0&fnval=16&session=6d318a29d5c43c12c17dcbaa43bf2588&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：chrome
2. 国家/地区：wuhan-china

**Comment by David20210** [comment]
同上，兩個都是掛的

**Comment by rrrrin** [comment]
我也。。。授权页面也有问题

**Comment by MarksonChen** [comment]
惊了，我也是。

**Comment by MarksonChen** [comment]
昨天还能看的番，今天就不行了，买了大会员也不行。
![image](https://user-images.githubusercontent.com/46666959/51099108-a05b3f80-1783-11e9-8064-2765a86d3962.png)
