### ISSUE TITLE
拉取视频地址失败=>服务器间歇性爆炸

### ISSUE THREAD

**Issue by rrrrin** [ipcjs/bilibili-helper#337]
脚本问题：@ipcjs

## 描述

今天早些时候看还没问题
重新授权也不行，只会显示 www.biliplus.com took too long to respond.

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by 513449525** [comment]
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183809
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"JIN_坷垃","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":0,"status":0,"type":0},"watch_progress":{"last_ep_id":183808,"last_ep_index":"10","last_time":-1}}}
log: setAreaLimitSeason ep183809 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=21174685&cid=34768082&qn=80&type=&otype=json&ep_id=183809&fnver=0&fnval=16&session=68c6a564a4a9db3bf0c9329c8ba4786b&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=34768082&player=1&qn=80&quality=&ts=1547437433&sign=ab7b0b6d92d22e83d3760f54707604f5
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=21174685&cid=34768082&qn=80&type=&otype=json&ep_id=183809&fnver=0&fnval=16&session=68c6a564a4a9db3bf0c9329c8ba4786b&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=34768082&player=1&qn=80&quality=&ts=1547437445&sign=2b7d2d997cf4e1c6c09ba84d2151e544
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=21174685&cid=34768082&qn=80&type=&otype=json&ep_id=183809&fnver=0&fnval=16&session=68c6a564a4a9db3bf0c9329c8ba4786b&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=34768082&player=1&qn=80&quality=&ts=1547437457&sign=e5cb652c2857eb2ceede6bee31fec6e6
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=21174685&cid=34768082&qn=80&type=&otype=json&ep_id=183809&fnver=0&fnval=16&session=68c6a564a4a9db3bf0c9329c8ba4786b&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by Chaos0482** [comment]
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250549
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"伪物律","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1553788800000,"status":1,"type":1},"watch_progress":{"last_ep_id":250548,"last_ep_index":"13","last_time":-1}}}
log: setAreaLimitSeason ep250549 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40551058&cid=71273572&qn=80&type=&otype=json&ep_id=250549&fnver=0&fnval=16&session=0686021e0bbb320447953d12eda43f08&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=71273572&player=1&qn=80&quality=&ts=1547438656&sign=ea75ab777ff71fa8682d27b83e72649e
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40551058&cid=71273572&qn=80&type=&otype=json&ep_id=250549&fnver=0&fnval=16&session=0686021e0bbb320447953d12eda43f08&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.
坐标 日本
视频拉取失败 已经是7.2.2了

**Comment by mystery00ou** [comment]
B+ 服务器又炸了？？

**Comment by zhendian** [comment]
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep259700/?spm_id_from=333.334.b_62696c695f62616e67756d69.8
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"严严明","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1555430400000,"status":1,"type":2},"watch_progress":{"last_ep_id":259700,"last_ep_index":"2","last_time":0}}}
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=40719691&cid=71519580&qn=64&type=&otype=json&ep_id=259700&fnver=0&fnval=16&session=e90ca22c1d869fce523b5299fc66a8e0&module=bangumi
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by hang333** [comment]
> B+ 服务器又炸了？？

炸了， 到现在仍然未回复

**Comment by MooerFoes** [comment]
biliplus主页进不去了，应该是服务器炸了吧……难得想用一下结果不行，哭哭

**Comment by pakasas** [comment]
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26295/?spm_id_from=333.334.b_62696c695f62616e67756d69.7
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Pakasas","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586966400000,"status":1,"type":2}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=40737750&cid=71551474&qn=112&type=&otype=json&ep_id=259830&fnver=0&fnval=16&session=79c57d7cc89cc22496a638fde236e333&module=bangumi
error: >>area limit
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=40737750&cid=71551474&qn=16&type=&otype=json&ep_id=259830&fnver=0&fnval=16&session=79c57d7cc89cc22496a638fde236e333&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by ljf4103** [comment]
今天又炸了

**Comment by rrrrin** [comment]
又炸了。。。最近到底什么情况

**Comment by David20210** [comment]
又炸了...

**Comment by David20210** [comment]
又炸了
