### ISSUE TITLE
拉取视频地址失败，代理服务器无法访问

### ISSUE THREAD

**Issue by MWang94** [ipcjs/bilibili-helper#339]
脚本问题：@ipcjs

## 描述

- 问题网址：https://www.bilibili.com/bangumi/play/ep251095

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep251095
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"secret821","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1556035200000,"status":1,"type":2},"watch_progress":{"last_ep_id":251094,"last_ep_index":"5","last_time":1253}}}
log: setAreaLimitSeason ep251095 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=35965244&cid=63129167&qn=64&type=&otype=json&ep_id=251095&fnver=0&fnval=16&session=10c1d1a33d1ffaa94e314e15c5385cfb&module=bangumi
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=63129167&player=1&qn=64&quality=&ts=1548363673&sign=6ac730903990c8d358d2fc5e8214e431
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=35965244&cid=63129167&qn=64&type=&otype=json&ep_id=251095&fnver=0&fnval=16&session=10c1d1a33d1ffaa94e314e15c5385cfb&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=63129167&player=1&qn=64&quality=&ts=1548363750&sign=938ae096b4f0fe8907d183f747add7dd
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=35965244&cid=63129167&qn=64&type=&otype=json&ep_id=251095&fnver=0&fnval=16&session=10c1d1a33d1ffaa94e314e15c5385cfb&module=bangumi``
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：Chrome Version 71.0.3578.98
2. 国家/地区：美国

**Comment by saeVirginia** [comment]
我也是 代理服務器無法訪問

**Comment by Paul980416** [comment]
+1

**Comment by skyduo** [comment]
+1

**Comment by bbanni** [comment]
我也是。目前使用的是Chrome浏览器，视屏无法显示那个界面显示“获取番剧URL”后就变成“error”了

**Comment by pakasas** [comment]
log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25851/?spm_id_from=333.334.b_62696c695f62616e67756d69.7
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"Pakasas","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586966400000,"status":1,"type":2}}}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=33246885&cid=58192277&qn=116&type=&otype=json&ep_id=251541&fnver=0&fnval=16&session=be5c0a8ab2c639cfe56337fe18d6215e&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=58192277&player=1&qn=116&quality=&ts=1548567114&sign=6cf519ad08eb32bd631bf8b297d7b4ce
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=33246885&cid=58192277&qn=116&type=&otype=json&ep_id=251541&fnver=0&fnval=16&session=be5c0a8ab2c639cfe56337fe18d6215e&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=58192277&player=1&qn=116&quality=&ts=1548567117&sign=b620ab83fa516b58cb878a9171f8c469
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
