### ISSUE TITLE
代理服务器爆炸了

### ISSUE THREAD

**Issue by mayakovsji** [ipcjs/bilibili-helper#341]
脚本问题：@ipcjs

## 描述

代理服务器似乎爆炸了，502 bad gateway

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 log: [解除B站区域限制 v7.2.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep103137
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server: oss flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":0,"status":0,"type":0},"watch_progress":{"last_ep_id":103137,"last_ep_index":"8","last_time":1}}}
log: setAreaLimitSeason ep103137 true
log: /x/web-interface/nav {"uname":"毒瘤2号c","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=9485931&cid=15679867&qn=32&type=&otype=json&ep_id=103137&fnver=0&fnval=16&session=48648516fc4a9aed7d852b221a23768d&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=15679867&player=1&qn=32&quality=&ts=1548586430&sign=93315a03270323b662b52096c6d9a3c0
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=9485931&cid=15679867&qn=32&type=&otype=json&ep_id=103137&fnver=0&fnval=16&session=48648516fc4a9aed7d852b221a23768d&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=15679867&player=1&qn=32&quality=&ts=1548586431&sign=b727db0986cef3114a67be7cc1b576c7
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=9485931&cid=15679867&qn=32&type=&otype=json&ep_id=103137&fnver=0&fnval=16&session=48648516fc4a9aed7d852b221a23768d&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=15679867&player=1&qn=32&quality=&ts=1548586439&sign=069caf6751cb9e17013f8149ecbfa587
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=9485931&cid=15679867&qn=32&type=&otype=json&ep_id=103137&fnver=0&fnval=16&session=48648516fc4a9aed7d852b221a23768d&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=15679867&player=1&qn=32&quality=&ts=1548586445&sign=f12fc3d7bd6a2afed2c244bb2b859dc2
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
</details>

## 其他

1. 浏览器版本：chrome 71.0.3578.98（正式版本） （64 位）
2. 国家/地区：中国大陆

**Comment by Yolice** [comment]
日本这里好像炸了
