### ISSUE TITLE
脚本在某些页面无效，直接显示404页面

### ISSUE THREAD

**Issue by ShenChenrui** [ipcjs/bilibili-helper#344]
脚本问题：@ipcjs

## 描述
脚本失效，无法拉取视频

- 问题网址：
https://search.bilibili.com/all?keyword=%E8%BF%9B%E5%87%BB%E7%9A%84%E5%B7%A8%E4%BA%BA%E7%AC%AC%E4%B8%89%E5%AD%A3&from_source=banner_search&spm_id_from=333.334.b_62616e6e65725f6c696e6b.1

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
直接404 `Σ(ﾟдﾟ;)`
看起来要手动创建播放器。。。挺麻烦_(:3」∠)_

**Comment by ipcjs** [comment]
这个页面似乎没问题了？？

**Comment by ipcjs** [comment]
哦，我懂了
老版播放器不会直接404，要看的话，先直接切成老版吧

**Comment by ipcjs** [comment]
先切换回旧版用吧
a448d4cb2192015713979f3536d8d6ee80e97d41

**Comment by ipcjs** [comment]
切换回旧版按钮，改成只对当前这次刷新有效`(°∀°)ﾉ`
b7a372e0a2699a2beca7fe851ee87b2b631b7b83

**Comment by ipcjs** [comment]
通过临时切换回旧版的方式，支持播放
be5a4985dfd7ea67b21383228d43ff15bfe2e23f

**Comment by chaserstrong** [comment]
@ipcjs  7.9.5版本改了这段脚本，仍旧不能打开进击的巨人2
https://www.bilibili.com/bangumi/play/ep103736
