### ISSUE TITLE
仅自动跳转模式？

### ISSUE THREAD

**Issue by tleydxdy** [ipcjs/bilibili-helper#345]
脚本问题：@ipcjs

## 描述

能否开发一个仅自动跳转的脚本？因为我发现只代理api.bilibili.com就能看番了好像。

顺便品酒的自动跳转好像挂了

- 问题网址：https://www.bilibili.com/bangumi/play/ep115076

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
品酒看不了是B站改版的，见 #344

**Comment by ipcjs** [comment]
我想起来了，跳转功能其实上是从别的脚本里面移植过来的，你可以试试原版还能不能用：
https://greasyfork.org/zh-CN/scripts/29151-%E6%88%91%E5%B0%B1%E6%98%AF%E8%A6%81%E8%B7%B3%E8%BD%89-b%E7%AB%99%E7%95%AA%E5%8A%87%E6%8A%95%E7%A8%BF%E9%A0%81%E8%B7%B3%E8%BD%89%E5%8E%BB%E7%95%AA%E5%8A%87%E9%A0%81
