### ISSUE TITLE
总是黑洞

### ISSUE THREAD

**Issue by 994478084** [ipcjs/bilibili-helper#347]
log: [解除B站区域限制 v7.3.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183812
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1571068800000,"status":1,"type":2},"watch_progress":{"last_ep_id":183812,"last_ep_index":"14","last_time":5}}}
log: /x/web-interface/nav {"uname":"无语wyh","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=22086569&cid=36514990&qn=0&type=&otype=json&ep_id=183812&fnver=0&fnval=16&session=fd29fad4c7f65aa528d80174a8600753&module=bangumi
debug: userAgent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 YaBrowser/18.11.1.963.00 Safari/537.36

**Comment by ipcjs** [comment]
登录代理服务器：https://www.biliplus.com
