### ISSUE TITLE
旧番《希德尼娅的骑士》完全不能看

### ISSUE THREAD

**Issue by mystery00ou** [ipcjs/bilibili-helper#348]
脚本问题：@ipcjs

## 描述

看新番完全没问题能满速缓冲！但是我想重温《希德尼娅的骑士第一季》时就完全不能缓冲（超慢的缓冲速度）！

- 问题网址：https://www.bilibili.com/bangumi/play/ep80171  （其实就是整部出问题）

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Chrome 72.0.3626.96
2. 国家/地区：Malaysia 马来西亚

**Comment by ipcjs** [comment]
缓冲速度慢？试试：https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.md#%E6%92%AD%E6%94%BE%E5%8D%A1%E9%A1%BF%E9%99%90%E9%80%9F200kb

**Comment by mystery00ou** [comment]
> 缓冲速度慢？试试：https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.md#%E6%92%AD%E6%94%BE%E5%8D%A1%E9%A1%BF%E9%99%90%E9%80%9F200kb

试过了.....没用！我还甚至把代理服务器从B+换成土豆的也没用
