### ISSUE TITLE
拉取視頻失敗

### ISSUE THREAD

**Issue by asd640035** [ipcjs/bilibili-helper#349]
## 描述

拉取視頻失敗

- 问题网址：https://www.bilibili.com/bangumi/play/ep262038

## 日志

<details>
<summary>Verbose 日志</summary>

```
log: [解除B站区域限制 v7.3.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep262038
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"終末的愚者","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1593360000000,"status":1,"type":2},"watch_progress":{"last_ep_id":262000,"last_ep_index":"第1话","last_time":3375}}}
log: setAreaLimitSeason ep262038 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=42014725&cid=73762222&qn=80&type=&otype=json&ep_id=262038&fnver=0&fnval=16&session=91f36a2c8fe0a11024500044ce12478d
error: {"code":10004,"result":"error","message":"Video is hidden."}
log: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\"}","code":10004}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=73762222&player=1&qn=80&quality=&ts=1550210658&sign=bac003a5e864623bb73e328312f1d22f
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=42014725&cid=73762222&qn=80&type=&otype=json&ep_id=262038&fnver=0&fnval=16&session=91f36a2c8fe0a11024500044ce12478d
error: {"code":10004,"result":"error","message":"Video is hidden."}
log: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\"}","code":10004}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=73762222&player=1&qn=80&quality=&ts=1550210660&sign=0e95963fe250c0e8b01d4f4aba3d111a
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=42014725&cid=73762222&qn=80&type=&otype=json&ep_id=262038&fnver=0&fnval=16&session=91f36a2c8fe0a11024500044ce12478d
error: {"code":10004,"result":"error","message":"Video is hidden."}
log: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\"}","code":10004}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=73762222&player=1&qn=80&quality=&ts=1550210665&sign=f8d4f6b7899a34612b80afc6bdad3071
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
```
 
</details>

## 其他

1. 浏览器版本：7.3.1
2. 国家/地区：台灣

**Comment by wolfgang160** [comment]
对对对，电影都不能看了

**Comment by wolfgang160** [comment]
一些番剧，动漫可以看，放映厅的有一些电影看不了，尤其是新电影

**Comment by autapomorphy** [comment]
应该是那些付费观看的看不了吧

**Comment by asd640035** [comment]
我有大會員，會員專享的動畫可看，電影卻看不了

**Comment by ipcjs** [comment]
你这个链接，7.3.2版改好了
其他人，不能播的视频，能给个链接吗？

**Comment by Geliv** [comment]
电影，神奇动物：https://www.bilibili.com/bangumi/play/ss26590 看不了

**Comment by CyclonicPinna** [comment]
上周开始（7.3.1版时）biliplus.com服务器就一直拉取视频失败，切换ipcjs.top可以正常播放番剧。从昨天开始（已更新7.3.2）两个服务器都提示拉取视频失败了。所有番剧都无法正常播放。

另外还有一些状况不知是否相关，包括：1、biliplus.com原本可以正常使用时测速显示的延迟要远远低于ipcjs.top，所以一直用的biliplus.com，但自从上周拉取视频失败起两个服务器的延迟就颠倒了，ipcjs.top低于biliplus.com。2、尝试替换upos视频服务器会出现保存错误（昨天开始，上周没有试过，更早之前是正常的）。3、账号授权后弹出错误页面（灰屏中间一个 :( 标志，没有其他提示），也是昨天开始，上周没有试过，更早之前可以正常授权。

log: [解除B站区域限制 v7.3.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26284/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function (a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"手动打码","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1595001600000,"status":1,"type":2}}}
log: setAreaLimitSeason ss26284 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
log: season_type: 0
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=39745777&cid=69913912&qn=32&type=&otype=json&ep_id=259674&fnver=0&fnval=16&session=02b2e65f1e579cb821170a3a96cf500e&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=69913912&player=1&qn=32&quality=&ts=1550694956&sign=2174cd0a5e57a0b8661c7d3150075290
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
log: season_type: 0
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=39745777&cid=69913912&qn=32&type=&otype=json&ep_id=259674&fnver=0&fnval=16&session=02b2e65f1e579cb821170a3a96cf500e&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=69913912&player=1&qn=32&quality=&ts=1550694958&sign=d627fd6a8d439c53da9726466ff41236
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
log: season_type: 0
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=39745777&cid=69913912&qn=32&type=&otype=json&ep_id=259674&fnver=0&fnval=16&session=02b2e65f1e579cb821170a3a96cf500e&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=69913912&player=1&qn=32&quality=&ts=1550694963&sign=21660e76035e7c2f04b3fcdbeabb7871
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
log: season_type: 0
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=39745777&cid=69913912&qn=32&type=&otype=json&ep_id=259674&fnver=0&fnval=16&session=02b2e65f1e579cb821170a3a96cf500e&module=bangumi
log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
debug: ajax: https://interface.bilibili.com/playurl?cid=69913912&player=1&qn=32&quality=&ts=1550694966&sign=8277180caa77c5f87111f42eed3e976d
log: player msg: 服务器错误: {"result":"error","code":10004,"message":"Video is hidden."}
log: balh_remove_pre_ad  =>  
debug: userAgent Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by CyclonicPinna** [comment]
上周（7.3.1版本时）开始biliplus.com服务器一直显示拉取视频失败，切换ipcjs.top后可以正常使用。从昨天开始（已更新7.3.2）两个服务器都显示拉取视频失败，所有番剧都无法播放（包括新番和其他需要解除限制的番剧）。

还有一些其他状况不知是否相关，包括：1、原本biliplus.com可以正常使用时测速得到的延迟要远低于ipcjs.top，但自从上周biliplus.com拉取视频失败以后，测速结果颠倒了，ipcjs.top的延迟低于biliplus.com（同网络同浏览器）。2、在拉取视频失败的状态下尝试替换upos视频服务器会显示保存出错（昨天开始，上周没有试过，以前能够播放视频时替换是正常的）。3、在拉取视频失败的状态下尝试帐号授权会弹出错误页面（灰屏中间一个 :( 的符号，没有其他显示），也是从昨天开始，上周没有试过，以前能够播放视频时是正常的。

**Comment by ipcjs** [comment]
@CyclonicPinna ipcjs.top前两天证书过期了，刚renew了下`(-_-#)`

**Comment by ipcjs** [comment]
> 电影，神奇动物：https://www.bilibili.com/bangumi/play/ss26590 看不了

@Geliv 这个可能要@esterTion，试了下，biliplus里面也获取不了完整视频

**Comment by esterTion** [comment]
这是付费电影，大会员有个p用

**Comment by CyclonicPinna** [comment]
@ipcjs 感谢回复，刚试了下ipcjs.top可以正常使用，biliplus.com还是拉取视频失败。

**Comment by ipcjs** [comment]
😅，没意义

**Comment by ipcjs** [comment]
😅，没注意

**Comment by Geliv** [comment]
@ipcjs 感谢回复，付费页面是无法拉取吗？😂

**Comment by asd640035** [comment]
有大會員，一堆會員專享的電影也無法拉取
所以跟是不是付費電影無關吧(?

**Comment by ipcjs** [comment]
2bfd974ef55974e3f459676552e2565c3164b1f5

@esterTion 
貌似用`season_type`判断是否要添加`module=bangumi`并不准确？
我现在只能改成获取地址失败，就添加个`module=bangumi`重试一次`(-_-#)`
示例：https://www.bilibili.com/bangumi/play/ep262799

@asd640035 
7.3.3版，试试？

**Comment by esterTion** [comment]
> 看到邮件了然后忘记测试和回复

你可以直接在参数里加season_type，这个兼容我很早就加过了，虽然后台本质也是相当于我帮你加了个module=bangumi

```PHP
if (isset($_GET['season_type'])) $bangumi = 1;
```

是不是有的season_type不算bangumi来的？

**Comment by ipcjs** [comment]
有就是说，只要有`season_type`，就算`bangumi`？
b812a684c8681824cd3ed91ab0e03c5bbecf3b75

**Comment by esterTion** [comment]
我不知道啊

**Comment by ipcjs** [comment]
🤪，就这样吧，有问题再改
