### ISSUE TITLE
[feature request] 利用biliplus观看大会员抢先番剧

### ISSUE THREAD

**Issue by ZeppLu** [ipcjs/bilibili-helper#350]
脚本问题：@ipcjs

## 描述
（一个建议，不算真正的问题）

https://www.biliplus.com 可以用B站账号登录，如果是五级或以上的话，还能访问服务器上转存好的大会员提前看视频。我的一个想法是，能不能在B站把视频源地址换成biliplus转存的，这样就算是突破大会员提前看的限制了，当然这功能只对五级或以上的用户开放

![image](https://user-images.githubusercontent.com/17007549/52894378-87f79e00-31e3-11e9-86eb-870ed72fb50e.png)

**Comment by ipcjs** [comment]
脚本只做解除区域限制，不做破解大会员。

**Comment by ipcjs** [comment]
你向别人借个大会员帐号，再在biliplus登录，然后打开“被永封的大会员”选项，不就是这个效果了。`(;¬_¬)`

**Comment by ipcjs** [comment]
你的想法的另一个问题是，biliplus转存视频的下载速度非常慢，在线播放会超卡

**Comment by ZeppLu** [comment]
这个功能确实会触碰到B站的利益，比较敏感。
不过转存视频的下载速度可能与网络环境有关，我记得用校园网通过代理来下载，速度还是可以接受的，有2MB/s左右，不过现在在家就非常慢

**Comment by TTTPOB** [comment]
被永封的大会员功能今天似乎出了问题，
这是报错
## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"敏感信息脱敏处理\",\"mid\":6273455,\"level\":5,\"vip_expire\":0}}","code":-404}

可以考虑进行如下尝试:
1. 多刷新几下页面
2. 进入设置页面更换代理服务器
3. 耐心等待代理服务器端修复问题
