### ISSUE TITLE
动画番剧可以看，电影不能看

### ISSUE THREAD

**Issue by yhm5311709** [ipcjs/bilibili-helper#352]
请问该脚本是不是不支持电影？怎么切换代理也没用。谢谢！

![1](https://user-images.githubusercontent.com/46564381/53239219-cf4bc600-36de-11e9-8ba0-e193a3de66d2.PNG)

![2](https://user-images.githubusercontent.com/46564381/53239220-cfe45c80-36de-11e9-8e52-19bf8b2971c5.PNG)

**Comment by ipcjs** [comment]
url？
