### ISSUE TITLE
部分视频只能看6分钟预览版

### ISSUE THREAD

**Issue by xhzz161** [ipcjs/bilibili-helper#355]
描述
如题目 部分需要大会员才能观看的电影番剧
在解除区域限制后只能观看6分钟预览版 
也就是说 区域限制解锁成功 但是在已有大会员的情况下无法正常观看

PS：尝试了FireFox 使用同样的扩展 没有任何问题 好像只有chrome有

问题网址
https://www.bilibili.com/bangumi/play/ep264225/
PS：比如最新的白蛇就不能看完整版 只有6分钟

日志
导出日志的操作不会...

其他
浏览器版本：72.0.3626.96
国家/地区：美国

**Comment by ipcjs** [comment]
为什么有些人说firefox有问题，有些人说chrome有问题`(-_-#)`
#356
