### ISSUE TITLE
付費會員限定的都看不了,直接出錯(有用大會員授權)

### ISSUE THREAD

**Issue by brianchu14** [ipcjs/bilibili-helper#359]
脚本问题：@ipcjs

## 描述
我在biliplus 不用小幫手調畫質能看,在官網上脚本看就出錯了,
腳本有用大會員授權

- 问题网址：https://www.bilibili.com/bangumi/play/ss25739/

## 日志
log: [解除B站区域限制 v7.3.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25739/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"brianchu14","isLogin":true,"level":3,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1570464000000,"status":1,"type":2},"watch_progress":{"last_ep_id":250483,"last_ep_index":"24","last_time":0}}}
log: setAreaLimitSeason ss25739 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=46653684&cid=81727084&qn=80&type=&otype=json&ep_id=250483&fnver=0&fnval=16&session=6fea39410e113309c1b56376986694b9&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

1. 浏览器版本：Google Chrome 目前是最新版本
版本 73.0.3683.86 (正式版本) (64 位元)
2. 国家/地区：澳門

**Comment by ipcjs** [comment]
在biliplus登录帐号了？

**Comment by brianchu14** [comment]
有
