### ISSUE TITLE
服务器返回异常

### ISSUE THREAD

**Issue by UncleKan** [ipcjs/bilibili-helper#36]
## 描述
我的chrome在使用这个脚本之后，在html5格式下除了新番和部分视频之外，加载视频内容都会失败，第一次返回服务器返回异常 ([NetworkError] HttpStatusCodeInvalid: 466)， 然后它自己尝试第二次则会返回无法连接服务器或者服务器返回异常 ([NetworkError] Exception: 3104 Failed to fetch)。

尝试 1：
转换成flash格式，视频可以播放

尝试 2:
使用edge播放html5视频，视频可以播放

尝试 3：
清空chrome的cookie再返回bilibili播放html5视频，视频播放失败

尝试 4：
卸载chrome并且不保留用户信息再重新安装，再次打开bilibili播放同一视频，视频播放失败

## 日志

```
不知道该放哪些日志= =
```
![capture](https://user-images.githubusercontent.com/35414710/34913059-73f1fd2c-f8a7-11e7-8241-8d15ab7739c8.JPG)

## 其他

1. 浏览器版本：Google Chrome 63.0.3239.132
2. 国家/地区：加拿大 Canada

**Comment by ipcjs** [comment]
别光瞎jb试，看脚本的帮助说明呀

**Comment by ipcjs** [comment]
帐号授权一下

**Comment by ipcjs** [comment]
你用脚本的“复制日志”功能，把日志复制过来，看下

**Comment by ipcjs** [comment]
还有你记得看下邮箱，GitHub的通知是会有邮件提醒的，这样可以交流的快一点
