### ISSUE TITLE
新版番剧页面不能用

### ISSUE THREAD

**Issue by wysjd** [ipcjs/bilibili-helper#360]
脚本问题：@ipcjs

## 描述

脚本在谷歌浏览器中直接出错，不能用。
- 问题网址：https://www.bilibili.com/bangumi/play/ep234669?from=search&seid=8188188027326580041

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```没有图标，直接出错。
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->
![捕获](https://user-images.githubusercontent.com/48590065/54980484-d0735a00-4fe0-11e9-8bdd-0189de586222.PNG)


## 

1. 浏览器版本：Google Chrome 最新版本
版本 73.0.3683.86（正式版本） （64 位）
2. 国家/地区：中国大陆

**Comment by DonJose2002** [comment]
实测可以用
b站似乎弄了一个新的番剧网页系统（虽然没弄明白和老版有什么区别）页面右下角有“返回老版（差不多是这个）”的选项，就可以正常使用脚本功能了。如果不可以，尝试切换代理服务器或upos服务器，多试几次就行

**Comment by ipcjs** [comment]
如二楼所说，脚本没有适配B站的新版番剧页面，但提供了一个自动临时切换成旧版番剧页面的机制。
这个机制，不知道什么原因，在你那里没生效。
你可以手动切换成旧版播放器

**Comment by ville401578112** [comment]
点进楼主发的网址播放的非常顺畅..巨人无论哪一集点进去播放都很顺畅..然后试了一下只要是仅限港澳台的都非常顺畅其他的就在一直黑屏播放不了..

**Comment by HYY1996** [comment]
等等，我也发现了，楼主这部进击的巨人可以顺畅播放，但是路人超能100 https://www.bilibili.com/bangumi/play/ep92395
鬼灭之刃 https://www.bilibili.com/bangumi/play/ss26801
这两部都打不开，路人超能100 I 和II 一直显示无法连接服务器，鬼灭之刃一直黑屏，有大会员，且已授权，biliplus可以上的去，切换土豆服也是一样的情况

**Comment by Lynx1091** [comment]
我这边也是很多番剧打不开，更换了服务器也没有用。打不开的大多是新番。@ipcjs
debug: [解除B站区域限制 v7.8.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep114687?from=search&seid=6786443800787367804
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: /x/web-interface/nav {"uname":"BeeKJ","isLogin":true,"level":3,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1565539200000,"status":0,"type":1},"watch_progress":{"last_ep_id":114687,"last_ep_index":"1","last_time":0}}}
debug: setAreaLimitSeason ep114687 true
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 4
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=15138420&cid=46481703&qn=0&type=&otype=json&ep_id=114687&fnver=0&fnval=16&session=afed88f46101d11d213d45a4b3903fbf&module=bangumi&balh_ajax=1
debug: /x/web-interface/nav {"uname":"BeeKJ","isLogin":true,"level":3,"vipType":1,"vipStatus":0,"isFromReport":true}
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"BeeKJ","mid":322884370,"level":3,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"BeeKJ\",\"mid\":322884370,\"level\":3,\"vip_expire\":0}}","code":-404}
info: player msg: 尝试使用非番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=15138420&cid=46481703&qn=0&type=&otype=json&ep_id=114687&fnver=0&fnval=16&session=afed88f46101d11d213d45a4b3903fbf&balh_ajax=1
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"BeeKJ","mid":322884370,"level":3,"vip_expire":0}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by fallingsure** [comment]
好久没找到设置图标到底说的是啥，为啥不放个截图呢，没看到就可以安心去找浏览器的问题了
![image](https://user-images.githubusercontent.com/85953217/122085157-0658bf00-ce35-11eb-9d7a-3d88a45060ce.png)
![image](https://user-images.githubusercontent.com/85953217/122085585-70716400-ce35-11eb-920c-18444fe35358.png)
