### ISSUE TITLE
Chrome更新后无法加载新番视频

### ISSUE THREAD

**Issue by zhenquanma** [ipcjs/bilibili-helper#362]
具体日志如下：
log: [解除B站区域限制 v7.3.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26284/?spm_id_from=333.334.b_62696c695f62616e67756d69.11
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"堕天圣白猫","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1562428800000,"status":1,"type":2},"watch_progress":{"last_ep_id":259685,"last_ep_index":"12","last_time":0}}}
log: setAreaLimitSeason ss26284 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=47481961&cid=83164535&qn=112&type=&otype=json&ep_id=259685&fnver=0&fnval=16&session=b742ecbc149dabb79b6a41f9747aeb70&module=bangumi
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=47481961&cid=83164535&qn=112&type=&otype=json&ep_id=259685&module=bangumi
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=47481961&cid=83164535&qn=16&type=&otype=json&ep_id=259685&module=bangumi
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

Console的截图：
<img width="1101" alt="Screen Shot 2019-03-27 at 3 45 25 PM" src="https://user-images.githubusercontent.com/19522389/55107300-607bd700-50a7-11e9-85f6-3441e126b495.png">

**Comment by esterTion** [comment]
已处理，b站新加了akamai cdn，不能和其他cdn一样直接域名替换
