### ISSUE TITLE
B站chrome浏览器无法work

### ISSUE THREAD

**Issue by sun8608** [ipcjs/bilibili-helper#363]
如题，已经按照之前的instruction update了浏览器和Tampermonkey extension到了latest version（chrome Version 73.0.3683.86 (Official Build) (64-bit)，Tampermonkey version 4.8）， 但是依旧看不到那个设置的地球图标，所有有区域限制的视频现在都无法观看了，重复安装Tampermonkey 也没有用

**Comment by ipcjs** [comment]
视频播放页面的设置图标，因为一个bug，被我删了
现在只有概况页面有设置图标：https://www.bilibili.com/bangumi/media/md4762734/
无法观看。。。那就只能看控制台log了，截个图看看？

**Comment by ville401578112** [comment]
我也是！都是最新版本了。。美东时间3/28晚上10点11分~3/29白天一直都在b站看滴很欢（看脚本最新设置是在美东时间3/28晚上10点04..）但是今天再上B站视频就载不出来（没有提示是区域的问题 就是黑屏载不出来..）

**Comment by ygycallmeaAlbet** [comment]
好像是bilibili把播放的地址改成https://www.bilibili.com/bangumi/play/epxxxxxxx（xxx是原来的av号），脚本检测不到这是b站的页面无法自动启动，我所处的北美地区已经好几天看不了了……

**Comment by ygycallmeaAlbet** [comment]
啊好像不是……但是我有两台电脑，pc脚本无法自动加载，但是mac就可以……都是chrome

**Comment by ygycallmeaAlbet** [comment]
现在mac也用不了了，提示信息
![Screen Shot 2019-04-04 at 1 16 24 AM](https://user-images.githubusercontent.com/31736066/55531199-4d54a280-5677-11e9-9318-52a38410f932.png)

**Comment by zwan0202** [comment]
升级了 Chrome 后 Tampermonkey 就显示 Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others! 
重新安装 Tampermonkey 后所有有区域限制的视频都无法观看了, 重新安装 Chrome 也没有用
![Capture](https://user-images.githubusercontent.com/37109314/55532020-12468380-56f8-11e9-9a26-5b1801e63405.PNG)

**Comment by TomoyaSpencer** [comment]
> 升级了 Chrome 后 Tampermonkey 就显示 Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!
> 重新安装 Tampermonkey 后所有有区域限制的视频都无法观看了, 重新安装 Chrome 也没有用

如果我沒理解錯，biliplus被B站搞了、整個站都沒了。只要之前設置為使用biliplus的服務器，就無法成功解除區域限制。
目前貌似可以通過改為使用另一個服務器來解決。

**Comment by ville401578112** [comment]
> 现在mac也用不了了，提示信息
> ![Screen Shot 2019-04-04 at 1 16 24 AM](https://user-images.githubusercontent.com/31736066/55531199-4d54a280-5677-11e9-9318-52a38410f932.png)

看港澳台限定的有问题吗（我之前开了个post也是加载视频内容不行）但是港澳台限定的就很顺畅

**Comment by ville401578112** [comment]
> > 升级了 Chrome 后 Tampermonkey 就显示 Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!
> > 重新安装 Tampermonkey 后所有有区域限制的视频都无法观看了, 重新安装 Chrome 也没有用
> 
> 如果我沒理解錯，biliplus被B站搞了、整個站都沒了。只要之前設置為使用biliplus的服務器，就無法成功解除區域限制。
> 目前貌似可以通過改為使用另一個服務器來解決。

emmm我之前试了貌似没用啊..

**Comment by ville401578112** [comment]
> > 升级了 Chrome 后 Tampermonkey 就显示 Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!
> > 重新安装 Tampermonkey 后所有有区域限制的视频都无法观看了, 重新安装 Chrome 也没有用
> 
> 如果我沒理解錯，biliplus被B站搞了、整個站都沒了。只要之前設置為使用biliplus的服務器，就無法成功解除區域限制。
> 目前貌似可以通過改為使用另一個服務器來解決。

！刚又试了一下可以用了..也看到脚本编写者最新的post了Otz
