### ISSUE TITLE
解除B站区域限制 同步停业。

### ISSUE THREAD

**Issue by ipcjs** [ipcjs/bilibili-helper#365]
BiliPlus已停业，原因见：https://www.biliplus.com/
脚本同步停业。

<del>目前土豆服还能用。。。所以脚本暂时不停
手动切换，或者更新到最新版脚本，默认即为土豆服
但土豆服的稳定性，不保证`(-_-#)`</del>

**Comment by ubbh** [comment]
是的。好难受。。

**Comment by ville401578112** [comment]
也辛苦您啦

**Comment by lbldknight** [comment]
辛苦了，只能且行且珍惜了

**Comment by aruruwoo** [comment]
现在手动换成土豆源重新授权就一直504……………………

**Comment by ipcjs** [comment]
标题的 问号，已经改成 句号 了😔

**Comment by FlandreDaisuki** [comment]
@ipcjs @esterTion 辛苦了 <(_ _)>

**Comment by paulzzh** [comment]
@ipcjs @esterTion 辛苦了 <(_ _)>

**Comment by Malpaca** [comment]
@ipcjs 辛苦啦。
大家知道什么其他方法吗？除了用vpn

**Comment by jomainqaq** [comment]
辛苦了，好可惜

**Comment by steven7851** [comment]
@Malpaca 
https://bilibili-helper.github.io/ 有`跨区域解锁`功能

**Comment by AlfredChairman** [comment]
请问以后还会再开启吗😭

**Comment by ochang94** [comment]
辛苦了！

**Comment by ubbh** [comment]
辛苦了

**Comment by yoonhakcher** [comment]
RIP

**Comment by ljf4103** [comment]
> @Malpaca
> https://bilibili-helper.github.io/ 有`跨区域解锁`功能

非常感谢！

**Comment by ljf4103** [comment]
辛苦大神了

**Comment by KobeIverson0** [comment]
万分感谢

**Comment by leoouyang** [comment]
辛苦了

**Comment by danielzbw** [comment]
辛苦了QAQ

**Comment by llsccm** [comment]
辛苦了 感谢

**Comment by ipcjs** [comment]
你们先别急着献花圈，脚本貌似还能苟 `(-_-#)`
