### ISSUE TITLE
解除B站区域限制 “苟”模式

### ISSUE THREAD

**Issue by ipcjs** [ipcjs/bilibili-helper#367]
脚本貌似还能苟，重新打开了功能，默认切换到土豆服
鉴于服务器不稳定的原因，若服务器出错，不再弹窗
另外增加了自定义代理服务器地址的功能

**Comment by lzy0702** [comment]
似乎确实还能继续用土豆服，下午一度连土豆服都不工作了。
生存不易，大佬辛苦了。

**Comment by BraveSail** [comment]
服务器能自己搭么 手里正好几个闲置的
