### ISSUE TITLE
无法使用： 非常抱歉，根据版权方要求， 您所在的地区无法观看本片 ~

### ISSUE THREAD

**Issue by 1072814146** [ipcjs/bilibili-helper#368]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
url?

**Comment by 1072814146** [comment]
https://www.bilibili.com/bangumi/play/ss21371#126104

**Comment by ipcjs** [comment]
更新到7.5.5，然后在控制台执行 `bangumi_area_limit_hack.getLog()`，将输出的日志贴上来
