### ISSUE TITLE
这是咋回事

### ISSUE THREAD

**Issue by Tichonderious** [ipcjs/bilibili-helper#371]
log: [解除B站区域限制 v7.5.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26960/?spm_id_from=333.334.b_62696c695f62616e67756d69.22
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"Kindredspirits","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1558022400000,"status":1,"type":2},"watch_progress":{"last_ep_id":268060,"last_ep_index":"1","last_time":4}}}
log: setAreaLimitSeason ss26960 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=48377996&cid=84766213&qn=16&type=&otype=json&ep_id=268060&fnver=0&fnval=16&session=50e19b6d1f84daede7ef1324cb58aec6&module=bangumi
log: player msg: 代理服务器错误
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by Tichonderious** [comment]
点重新安装之后RegisterCom.dll文件下载了点开结果显示：行26，字符1，语法错误，代码800A03EA，源Microsoft JScript编译错误，Tempermonkey上面黄字显示Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!

**Comment by ipcjs** [comment]
`log: player msg: 代理服务器错误`
就是代理服务器出错了，多刷几下
