### ISSUE TITLE
生肖奇缘 看不了

### ISSUE THREAD

**Issue by zmd1998** [ipcjs/bilibili-helper#373]
脚本问题：@ipcjs

## 描述

显示“突破黑洞失败请重新登录，点击确定进行登录”
但是点击确定重新登录以后还是弹这个窗口而且还是不能看
其它的番都能看，就只有这一个会这样
- 问题网址：
https://www.bilibili.com/bangumi/play/ss26960

## 日志

<details>
<summary>Verbose 日志</summary>

```
log: [解除B站区域限制 v7.5.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26960
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: oss flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"doorholez","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586102400000,"status":1,"type":2}}}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=48377996&cid=84766213&qn=80&type=&otype=json&ep_id=268060&fnver=0&fnval=16&session=22db6d8cb157dd08e8d3de018c1834cc&module=bangumi
error: >>area limit
log: season_type: 1
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=48377996&cid=84766213&qn=16&type=&otype=json&ep_id=268060&fnver=0&fnval=16&session=22db6d8cb157dd08e8d3de018c1834cc&module=bangumi
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
```
 
</details>

## 其他

1. 浏览器版本：chrome  72.0.3626.121
2. 国家/地区：大陆

**Comment by ipcjs** [comment]
这个页面已经有人说过了，已经 @esterTion 了

**Comment by esterTion** [comment]
港澳，我这是台湾ip

**Comment by beautymarsalien** [comment]
不知道为什么生肖奇缘看不了了，前两个星期还没问题，今天打开直接就是显示视频被删除了，只有那个显示视频被删除的16秒的画面 试了Chrome和Firefox都不行 试了另外几个港澳台限定的，花丸 Given 埃尔梅罗二世都可以，但是生肖奇缘还是不是
log: [解除B站区域限制 v7.7.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26960
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"东方寂岚","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":268077,"last_ep_index":"18","last_time":1408},"sponsor":0,"vip_info":{"due_date":0,"status":0,"type":0}}}
log: /x/web-interface/nav {"uname":"东方寂岚","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /pgc/player/web/playurl
log: season_type: 1
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=61895394&cid=107623519&qn=80&type=&otype=json&ep_id=268077&fourk=1&fnver=0&fnval=16&session=7074f39ef9b6b6c2a4aa1b1de6e7bc27&module=bangumi
log: /pgc/player/web/playurl proxy(redirect) {"code":-403,"error":"returned cid not requested","message":"所在地区无法播放　Restricted area","errorcid":"8986943","raw_return":{"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"https://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1565742000&platform=ios&ssig=3e5W9_eQMZF6wVsJIRlUpA&oi=3078818617&trid=2024c91869164d21b6835d58ed265af8&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126},"loginStatus":{"isLogin":true,"uname":"东方寂岚","mid":2006593,"level":4,"vip_expire":0}}
log: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=61895394&cid=107623519&qn=80&type=&otype=json&ep_id=268077&fourk=1&fnver=0&fnval=16&session=464e0b0ba4c6813291bda5340b3d7d2f&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by doorn-exeva** [comment]
高達創戰潛行者 Re:RISE
看不了
https://www.bilibili.com/bangumi/play/ss28743

{"code":-403,"error":"returned cid not requested","message":"所在地区无法播放　Restricted area","errorcid":"8986943","raw_return":{"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"https://cn-zjjh4-dx-v-15.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1570727700&amp;platform=ios&amp;ssig=IshDe7UR7IndrxOPRF_W1Q&amp;oi=3078818617&amp;trid=f65dec809a1e49c39f7f9190f716e09c&amp;nfb=maPYqpoel5MI3qOUX6YpRA==&amp;nfc=1&amp;mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126},"loginStatus":{"isLogin":true,"uname":"异常者Doorn","mid":1309637,"level":5,"vip_expire":1586188800000}}
