### ISSUE TITLE
使用脚本后网络出问题了

### ISSUE THREAD

**Issue by yanjieyv** [ipcjs/bilibili-helper#376]
脚本非常实用，但是安装并使用脚本之后，无论是停用脚本还是启用脚本，都有部分网页打不开，要么类似DNS_PROBE_FINISHED_BAD_CONFIG，要么网页跳转提示我宽带欠费，我该怎么重置网络设置，变回没有用脚本之前的样子。

**Comment by ipcjs** [comment]
这是你网络的问题，和脚本没关系，脚本的“代理”是通过拦截网页的Ajax请求实现的，不会影响到系统
