### ISSUE TITLE
upos换成akamai的了

### ISSUE THREAD

**Issue by BraveSail** [ipcjs/bilibili-helper#378]
更新后upos换成upos-hz-mirrorakam.akamaized.net了，因为我都是下载下来看的，akamai的服务器是视频音频轨分开的有点麻烦，设置里面选择代理所有番剧替换阿里等upos服务器也没用，以前的upos-hz-mirrorxxx.acgvideo.com是视频音频合并的

**Comment by ipcjs** [comment]
确实改了，这个服务器貌似是德国的？不知道是不是因为biliplus在德国的原因，@esterTion 
国内访问挺慢的(-_-#)

**Comment by esterTion** [comment]
1. akamai有国内节点
2. cdn不由我控制
3. 
> 以前的upos-hz-mirrorxxx.acgvideo.com是视频音频合并的

切换旧版

**Comment by Itzamana** [comment]
换成akamai确实有点卡…

**Comment by CamelKing1997** [comment]
akamai现经测试，国内全部超时。

**Comment by BraveSail** [comment]
> akamai现经测试，国内全部超时。

![image](https://user-images.githubusercontent.com/49320262/60976993-423d9c80-a361-11e9-83e3-7fe2fc3c60c5.png)
没吧 实在不行可以挂代理

**Comment by cherinyy** [comment]
那能不能将节点替换成 `upos-hz-mirrorakam.akamaized.net`？
另外迅雷 CDN 的似乎只有旧版？
`upos-sz-mirrorxycdn.bilivideo.com` 已经没有解析了。
