### ISSUE TITLE
safari浏览器老是提示加载时机不对，重装无效，也是老样子

### ISSUE THREAD

**Issue by lvmingye523** [ipcjs/bilibili-helper#380]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
不支持safari
