### ISSUE TITLE
关于获取逻辑

### ISSUE THREAD

**Issue by esterTion** [ipcjs/bilibili-helper#385]
上次改了错误提示之后，反正也不知道是什么原因，经常会把普通番剧设置上地区限制的标记
本来是在playurl上检测添加标记缓存的，我现在改成通过season接口一次性缓存了
另外昨天也把所有除番剧出差之外的全部投稿的标记都删了
总体上来讲是会导致如果一直没有访问过相关的season信息的话，playurl永远会慢一倍（其实好像也就是多个3 400ms）
或许可以看下在某个地方加个空请求之类的

**Comment by ipcjs** [comment]
像这样（1869326aa1648daa60d48167b688a7e84d5ff93d），在番剧页面请求一下应该可以了吧？
