### ISSUE TITLE
AV页面番剧无法观看

### ISSUE THREAD

**Issue by ZegapainZ** [ipcjs/bilibili-helper#387]
使用插件后，bangumi页面的番剧是可以正常观看了，但是AV页面的番剧打开时会先显示“视频不见了”，过2、3秒显示出正常页面，但是再过2、3秒又会再次跳转到“视频不见了”，无法观看。
看到插件选项有一项“在AV页面启用”，已勾选，但是依然会出现同样问题。

**Comment by ZegapainZ** [comment]
浏览器：chrome版本 73.0.3683.103（正式版本） （64 位）
国家/地区：日本

**Comment by ZegapainZ** [comment]
问题页面：
https://www.bilibili.com/video/av2902943/?p=19
https://www.bilibili.com/video/av5439473/?p=12

**Comment by ipcjs** [comment]
别勾选试试？

**Comment by ZegapainZ** [comment]
前面的描述均是未勾选的情况下发生的，无论是否勾选“在AV页面启用”选项都会出现同样的问题，显示正常视频页面后过几秒必定跳回“视频不见了”页面，没法观看

**Comment by ipcjs** [comment]
页面用Vue写的，更新一下加会把脚本做的修改刷掉，有些页面显示不了设置图标也是这个原因
将AV页面的播放器换成新版吧，我这里试了下，新版没问题

**Comment by ZegapainZ** [comment]
刚试了试切换新版播放器，依旧看不了，而且跳回“视频不见了”的速度更加快了OTZ

**Comment by ipcjs** [comment]
试试7.5.11版？

**Comment by ZegapainZ** [comment]
试了试，可以看了，非常感谢＞＜！
不过很神奇的是依旧会在显示播放器后过2~3s跳出“视频不见了”的画面，只不过往下滚就看到了

**Comment by ZegapainZ** [comment]
![QQ图片20190429143853](https://user-images.githubusercontent.com/49830280/56877990-b53ab500-6a8c-11e9-8db8-faab9cce0be5.png)
![QQ图片20190429143859](https://user-images.githubusercontent.com/49830280/56877999-b9ff6900-6a8c-11e9-8cc5-24630c697581.png)

画面是这样
回头想了想其实有可能只是自己忘记往下滚没看到而已，有点不好意思OTZ
感谢菊苣耐心解答！m(_ _)m

**Comment by ipcjs** [comment]
不是你看错了，是我改了代码
新的，7.5.12版，改成播放器放页面顶端了`_(:3」∠)_`
