### ISSUE TITLE
番剧页面突破黑洞失败

### ISSUE THREAD

**Issue by Aniobi** [ipcjs/bilibili-helper#391]
脚本问题：@ipcjs

## 描述

连续打开了5个番剧页面均显示突破黑洞失败
- 问题网址：
https://www.bilibili.com/bangumi/play/ss25742/
https://www.bilibili.com/bangumi/play/ss26875/
https://www.bilibili.com/bangumi/play/ss26794/
https://www.bilibili.com/bangumi/play/ss26802/
https://www.bilibili.com/bangumi/play/ss25615/

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```log: [解除B站区域限制 v7.5.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26802/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"AniObi","isLogin":true,"level":4,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1560614400000,"status":1,"type":1},"watch_progress":{"last_ep_id":267737,"last_ep_index":"2","last_time":-1}}}
log: setAreaLimitSeason ss26802 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=49680633&cid=87759894&qn=80&type=&otype=json&ep_id=267737&fnver=0&fnval=16&session=be28c2672d4bc1b3c91ca9c42519a8cf&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：Google Chrome 73.0.3683.103
2. 国家/地区：美国加洲

**Comment by Hs096** [comment]
地区日本
好像所有的番都看不了了

log: [解除B站区域限制 v7.5.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss3495/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"ShisukonHachiman","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1626278400000,"status":1,"type":2},"watch_progress":{"last_ep_id":88251,"last_ep_index":"7","last_time":0}}}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=4702132&cid=50468710&qn=112&type=&otype=json&ep_id=88251&fnver=0&fnval=16&session=6a290fc7f3c9443722cd8fd444648eb0&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36

**Comment by Reki0A0L** [comment]
坐标美国/Chrome
同上所有番剧突破黑洞失败
更新浏览器，授权，更换upos和代理服务器
等等操作均没有效果。

log: [解除B站区域限制 v7.5.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26875/?spm_id_from=333.334.b_62696c695f62616e67756d69.4
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Reki·L","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1569168000000,"status":1,"type":2},"watch_progress":{"last_ep_id":267692,"last_ep_index":"1","last_time":0}}}
log: setAreaLimitSeason ss26875 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=48896153&cid=85630428&qn=0&type=&otype=json&ep_id=267692&fnver=0&fnval=16&session=f97ebb430eae671f1ab2cc89e20d72ca&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36
log: balh_server_inner  =>  https://biliplus.ipcjs.top
log: balh_server_inner  =>  https://www.biliplus.com
log: balh_server_inner  =>  __custom__
log: balh_server_inner  =>  https://www.biliplus.com

**Comment by TSUKINA** [comment]
澳洲/Chrome 俺也一样

log: [解除B站区域限制 v7.5.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep267738
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://biliplus.ipcjs.top upos_server: kodo flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"月鸣山崎","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":265652,"last_ep_index":"PV","last_time":2},"sponsor":0,"vip_info":{"due_date":1586102400000,"status":1,"type":2}}}
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=50423468&cid=88294370&qn=80&type=&otype=json&ep_id=267738&fnver=0&fnval=16&session=71f23bc0bb188dd467e5ac562c98ecc0&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by vienna95** [comment]
log: [解除B站区域限制 v7.5.10 (Greasemonkey.injector)] run on: https://www.bilibili.com/bangumi/play/ep234658?from=search&seid=13906300680628373605
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"猫与玫瑰","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1575043200000,"status":1,"type":2},"watch_progress":{"last_ep_id":234663,"last_ep_index":"6","last_time":1}}}
log: setAreaLimitSeason ep234658 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=27501468&cid=48928808&qn=112&type=&otype=json&ep_id=234658&fnver=0&fnval=16&session=e69c404dc8a34858bdd36a502f5d0fed&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by Aniobi** [comment]
现在好像是需要会员的的作品无法观看
https://www.bilibili.com/bangumi/play/ep267682

log: [解除B站区域限制 v7.5.11 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26794/
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"AniObi","isLogin":true,"level":4,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1560614400000,"status":1,"type":1},"watch_progress":{"last_ep_id":267681,"last_ep_index":"2","last_time":-1}}}
log: setAreaLimitSeason ss26794 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=49623611&cid=86887721&qn=64&type=&otype=json&ep_id=267681&fnver=0&fnval=16&session=c83eccb78e2cada4570120b22622eec7&module=bangumi
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=50363365&cid=88170540&qn=64&type=&otype=json&ep_id=267682&fnver=0&fnval=16&session=43956673d7e950fa93d8c93124f91550&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36

**Comment by jiupeiz** [comment]
日本/chrome
我遇到的问题是只有C&T打不开，会员限定的新剧集和开放的上周之前的剧集都是。

log: [解除B站区域限制 v7.5.11 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep269569
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server: kodo flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"海卫四","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":269569,"last_ep_index":"3","last_time":1036},"sponsor":0,"vip_info":{"due_date":1595001600000,"status":1,"type":2}}}
log: setAreaLimitSeason ep269569 true
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=50353241&cid=88152812&qn=80&type=&otype=json&ep_id=269569&fnver=0&fnval=16&session=8c2797489ba97235e0fcaea472b6b62c&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36

**Comment by ipcjs** [comment]
#399
