### ISSUE TITLE
番剧页面突破黑洞失败

### ISSUE THREAD

**Issue by SecretLoveRem** [ipcjs/bilibili-helper#392]
脚本问题：@ipcjs

## 描述
昨晚还好好地 一到今天就不行了 两个代理服务器都不行了

- 问题网址：https://www.bilibili.com/bangumi/play/ss25727#251220

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
log: [解除B站区域限制 v7.5.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss25727#251220
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"新闻联播大结局丷","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1570809600000,"status":1,"type":2},"watch_progress":{"last_ep_id":251220,"last_ep_index":"11","last_time":1157}}}
log: setAreaLimitSeason ss25727 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=38461423&cid=67608598&qn=112&type=&otype=json&ep_id=251220&fnver=0&fnval=16&session=9e1850e000310f7d621e8e772e39a4b3&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
```
 
</details>

## 其他

1. 浏览器版本：谷歌浏览器 73.0.3683.103
2. 国家/地区：中国

**Comment by biogk** [comment]
log: [解除B站区域限制 v7.5.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep269569
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function (a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function (a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":" ","isLogin":true,"level":4,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":269569,"last_ep_index":"3","last_time":0},"sponsor":0,"vip_info":{"due_date":1558540800000,"status":1,"type":1}}}
log: setAreaLimitSeason ep269569 true
log: set jQuery function (a,b){return new e.fn.init(a,b,h)} -> function (a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function (a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: setAreaLimitSeason ep269569 true
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=50353241&cid=88152812&qn=80&type=&otype=json&ep_id=269569&fnver=0&fnval=16&session=5769669b3e8ada86be7e554857eb46a1&module=bangumi
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15

**Comment by SecretLoveRem** [comment]
你这发的什么我也看不懂啊
