### ISSUE TITLE
番剧突破失败

### ISSUE THREAD

**Issue by Shimakazeisme** [ipcjs/bilibili-helper#394]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志
log: [解除B站区域限制 v7.5.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26794/?spm_id_from=333.334.b_62696c695f62616e67756d69.20
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"等待De过去式","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1587225600000,"status":1,"type":2},"watch_progress":{"last_ep_id":267680,"last_ep_index":"1","last_time":1}}}
log: setAreaLimitSeason ss26794 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=48899706&cid=85636818&qn=0&type=&otype=json&ep_id=267680&fnver=0&fnval=16&session=8d74c181f75e3df3a45f2e720fe190b0&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：chrome
2. 国家/地区：美国

**Comment by ipcjs** [comment]
正常了就把问题close掉吧
