### ISSUE TITLE
看不到博人傳 

### ISSUE THREAD

**Issue by toddy1b21** [ipcjs/bilibili-helper#398]
脚本问题：@ipcjs

## 描述
看不到博人傳 其他番都可以 就是博人傳不是突破黑洞

- 问题网址：

## 日志

<details>
<summary>log: [解除B站区域限制 v7.5.11 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep179621
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"凜推咲Saki最高","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1601913600000,"status":1,"type":2},"watch_progress":{"last_ep_id":161928,"last_ep_index":"39","last_time":-1}}}
log: setAreaLimitSeason ep179621 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=18161109&cid=29650209&qn=112&type=&otype=json&ep_id=179621&fnver=0&fnval=16&session=20c0812ee24470c5b08cb1b691dd454d&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36</summary>

```


 


## 其他

1. 浏览器版本：Google Chrome 版本 74.0.3729.108
2. 国家/地区：香港

**Comment by toddy1b21** [comment]
问题网址：https://www.bilibili.com/bangumi/play/ep179621

**Comment by ipcjs** [comment]
#399
