### ISSUE TITLE
code-403问题汇总

### ISSUE THREAD

**Issue by ipcjs** [ipcjs/bilibili-helper#399]
最近貌似挺多番剧页面报这个错的？在这里汇总一下吧

## 报code-403的页面

- [ ] [生肖奇缘](https://www.bilibili.com/bangumi/play/ss26960)：仅限港澳，无解，详见：#373
- [ ] [冰冷热带鱼](https://www.bilibili.com/bangumi/play/ss26341)：仅限东南亚，无解

## 已修复的页面

- [x] [博人传](https://www.bilibili.com/bangumi/play/ep179621)
- [x] [CAROLE & TUESDAY](https://www.bilibili.com/bangumi/play/ep269569)
- [x] [Re：从零开始的异世界生活](https://www.bilibili.com/bangumi/play/ep85754)

**Comment by biogk** [comment]
[+辉夜大小姐](https://www.bilibili.com/bangumi/media/md5267730/?from=search&seid=682861337107235085)

**Comment by ipcjs** [comment]
@biogk
我这里没问题呀，这是大会员限定的视频，你授权了没有？

**Comment by biogk** [comment]
@ipcjs 授权了，但可能跟Safari有关系，我晚点用Firefox试一下
试了下，可以，打扰了

**Comment by elsy328** [comment]
{"code":-403,"message":"所在地区无法播放　Restricted area","errorcid":"8986943"}
坐标英国，有大会员，也是Carole & Tuesday 看不了

现在可以看了，感恩~（05.02）

**Comment by esterTion** [comment]
emmmm？
我不是都改了逻辑了，怎么这几个还是会加进跨区缓存

---
又改了逻辑了，把单个cid缓存加了回去，然后season api会对应进行批量设置/清除所属cid
这几个目前都好了
（搞不懂什么原因发生的，偶发性的ip location故障？）

---
所以 1869326 就没用了（
以后还出现的话加载一次season再刷新应该会恢复

**Comment by HikaruGloria** [comment]
坐标澳大利亚悉尼
黒執事也看不了了qwq
https://www.bilibili.com/bangumi/play/ss75#193572
```
log: [解除B站区域限制 v7.5.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss75#193572
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"政井洛酱","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1570809600000,"status":1,"type":2},"watch_progress":{"last_ep_id":193572,"last_ep_index":"24","last_time":-1}}}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=18958999&cid=30922252&qn=0&type=&otype=json&ep_id=193572&fnver=0&fnval=16&session=b7880e65669f8d141dee3caef4a36fd3&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
```

**Comment by sdsau** [comment]
坐标国内，仅限xxx地区，点开的都报403，以前都是可以打开的。
脚本版本7.5.13，浏览器chrome 73.

**Comment by ipcjs** [comment]
@HikaruGloria @sdsau 
你们两说的，我这里试了，都没问题。可能是服务器抽风？再试试？

**Comment by Alex7120** [comment]
会员授权无反应，非自然死亡第1集，chrome73
> `log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep204577
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"匠","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1588694400000,"status":1,"type":2},"watch_progress":{"last_ep_id":204577,"last_ep_index":"第1话","last_time":2}}}
log: setAreaLimitSeason ep204577 true
log: season_type: 5
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=21818385&cid=36003632&qn=112&type=&otype=json&ep_id=204577&fnver=0&fnval=16&session=c70d466cae99a2b25522ba2677a14461&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36`

**Comment by gittohabo** [comment]
bilibili.com/bangumi/play/ss26341
冰冷热带鱼 仅限东南亚的

**Comment by alanxzl** [comment]
safari 授权显示成功了 但是一直看不了 有会员标记的视频 我明明还是大会员的。。。

**Comment by sayalan** [comment]
人形天使电脑心第三集也是403错误

**Comment by zy-HNU** [comment]
《鬼灭之刃》第六话台湾版报错

**Comment by ljf4103** [comment]
授权的时候
This page isn’t working link.acg.tv is currently unable to handle this request.
HTTP ERROR 503

**Comment by ipcjs** [comment]
@sayalan @zy-HNU 这两个我试了，没问题

**Comment by LoneFireBlossom** [comment]
进击的巨人第二季第三季第三季part2所有
chrome最新
解除B站区域限制最新

**Comment by lxfly2000** [comment]
同样问题，怀疑是B站不给看了

**Comment by MasterXuZ** [comment]
满脑都是oo的我无法谈恋爱，403，脚本版本7.60

**Comment by mystery00ou** [comment]
轻音少女 403 脚本7.60

**Comment by habutower** [comment]
坐标国内 进击的巨人第三季 Part.2
code-403: {"code":-403,"message":"所在地区无法播放　Restricted area","errorcid":"8986943"}

当前代理服务器（https://www.biliplus.com）依然有区域限制

**Comment by romknight** [comment]
所有的最新大会员番剧都有区域限制，两个代理服务器都不行(有大会员)

**Comment by lordpotter** [comment]
吹响吧！上低音号第二季。www.bilibiliplus.com的服务器无法突破地区限制。土豆服特别的卡。自定义没法用。

**Comment by maoam1009** [comment]
鬼灭之刃台湾地区 403

**Comment by sdsau** [comment]
> 鬼灭之刃台湾地区 403

试试隐身模式？我现在的情况是所有页面都失效了，但是进隐身模式再打开又成功了

**Comment by Blinging** [comment]
英国，辉夜大小姐想让我告白，b站403，脚本 7.7.1

**Comment by zuobull** [comment]
国内，进击的巨人403

**Comment by srongan** [comment]
国内，版本7.72，番名：彼方的阿斯特拉，其实其他限定地区的番也是同样的403。刚刚知道油猴，不知道是什么情况，加油
log: [解除B站区域限制 v7.7.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28017#276761
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"srongan","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":276761,"last_ep_index":"1","last_time":1},"sponsor":0,"vip_info":{"due_date":1594137600000,"status":1,"type":2}}}
log: setAreaLimitSeason ss28017 true
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=57730197&cid=100766900&qn=0&type=&otype=json&ep_id=276761&fourk=1&fnver=0&fnval=16&session=1bf8e5bf3f93e9e15002da3763d64c76&module=bangumi
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by ggdesjsm** [comment]
美国，所有版权都不能看了，有大会员

**Comment by EVNII** [comment]
国内，“遭難了嗎？” 看不了

**Comment by SecretLoveRem** [comment]
code-403: {"code":-403,"error":"returned cid not requested","message":"所在地区无法播放　Restricted area","errorcid":"8986943","raw_return":{"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4
鬼灭之刃看不了 B站

**Comment by prpapr** [comment]
{"code":-403,"error":"returned cid not requested","message":"所在地区无法播放　Restricted area","errorcid":"8986943","raw_return":{"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"https://cn-zjwz-dx-v-04.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1562391300&platform=ios&ssig=_XUcap4aR-Iw8Rw4Kqi1nQ&oi=3078818617&trid=c399a30f2d394fa0bd03a569c509245d&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}}

港澳地区的所有视频都无法观看

**Comment by chaonen** [comment]
只要長得可愛，即使是變態你也喜歡嗎？（僅限台灣地區）：第1话 弄丟內褲的灰姑娘!?
错误403

**Comment by chaonen** [comment]
补上https://www.bilibili.com/bangumi/play/ss28015

**Comment by lxfly2000** [comment]
国内如果遇到403错误，请尝试重新授权，如果已经有登录信息了就退出再授权

**Comment by esterTion** [comment]
update
```
提交： d61766d3f16f1a8533b72dff91bbb7f5e828012a [d61766d]
父级： 4b6729297b
日期： 2019年7月10日 16:37:52
标签： HEAD, ->, master, origin/master, origin/HEAD

playurl对于跨区取消登录的要求
```

游客不能访问720以上是播放器端的限制，未授权时1080+将切换失败

**Comment by chaonen** [comment]
已解决
感谢

**Comment by Rewriter123** [comment]
炎炎消防队看不了，本身是大会员。
坐标日本

**Comment by ghost** [comment]
显示会员观看的都看不了T_T（如炎炎消防队、地错等），但本身是大会员。
坐标日本

**Comment by Zaharial** [comment]
坐标美国 有大会员
灵能百分百第二季看不了 QAQ

**Comment by xiaoyoucheng** [comment]
显示会员观看的都看不了，，如 番剧索引中所有含有大会员专属得番，本身有大会员。坐标国内。
取消授权页面显示
感谢使用，正在为您清除登录cookie
访问key删除失败，错误：[403]undefined

**Comment by joshua694368414** [comment]
code-403: {"code":-403,"error":"returned cid not requested","message":"没有观看此付费视频的权限　Video requires payment","errorcid":"28453487","raw_return":{"accept_description":["流畅 360P"],"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15083,"order":1,"size":866787,"url":"https://cn-zjwz-dx-v-08.acgvideo.com/upgcxcode/87/34/28453487/28453487-1-16.mp4?expires=1564172100&platform=ios&ssig=_tnuzN2gcFo5SEAYzP8vdQ&oi=3078818617&trid=c30df63f67464613b53ca6167afe2639&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15083}}

当前代理服务器（https://www.biliplus.com）依然有区域限制

哦豁，估计B站不给看了

**Comment by robert1015** [comment]
石纪元第5集报错，坐标日本东京

**Comment by wlkz** [comment]
在7.5.5以后新加的这段逻辑貌似会导致大会员番剧403

https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.user.js#L1199

删除这个判断支以后一切正常。

```
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":1,"follow_status":2,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":276372,"last_ep_index":"1","last_time":-1},"sponsor":0,"vip_info":{"due_date":1590336000000,"status":1,"type":2}}}
log: setAreaLimitSeason ep276376 false
log: __playinfo__ get
log: /pgc/player/web/playurl
log: season_type: 1
log: /pgc/player/web/playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=62935269&cid=109326569&qn=0&type=&otype=json&ep_id=276376&fourk=1&fnver=0&fnval=16&session=e823e7c3c3794ddd7f94e26d83980d8c&module=bangumi
log: /pgc/player/web/playurl origin block: true {"code":0,"message":"0","result":{"accept_format":"hdflv2,flv,flv720,flv480,mp4","code":0,"seek_param":"start","is_preview":0,"fnval":16,"video_project":true,"fnver":0,"type":"DASH","bp":0,"result":"suee","seek_type":"offset","vip_type":2,"from":"local","video_codecid":7,"no_rexcode":0,"format":"hdflv2","message":"","accept_quality":[112,80,64,32,16],"quality":112,"timelength":1451029,"has_paid":true,"vip_status":1,"dash":{...},"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":13}}
log: /pgc/player/web/playurl proxy {"code":-403,"error":"returned cid not requested","message":"没有观看此付费视频的权限　Video requires payment","errorcid":"28453487","raw_return":{"accept_description":["流畅 360P"],"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15083,"order":1,"size":866787,"url":"https://cn-zjwz4-dx-v-05.acgvideo.com/upgcxcode/87/34/28453487/28453487-1-16.mp4?expires=1565461200&platform=ios&ssig=ihCOGQwYEOZv5TWy76mWig&oi=3078818617&trid=7eeb12d4f2cd44deb6354cb14ac14468&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15083},"loginStatus":{"isLogin":false}}
log: __playinfo__ set
```

**Comment by esterTion** [comment]
`"loginStatus":{"isLogin":false}`
？

**Comment by ipcjs** [comment]
原来playurl里的登录信息是这个用处🤣

**Comment by ipcjs** [comment]
@wlkz 应该是那个替换模式的问题，更新下7.7.7

**Comment by wlkz** [comment]
> @wlkz 应该是那个替换模式的问题，更新下7.7.7

ok 没有问题了

**Comment by beautymarsalien** [comment]
不知道为什么生肖奇缘看不了了，前两个星期还没问题，今天打开直接就是显示视频被删除了，只有那个显示视频被删除的16秒的画面 试了Chrome和Firefox都不行 坐标荷兰
log: [解除B站区域限制 v7.7.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26960
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: server: https://www.biliplus.com upos_server: flv_prefer_ws: remove_pre_ad: readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"东方寂岚","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":268077,"last_ep_index":"18","last_time":1408},"sponsor":0,"vip_info":{"due_date":0,"status":0,"type":0}}}
log: /x/web-interface/nav {"uname":"东方寂岚","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /pgc/player/web/playurl
log: season_type: 1
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=61895394&cid=107623519&qn=80&type=&otype=json&ep_id=268077&fourk=1&fnver=0&fnval=16&session=7074f39ef9b6b6c2a4aa1b1de6e7bc27&module=bangumi
log: /pgc/player/web/playurl proxy(redirect) {"code":-403,"error":"returned cid not requested","message":"所在地区无法播放　Restricted area","errorcid":"8986943","raw_return":{"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"https://cn-zjwz4-dx-v-09.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1565742000&platform=ios&ssig=3e5W9_eQMZF6wVsJIRlUpA&oi=3078818617&trid=2024c91869164d21b6835d58ed265af8&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126},"loginStatus":{"isLogin":true,"uname":"东方寂岚","mid":2006593,"level":4,"vip_expire":0}}
log: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=61895394&cid=107623519&qn=80&type=&otype=json&ep_id=268077&fourk=1&fnver=0&fnval=16&session=464e0b0ba4c6813291bda5340b3d7d2f&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by kejsdhjsdhi** [comment]
石纪元！！

**Comment by GrimmNoters** [comment]
坐标加拿大，炎炎消防队

**Comment by scallibur** [comment]
坐标米国，top gear全季都看不了

**Comment by liunima1129** [comment]
坐标美国，Carole&Tuesday最新一集买了大会员还是看不了...

**Comment by weberchen20180302** [comment]
坐标日本，Carole&Tuesday最新一集看不了，403

**Comment by donng-d** [comment]
插件还能用嘛，昨天就是有点卡，挂了梯子能用，今天打开啥都看不了，嘤嘤嘤

code-403: {"code":-403,"error":"returned cid not requested","message":"所在地区无法播放　Restricted area","errorcid":"8986943","raw_return":{"accept_description":["高清 720P","流畅 360P"],"accept_format":"hdmp4,mp4","accept_quality":[48,16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"https://cn-zjjh4-dx-v-15.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1568274000&platform=ios&ssig=qPospxrAVLJuoIwyEmJZCg&oi=3078818617&trid=2d7412d14edd42748f14b6b559cdccdb&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126},"loginStatus":{"isLogin":true,"uname":"栋栋咚","mid":4121215,"level":0,"vip_expire":0}}

当前代理服务器（https://biliplus.ipcjs.top）依然有区域限制

**Comment by ShuqiGao** [comment]
坐标美国，看所有的番剧都会跳403错误了

**Comment by Z206167503** [comment]
坐标中国，彼方的阿斯特拉看不了

**Comment by esterTion** [comment]
2019/9/12的大范围-403问题已解决

---
原因：
原用于获取较高下载限速的视频地址的参数`npcybs=1`在今天（昨天？）用于番剧上会触发地区限制的错误返回，推测是对禁止缓存添加了屏蔽措施。
> 较旧之前视频地址为码率1.25~1.5倍限速，在当时使用这个参数会把限速全部提升至1.2m。
但这个限速方式已经停用了很久，这个参数作为历史遗留一直保留了下来。

也就是，现在魔改客户端在强制下载番剧时也会碰到错误，无法下载。

**Comment by shuan7110** [comment]
座標台灣 所有番劇都不能看了

**Comment by shuan7110** [comment]
跳404錯誤，重新點授權後跳了403錯誤...接著刷新又跳成404了
有大會員

**Comment by nekoidoc** [comment]
坐标澳洲，所有番剧都403，持续超过半个月

**Comment by jvziovo** [comment]
在美国，现在要大会员的番都403报错了，我也有大会员呀，删了重下代码也没用。

**Comment by joshua694368414** [comment]
code-403: {"code":-403,"error":"returned cid not requested","message":"没有观看此付费视频的权限　

当前代理服务器（https://biliplus.ipcjs.top）依然有区域限制

请问现在是不是要设置什么东西了

**Comment by shyrz** [comment]
坐标国内
[我不是說了能力要平均值嗎？（僅限港澳台地區）](https://www.bilibili.com/bangumi/play/ep286154)
出现和楼上一样的403错误

**Comment by esterTion** [comment]
@joshua694368414 @Phantr4x
`没有观看此付费视频的权限`
https://account.bilibili.com/account/big
这边请

**Comment by Manticore0918** [comment]
英国，带大会员的番都看不了，授权了也不行，自己充了大会员
"code":-403,"error":"returned cid not requested","message":"没有观看此付费视频的权限　Video requires payment"

**Comment by chenjwleo** [comment]
意大利 ，年费大会员用户，中午还能看，下午开始所有大会员视频都不能看 {"code":-403,"error":"returned cid not requested","message":"没有观看此付费视频的权限

**Comment by esterTion** [comment]
谁还给我点踩，真能行
错误信息截一半什么意思，后边一半是不是isLogin false啊？
给你提供个服务不是欠你的，能好好报问题不，整个列表下来除了开头几个已知的地区问题后面全都是我随便一开直接播放的

**Comment by lxfly2000** [comment]
是不是没显示全啊，isLogin是false就提示让用户登录也行吧（我的邮件列表快爆炸了

**Comment by joshua694368414** [comment]
> @joshua694368414 @Phantr4x
> `没有观看此付费视频的权限`
> https://account.bilibili.com/account/big
> 这边请

所以现在是脚本不能突破会员了?

**Comment by lxfly2000** [comment]
我记得这东西是突破地区限制而不是大会员限制的吧

**Comment by joshua694368414** [comment]
> 我记得这东西是突破地区限制而不是大会员限制的吧

前阵子那些会员我居然突破了= =

**Comment by chenjwleo** [comment]
已经是大会员的用户为啥突然不能看会员视频了，昨天下午还好好的，晚上就不行了
 debug: [解除B站区域限制 v7.8.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss5069/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"Leonardochen725","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1603641600000,"status":1,"type":2},"watch_progress":{"last_ep_id":95964,"last_ep_index":"14","last_time":856}}}
debug: setAreaLimitSeason ss5069 true
debug: /x/web-interface/nav {"uname":"Leonardochen725","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=6612154&cid=11572761&qn=80&type=&otype=json&ep_id=95964&fnver=0&fnval=16&session=d5362fcf7cce23ea8a1747899f887e50&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by SecretLoveRem** [comment]
能不能不要发给我
烦的一批




------------------ 原始邮件 ------------------
发件人: "chenjwleo"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 下午2:53
收件人: "ipcjs/bilibili-helper"<bilibili-helper@noreply.github.com>; 
抄送: "不要看                 "<1696426987@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ipcjs/bilibili-helper] code-403问题汇总 (#399)




已经是大会员的用户为啥突然不能看会员视频了，昨天下午还好好的，晚上就不行了
 debug: [解除B站区域限制 v7.8.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss5069/
 debug: window.playinfo
 debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
 info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
 debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
 debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
 debug: /x/web-interface/nav {"uname":"Leonardochen725","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
 debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1603641600000,"status":1,"type":2},"watch_progress":{"last_ep_id":95964,"last_ep_index":"14","last_time":856}}}
 debug: setAreaLimitSeason ss5069 true
 debug: /x/web-interface/nav {"uname":"Leonardochen725","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
 debug: playinfo get
 debug: playinfo get
 debug: season_type: 1
 debug: playurl add 'module=bangumi' param
 info: player msg: 从代理服务器拉取视频地址中...
 debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=6612154&cid=11572761&qn=80&type=&otype=json&ep_id=95964&fnver=0&fnval=16&session=d5362fcf7cce23ea8a1747899f887e50&module=bangumi&balh_ajax=1
 debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by ipcjs** [comment]
@SecretLoveRem 请善用GitHub的订阅功能，别发送垃圾消息
![ScreenClip  19](https://user-images.githubusercontent.com/4396864/66899643-ec4a5600-f02d-11e9-9ca7-d04e087cb1fa.png)
