### ISSUE TITLE
视频加载失败，显示代理服务器不可用

### ISSUE THREAD

**Issue by uraya4** [ipcjs/bilibili-helper#404]
脚本问题：@ipcjs
![image](https://user-images.githubusercontent.com/50269510/57180936-37c5d900-6ec0-11e9-9b9d-71ed2d5fe14f.png)

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
不写了吗，“代理服务器临时不可用”，“耐心等待代理服务器端修复”就是了
