### ISSUE TITLE
锁区可以看，付费无法观看（原因：脚本不提供破解付费功能）

### ISSUE THREAD

**Issue by tsj007** [ipcjs/bilibili-helper#41]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```
log: [解除B站区域限制 v6.4.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep172120
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading
log: /x/web-interface/nav {"isLogin":true,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=29854207|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=84272f997be5dc8c23ee28642437de9f
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by tsj007** [comment]
log: [解除B站区域限制 v6.4.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep172120
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip: Y server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading
log: /x/web-interface/nav {"isLogin":true,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":172120,"last_ep_index":"2","last_time":0}}}
log: setAreaLimitSeason ep172120 false
log: {"code":-500,"message":"本集为大会员专享剧集......."}
log: setAreaLimitSeason ep172120 true
log: ==> {"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15083,"order":1,"size":866787,"url":"http://cn-jsnt2-dx-v-09.acgvideo.com/vg2/2/0a/28453487-1-16.mp4?expires=1515943800&platform=ios&ssig=CDkMoje3FEchwLb1p5D7yw&oi=3078818617&nfa=XDgDxK8AWd7SRf4xKS6qxA==&dynamic=1&hfa=2020114066&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM="}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15083,"flvjsType":"mp4"}
log: Redirected request: bangumi playurl ->  https://biliplus.ipcjs.win/BPplayurl.php?cid=29854207|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=0a92e70dc68920ec1f9b8dce370ded0d
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by ipcjs** [comment]
你貌似不是大会员吧，是给单集付了钱吗？
单集付费，是有可能不能看的，我在脚本说明里面都写了

还有“被永封的大会员”选项别乱开，去看下这个选项的作用先

**Comment by ipcjs** [comment]
不对，你大概单集都没买？

这个脚本是“解除B站区域限制”，不是“破解B站付费”。
