### ISSUE TITLE
拉取视频失败，看不了视频

### ISSUE THREAD

**Issue by xtdxb** [ipcjs/bilibili-helper#417]
## 描述
脚本好像炸了，拉取视频地址失败

- 问题网址：https://www.bilibili.com/bangumi/play/ep268180

## 日志

<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep268180
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"夏天的雪碧","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1602777600000,"status":1,"type":2},"watch_progress":{"last_ep_id":268179,"last_ep_index":"16","last_time":4}}}
log: setAreaLimitSeason ep268180 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=53750209&cid=94022221&qn=0&type=&otype=json&ep_id=268180&fnver=0&fnval=16&session=064589b8aae7f220172c61bc9a696a30&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```

## 其他

1. 浏览器版本：360极速浏览器
2. 国家/地区：大陆

**Comment by veritablevein** [comment]
我这边刚才炸了，现在好了

**Comment by xtdxb** [comment]
我也好了但是卡的一b，一直加载中
