### ISSUE TITLE
biliplus无法解除限制，土豆服3s一卡

### ISSUE THREAD

**Issue by longzhongba** [ipcjs/bilibili-helper#418]
脚本问题：@ipcjs

## 描述

code-403: {"code":-403,"message":"所在地区无法播放　Restricted area","errorcid":"8986943"}

当前代理服务器（https://www.biliplus.com）依然有区域限制
- 问题网址：
https://www.bilibili.com/bangumi/play/ep268180

## 日志

log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep268180
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"LVOA-C","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1586966400000,"status":1,"type":2},"watch_progress":{"last_ep_id":268180,"last_ep_index":"17","last_time":5}}}
log: setAreaLimitSeason ep268180 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=53750209&cid=94022221&qn=116&type=&otype=json&ep_id=268180&fnver=0&fnval=16&session=afa6aa8ce2b9212c04bcc5f2e6f09be3&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
## 其他

1. 浏览器版本：chrome 74.0
2. 国家/地区：国内

**Comment by ipcjs** [comment]
#399
