### ISSUE TITLE
自定义代理，服务器如何搭建？

### ISSUE THREAD

**Issue by revel201** [ipcjs/bilibili-helper#419]

**Comment by ipcjs** [comment]
脚本里不是调用了很多代理服务器的接口吗？全部实现它们就行了了（

**Comment by Lyken17** [comment]
有没有可以参考的代码？

**Comment by esterTion** [comment]
实际访问代理需要自己解决

* `/api/bangumi`: 
不带season_type：`https://bangumi.bilibili.com/api/season_v5`
带season_type：`https://bangumi.bilibili.com/view/api/season`
<details>
<summary>init.lua: function buildParam</summary>

```Lua
function buildParam(params, key)
    local keyset = {}
    local i = 0
    for k, v in pairs(params) do
        i = i + 1
        keyset[i] = k
    end
    table.sort(keyset, key_sort)
    local data = {}
    for k, v in pairs(keyset) do
        table.insert(data, v .. "=" .. encodeURI(params[v]))
    end
    data = table.concat(data, '&')

    local md5str = ngx.md5(data .. key)
    return data .. "&sign=" .. md5str
end
```

</details>
<details>
<summary>api_bangumi.lua</summary>

```Lua
local reqHeader = { ['Host']='bangumi.bilibili.com' }
local param={}
param["appkey"] = appkey
param["build"]=12450
param["ts"]=ngx.time()
param["type"]='bangumi'
param['platform']='ios'
if GET['spid'] ~=nil and tonumber(GET['spid']) > 5000000 then
	GET['season'] = (tonumber(GET['spid']) - 5000000) ..""
end
local sid = param['season_id']
local endpoint = '/api/season_v5?'

if GET['season_type'] ~= nil then
	endpoint = '/view/api/season?'
	param['season_type'] = GET['season_type']
end
```
</details>

* `/BPplayurl.php`
<details>
<summary>function playurl</summary>

```PHP
switch($module){
	case 'interface':
		$arr=array_merge(array(
			'appkey'=>$luaAppkey,
			'cid'=>$cid,
			'npcybs'=>1,
			'quality'=>$quality,
			'type'=>$type,
			'otype'=>'json',
			'buvid'=>12450,
			'platform'=>$param['platform']
		),$extra);
		$base='http://app.bilibili.com/';
		$useSecret=$luaAppSecret;
	break;
	case 'bangumi':
		$arr=array_merge(array(
			'module'=>'bangumi',
			'appkey'=>$h5Appkey,
			'type'=>$type,
			'cid'=>$cid,
			'npcybs'=>1,
			'otype'=>'json',
			'ts'=>time(),
			'build'=>12450,
			'quality'=>$quality,
			'platform'=>$param['platform'],
			'season_type'=>0
		),$extra);
		$base='http://bangumi.bilibili.com/player/api/';
		$useSecret=$h5AppSecret;
	break;
	case 'movie':
		$arr=array_merge(array(
			'module'=>'movie',
			'appkey'=>$h5Appkey,
			'quality'=>4,
			'type'=>$type,
			'cid'=>$cid,
			'npcybs'=>1,
			'otype'=>'json',
			'ts'=>time(),
			'build'=>12450,
			'quality'=>$quality,
			'platform'=>$param['platform']
		),$extra);
		$base='http://bangumi.bilibili.com/player/api/';
		$useSecret=$h5AppSecret;
	break;
}
switch ($param['playurl_ver']) {
	case 'v1': { if ($module != 'interface') $base = substr($base, 0,  -4); $base .= 'playurl?'; break; }
	default: { $base .= 'v2/playurl?'; }
}
$url=$base.buildParam($arr,$useSecret);
```
</details>

**Comment by ipcjs** [comment]
或者像 https://github.com/kghost/bilibili-area-limit 那样，直接用Nginx反代`api.bilibili.com`，脚本也是可以用的
https://github.com/ipcjs/bilibili-helper/commit/1135309b2b86b106d3fe451195e15e5e3ee75d1c

**Comment by libao0412** [comment]
> 实际访问代理需要自己解决
> 
> * `/api/bangumi`:
>   不带season_type：`https://bangumi.bilibili.com/api/season_v5`
>   带season_type：`https://bangumi.bilibili.com/view/api/season`
> 
> init.lua: function buildParam
> api_bangumi.lua
> * `/BPplayurl.php`
> 
> function playurl

你好，對於上面這段的解說能否更詳細的說明一下呢？是全部都必須放到nginx內嗎？如果只要實現BPplayurl的功能是否能只放BPplayurl.php呢？再來是帳號授權的部分，這個要怎麼做才能讓代理能夠有帳號的cookie呢？有沒有這部分的原始碼可以用呢？謝謝。

**Comment by libao0412** [comment]
> 或者像 https://github.com/kghost/bilibili-area-limit 那样，直接用Nginx反代`api.bilibili.com`，脚本也是可以用的
> [1135309](https://github.com/ipcjs/bilibili-helper/commit/1135309b2b86b106d3fe451195e15e5e3ee75d1c)

這個我有試過了，在nginx直接把整個api.bilibili.com做反代，做一般的aid解析跟cid解析flv流都很正常，但是遇到一些麻煩，首先是cookie的問題，用kghost腳本套成自己的伺服器會遇到cros的問題(例如跨域...等等)，這個有沒有甚麼解決方法?再來想請問的就是，用反代做法能使用在ipcjs大大的腳本上嗎？

**Comment by ipcjs** [comment]
@libao0412 kghost的仓库里不是直接有nginx的配置文件吗？
脚本目前不能配置反代的url，要改代码：https://github.com/ipcjs/bilibili-helper/commit/1135309b2b86b106d3fe451195e15e5e3ee75d1c

**Comment by libao0412** [comment]
> @libao0412 kghost的倉庫裡不是直接有nginx的配置文件嗎？
> 腳本目前不能配置反代的url，要改代碼：[1135309](https://github.com/ipcjs/bilibili-helper/commit/1135309b2b86b106d3fe451195e15e5e3ee75d1c)

謝謝ipcjs大大的提醒，我有找到配置文件了，一直都沒發現，自己研究很久都用不好。
但目前出現了第二個問題，腳本回傳抓取到的影片源位址都是不能看的
伺服器一般都是抓到如

> cn-xxxx-gd-bcache-xx.acgvideo.com

這種帶有bcache字樣的都訪問不了，還有一部分就先不舉例了
不知道有沒有其他解決方法呢?例如用腳本內的換源功能呢(?

**Comment by ipcjs** [comment]
不知道，你或许可以去问下kghost的作者？
