### ISSUE TITLE
服务器返回异常

### ISSUE THREAD

**Issue by UncleKan** [ipcjs/bilibili-helper#42]
首先申明，我并非光瞎jg试，我看过帮助说明并对照着进行了尝试，也有授权，但是都行不通，关键是我的情况跟上面的不太相符。在安装了这个脚本时候，新番部分的视频我都能看，问题是其他区的视频我看不了了。

原po:

我的chrome在使用这个脚本之后，在html5格式下除了新番和部分视频之外，加载视频内容都会失败，第一次返回服务器返回异常 ([NetworkError] HttpStatusCodeInvalid: 466)， 然后它自己尝试第二次则会返回无法连接服务器或者服务器返回异常 ([NetworkError] Exception: 3104 Failed to fetch)。

![capture](https://user-images.githubusercontent.com/35414710/34974528-66cfc006-fa42-11e7-854a-fc26753924ce.JPG)

**Comment by ipcjs** [comment]
466确实没见过
为什么没用脚本的复制log功能，把log复制过来？

**Comment by ipcjs** [comment]
在这个issue下追踪问题吧 #36 
这条就关掉了
