### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by btteamss** [ipcjs/bilibili-helper#421]
脚本问题：@ipcjs

## 描述

 拉取视频地址失败
原因: 代理服务器临时不可用
- 问题网址：https://www.bilibili.com/bangumi/play/ep268350 美妙☆频道

## 日志

<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss23841/?spm_id_from=333.334.b_62696c695f62616e67756d69.13
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1584892800000,"status":1,"type":2},"watch_progress":{"last_ep_id":268349,"last_ep_index":"59","last_time":-1}}}
log: setAreaLimitSeason ss23841 true
log: /x/web-interface/nav {"uname":"234566","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=53563296&cid=93702532&qn=0&type=&otype=json&ep_id=268349&fnver=0&fnval=16&session=b98a7dd3794f25a92cf6ba8147149fae&module=bangumi
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=54243855&cid=94889106&qn=0&type=&otype=json&ep_id=268350&fnver=0&fnval=16&session=210b564a72466c764a592d4bc526dbc1&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
log: player msg: 代理服务器临时不可用
log: player msg: 代理服务器临时不可用
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：chrome
2. 国家/地区：加拿大

**Comment by jerryy1235** [comment]
脚本问题：@ipcjs

## 描述

拉取视频地址失败
原因: 代理服务器临时不可用
- 问题网址：https://www.bilibili.com/bangumi/play/ss26801

## 日志

<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26801
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"YZUnion","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1593619200000,"status":1,"type":2},"watch_progress":{"last_ep_id":267859,"last_ep_index":"9","last_time":1369}}}
log: setAreaLimitSeason ss26801 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=54247495&cid=94895465&qn=80&type=&otype=json&ep_id=267859&fnver=0&fnval=16&session=b534ebd54fea70dc6723b6620b8731a8&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
</details>

## 其他

1. 浏览器版本：Chrome
2. 国家/地区：USA

**Comment by lucienleigh** [comment]
拉取视频地址失败
原因: 代理服务器临时不可用

两个代理测速都测不出。
所在地，比利时。浏览器 chrome

更新：
视频地址也无法解析了
显示：
error:[object Object]

**Comment by yuankami000** [comment]
拉取视频地址失败
原因: 代理服务器临时不可用

问题网址：https://www.bilibili.com/bangumi/play/ep103743

加拿大，Chrome 74
两个测速都boom了

log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep103743
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"鹿目小圆","isLogin":true,"level":6,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1595001600000,"status":1,"type":2},"watch_progress":{"last_ep_id":103744,"last_ep_index":"9","last_time":90}}}
log: setAreaLimitSeason ep103743 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=10710703&cid=17673567&qn=80&type=&otype=json&ep_id=103743&fnver=0&fnval=16&session=4581c2098287d3138530e8af3144ddd2&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by IRIS-5452** [comment]
biliplus后面的自定义怎么用

**Comment by ipcjs** [comment]
看biliplus的主页
儿童节的常规操作，没什么奇怪的😏

**Comment by fws1998** [comment]
> 看biliplus的主页
> 儿童节的常规操作，没什么奇怪的

儿童节是指明天吗？

**Comment by MarksonChen** [comment]
加拿大，看不了番了。。。
代理服务器换了，没用。昨天晚上不行，今天下午也不行。。

log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep250640
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"绿叶成荫猫满枝","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1560873600000,"status":1,"type":1},"watch_progress":{"last_ep_id":250640,"last_ep_index":"28","last_time":5}}}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=50547023&cid=92190898&qn=80&type=&otype=json&ep_id=250640&fnver=0&fnval=16&session=bab94f7b4066c6e60020b850e8618411&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
log: player msg: 代理服务器临时不可用

![image](https://user-images.githubusercontent.com/46666959/58840099-3d2a5680-8619-11e9-879a-a5ba48969c1a.png)

**Comment by Cathgao** [comment]
中国广东，土豆服没有限制但是加载不出视频，biliplus显示限制。
log: [解除B站区域限制 v7.7.1 (Violentmonkey)] run on: https://www.bilibili.com/bangumi/play/ep268779
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: replace blocked_vip:  server: https://biliplus.ipcjs.top upos_server: cos flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"Cath","isLogin":true,"level":5,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1526400000000,"status":0,"type":1},"watch_progress":{"last_ep_id":268779,"last_ep_index":"11","last_time":0}}}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=56000092&cid=97890425&qn=116&type=&otype=json&ep_id=268779&fnver=0&fnval=16&session=db35cea42707d4292070752dee5a8bb6&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
