### ISSUE TITLE
biliplus的失效，看了一下，似乎凉掉了

### ISSUE THREAD

**Issue by IRIS-5452** [ipcjs/bilibili-helper#422]
脚本问题：@ipcjs

## 描述

biliplus无法正常使用
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他
就单纯崩掉，gg的亚子
1. 浏览器版本：chrome
2. 国家/地区：cn

**Comment by ipcjs** [comment]
#421
