### ISSUE TITLE
拉取视频地址失效

### ISSUE THREAD

**Issue by xtdxb** [ipcjs/bilibili-helper#423]
## 描述
拉取视频地址失效

- 问题网址：
https://www.bilibili.com/bangumi/play/ss26963

## 日志
log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26963
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"夏天的雪碧","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1605456000000,"status":1,"type":2},"watch_progress":{"last_ep_id":268180,"last_ep_index":"17","last_time":0}}}
log: setAreaLimitSeason ss26963 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=53750209&cid=94022221&qn=112&type=&otype=json&ep_id=268180&fnver=0&fnval=16&session=32f035e8e25bda7df3ddc13493decdbf&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

## 其他

1. 浏览器版本：360极速浏览器
2. 国家/地区：大陆

**Comment by mrvx666** [comment]
chrome  74.0.3729.169 同样的问题
测试番剧https://www.bilibili.com/bangumi/play/ss26963/?spm_id_from=333.334.b_62696c695f62616e67756d69.10

log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26963/?spm_id_from=333.334.b_62696c695f62616e67756d69.10
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"谁注册我的IDmrvx","isLogin":true,"level":4,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1522684800000,"status":0,"type":1},"watch_progress":{"last_ep_id":268180,"last_ep_index":"17","last_time":-1}}}
log: setAreaLimitSeason ss26963 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=53750209&cid=94022221&qn=64&type=&otype=json&ep_id=268180&fnver=0&fnval=16&session=ed3f6f178ff92a24a94298f8b23a76ac&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by ipcjs** [comment]
#421

**Comment by JKKLLSLFS** [comment]
421贴好像没有解决方法

**Comment by ipcjs** [comment]
@JKKLLSLFS 能有什么解决办法，儿童节呀！你要解决***么？
