### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by dumumu** [ipcjs/bilibili-helper#426]
脚本问题：@ipcjs

## 描述

log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26959
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip: Y server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"黎寐暮栖","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vip_info":{"due_date":1581004800000,"status":1,"type":2}}}
log: setAreaLimitSeason ss26959 true
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=48531982&cid=84995275&qn=0&type=&otype=json&ep_id=268048&fourk=1&fnver=0&fnval=16&session=66da81baa8035c9e1fbac3d1ac07c950&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
- 问题网址：
https://www.bilibili.com/bangumi/play/ss26959

## 日志

<details>
<summary>Verbose 日志</summary>

```log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26959
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip: Y server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"黎寐暮栖","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vip_info":{"due_date":1581004800000,"status":1,"type":2}}}
log: setAreaLimitSeason ss26959 true
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=48531982&cid=84995275&qn=0&type=&otype=json&ep_id=268048&fourk=1&fnver=0&fnval=16&session=66da81baa8035c9e1fbac3d1ac07c950&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by yueqixin123** [comment]
log: [解除B站区域限制 v7.6.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26957
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"零七七","isLogin":true,"level":4,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1560787200000,"status":1,"type":1},"watch_progress":{"last_ep_id":268019,"last_ep_index":"9","last_time":1}}}
log: setAreaLimitSeason ss26957 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=54175555&cid=94771630&qn=80&type=&otype=json&ep_id=268019&fnver=0&fnval=16&session=4576f3e1eda31e47f0956131f05edd5b&module=bangumi
log: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by ipcjs** [comment]
#421
