### ISSUE TITLE
无限提示 突破黑洞失败 要求登陆

### ISSUE THREAD

**Issue by AriaDenka** [ipcjs/bilibili-helper#43]
log: [解除B站区域限制 v6.4.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss21680#183799
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"isLogin":true,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183799,"last_ep_index":"1","last_time":15}}}
log: setAreaLimitSeason ss21680 true
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=29892777|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=15956580064e85f6d4b235ae0b7ccb3a
error: >>area limit
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=29892777|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=f32f46e637fa3514918ece365eb97eac
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by AriaDenka** [comment]
无限提示 突破黑洞失败 要求登陆。 但是我登陆这账户 和 授权了N 边

**Comment by Roentgeni** [comment]
遇到同样的问题 Chrome Version 63.0.3239.132 (Official Build) (64-bit)
The SSL certificate used to load resources from https://s1.hdslb.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 log: [解除B站区域限制 v6.4.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss21754#173156
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: undefined readyState: loading isLogin: true isLoginBiliBili: true
bangumi-play.a5569cd4.js:1 The SSL certificate used to load resources from https://static.hdslb.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
handerResize @ bangumi-play.a5569cd4.js:1
n @ vendor.a5569cd4.js:11
addSettingsButton @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:1549
util_init @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:1693
(anonymous) @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:183
callbacks.(anonymous function).sort.filter.forEach.item @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:230
dcl @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:230
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 log: /x/web-interface/nav Object
ss21754#173156:1 Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.
ss21754#173156:1 The SSL certificate used to load resources from https://data.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ss21754#173156:1 The SSL certificate used to load resources from https://i2.hdslb.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ss21754#173156:1 The SSL certificate used to load resources from https://api.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ss21754#173156:1 The SSL certificate used to load resources from https://bangumi.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":173156,"last_ep_index":"2","last_time":1430}}}
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 log: setAreaLimitSeason ss21754 true
ss21754#173156:1 The SSL certificate used to load resources from https://www.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ss21754#173156:1 The SSL certificate used to load resources from https://message.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ss21754#173156:1 The SSL certificate used to load resources from https://big.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=29892136|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=315392957e5f0f77ca132fce12234140
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 error: >>area limit
(anonymous) @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168
processProxySuccess @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:1095
param.success @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:843
o @ jquery.min.js:2
fireWith @ jquery.min.js:2
w @ jquery.min.js:4
d @ jquery.min.js:4
value @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:766
cn-zjwz-dx-v-10.acgvideo.com/vg1/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1516233600&platform=ios&ssig=rrr_vuPQZInR5tvDGadVlw&oi=3078818617&nfa=QY4gbJYKJs7cixEssSU8nA==&dynamic=1&hfa=2020404139&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM= Failed to load resource: the server responded with a status of 460 ()
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=29892136|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=690e5c6f2c67bd049d886affb6f210ac
userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168 error: >>area limit
(anonymous) @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:168
processProxySuccess @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:1095
param.success @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:843
o @ jquery.min.js:2
fireWith @ jquery.min.js:2
w @ jquery.min.js:4
d @ jquery.min.js:4
value @ userscript.html?id=950d7512-c1ed-4a66-b23f-04921e08299d:766
ss21754#173156:1 The SSL certificate used to load resources from https://cn-zjwz-dx-v-10.acgvideo.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
cn-zjwz-dx-v-10.acgvideo.com/vg1/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1516233900&platform=ios&ssig=jaRmEJ6OxYc57pURYK8zIA&oi=3078818617&nfa=QY4gbJYKJs7cixEssSU8nA==&dynamic=1&hfa=2020403359&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM= Failed to load resource: the server responded with a status of 460 ()

**Comment by ipcjs** [comment]
换个服务器

**Comment by 1343686204** [comment]
怎么换服务器呀？
