### ISSUE TITLE
点开任何港澳台番剧都显示无法找到视频

### ISSUE THREAD

**Issue by wylb0198** [ipcjs/bilibili-helper#433]
没有问题网址，直接从B站打开的番就会显示无法找到视频，而如果已经有不是av号结尾的链接则可以正常观看。
![捕获1](https://user-images.githubusercontent.com/41237294/59570473-1ebd6400-90cb-11e9-9adb-ce464a31fc0f.PNG)

**Comment by ipcjs** [comment]
7.7.2
