### ISSUE TITLE
再点击账号授权后无法进行授权

### ISSUE THREAD

**Issue by Waluxs** [ipcjs/bilibili-helper#434]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by Waluxs** [comment]
提示：客户端和服务器不支持一般 SSL 协议版本或加密套件

**Comment by Waluxs** [comment]
使用的是Chrome v49.0

**Comment by ipcjs** [comment]
请用最新版chrome
