### ISSUE TITLE
老版edge可全功能使用脚本

### ISSUE THREAD

**Issue by PT-card** [ipcjs/bilibili-helper#443]
实测非chrome内核dege可用，（开了adblock也能用）版本号见图
![image](https://user-images.githubusercontent.com/42504283/60439828-10805380-9c46-11e9-8ee1-ff3f29438343.png)
![image](https://user-images.githubusercontent.com/42504283/60439857-22fa8d00-9c46-11e9-917d-e0efa17caa7e.png)
![image](https://user-images.githubusercontent.com/42504283/60439948-50473b00-9c46-11e9-90d2-9fc592dc5f30.png)

**Comment by ipcjs** [comment]
某些情况下用不了的
