### ISSUE TITLE
非常卡，切换upos没有用

### ISSUE THREAD

**Issue by trutran233** [ipcjs/bilibili-helper#444]
log: [解除B站区域限制 v7.7.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26963#268177
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"さすらい散る花","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1616860800000,"status":1,"type":2},"watch_progress":{"last_ep_id":268177,"last_ep_index":"14","last_time":7}}}
log: setAreaLimitSeason ss26963 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=51549723&cid=90232794&qn=64&type=&otype=json&ep_id=268177&fnver=0&fnval=16&session=0783c58c4848251dc97b2be46d5fa976&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

很卡，总之就是非常卡。能正常打开港澳台番剧，但是非常卡，网速没问题

**Comment by ipcjs** [comment]
港澳台切upos没用，要改hosts，看脚本的readme
