### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by icl322** [ipcjs/bilibili-helper#449]
脚本问题：@ipcjs
log: [解除B站区域限制 v7.7.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep251231?from=search&seid=14206040483249466162
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: injectAjax at: function (a,b){return new e.fn.init(a,b,h)}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"丨Neptune丶","isLogin":true,"level":3,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":0,"status":0,"type":0},"watch_progress":{"last_ep_id":251231,"last_ep_index":"1","last_time":0}}}
log: setAreaLimitSeason ep251231 true
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=33021084&cid=57799098&qn=64&type=&otype=json&ep_id=251231&fnver=0&fnval=16&session=7793607fddba08a416b46408f2a8f8a6&module=bangumi
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=33021084&cid=57799098&qn=64&type=&otype=json&ep_id=251231&module=bangumi
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=33021084&cid=57799098&qn=16&type=&otype=json&ep_id=251231&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

1. 浏览器版本：360安全浏览器
2. 国家/地区：中国

**Comment by ipcjs** [comment]
换成biliplus试试
