### ISSUE TITLE
番剧可以打开但加载过慢 缓冲十分钟看一分钟

### ISSUE THREAD

**Issue by WHYWELOSE** [ipcjs/bilibili-helper#450]
log: [解除B站区域限制 v7.7.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28022/?spm_id_from=333.334.b_62696c695f62616e67756d69.32
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: oss flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":276933,"last_ep_index":"2","last_time":0},"sponsor":0,"vip_info":{"due_date":1581609600000,"status":1,"type":2}}}
log: setAreaLimitSeason ss28022 true
log: /x/web-interface/nav {"uname":"FateFadeAway","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=58886049&cid=102660218&qn=112&type=&otype=json&ep_id=276933&fourk=1&fnver=0&fnval=16&session=e0aa3fd3180fdf927b9325ce2e842497&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by WHYWELOSE** [comment]
并不是自身网络问题  看其他内陆番剧秒加载

**Comment by WHYWELOSE** [comment]
更换upos服务器也木大哒QwQ

**Comment by WHYWELOSE** [comment]
问题基本解决了   处在host文件上  我把之前自己写进去的东西注释掉就好使了

**Comment by czfls** [comment]
您好，之前因为origin下载的原因改过hosts，目前看番剧也出现了卡到爆的情况，请问该如何处理，是重置hosts嘛？

**Comment by WHYWELOSE** [comment]
> 您好，之前因为origin下载的原因改过hosts，目前看番剧也出现了卡到爆的情况，请问该如何处理，是重置hosts嘛？

你可以试试  我重置host后好用了几天  但是最近又不太好使了  如果你在北京或者东北 或许会更容易出现这种状况  还有 win10商店里有一个uwp版bilibili  是可以直接看区域限制的番的

**Comment by ipcjs** [comment]
#401
