### ISSUE TITLE
host文件修改無效

### ISSUE THREAD

**Issue by David20210** [ipcjs/bilibili-helper#451]
就算host文件內部已更改節點，
在看番劇時依然是hz-mirrorakam.akamaized.net
我要如何換成其他節點?

**Comment by David20210** [comment]
補充，這個節點在看舊番的時候特別慢，幾乎小於100kb/s

**Comment by ipcjs** [comment]
你是改成哪个ip了？ping一下看多少毫秒

**Comment by David20210** [comment]
在台灣推薦哪一個ip?

**Comment by ipcjs** [comment]
在这个网页ping出的ip地址里找：<http://ping.chinaz.com/upos-hz-mirrorakam.akamaized.net>

**Comment by David20210** [comment]
那我要怎麼改ip啊?

**Comment by ipcjs** [comment]
http://letmegooglethat.com/?q=%E4%BF%AE%E6%94%B9hosts
