### ISSUE TITLE
7.7.3版本是否不再支持upos切换？

### ISSUE THREAD

**Issue by chenmt** [ipcjs/bilibili-helper#452]
你好，
  脚本更新至7.7.3版本后控制台的upos设置控件消失了，新脚本是否不再支持upos切换？

**Comment by KirkXL** [comment]
對啊, 怎麼沒有了...

**Comment by ipcjs** [comment]
这个功能还有用吗？
我看着貌似没用就隐藏了😅

**Comment by changharry** [comment]
海外党表示很有用啊 😢

**Comment by chenmt** [comment]
> 这个功能还有用吗？
> 我看着貌似没用就隐藏了😅

国内党表示也很有用😢

**Comment by ipcjs** [comment]
居然有用。。。7.7.4重新显示出来了
