### ISSUE TITLE
部分番剧无限小电视

### ISSUE THREAD

**Issue by 11111111111ge1** [ipcjs/bilibili-helper#457]
## 描述
观看绝大多数港澳台番剧会出现无限小电视的问题
网址以bilibili.com/bangumi/play/ss开头的番剧无法加载评论区及侧边推荐栏
![2019-08-07 (1)](https://user-images.githubusercontent.com/39661677/62625603-20333c00-b958-11e9-86b2-f92b25bfddf4.png)

而网址以bilibili.com/bangumi/play/ep开头的番剧却可以正常加载除视频即弹幕外的所有内容
![image](https://user-images.githubusercontent.com/39661677/62625647-3d680a80-b958-11e9-8722-1c62e693f7b7.png)

有例外情况 https://www.bilibili.com/bangumi/play/ep96708 此系列可以正常加载
今天下午看是正常的，但晚上看就不行了，未添加或更新任何插件
## 日志

<details>
<summary>Verbose 日志</summary>
log: [解除B站区域限制 v7.7.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep276765
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":1,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":276765,"last_ep_index":"5","last_time":64},"sponsor":0,"vip_info":{"due_date":1625155200000,"status":1,"type":2}}}
log: /x/web-interface/nav {"uname":"廉价水军","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /x/web-interface/nav {"uname":"廉价水军","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=61562777&cid=107075069&qn=116&type=&otype=json&ep_id=276765&fourk=1&fnver=0&fnval=16&session=a20679dcbcdf5e8fe95e4c43515d2ab5&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

</details>

## 其他
1. 浏览器版本：Google Chrome 76.0.3809.100（正式版本） （64 位）
2. 国家/地区：中国大陆     

3. 已尝试的解决方法

- 恢复已修改的hosts

- 暂时禁用其他所有脚本

- 通过油猴插件重置脚本

**Comment by realLyans** [comment]
顶一个，同样情况路过。大陆番剧也不能看。
坐标悉尼
Chrome 75.0.3770.142
已尝试重新安装插件

**Comment by OiCkilL** [comment]
大陆的番剧也有相同问题

**Comment by ipcjs** [comment]
确实。。。我看看

**Comment by kerefe** [comment]
切回旧版试试

**Comment by azurechen97** [comment]
实测切回旧版可以解决

**Comment by ipcjs** [comment]
MMP，接口改了个大小写，我说怎么debugger了半年也找不到报错的地方的(╯°口°)╯(┴—┴

更新7.7.5，有问题再反馈( ´_ゝ｀)
