### ISSUE TITLE
视频界面一直显示正在拉取地址

### ISSUE THREAD

**Issue by DD1ng-c** [ipcjs/bilibili-helper#459]
**修改host无法解决问题，使用vpn全局模式也无法拉取地址**
**以下是日志**
log: [解除B站区域限制 v7.7.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep276732
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: kodo flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: /x/web-interface/nav {"uname":"DD1ng-c","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":276731,"last_ep_index":"5","last_time":-1},"sponsor":0,"vip_info":{"due_date":1602086400000,"status":1,"type":2}}}
log: setAreaLimitSeason ep276732 true
log: /x/web-interface/nav {"uname":"DD1ng-c","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
log: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
log: season_type: 1
log: playurl add 'module=bangumi' param
log: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=62613123&cid=108801290&qn=116&type=&otype=json&ep_id=276732&fourk=1&fnver=0&fnval=16&session=8978a0ae18599dd7ffa2add195ed6a11&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by Kizuna-AII** [comment]
似乎把代理服务器设置为
https://hd.pilipili.com
就能解决了呢

**Comment by ipcjs** [comment]
#457
