### ISSUE TITLE
登陆bilibili时提示无效域名 biliplus已无法登陆

### ISSUE THREAD

**Issue by KingSola** [ipcjs/bilibili-helper#461]
log: [解除B站区域限制 v6.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28016/?spm_id_from=333.334.b_62696c695f62616e67756d69.11
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"King_Sola","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1631030400000,"status":1,"type":2}}}
log: setAreaLimitSeason ss28016 false
log: /x/web-interface/nav {"uname":"King_Sola","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Comment by ipcjs** [comment]
你的版本太老了吧
