### ISSUE TITLE
08/16 脚本失效

### ISSUE THREAD

**Issue by yifanlyf** [ipcjs/bilibili-helper#462]
脚本失效，港澳台视频显示无权限，大陆番剧无限小电视（试了几次发现是有概率可以刷出来）

脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by XieXiaojie-Cheryl** [comment]
英国地区 内地版权番显示无权限

**Comment by rcyggdra** [comment]
ep链接失效，从ss或者av链接进去吧。

**Comment by ipcjs** [comment]
更新 7.8.0
