### ISSUE TITLE
这里是7.8.0版本，打开B站港台地区番剧总是显示“脚本加载时机不对，可能不生效”，以前没有这个问题，而且脚本总会加载B站所有视频，导致正常看视频得加载很长时间，希望优化

### ISSUE THREAD

**Issue by Eric1930642479** [ipcjs/bilibili-helper#464]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
浏览器是啥？日志呢？毛都没有我怎么给建议？？

**Comment by 11111111111ge1** [comment]
> 浏览器是啥？日志呢？毛都没有我怎么给建议？？

我也有类似的问题 不过只有非港澳台番剧才会出现提示，港澳台番反而能正常加载
![Q0PBNCW V2@10K77%SM9%`W](https://user-images.githubusercontent.com/39661677/64000335-13a99a00-cb38-11e9-8d99-3b429592f56d.png)
点确定刷新界面 点取消关闭脚本并刷新界面 貌似没法导出日志 
地区：中国大陆
浏览器：Google Chrome 版本 76.0.3809.132（正式版本） （64 位）
（咋我每次都能碰到这种莫名其妙的bug_(:3」∠)_

**Comment by Eric1930642479** [comment]
我就很奇葩了，港澳台和非港澳台都有这个问题，而且我发现这个脚本貌似会加载逼站所有视频，不管是不是港澳台，最明显的就是看普通视频加载时间变长了，不用脚本都是秒加载。



---原始邮件---
发件人: "11111111111ge1"<notifications@github.com&gt;
发送时间: 2019年8月30日(星期五) 下午3:13
收件人: "ipcjs/bilibili-helper"<bilibili-helper@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Eric1930642479"<783992681@qq.com&gt;;
主题: Re: [ipcjs/bilibili-helper] 这里是7.8.0版本，打开B站港台地区番剧总是显示“脚本加载时机不对，可能不生效”，以前没有这个问题，而且脚本总会加载B站所有视频，导致正常看视频得加载很长时间，希望优化 (#464)


 
浏览器是啥？日志呢？毛都没有我怎么给建议？？
  
我也有类似的问题 不过只有非港澳台番剧才会出现提示，港澳台番反而能正常加载
 
 点确定刷新界面 点取消关闭脚本并刷新界面 貌似没法导出日志
 地区：中国大陆
 浏览器：Google Chrome 版本 76.0.3809.132（正式版本） （64 位）
 （咋我每次都能碰到这种莫名其妙的bug_(:3」∠)_

**Comment by Eric1930642479** [comment]
> 浏览器是啥？日志呢？毛都没有我怎么给建议？？

debug: [解除B站区域限制 v7.8.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep277100
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
debug: /x/web-interface/nav {"uname":"恩怨如尘","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1529510400000,"status":0,"type":1},"watch_progress":{"last_ep_id":277100,"last_ep_index":"9","last_time":1424}}}
debug: setAreaLimitSeason ep277100 true
debug: /x/web-interface/nav {"uname":"恩怨如尘","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=66132623&cid=114710374&qn=0&type=&otype=json&ep_id=277100&fnver=0&fnval=16&session=ac62144a9a6750f9e60b8c366c65b2fa&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Comment by Eric1930642479** [comment]
> 浏览器是啥？日志呢？毛都没有我怎么给建议？？

浏览器是谷歌浏览器

**Comment by ipcjs** [comment]
看下是不是开启了“在av页面启用”选项
