### ISSUE TITLE
希望增加使用复制粘贴cookie入口

### ISSUE THREAD

**Issue by sileence114** [ipcjs/bilibili-helper#466]
我一个同学要问我借大会员，但是也不想直接把密码告诉他。所以我想把我的cookie给他。

建议加个“导出”按钮(复制cookie到剪贴板)和“cookie登录”输入框(粘贴cookie)

**Comment by ipcjs** [comment]
f12

**Comment by Qixingchen** [comment]
你这个扫码登入不就行了(
