### ISSUE TITLE
Android平板无法授权账户

### ISSUE THREAD

**Issue by SDM855** [ipcjs/bilibili-helper#467]
尝试了Android上的kiwi browser, Yandex, Firefox安装了插件

不过都会出现code-403错误 且无法授权账号

点击账号授权会跳转至link.acg.tv论坛

无法像PC那样跳转回番剧页面并完成授权

请问有没有什么解决办法 谢谢

**Comment by ipcjs** [comment]
是不是跳转到一个网址为`link.acg.tv/forum.php`的手机版网页上？
点页面下方的“电脑版”，然后重新授权，就能授权成功了😅
