### ISSUE TITLE
是否应该放弃GM4 将函数抽离

### ISSUE THREAD

**Issue by arrebole** [ipcjs/bilibili-helper#468]
或者先做一个接口统计一下 各个插件用户数量

**Comment by ipcjs** [comment]
GM不是脚本鼻祖吗？为什么要放弃？能支持就支持呗

用户数量统计，脚本的安装页面不是有这个功能吗？

**Comment by arrebole** [comment]
都集中在一个函数中，是否会难以维护？或者压力主要在服务器上？

**Comment by ipcjs** [comment]
维护起来确实有点蛋疼😅

不过要解决代码乱的问题的话，应该拆分文件，最好是用ts重写，然后用那堆乱七八糟的打包工具打包成一个user.js，要求不影响GM4

不过现在的代码又不是不能跑，懒得搞🤪

**Comment by arrebole** [comment]
其实我是想帮助重构一下，但是看着都在一个函数里的，慌了。

**Comment by ipcjs** [comment]
放一个函数只是为了方便转换成string，函数里面还是有分功能的，`const util_xxx`之类的。
不过改着改着也就越来越乱了
说到底，一个文件里面塞两三千行，怎么写都感觉乱（

**Comment by arrebole** [comment]
我尝试过使用webpack但是打包后使用里面使用了eval ，然后...运行的时候 eval不是函数

**Comment by ipcjs** [comment]
那堆打包工具配置贼鸡儿复杂😅
