### ISSUE TITLE
谷歌浏览器无法观看

### ISSUE THREAD

**Issue by 171563857** [ipcjs/bilibili-helper#469]
debug: [解除B站区域限制 v7.8.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep276509?spm_id_from=333.334.b_62696c695f62616e67756d69.17
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: window.__PGC_USERSTATE__ {"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":276508,"last_ep_index":"6","last_time":5},"sponsor":0,"vip_info":{"due_date":1588262400000,"status":1,"type":2}}
debug: /x/web-interface/nav {"uname":"陌路枯树","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=65060950&cid=112927275&qn=112&type=&otype=json&ep_id=276509&fourk=1&fnver=0&fnval=16&session=56cff89aa5e654345b12fdf67eebc2ad&module=bangumi
debug: /x/web-interface/nav {"uname":"陌路枯树","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /pgc/player/web/playurl proxy(redirect) {"code":-403,"error":"returned cid not requested","message":"没有观看此付费视频的权限　Video requires payment","errorcid":"28453487","raw_return":{"accept_description":["流畅 360P"],"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15083,"order":1,"size":866787,"url":"https://cn-zjwz4-dx-v-05.acgvideo.com/upgcxcode/87/34/28453487/28453487-1-16.mp4?expires=1566819000&platform=ios&ssig=lZoEmJVUzqvDbwiVsgiM6g&oi=3078818617&trid=e68029f887cd4a13b577b3db6f347dbd&nfb=maPYqpoel5MI3qOUX6YpRA==&nfc=1&mid=0"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15083},"loginStatus":{"isLogin":false}}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=65060950&cid=112927275&qn=112&type=&otype=json&ep_id=276509&fourk=1&fnver=0&fnval=16&session=0f6d4fb9c5ae039c426da60f82804955&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
debug: balh_server_inner  =>  https://www.biliplus.com

**Comment by ipcjs** [comment]
登录一下biliplus
