### ISSUE TITLE
開啟解除b站地區限制腳本 7.8.0 無法讀取彈幕以及清晰度

### ISSUE THREAD

**Issue by tkp206093** [ipcjs/bilibili-helper#470]
脚本问题：@ipcjs

## 描述

無法讀取彈幕以及清晰度
普通的av號沒有問題
但是後綴這個的bangumi/play/ep全部都是這樣
![image](https://user-images.githubusercontent.com/29872453/63888582-d0eda200-ca11-11e9-90cc-9900eaac39f0.png)
![image](https://user-images.githubusercontent.com/29872453/63888609-e2cf4500-ca11-11e9-92e2-e38e47c40157.png)

- 问题网址：https://www.bilibili.com/bangumi/play/*

## 日志
debug: [解除B站区域限制 v7.8.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep4639
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
debug: window.__PGC_USERSTATE__ {"area_limit":0,"ban_area_show":1,"follow":1,"follow_status":2,"login":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":4638,"last_ep_index":"9","last_time":-1},"sponsor":0,"vip_info":{"due_date":1526400000000,"status":0,"type":1}}
debug: window.__playinfo__ {"accept_format":"flv,flv720,flv360","code":0,"seek_param":"start","is_preview":0,"fnval":16,"video_project":true,"fnver":0,"type":"FLV","bp":0,"result":"suee","seek_type":"offset","vip_type":1,"from":"local","video_codecid":7,"durl":[{"size":30025564,"ahead":"","length":354667,"vhead":"","backup_url":["https://upos-hz-mirrorwcsu.acgvideo.com/upgcxcode/33/34/353433/353433-1-80.flv?e=ig8euxZM2rNcNbN1hwdVhoMghWdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1567029350&gen=playurl&os=wcsu&oi=2101024049&trid=dd7a53ea856848a4bcc633c31e404452p&platform=pc&upsig=9367ec01a52dce6b9fd2ec675beceeb6&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=1725113"],"url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/33/34/353433/353433-1-80.flv?e=ig8euxZM2rNcNbN1hwdVhoMghWdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1567029350&gen=playurl&os=akam&oi=2101024049&trid=dd7a53ea856848a4bcc633c31e404452p&platform=pc&upsig=abbafc763d538bfeee7f6ea949528b3d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1567029350~hmac=1b302e0d0841fa12896e84c5265234c304fa31f77237d3ce3a920fa21eb8a913&mid=1725113","order":1,"md5":""},{"size":18763561,"ahead":"","length":257131,"vhead":"","backup_url":[],"url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/33/34/353433/353433-2-80.flv?e=ig8euxZM2rNcNbR3hwdVhoM1nwdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1567029350&gen=playurl&os=akam&oi=2101024049&trid=dd7a53ea856848a4bcc633c31e404452p&platform=pc&upsig=8e9da7ce7f082ef5029e5d0ef210b74b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1567029350~hmac=f5126b300f31e3caecab6bbe58e39eb4a534e4ad724e4b64e80c7138dcf9f553&mid=1725113","order":2,"md5":""},{"size":28262678,"ahead":"","length":388059,"vhead":"","backup_url":[],"url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/33/34/353433/353433-3-80.flv?e=ig8euxZM2rNcNbR3hwdVhoM1nwdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1567029350&gen=playurl&os=akam&oi=2101024049&trid=dd7a53ea856848a4bcc633c31e404452p&platform=pc&upsig=95b1c200f3e3e57c4e1cfa14c48cb9c0&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1567029350~hmac=9ca828340ccf002b65385ab5a27162770b60836204f741aea907faa903bc5914&mid=1725113","order":3,"md5":""},{"size":34585854,"ahead":"","length":399759,"vhead":"","backup_url":[],"url":"https://upos-hz-mirrorakam.akamaized.net/upgcxcode/33/34/353433/353433-4-80.flv?e=ig8euxZM2rNcNbN17WdVhoMghWUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1567029350&gen=playurl&os=akam&oi=2101024049&trid=dd7a53ea856848a4bcc633c31e404452p&platform=pc&upsig=04e4b2dc12ca7030404b53c5ebce0981&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1567029350~hmac=53682a69a750fa723a43a47ee49b8b20faabc92211403eadd2b642684e46bd16&mid=1725113","order":4,"md5":""}],"no_rexcode":0,"format":"flv","message":"","accept_quality":[80,64,16],"quality":80,"timelength":1399616,"has_paid":false,"vip_status":0,"accept_description":["高清 1080P","高清 720P","流畅 360P"],"status":2}
debug: /x/web-interface/nav {"uname":"tkp206093","isLogin":true,"level":6,"vipType":1,"vipStatus":0,"isFromReport":true}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"tkp206093","isLogin":true,"level":6,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: balh_mode  =>  default
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：360極速瀏覽器 v11.0.2179.0 (Google chrome內核:69.0.3497.100)
2. 国家/地区：香港特別行政區

**Comment by tkp206093** [comment]
直接把脚本里面这一行删掉：
// @include *://www.bilibili.com/bangumi/play/ep*

可暫時解決問題
但會導致這個連結下面的番劇無法可以尋找到脚本選項

這樣只能解決燃眉之急 自標不治本
希望偉大的作者你早日可以找到解決方法並修復

謝謝你們的付出

**Comment by ipcjs** [comment]
7.8.1 修复

**Comment by tkp206093** [comment]
感謝你的修復

**Comment by tkp206093** [comment]
今天問題依舊
剷除// @include ://www.bilibili.com/bangumi/play/ep直接無法翻牆

**Comment by tkp206093** [comment]
如果有問題的時候再返選集列表 選擇其他集數 然後選擇最新的一集的時候就會沒有事

但一按F5刷新 馬上又出事

**Comment by ipcjs** [comment]
😣我明天再看下吧

**Comment by ipcjs** [comment]
还是这个url吗？https://www.bilibili.com/bangumi/play/ep4639 我试着没问题呀(-_-#)

**Comment by tkp206093** [comment]
https://www.bilibili.com/bangumi/play/ss28059

隨便首頁一個翻牆地區新番

**Comment by tkp206093** [comment]
https://github.com/ipcjs/bilibili-helper/issues/471

詳情可以看看這篇討論

**Comment by ipcjs** [comment]
441025c0bbe7745be5a6f583a7a75d1364aaa56a 这下总不会有问题了吧🤔

**Comment by tkp206093** [comment]
感謝修復希望沒有再有問題
如有問題會馬上相告謝謝!~
