### ISSUE TITLE
拉取失败啊大大

### ISSUE THREAD

**Issue by 1zhangkehan** [ipcjs/bilibili-helper#484]
debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss12044/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: /x/web-interface/nav {"uname":"墙角一寸毛","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":true}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=13662970&cid=22620491&qn=80&type=&otype=json&ep_id=118250&fourk=1&fnver=0&fnval=16&session=99f69d1e108755d4111ede040a81ce2a&module=bangumi
debug: /x/web-interface/nav {"uname":"墙角一寸毛","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":3360769129,"length":6400406,"url":"https://video-ru.biliplus.com/file/4883549e30c39eb77f34f3a6811d01aa/1568675605/533543506/1IZROAhQmnHT32qss3QJHOpmrI8nskffG/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"墙角一寸毛","mid":5425586,"level":5,"vip_expire":0}},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=13662970&cid=22620491&qn=80&type=&otype=json&ep_id=118250&fourk=1&fnver=0&fnval=16&session=ed560029c3296900dac9cf2e34c30586&module=bangumi&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":3360769129,"length":6400406,"url":"https://video-ru.biliplus.com/file/19c675f175ecc723bf8d50a28d73ed62/1568675606/533543506/1IZROAhQmnHT32qss3QJHOpmrI8nskffG/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"墙角一寸毛","mid":5425586,"level":5,"vip_expire":0}}
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=13662970&cid=22620491&qn=16&type=&otype=json&ep_id=118250&fourk=1&fnver=0&fnval=16&session=ed560029c3296900dac9cf2e34c30586&module=bangumi&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":3360769129,"length":6400406,"url":"https://video-ru.biliplus.com/file/7f9fba557c6b35ced34f198d8379a750/1568675608/533543506/1IZROAhQmnHT32qss3QJHOpmrI8nskffG/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"墙角一寸毛","mid":5425586,"level":5,"vip_expire":0}}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by ipcjs** [comment]
fixed
