### ISSUE TITLE
电影看不了了大大

### ISSUE THREAD

**Issue by Miserablewww** [ipcjs/bilibili-helper#485]
坐标英国
浏览器：Google Chrome
能看番剧，但是电影都看不了，求救呜呜呜

debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28515
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: ks3 flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"Miserable","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: /x/web-interface/nav {"uname":"Miserable","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"dialog":{"btn_right":{"title":"3B币购买","type":"pay"},"desc":"应版权方要求，本片暂不支持B币券支付\n购买后可在48小时内观看","title":"付费开启全片，大会员半价"},"follow":0,"follow_status":2,"login":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vip_info":{"due_date":1626364800000,"status":1,"type":2}}}
debug: setAreaLimitSeason ss28515 true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: null
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=67419581&cid=117155406&qn=116&type=&otype=json&ep_id=283947&fourk=1&fnver=0&fnval=16&session=ebeca5c314138a3b61d35f3458e8f85d
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"Miserable","mid":542534,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Miserable\",\"mid\":542534,\"level\":0,\"vip_expire\":0}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=67419581&cid=117155406&qn=116&type=&otype=json&ep_id=283947&fourk=1&fnver=0&fnval=16&session=ebeca5c314138a3b61d35f3458e8f85d&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"Miserable","mid":542534,"level":0,"vip_expire":0}}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: null
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=67419581&cid=117155406&qn=116&type=&otype=json&ep_id=283947&fourk=1&fnver=0&fnval=16&session=57e32ff1e43cc62a2b63ac600a721108&balh_ajax=1
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"Miserable","mid":542534,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Miserable\",\"mid\":542534,\"level\":0,\"vip_expire\":0}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=67419581&cid=117155406&qn=116&type=&otype=json&ep_id=283947&fourk=1&fnver=0&fnval=16&session=57e32ff1e43cc62a2b63ac600a721108&balh_ajax=1&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"Miserable","mid":542534,"level":0,"vip_expire":0}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by ipcjs** [comment]
付费的。。。太难搞(-_-#)

**Comment by ipcjs** [comment]
汇总到#509
