### ISSUE TITLE
有一些出现了问题

### ISSUE THREAD

**Issue by q790540643** [ipcjs/bilibili-helper#486]
debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28515#283947
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"AB君_","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=67419581&cid=117155406&qn=80&type=&otype=json&ep_id=283947&fourk=1&fnver=0&fnval=16&session=f2304c95c3b83449e9686619ebd4e6a6&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"AB君_","mid":1429731,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"AB君_\",\"mid\":1429731,\"level\":0,\"vip_expire\":0}}","code":-404}
debug: /x/web-interface/nav {"uname":"AB君_","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=67419581&cid=117155406&qn=80&type=&otype=json&ep_id=283947&fourk=1&fnver=0&fnval=16&session=7cc80cc632cb78718e6aa30ee5ad88b7&module=bangumi&balh_ajax=1
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"AB君_","mid":1429731,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"AB君_\",\"mid\":1429731,\"level\":0,\"vip_expire\":0}}","code":-404}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by ipcjs** [comment]
#485

**Comment by ipcjs** [comment]
汇总到#509
