### ISSUE TITLE
您好，请问地区限制的代理规则是什么呀？

### ISSUE THREAD

**Issue by stonerockone** [ipcjs/bilibili-helper#488]
您好，我路由器上有小飞机，我不想全局但又能看地区限制的番剧，那我在强制代理规则应该是什么呀，跪求！谢谢！

**Comment by ipcjs** [comment]
目前有用的应该就是这两个url
https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.user.js#L1272
https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.user.js#L1289
