### ISSUE TITLE
换了代理服务器也刷新很多遍  显示仍有区域限制

### ISSUE THREAD

**Issue by Vlaus** [ipcjs/bilibili-helper#49]
## 描述
刷新很多遍一直显示
![image](https://user-images.githubusercontent.com/35651754/35192083-a3e3cadc-fec5-11e7-90b6-15315f4135ce.png)

## 日志
log: [解除B站区域限制 v6.4.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183799
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"VKather","isLogin":true,"level":2,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183799,"last_ep_index":"1","last_time":0}}}
log: setAreaLimitSeason ep183799 true
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=29892777|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=d44f41b03f9930e1086556a8f8194724
debug: userAgent Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```
<!-- 复制来的日志，粘贴在这里 -->
```

![image](https://user-images.githubusercontent.com/35651754/35192109-3c856a84-fec6-11e7-8a0e-bee6157c77af.png)

## 其他

1. 浏览器版本：
![image](https://user-images.githubusercontent.com/35651754/35192126-84dec488-fec6-11e7-886e-1740405fdef6.png)

2. 国家/地区：中国大陆

**Comment by ipcjs** [comment]
最新版改了提示信息，更新下

**Comment by Vlaus** [comment]
![image](https://user-images.githubusercontent.com/35651754/35195634-74473e26-ff01-11e7-9259-2a90fb17bd84.png)
脚本无可更新的呐  能否具体指导下？

**Comment by ipcjs** [comment]
我弹提示是干嘛的；提示框里面不是写了吗？
“请尝试“帐号授权”或者换个代理服务器”，这么大的字没看到？！！

**Comment by Vlaus** [comment]
别急啊   就是因为无论是授权登陆还是换默认服务器 刷新没用才反馈的

**Comment by ipcjs** [comment]
换成“默认代理服务器”，再授权登录？

**Comment by ipcjs** [comment]
还是不行的话，把日志给我复制过来

**Comment by Vlaus** [comment]
昂  刷新好几遍OK了  感谢po主回复帮忙解决问题！！
