### ISSUE TITLE
无法接触B站区域限制 

### ISSUE THREAD

**Issue by JustinLyu** [ipcjs/bilibili-helper#490]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by JustinLyu** [comment]
无法使用此脚本

**Comment by newhy** [comment]
用得好好的，不描述问题都是流氓

**Comment by newhy** [comment]
> 无法使用此脚本
用得好好的，不描述问题都是流氓

**Comment by newhy** [comment]
> 无法使用此脚本

用得好好的，不描述问题都是流氓
