### ISSUE TITLE
3104 failed to fetch

### ISSUE THREAD

**Issue by anime5167** [ipcjs/bilibili-helper#491]
脚本问题：@ipcjs

## 描述

非一般視頻類(如電影區)都會跳出3104 failed to fetch錯誤
雖然沒了區域限制提示..但也無法載入視頻

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：cent chrome
2. 国家/地区：

**Comment by YuruWu1204** [comment]
一样的问题，请问有办法解决吗？
