### ISSUE TITLE
b站番剧打不开

### ISSUE THREAD

**Issue by TrainerPikachu** [ipcjs/bilibili-helper#492]
debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26826/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=47380559&cid=85300474&qn=80&type=&otype=json&ep_id=267951&fourk=1&fnver=0&fnval=16&session=6c4a7e1873e3c869002b5fb41e591c1b&module=bangumi
debug: /x/web-interface/nav {"uname":"中国少年先疯队大队长","isLogin":true,"level":4,"vipType":1,"vipStatus":0,"isFromReport":true}
debug: /x/web-interface/nav {"uname":"中国少年先疯队大队长","isLogin":true,"level":4,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"中国少年先疯队大队长","mid":209703267,"level":4,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"中国少年先疯队大队长\",\"mid\":209703267,\"level\":4,\"vip_expire\":0}}","code":-404}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=47380559&cid=85300474&qn=80&type=&otype=json&ep_id=267951&fourk=1&fnver=0&fnval=16&session=8a0f59e0c43452b9daebbb0f1cadfcf5&module=bangumi&balh_ajax=1
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"中国少年先疯队大队长","mid":209703267,"level":4,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"中国少年先疯队大队长\",\"mid\":209703267,\"level\":4,\"vip_expire\":0}}","code":-404}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Comment by ipcjs** [comment]
https://github.com/ipcjs/bilibili-helper/commit/aa9ce04aae7c53a7e6c4327ec8fe5a4dbf35b626
