### ISSUE TITLE
看番剧没问题但是看不了放映厅的电影

### ISSUE THREAD

**Issue by DxyWhh** [ipcjs/bilibili-helper#493]
debug: [解除B站区域限制 v7.8.4 (AceScript)] run on: https://www.bilibili.com/bangumi/play/ss28274
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=68400556&cid=118808192&qn=0&type=&otype=json&ep_id=284310&fourk=1&fnver=0&fnval=16&session=def9277a8c0299b57337ce38e8529c5c&module=bangumi
debug: /x/web-interface/nav {"uname":"哎哟我好萌","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"哎哟我好萌","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"哎哟我好萌","mid":1483893,"level":5,"vip_expire":1592064000000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"哎哟我好萌\",\"mid\":1483893,\"level\":5,\"vip_expire\":1592064000000}}","code":-404}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=68400556&cid=118808192&qn=0&type=&otype=json&ep_id=284310&fourk=1&fnver=0&fnval=16&session=633088c4bb65a74ad3178c5aab6d28ba&module=bangumi&balh_ajax=1
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"哎哟我好萌","mid":1483893,"level":5,"vip_expire":1592064000000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"哎哟我好萌\",\"mid\":1483893,\"level\":5,\"vip_expire\":1592064000000}}","code":-404}
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by ipcjs** [comment]
这要@esterTion 

https://www.biliplus.com/BPplayurl.php?avid=68400556&cid=118808192&qn=112&type=&otype=json&ep_id=284310&fourk=1&fnver=0&fnval=16&session=1b98af1be9f9fd53b5dd43284b52cd81&module=bangumi
这个url有一定概率会返回-404。。。

**Comment by esterTion** [comment]
？？

**Comment by ipcjs** [comment]
你多点几下，有的时候能出来有的时候出不来，有点玄学🤔

<del>貌似点开其他动画再点这个链接就出的来😅</del>

**Comment by esterTion** [comment]
我看见了…
像是基于时间的，可能是api问题
毕竟我用的版本挺老的了

**Comment by ipcjs** [comment]
汇总到#509
