### ISSUE TITLE
非番剧类地区限制无法解锁

### ISSUE THREAD

**Issue by fa22zhq** [ipcjs/bilibili-helper#494]
脚本问题：@ipcjs

## 描述

非番剧类地区限制无法解锁观看
- 问题网址：https://www.bilibili.com/bangumi/play/ss23885

## 日志

debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss23885
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"fa22","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1588435200000,"status":1,"type":2},"watch_progress":{"last_ep_id":199427,"last_ep_index":"巴塔哥尼亚特辑（上）","last_time":3711}}}
debug: /x/web-interface/nav {"uname":"fa22","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 3
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=21305669&cid=35052269&qn=80&type=&otype=json&ep_id=199427&fnver=0&fnval=16&session=e02534ca3a5acc41ef646a1b628162cc&module=bangumi&balh_ajax=1
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"fa22","mid":3036006,"level":5,"vip_expire":1588435200000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-404,\"message\":\"结果为空或者已被删除\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"fa22\",\"mid\":3036006,\"level\":5,\"vip_expire\":1588435200000}}","code":-404}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

## 其他

1. 浏览器版本：Chrome77.0.3865.90
2. 国家/地区：日本

**Comment by ipcjs** [comment]
先加个if...else跑起来：https://github.com/ipcjs/bilibili-helper/commit/4b4345ffbb1f8995459b1eb52b6ed19ec693a929
