### ISSUE TITLE
脚本无法使用

### ISSUE THREAD

**Issue by HYY1996** [ipcjs/bilibili-helper#495]
脚本问题：@ipcjs

## 描述

10月1号早上还能用，晚上回来发现打不开了
- 问题网址：https://www.bilibili.com/bangumi/play/ep92393

## 日志

<details>
<summary>Verbose 日志</summary>
</details>
debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep92393
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"破坏CP的企鹅","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"破坏CP的企鹅","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=5389302&cid=10947519&qn=64&type=&otype=json&ep_id=92393&fourk=1&fnver=0&fnval=16&session=f93df5b79f2670174bc7ad6359b5b869&module=bangumi
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=5389302&cid=10947519&qn=64&type=&otype=json&ep_id=92393&fourk=1&fnver=0&fnval=16&session=f93df5b79f2670174bc7ad6359b5b869&module=bangumi
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"accept_format":"hdflv2,flv,flv720,flv480,flv360","code":0,"durl":[{"size":48042129,"ahead":"","length":367065,"vhead":"","backup_url":["https://cn-sh-cc-bcache-13.acgvideo.com/upgcxcode/19/75/10947519/10947519-1-64.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=d478afbed0668b77fe91085a148accb9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-13.acgvideo.com/upgcxcode/19/75/10947519/10947519-1-64.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=d478afbed0668b77fe91085a148accb9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-03.acgvideo.com/upgcxcode/19/75/10947519/10947519-1-64.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=d478afbed0668b77fe91085a148accb9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":1,"md5":""},{"size":46496206,"ahead":"","length":355470,"vhead":"","backup_url":["https://cn-sh-cc-bcache-12.acgvideo.com/upgcxcode/19/75/10947519/10947519-2-64.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=ef2c28848bd474233053253d33792322&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-20.acgvideo.com/upgcxcode/19/75/10947519/10947519-2-64.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=ef2c28848bd474233053253d33792322&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-02.acgvideo.com/upgcxcode/19/75/10947519/10947519-2-64.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=ef2c28848bd474233053253d33792322&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":2,"md5":""},{"size":47747423,"ahead":"","length":363353,"vhead":"","backup_url":["https://cn-sh-cc-bcache-10.acgvideo.com/upgcxcode/19/75/10947519/10947519-3-64.flv?e=ig8euxZM2rNcNbhg7zUVhoMzhbuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=aceac8a3d2c2f5c7b1876c9623cc28f5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-02.acgvideo.com/upgcxcode/19/75/10947519/10947519-3-64.flv?e=ig8euxZM2rNcNbhg7zUVhoMzhbuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=aceac8a3d2c2f5c7b1876c9623cc28f5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-14.acgvideo.com/upgcxcode/19/75/10947519/10947519-3-64.flv?e=ig8euxZM2rNcNbhg7zUVhoMzhbuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=aceac8a3d2c2f5c7b1876c9623cc28f5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":3,"md5":""},{"size":50830138,"ahead":"","length":384463,"vhead":"","backup_url":["https://cn-sh-cc-bcache-13.acgvideo.com/upgcxcode/19/75/10947519/10947519-4-64.flv?e=ig8euxZM2rNcNbhzhwdVhoMzhzdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=1135421d77ec4f14afe43fb7cb2af49a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-13.acgvideo.com/upgcxcode/19/75/10947519/10947519-4-64.flv?e=ig8euxZM2rNcNbhzhwdVhoMzhzdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=1135421d77ec4f14afe43fb7cb2af49a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-03.acgvideo.com/upgcxcode/19/75/10947519/10947519-4-64.flv?e=ig8euxZM2rNcNbhzhwdVhoMzhzdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569981833&gen=playurl&os=bcache&oi=1779414179&trid=9f53aa733b3c46c0b040f6ed1d67bef7p&platform=pc&upsig=1135421d77ec4f14afe43fb7cb2af49a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":4,"md5":""}],"seek_param":"start","is_preview":0,"no_rexcode":0,"format":"flv720","fnval":16,"video_project":true,"fnver":0,"message":"","type":"FLV","accept_quality":[112,80,64,32,16],"bp":0,"quality":64,"timelength":1470351,"result":"suee","seek_type":"offset","has_paid":false,"from":"local","video_codecid":7,"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":2},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

## 其他

1. 浏览器版本：Google Chrome版本 77.0.3865.90 (正式版本) (64 位元)
2. 国家/地区：德国

**Comment by HYY1996** [comment]
都是白天可以使用，一到晚上就连不上服务器

**Comment by ipcjs** [comment]
试试在设置里把服务器改成“土豆服”？
