### ISSUE TITLE
无法观看非港澳台的番

### ISSUE THREAD

**Issue by tyker1** [ipcjs/bilibili-helper#496]
脚本问题：@ipcjs

## 描述

刚看的还好好的 （部分已打开的番剧不受影响）

突然无法观看非港澳台限定的番剧，尝试修改upos服务器，失败，重装脚本，失败，重新授权帐号，502 time out……显示尝试从kghost拉取地址

- 问题网址：所有非港澳台的番剧

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep285131/?spm_id_from=333.334.b_62696c695f62616e67756d69.21
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"Tsukiyomu","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1595001600000,"status":1,"type":2}}}
debug: setAreaLimitSeason ep285131 true
debug: /x/web-interface/nav {"uname":"Tsukiyomu","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=69527663&cid=120504871&qn=112&type=&otype=json&ep_id=285131&fnver=0&fnval=16&session=e2c342c3a5cd680fe0aec392c4fd5e36&module=bangumi&balh_ajax=1
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=69527663&cid=120504871&qn=112&type=&otype=json&ep_id=285131&fnver=0&fnval=16&session=e2c342c3a5cd680fe0aec392c4fd5e36&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
</details>

## 其他

1. 浏览器版本：Chrome
2. 国家/地区：德国

**Comment by HYY1996** [comment]
我也这种情况，早上还能看的，晚上回来打开发现不行了

**Comment by KhasoKun** [comment]
主页502了，服务器炸了么

**Comment by HYY1996** [comment]
是的，主页502了

On 2. Oct 2019, at 00:32, KhasoKun <notifications@github.com<mailto:notifications@github.com>> wrote:


主页502了，服务器炸了么

**Comment by HYY1996** [comment]
感觉应该是服务器的问题

**Comment by Jings-hiGuan** [comment]
前一集番剧还能看，然后就哪个都看不了了，重新授权就一直502超时，是服务器的问题吗？有什么可以替换的代理服务器吗？用的是最新版本的chrome，地区是加拿大

**Comment by HYY1996** [comment]
你的问题解决了吗，同在德国，昨天开始一到晚上就连接失败

**Comment by Jings-hiGuan** [comment]
还是不好使，打开就是链接失效

**Comment by tyker1** [comment]
我这边已经正常了

**Comment by tyker1** [comment]
然后又不正常了。。。港澳台的都没问题。。。大陆的都不行

**Comment by HYY1996** [comment]
就是服务器的问题吧，我在用eduroam的网也打不开
