### ISSUE TITLE
番剧拉取失败，无法连接服务器

### ISSUE THREAD

**Issue by Paul980416** [ipcjs/bilibili-helper#497]
debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep15564?from=search&seid=4198765575700626243
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"白白白白泽HAKU","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=16159830&cid=26372492&qn=0&type=&otype=json&ep_id=15564&fourk=1&fnver=0&fnval=16&session=d21b29081ef9ae6e388dc72c40d6c250&module=bangumi
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=16159830&cid=26372492&qn=0&type=&otype=json&ep_id=15564&fourk=1&fnver=0&fnval=16&session=d21b29081ef9ae6e388dc72c40d6c250&module=bangumi
debug: /x/web-interface/nav {"uname":"白白白白泽HAKU","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"accept_format":"hdflv2,flv,flv720,flv480,flv360","code":0,"durl":[{"size":50770263,"ahead":"","length":384488,"vhead":"","backup_url":["https://cn-sh-cc-bcache-02.acgvideo.com/upgcxcode/92/24/26372492/26372492-1-32.flv?e=ig8euxZM2rNcNbhzhwdVhoMzhzdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=17b37b442d186b055918e5c48a33f98f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-18.acgvideo.com/upgcxcode/92/24/26372492/26372492-1-32.flv?e=ig8euxZM2rNcNbhzhwdVhoMzhzdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=17b37b442d186b055918e5c48a33f98f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-04.acgvideo.com/upgcxcode/92/24/26372492/26372492-1-32.flv?e=ig8euxZM2rNcNbhzhwdVhoMzhzdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=17b37b442d186b055918e5c48a33f98f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":1,"md5":""},{"size":40819876,"ahead":"","length":299905,"vhead":"","backup_url":["https://cn-sh-cc-bcache-09.acgvideo.com/upgcxcode/92/24/26372492/26372492-2-32.flv?e=ig8euxZM2rNcNbhMhwdVhoMz7wdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=3a41e4527e0d0089c4a06ed987b9e38f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-11.acgvideo.com/upgcxcode/92/24/26372492/26372492-2-32.flv?e=ig8euxZM2rNcNbhMhwdVhoMz7wdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=3a41e4527e0d0089c4a06ed987b9e38f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-01.acgvideo.com/upgcxcode/92/24/26372492/26372492-2-32.flv?e=ig8euxZM2rNcNbhMhwdVhoMz7wdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=3a41e4527e0d0089c4a06ed987b9e38f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":2,"md5":""},{"size":51218217,"ahead":"","length":392705,"vhead":"","backup_url":["https://cn-sh-cc-bcache-13.acgvideo.com/upgcxcode/92/24/26372492/26372492-3-32.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=40ffd1ae14975b63b9f5c124a11687ed&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-05.acgvideo.com/upgcxcode/92/24/26372492/26372492-3-32.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=40ffd1ae14975b63b9f5c124a11687ed&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-01.acgvideo.com/upgcxcode/92/24/26372492/26372492-3-32.flv?e=ig8euxZM2rNcNbhg7WdVhoMzhbUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=40ffd1ae14975b63b9f5c124a11687ed&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":3,"md5":""},{"size":47205943,"ahead":"","length":354710,"vhead":"","backup_url":["https://cn-sh-cc-bcache-02.acgvideo.com/upgcxcode/92/24/26372492/26372492-4-32.flv?e=ig8euxZM2rNcNbhzhbUVhoMzhzNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=5cacf83eec676fca36057f3b552bf487&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","https://cn-gdfs2-cc-bcache-14.acgvideo.com/upgcxcode/92/24/26372492/26372492-4-32.flv?e=ig8euxZM2rNcNbhzhbUVhoMzhzNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=5cacf83eec676fca36057f3b552bf487&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0"],"url":"https://cn-bj3-cc-bcache-10.acgvideo.com/upgcxcode/92/24/26372492/26372492-4-32.flv?e=ig8euxZM2rNcNbhzhbUVhoMzhzNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1569988810&gen=playurl&os=bcache&oi=1779414179&trid=75356abac5744cf2b4350203f243473cp&platform=pc&upsig=5cacf83eec676fca36057f3b552bf487&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0","order":4,"md5":""}],"seek_param":"start","is_preview":0,"no_rexcode":0,"format":"flv480","fnval":16,"video_project":true,"fnver":0,"message":"","type":"FLV","accept_quality":[112,80,64,32,16],"bp":0,"quality":32,"timelength":1431808,"result":"suee","seek_type":"offset","has_paid":false,"from":"local","video_codecid":7,"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":2},"message":"0"}
debug: __playinfo__ set
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by HYY1996** [comment]
是不是一到晚上就不行
