### ISSUE TITLE
## 拉取视频地址失败

### ISSUE THREAD

**Issue by Ziggylee1218** [ipcjs/bilibili-helper#502]
debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep284434?from=search&seid=9984696200637476022
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server: cos flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep284434 true
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=69238185&cid=119995514&qn=0&type=&otype=json&ep_id=284434&fourk=1&fnver=0&fnval=16&session=3dcb4635e35581adb33a5a6cde41d238&module=bangumi
debug: /x/web-interface/nav {"uname":"大明湖畔的老李","isLogin":tr

**Comment by ipcjs** [comment]
#493
