### ISSUE TITLE
无法连接服务器或服务器返回异常

### ISSUE THREAD

**Issue by MisakaAlice** [ipcjs/bilibili-helper#503]
## 描述

电视剧第一集不需要大会员可以直接观看，后面仅限大会员的集数会提示“无法连接服务器或服务器返回异常”，已授权账号
- 问题网址：https://www.bilibili.com/bangumi/play/ep269776?from=search&seid=2033568697157321502

## 日志

<details>
<summary>debug: [解除B站区域限制 v7.8.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss20119#269790
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"叫我御坂大人丶","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1598025600000,"status":1,"type":2},"watch_progress":{"last_ep_id":269790,"last_ep_index":"第五话","last_time":1639}}}
debug: /x/web-interface/nav {"uname":"叫我御坂大人丶","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 5
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=49711670&cid=87044439&qn=0&type=&otype=json&ep_id=269790&fnver=0&fnval=16&session=15e65d6d8e0c6f92356288a2757409be&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":1509054055,"length":2003673,"url":"https://video-ru.biliplus.com/file/2ae26b97f87c1b8900ebca349db84f01/1570220560/1854187683/1MVbWLbAcoWrey5g27hFbDFgkmtkZAqJd/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"叫我御坂大人丶","mid":1300367,"level":5,"vip_expire":1598025600000}}
debug: __playinfo__ get
debug: season_type: 5
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=49711670&cid=87044439&qn=16&type=&otype=json&ep_id=269790&fnver=0&fnval=16&session=15e65d6d8e0c6f92356288a2757409be&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":1509054055,"length":2003673,"url":"https://video-ru.biliplus.com/file/c7c63c28b043bcfce4022e03b5318f00/1570220563/1854187683/1MVbWLbAcoWrey5g27hFbDFgkmtkZAqJd/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"叫我御坂大人丶","mid":1300367,"level":5,"vip_expire":1598025600000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Chrome
2. 国家/地区：日本

**Comment by ipcjs** [comment]
汇总到#509
