### ISSUE TITLE
## 拉取视频地址失败

### ISSUE THREAD

**Issue by xhzz161** [ipcjs/bilibili-helper#504]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by xhzz161** [comment]
debug: [解除B站区域限制 v7.8.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep285626
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"天生战狂扣肉包","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1583337600000,"status":1,"type":2},"watch_progress":{"last_ep_id":255360,"last_ep_index":"4","last_time":-1}}}
debug: setAreaLimitSeason ep285626 true
debug: /x/web-interface/nav {"uname":"天生战狂扣肉包","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 3
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=62471760&cid=108569329&qn=116&type=&otype=json&ep_id=285626&fnver=0&fnval=16&session=0a8f4ca5eaa7489fa6a5d3f6897ea6c2&balh_ajax=1
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"天生战狂扣肉包","mid":499948,"level":6,"vip_expire":1583337600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"天生战狂扣肉包\",\"mid\":499948,\"level\":6,\"vip_expire\":1583337600000}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=62471760&cid=108569329&qn=116&type=&otype=json&ep_id=285626&fnver=0&fnval=16&session=0a8f4ca5eaa7489fa6a5d3f6897ea6c2&balh_ajax=1&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"天生战狂扣肉包","mid":499948,"level":6,"vip_expire":1583337600000}}
debug: balh_server_inner  =>  https://www.biliplus.com
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
debug: balh_server_inner  =>  https://biliplus.ipcjs.top
debug: balh_server_inner  =>  https://www.biliplus.com
debug: balh_mode  =>  redirect
debug: balh_mode  =>  default

**Comment by ipcjs** [comment]
统一到#509
