### ISSUE TITLE
无法从播放历史打开视频

### ISSUE THREAD

**Issue by littlesb1990** [ipcjs/bilibili-helper#508]
如果从播放历史打开看过的视频，会显示视频不见了的提示
从番剧界面可以正常观看

debug: [解除B站区域限制 v7.8.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss5761#97543
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"小sb","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1627142400000,"status":1,"type":2},"watch_progress":{"last_ep_id":97543,"last_ep_index":"45","last_time":0}}}
debug: setAreaLimitSeason ss5761 false
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":0,"message":"0","result":{"accept_format":"flv,flv720,flv480,flv360","code":0,"seek_param":"start","is_preview":0,"fnval":16,"video_project":true,"fnver":0,"type":"FLV","bp":0,"result":"suee","seek_type":"offset","vip_type":2,"from":"local","video_codecid":7,"durl":[{"size":85382929,"ahead":"","length":332859,"vhead":"","backup_url":["https://cn-hbsjz-cmcc-bcache-02.acgvideo.com/upgcxcode/98/12/12131298/12131298-1-80.flv?e=ig8euxZM2rNcNbTMhwdVhoMj7wdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=7ca731ad39072f717561fa5ca1c843f5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","https://upos-hz-mirrorkodou.acgvideo.com/upgcxcode/98/12/12131298/12131298-1-80.flv?e=ig8euxZM2rNcNbTMhwdVhoMj7wdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=kodou&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=41f501e0c72be6da678b5107b01579f1&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972"],"url":"https://cn-sdjn3-cmcc-bcache-05.acgvideo.com/upgcxcode/98/12/12131298/12131298-1-80.flv?e=ig8euxZM2rNcNbTMhwdVhoMj7wdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=7ca731ad39072f717561fa5ca1c843f5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","order":1,"md5":""},{"size":92740791,"ahead":"","length":384619,"vhead":"","backup_url":["https://cn-hbsjz-cmcc-bcache-03.acgvideo.com/upgcxcode/98/12/12131298/12131298-2-80.flv?e=ig8euxZM2rNcNbTVhbUVhoMjhwNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=a2787c98d29d4fe659053a5309edecac&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","https://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/98/12/12131298/12131298-2-80.flv?e=ig8euxZM2rNcNbTVhbUVhoMjhwNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=ks3u&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=7888f97c8f42d511386682da00a3218e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972"],"url":"https://cn-sdjn3-cmcc-bcache-10.acgvideo.com/upgcxcode/98/12/12131298/12131298-2-80.flv?e=ig8euxZM2rNcNbTVhbUVhoMjhwNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=a2787c98d29d4fe659053a5309edecac&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","order":2,"md5":""},{"size":83495028,"ahead":"","length":348139,"vhead":"","backup_url":["https://cn-hbsjz-cmcc-bcache-01.acgvideo.com/upgcxcode/98/12/12131298/12131298-3-80.flv?e=ig8euxZM2rNcNbUH7zUVhoMBnWuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=bb8bcf28b80db08acec2305c502dc927&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","https://upos-hz-mirrorwcsu.acgvideo.com/upgcxcode/98/12/12131298/12131298-3-80.flv?e=ig8euxZM2rNcNbUH7zUVhoMBnWuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=wcsu&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=74238b08467592c004a68e1427461625&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972"],"url":"https://cn-sdjn3-cmcc-bcache-18.acgvideo.com/upgcxcode/98/12/12131298/12131298-3-80.flv?e=ig8euxZM2rNcNbUH7zUVhoMBnWuBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=bb8bcf28b80db08acec2305c502dc927&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","order":3,"md5":""},{"size":82234828,"ahead":"","length":309888,"vhead":"","backup_url":["https://cn-hbsjz-cmcc-bcache-04.acgvideo.com/upgcxcode/98/12/12131298/12131298-4-80.flv?e=ig8euxZM2rNcNbTjhbUVhoMj7bNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=2a901a1c143472c33d16f13537440e77&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","https://upos-hz-mirrorkodou.acgvideo.com/upgcxcode/98/12/12131298/12131298-4-80.flv?e=ig8euxZM2rNcNbTjhbUVhoMj7bNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=kodou&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=d582754b092b3172adb0fb1ecaf048f1&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972"],"url":"https://cn-sdjn3-cmcc-bcache-01.acgvideo.com/upgcxcode/98/12/12131298/12131298-4-80.flv?e=ig8euxZM2rNcNbTjhbUVhoMj7bNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1570522954&gen=playurl&os=bcache&oi=1880734097&trid=f58d71eec0a34fe4aee950e101767395p&platform=pc&upsig=2a901a1c143472c33d16f13537440e77&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=298972","order":4,"md5":""}],"no_rexcode":0,"format":"flv","message":"","accept_quality":[80,64,32,16],"quality":80,"timelength":1375505,"has_paid":true,"vip_status":1,"accept_description":["高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":13}}
debug: setAreaLimitSeason ss5761 false
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by ipcjs** [comment]
那就去番剧页面看吧_(:3」∠)_
