### ISSUE TITLE
(code-404)无法播放 电影、电视剧、纪录片、国创

### ISSUE THREAD

**Issue by ipcjs** [ipcjs/bilibili-helper#509]
目前非“番剧”的视频，存在 无法获取视频播放地址 的情况，这里汇总下

| url                                                                                  | 付费视频 | 不追加&module=bangumi | 追加&module=bangumi |
| ------------------------------------------------------------------------------------ | :------: | --------------------- | ------------------- |
| [求生一加一 第五季：第7集_纪录片](https://www.bilibili.com/bangumi/play/ep285626)    |          | 10004                 | -404                |
| [肖申克的救赎：正片_电影](https://www.bilibili.com/bangumi/play/ss28274)             |          | 10004                 | 概率性-404          |
| [孤独的美食家 第三季：第四话_电视剧](https://www.bilibili.com/bangumi/play/ep269776) |          | 回退到gdrive_mp4      | -                   |
| [蜘蛛侠：英雄远征：正片_电影](https://www.bilibili.com/bangumi/play/ss28515)         |    Y     | 回退到gdrive_mp4      | -                   |
| [永远的蝙蝠侠：正片_电影](https://www.bilibili.com/bangumi/play/ep284434)            |          | 10004                 | -404                |
| [金光御九界之战血天道：第10话_国创](https://www.bilibili.com/bangumi/play/ep281789)  |          | 10004                 | -404                |
| [守望者_电影](https://www.bilibili.com/bangumi/play/ss26178)                         |          | 回退到gdrive_mp4      | -                   |

**Comment by MichaelMai2000** [comment]
[深夜食堂 第一季：第一话_电视剧](https://www.bilibili.com/bangumi/play/ep286579)
不追加&module=bangumi 10004
追加&module=bangumi 概率性-404 小概率成功加载小部分

**Comment by zym10086** [comment]
似乎使用番剧接口拉取视频地址可以播放

**Comment by piaopiaomofa** [comment]
电影都加载不了，悲o(╥﹏╥)o

**Comment by hahatrisha** [comment]
[孤独的美食家](https://www.bilibili.com/bangumi/play/ep269674)全季都无法播放，已授权大会员

**Comment by Yangff** [comment]
https://www.bilibili.com/bangumi/play/ep291905

**Comment by ipcjs** [comment]
0a692f31466c00c140b54221ad3024908961c67e
