### ISSUE TITLE
无法播放部分电影

### ISSUE THREAD

**Issue by jjkkkj** [ipcjs/bilibili-helper#511]
脚本问题：@ipcjs

## 描述

一部分电影无法播放，如哈利波特全系列，蝙蝠侠，游戏人生·零。显示无法连接服务器或服务器返回异常
- 问题网址：

哈利波特 https://www.bilibili.com/bangumi/play/ss28281/
蝙蝠侠 https://www.bilibili.com/bangumi/play/ss28306/
游戏人生 https://www.bilibili.com/bangumi/play/ss28381

## 日志

这个是哈利波特与魔法石的日志：

debug: [解除B站区域限制 v7.8.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28281/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1618588800000,"status":1,"type":2}}}
debug: setAreaLimitSeason ss28281 true
debug: /x/web-interface/nav {"uname":"66992323","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"66992323","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=62984882&cid=112148195&qn=10&type=&otype=json&ep_id=280975&fnver=0&fnval=16&session=b208f2efc2d4526281dcce9f654ffb99&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":7334489698,"length":9530684,"url":"https://video-ru.biliplus.com/file/7c3d91facfbf946119590d238e18d946/1570688172/2023449274/1L0unqEAdCVSgaPzNoLIlHP0Rem2IVFlA/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"66992323","mid":62772242,"level":5,"vip_expire":1618588800000}}
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=62984882&cid=112148195&qn=16&type=&otype=json&ep_id=280975&fnver=0&fnval=16&session=b208f2efc2d4526281dcce9f654ffb99&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":7334489698,"length":9530684,"url":"https://video-ru.biliplus.com/file/3e994af7e9e92897725c0746efe6bba7/1570688175/2023449274/1L0unqEAdCVSgaPzNoLIlHP0Rem2IVFlA/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"66992323","mid":62772242,"level":5,"vip_expire":1618588800000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
已知问题 #509
