### ISSUE TITLE
无法播放电影

### ISSUE THREAD

**Issue by AkitsukiShintai** [ipcjs/bilibili-helper#514]
脚本问题：@ipcjs

## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"秋月心太\",\"mid\":2210582,\"level\":5,\"vip_expire\":1630512000000}}","code":10004}
- 问题网址：https://www.bilibili.com/bangumi/play/ss28274/

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：chrome  77.0.3865.120 x64
2. 国家/地区：美国

**Comment by jerryuhoo** [comment]
同样问题，番剧可以看，电影板块看不了

**Comment by ipcjs** [comment]
已知问题 #509
