### ISSUE TITLE
本来还可以看，但是调不了清晰度（我是大会员）结果授权之后就干脆看不来了要命啊！

### ISSUE THREAD

**Issue by Sakuradreancat** [ipcjs/bilibili-helper#516]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by Sakuradreancat** [comment]
https://www.bilibili.com/bangumi/play/ss28198/?from=search&seid=17039218327287146956

**Comment by Sakuradreancat** [comment]
而且最开始的那个页面也不出现了，别的视频也看不了了，我好绝望

**Comment by ipcjs** [comment]
日志？

**Comment by Sakuradreancat** [comment]
抱歉在哪里找日志？ 现在还是看不了 拉取视频失败

**Comment by Sakuradreancat** [comment]
> 日志？

抱歉在哪里找日志？ 现在还是看不了 拉取视频失败
