### ISSUE TITLE
使用脚本后，视频有一定概率丢失片段。

### ISSUE THREAD

**Issue by ipcjs** [ipcjs/bilibili-helper#52]
> [关于B站看番时中途会有部分视频被跳过的问题](https://greasyfork.org/zh-CN/forum/discussion/33432/x)
> 不知道大家遇到没遇到过，在使用这个插件的时候，看的视频有时候中间会有一部分直接被跳过，如24分钟的番剧可能中间有个几分钟不见了，到最后只播放了18分钟，像被剪掉了一样。这个问题时好时坏，不使用该插件使用其他方法的时候没有这个问题，不知道是B站的措施还是脚本本来的问题

原因未知。

**Comment by CNife** [comment]
是这个脚本的问题吗，我一直以为是 B 站播放器的 BUG

**Comment by ipcjs** [comment]
@CNife 不用脚本就没问题，那就应该就是脚本的问题

**Comment by aLLeENSmith** [comment]
@ipcjs 
应该是网络环境问题。
我这租房网络环境很差；无脚本，正常观看视频有时候也跳片段。
长点的视频，有时候甚至只加载了一个6分钟的片段，其他都没了。
刷新就好了，估计是网络波动导致的。

**Comment by mykaiping** [comment]
@aLLeENSmith
然而我用unblock youku就没出现过跳过一段（进度条直接变成只有18分钟什么的）
用这个插件就经常会发生 应该是插件bug吧

**Comment by aLLeENSmith** [comment]
@mykaiping 
具体情况我也不是很清楚，这个脚本和你说的那个脚本我都没有实际用过；只是基于推测得出的结论。
这种解锁区域限制的，一般来说解决方法就是让**视频流量走代理**。
那么代理服务器的网络环境，服务器与代理之间的连接，电脑与代理之间的连接，视频播放网站的视频加载策略都有可能导致一些不正常的情况发生。
我不能保证脚本一定不会导致问题，但一般出问题的原因往往是多方面的，比如你连接的代理服务器爆满等等之类的。

**Comment by mykaiping** [comment]
这是我的网路测试 没什么毛病 应该是代理服务器坑了  
![default](https://user-images.githubusercontent.com/37016477/36948747-8adee8ac-201a-11e8-8f09-744119a09305.PNG)

额 刚刚又出现这问题了 无语了 凌晨两点多也会代理服务器爆满么66666
![default](https://user-images.githubusercontent.com/37016477/36948809-420f0e58-201b-11e8-8f29-bca8e7ffacf9.PNG)

**Comment by cloudyoa** [comment]
我的一直黑屏是为什么，声音和弹幕是显示正常的，就是画面不显示
![20180410002138](https://user-images.githubusercontent.com/38222420/38510242-fb85a78c-3c56-11e8-8ef3-ef0634a672f9.png)
