### ISSUE TITLE
B站新出的电影看不了，旧的可以看

### ISSUE THREAD

**Issue by langlang19891025** [ipcjs/bilibili-helper#521]
debug: [解除B站区域限制 v7.8.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep289130
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"小浪子1989","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1572537600000,"status":1,"type":1}}}
debug: setAreaLimitSeason ep289130 true
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=73037451&cid=124919753&qn=0&type=&otype=json&ep_id=289130&fnver=0&fnval=16&session=3a5a280a27cafc5c0802b7047958a4bc&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":2497657812,"length":5543697,"url":"https://video-ru.biliplus.com/file/4fb5ec48044049ad33025e7ed3e7dcdc/1572106853/2892623181/1NvvHMSYHd9dFiu9lk1Hp3dpCLzEsVJZq/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"小浪子1989","mid":456248,"level":5,"vip_expire":1572537600000}}
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=73037451&cid=124919753&qn=16&type=&otype=json&ep_id=289130&fnver=0&fnval=16&session=3a5a280a27cafc5c0802b7047958a4bc&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":2497657812,"length":5543697,"url":"https://video-ru.biliplus.com/file/a69d828598b4e865b98c3bf6aac57fd3/1572106877/2892623181/1NvvHMSYHd9dFiu9lk1Hp3dpCLzEsVJZq/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"小浪子1989","mid":456248,"level":5,"vip_expire":1572537600000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by DanielBasara** [comment]
相同问题，7.8.9版本。测试页的形之声可以正常观看。但是新购入或者一部分老电影显示无法连接服务器或服务器返回异常。测试电影【盗梦空间】，【夺宝奇兵1，2，3，4】【名侦探柯南：绀青之拳】新老版本播放器均测试过，使用最新版谷歌chrome。

**Comment by ironyx217** [comment]
我也是这样

**Comment by Richard1Chen** [comment]
debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep292239
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: /x/web-interface/nav {"uname":"摸鱼城管","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1599494400000,"status":1,"type":2}}}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=74046568&cid=129218264&qn=64&type=&otype=json&ep_id=292239&fnver=0&fnval=16&session=3433305207a7c28796166223c27fb590&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":5947851508,"length":8174034,"url":"https://video-ru.biliplus.com/file/6fb05dda2a077dc096f9372fb578bd6f/1574891495/1844843638/1bK_Aue09x7Rs0sNa9T3KZ1TKHNFaiogm/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"摸鱼城管","mid":2554937,"level":5,"vip_expire":1599494400000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=74046568&cid=129218264&qn=16&type=&otype=json&ep_id=292239&fnver=0&fnval=16&session=3433305207a7c28796166223c27fb590&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":5947851508,"length":8174034,"url":"https://video-ru.biliplus.com/file/8dc0daca07486fddc221ffaa9e96659d/1574891518/1844843638/1bK_Aue09x7Rs0sNa9T3KZ1TKHNFaiogm/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"摸鱼城管","mid":2554937,"level":5,"vip_expire":1599494400000}}

**Comment by tiny-cup** [comment]
应该是类似的问题？罗小黑电影不能看，大概最近两个月出的

debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep287966?spm_id_from=333.334.b_63686965665f7265636f6d6d656e64.1
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: /x/web-interface/nav {"uname":"Tinycup","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1618502400000,"status":1,"type":2},"watch_progress":{"last_ep_id":287966,"last_ep_index":"正片","last_time":4}}}
debug: setAreaLimitSeason ep287966 true
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=71422691&cid=123756195&qn=0&type=&otype=json&ep_id=287966&fnver=0&fnval=16&session=7d29744db6d9fdd7dc40a26e505cb109&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":2877220857,"length":6099623,"url":"https://video-ru.biliplus.com/file/ec94333382b7f2ec5338190a1486b475/1574926280/1655264989/1dky6CGYvAFC5p1XW1MIiLBm4clKpDUMQ/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"Tinycup","mid":663409,"level":5,"vip_expire":1618502400000}}
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=71422691&cid=123756195&qn=16&type=&otype=json&ep_id=287966&fnver=0&fnval=16&session=7d29744db6d9fdd7dc40a26e505cb109&balh_ajax=1
warn: playurl的result缺少必要的字段: {"code":0,"flvjsType":"flv","format":"gdrive_mp4","accept_quality":[10],"quality":10,"durl":[{"order":1,"size":2877220857,"length":6099623,"url":"https://video-ru.biliplus.com/file/e49e200e9eb783d5a67eb1813c090016/1574926296/1655264989/1dky6CGYvAFC5p1XW1MIiLBm4clKpDUMQ/videoplayback.mp4"}],"loginStatus":{"isLogin":true,"uname":"Tinycup","mid":663409,"level":5,"vip_expire":1618502400000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

**Comment by ipcjs** [comment]
#525
