### ISSUE TITLE
无法观看大会员番剧（已经是大会员）

### ISSUE THREAD

**Issue by ghost** [ipcjs/bilibili-helper#522]
脚本问题：@ipcjs

## 描述

无法观看需要大会员的番剧（所有的大会员番剧），而且无法调整到1080p+的画质（显示切换失败）。（已经是大会员，而且尝试过账号授权，没有用。）
- 问题网址：
https://www.bilibili.com/bangumi/play/ep285963
https://www.bilibili.com/bangumi/play/ep259675
https://www.bilibili.com/bangumi/play/ep84450

## 日志

<details>
<summary>Verbose 日志</summary>

```
debug: [解除B站区域限制 v7.8.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep285963
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.top upos_server: cos flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1583251200000,"status":1,"type":2}}}
debug: /x/web-interface/nav {"uname":"小さなのひつじだ","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: /x/web-interface/nav {"uname":"小さなのひつじだ","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=71616905&cid=124105013&qn=112&type=&otype=json&ep_id=285963&fnver=0&fnval=16&session=3c7b9c0188d7becc446bdf17e7464e58&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36
```
</details>

## 其他

1. 浏览器版本：Chrome 77.0.3865.120
2. 国家/地区：墨西哥

**Comment by ghost** [comment]
无法观看需要大会员的番剧，也无法切换到1080p+。（已经是大会员，尝试过账号授权，但没有用，还是显示的
{"code":-403,"error":"returned cid not requested","message":"没有观看此付费视频的权限。）

**Comment by ghost** [comment]
代理服务器为BiliPlus，upos服务器为腾讯。（这些服务器怎么改都没有用。）
脚本工作模式为重定向：完全代理所有番剧。
其他里面没有选择任何选项。

**Comment by ghost** [comment]
观看不需要大会员的番剧时没有问题，但无法切换到1080p+。（尝试过账号授权）

**Comment by ghost** [comment]
使用了土豆代理服务器后也无法播放：
debug: [解除B站区域限制 v7.8.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep84450
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad: Y enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: /x/web-interface/nav {"uname":"小さなのひつじだ","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1583251200000,"status":1,"type":2},"watch_progress":{"last_ep_id":84449,"last_ep_index":"1","last_time":6}}}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=50429644&cid=89195538&qn=112&type=&otype=json&ep_id=84450&fnver=0&fnval=16&session=76982566309974fc7990e9f434c6338f&module=bangumi&balh_ajax=1
debug: /x/web-interface/nav {"uname":"小さなのひつじだ","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":true}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=50429644&cid=89195319&qn=112&type=&otype=json&ep_id=84449&fnver=0&fnval=16&session=b724db1bb12d03fd1ebc7561c2b5f23a&module=bangumi&balh_ajax=1
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=50429644&cid=89195319&qn=112&type=&otype=json&ep_id=84449&fnver=0&fnval=16&session=b724db1bb12d03fd1ebc7561c2b5f23a&module=bangumi&balh_ajax=1
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=50429644&cid=89195538&qn=112&type=&otype=json&ep_id=84450&fnver=0&fnval=16&session=1df3d4b87c27aa92af54db04c33946e0&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

**Comment by skyrealmz** [comment]
我看大会员动画倒没问题，就是看不了需要大会员的日剧和电影

**Comment by MisaMatsuno** [comment]
看不了日剧+1

**Comment by yiwenzhang92** [comment]
动画没问题 1080+也没问题
但是确实需要大会员的日剧都看不了
我本身是大会员

**Comment by happygaoxiao** [comment]
我也是这样，开了大会员也授权了，但是看不了需要会员的新番

**Comment by valvesyou** [comment]
+1

**Comment by AlfredChairman** [comment]
我现在无法观看港澳台地区的1080P+（有大会员）
