### ISSUE TITLE
新增upos

### ISSUE THREAD

**Issue by zzc10086** [ipcjs/bilibili-helper#525]
貌似买了华为的cdn
地址https://upos-hz-mirrorhw.acgvideo.com

**Comment by zzc10086** [comment]
我这边用华为的加载一个片段要一秒多,网宿只要几百毫秒,华为CDN还是不行啊(在我的网络环境下)(￣▽￣)"

**Comment by ipcjs** [comment]
740429ed883e152d0039da907a86727ced0dc189
脚本上其实只是个配置，功能是服务端实现的
@esterTion

**Comment by esterTion** [comment]
感觉没啥用，目前就cos体验比较好，其他几个已有的也都不行

**Comment by zzc10086** [comment]
> 感觉没啥用，目前就cos体验比较好，其他几个已有的也都不行

大概是网络环境不一样吧

**Comment by esterTion** [comment]
摸鱼人来加功能了
我记得以前有个isuka？还是叫什么来的
nslookup没这个域名了
（加功能原因是cos突然速度变慢了，然而hw却满速(x）

还有一个是upos真的乱，早期cdn是一个sign算法，后来新加的都是早期的u版本cdn
比如ks3和cos和kodo可以替换，但是hw就要换成cosu kodou

**Comment by esterTion** [comment]
服务器上推了
现在后台支持的替换：
```HTML
<option value="">不替换</option>
<option value="ks3u">ks3（金山）</option>
<option value="kodou">kodo（七牛）</option>
<option value="cosu">cos（腾讯）</option>
<option value="bosu">bos（百度）</option>
<option value="wcsu">wcs（网宿）</option>
<option value="xycdn">xycdn（迅雷）</option>
<option value="hw">hw（华为）</option>
```

---
设置旧式（没有u）的话会在下次访问时候转换，这个倒是影响不大
另外需不需要一个获取状态的api（设置和登录状态等等）

**Comment by zzc10086** [comment]
迅雷速度起来的真快,迅雷NB(～￣▽￣)～

**Comment by zzc10086** [comment]
> 服务器上推了
> 现在后台支持的替换：
> 
> ```
> <option value="">不替换</option>
> <option value="ks3u">ks3（金山）</option>
> <option value="kodou">kodo（七牛）</option>
> <option value="cosu">cos（腾讯）</option>
> <option value="bosu">bos（百度）</option>
> <option value="wcsu">wcs（网宿）</option>
> <option value="xycdn">xycdn（迅雷）</option>
> <option value="hw">hw（华为）</option>
> ```
> 
> 设置旧式（没有u）的话会在下次访问时候转换，这个倒是影响不大
> 另外需不需要一个获取状态的api（设置和登录状态等等）

迅雷速度起来的真快，迅雷NB（〜￣▽￣）〜

**Comment by esterTion** [comment]
新加了一个也扔在这里算了
@ipcjs
对于 #509 的情况，换用 module=pgc 
（大概所有版权内容可以统一用一个了？）

---
草，想起来看了一眼，我投稿的魔法老师2也变成pgc了

**Comment by ipcjs** [comment]
upos加了
bangumi改pgc。。。乱七八糟判断有点多，看的头大，等我看下怎么改😵

**Comment by esterTion** [comment]
b站又把事情弄的更复杂了……
新添加了`upos-sz-mirrorhw.bilivideo.com`，这次所有的acgvideo下面的u系列都不需要u了
现在可以任意替换域名的逻辑变成了：
- `upos-sz-mirrorhw.bilivideo.com`
- `upos-sz-mirrorcos.bilivideo.com`
- `upos-hz-mirrorhw.acgvideo.com`
- `upos-hz-mirrorcosu.acgvideo.com`

哇，你们后端搞什么啊，整这么复杂

**Comment by zzc10086** [comment]
迅雷好像变成p2p专属了,替换就证书错误.
百度403.
华为的acgvideo也报错了
对了,能加上番剧的upos的替换吗,普通视频确实替换了.番剧还是默认的aka的@esterTion
