### ISSUE TITLE
在AdGuard中也可以使用脚本

### ISSUE THREAD

**Issue by lizhongruan** [ipcjs/bilibili-helper#526]
我在下载脚本以后，突然触发了AdGuard桌面版, 提示是否安装脚本进去。
安装以后可以正常使用。在Chrome里并没有装。
设置页面只有进入b站番剧以后。向下滑动滚动条才会出现。不能在adguard里进行设置。
![Setting](https://user-images.githubusercontent.com/53921738/68246985-336aac00-001a-11ea-8cd5-babd2dd7f190.png)
不过这都不是问题。使用状况良好。
所以来反馈一下。如果有浏览器装不上又有AdGuard的桌面版的小伙伴可以直接装到这里。不用再去安装其他扩展程序啦~
![adguard](https://user-images.githubusercontent.com/53921738/68246526-37e29500-0019-11ea-9559-1ffe56145ae2.png)
![active](https://user-images.githubusercontent.com/53921738/68247020-41b8c800-001a-11ea-8a26-d45dc850b46f.png)

**Comment by ipcjs** [comment]
这个东西这么厉害的吗，还能装脚本！

**Comment by lizhongruan** [comment]
是鸭，我当时都惊呆了。adguard自己弹出来的。

**Comment by mykey8585** [comment]
怎麼安裝到ADGUARD啊

**Comment by Jiayi-Yang** [comment]
非常感谢！！！解决了油猴里Windows不跳出脚本的问题

**Comment by jackwude** [comment]
您好，我想问一下，像上图那种形式，把脚本装进去adguard后，比如我想要进入脚本本身的设置页面如何进入呢？ 有一些脚本有一些自定义个性化的选项是可以设置的，我觉得adguard还是挺好用的，但是不知道咋进入这种设置。@ @lizhongruan
