### ISSUE TITLE
用着还行 希望“被永封的大会员？”这个选项 在看其他非番剧的视频的时候也能启用然后愉快的享受60fps的愉悦

### ISSUE THREAD

**Issue by miaomucheng1** [ipcjs/bilibili-helper#528]
就是希望其他视频也能进行大会员的60FPS选项

**Comment by TTTPOB** [comment]
现在已经有了“在av页面启用”的选项呀

**Comment by miaomucheng1** [comment]
> 现在已经有了“在av页面启用”的选项呀

但我用了发现是切换失败，不知道为啥，切不到60FPS，我要哭了

**Comment by TTTPOB** [comment]
我大概知道为啥，这个脚本应只在第一次加载视频的时候拉取视频地址。然后也提了一个issue https://github.com/ipcjs/bilibili-helper/issues/536
