### ISSUE TITLE
大会员账号切换大会员1080+清晰度失败

### ISSUE THREAD

**Issue by Sincerelyrin** [ipcjs/bilibili-helper#529]
## 描述
大会员账号切换大会员1080+清晰度失败

- 问题网址：https://www.bilibili.com/bangumi/play/ss2701#256595

## 日志

debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss2701#256595
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y enable_in_av: Y readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"碳酸度假村","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1625760000000,"status":1,"type":2},"watch_progress":{"last_ep_id":256595,"last_ep_index":"1","last_time":1}}}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=35891970&cid=62993549&qn=112&type=&otype=json&ep_id=256595&fnver=0&fnval=16&session=cf094a59207563a8d57ff2a46f8c61bb&module=bangumi&balh_ajax=1
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=35891970&cid=62993549&qn=112&type=&otype=json&ep_id=256595&fnver=0&fnval=16&session=cf094a59207563a8d57ff2a46f8c61bb&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

1. 浏览器版本：firefox 70.0.1
2. 国家/地区：中国

**Comment by holoyoitsu** [comment]
国外chrome试好像1080p+没问题
