### ISSUE TITLE
电视剧：日剧  无法观看    

### ISSUE THREAD

**Issue by sherab-dorje** [ipcjs/bilibili-helper#532]
debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep262038
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 5
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"石总","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=42014725&cid=73762222&qn=80&type=&otype=json&ep_id=262038&fourk=1&fnver=0&fnval=16&session=aedbf5586ce850b026bf5b68ad0b8b02
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"石总","mid":7669805,"level":5,"vip_expire":1576166400000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"石总\",\"mid\":7669805,\"level\":5,\"vip_expire\":1576166400000}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=42014725&cid=73762222&qn=80&type=&otype=json&ep_id=262038&fourk=1&fnver=0&fnval=16&session=aedbf5586ce850b026bf5b68ad0b8b02&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"石总","mid":7669805,"level":5,"vip_expire":1576166400000}}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function(e,i){return new l.fn.init(e,i,t)}
debug: injectAjax at: function(e,i){return new l.fn.init(e,i,t)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 5
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=42014725&cid=73762222&qn=80&type=&otype=json&ep_id=262038&fourk=1&fnver=0&fnval=16&session=12e0ba9ff4a4147a70d9f02a9d0dc410&balh_ajax=1
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"石总","mid":7669805,"level":5,"vip_expire":1576166400000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"石总\",\"mid\":7669805,\"level\":5,\"vip_expire\":1576166400000}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=42014725&cid=73762222&qn=80&type=&otype=json&ep_id=262038&fourk=1&fnver=0&fnval=16&session=12e0ba9ff4a4147a70d9f02a9d0dc410&balh_ajax=1&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"石总","mid":7669805,"level":5,"vip_expire":1576166400000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by ipcjs** [comment]
#525 现在应该好了，试试
