### ISSUE TITLE
这个脚本无法在b站上看电影

### ISSUE THREAD

**Issue by lt1912** [ipcjs/bilibili-helper#533]
debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep257474/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"lt1912","isLogin":true,"level":0,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"pay":0,"pay_pack_paid":0,"sponsor":0,"vipInfo":{"due_date":1602518400000,"status":1,"type":2},"watch_progress":{"last_ep_id":257474,"last_ep_index":"正片","last_time":2357}}}
debug: setAreaLimitSeason ep257474 true
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=37085622&cid=65169688&qn=80&type=&otype=json&ep_id=257474&fnver=0&fnval=16&session=edecd17d92f736a47c458dcfeb93a885&balh_ajax=1
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"lt1912","mid":6152542,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"lt1912\",\"mid\":6152542,\"level\":0,\"vip_expire\":0}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=37085622&cid=65169688&qn=80&type=&otype=json&ep_id=257474&fnver=0&fnval=16&session=edecd17d92f736a47c458dcfeb93a885&balh_ajax=1&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"lt1912","mid":6152542,"level":0,"vip_expire":0}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

## 其他

1. 浏览器版本：chrome
2. 国家/地区：美国

**Comment by ipcjs** [comment]
esterTion 改了服务器，现在应该好了，试试
