### ISSUE TITLE
会员电视剧视频拉取失败

### ISSUE THREAD

**Issue by VesslanEme** [ipcjs/bilibili-helper#537]
## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"XXXXX\",\"mid\":2693643,\"level\":6,\"vip_expire\":1588435200000}}","code":10004}

https://www.bilibili.com/bangumi/play/ep204579

**Comment by ipcjs** [comment]
#525
