### ISSUE TITLE
所有番剧无法观看 CODE -502  （重复问题就别再发了）

### ISSUE THREAD

**Issue by tianpai** [ipcjs/bilibili-helper#539]
脚本问题：@ipcjs

## 描述

今天早些时间，b站还是可以用旧版的播放器，所有地区锁的番都可以看。下午打个盹，现在b站似乎去掉了返回旧版的选择，都是新版了，所有番剧都不可以了。试了试jojo，和一些港澳台的。都不可以看了。望修复，谢谢。

- 问题网址：所有番剧

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```

 debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28022/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"与草木俱朽","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=104266776&qn=64&type=&otype=json&avid=59861522&ep_id=276934&fourk=1&fnver=0&fnval=16&session=1f96587d55924728a90b9c17020cbf4c&module=bangumi
error: {"code":-502,"message":"无法连接到playurl","api":"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=104266776&otype=json&ts=1576030526&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&fourk=1&access_key=ab967816ba2a724f5951682ef7dd5ab1&qn=64&sign=be775a5f2e89d7f21c3e6db0edeb85a5","loginStatus":{"isLogin":true,"uname":"与草木俱朽","mid":8898770,"level":5,"vip_expire":1595606400000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=104266776&otype=json&ts=1576030526&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&fourk=1&access_key=ab967816ba2a724f5951682ef7dd5ab1&qn=64&sign=be775a5f2e89d7f21c3e6db0edeb85a5\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"与草木俱朽\",\"mid\":8898770,\"level\":5,\"vip_expire\":1595606400000}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=59861522&cid=104266776&bvid=undefined&qn=64&type=&otype=json&ep_id=276934&fourk=1&fnver=0&fnval=16&session=ad48ba61cd12d33c6e04663d36cc4f28&module=bangumi&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=104266776&otype=json&ts=1576030538&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&fourk=1&access_key=ab967816ba2a724f5951682ef7dd5ab1&qn=64&sign=8d6fb438394c56d3093b524737c1df82","loginStatus":{"isLogin":true,"uname":"与草木俱朽","mid":8898770,"level":5,"vip_expire":1595606400000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=104266776&otype=json&ts=1576030538&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&fourk=1&access_key=ab967816ba2a724f5951682ef7dd5ab1&qn=64&sign=8d6fb438394c56d3093b524737c1df82\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"与草木俱朽\",\"mid\":8898770,\"level\":5,\"vip_expire\":1595606400000}}","code":-502}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0

</details>

## 其他

1. 浏览器版本：火狐 71.0 (64-bit) mac
2. 国家/地区：加拿大 安大略

**Comment by ipcjs** [comment]
别在发了你还不close(;¬_¬)
