### ISSUE TITLE
所有视频均无法使用脚本，切换服务器后仍无法使用

### ISSUE THREAD

**Issue by rsruby25** [ipcjs/bilibili-helper#540]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28741/?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.7
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=125019445&qn=112&type=&otype=json&avid=73094209&ep_id=286943&fourk=1&fnver=0&fnval=16&session=bfc634a376eb6131047fa2dbd207576e&module=bangumi
debug: /x/web-interface/nav {"uname":"风星先生","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-502,"message":"无法连接到playurl","api":"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=125019445&otype=json&ts=1576032763&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&fourk=1&access_key=317e689ae4bb4784c52aed2435b8b881&qn=112&sign=0e35dd9546830d2d7c9411c330cadc3d","loginStatus":{"isLogin":true,"uname":"风星先生","mid":1466064,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=125019445&otype=json&ts=1576032763&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&fourk=1&access_key=317e689ae4bb4784c52aed2435b8b881&qn=112&sign=0e35dd9546830d2d7c9411c330cadc3d\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"风星先生\",\"mid\":1466064,\"level\":0,\"vip_expire\":0}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=73094209&cid=125019445&bvid=undefined&qn=112&type=&otype=json&ep_id=286943&fourk=1&fnver=0&fnval=16&session=f610825c37589c8ddeed5de4780a5711&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by lt1912** [comment]
我也一样，才买了没多久的大会员结果只能白白作废

**Comment by syr-123** [comment]
啊我也是，7点多用的时候还没问题的，过来会到中午11点就不行了

**Comment by tianpai** [comment]
看一下 -502的问题  我猜是b站换了新版吧

**Comment by MrWhoami** [comment]
Same here. 看起来是 B 站更新了。

**Comment by egoist1234** [comment]
+1，哔哩哔哩网页版更新了新版了后就用不了脚本了，请求修复

**Comment by heye521** [comment]
## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到
