### ISSUE TITLE
拉取视频失败，服务器错误，code：-502

### ISSUE THREAD

**Issue by syr-123** [ipcjs/bilibili-helper#541]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他
坐标日本，具体现象表现为能够打开新番网页，能够看到评论，但是视频显示“非常抱歉......”的画面，无法正常拉取视频。
北京时间早上7点多的时候还能正常使用，10点左右就用不了了，多次重装脚本无效、更新Chrome后也无效，打开的番剧都显示“拉取视频失败”，具体显示如下：

## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://bangumi.bilibili.com/player/api/v2/playurl?module=bangumi&appkey=84956560bc028eb7&type=flv&cid=134003956&otype=json&ts=1576039868&build=12450&platform=pc&season_type=1&fnver=0&fnval=16&fourk=1&access_key=054c4003265b0a21b8d074b1cf54ddb1&qn=112&sign=cc30df5618c7e834891dc9ded9abfc68\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"浅間夏和\",\"mid\":4728561,\"level\":5,\"vip_expire\":1705075200000}}","code":-502}

1. 浏览器版本：最新版的Google Chrome
2. 国家/地区：日本

**Comment by yujincheng08** [comment]
Same here.

**Comment by ysyscool** [comment]
+1

**Comment by ttawi** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by carlton981010** [comment]
澳洲同样情况

**Comment by ZHZ068** [comment]
美国这里也是。
浏览器：Chrome Version 78.0.3904.108 (64-bit)

**Comment by 5418ly** [comment]
坐标澳大利亚，同意的状况，而且也不能授权登录了。浏览器：Firefox 7.10（64bit）系统： windwos 10 家庭

**Comment by JinghangWang** [comment]
+1， 授权登录失败，无法拉取视频
地区： 美国
浏览器： Chrome 78.0.3904.108 (Official Build) (64-bit)
macOS 10.14.6 (18G103)

**Comment by carlton981010** [comment]
目前状况：澳洲能看，但是很卡，开头5-8分钟加载没有问题，10分钟之后几乎没有加载，反复刷新无果。

**Comment by yujincheng08** [comment]
It seems to work now.

**Comment by syr-123** [comment]
现在貌似恢复正常了
