### ISSUE TITLE
会员动画番剧观看正常，但是在观看会员电视剧时报错，反复授权仍然不行。错误日志如下

### ISSUE THREAD

**Issue by Hoshino324** [ipcjs/bilibili-helper#542]
debug: [解除B站区域限制 v7.8.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep269798?from=search&seid=12021988342973714213
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 5
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=87914247&qn=116&type=&otype=json&avid=49695188&ep_id=269798&fourk=1&fnver=0&fnval=16&session=2f2a24a34781eec9cac61347b2bb58f6
debug: /x/web-interface/nav {"uname":"星野o_O","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"星野o_O","mid":922777,"level":5,"vip_expire":1591718400000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"星野o_O\",\"mid\":922777,\"level\":5,\"vip_expire\":1591718400000}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=87914247&qn=116&type=&otype=json&avid=49695188&ep_id=269798&fourk=1&fnver=0&fnval=16&session=2f2a24a34781eec9cac61347b2bb58f6&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"星野o_O","mid":922777,"level":5,"vip_expire":1591718400000}}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 5
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=49695188&cid=87914247&bvid=undefined&qn=116&type=&otype=json&ep_id=269798&fourk=1&fnver=0&fnval=16&session=3c3c4bcd96e28ae9b8652f104984074e&balh_ajax=1
error: {"code":10004,"result":"error","message":"Video is hidden.","loginStatus":{"isLogin":true,"uname":"星野o_O","mid":922777,"level":5,"vip_expire":1591718400000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":10004,\"result\":\"error\",\"message\":\"Video is hidden.\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"星野o_O\",\"mid\":922777,\"level\":5,\"vip_expire\":1591718400000}}","code":10004}
info: player msg: 尝试使用番剧视频接口拉取视频地址...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=49695188&cid=87914247&bvid=undefined&qn=116&type=&otype=json&ep_id=269798&fourk=1&fnver=0&fnval=16&session=3c3c4bcd96e28ae9b8652f104984074e&balh_ajax=1&module=bangumi
error: {"code":-404,"message":"结果为空或者已被删除","loginStatus":{"isLogin":true,"uname":"星野o_O","mid":922777,"level":5,"vip_expire":1591718400000}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Comment by ipcjs** [comment]
更新下，刚改的

**Comment by Hoshino324** [comment]
万分感谢
