### ISSUE TITLE
我不小心错过了授权界面怎么办？

### ISSUE THREAD

**Issue by qzcyyw13** [ipcjs/bilibili-helper#546]
之前因为我的操作失误而不小心错过了授权界面
之后不管我怎么重新安装脚本都没有再出现授权界面了
现在根本看不了番剧，请问有什么解决办法吗？

**Comment by esterTion** [comment]
在播放页向下滚动页面，点击右下角按钮
或
进入任意番剧介绍页，点击追番右侧按钮打开设置界面
