### ISSUE TITLE
看不到所有JOJO的奇妙冒險,除了第一集之外

### ISSUE THREAD

**Issue by AnnaAlexander** [ipcjs/bilibili-helper#556]
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=59014333&qn=64&type=&otype=json&avid=33696108&ep_id=250612&fourk=1&fnver=0&fnval=16&session=7e0472758432b7ff91a2561b7f9fefd1&module=pgc
debug: /x/web-interface/nav {"uname":"煉炭and義炭","isLogin":true,"level":4,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=59014333&otype=json&ts=1579533508&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&qn=64&sign=53676551a422067016e2fc6b98f140e7","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=59014333&otype=json&ts=1579533508&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&qn=64&sign=53676551a422067016e2fc6b98f140e7\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=33696108&cid=59014333&bvid=&qn=64&type=&otype=json&ep_id=250612&fourk=1&fnver=0&fnval=16&session=2f7d04a3bf210323f85012a9d8b3ac8e&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=59014333&otype=json&ts=1579533510&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&qn=64&sign=0e46f87a5e9bd714f797b0fbd2d6178e","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=59014333&otype=json&ts=1579533510&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&qn=64&sign=0e46f87a5e9bd714f797b0fbd2d6178e\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

1. 浏览器版本：Google Chrome 
版本 79.0.3945.130 (正式版本) (64 位元)
2. 国家/地区：

**Comment by Ruochen-Ji** [comment]
我也有这个问题，请问有人会修这个issue吗
