### ISSUE TITLE
每天晚上6:00~11:30左右固定无法观看视频

### ISSUE THREAD

**Issue by fhy14** [ipcjs/bilibili-helper#56]
## 描述
白天的时候默认代理服务器可以观看，但每天晚上6:00~11:30左右这段时间内固定无法观看视频（会变成16秒“非常抱歉”那个短视频），测试延迟基本都在60000毫秒~120000毫秒，有时候还会更高
备选代理服务器一直都是没法看的，一直都是16秒“非常抱歉”那个短视频

## 日志

log: [解除B站区域限制 v6.4.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183800
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: false
log: /x/web-interface/nav {"code":-101,"data":{"isLogin":false},"message":"账号未登录","ttl":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: setAreaLimitSeason ep183800 true
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=30219063|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=2349e0f6ec74d4a8fdd041d2748f58bd
log: Notification permission: denied
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## 其他

1. 浏览器版本：Chrome 63.0.3239.132
2. 国家/地区：天朝大陆

**Comment by fhy14** [comment]
6:00-11:30左右这段时间内固定无法观看视频（会变成16秒“非常抱歉”那个短视频），测试延迟基本都在60000毫秒-120000毫秒
看了看有个被关闭的问题里，用备用服务器对账号有什么要求么？

**Comment by ipcjs** [comment]
你连B站账号都没登，当然不行

**Comment by fhy14** [comment]
必须要本身的大会员账号才行么……注册的小号一样没用
