### ISSUE TITLE
拉取视频地址失败，无法正常播放b站新番

### ISSUE THREAD

**Issue by syr-123** [ipcjs/bilibili-helper#563]
坐标日本，b站的新番无法播放。刷新好几次没有任何变化。
前两天就有出现过这个问题，但是用了旧播放页脚本之后又能正常播放了，
这次是怎么样都没法正常播放orz 

日志如下：

debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss29325?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.53
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ss29325 true
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=152034129&qn=64&type=&otype=json&avid=89005155&ep_id=307252&fourk=1&fnver=0&fnval=16&session=e9e344f3636a6e64c99de344a083c24f&module=pgc
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=152034129&otype=json&ts=1583232304&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=82930bafe73cba37476266101fbbcab8","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=152034129&otype=json&ts=1583232304&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=82930bafe73cba37476266101fbbcab8\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: __playinfo__ set
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep307253 true
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=157898360&qn=64&type=&otype=json&avid=92478490&ep_id=307253&fourk=1&fnver=0&fnval=16&session=bc2691738f5e45b3cffeb6d19b10649b&module=pgc
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=89005155&cid=152034129&bvid=&qn=64&type=&otype=json&ep_id=307252&fourk=1&fnver=0&fnval=16&session=9dfd4202f6ef0ac7c80a5a7a62ec5f48&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=152034129&otype=json&ts=1583232307&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=029770bfa5ac69f86e89689735499db1","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=152034129&otype=json&ts=1583232307&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=029770bfa5ac69f86e89689735499db1\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=157898360&otype=json&ts=1583232306&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=e3381c028e96c160cfb0c380b5ee3e16","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=157898360&otype=json&ts=1583232306&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=e3381c028e96c160cfb0c380b5ee3e16\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=92478490&cid=157898360&bvid=&qn=64&type=&otype=json&ep_id=307253&fourk=1&fnver=0&fnval=16&session=4cfa78ad73689edad3999b4609c392ec&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=157898360&otype=json&ts=1583232310&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=0bb079b59702f4c1661892db53aa44a5","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=157898360&otype=json&ts=1583232310&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=64&sign=0bb079b59702f4c1661892db53aa44a5\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

## 其他

1. 浏览器版本：最新的谷歌浏览器
2. 国家/地区：日本

**Comment by Giwen-git** [comment]
同样遇到这个问题，坐标埃及，看着看着就突然弹出需要重新验证大会员的消息，但是点进去无法重新验证（显示存储失败：网络错误。重试次数超过3次，登陆失败）
看不需要大会员的番也无法正常拉取地址，换了服务器也仍然失败。


日志：
debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep307448
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=142323928&qn=32&type=&otype=json&avid=83157260&ep_id=307448&fourk=1&fnver=0&fnval=16&session=1b07a7da0f9947bdc4bad41ee4d5f8cd&module=pgc
debug: /x/web-interface/nav {"uname":"Gi文","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=142323928&otype=json&ts=1583232970&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6d025bcc32e4ddc713dfe6c71dee4d11&qn=32&sign=89a21efdc26290030257ac0f6a8f405e","loginStatus":{"isLogin":true,"uname":"Gi文","mid":2310549,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=142323928&otype=json&ts=1583232970&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6d025bcc32e4ddc713dfe6c71dee4d11&qn=32&sign=89a21efdc26290030257ac0f6a8f405e\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Gi文\",\"mid\":2310549,\"level\":0,\"vip_expire\":0}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=83157260&cid=142323928&bvid=&qn=32&type=&otype=json&ep_id=307448&fourk=1&fnver=0&fnval=16&session=d857a5a46d140ac278d2f3e3f1f58f68&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=142323928&otype=json&ts=1583232975&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6d025bcc32e4ddc713dfe6c71dee4d11&qn=32&sign=9c24e8fb0caacfe17782d54cc4da558a","loginStatus":{"isLogin":true,"uname":"Gi文","mid":2310549,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=142323928&otype=json&ts=1583232975&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6d025bcc32e4ddc713dfe6c71dee4d11&qn=32&sign=9c24e8fb0caacfe17782d54cc4da558a\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Gi文\",\"mid\":2310549,\"level\":0,\"vip_expire\":0}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Comment by curecurse** [comment]
相同问题，可以正常刷出番剧页面但是播放的不是番剧而是16秒的自主和谐短视频，更换代理服务器无效
位置日本
浏览器版本Chrome 80.0.3987.122（正式版本）（64 位）

debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss29358?spm_id_from=333.334.b_72616e6b696e675f74696d696e675f62616e67756d69.5
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av: Y readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"_Shio","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=143079977&qn=80&type=&otype=json&avid=83536679&ep_id=307070&fourk=1&fnver=0&fnval=16&session=f908dc204041799daf3e234e6000eb2e&module=pgc
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=143079977&otype=json&ts=1583232713&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6c3fcaf382fd3fbf24d3615aad527e21&qn=80&sign=9fb2f6abe894a00824c2f71b54cbd70e","loginStatus":{"isLogin":true,"uname":"_Shio","mid":649378,"level":5,"vip_expire":1600876800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=143079977&otype=json&ts=1583232713&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6c3fcaf382fd3fbf24d3615aad527e21&qn=80&sign=9fb2f6abe894a00824c2f71b54cbd70e\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"_Shio\",\"mid\":649378,\"level\":5,\"vip_expire\":1600876800000}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=83536679&cid=143079977&bvid=&qn=80&type=&otype=json&ep_id=307070&fourk=1&fnver=0&fnval=16&session=c4d5d4d9952f0de986c4057bbbee9e42&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=143079977&otype=json&ts=1583232715&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6c3fcaf382fd3fbf24d3615aad527e21&qn=80&sign=1cb6fb5c1fa70464f664f914222795f7","loginStatus":{"isLogin":true,"uname":"_Shio","mid":649378,"level":5,"vip_expire":1600876800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=143079977&otype=json&ts=1583232715&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6c3fcaf382fd3fbf24d3615aad527e21&qn=80&sign=1cb6fb5c1fa70464f664f914222795f7\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"_Shio\",\"mid\":649378,\"level\":5,\"vip_expire\":1600876800000}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
debug: balh_server_inner  =>  __custom__
debug: balh_server_inner  =>  https://biliplus.ipcjs.top
debug: balh_server_inner  =>  https://www.biliplus.com

**Comment by tradce** [comment]
伺服器停業了，有人舉報
http://biliplus.ipcjs.top/tmp_home/end_of_service.htm

**Comment by PatriciaXiao** [comment]
坐标美国，枚举了所有设置，无效。

**Comment by realJuliaZ** [comment]
美国+1，还以为番剧下架了.....

**Comment by superpowermeatball** [comment]
坐標澳門，昨天3/4號凌晨還在看JOJO來著，晚上看就不行

**Comment by ironyx217** [comment]
香港人報到

**Comment by hinson** [comment]
是Chrome升级到80的问题，对跨域Cookie作了限制：https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
可以先用Firefox暂时解决
