### ISSUE TITLE
无法观看番剧，刷新出来的页面是提示自主和谐的16秒视频

### ISSUE THREAD

**Issue by curecurse** [ipcjs/bilibili-helper#564]
## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=143079977&otype=json&ts=1583232715&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=6c3fcaf382fd3fbf24d3615aad527e21&qn=80&sign=1cb6fb5c1fa70464f664f914222795f7\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"_Shio\",\"mid\":649378,\"level\":5,\"vip_expire\":1600876800000}}","code":-502}

位置：日本
使用浏览器：chrome80.0.3987.122（正式版本）64 位

**Comment by tradce** [comment]
伺服器停業，仔細情報往[這](http://biliplus.ipcjs.top/tmp_home/end_of_service.htm)
