### ISSUE TITLE
拉取视频地址失败，无法正常播放b站番剧

### ISSUE THREAD

**Issue by Chaos0482** [ipcjs/bilibili-helper#565]
坐标日本，b站的新番无法播放。刷新没有任何变化。

日志如下：

debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep98553
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=12686262&qn=0&type=&otype=json&avid=7738842&ep_id=98553&fourk=1&fnver=0&fnval=16&session=871af668d4f2c4112d19614daf160cb7&module=pgc
debug: /x/web-interface/nav {"uname":"伪物律","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=12686262&otype=json&ts=1583232007&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a2d68ffa48be1b1a47208c35ea18fa31&qn=112&sign=aef98e6cbb51972d7c6f67653e0048ab","loginStatus":{"isLogin":true,"uname":"伪物律","mid":5822548,"level":5,"vip_expire":1585411200000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=12686262&otype=json&ts=1583232007&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a2d68ffa48be1b1a47208c35ea18fa31&qn=112&sign=aef98e6cbb51972d7c6f67653e0048ab\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"伪物律\",\"mid\":5822548,\"level\":5,\"vip_expire\":1585411200000}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=7738842&cid=12686262&bvid=&qn=0&type=&otype=json&ep_id=98553&fourk=1&fnver=0&fnval=16&session=a70829536fb9fac9f0303c1a3b5696e2&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=12686262&otype=json&ts=1583232009&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a2d68ffa48be1b1a47208c35ea18fa31&qn=112&sign=ecb4035479ac8722e992be5df059ed79","loginStatus":{"isLogin":true,"uname":"伪物律","mid":5822548,"level":5,"vip_expire":1585411200000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=12686262&otype=json&ts=1583232009&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a2d68ffa48be1b1a47208c35ea18fa31&qn=112&sign=ecb4035479ac8722e992be5df059ed79\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"伪物律\",\"mid\":5822548,\"level\":5,\"vip_expire\":1585411200000}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

1. 浏览器版本：最新的谷歌浏览器
2. 国家/地区：日本

**Comment by tradce** [comment]
biliplus被舉報

http://biliplus.ipcjs.top/tmp_home/end_of_service.htm
看這

**Comment by PatriciaXiao** [comment]
坐标美国，一样。

**Comment by timi137137** [comment]
坐标HK，同样
