### ISSUE TITLE
各位昨天出現連線失敗錯誤的往這看！

### ISSUE THREAD

**Issue by tradce** [ipcjs/bilibili-helper#566]
現在應該可以正確授權賬戶以及看片了，所謂停業可能是跳轉問題，我進網時出了個停止登錄提示，點進去就說停業，但是可能是跳轉時出錯了，各位可以放心使用了。

**Comment by curecurse** [comment]
哇干，被被刺了（悲

**Comment by Giwen-git** [comment]
……停止服务了吗？
真是太遗憾了 QwQQQ 希望不是使用者举报

非常非常感谢大佬做的插件！让我们海外党能看到B站国内版权番，在国内的时候也用这个插件看港澳台特供番。每次用的时候看见屏幕上“拉取地址”的字样就打心里感恩做插件的大佬。不知道是不是永久停止服务了…希望还能有缘再用到

**Comment by PatriciaXiao** [comment]
真的假的……太难过了。

**Comment by syr-123** [comment]
> ……停止服务了吗？
> 真是太遗憾了 QwQQQ 希望不是使用者举报
> 
> 非常非常感谢大佬做的插件！让我们海外党能看到B站国内版权番，在国内的时候也用这个插件看港澳台特供番。每次用的时候看见屏幕上“拉取地址”的字样就打心里感恩做插件的大佬。不知道是不是永久停止服务了…希望还能有缘再用到

哇TAT我也是，我知道这个用了一年都还不到，真的十分方便orz太感谢大佬。真的希望还有机会能用到

**Comment by piaopiaomofa** [comment]
不是，你看看那个网址下面写的是2019年4月5日，去年的事情

**Comment by Chaos0482** [comment]
我记得去年也有一个BiliPlus被举报了来着。。。

**Comment by tradce** [comment]
現在是土豆服，不是biliplus

**Comment by tradce** [comment]
土豆服網址: http://biliplus.*ipcjs.top*/
biliplus網址: http://biliplus.*com*
後綴是不同的

**Comment by tradce** [comment]
剛才又彈出了停業通知，不知道是真是假，可是我登錄正常

**Comment by syr-123** [comment]
> 現在應該可以正確授權賬戶以及看片了，所謂停業可能是跳轉問題，我進網時出了個停止登錄提示，點進去就說停業，但是可能是跳轉時出錯了，各位可以放心使用了。

诶？但是我还是播放不了，进去就变成自主规制视频了

**Comment by curecurse** [comment]
> > 現在應該可以正確授權賬戶以及看片了，所謂停業可能是跳轉問題，我進網時出了個停止登錄提示，點進去就說停業，但是可能是跳轉時出錯了，各位可以放心使用了。
> 
> 诶？但是我还是播放不了，进去就变成自主规制视频了

下午还能正常播放的，刷新了一下也变成自主规制视频了

**Comment by Fanniesiu** [comment]
我也遇到这个问题了，下午本来在看然后再下一集就拉取失败了，换了服务器也还是

**Comment by tradce** [comment]
目前我似乎沒有再遇到這問題，可是網頁那邊仍然有顯示停服通知，不知道為什麼，或者你們可以試一試在頁面登入，再進插件裡授權

**Comment by tradce** [comment]
我剛才再試了試，應該沒事了，先到 http://biliplus.ipcjs.top 登入，再到插件裡授權登入

**Comment by syr-123** [comment]
> 我剛才再試了試，應該沒事了，先到 http://bilious.ipcjs.top 登入，再到插件裡授權登入

诶这个是什么网页，我打开显示400Bad Request打不开

**Comment by tradce** [comment]
抱歉，打錯了，是http://biliplus.ipcjs.top ，手快打錯了

**Comment by syr-123** [comment]
> 抱歉，打錯了，是http://biliplus.ipcjs.top ，手快打錯了

啊谢谢...但是我还是打不开orz

**Comment by tradce** [comment]
http://biliplus.ipcjs.top/

**Comment by tradce** [comment]
我可以點進去啊orz

**Comment by syr-123** [comment]
> 我可以點進去啊orz

谢谢！我能点进去了。但是登陆了账号之后重新授权还是看不了会员的番...（不过这个到底是授权上没也不知道，点“取消授权”取消不了的样子，但是点账号授权又显示成功）

**Comment by ipcjs** [comment]
你这网络延迟也太大，biliplus停业事件都是去年的事情了
