### ISSUE TITLE
是不是B站更新了，今天所有番剧都看不到，都是无法连接、服务器错误

### ISSUE THREAD

**Issue by chanchyin** [ipcjs/bilibili-helper#567]
debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss29308/?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.4
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=159536906&qn=32&type=&otype=json&avid=93438784&ep_id=314376&fourk=1&fnver=0&fnval=16&session=849178f1713ae08e5dc8cc87d40bc25b&module=pgc
debug: /x/web-interface/nav {"uname":"Chanchyin","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=159536906&otype=json&ts=1583237411&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a59e05ba9221d1f617f5017502874fa1&qn=32&sign=deb2ebfe5ca9587868dd58dc3d12ddd2","loginStatus":{"isLogin":true,"uname":"Chanchyin","mid":1440959,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=159536906&otype=json&ts=1583237411&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a59e05ba9221d1f617f5017502874fa1&qn=32&sign=deb2ebfe5ca9587868dd58dc3d12ddd2\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Chanchyin\",\"mid\":1440959,\"level\":0,\"vip_expire\":0}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=93438784&cid=159536906&bvid=&qn=32&type=&otype=json&ep_id=314376&fourk=1&fnver=0&fnval=16&session=c55933c2ad31818496520fcc08d4b708&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=159536906&otype=json&ts=1583237413&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a59e05ba9221d1f617f5017502874fa1&qn=32&sign=0bfd6560dc279e732df73b8cc72a9249","loginStatus":{"isLogin":true,"uname":"Chanchyin","mid":1440959,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=159536906&otype=json&ts=1583237413&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=a59e05ba9221d1f617f5017502874fa1&qn=32&sign=0bfd6560dc279e732df73b8cc72a9249\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Chanchyin\",\"mid\":1440959,\"level\":0,\"vip_expire\":0}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Comment by PatriciaXiao** [comment]
The same. 俺也一样。

**Comment by carina733** [comment]
俺也一样 昨晚还行现在就不行了

**Comment by gelesy** [comment]
同樣問題今天下午突然不能用了，現在只好先用VPN看，順便感謝開發給我用了很久的解除限制，這邊分享一下VPN的免費碼，有需要的先用這個撐過幾天吧，希望這裡過段時間就能用了，VPN免費的都慢....
MALUS https://getmalus.com/start/1L2K8P 邀請的有3天
這有兩個7天碼
TZCYWV4E8CINJ
T1MKR07ORA67Q

**Comment by carina733** [comment]
> 同樣問題今天下午突然不能用了，現在只好先用VPN看，順便感謝開發給我用了很久的解除限制，這邊分享一下VPN的免費碼，有需要的先用這個撐過幾天吧，希望這裡過段時間就能用了，VPN免費的都慢....
> MALUS https://getmalus.com/start/1L2K8P 邀請的有3天
> 這有兩個7天碼
> TZCYWV4E8CINJ
> T1MKR07ORA67Q

好像还是无法观看仅限台湾的番剧？

**Comment by gelesy** [comment]
> > 同樣問題今天下午突然不能用了，現在只好先用VPN看，順便感謝開發給我用了很久的解除限制，這邊分享一下VPN的免費碼，有需要的先用這個撐過幾天吧，希望這裡過段時間就能用了，VPN免費的都慢....
> > MALUS https://getmalus.com/start/1L2K8P 邀請的有3天
> > 這有兩個7天碼
> > TZCYWV4E8CINJ
> > T1MKR07ORA67Q
> 
> 好像还是无法观看仅限台湾的番剧？

這是給我們連過去的VPN..你要連出來應該要找翻牆的VPN阿
