### ISSUE TITLE
原先使用备选代理服务器突破黑洞失败后，再选用默认代理服务器可以连接上，但今天突然也没法链接了，刷新几次也没用，弹窗说无法连接服务器建议换一个试试。。。但备选代理服务器还是突破黑洞失败

### ISSUE THREAD

**Issue by szjhy0** [ipcjs/bilibili-helper#57]
## 描述

一直显示无法连接服务器或服务器返回异常
难道是默认服务器在晚上会关闭？
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep115386
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"帝国标准计量单位","isLogin":true,"level":4,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":115386,"last_ep_index":"15","last_time":0}}}
log: setAreaLimitSeason ep115386 true
log: {"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://upos-hz-mirrorks3.acgvideo.com/upgcxcode/43/69/8986943/8986943-1-16.mp4?e=ig8g5X10ugNcXBlqNCNEto8g5gNvNE3DN0B5tZlqNxTEto8BTrNvN05fqx6S5ahE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5to8euxZM2rNcNbUVhwdVhoM1hwdVhwdVNCM%3D&platform=ios&uipk=5&uipv=5&deadline=1516638988&gen=playurl&um_deadline=1516638988&rate=16478&um_sign=5259873dc546bfca6c20b78d47590ef3&dynamic=1&os=ks3&oi=3078818617&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM%3D&upsig=8b83031af6cad6bc9eee814d2fd5eb27"}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: setAreaLimitSeason ep115386 true
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
log: error {"0":{"readyState":0,"responseText":"","status":0,"statusText":"error"},"1":"error","2":""} {"url":"https://biliplus.ipcjs.win/BPplayurl.php?cid=30217997|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=a298075ce3cca390bf3ecd5de7f3d171","isLocal":false,"global":true,"type":"GET","contentType":"application/x-www-form-urlencoded; charset=UTF-8","processData":true,"async":true,"accepts":{"xml":"application/xml, text/xml","html":"text/html","text":"text/plain","json":"application/json, text/javascript","*":"*/*","script":"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},"contents":{"xml":{},"html":{},"json":{},"script":{}},"responseFields":{"xml":"responseXML","text":"responseText"},"converters":{"text html":true},"flatOptions":{"context":true,"url":true},"jsonp":"callback","xhrFields":{"withCredentials":true},"dataTypes":["text"],"crossDomain":true,"hasContent":false}
log: {"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-fjxm2-dx-v-01.acgvideo.com/vg2/a/75/8986943-1.mp4?expires=1516638900&platform=ios&ssig=uTnS6-4nYDasZoxAI6iZzA&oi=3078818617&nfa=QY4gbJYKJs7cixEssSU8nA==&dynamic=1&hfa=2018957888&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM="}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: setAreaLimitSeason ep115386 true
log: error {"0":{"readyState":0,"responseText":"","status":0,"statusText":"error"},"1":"error","2":""} {"url":"https://biliplus.ipcjs.win/BPplayurl.php?cid=30217997|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=49984fc662e67cd2bd6777dc0afbab16","isLocal":false,"global":true,"type":"GET","contentType":"application/x-www-form-urlencoded; charset=UTF-8","processData":true,"async":true,"accepts":{"xml":"application/xml, text/xml","html":"text/html","text":"text/plain","json":"application/json, text/javascript","*":"*/*","script":"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},"contents":{"xml":{},"html":{},"json":{},"script":{}},"responseFields":{"xml":"responseXML","text":"responseText"},"converters":{"text [html":true},"flatOptions":{"context":true,"url":true},"jsonp":"callback","xhrFields":{"withCredentials":true},"dataTypes":["text"],"crossDomain":true,"hasContent":false}]

## 其他

1. 浏览器版本：Safari 版本 11.0.2 (13604.4.7.1.6)
2. 国家/地区：大陆

**Comment by ipcjs** [comment]
重启服务器了😫，刷新下

**Comment by szjhy0** [comment]
非常感谢
