### ISSUE TITLE
 拉取视频地址失败

### ISSUE THREAD

**Issue by tyq0330** [ipcjs/bilibili-helper#570]
debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep35613
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=104238631&qn=112&type=&otype=json&avid=59846708&ep_id=35613&fourk=1&fnver=0&fnval=16&session=bcb94588f65f2a843dfda5dcdb0dc81f&module=pgc
debug: /x/web-interface/nav {"uname":"Abct","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=104238631&otype=json&ts=1583338912&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9dd2fed2eaaa5258821f5b0afaba2231&qn=112&sign=820c4d0809cf5c4414fbb525e569c64b","loginStatus":{"isLogin":true,"uname":"Abct","mid":1563159,"level":6,"vip_expire":1591977600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=104238631&otype=json&ts=1583338912&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9dd2fed2eaaa5258821f5b0afaba2231&qn=112&sign=820c4d0809cf5c4414fbb525e569c64b\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Abct\",\"mid\":1563159,\"level\":6,\"vip_expire\":1591977600000}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=59846708&cid=104238631&bvid=&qn=112&type=&otype=json&ep_id=35613&fourk=1&fnver=0&fnval=16&session=5bc6fa8987b1d1519d893d461864d045&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=104238631&otype=json&ts=1583338913&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9dd2fed2eaaa5258821f5b0afaba2231&qn=112&sign=7e4237bfe36dd2bd0f5995c607ea2f72","loginStatus":{"isLogin":true,"uname":"Abct","mid":1563159,"level":6,"vip_expire":1591977600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=104238631&otype=json&ts=1583338913&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9dd2fed2eaaa5258821f5b0afaba2231&qn=112&sign=7e4237bfe36dd2bd0f5995c607ea2f72\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Abct\",\"mid\":1563159,\"level\":6,\"vip_expire\":1591977600000}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Comment by himesamarose** [comment]
我这边也是这问题，不过尝试多刷几遍就能刷出来
