### ISSUE TITLE
账号授权没问题还是看不了会员番剧

### ISSUE THREAD

**Issue by xd-c-l** [ipcjs/bilibili-helper#572]
描述

账号授权显示储存完成，但是需要会员的番剧还是没法看（我的账号是年度大会员），清晰度也没法切换到需要会员的1080+，显示切换失败
- 问题网址：
https://www.bilibili.com/bangumi/play/ss6447/

## 日志
debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss6447/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=26889886&qn=112&type=&otype=json&avid=15392891&ep_id=115215&fourk=1&fnver=0&fnval=16&session=37b5baeb8a222a6613274011d8f6de8a&module=pgc
debug: /x/web-interface/nav {"uname":"lxdcy","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"accept_format":"mp4","code":0,"durl":[{"size":38369442,"ahead":"","length":269393,"vhead":"","backup_url":["https://upos-sz-mirrorks3.bilivideo.com/upgcxcode/86/98/26889886/26889886-1-29.mp4?e=ig8euxZM2rNcNbhB7WdVhoMz7WUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1584013987&gen=playurl&os=ks3bv&oi=3400790661&trid=ea9d28b583a44e87a7a637305d50952fp&platform=pc&upsig=7685a7719c5fc7a8e803d5eb4cf127f2&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=40000000"],"url":"https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/86/98/26889886/26889886-1-29.mp4?e=ig8euxZM2rNcNbhB7WdVhoMz7WUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1584013987&gen=playurl&os=cosbv&oi=3400790661&trid=ea9d28b583a44e87a7a637305d50952fp&platform=pc&upsig=f4170763be70f2a8e6aceb2bf687aecf&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=80000000","order":1,"md5":""}],"seek_param":"start","is_preview":1,"no_rexcode":0,"format":"mp4","fnval":16,"video_project":false,"fnver":0,"message":"","type":"MP4","accept_quality":[32],"bp":0,"quality":32,"timelength":1419948,"result":"suee","seek_type":"second","has_paid":false,"from":"local","video_codecid":7,"accept_description":["清晰 480P"],"status":13,"flvjsType":"mp4","loginStatus":{"isLogin":false}},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

## 其他

1. 浏览器版本：Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
2. 国家/地区：日本

**Comment by seeles** [comment]
一样。

**Comment by IceBlueI** [comment]
好像是代理服务器被举报停业了。

**Comment by heroerokero** [comment]
昨天还好好的，今天突然出现一样的问题

**Comment by Emmaory** [comment]
相似的问题 已经好几天看不了会员最新集了

debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep285761?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.57
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip: Y server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: epStatus 13 => 2 {"loaded":true,"id":285761,"badge":"会员","badgeType":0,"epStatus":13,"aid":96010471,"bvid":"BV11E411G7Rg","cid":164081063,"from":"bangumi","cover":"//i0.hdslb.com/bfs/archive/a214a94d3f3717aa5df049fab0a21735702da25b.jpg","title":"11","titleFormat":"第11话","vid":"","longTitle":"怪物 战火蔓延的大海","hasNext":false,"i":10,"sectionType":0,"releaseDate":"","skip":{},"hasSkip":false}
debug: epStatus 13 => 2 {"loaded":true,"id":285761,"badge":"会员","badgeType":0,"epStatus":13,"aid":96010471,"bvid":"BV11E411G7Rg","cid":164081063,"from":"bangumi","cover":"//i0.hdslb.com/bfs/archive/a214a94d3f3717aa5df049fab0a21735702da25b.jpg","title":"11","titleFormat":"第11话","vid":"","longTitle":"怪物 战火蔓延的大海","hasNext":false,"i":10,"sectionType":0,"releaseDate":"","skip":{},"hasSkip":false}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=164081063&qn=112&type=&otype=json&avid=96010471&ep_id=285761&fourk=1&fnver=0&fnval=16&session=08881bb5dae85e9a2dbc2b03996842d0&module=pgc
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164081063&otype=json&ts=1584318735&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=8c1185f8eb7f261f07b23d7297897bb1","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164081063&otype=json&ts=1584318735&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=8c1185f8eb7f261f07b23d7297897bb1\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: /x/web-interface/nav {"uname":"LelocheouViBritannia","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=96010471&cid=164081063&bvid=&qn=112&type=&otype=json&ep_id=285761&fourk=1&fnver=0&fnval=16&session=17fe24eef7da766c38ea32c5de1a38ba&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164081063&otype=json&ts=1584318736&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=c8bf80de7e83e95bf08db58c3004edcb","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164081063&otype=json&ts=1584318736&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=c8bf80de7e83e95bf08db58c3004edcb\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: /x/player.so
debug: balh_mode  =>  default
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Comment by syr-123** [comment]
+1 半月前就这样了
