### ISSUE TITLE
日本无法正常观看大会员番剧

### ISSUE THREAD

**Issue by yn2103** [ipcjs/bilibili-helper#574]
脚本问题：@ipcjs

## 描述
插件用了很久了，到上周开始出现异常，
授权之后依然无法看需要大会员的番剧，非大会员番剧一切正常
同一ip下，另一电脑可以使用同一版本的脚本和同一B站账号正常观看
似乎是页面显示授权成功但是实际授权没有成功？

- 问题网址：https://www.bilibili.com/bangumi/play/ep307430

## 日志
debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep307430
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=164249442&qn=0&type=&otype=json&avid=96212761&ep_id=307430&fourk=1&fnver=0&fnval=16&session=6db9a27225baae8b574c30a37476c0d2&module=pgc
debug: /x/web-interface/nav {"uname":"******（隐去）","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164249442&otype=json&ts=1584229460&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=83c5e8b45c023fa15ece38b1dceaeb3e","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164249442&otype=json&ts=1584229460&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=83c5e8b45c023fa15ece38b1dceaeb3e\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=96212761&cid=164249442&bvid=&qn=0&type=&otype=json&ep_id=307430&fourk=1&fnver=0&fnval=16&session=f797cb0ae5decf94418d66f3416378e4&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164249442&otype=json&ts=1584229462&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=c7d5112821f58228a0704cae0d00aabf","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=164249442&otype=json&ts=1584229462&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=112&sign=c7d5112821f58228a0704cae0d00aabf\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
 
## 其他

1. 浏览器版本：Chrome 80.0.3987.132（正式版本） （64 位）
2. 国家/地区：日本东京softbank

**Comment by syr-123** [comment]
同样的问题...半个月前就这样了，账号授权没问题，但是选择取消账号授权反而退不出去，而且会员番剧还是看不了orz

**Comment by ipcjs** [comment]
`"isLogin":false`，可以确定授权时没成功的，重新授权试试？
