### ISSUE TITLE
会员番剧最新话看不了

### ISSUE THREAD

**Issue by 2166888** [ipcjs/bilibili-helper#580]
所以需要大会员看最新话的番剧的最新话都无法观看
有大会员，已授权
显示内容如下
## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=165709414&otype=json&ts=1584539609&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=b9a1658432f111814145349eafc6c81d\",\"loginStatus\":{\"isLogin\":false}}","code":-502}

尝试过退出账号和清楚cookie

**Comment by angiwww** [comment]
同样的问题。
Chrome 80.0 win10-64

大会员授权页面卡住，登录不上

**Comment by momo5124** [comment]
同一个问题，重装了chrome＋清除cookie还是不行

**Comment by 2166888** [comment]
更新
莫名其妙去试了一下QQ浏览器，同一电脑同一网络却没有出现这个问题，能够正常观看大会员限定的最新话，就是不知道Chrome为什么不行了，不想转其他浏览器

**Comment by syr-123** [comment]
同样的问题，半个月前就这样了，账号授权没问题，但是选择取消账号授权反而退不出去，而且会员番剧还是看不了orz

**Comment by Matrix-J-H** [comment]
之前一段时间也是这样，后来好了。现在又这样了，看需要会员的最新话可以，开放给非会员的过往话就没问题。我用的是chrome，应该是最新版本。
报错代码：
## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=167173978&otype=json&ts=1584742045&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=116&sign=0f619b71d4f9aa1a3f5de7d07245c7ff\",\"loginStatus\":{\"isLogin\":false}}","code":-502}

**Comment by DF-wu** [comment]
same issue

## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=167173978&otype=json&ts=1584751367&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=116&sign=de030101b3c1ad5288ebda200639cf16\",\"loginStatus\":{\"isLogin\":false}}","code":-502}

**Comment by Yihang95** [comment]
我用chrome也不行，然后试了一下用firefox就可以看了。。

**Comment by gnosisyuw** [comment]
嗯，的确是chrome的问题，我用firefox也可以看。看起来应该是大会员授权在chrome出了问题。如果firefox不授权报得是一样的错误。

**Comment by wuzhengkai** [comment]
发现一个临时修复方式：
将chrome://flags/#same-site-by-default-cookies设为disabled。

参考：https://stackoverflow.com/a/60592944

**Comment by gnosisyuw** [comment]
> 发现一个临时修复方式：
> 将chrome://flags/#same-site-by-default-cookies设为disabled。
> 
> 参考：https://stackoverflow.com/a/60592944

实测有效

**Comment by Energy0124** [comment]
> 发现一个临时修复方式：
> 将chrome://flags/#same-site-by-default-cookies设为disabled。
> 
> 参考：https://stackoverflow.com/a/60592944

Confirmed that it works! It is likely that Chrome's latest changes that make cookies set by Bilbilli not sent to the proxy server by default, which is why the api request on the proxy return "无法连接到playurl". Thank you!
