### ISSUE TITLE
大会员电影只能看6分钟已经持续很长一段时间了

### ISSUE THREAD

**Issue by AiotrM** [ipcjs/bilibili-helper#583]
万分感谢作者，希望能修复一下

debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28585/?from=search&seid=14542105712471795361
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"Coin硬币君","isLogin":true,"level":6,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ss28585 true
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=122716321&qn=116&type=&otype=json&avid=70665722&ep_id=285026&fourk=1&fnver=0&fnval=16&session=06b9a58315dc3249c35589f601c4b61e&module=pgc
debug: /pgc/player/web/playurl proxy {"code":0,"result":{"accept_format":"mp4","code":0,"durl":[{"size":45640432,"ahead":"","length":360109,"vhead":"","backup_url":["https://upos-sz-mirrorks3.bilivideo.com/upgcxcode/21/63/122716321/122716321-1-29.mp4?e=ig8euxZM2rNcNbh17WdVhoMzhWUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1584799374&gen=playurl&os=ks3bv&oi=3400791657&trid=d6cd8f14995a4ac98584f13fb8690551p&platform=pc&upsig=a4bde08a1cf03924cd6a0649247f35a7&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=40000000"],"url":"https://upos-sz-mirrorkodo.bilivideo.com/upgcxcode/21/63/122716321/122716321-1-29.mp4?e=ig8euxZM2rNcNbh17WdVhoMzhWUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1584799374&gen=playurl&os=kodobv&oi=3400791657&trid=d6cd8f14995a4ac98584f13fb8690551p&platform=pc&upsig=e428864e71c0da571fae51bd38a28790&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=80000000","order":1,"md5":""}],"seek_param":"start","is_preview":1,"no_rexcode":0,"format":"mp4","fnval":16,"video_project":false,"fnver":0,"message":"","type":"MP4","accept_quality":[32],"bp":0,"quality":32,"timelength":10143957,"result":"suee","seek_type":"second","has_paid":false,"from":"local","video_codecid":7,"accept_description":["清晰 480P"],"status":13,"flvjsType":"mp4","loginStatus":{"isLogin":false}},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by lxl217114** [comment]
是的，大部分大会员才能观看的资源，点开以后直接跳转出只播放6分钟的页面
![T%QC~`13U3_ @ZT75A_LKJ](https://user-images.githubusercontent.com/54263659/85986027-2c1b6700-ba1e-11ea-9034-9b6095dc3dbb.png)
