### ISSUE TITLE
看不到番劇的最新話

### ISSUE THREAD

**Issue by fate01076** [ipcjs/bilibili-helper#584]
脚本问题：@ipcjs

## 描述

每一套新番的最新話都沒法成功跳轉
- 问题网址：https://www.bilibili.com/bangumi/play/ep285911

## 日志
debug: [解除B站区域限制 v7.9.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep285911
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"朝田詩乃","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=167527446&qn=80&type=&otype=json&avid=98138712&ep_id=285911&fourk=1&fnver=0&fnval=16&session=d7cb6876105c32c0a175fc308767374d&module=pgc
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=167527446&otype=json&ts=1584811032&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=8d4b48f7bef465c1735f75d1297e7051","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=167527446&otype=json&ts=1584811032&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=8d4b48f7bef465c1735f75d1297e7051\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=98138712&cid=167527446&bvid=&qn=80&type=&otype=json&ep_id=285911&fourk=1&fnver=0&fnval=16&session=83d6d9d01c0e7383911531390948f5b3&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=167527446&otype=json&ts=1584811034&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=2d89305b6a755a24d678d82bc6fba8f3","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=167527446&otype=json&ts=1584811034&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=2d89305b6a755a24d678d82bc6fba8f3\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: balh_server_inner  =>  https://biliplus.ipcjs.top
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
debug: balh_mode  =>  default
debug: balh_server_inner  =>  https://www.biliplus.com
debug: balh_server_inner  =>  https://biliplus.ipcjs.top
debug: balh_server_inner  =>  https://www.biliplus.com
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by stbaqi** [comment]
不仅是最新话，所有与会员相关的权益均无法使用，包括1080p
