### ISSUE TITLE
脚本对B站最新的BV视频无效

### ISSUE THREAD

**Issue by karaikyo** [ipcjs/bilibili-helper#589]
脚本问题：@ipcjs
## 描述

不支持 https://www.bilibili.com/video/BV* 这样的视频地址

- 问题网址：
例如 https://www.bilibili.com/video/BV1JJ411q7pq

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Chrome 80.0.3987.149 
2. 国家/地区：UK

**Comment by Cecropis** [comment]
临时的解决方案：
手动替换掉脚本里的www.bilibili.com/video/av 到 www.bilibili.com/video/BV

**Comment by schenad** [comment]
从番剧页（ https://www.bilibili.com/bangumi/play/epXXXXX ）直接进去还是可以看的~只是没法跳转，脚本并没有失效

**Comment by Cecropis** [comment]
> 从番剧页（ https://www.bilibili.com/bangumi/play/epXXXXX ）直接进去还是可以看的~只是没法跳转，脚本并没有失效

是的，不过他应该是和我一样勾选了‘在av页面启用’的患者233333

**Comment by ipcjs** [comment]
最新版，在BV页面启用了

**Comment by schenad** [comment]
Chrome 还是跳转失败：
error:{"code":-400,"message":"请求错误","ttl":1}

但是如果手动将BV号转成av号，就可以跳转成功

**Comment by ipcjs** [comment]
修了，再更新下脚本
