### ISSUE TITLE
3104

### ISSUE THREAD

**Issue by l89669** [ipcjs/bilibili-helper#59]
Darling in the franxx
多次提示授权，已授权，本人年度大会员（授权成功后就自动刷新页面，然后继续突破黑洞失败提示授权）
重新安装过脚本，无效
chrome最新版本，html5播放器

ep183800:1 The SSL certificate used to load resources from https://www.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183800
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 log: mode: redirect blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: Y remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
ep183800:1 The SSL certificate used to load resources from https://data.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ep183800:1 The SSL certificate used to load resources from https://api.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ep183800:1 The SSL certificate used to load resources from https://comment.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 log: /x/web-interface/nav Object
ep183800:1 The SSL certificate used to load resources from https://bangumi.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ep183800:1 The SSL certificate used to load resources from https://i2.hdslb.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ep183800:1 The SSL certificate used to load resources from https://message.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ep183800:1 The SSL certificate used to load resources from https://big.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
ep183800:1 Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183800,"last_ep_index":"2","last_time":611}}}
ep183800:1 The SSL certificate used to load resources from https://interface.bilibili.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=30219063|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=e2dc70b8ef649870db6a5ced8b93e1f9
ep183800:1 The SSL certificate used to load resources from https://static.hdslb.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 error: >>area limit
(anonymous) @ chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168
ep183800:1 Additional resources on this page were loaded with SSL certificates that will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. Seehttps://g.co/chrome/symantecpkicerts for more information.
cn-zjwz-dx-v-10.acgvideo.com/vg1/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1516745100&platform=ios&ssig=u-D5jIu1DgHUbsaopm4e4g&oi=3078818617&nfa=QY4gbJYKJs7cixEssSU8nA==&dynamic=1&hfa=2018817344&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM= Failed to load resource: the server responded with a status of 460 ()
third.70210bc511ec149b5fe2.js:9 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=30219063|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=e2dc70b8ef649870db6a5ced8b93e1f9
userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168 error: >>area limit
(anonymous) @ userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:168
processProxySuccess @ userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:1094
param.success @ userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:843
o @ jquery.min.js:2
fireWith @ jquery.min.js:2
w @ jquery.min.js:4
d @ jquery.min.js:4
value @ userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:766
XMLHttpRequest.send (async)
value @ userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:779
send @ jquery.min.js:4
ajax @ jquery.min.js:4
$.ajax @ userscript.html?id=b01c9c66-0ff0-475d-88a8-a800ea26ba13:903
t.ajax @ comment.min.js:1
f.ajax @ bilibiliPlayer.min.js?v=d4f4a9fb:257
(anonymous) @ bilibiliPlayer.min.js?v=d4f4a9fb:1062
yH @ bilibiliPlayer.min.js?v=d4f4a9fb:1336
d @ bilibiliPlayer.min.js?v=d4f4a9fb:1354
da @ bilibiliPlayer.min.js?v=d4f4a9fb:1393
d @ bilibiliPlayer.min.js?v=d4f4a9fb:1354
ia @ bilibiliPlayer.min.js?v=d4f4a9fb:1392
dynCall_vi @ bilibiliPlayer.min.js?v=d4f4a9fb:1395
Sq @ bilibiliPlayer.min.js?v=d4f4a9fb:1089
JA.e.(anonymous function).e.(anonymous function) @ bilibiliPlayer.min.js?v=d4f4a9fb:1090
d @ bilibiliPlayer.min.js?v=d4f4a9fb:1337
(anonymous) @ bilibiliPlayer.min.js?v=d4f4a9fb:1080
setTimeout (async)
$a @ bilibiliPlayer.min.js?v=d4f4a9fb:1080
aD @ bilibiliPlayer.min.js?v=d4f4a9fb:1337
d @ bilibiliPlayer.min.js?v=d4f4a9fb:1353
_r @ bilibiliPlayer.min.js?v=d4f4a9fb:1395
(anonymous) @ VM3933:1
r @ bilibiliPlayer.min.js?v=d4f4a9fb:1063
f.Jm @ bilibiliPlayer.min.js?v=d4f4a9fb:236
(anonymous) @ bilibiliPlayer.min.js?v=d4f4a9fb:245
8986943-1-16.mp4:1 GET https://cn-zjwz-dx-v-10.acgvideo.com/vg1/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1516745100&platform=ios&ssig=G12PrbnYd1aSlK17m36TfA&oi=3078818617&nfa=QY4gbJYKJs7cixEssSU8nA==&dynamic=1&hfa=2018817348&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM= 460 ()
geetest.6.0.9.js:1 Uncaught ReferenceError: errors is not defined
    at Object.v7B.(anonymous function) [as Wa] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:90988)
    at k7B.v7B.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:97923)
    at k7B.<anonymous> (https://static.geetest.com/static/js/geetest.6.0.9.js:1:108015)
    at Object.n7B.(anonymous function) [as I] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:181400)
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78846
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:203044
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78247
    at r8W (https://static.geetest.com/static/js/geetest.6.0.9.js:1:196533)
    at HTMLLinkElement.M0B.Y8W.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:193881)
v7B.(anonymous function) @ geetest.6.0.9.js:1
v7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
n7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
r8W @ geetest.6.0.9.js:1
M0B.Y8W.(anonymous function) @ geetest.6.0.9.js:1
geetest.6.0.9.js:1 Uncaught ReferenceError: errors is not defined
    at Object.v7B.(anonymous function) [as Wa] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:90988)
    at k7B.v7B.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:97923)
    at k7B.<anonymous> (https://static.geetest.com/static/js/geetest.6.0.9.js:1:108015)
    at Object.n7B.(anonymous function) [as I] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:181400)
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78846
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:203044
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78571
v7B.(anonymous function) @ geetest.6.0.9.js:1
v7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
n7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
setTimeout (async)
(anonymous) @ geetest.6.0.9.js:1
w7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
l6W @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
w7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
w7B.(anonymous function) @ geetest.6.0.9.js:1
N0B @ geetest.6.0.9.js:1
P7B.Q7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ get.php?gt=1aa3ab3b7f07681cb310696cd27932d1&challenge=79736bfd7c64c9b43e9de08d28cbd619&width=100%&product=float&offline=false&protocol=https://&path=/static/js/geetest.6.0.9.js&type=slide&callback=geetest_1516738130286:1
third.70210bc511ec149b5fe2.js:9 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
geetest.6.0.9.js:1 Uncaught ReferenceError: errors is not defined
    at Object.v7B.(anonymous function) [as Wa] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:90988)
    at k7B.v7B.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:97923)
    at k7B.<anonymous> (https://static.geetest.com/static/js/geetest.6.0.9.js:1:108015)
    at Object.n7B.(anonymous function) [as I] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:181400)
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78846
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:203044
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78247
    at r8W (https://static.geetest.com/static/js/geetest.6.0.9.js:1:196533)
    at HTMLLinkElement.M0B.Y8W.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:193881)
v7B.(anonymous function) @ geetest.6.0.9.js:1
v7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
n7B.(anonymous function) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
(anonymous) @ geetest.6.0.9.js:1
r8W @ geetest.6.0.9.js:1
M0B.Y8W.(anonymous function) @ geetest.6.0.9.js:1
geetest.6.0.9.js:1 Uncaught ReferenceError: errors is not defined
    at Object.v7B.(anonymous function) [as Wa] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:90988)
    at k7B.v7B.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:97923)
    at k7B.<anonymous> (https://static.geetest.com/static/js/geetest.6.0.9.js:1:108015)
    at Object.n7B.(anonymous function) [as I] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:181400)
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78846
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:203044
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78571

**Comment by ipcjs** [comment]
你这一大堆log看得我头疼，能不能用脚本的“复制日志”功能？

**Comment by l89669** [comment]
已经好了。看来是服务器出问题了
话说如果服务器出问题能不能直接提示服务器有问题而不是莫名其妙的一次又一次要授权？

**Comment by ipcjs** [comment]
那要怎么判断是不是服务器出问题呢？
