### ISSUE TITLE
BV轉番劇貌相失效

### ISSUE THREAD

**Issue by tkp206093** [ipcjs/bilibili-helper#590]
脚本问题：@ipcjs

## 描述

RT
- 问题网址：https://www.bilibili.com/video/BV1D741127hL

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：360極速瀏覽器 12.0.1190.0 內核版本 78.0.3904.108
2. 国家/地区：香港

**Comment by ipcjs** [comment]
9b6d3ebb34630d63cc35e12a105cd114f5ca08e9
