### ISSUE TITLE
已经一个月不好使了 所有的剧番都看不了

### ISSUE THREAD

**Issue by v2dstavwng** [ipcjs/bilibili-helper#593]
debug: [解除B站区域限制 v7.9.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss29358/?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.9
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=169512624&qn=32&type=&otype=json&avid=412567123&ep_id=307080&fourk=1&fnver=0&fnval=16&session=708d9b694a201618f5c83d19906c3557&module=pgc
debug: /x/web-interface/nav {"uname":"幻H想","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=169512624&otype=json&ts=1585232214&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=32&sign=e4e372bac9a782e5ebee57c049d4716b","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=169512624&otype=json&ts=1585232214&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=32&sign=e4e372bac9a782e5ebee57c049d4716b\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=412567123&cid=169512624&bvid=&qn=32&type=&otype=json&ep_id=307080&fourk=1&fnver=0&fnval=16&session=02d52aa31bd57c5a207db10a94a01d5d&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=169512624&otype=json&ts=1585232216&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=32&sign=f85ba41eafc45cd7e0fc3389fb51edb2","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=169512624&otype=json&ts=1585232216&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=32&sign=f85ba41eafc45cd7e0fc3389fb51edb2\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by v2dstavwng** [comment]
刚刚看了一下 是所有的大会员限定视频无法观看 重新授权也没用

**Comment by xiangshao** [comment]
是的，有同样的问题

**Comment by v2dstavwng** [comment]
解决问题了 首先把bilibili港澳台脚本关掉 谷歌浏览器  进chrome://flags/  
找到SameSite by default cookies 设置为 Disabled
重启浏览器 重新授权 就可以看了

**Comment by mylaluna** [comment]
楼上正解，而且好像必须一直Disabled

**Comment by GalvinGao** [comment]
> chrome://flags/

直达链接 chrome://flags/#same-site-by-default-cookies
另外顺便说下：
- 设置后需要重启浏览器；并且
- 重启后如果还是出现 `code: -502`，重新**授权账号**就可以正常使用了~
