### ISSUE TITLE
剧番最新话 大会员视频 无法观看解决方法

### ISSUE THREAD

**Issue by v2dstavwng** [ipcjs/bilibili-helper#595]
首先把bilibili港澳台脚本关掉（有冲突的脚本都关掉） 
谷歌浏览器  进chrome://flags/  
找到SameSite by default cookies 设置为 Disabled
重启浏览器 重新授权 就可以看了

**Comment by reeeno** [comment]
这个workaround好使，感谢！

**Comment by YU1ut** [comment]
感谢！

**Comment by AiotrM** [comment]
感謝

**Comment by tyq0330** [comment]
感谢

**Comment by oskarkyle** [comment]
感谢

**Comment by theonaku** [comment]
補充一句，Safari中只需要打開 Prevent cross-site tracking即可

**Comment by zxy15647** [comment]
試了有效，非常感謝
