### ISSUE TITLE
7.9.2版本在旧版Chrome上不工作

### ISSUE THREAD

**Issue by CyclonicPinna** [ipcjs/bilibili-helper#596]
Chrome版本：49.0.2623.112。

更新7.9.2版本后脚本完全不工作，无法跳转页面、播放页面直接显示地区限制，无法播放、也不显示脚本设置按钮。退回到7.9.1版本可以正常使用。

**Comment by ipcjs** [comment]
你这也太老了，升级下吧

**Comment by CyclonicPinna** [comment]
老电脑发挥余热，运行的XP系统，49.0.2623.112是最后一个支持XP的Chrome版本，考虑到硬件问题升级是基本不可能了。不知道有没有其他方法可以解决。尝试了一下，脚本在Firefox上是可以正常运行的，不知道和Chrome相比具体存在哪些区别。在最后一版支持XP系统的Firefox 52.9 ESR以及基于更老版本Firefox 38 ESR修改的Palemoon上都可以正常运行。

**Comment by ipcjs** [comment]
可能是新代码里有`**`导致的吧，试下7.9.3+

**Comment by CyclonicPinna** [comment]
感谢回复，试了下7.9.3版本目前没有遇到问题，可以正常运行。
