### ISSUE TITLE
特定番剧及特定集数无法观看

### ISSUE THREAD

**Issue by damondql** [ipcjs/bilibili-helper#598]
特定番剧及特定集数无法观看， 尝试过切换代理服务器以及账号授权（有大会员）都没有解决。
地区：美国
浏览器：Chrome 80.0.3987.149
日志如下：
debug: [解除B站区域限制 v7.9.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep307134?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.6
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=172592078&qn=80&type=&otype=json&avid=582562079&ep_id=307134&fourk=1&fnver=0&fnval=16&session=4f17a19e7857ef80664ab30a9a4f9d16&module=pgc
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=172592078&otype=json&ts=1585788496&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=b8ad2b8bbc3a88fc4884d0d33f4a4895","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=172592078&otype=json&ts=1585788496&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=b8ad2b8bbc3a88fc4884d0d33f4a4895\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: /x/web-interface/nav {"uname":"叮啊啡","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=582562079&cid=172592078&bvid=&qn=80&type=&otype=json&ep_id=307134&fourk=1&fnver=0&fnval=16&session=f430d0a55631b3aa68b9e8a8e9710cbb&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=172592078&otype=json&ts=1585788498&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=071afafab70e62ebd998cd2b77932ae2","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=172592078&otype=json&ts=1585788498&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=&qn=80&sign=071afafab70e62ebd998cd2b77932ae2\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by Energy0124** [comment]
這裏有臨時的解決方法, 實測可用
https://github.com/ipcjs/bilibili-helper/issues/580#issuecomment-603033541
