### ISSUE TITLE
大会员的视频看不了 什么时候解决呀

### ISSUE THREAD

**Issue by nevo001** [ipcjs/bilibili-helper#599]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志
debug: [解除B站区域限制 v7.9.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss1660
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cosu flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"nevo001","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ss1660 true
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=2954005&qn=112&type=&otype=json&avid=1913027&ep_id=30134&fourk=1&fnver=0&fnval=16&session=a3edf5182e74f1d1d43e06a1dc016d1b&module=pgc
debug: /pgc/player/web/playurl proxy {"code":0,"result":{"accept_format":"flv,flv720,flv480,flv360","code":0,"durl":[{"size":42798196,"ahead":"","length":338398,"vhead":"AWQAHv/hABhnZAAerMhQNg95+EAAAPpAAC7gI8WLZYABAAZo6+HyyLD9+PgA","backup_url":["https://upos-sz-mirrorks3.bilivideo.com/upgcxcode/05/40/2954005/2954005-1-80.flv?e=ig8euxZM2rNcNbh17WdVhoMzhWUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=ks3bv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=baa639072bfff0f3c61dfd9312eebd50&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=40000000"],"url":"https://upos-sz-mirrorkodo.bilivideo.com/upgcxcode/05/40/2954005/2954005-1-80.flv?e=ig8euxZM2rNcNbh17WdVhoMzhWUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=kodobv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=e687444c28fb8ecfb675edf950d45d7f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=80000000","order":1,"md5":""},{"size":24089293,"ahead":"","length":301070,"vhead":"","backup_url":["https://upos-sz-mirrorks3.bilivideo.com/upgcxcode/05/40/2954005/2954005-2-80.flv?e=ig8euxZM2rNcNbNVhwdVhoMghwdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=ks3bv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=5c5e44a14a75380a28d031565d48ae75&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=40000000"],"url":"https://upos-sz-mirrorhw.bilivideo.com/upgcxcode/05/40/2954005/2954005-2-80.flv?e=ig8euxZM2rNcNbNVhwdVhoMghwdVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=hwbv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=f7dcd78fba6e068452a0f8f60473d549&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=80000000","order":2,"md5":""},{"size":29692792,"ahead":"","length":362256,"vhead":"","backup_url":["https://upos-sz-mirrorks3.bilivideo.com/upgcxcode/05/40/2954005/2954005-3-80.flv?e=ig8euxZM2rNcNbNVhbUVhoMghwNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=ks3bv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=1f52cc93ef3e119220671b6874196d7b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=40000000"],"url":"https://upos-sz-mirrorkodo.bilivideo.com/upgcxcode/05/40/2954005/2954005-3-80.flv?e=ig8euxZM2rNcNbNVhbUVhoMghwNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=kodobv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=cbc230fd4c40801d01f98dc61931b3ab&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=80000000","order":3,"md5":""},{"size":53539332,"ahead":"","length":428060,"vhead":"","backup_url":["https://upos-sz-mirrorks3.bilivideo.com/upgcxcode/05/40/2954005/2954005-4-80.flv?e=ig8euxZM2rNcNbh1hbUVhoMzhWNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=ks3bv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=dee1106226c22ec03cd7fcc68fb3c7f1&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=40000000"],"url":"https://upos-sz-mirrorhw.bilivideo.com/upgcxcode/05/40/2954005/2954005-4-80.flv?e=ig8euxZM2rNcNbh1hbUVhoMzhWNBhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1585974827&gen=playurl&os=hwbv&oi=3400791302&trid=6530dd75f3eb420e898c99e0e3bc6fc9p&platform=pc&upsig=a0052205bce20dace8aef1d69934c4fb&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&logo=80000000","order":4,"md5":""}],"seek_param":"start","is_preview":0,"no_rexcode":0,"format":"flv","fnval":16,"video_project":true,"fnver":0,"message":"","type":"FLV","accept_quality":[80,64,32,16],"bp":0,"quality":80,"timelength":1429784,"result":"suee","seek_type":"offset","has_paid":false,"from":"local","video_codecid":7,"accept_description":["高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":2,"flvjsType":"flv","loginStatus":{"isLogin":false}},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"nevo001","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep30137 true
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=1913027&cid=2954050&bvid=&qn=112&type=&otype=json&ep_id=30137&fourk=1&fnver=0&fnval=16&session=bce070d55f61c6e66897943cb525d3e6&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=2954050&otype=json&ts=1585960430&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&qn=112&sign=80a6839d4b7f91a93ffe6766c64452c0","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=2954050&otype=json&ts=1585960430&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&qn=112&sign=80a6839d4b7f91a93ffe6766c64452c0\",\"loginStatus\":{\"isLogin\":false}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by Energy0124** [comment]
這裏有臨時的解決方法, 實測可用
https://github.com/ipcjs/bilibili-helper/issues/580#issuecomment-603033541

**Comment by songzhuoru** [comment]
> 這裏有臨時的解決方法, 實測可用
> [#580 (comment)](https://github.com/ipcjs/bilibili-helper/issues/580#issuecomment-603033541)

好像又不行了
