### ISSUE TITLE
登陆了N多次依然说黑洞失败

### ISSUE THREAD

**Issue by andyfriendgamw** [ipcjs/bilibili-helper#60]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by andyfriendgamw** [comment]
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep115383
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"andy的游戏","isLogin":true,"level":3,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":115382,"last_ep_index":"11","last_time":1316}}}
log: setAreaLimitSeason ep115383 true
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=28640482|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=0&module=bangumi&season_type=1&qn=0&sign=521a0560b73206879229031f27b17756
error: >>area limit
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=28640482|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=180ee9cd004c8811de8a0c6aa7bf104e
error: >>area limit
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by andyfriendgamw** [comment]
浏览器是火狐的最新版 国家是中国

**Comment by ipcjs** [comment]
换个代理服务器
