### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by ginlzc** [ipcjs/bilibili-helper#613]
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=178316299&otype=json&ts=1588170178&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=79ad2247c95022b28fc6bde90a29a141&qn=80&sign=b7d12304168fe8c8cf8bcd1d70820d78\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Ginlzc96\",\"mid\":288326165,\"level\":5,\"vip_expire\":1619193600000}}","code":-502}

**Comment by Nicomakii** [comment]
+1
debug: [解除B站区域限制 v7.9.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss32974/?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.4
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=175514325&qn=64&type=&otype=json&fourk=1&bvid=BV1Q541147W4&ep_id=317442&fnver=0&fnval=16&session=aac1c2dbf5217d2dd5373ea207d62136&module=pgc
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"Nicomakii","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=175514325&otype=json&ts=1588176582&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=4a66b6fe8bf49428e74d39ba26639041&qn=64&sign=212b7679526b4c8ffc5ebb68ce9bf759","loginStatus":{"isLogin":true,"uname":"Nicomakii","mid":3971724,"level":5,"vip_expire":1612713600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=175514325&otype=json&ts=1588176582&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=4a66b6fe8bf49428e74d39ba26639041&qn=64&sign=212b7679526b4c8ffc5ebb68ce9bf759\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Nicomakii\",\"mid\":3971724,\"level\":5,\"vip_expire\":1612713600000}}","code":-502}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=175514325&bvid=BV1Q541147W4&qn=64&type=&otype=json&ep_id=317442&fourk=1&fnver=0&fnval=16&session=62e6fdbdcedfe13288b55677b0576649&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=175514325&otype=json&ts=1588176584&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=4a66b6fe8bf49428e74d39ba26639041&qn=64&sign=e893cec8fa404bb550d1fe4c19073963","loginStatus":{"isLogin":true,"uname":"Nicomakii","mid":3971724,"level":5,"vip_expire":1612713600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=175514325&otype=json&ts=1588176584&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=4a66b6fe8bf49428e74d39ba26639041&qn=64&sign=e893cec8fa404bb550d1fe4c19073963\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Nicomakii\",\"mid\":3971724,\"level\":5,\"vip_expire\":1612713600000}}","code":-502}
debug: /x/web-interface/nav {"uname":"*******","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36

**Comment by eleanoryy** [comment]
+1
