### ISSUE TITLE
刷新页面就会提示“尚未开播”

### ISSUE THREAD

**Issue by peter17ji** [ipcjs/bilibili-helper#62]
## 描述

使用“被永封的大会员”后观看1080p番剧《宅饮》时刷新页面就会提示“尚未开播”。《爱吃拉面的小泉同学》也有一样的问题。
## 日志
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183850
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip: Y server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"敏感之国的敏感酱","isLogin":true,"level":3,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":-404,"message":"地球上找不到该内容哦 (╥﹏╥)"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by peter17ji** [comment]
版本 62.0.3202.89，中国大陆访问

**Comment by ipcjs** [comment]
你先看下这个选项的说明呀
