### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by tyq0330** [ipcjs/bilibili-helper#620]
脚本问题：@ipcjs

## 描述
debug: [解除B站区域限制 v7.9.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep317607?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.42
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=180259765&qn=116&type=&otype=json&fourk=1&bvid=BV1JV411Z7pY&ep_id=317607&fnver=0&fnval=16&session=7c0b4682104c73430d6870bc869f00a4&module=pgc
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=180259765&otype=json&ts=1588207117&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9a72e7b5a950f5317d4143747825c631&qn=116&sign=8e7d6e7e71b3d184472414393c4cfee9","loginStatus":{"isLogin":true,"uname":"Abct","mid":1563159,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=180259765&otype=json&ts=1588207117&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9a72e7b5a950f5317d4143747825c631&qn=116&sign=8e7d6e7e71b3d184472414393c4cfee9\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Abct\",\"mid\":1563159,\"level\":0,\"vip_expire\":0}}","code":-502}
debug: /x/web-interface/nav {"uname":"Abct","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"Abct","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=180259765&bvid=BV1JV411Z7pY&qn=116&type=&otype=json&ep_id=317607&fourk=1&fnver=0&fnval=16&session=16c06d48490d06d8c20518ee321a0fc3&module=pgc&balh_ajax=1
error: {"code":-502,"message":"无法连接到playurl","api":"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=180259765&otype=json&ts=1588207119&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9a72e7b5a950f5317d4143747825c631&qn=116&sign=574210e1361959f80016f3d5c180f66f","loginStatus":{"isLogin":true,"uname":"Abct","mid":1563159,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-502,\"message\":\"无法连接到playurl\",\"api\":\"http://api.bilibili.com/pgc/player/web/playurl?appkey=84956560bc028eb7&type=flv&cid=180259765&otype=json&ts=1588207119&build=12450&platform=pc&fnver=0&fnval=16&fourk=1&access_key=9a72e7b5a950f5317d4143747825c631&qn=116&sign=574210e1361959f80016f3d5c180f66f\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"Abct\",\"mid\":1563159,\"level\":0,\"vip_expire\":0}}","code":-502}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36

- 问题网址：https://www.bilibili.com/bangumi/play/ss33290/?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.4

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：美国

**Comment by rsw510670993** [comment]
同样的问题我看都刷了将近20个issue了，我也一样的报错
看着像是代理服务器被block了？

**Comment by ruixuanw** [comment]
> 同样的问题我看都刷了将近20个issue了，我也一样的报错
> 看着像是代理服务器被block了？

感觉是的哔哩哔哩UWP也不能用了

**Comment by Colorfulnia** [comment]
设置成第三个代理可以用，但是该如何授权大会员啊

**Comment by Colorfulnia** [comment]
> 设置成第三个代理可以用，但是该如何授权大会员啊

好吧，我知道如何授权了，你们可以改成第三个试试

**Comment by rsw510670993** [comment]
> > 设置成第三个代理可以用，但是该如何授权大会员啊
> 
> 好吧，我知道如何授权了，你们可以改成第三个试试

感谢，我这边生效了
自定义居然什么都不填就生效了……

**Comment by wzhishen** [comment]
> > > 设置成第三个代理可以用，但是该如何授权大会员啊
> > 
> > 
> > 好吧，我知道如何授权了，你们可以改成第三个试试
> 
> 感谢，我这边生效了
> 自定义居然什么都不填就生效了……

是吗？为啥我的不行……

**Comment by rsw510670993** [comment]
> 是吗？为啥我的不行……

本质还是换了个代理，可能和地区网络有关系
另外我之前参照[#580](https://github.com/ipcjs/bilibili-helper/issues/580)的答复把chrome://flags/#same-site-by-default-cookies改成disabled了，可以参考一下

**Comment by LvTianYi431** [comment]
我
现在是要会员的看不了不要会员的可以看

**Comment by rrrrin** [comment]
是大会员账号，但改成第三个代理还是看不了大会员

**Comment by HCrSn** [comment]
> > 设置成第三个代理可以用，但是该如何授权大会员啊
> 
> 好吧，我知道如何授权了，你们可以改成第三个试试

怎么授权啊，我点授权弹出的是肥肠抱歉

**Comment by rsw510670993** [comment]
> 怎么授权啊，我点授权弹出的是肥肠抱歉

报错时能进设置页面，下面有个账号授权按钮，点一下就好
如果还不行可以试试清下cookie重新登录

**Comment by rsw510670993** [comment]
嗯……
确实会员番剧又看不了了…… 
只能先用梯子了

**Comment by ipcjs** [comment]
> 设置成第三个代理可以用，但是该如何授权大会员啊

设成第三个，但是不填内容的话，我记得是会回退到使用kghost的服务器，它是不支持登录的🤔

**Comment by rsw510670993** [comment]
> > 设置成第三个代理可以用，但是该如何授权大会员啊
> 
> 设成第三个，但是不填内容的话，我记得是会回退到使用kghost的服务器，它是不支持登录的🤔

嗯，确实是在用kghost
不过其余的都502啊😂

**Comment by rsw510670993** [comment]
感谢对应
我这边恢复正常了

**Comment by Colorfulnia** [comment]
肥肠感谢

**Comment by gnosisyuw** [comment]
这又是chrome的问题。换成firefox就没这个问题。
