### ISSUE TITLE
请问“替换视频服务器”功能还有效吗？

### ISSUE THREAD

**Issue by cherinyy** [ipcjs/bilibili-helper#630]
一开始确实是变成了替换后的源，但在请求了一次 `https://api.yfscdn.net/v1/node/get_nodes` 后
我发现视频数据的服务器变成了 `https://f8lsss1.yfcalc.com:54909/upos-dash-mirrorks3u.bilivideo.com`

用于普通视频页面 1080P60 https://www.bilibili.com/video/BV1NQ4y1P73V

**Comment by zzc10086** [comment]
这个好像是p2p加速来着

**Comment by cherinyy** [comment]
> 这个好像是p2p加速来着

哦豁，我第一次听说 B 站有 P2P，不过我也没有注意上行带宽……

**Comment by zzc10086** [comment]
估计最近加上的,在浏览器的window对象下有个window.__DASH_P2P_TYPE__属性,设置的yf-eg之类的值,会加载一个pcdn脚本,里面有yfcalc.com:54909....字样.不清楚这个p2p吸得哪的血ㄟ( ▔, ▔ )ㄏ

**Comment by cherinyy** [comment]
由于 PCDN 并没有大规模使用，所以目前来说“替换功能”还是可用的，故关闭此 issue。

**Comment by zhengfan2014** [comment]
> 估计最近加上的,在浏览器的window对象下有个window.__DASH_P2P_TYPE__属性,设置的yf-eg之类的值,会加载一个pcdn脚本,里面有yfcalc.com:54909....字样.不清楚这个p2p吸得哪的血ㄟ( ▔, ▔ )ㄏ

据我所知，京东云无线宝路由器运行的云帆加速的pcdn
