### ISSUE TITLE
这个脚本有没有安全性问题，会不会盗号啊？提示什么授权然后异地登录了

### ISSUE THREAD

**Issue by 1265578519** [ipcjs/bilibili-helper#631]
![1](https://user-images.githubusercontent.com/6442439/83796592-d7612680-a6d3-11ea-9b69-ce4bd3599d8e.png)

**Comment by ChuangSheep** [comment]
代码都在这儿，如果真的不放心不妨自己去读一读代码，真的发现安全性问题的话直接指出，也算是造福众生。
如果还没读过的话，那是不是没有必要直接说别人`偷密码` ??

或者说，直接以`为什么使用脚本后提示异地登陆`作为issue标题是不是更中性一点?

**Comment by sileence114** [comment]
你授权了 就要用你的SESSION ID去墙外的服务器上拉视频啊……
那B站服务器看到你的SESSION ID到了墙外登陆了 还不报异地登录么？

**Comment by Alphayellowcat** [comment]
好奇机制原因---我这没这种情况啊。是不是用了“授权永封大会员”之类的功能

**Comment by infinitysky** [comment]
机制上拿到到是你的session ID， 跟密码有个锤子的关系
这代码不读起手就一套扣帽子的操作，像极了某些PXJ
