### ISSUE TITLE
大会员专享失效

### ISSUE THREAD

**Issue by AmyRose1288** [ipcjs/bilibili-helper#632]
脚本问题：@ipcjs

## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-10403,\"message\":\"大会员专享限制\",\"loginStatus\":{\"isLogin\":false}}","code":-10403}

可以考虑进行如下尝试:
1. 多刷新几下页面
2. 进入设置页面更换代理服务器
3. 耐心等待代理服务器端修复问题

点击账号授权后如下：

嗯… 无法访问此页面找不到 link.acg.tv 的服务器 IP 地址。
在 Web 中搜索 link.acg.tv
ERR_NAME_NOT_RESOLVED

- 问题网址：

https://www.bilibili.com/bangumi/play/ep318032

## 日志

debug: [解除B站区域限制 v7.9.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep318032
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=200021199&qn=0&type=&otype=json&fourk=1&bvid=BV1TA411B7AG&ep_id=318032&fnver=0&fnval=16&session=906aa3bc9ffbce71230832c5813d4c26&module=pgc
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
error: {"code":-10403,"message":"大会员专享限制","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-10403,\"message\":\"大会员专享限制\",\"loginStatus\":{\"isLogin\":false}}","code":-10403}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=200021199&bvid=BV1TA411B7AG&qn=0&type=&otype=json&ep_id=318032&fourk=1&fnver=0&fnval=16&session=e5ac63fe40f07cc8abb2e69e812bb4cf&module=pgc&balh_ajax=1
debug: /x/web-interface/nav {"uname":"猫屋敷メア","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
error: {"code":-10403,"message":"大会员专享限制","loginStatus":{"isLogin":false}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-10403,\"message\":\"大会员专享限制\",\"loginStatus\":{\"isLogin\":false}}","code":-10403}
debug: /x/web-interface/nav {"uname":"猫屋敷メア","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 Edge/83.0.478.45

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Edge/83.0.478.45 (Chromium Based)
2. 国家/地区：中国 - 北京 - 海淀区

**Comment by RinshannKaihou** [comment]
+1  一模一样的问题

**Comment by Seekerzero** [comment]
+1

**Comment by Lostpart** [comment]
+1

**Comment by Edward-Y** [comment]
同，Firefox和Chrome都不行

**Comment by wli189** [comment]
同样的问题，看不了会员专享

**Comment by ydeng19** [comment]
ca, Xu yi 把acg.tv线拔了？

**Comment by indefined** [comment]
授权接口挂掉了，B站直接关掉了反馈论坛，甚至都不想解决用户反馈了……从mcbbs看，这波B站应该是把所有第三方授权接口全关了，看来这条路也死了……
另外请教一下 @ipcjs @esterTion , #308 里的 `sign` 是怎么计算出来的……我记得之前从这里偷代码的时候是用 `util_generate_sign` 计算出来的啊（换了对应的盐），现在算不出之前的结果，想测一些网址都测不了……

**Comment by esterTion** [comment]
```
md5(api=<endpoint><appsecret>)

md5(api=http://link.acg.tv/forum.phpc2ed53a74eeefe3cf99fbd01d8c9c375)
=> 67ec798004373253d60114caaad89a8c
```

只有这个地方不是标准sign，很诡异
注意不要urlencode

**Comment by esterTion** [comment]
hmmm，其实接口还能工作，只是dns错误的时候没法获取到跳转后的地址
GM_xhr也没法选择不跟随跳转
唯一的绕路是让人自己复制跳转页面的地址填进去了

等什么时候授权直接关了就只能密码登录了

mcbbs登录早都关了，那次改绕路的时候就是只有这一个域名可以通过接口，其他都返回的无效域名

**Comment by indefined** [comment]
> hmmm，其实接口还能工作，只是dns错误的时候没法获取到跳转后的地址
> GM_xhr也没法选择不跟随跳转
> 唯一的绕路是让人自己复制跳转页面的地址填进去了
> 
> 等什么时候授权直接关了就只能密码登录了
> 
> mcbbs登录早都关了，那次改绕路的时候就是只有这一个域名可以通过接口，其他都返回的无效域名

应该说B站只是关了用户反馈论坛没有关接口吧，所以实际只是因为论坛无法打开导致脚本无法获取到最终地址，授权接口还是能用的。

让人自己输入最终转跳地址似乎也是个方法，但是我刚测了mcbbs的域名竟然是有效的就很迷了，把授权地址改成
```
https://passport.bilibili.com/login/app/third?appkey=27eb53fc9058f8c3&api=https%3A%2F%2Fwww.mcbbs.net%2Fbilibili_connect.php&sign=78d0f6a90a58e7dc5198f05dc481c06f
```
换一下域名匹配其它都和以前一样用，虽然最终并没有办法真正成功登陆mcbbs，不过这并不影响脚本获取需要的东西……
mcbbs是今年4月发的公告表示B站的登录接口要关的，可能他们用的并不是同一个授权接口

**Comment by esterTion** [comment]
发现mcbbs那边还有按钮（怪了，我记得去年白名单的时候没按钮的）
然后确实不是同一个接口，那边用的是oauth，拿到的是code要服务器拿去换access。这里用的直接是third（啥逼名字），过完直接拿到access

`https://passport.bilibili.com/register/oauth.html`和`https://passport.bilibili.com/register/third.html`

---
翻腾我史前申请的appkey授权链接，这货居然还是那个方框绿链接的界面！？
https://account.bilibili.com/login?api=http%3A%2F%2Fi.lcz970.xyz%2Fapi%2Flogin.php&appkey=9326043312df4201&sign=9a6003097414f1d9de369b8523257f3e

---
啊这，原来现在直接用/login的话不会显示确认了？
