### ISSUE TITLE
谷歌浏览器账号授权失败

### ISSUE THREAD

**Issue by MDkuro** [ipcjs/bilibili-helper#634]
在chrome账号授权的时候会显示无法访问次网站，找不到link.acg.tv的服务器IP地址
但是在firefox就没有问题
![图片](https://user-images.githubusercontent.com/65263888/84528274-54b31980-ad1a-11ea-9729-5903d863e24e.png)

**Comment by Trigon** [comment]
Same Issue

**Comment by yw662** [comment]
但是你确定在ff没问题吗？

**Comment by yw662** [comment]
3905b2a9a988eebdff4dfb6a2b98387c4c1e3021
这个commit应该已经解决了这个问题，更新一下试试。

**Comment by gnosisyuw** [comment]
@yw662 我这边更新了7.9.5版本依旧有这个授权失败的问题。ff和chrome都不行。还请大佬指点迷津。

edit: 我发现ff没更新，更新之后就可以授权了。但是chrome依旧不行。chrome的问题实际上无法登出...系统判断我没有登录。所以无法授权。但是我没法登出又没法登录。

**Comment by lw37** [comment]
完美解决

https://blog.csdn.net/Egg_of_pigeon/article/details/106727038

> @yw662 我这边更新了7.9.5版本依旧有这个授权失败的问题。ff和chrome都不行。还请大佬指点迷津。
> 
> edit: 我发现ff没更新，更新之后就可以授权了。但是chrome依旧不行。chrome的问题实际上无法登出...系统判断我没有登录。所以无法授权。但是我没法登出又没法登录。
