### ISSUE TITLE
适配圈x

### ISSUE THREAD

**Issue by OpenWaygate** [ipcjs/bilibili-helper#635]
如题.

**Comment by ipcjs** [comment]
？啥子

**Comment by OpenWaygate** [comment]
Quantumult X, ios上的科学工具, 可以使用js改写网络请求

**Comment by ipcjs** [comment]
那你可以参照脚本的代码，将请求转发到代理服务器上
https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.user.js#L1842
