### ISSUE TITLE
最近在Safari浏览器中和“bilibili evolved”存在冲突

### ISSUE THREAD

**Issue by GlowsSama** [ipcjs/bilibili-helper#643]
最近才出现的问题
在safari浏览器中会和bilibili evolved冲突   插件随机失效
但在Chrome中无此问题   其他浏览器未测试

已向bilibili evolved反馈

**Comment by cmmdwl** [comment]
不仅仅在safari中冲突，在谷歌浏览器里面也冲突，双开发现弹幕模块无法正常加载视频没有弹幕
