### ISSUE TITLE
代理服务器临时不可用

### ISSUE THREAD

**Issue by dajiangyoude-dev** [ipcjs/bilibili-helper#653]
debug: [解除B站区域限制 v7.9.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss33800?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.56
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=232112815&qn=32&type=&otype=json&fourk=1&bvid=BV1Xa4y177Rf&ep_id=331064&fnver=0&fnval=80&session=5cd23fb74cc43feb451abad6a0be8521&module=pgc&access_key=622f9ce039f7586df198dfed310bb191
debug: /x/web-interface/nav {"uname":"打酱油的小书虫","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"打酱油的小书虫","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=232112815&qn=32&type=&otype=json&fourk=1&bvid=BV1Xa4y177Rf&ep_id=331064&fnver=0&fnval=80&session=5cd23fb74cc43feb451abad6a0be8521&module=bangumi&access_key=622f9ce039f7586df198dfed310bb191
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=232112815&bvid=BV1Xa4y177Rf&qn=32&type=&otype=json&ep_id=331064&fourk=1&fnver=0&fnval=80&session=8fb9b724d19d8f592a7c906391fc9f57&module=pgc&balh_ajax=1&access_key=622f9ce039f7586df198dfed310bb191
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

**Comment by BaksiLi** [comment]
一樣。土豆的代理也不行。

**Comment by Jiaming-Jin** [comment]
一样，服务器测速延时显示3万多ms

**Comment by Alphayellowcat** [comment]
之前bilibiliplus服务器dowm了，现在确认是重启了，API什么的恢复了，又能用了芜湖。
视频提速的方法可以参考这篇文章：https://www.bilibili.com/read/cv3118508/

**Comment by BaksiLi** [comment]
> 之前bilibiliplus服务器dowm了，现在确认是重启了，API什么的恢复了，又能用了芜湖。
> 视频提速的方法可以参考这篇文章：https://www.bilibili.com/read/cv3118508/

最近還是偶爾抽風，在 BiliPlus 管網上看，是因爲有人舉報所以服務暫停了。

這條 Issue 估計可以關了。
