### ISSUE TITLE
## 拉取视频地址失败  原因: 代理服务器临时不可用 

### ISSUE THREAD

**Issue by syr-123** [ipcjs/bilibili-helper#654]
坐标日本。大概北京时间2020年9月15日19点30分发现开始有问题，本来还看的好好的，突然点下一集的时候显示拉取视频失败，换了代理服务器也不行，而且账号授权响应时间太长跳转不了。

日志如下：

debug: [解除B站区域限制 v7.9.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss26307?t=1264
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=77404115&qn=80&type=&otype=json&fourk=1&bvid=BV1nb411Y79p&ep_id=259872&fnver=0&fnval=80&session=f0c46e83f58fa5e9a03733079421fd86&module=pgc&access_key=a55bfdbbed66da1ef9f4740c72124591
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=77404115&qn=80&type=&otype=json&fourk=1&bvid=BV1nb411Y79p&ep_id=259872&fnver=0&fnval=80&session=f0c46e83f58fa5e9a03733079421fd86&module=bangumi&access_key=a55bfdbbed66da1ef9f4740c72124591
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=undefined&cid=77404115&bvid=BV1nb411Y79p&qn=80&type=&otype=json&ep_id=259872&fourk=1&fnver=0&fnval=80&session=d6fe911d0a777d2f591825423610413b&module=pgc&balh_ajax=1&access_key=a55bfdbbed66da1ef9f4740c72124591
debug: balh_server_inner  =>  https://www.biliplus.com
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=77404115&bvid=BV1nb411Y79p&qn=80&type=&otype=json&ep_id=259872&fourk=1&fnver=0&fnval=80&session=d6fe911d0a777d2f591825423610413b&module=bangumi&balh_ajax=1&access_key=3ade7dfa5f45b4c4361827ca3bd9ce91
info: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36

## 其他

1. 浏览器版本：Chorme 最新版
2. 国家/地区：日本

**Comment by pakasas** [comment]
同在日本，服务器临时不可用

debug: [解除B站区域限制 v7.9.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep259771
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=72227438&qn=116&type=&otype=json&fourk=1&bvid=BV1at411a7LR&ep_id=259771&fnver=0&fnval=80&session=ef9759d338972e70d5b8d13f16252c9b&module=pgc&access_key=97c726c4a169cb29290cf33a8c710891
debug: /x/web-interface/nav {"uname":"Pakasas","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=72227438&qn=116&type=&otype=json&fourk=1&bvid=BV1at411a7LR&ep_id=259771&fnver=0&fnval=80&session=ef9759d338972e70d5b8d13f16252c9b&module=bangumi&access_key=97c726c4a169cb29290cf33a8c710891
debug: /x/web-interface/nav {"uname":"Pakasas","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=72227438&bvid=BV1at411a7LR&qn=116&type=&otype=json&ep_id=259771&fourk=1&fnver=0&fnval=80&session=b26258457b714534ded05d18d1f493ea&module=pgc&balh_ajax=1&access_key=97c726c4a169cb29290cf33a8c710891
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=72227438&bvid=BV1at411a7LR&qn=116&type=&otype=json&ep_id=259771&fourk=1&fnver=0&fnval=80&session=b26258457b714534ded05d18d1f493ea&module=bangumi&balh_ajax=1&access_key=97c726c4a169cb29290cf33a8c710891
info: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by ZSunEPS** [comment]
坐标美国，拉取视频地址失败，原因: 代理服务器临时不可用

debug: [解除B站区域限制 v7.9.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep317868
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: kodou flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=235658417&qn=116&type=&otype=json&fourk=1&bvid=BV1dz4y1o74p&ep_id=317868&fnver=0&fnval=80&session=5d3ad62c4c8b7d98741c5fc349f54bf8&module=pgc&access_key=b49d735a8b16f903445c54605e40a291
debug: /x/web-interface/nav {"uname":"楠濑-诺艾尔","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"楠濑-诺艾尔","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
debug:   =>  ks3u
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=175236472&qn=116&type=&otype=json&fourk=1&bvid=BV1F54y197qq&ep_id=317858&fnver=0&fnval=80&session=ff8d87dc3675f68475f59f34eff8ab4a&module=pgc&access_key=b49d735a8b16f903445c54605e40a291
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=235658417&bvid=BV1dz4y1o74p&qn=116&type=&otype=json&ep_id=317868&fourk=1&fnver=0&fnval=80&session=adda55967c1bcdef9028221903cd3f3d&module=pgc&balh_ajax=1&access_key=b49d735a8b16f903445c54605e40a291
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=235658417&qn=116&type=&otype=json&fourk=1&bvid=BV1dz4y1o74p&ep_id=317868&fnver=0&fnval=80&session=5d3ad62c4c8b7d98741c5fc349f54bf8&module=bangumi&access_key=b49d735a8b16f903445c54605e40a291
info: player msg: 代理服务器临时不可用
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=175236472&qn=116&type=&otype=json&fourk=1&bvid=BV1F54y197qq&ep_id=317858&fnver=0&fnval=80&session=ff8d87dc3675f68475f59f34eff8ab4a&module=bangumi&access_key=b49d735a8b16f903445c54605e40a291
info: player msg: 代理服务器临时不可用
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=175236472&bvid=BV1F54y197qq&qn=116&type=&otype=json&ep_id=317858&fourk=1&fnver=0&fnval=80&session=373bd5b7b9fd67e83ca0196159b2b331&module=pgc&balh_ajax=1&access_key=b49d735a8b16f903445c54605e40a291
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=235658417&bvid=BV1dz4y1o74p&qn=116&type=&otype=json&ep_id=317868&fourk=1&fnver=0&fnval=80&session=adda55967c1bcdef9028221903cd3f3d&module=bangumi&balh_ajax=1&access_key=b49d735a8b16f903445c54605e40a291
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=175236472&bvid=BV1F54y197qq&qn=116&type=&otype=json&ep_id=317858&fourk=1&fnver=0&fnval=80&session=373bd5b7b9fd67e83ca0196159b2b331&module=bangumi&balh_ajax=1&access_key=b49d735a8b16f903445c54605e40a291
info: player msg: 代理服务器临时不可用
info: player msg: 代理服务器临时不可用

**Comment by wingdawn7551** [comment]
坐标美国，也是同样的问题，代理服务器临时不可用而且无法重新授权，更改代理服务器也没用，且biliplus无法访问，用的一直是Google Chrome浏览器
日志如下：
debug: [解除B站区域限制 v7.9.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep336156?from=search&seid=1862518917992761907
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 7
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=228684032&qn=32&type=&otype=json&fourk=1&bvid=BV1St4y1U71p&ep_id=336156&fnver=0&fnval=80&session=69e21699b3d6e6d2d5ba6dcfa68d0fd8&module=pgc&access_key=9b8e1a4eed311dc79a04c5158e682d71
debug: /x/web-interface/nav {"uname":"奇妙爱丽丝","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"奇妙爱丽丝","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=228684032&qn=32&type=&otype=json&fourk=1&bvid=BV1St4y1U71p&ep_id=336156&fnver=0&fnval=80&session=69e21699b3d6e6d2d5ba6dcfa68d0fd8&module=bangumi&access_key=9b8e1a4eed311dc79a04c5158e682d71
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 7
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=undefined&cid=228684032&bvid=BV1St4y1U71p&qn=32&type=&otype=json&ep_id=336156&fourk=1&fnver=0&fnval=80&session=d9bb7bd76469f3ccee4274b756abf273&module=pgc&balh_ajax=1&access_key=9b8e1a4eed311dc79a04c5158e682d71
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=228684032&bvid=BV1St4y1U71p&qn=32&type=&otype=json&ep_id=336156&fourk=1&fnver=0&fnval=80&session=d9bb7bd76469f3ccee4274b756abf273&module=bangumi&balh_ajax=1&access_key=9b8e1a4eed311dc79a04c5158e682d71
info: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

**Comment by yujincheng08** [comment]
Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

服务器已经恢复，大家可以切换回去啦

**Comment by syr-123** [comment]
> Biliplus要挂到20号。所以我临时建了个服务器。更新最新脚本，然后填自定义服务器`bili.lovesykun.cn`

谢谢！！啊不过我刚刚试了下我这还是不行orz

**Comment by yujincheng08** [comment]
@syr-123 要最新版，https://github.com/ipcjs/bilibili-helper/commit/8c064faeaab348b40513152c0cd9d19fd1052d44 这个commit以后

**Comment by marco8885200** [comment]
> @syr-123 要最新版，[8c064fa](https://github.com/ipcjs/bilibili-helper/commit/8c064faeaab348b40513152c0cd9d19fd1052d44) 这个commit以后

我是最新版，但还是不行

**Comment by syr-123** [comment]
> @syr-123 要最新版，[8c064fa](https://github.com/ipcjs/bilibili-helper/commit/8c064faeaab348b40513152c0cd9d19fd1052d44) 这个commit以后

最新版是指的是这个解除地域限制脚本的最新版么，我点更新说已经是没有更新了,,,,

**Comment by yujincheng08** [comment]
@marco8885200  @syr-123  我这个是只能看大陆番剧的，我超炮T测了一下没问题

**Comment by syr-123** [comment]
> @marco8885200 @syr-123 我这个是只能看大陆番剧的，我超炮T测了一下没问题

诶我试了下超炮T也打不开.....

**Comment by yujincheng08** [comment]
@syr-123 建议重新安装一下脚本。我感觉好像还在用旧的。。

**Comment by syr-123** [comment]
> @syr-123 建议重新安装一下脚本。我感觉好像还在用旧的。。

谢谢！！可能真的是这个问题，现在好了！！
另外再问一下，这个代理服务器设置还可以在哪里改？每次只有出问题跳出来框了能点那个设置...

**Comment by yujincheng08** [comment]
@syr-123 页面下拉，右下角会出现几个悬浮图标，最后一个土星图标就是脚本设置。
![20200916183222](https://user-images.githubusercontent.com/5022927/93326249-16625480-f84b-11ea-867d-f65728593d5d.png)

**Comment by syr-123** [comment]
> @syr-123 页面下拉，右下角会出现几个悬浮图标，最后一个土星图标就是脚本设置。
> ![20200916183222](https://user-images.githubusercontent.com/5022927/93326249-16625480-f84b-11ea-867d-f65728593d5d.png)

啊原来一直说的土星就是这个！！ orz 才知道....非常感谢！！是不是等20号biliplus那边好了就能换回去了

**Comment by yujincheng08** [comment]
@syr-123 biliplus好了我就把服务器关掉:smile: 到时候你就知道要换回来了

**Comment by syr-123** [comment]
> @syr-123 biliplus好了我就把服务器关掉 到时候你就知道要换回来了

2333明白了！！不好意思问了好多orz

**Comment by rexfanyc** [comment]
@yujincheng08 我这里似乎还是不行，显示

> 尝试使用kghost的服务器拉取视频地址...
代理服务器临时不可用

**Comment by syr-123** [comment]
> @yujincheng08 我这里似乎还是不行，显示
> 
> > 尝试使用kghost的服务器拉取视频地址...
> > 代理服务器临时不可用

我是把脚本删了重新下载装了。你看一下，脚本版本是不是7.9.5的，然后再输入自定义代理服务器

**Comment by yujincheng08** [comment]
@rexfanyc 你是在香港？我怀疑你也没更新。尝试点那个油猴页面的reinstall

**Comment by rexfanyc** [comment]
> @rexfanyc 你是在香港？我怀疑你也没更新。尝试点那个油猴页面的reinstall

我在欧洲，完整的前面还有一条 从自定义服务器拉取视频地址中...
已经更新到 8c064fa 之后的了

刚刚更新到 7.9.6 但问题还在

**Comment by rexfanyc** [comment]
> > @yujincheng08 我这里似乎还是不行，显示
> > > 尝试使用kghost的服务器拉取视频地址...
> > > 代理服务器临时不可用
> 
> 我是把脚本删了重新下载装了。你看一下，脚本版本是不是7.9.5的，然后再输入自定义代理服务器

7.9.6了似乎还不行
重新安装了一遍不过貌似设置保留着不需要重新输入自定义代理服务器，会不会是这里的问题

**Comment by delyskelton** [comment]
> > > @yujincheng08 我这里似乎还是不行，显示
> > > > 尝试使用kghost的服务器拉取视频地址...
> > > > 代理服务器临时不可用
> > 
> > 
> > 我是把脚本删了重新下载装了。你看一下，脚本版本是不是7.9.5的，然后再输入自定义代理服务器
> 
> 7.9.6了似乎还不行
> 重新安装了一遍不过貌似设置保留着不需要重新输入自定义代理服务器，会不会是这里的问题

你是不是在自定义那里没有输入https://的前缀

**Comment by Milled** [comment]
> > > > @yujincheng08 我这里似乎还是不行，显示
> > > > > 尝试使用kghost的服务器拉取视频地址...
> > > > > 代理服务器临时不可用
> > > 
> > > 
> > > 我是把脚本删了重新下载装了。你看一下，脚本版本是不是7.9.5的，然后再输入自定义代理服务器
> > 
> > 
> > 7.9.6了似乎还不行
> > 重新安装了一遍不过貌似设置保留着不需要重新输入自定义代理服务器，会不会是这里的问题
> 
> 你是不是在自定义那里没有输入[https://的前缀](https://%E7%9A%84%E5%89%8D%E7%BC%80)

正解👍

**Comment by rexfanyc** [comment]
> > > > @yujincheng08 我这里似乎还是不行，显示
> > > > > 尝试使用kghost的服务器拉取视频地址...
> > > > > 代理服务器临时不可用
> > > 
> > > 
> > > 我是把脚本删了重新下载装了。你看一下，脚本版本是不是7.9.5的，然后再输入自定义代理服务器
> > 
> > 
> > 7.9.6了似乎还不行
> > 重新安装了一遍不过貌似设置保留着不需要重新输入自定义代理服务器，会不会是这里的问题
> 
> 你是不是在自定义那里没有输入[https://的前缀](https://%E7%9A%84%E5%89%8D%E7%BC%80)

的确是这个问题
解决了多谢，也谢谢 @yujincheng08 @syr-123

**Comment by yujincheng08** [comment]
原来要输入https的吗，我自己都也不知道😱

好了上面评论改好了（

**Comment by Kayuun** [comment]
感谢作者
之前也有一次这样的情况
我是用B站 UWP 客户端 看的……
没想到那个 海外勾选 还真有用……

**Comment by yujincheng08** [comment]
@Kayuun 现在UWP已经不行了吧

懂了，那个第三方UWP对吧，那个也是用Biliplus的。

**Comment by windload89** [comment]
我想请问 哪里可以捐些钱给创作者？alipay我不能用，还有伺服器 也是 作者做的吗？

**Comment by Kayuun** [comment]
用来看国内版权视频还行…… 而且官方UWP也一直更新……

LoveSy <notifications@github.com> 于2020年9月16日周三 下午10:04写道：

**Comment by yujincheng08** [comment]
@Kayuun 问题是biliplus挂了他也跟着挂的

**Comment by realJuliaZ** [comment]
坐标美国
按照前面的小伙伴的说法，我试了更新脚本，然后尝试了重新进行账号授权，得到以下页面：
![image](https://user-images.githubusercontent.com/30909579/93363964-f82e3180-f815-11ea-9530-cde55a4f562d.png)

连续几天不能用是因为这个原因吗？
附上日志：
debug: [解除B站区域限制 v7.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep317807
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: /pgc/player/web/playurl?cid=235411147&qn=0&type=&otype=json&fourk=1&bvid=BV1ok4y1y7Cx&ep_id=317807&fnver=0&fnval=80&session=1287ea9cfb322a95f0d939995d2aaddf&module=bangumi&access_key=4f47ad38e263735b61b7239101e36891
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=235411147&qn=0&type=&otype=json&fourk=1&bvid=BV1ok4y1y7Cx&ep_id=317807&fnver=0&fnval=80&session=1287ea9cfb322a95f0d939995d2aaddf&module=bangumi&access_key=4f47ad38e263735b61b7239101e36891
debug: /x/web-interface/nav {"uname":"JeBoome","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"JeBoome","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: ajax: /pgc/player/web/playurl?avid=undefined&cid=235411147&bvid=BV1ok4y1y7Cx&qn=0&type=&otype=json&ep_id=317807&fourk=1&fnver=0&fnval=80&session=27fa1bb1ae4fd18df3c0234fc9d3e484&module=bangumi&balh_ajax=1&access_key=4f47ad38e263735b61b7239101e36891
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=235411147&bvid=BV1ok4y1y7Cx&qn=0&type=&otype=json&ep_id=317807&fourk=1&fnver=0&fnval=80&session=27fa1bb1ae4fd18df3c0234fc9d3e484&module=bangumi&balh_ajax=1&access_key=4f47ad38e263735b61b7239101e36891
info: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by yujincheng08** [comment]
@realJuliaZ 那个没通网不影响授权成功

**Comment by realJuliaZ** [comment]
> @realJuliaZ 那个没通网不影响授权成功

依然是
“## 拉取视频地址失败
原因: 代理服务器临时不可用”



> Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

改了这个好像可以了！感谢！

**Comment by Kayuun** [comment]
您说的那个 名字是 “哔哩哔哩动画UWP”吧…… 我说的是官方研发的那个……

LoveSy <notifications@github.com> 于2020年9月17日周四 上午1:07写道：

**Comment by cjy543731778** [comment]
> Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

感谢巨佬的无私奉献。

**Comment by Kashionz** [comment]
> Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

換了您的服務器就可以了，非常感謝！！

**Comment by Decol-24** [comment]
> Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

非常感谢巨佬的无私

**Comment by gpgg** [comment]
> Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

感谢！

**Comment by ShooterMiku** [comment]
> Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

大佬 方便简单给一个教程吗 我以后想在自己的vps顺便也做一个

**Comment by yujincheng08** [comment]
@ShooterMiku
Nginx配置
```
server
{
    server_name bili.example.com;    # 这里换成自己的服务器域名

    listen 443 ssl http2; # managed by Certbot 注意使用ssl

    client_max_body_size 128M;

    location / {
       return 403;
    }

    location /pgc/player/web/playurl {
      proxy_pass https://api.bilibili.com;
    }
    # ssl证书配置。具体课看acme.sh
    ssl_certificate /etc/nginx/ssl/example.com/full.pem;
    ssl_certificate_key /etc/nginx/ssl/example.com/key.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_ecdh_curve prime256v1;
}
```

**Comment by yuureijinkou** [comment]
> @ShooterMiku
> Nginx配置
> 
> ```
> server
> {
>     server_name bili.example.com;    # 这里换成自己的服务器域名
> 
>     listen 443 ssl http2; # managed by Certbot 注意使用ssl
> 
>     client_max_body_size 128M;
> 
>     location / {
>        return 403;
>     }
> 
>     location /pgc/player/web/playurl {
>       proxy_pass https://api.bilibili.com;
>     }
>     # ssl证书配置。具体课看acme.sh
>     ssl_certificate /etc/nginx/ssl/example.com/full.pem;
>     ssl_certificate_key /etc/nginx/ssl/example.com/key.pem;
>     ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
>     ssl_ciphers         HIGH:!aNULL:!MD5;
>     ssl_ecdh_curve prime256v1;
> }
> ```



> Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`
> 
> 服务器已经恢复，大家可以切换回去啦

大佬，坐标日本。biliplus也没恢复，大佬的地址也失效了。。怎么办

**Comment by yujincheng08** [comment]
@yuureijinkou 恢复了啊：https://www.biliplus.com/

**Comment by yuureijinkou** [comment]
> @yuureijinkou 恢复了啊：https://www.biliplus.com/

是的，我能点开了，但是不知道为何，我在b站拉取视频还是失败

**Comment by yujincheng08** [comment]
@yuureijinkou 我的锅我的锅，已经提交PR了 #668

**Comment by yuureijinkou** [comment]
> @yuureijinkou 我的锅我的锅，已经提交PR了 #668

感谢大佬
