### ISSUE TITLE
代理服务器临时不可用

### ISSUE THREAD

**Issue by Haku247** [ipcjs/bilibili-helper#655]
## 描述

坐标日本 于2020/09/15 20：05发现
## 拉取视频地址失败
原因：代理服务器临时不可用

并且biliplus官网同样处于无法访问的状态

## 日志

<details>
<summary>Verbose 日志</summary>

debug: [解除B站区域限制 v7.9.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep260612?from=search&seid=2154088259242874525
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?cid=72836762&qn=112&type=&otype=json&fourk=1&bvid=BV14t411p7xT&ep_id=260612&fnver=0&fnval=80&session=80e5ebb7179446b5ec8f3ef92d6a224a&module=pgc&access_key=cefdffb694b0f77690253fa5b2ec4d91
debug: /x/web-interface/nav {"uname":"星光熠熠Astral","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"星光熠熠Astral","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=72836762&qn=112&type=&otype=json&fourk=1&bvid=BV14t411p7xT&ep_id=260612&fnver=0&fnval=80&session=80e5ebb7179446b5ec8f3ef92d6a224a&module=bangumi&access_key=cefdffb694b0f77690253fa5b2ec4d91
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=undefined&cid=72836762&bvid=BV14t411p7xT&qn=112&type=&otype=json&ep_id=260612&fourk=1&fnver=0&fnval=80&session=610685ea94f03d6b32807c9836abbd5f&module=pgc&balh_ajax=1&access_key=cefdffb694b0f77690253fa5b2ec4d91
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=72836762&bvid=BV14t411p7xT&qn=112&type=&otype=json&ep_id=260612&fourk=1&fnver=0&fnval=80&session=610685ea94f03d6b32807c9836abbd5f&module=bangumi&balh_ajax=1&access_key=cefdffb694b0f77690253fa5b2ec4d91
info: player msg: 代理服务器临时不可用
debug: balh_server_inner  =>  __custom__
debug: balh_server_inner  =>  https://biliplus.ipcjs.top
debug: balh_server_inner  =>  https://www.biliplus.com
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
 
</details>

## 其他

1. 浏览器版本：版本 85.0.4183.102（正式版本） （64 位）
2. 国家/地区：日本

**Comment by zxie52** [comment]
同样的问题， 坐标美国

问题： 代理服务器临时不可用

同时biliplus的官网也无法登录。问题已经断断续续几天了。

debug: [解除B站区域限制 v7.9.5 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep317807
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=235411147&qn=64&type=&otype=json&fourk=1&bvid=BV1ok4y1y7Cx&ep_id=317807&fnver=0&fnval=80&session=3d5883cf2c06a4766704fbbe3a871fa8&module=pgc&access_key=16d291ff6db1b02774983f39c6480e91
debug: /x/web-interface/nav {"uname":"***","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"***","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=235411147&qn=64&type=&otype=json&fourk=1&bvid=BV1ok4y1y7Cx&ep_id=317807&fnver=0&fnval=80&session=3d5883cf2c06a4766704fbbe3a871fa8&module=bangumi&access_key=16d291ff6db1b02774983f39c6480e91
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=235411147&bvid=BV1ok4y1y7Cx&qn=64&type=&otype=json&ep_id=317807&fourk=1&fnver=0&fnval=80&session=a1cba52c2dcf6564a30f90a7c80a0360&module=pgc&balh_ajax=1&access_key=16d291ff6db1b02774983f39c6480e91
debug: userAgent Mozilla/5.0 (X11; CrOS x86_64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36

**Comment by rickyzhangca** [comment]
![image](https://user-images.githubusercontent.com/16908811/93356523-468b0280-f80d-11ea-96cf-7c224b6b522f.png)
因为 biliplus 炸啦

**Comment by zhenzhongluo** [comment]
## 拉取视频地址失败
原因: {"readyState":4,"responseText":"\n\n\n\n    \n    \n    \n    \n    \n    \n    \n    \n    \n\n\n\n    
\n    
\n        
\n            \n            
\n              返回上一页\n            
\n        
\n        
\n        
\n        
\n        
\n    
\n    \n    \n\n\n\n","status":404,"statusText":"Not Found"}

可以考虑进行如下尝试:
1. 多刷新几下页面
2. 进入设置页面更换代理服务器
3. 耐心等待代理服务器端修复问题
