### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-10403,"message":"大会员专享限制"}

### ISSUE THREAD

**Issue by CyclonicPinna** [ipcjs/bilibili-helper#658]
Biliplus要挂到20号。所以我临时建了个服务器用来看大陆番剧。更新最新脚本，然后填自定义服务器`https://bili.lovesykun.cn`

_Originally posted by @yujincheng08 in https://github.com/ipcjs/bilibili-helper/issues/654#issuecomment-693251857_

限定大会员的番剧无法播放，非限定的番剧可以播放。
已更新到7.9.6版并填入自定义服务器，刷新后显示：## 拉取视频地址失败
原因: {"code":-10403,"message":"大会员专享限制"}。尝试取消并重新帐号授权，无果。另外帐号授权跳转时页面左上角闪过苦力怕的图标，然后自行关闭，原来似乎没有出现过，不知是否正常。

debug: [解除B站区域限制 v7.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep330757
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: __custom__ upos_server: wcsu flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function (a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function (a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?cid=235513414&qn=32&type=&otype=json&fourk=1&bvid=BV1Ji4y1u74o&ep_id=330757&fnver=0&fnval=80&session=6d8fad2447cf2da956da30b0e04c3a50&module=bangumi
debug: /x/web-interface/nav {"uname":"Sensored","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=235513414&qn=32&type=&otype=json&fourk=1&bvid=BV1Ji4y1u74o&ep_id=330757&fnver=0&fnval=80&session=6d8fad2447cf2da956da30b0e04c3a50&module=bangumi
debug: /x/web-interface/nav {"uname":"Sensored","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function (a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?avid=undefined&cid=235513414&bvid=BV1Ji4y1u74o&qn=32&type=&otype=json&ep_id=330757&fourk=1&fnver=0&fnval=80&session=f42a6a316ff8bdb66694537633642af8&module=bangumi&balh_ajax=1
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=235513414&bvid=BV1Ji4y1u74o&qn=32&type=&otype=json&ep_id=330757&fourk=1&fnver=0&fnval=80&session=f42a6a316ff8bdb66694537633642af8&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by yujincheng08** [comment]
你`access_key`没能正常获得，再授权试试？

**Comment by Alphayellowcat** [comment]
> 你`access_key`没能正常获得，再授权试试？
服务器炸了，API 也炸了

**Comment by yujincheng08** [comment]
@Alphayellowcat 获取`access_key`不需要服务器

**Comment by Alphayellowcat** [comment]
> @Alphayellowcat 获取`access_key`不需要服务器

是的--我傻逼了

**Comment by CyclonicPinna** [comment]
点击授权后显示正在跳转，转到如下页面，闪现苦力怕图标后自动退出：
https://www.mcbbs.net/template/mcbbs/image/special_photo_bg.png?access_key=2afd313feb41e4d4041c3d96e3ab5f91&mid=346550&uname=Sensored&sign=fb9970dbd59ec8d2e21279a92776c284
所以授权页面是MC中文论坛？
另外没更新7.9.6前虽然biliplus挂了，但我一直是保持着帐号授权的，更新后我在没动授权的情况下先试了自定义服务器，直接就出现了上述提示，我才试着重新授权的，结果还是一样。
还有7.9.6的番剧页面跳转功能失效了，显示：error:[object Object]。

**Comment by yujincheng08** [comment]
@CyclonicPinna 没毛病就是这样。另外 https://github.com/ipcjs/bilibili-helper/commit/c617ae1f4aa661014f395421eb1b294260620542 之后才会单独储存`access_key`的，所以之前授权无效也很正常。

**Comment by CyclonicPinna** [comment]
所以显示苦力怕页面到底是授权成功了还是没成功？目前点完以后还是不行。

**Comment by yujincheng08** [comment]
@CyclonicPinna 成功。你可以手动把你上面苦力怕的url中的`access_key`这个param加到主楼的那个`bili.lovesykun.cn`的url里面试试看，是可以成功解析出视频地址的。

**Comment by noow219** [comment]
我大概遇到了类似的问题。chrome和脚本都是最新版本，也授权了。

debug: [解除B站区域限制 v7.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep323067?from=search&seid=15616501258802059743
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: __custom__ upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"伊佐木纱友","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?cid=184438945&qn=80&type=&otype=json&fourk=1&bvid=BV1YK4y1b7nc&ep_id=323067&fnver=0&fnval=80&session=77196c19ebd40312fa30da104e99c916&module=bangumi
debug: /x/web-interface/nav {"uname":"伊佐木纱友","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=184438945&qn=80&type=&otype=json&fourk=1&bvid=BV1YK4y1b7nc&ep_id=323067&fnver=0&fnval=80&session=77196c19ebd40312fa30da104e99c916&module=bangumi
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?avid=undefined&cid=184438945&bvid=BV1YK4y1b7nc&qn=80&type=&otype=json&ep_id=323067&fourk=1&fnver=0&fnval=80&session=2710f0960474872d38afeed893cd6869&module=bangumi&balh_ajax=1
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=184438945&bvid=BV1YK4y1b7nc&qn=80&type=&otype=json&ep_id=323067&fourk=1&fnver=0&fnval=80&session=2710f0960474872d38afeed893cd6869&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by CyclonicPinna** [comment]
> @CyclonicPinna 成功。你可以手动把你上面苦力怕的url中的`access_key`这个param加到主楼的那个`bili.lovesykun.cn`的url里面试试看，是可以成功解析出视频地址的。

貌似是能看到视频地址。但是为什么在番剧页面仍然显示“大会员专享限制”呢？

**Comment by yujincheng08** [comment]
@CyclonicPinna 关键代码在这里
https://github.com/ipcjs/bilibili-helper/blob/1fbd4fb9589e5bff1c4c7eb32951664746ba4300/bilibili_bangumi_area_limit_hack.user.js#L2281-L2283

这里会保存`access_key`到`localStorage`。你应该是这里出了问题。建议看看授权时候console有没有报错，或者`console.log`一下看看这几行代码的结果是不是正常。怀疑是浏览器兼容问题。

**Comment by CyclonicPinna** [comment]
不知道找得对不对，点击授权的时候“const access_key = new URL(url).searchParams.get('access_key');”这一行报错，显示“Uncaught TypeError: Cannot read property 'get' of undefined”。

**Comment by yujincheng08** [comment]
@CyclonicPinna 看来是了。你的浏览器不支持`URL.searchParams`？我看基本所有浏览器都支持的呀：https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams

**Comment by CyclonicPinna** [comment]
好吧，Chrome要51以后才支持么？我是Chrome 49.0.2623.112。话说这样的话楼上 @noow219 用的是Chrome 85.0.4183.102为什么也有问题。另外是授权的代码改了么？因为我之前是正常的。

**Comment by yujincheng08** [comment]
@CyclonicPinna 我才发现你是windows XP。。。。

**Comment by CyclonicPinna** [comment]
是的，老电脑，没法升级了。

**Comment by yujincheng08** [comment]
@CyclonicPinna 你可以先弄个PR吧，把`URL.searchParams`变成字符串用正则`access_key=([0-9a-f]{32})`匹配出来。我没那么极限的环境不敢乱写。。

**Comment by yujincheng08** [comment]
@CyclonicPinna 建议你用360浏览器，这个东西在XP下面还是很厉害的。。。好像把新版Chromium强行移植到XP，兼容了很多XP没有的API。

**Comment by CyclonicPinna** [comment]
惭愧，我不会写代码，所以没法改。先试试浏览器吧，多谢告知。

**Comment by CyclonicPinna** [comment]
“惭愧，我不会写代码，所以没法改。先试试浏览器吧，多谢告知。”

刚刚这么说了之后，想着还不死心，所以试了试直接填access_key的土办法，暂时似乎可以用。不过access_key会过期么？
