### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by Peter20000101** [ipcjs/bilibili-helper#659]
debug: [解除B站区域限制 v7.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep322605
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: /pgc/player/web/playurl?cid=183479783&qn=112&type=&otype=json&fourk=1&bvid=BV1PQ4y1N7V8&ep_id=322605&fnver=0&fnval=80&session=928e2f39b2a0b5c7e4d9c6c45cbe30dd&module=bangumi&access_key=1a6244d3d6359d6e437e56801e880a71
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=183479783&qn=112&type=&otype=json&fourk=1&bvid=BV1PQ4y1N7V8&ep_id=322605&fnver=0&fnval=80&session=928e2f39b2a0b5c7e4d9c6c45cbe30dd&module=bangumi&access_key=1a6244d3d6359d6e437e56801e880a71
debug: /x/web-interface/nav {"uname":"Peter20000101","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"Peter20000101","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 代理服务器临时不可用
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: ajax: /pgc/player/web/playurl?avid=undefined&cid=183479783&bvid=BV1PQ4y1N7V8&qn=112&type=&otype=json&ep_id=322605&fourk=1&fnver=0&fnval=80&session=59af08043eb003f5367123608595d211&module=bangumi&balh_ajax=1&access_key=1a6244d3d6359d6e437e56801e880a71
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=183479783&bvid=BV1PQ4y1N7V8&qn=112&type=&otype=json&ep_id=322605&fourk=1&fnver=0&fnval=80&session=59af08043eb003f5367123608595d211&module=bangumi&balh_ajax=1&access_key=1a6244d3d6359d6e437e56801e880a71
info: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by yujincheng08** [comment]
https://github.com/ipcjs/bilibili-helper/issues/654#issuecomment-693251857
