### ISSUE TITLE
解析视频地址失败，更换服务器也不行

### ISSUE THREAD

**Issue by Peter20000101** [ipcjs/bilibili-helper#666]
脚本问题：@ipcjs

## 描述
解析视频地址失败，现服务器为https://bili.lovesykun.cn，提示说更换回biliplus服务器，但是更换完也不行

- 问题网址：https://www.bilibili.com/bangumi/play/ep322605

## 日志

<details>
<summary>Verbose 日志</summary>

```
debug: [解除B站区域限制 v7.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep322605
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?cid=183479783&qn=112&type=&otype=json&fourk=1&bvid=BV1PQ4y1N7V8&ep_id=322605&fnver=0&fnval=80&session=28b6ac4f5bebf236d7118dedd5a57e73&module=bangumi&access_key=65d8fa95e960d9b4941875e7da165b91
debug: /x/web-interface/nav {"uname":"Peter20000101","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"Peter20000101","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?avid=undefined&cid=183479783&bvid=BV1PQ4y1N7V8&qn=112&type=&otype=json&ep_id=322605&fourk=1&fnver=0&fnval=80&session=595e4c29bb0fb84162d2e1e3ae42ba1a&module=bangumi&balh_ajax=1&access_key=65d8fa95e960d9b4941875e7da165b91
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

```
 
</details>

## 其他

1. 浏览器版本：chrome 版本 85.0.4183.102（正式版本） （64 位）
2. 国家/地区：美国

**Comment by NeutrinoLiu** [comment]
同样问题、。

**Comment by Nicomakii** [comment]
+1

**Comment by wunaicheng** [comment]
+1

**Comment by yuureijinkou** [comment]
+2

debug: [解除B站区域限制 v7.9.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep330489?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.9
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?cid=236686528&qn=0&type=&otype=json&fourk=1&bvid=BV1zz4y1Z7B9&ep_id=330489&fnver=0&fnval=80&session=8b0b4e5730e95488c4c0253a8831dc1e&module=bangumi&access_key=7d680a816add190f0f4992e2c9db8291
debug: /x/web-interface/nav {"uname":"用户名","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"用户名","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: ajax: https://bili.lovesykun.cn/pgc/player/web/playurl?avid=undefined&cid=236686528&bvid=BV1zz4y1Z7B9&qn=0&type=&otype=json&ep_id=330489&fourk=1&fnver=0&fnval=80&session=b25eac03b4131b8adbaa1ec497e9f4f2&module=bangumi&balh_ajax=1&access_key=7d680a816add190f0f4992e2c9db8291
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
