### ISSUE TITLE
视频变成16秒的出错视频

### ISSUE THREAD

**Issue by Gagelee** [ipcjs/bilibili-helper#67]
## 日志
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183801
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"呵呵哒假肢","isLogin":true,"level":4,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183801,"last_ep_index":"3","last_time":1}}}
log: setAreaLimitSeason ep183801 true
log: Redirected request: bangumi playurl ->  https://biliplus.ipcjs.win/BPplayurl.php?cid=30670211|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=20d7229087c45ddce8daec51398f86a8
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
#58
