### ISSUE TITLE
7.9.7 脚本好像有点问题，降级到7.9.5之后可用

### ISSUE THREAD

**Issue by Sion2015** [ipcjs/bilibili-helper#677]
debug了20分钟发现降级就行了。具体fix交给作者了

**Comment by Sion2015** [comment]
https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6?version=815538
降级链接

**Comment by syr-123** [comment]
非常感谢！！
另外我想问一下，昨天浏览器崩溃了一次之后，我现在打开视频，就看不到土星标志和设置那些按钮了...请问这个也是脚本出问题的情况吗？还是我自己这里哪里不对.....orz

**Comment by steven7851** [comment]
同样问题，revert https://github.com/ipcjs/bilibili-helper/commit/78096584aef71a4f60485ebf1a52b77cfc4ebe61 就正常了

![snipaste_20201015_145328](https://user-images.githubusercontent.com/6252238/96087386-5a05b800-0ef6-11eb-9d16-f60c6a0340a9.png)

**Comment by yujincheng08** [comment]
海外用户？

**Comment by steven7851** [comment]
> 海外用户？

嗯 海外

**Comment by yujincheng08** [comment]
试试#679
