### ISSUE TITLE
如何取消b站账号授权

### ISSUE THREAD

**Issue by liushuai19920827** [ipcjs/bilibili-helper#68]
## 描述

如何取消b站账号授权，点开那个按钮，弹出来的还是账号授权，之后显示存储成功

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by linwea** [comment]
https://biliplus.ipcjs.win/

打开这个网站退出登录

**Comment by ipcjs** [comment]
是bug
6.7.5修复
