### ISSUE TITLE
问一下，这个项目有没有可能做成openwrt上的插件呢

### ISSUE THREAD

**Issue by JoseStone5** [ipcjs/bilibili-helper#680]
用路由器翻墙后，所有b站番剧都得靠这个插件看，有没有可能做成路由器插件，像https://github.com/maxlicheng/luci-app-unblockmusic  一样呢？我对编程不太了解

**Comment by ipcjs** [comment]
路由器翻墙应该可以配置那些域名不走代理的吧，把B站的域名加进去。

**Comment by JoseStone5** [comment]
> 路由器翻墙应该可以配置那些域名不走代理的吧，把B站的域名加进去。

emmm我是用ipv6实现校园网免流，所以必须全部流量都走代理

**Comment by ipcjs** [comment]
可行性应该是有的，脚本的原理很简单，就是转发几个请求而已
不过我没这需求，你可以自己写写看🤔
