### ISSUE TITLE
新版插件可以用网页看港澳台新番了(旧版不行还是得用app)，但不能发弹幕，评论区排版错误。这些功能会修复吗？

### ISSUE THREAD

**Issue by AimerEGOIST** [ipcjs/bilibili-helper#682]

**Comment by aeric20044** [comment]
> 
> 
> _No description provided._

求新插件连结阿

**Comment by ipcjs** [comment]
8.0.1 https://github.com/ipcjs/bilibili-helper/commit/84cc48b7f34b38ab30809c2f3d52ca31df4bc676
