### ISSUE TITLE
无法访问服务器或服务器返回异常 [NetworkErro] Exception：Failed to fetch

### ISSUE THREAD

**Issue by Yalio** [ipcjs/bilibili-helper#686]
脚本问题：@ipcjs

## 描述

无法访问服务器或服务器返回异常
- 问题网址：
https://www.bilibili.com/bangumi/play/ss34642
## 日志
debug: [解除B站区域限制 v7.9.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss34642
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: bosu flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=241643364&qn=120&type=&otype=json&fourk=1&bvid=BV1Tf4y1Q7GZ&ep_id=342510&fnver=0&fnval=80&session=4612fb0a6710523728262d675ce2184e&module=pgc&access_key=c20b5eb1210226af850ef2fd1eec41a1&platform=android&fnval=0
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
debug: /x/web-interface/nav {"uname":"18Z-0","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"accept_format":"hdflv2,flv,flv720,flv480,mp4","code":0,"seek_param":"start","is_preview":0,"fnval":0,"video_project":true,"fnver":0,"type":"FLV","bp":0,"result":"suee","seek_type":"offset","vip_type":2,"from":"local","video_codecid":7,"durl":[{"size":787734488,"ahead":"","length":1420007,"vhead":"","backup_url":[],"url":"https://upos-sz-mirrorbos.bilivideo.com/upgcxcode/64/33/241643364/241643364-1-112.flv?e=ig8euxZM2rNcNbNMnWhVhwdlhbKHhzdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1604144256&gen=playurl&os=akam&oi=19064611&trid=4f65f3d0be944f089fe3bbba817ba0cep&platform=android&upsig=78048516a2f985fb7555590dbd7dbb6e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1604137056~hmac=8180720d6d9c0137ec9daa951367f648e9ac964c6b6a5d4d2c0dcf791670d599&mid=20313204&orderid=0,1&logo=80000000","order":1,"md5":""}],"no_rexcode":0,"format":"hdflv2","support_formats":[{"display_desc":"1080P","superscript":"高码率","need_login":true,"format":"hdflv2","description":"高清 1080P+","need_vip":true,"quality":112,"new_description":"1080P 高码率"},{"display_desc":"1080P","superscript":"","need_login":true,"format":"flv","description":"高清 1080P","quality":80,"new_description":"1080P 高清"},{"display_desc":"720P","superscript":"","need_login":true,"format":"flv720","description":"高清 720P","quality":64,"new_description":"720P 高清"},{"display_desc":"480P","superscript":"","format":"flv480","description":"清晰 480P","quality":32,"new_description":"480P 清晰"},{"display_desc":"360P","superscript":"","format":"mp4","description":"流畅 360P","quality":16,"new_description":"360P 流畅"}],"message":"","accept_quality":[112,80,64,32,16],"quality":112,"timelength":1420007,"has_paid":false,"vip_status":1,"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":2,"flvjsType":"flv","loginStatus":{"isLogin":true,"uname":"18Z-0","mid":20313204,"level":5,"vip_expire":1665072000000}},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)
}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)
}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=241643364&bvid=BV1Tf4y1Q7GZ&qn=16&type=&otype=json&ep_id=342510&fourk=1&fnver=0&fnval=80&session=30f3aceb852c8b7ce13c38f036a4a0c4&module=pgc&balh_ajax=1&access_key=c20b5eb1210226af850ef2fd1eec41a1&platform=android&fnval=0
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：chrome
2. 国家/地区：

**Comment by yujincheng08** [comment]
先把upos取消了吧。怎么修我还得再看看。
