### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by aiyce** [ipcjs/bilibili-helper#69]
## 描述

无法播放

## 日志

log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183801
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"@@@@@","isLogin":true,"level":4,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183801,"last_ep_index":"3","last_time":-1}}}
log: setAreaLimitSeason ep183801 true
log: Redirected request: bangumi playurl ->  https://biliplus.ipcjs.win/BPplayurl.php?cid=30670211|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=f6cf78bfc546165f169fe2322efa0105
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

## 其他

1. 浏览器版本：谷歌最新
2. 国家/地区：大陆

**Comment by ipcjs** [comment]
网站应该在维护中吧

**Comment by weldss** [comment]
为什么我看不了，一直显示视屏无法播放
