### ISSUE TITLE
日在校园 拉取视频地址失败

### ISSUE THREAD

**Issue by fyk210** [ipcjs/bilibili-helper#692]
https://www.bilibili.com/bangumi/play/ss35583/
换服务器无用

## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-10403,\"message\":\"抱歉您所使用的平台不可观看！\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"游客ac69ed4d\",\"mid\":0,\"level\":0,\"vip_expire\":0}}","code":-10403}

浏览器chrome87.0.4280.88

**Comment by zkyhzxf** [comment]
+1，同没法看，听说是泰国限定???
参考https://t.bilibili.com/464871196944806384

**Comment by kong1998-lgtm** [comment]
warn: 解除B站区域限制 加载时机不对, 不能保证正常工作

1. 点击'确定', 刷新页面/重载脚本
2. 若依然出现该提示, 请尝试'硬性重新加载'(快捷键一般为ctrl+f5)
3. 若还是出现该提示, 请尝试关闭再重新打开该页面
4. 若反复出现该提示, 请尝试换个浏览器

debug: [解除B站区域限制 v8.0.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss35583/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: interactive isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=254381347&qn=116&type=&otype=json&fourk=1&bvid=BV1WK4y1E75F&ep_id=367262&fnver=0&fnval=80&session=079342fb68cbcd86eac12ee8ee3a22a0&module=pgc&access_key=f77f65a1869b15287dd5cc71854497c1&platform=android&fnval=0
debug: /x/web-interface/nav {"uname":"怀萌少年","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
error: {"code":-10403,"message":"抱歉您所使用的平台不可观看！","loginStatus":{"isLogin":true,"uname":"游客764f5763","mid":0,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-10403,\"message\":\"抱歉您所使用的平台不可观看！\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"游客764f5763\",\"mid\":0,\"level\":0,\"vip_expire\":0}}","code":-10403}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=254381347&qn=116&type=&otype=json&fourk=1&bvid=BV1WK4y1E75F&ep_id=367262&fnver=0&fnval=80&session=079342fb68cbcd86eac12ee8ee3a22a0&module=bangumi&access_key=f77f65a1869b15287dd5cc71854497c1
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=254381347&bvid=BV1WK4y1E75F&qn=116&type=&otype=json&ep_id=367262&fourk=1&fnver=0&fnval=80&session=7f00438d0382ec33add03fae1347c16d&module=pgc&balh_ajax=1&access_key=f77f65a1869b15287dd5cc71854497c1&platform=android&fnval=0
error: {"code":-10403,"message":"抱歉您所使用的平台不可观看！","loginStatus":{"isLogin":true,"uname":"游客764f5763","mid":0,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-10403,\"message\":\"抱歉您所使用的平台不可观看！\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"游客764f5763\",\"mid\":0,\"level\":0,\"vip_expire\":0}}","code":-10403}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=254381347&bvid=BV1WK4y1E75F&qn=116&type=&otype=json&ep_id=367262&fourk=1&fnver=0&fnval=80&session=7f00438d0382ec33add03fae1347c16d&module=bangumi&balh_ajax=1&access_key=f77f65a1869b15287dd5cc71854497c1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
