### ISSUE TITLE
进击的巨人 The Final Season 无法观看

### ISSUE THREAD

**Issue by StewartSX** [ipcjs/bilibili-helper#694]
脚本问题：@ipcjs

## 描述

- 问题网址：https://www.bilibili.com/bangumi/play/ss36297/

## 拉取视频地址失败
原因: {"name":"AjaxException","message":"服务器错误: {\"code\":-10403,\"message\":\"抱歉您所使用的平台不可观看！\",\"loginStatus\":{\"isLogin\":true,\"uname\":\"游客12a379ae\",\"mid\":0,\"level\":0,\"vip_expire\":0}}","code":-10403}

## 其他

1. 浏览器版本：chrome 87.0.4280.88（正式版本）
2. 国家/地区：中国大陆

**Comment by StewartSX** [comment]
不知道是B站问题还是脚本问题，所以试着问下作者大佬

**Comment by blue1874** [comment]
@StewartSX 应该是b站问题，我试过上台湾节点全局代理也看不了
（实在不明白这动画给哪里人看的

**Comment by NamelessJohan** [comment]
我也是一样的问题，有会员也打不开，试着问下作者大佬+1

**Comment by wladder** [comment]
我懷疑是APP限定的 拒絕WEB端請求了

**Comment by NonoKing** [comment]
刚尝试了一下用油猴脚本是可以看的

**Comment by ipcjs** [comment]
我这能点开，更新到最新版试下？

**Comment by StewartSX** [comment]
可以了兄弟们，脚本没问题，是B站问题

**Comment by ipcjs** [comment]
@StewartSX 所以你用脚本能不能打开？

**Comment by wladder** [comment]
> @StewartSX 所以你用脚本能不能打开？

现在用bili+会 -412 请求被拦截
