### ISSUE TITLE
巨人无法观看

### ISSUE THREAD

**Issue by swhoro** [ipcjs/bilibili-helper#695]
## 描述

显示403
![image](https://user-images.githubusercontent.com/34229589/101438593-ad701180-394d-11eb-9b96-43f19f557c17.png)
https://biliplus.ipcjs.top/api/bangumi?season=5551 测试链接能正常打开
测试番剧能正常播放
![image](https://user-images.githubusercontent.com/34229589/101438722-f922bb00-394d-11eb-945f-d6b318961725.png)

## 日志
<details>
<summary>Verbose 日志</summary>
debug: [解除B站区域限制 v8.0.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss36297
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: hw flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: undefined
debug: /x/web-interface/nav {"uname":"狼in约伊兹","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=263762334&qn=120&type=&otype=json&fourk=1&bvid=BV1t64y1f7Bb&ep_id=369747&fnver=0&fnval=80&session=748cd874c8675ff63cd57076f1b2d76d&module=pgc&access_key=4cb80f26c5d66702fd9b9b803b0d5a81&platform=android&fnval=0
debug: /pgc/player/web/playurl proxy(redirect) {"code":0,"result":{"accept_format":"hdflv2,flv,flv720,flv480,mp4","code":0,"seek_param":"start","is_preview":0,"fnval":0,"video_project":true,"fnver":0,"type":"FLV","bp":0,"result":"suee","seek_type":"offset","vip_type":2,"from":"local","video_codecid":7,"durl":[{"size":1102313068,"ahead":"","length":1435111,"vhead":"","backup_url":[],"url":"https://upos-sz-mirrorhw.bilivideo.com/upgcxcode/34/23/263762334/263762334-1-112.flv?e=ig8euxZM2rNcNbhM7WTVhwdlhzKB7bdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1607414654&gen=playurl&os=asiaovbv&oi=19048286&trid=7e0961f97d654288929c201127bc4832p&platform=android&upsig=874c94952c100544abe874c9fe03ed83&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=3234205&orderid=0,1&logo=80000000","order":1,"md5":""}],"no_rexcode":0,"format":"hdflv2","support_formats":[{"display_desc":"1080P","superscript":"高码率","need_login":true,"format":"hdflv2","description":"高清 1080P+","need_vip":true,"quality":112,"new_description":"1080P 高码率"},{"display_desc":"1080P","superscript":"","need_login":true,"format":"flv","description":"高清 1080P","quality":80,"new_description":"1080P 高清"},{"display_desc":"720P","superscript":"","need_login":true,"format":"flv720","description":"高清 720P","quality":64,"new_description":"720P 高清"},{"display_desc":"480P","superscript":"","format":"flv480","description":"清晰 480P","quality":32,"new_description":"480P 清晰"},{"display_desc":"360P","superscript":"","format":"mp4","description":"流畅 360P","quality":16,"new_description":"360P 流畅"}],"message":"","accept_quality":[112,80,64,32,16],"quality":112,"timelength":1435111,"has_paid":false,"vip_status":1,"accept_description":["高清 1080P+","高清 1080P","高清 720P","清晰 480P","流畅 360P"],"status":2,"flvjsType":"flv","loginStatus":{"isLogin":true,"uname":"狼in约伊兹","mid":3234205,"level":6,"vip_expire":1626451200000}},"message":"0"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"狼in约伊兹","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=263762334&bvid=BV1t64y1f7Bb&qn=16&type=&otype=json&ep_id=369747&fourk=1&fnver=0&fnval=80&session=ca9bc94773641bf8526cff7dc762d40a&module=pgc&balh_ajax=1&access_key=4cb80f26c5d66702fd9b9b803b0d5a81&platform=android&fnval=0
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.55
</details>

## 其他

1. 浏览器版本：chrominum edge 87.0.664.55
2. 国家/地区：大陆

**Comment by ipcjs** [comment]
把upos设为“不替换”

**Comment by swhoro** [comment]
> 把upos设为“不替换”

谢谢，已解决
