### ISSUE TITLE
脚本错误

### ISSUE THREAD

**Issue by seeroffish** [ipcjs/bilibili-helper#696]
debug: [解除B站区域限制 v8.0.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep341253
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"Little人鱼","mid":12521756,"level":6,"vip_expire":1693324800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"Little人鱼\",\"mid\":12521756,\"level\":6,\"vip_expire\":1693324800000}}","code":-412}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=262759909&bvid=BV1BX4y1M7yC&qn=80&type=&otype=json&ep_id=341253&fourk=1&fnver=0&fnval=80&session=7c92ec5c61b59dc590c48d276226371d&module=pgc&balh_ajax=1&access_key=dacfc70b2e3eb47b6a127e1255300dc1
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"Little人鱼","mid":12521756,"level":6,"vip_expire":1693324800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"Little人鱼\",\"mid\":12521756,\"level\":6,\"vip_expire\":1693324800000}}","code":-412}
debug: /x/web-interface/nav {"uname":"Little人鱼","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"Little人鱼","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: balh_server_inner  =>  __custom__
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by Nicomakii** [comment]
+1 地点：美国

**Comment by Godnight1006** [comment]
我也是唉

debug: [解除B站区域限制 v8.0.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep239628
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"Windgod1006","mid":481168663,"level":3,"vip_expire":1609689600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"Windgod1006\",\"mid\":481168663,\"level\":3,\"vip_expire\":1609689600000}}","code":-412}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"Windgod1006","isLogin":true,"level":3,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=48346342&bvid=BV1cs411P75M&qn=80&type=&otype=json&ep_id=239628&fourk=1&fnver=0&fnval=80&session=45546aa2a5e6fc99e80628b9210c5abe&module=pgc&balh_ajax=1&access_key=bf759499135197d6e4c05755c23414c1
debug: /x/web-interface/nav {"uname":"Windgod1006","isLogin":true,"level":3,"vipType":1,"vipStatus":1,"isFromReport":false}
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"Windgod1006","mid":481168663,"level":3,"vip_expire":1609689600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"Windgod1006\",\"mid\":481168663,\"level\":3,\"vip_expire\":1609689600000}}","code":-412}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.55

**Comment by NameLessKnight** [comment]
同上

**Comment by ZSunEPS** [comment]
debug: [解除B站区域限制 v8.0.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss29052?t=588
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: kodou flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=139299787&qn=116&type=&otype=json&fourk=1&bvid=BV1uJ411h7Me&ep_id=299884&fnver=0&fnval=80&session=dbe180da234a364ecfb08531158ce80d&module=pgc&access_key=895eb96f628fd6c813358c7293d2f9c1
debug: /x/web-interface/nav {"uname":"楠濑-诺艾尔","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"楠濑-诺艾尔","mid":5283095,"level":5,"vip_expire":1650124800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"楠濑-诺艾尔\",\"mid\":5283095,\"level\":5,\"vip_expire\":1650124800000}}","code":-412}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=139299787&bvid=BV1uJ411h7Me&qn=116&type=&otype=json&ep_id=299884&fourk=1&fnver=0&fnval=80&session=6998b17f53d6cdc0c3f9bb22a436072c&module=pgc&balh_ajax=1&access_key=895eb96f628fd6c813358c7293d2f9c1
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"楠濑-诺艾尔","mid":5283095,"level":5,"vip_expire":1650124800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"楠濑-诺艾尔\",\"mid\":5283095,\"level\":5,\"vip_expire\":1650124800000}}","code":-412}
debug: /x/web-interface/nav {"uname":"楠濑-诺艾尔","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by wzh4464** [comment]
啊 我的同上 另开了一个issue, 我那个是不是可以关了？

**Comment by wzh4464** [comment]
debug: [解除B站区域限制 v8.0.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss34402?t=225
debug: window.playinfo
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip: server: https://www.biliplus.com upos_server: flv_prefer_ws: remove_pre_ad: enable_in_av: readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: playinfo get
debug: /x/web-interface/nav {"uname":"霍霍爱吃虾滑","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ss34402 true
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=252800273&qn=0&type=&otype=json&fourk=1&bvid=BV1jA411j7Yu&ep_id=341485&fnver=0&fnval=80&session=0a215f19a2c8aa702c13054efcc9c965&module=pgc&access_key=a8043e392113839bc97942da5a657cc1
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"霍霍爱吃虾滑","mid":38036570,"level":5,"vip_expire":1692633600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"霍霍爱吃虾滑","mid":38036570,"level":5,"vip_expire":1692633600000}}","code":-412}
debug: playinfo set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: playinfo get
debug: playinfo get
debug: playinfo get
debug: playinfo get
debug: playinfo get
debug: playinfo get
debug: playinfo get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=252800273&bvid=BV1jA411j7Yu&qn=0&type=&otype=json&ep_id=341485&fourk=1&fnver=0&fnval=80&session=1a1e969e6ad79206a8fcd4a8e1cf826a&module=pgc&balh_ajax=1&access_key=a8043e392113839bc97942da5a657cc1
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"霍霍爱吃虾滑","mid":38036570,"level":5,"vip_expire":1692633600000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"霍霍爱吃虾滑","mid":38036570,"level":5,"vip_expire":1692633600000}}","code":-412}
debug: /x/web-interface/nav {"uname":"霍霍爱吃虾滑","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by SuperElephant** [comment]
+1 坐标美国
```
debug: [解除B站区域限制 v8.0.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep264225?from=search&seid=17836900485603097613
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"SuperEle","mid":9810705,"level":5,"vip_expire":1618156800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"SuperEle\",\"mid\":9810705,\"level\":5,\"vip_expire\":1618156800000}}","code":-412}
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://www.biliplus.com/BPplayurl.php?avid=undefined&cid=78802700&bvid=BV14b411b7Cm&qn=80&type=&otype=json&ep_id=264225&fourk=1&fnver=0&fnval=80&session=ffdbe1cd0f5aab60b5eed6795bcb1f21&module=pgc&balh_ajax=1&access_key=c79b885ec4250e1f2d84c5004fffdfc1
debug: /x/web-interface/nav {"uname":"SuperEle","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"SuperEle","mid":9810705,"level":5,"vip_expire":1618156800000}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"SuperEle\",\"mid\":9810705,\"level\":5,\"vip_expire\":1618156800000}}","code":-412}
debug: /x/web-interface/nav {"uname":"SuperEle","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
```

**Comment by wzh4464** [comment]
都是海外翻国内的吧

**Comment by ceramshaw** [comment]
同
坐标日本，也是请求被拦截

**Comment by sam01101** [comment]
理论上应该是被服务器检测到拦截链接了

**Comment by BraveSail** [comment]
> 都是海外翻国内的吧

坐标国内，看港澳台和内地番也是拦截

**Comment by Eric8925** [comment]
jojo看的正在兴头上呢，吉良吉影马上要悟出来败者食尘了。。竟然没法看了！岂可休

**Comment by deernic** [comment]
同，也是412，国外翻国内被拦截惹555

**Comment by axakira** [comment]
澳洲同上

**Comment by axakira** [comment]
澳洲同上，換服務器也沒用

**Comment by shiyukfong** [comment]
香港同上，突然看不了

**Comment by sam01101** [comment]
快加点Header什么的解决吧

**Comment by Alphayellowcat** [comment]
澳洲 code : -412

**Comment by tandagou** [comment]
在俄罗斯，也是412

**Comment by wzh4464** [comment]
是不是好了

**Comment by SuperElephant** [comment]
> 是不是好了

emmm现在能用了
