### ISSUE TITLE
看不了unnatural  微博已联系

### ISSUE THREAD

**Issue by xztc** [ipcjs/bilibili-helper#70]
## 描述

看不了unnatural  微博已联系
unnatural那页找不到日志，只能换了一个页面
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep103736
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: true isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"右手惨被夺","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0}}
log: setAreaLimitSeason ep103736 true
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=16672007|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=5e30a9f740ddaa24cf87ecedc9fd3028
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
我有试了下，是可以打开的
