### ISSUE TITLE
[Feature request] 僅解除網頁上的app限制

### ISSUE THREAD

**Issue by yangzhaofeng** [ipcjs/bilibili-helper#703]
脚本问题：@ipcjs

## 描述
目前無論用戶的公網IP為多少對於 app only 的內容都需要通過代理服務器來獲取。原理是在 `${balh_config.server}/BPplayurl.php` 的參數中加入 `platform=android` 和 `fnval=0`。這兩個參數在後端會如何調用 bilibili api？對於已經是對應地區IP的用戶而言，如果能在瀏覽器本地做，可以降低 biliplus 服務器的負擔，同時在biliplus出錯的時候也能使用。另外用戶也無需傳cookie到biliplus，也能增加安全性。

- 问题网址：
https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/src/main.js#L723
https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/src/api/bilibili.ts#L9

## 其他

1. 浏览器版本：Chrome 89.0.4350.6
2. 国家/地区：HK -> HK

**Comment by ipcjs** [comment]
浏览器本地就是不行，才需要走biliplus呀

**Comment by yangzhaofeng** [comment]
根據 #711 這個似乎是可行的？

把默認的服務器改成 https://api.bilibili.com 就可以了？

不過依然需要授權cookies，這一點似乎無解？
