### ISSUE TITLE
请求被拦截

### ISSUE THREAD

**Issue by TooYoungTooSimples** [ipcjs/bilibili-helper#709]
debug: [解除B站区域限制 v8.0.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep318867?from=search&seid=13769044964247648966
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://biliplus.ipcjs.top upos_server: ks3u flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"微凉凉啊","isLogin":true,"level":2,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"微凉凉啊","isLogin":true,"level":2,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从代理服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://biliplus.ipcjs.top/BPplayurl.php?avid=undefined&cid=176440053&bvid=BV1Mk4y1R735&qn=116&type=&otype=json&ep_id=318867&fourk=1&fnver=0&fnval=80&session=07cd47894f12b281cae582617e0e2b8e&module=pgc&balh_ajax=1&access_key=28d86da64f3677c460be57d16bc759c1
error: {"code":-412,"message":"请求被拦截","ttl":1,"data":null,"loginStatus":{"isLogin":true,"uname":"游客ac69ed4d","mid":0,"level":0,"vip_expire":0}}
info: player msg: {"name":"AjaxException","message":"服务器错误: {\"code\":-412,\"message\":\"请求被拦截\",\"ttl\":1,\"data\":null,\"loginStatus\":{\"isLogin\":true,\"uname\":\"游客ac69ed4d\",\"mid\":0,\"level\":0,\"vip_expire\":0}}","code":-412}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=176440053&bvid=BV1Mk4y1R735&qn=116&type=&otype=json&ep_id=318867&fourk=1&fnver=0&fnval=80&session=07cd47894f12b281cae582617e0e2b8e&module=bangumi&balh_ajax=1&access_key=28d86da64f3677c460be57d16bc759c1
debug:   =>  
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4181.9 Safari/537.36

**Comment by Elletear** [comment]
都是同一個問題，已經有好幾個相同issue了，沒必要重新開了😂（僅個人善意提醒）
#704 #705 #706 #707 #708

**Comment by ironyx217** [comment]
給點時間讓老哥慢慢修吧

**Comment by autoAnti** [comment]
周五还好好的 突然就炸了 吓一跳 还以为我的FF浏览器抽风了 彻底删除了 重装 
等待大哥修复吧

**Comment by LiangJue** [comment]
之前好了。现在又不行了。。
