### ISSUE TITLE
QQ浏览器无法使用脚本

### ISSUE THREAD

**Issue by sakana164** [ipcjs/bilibili-helper#712]
脚本问题：@ipcjs
QQ浏览器无法使用脚本
## 描述

![QQ截图20201219233302](https://user-images.githubusercontent.com/76257039/102693063-b799e600-4252-11eb-8903-ec9874210d2f.png)
没有重新编译前的8.0.5，还正常显示模块设置按钮，但是在安装重新编译后的8.0.5以及之后的8.0.6，脚本不生效，不显示设置按钮
- 问题网址：
https://www.bilibili.com/bangumi/play/ss33086/

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
![QQ截图20201219233648](https://user-images.githubusercontent.com/76257039/102693105-165f5f80-4253-11eb-98da-4807dd780980.png)

2. 国家/地区：中国

**Comment by ipcjs** [comment]
最新版，试下

**Comment by niu164** [comment]
刚刚试了，还是不行，不显示按钮，也可以说脚本根本没生效

**Comment by sakana164** [comment]
> 最新版，试下

刚刚试了，还是不行，不显示按钮，也可以说脚本根本没生效

**Comment by ipcjs** [comment]
控制台(F12)截图，看下

**Comment by ghost** [comment]
> 控制台(F12)截图，看下

@ipcjs 
我也是这种问题 ，已更新到8.0.7版本 /  
F12 (控制台)
[QQ截图20201221102526.png](https://i.loli.net/2020/12/21/Dx7TSpIcLdJysq2.png)

**Comment by sakana164** [comment]
> 控制台(F12)截图，看下

![QQ截图20201221201044](https://user-images.githubusercontent.com/76257039/102775865-a96dd600-43c8-11eb-8124-47a1e0df9cf2.png)
你看看，很奇怪

**Comment by ipcjs** [comment]
哦，找到了，在js里面写了个optional chaining。。。
8.0.8应该可以了

**Comment by sakana164** [comment]
> 哦，找到了，在js里面写了个optional chaining。。。
> 8.0.8应该可以了

刚刚试了，可以了，upos服务器能不能增加akamai等其他更多的
