### ISSUE TITLE
Edge浏览器脚本无效

### ISSUE THREAD

**Issue by luffyklose** [ipcjs/bilibili-helper#715]
脚本问题：@ipcjs

## 描述
Edge浏览器无法使用，已经在油猴勾选了启用脚本，但是找不到脚本的设置按钮

- 问题网址：
所有视频都用不了

## 日志

没有日志

## 其他

1. 浏览器版本：Edge 87.0.664.66（64位）
2. 国家/地区：加拿大

**Comment by 1Step2Talk** [comment]
1. `F12` 进入开发者工具的 Console 标签页
2. 输入命令`bangumi_area_limit_hack.showSettings()`调出脚本设置
3. 填入自定义代理服务器后脚本正常工作，可能与初始状态下自定义代理为空有关

**Comment by sakana164** [comment]
> 1. `F12` 进入开发者工具的 Console 标签页
> 2. 输入命令`bangumi_area_limit_hack.showSettings()`调出脚本设置
> 3. 填入自定义代理服务器后脚本正常工作，可能与初始状态下自定义代理为空有关

我是QQ浏览器，脚本也无法生效，按照你说的操作了，也不行
![QQ截图20201221201305](https://user-images.githubusercontent.com/76257039/102776074-0d909a00-43c9-11eb-9c92-7cb38599ea71.png)

**Comment by luffyklose** [comment]
还是不好用，两个代理地址都试过了
![image](https://user-images.githubusercontent.com/45724496/103050927-96433d80-4563-11eb-94fc-c1338302b0a3.png)

**Comment by sakana164** [comment]
> 还是不好用，两个代理地址都试过了
> ![image](https://user-images.githubusercontent.com/45724496/103050927-96433d80-4563-11eb-94fc-c1338302b0a3.png)

代理地址？现在biliplus都关了，需要自己填自定义服务器

**Comment by luffyklose** [comment]
我两个都试了，都是这个报错
![image](https://user-images.githubusercontent.com/45724496/103103274-00a0c000-45ee-11eb-810c-ccad9fa8f8bf.png)

**Comment by sakana164** [comment]
> 我两个都试了，都是这个报错
> ![image](https://user-images.githubusercontent.com/45724496/103103274-00a0c000-45ee-11eb-810c-ccad9fa8f8bf.png)

这些服务器又不归脚本作者管，服务器自己确定可用性，又不一定，自己试试其他的

**Comment by luffyklose** [comment]
好吧，但是我从哪里能看出来是服务器的问题还是脚本的问题呢？

**Comment by sakana164** [comment]
> 好吧，但是我从哪里能看出来是服务器的问题还是脚本的问题呢？

你自定义服务器试试这个https://bili.tuturu.top
我这个能用，建议先清除缓存包括cookie

**Comment by luffyklose** [comment]
不行，还是报错
![image](https://user-images.githubusercontent.com/45724496/103139899-2b068200-46af-11eb-854a-9a8aa4343786.png)

**Comment by niu164** [comment]
> 不行，还是报错
> ![image](https://user-images.githubusercontent.com/45724496/103139899-2b068200-46af-11eb-854a-9a8aa4343786.png)

![Uploading QQ图片20201226141135.png…]()
那就不知道了，我使用正常

**Comment by sakana164** [comment]
> 不行，还是报错
> ![image](https://user-images.githubusercontent.com/45724496/103139899-2b068200-46af-11eb-854a-9a8aa4343786.png)

![QQ图片20201226141135](https://user-images.githubusercontent.com/76257039/103146473-d6cdd180-4784-11eb-8991-9ecbf304c7c8.png)
那就不知道了，我使用正常，你问问作者

**Comment by luffyklose** [comment]
好奇怪，明明是一样的设置啊……
