### ISSUE TITLE
[idea] UWP 官方客户端 解除海外限制 API

### ISSUE THREAD

**Issue by MichaelMai2000** [ipcjs/bilibili-helper#716]
UWP有个[官方的客户端](https://www.microsoft.com/zh-cn/p/哔哩哔哩动画/9nblggh5q5fv)，海外IP可以开启解除海外限制。
我用WireShark抓了个包，似乎在和某个服务器直接在TCP层连接，然后会返回一个直链，替换海外无法播放的301。
不知道能不能作为一个idea，不过感觉很容易被封杀，导致UWP官方客户端也完全用不了。
顺便，官方客户端经常更新，而且每次都会更掉一些很有用的内容。目前最新版的客户端已经无法直接复制出直链了，但抓包应该还是可以抓到；之前有一次更新把番剧下载更掉了。。。大概就是这样。

**Comment by wax951223** [comment]
兄dei请问uwp这个客户端怎么解除的限制呀

**Comment by MichaelMai2000** [comment]
> 兄dei请问uwp这个客户端怎么解除的限制呀

没有源码，具体原理我也不知道。靠抓包观察行为就是：B站有个内部服务器，供满足条件的客户端使用，负责把版权内容分发海外；官方的解除限制。

**Comment by OscarSheng** [comment]
> > 兄dei请问uwp这个客户端怎么解除的限制呀
> 
> 没有源码，具体原理我也不知道。靠抓包观察行为就是：B站有个内部服务器，供满足条件的客户端使用，负责把版权内容分发海外；官方的解除限制。

他的意思是在你说的app里面没找到解除限制的设置吧

**Comment by MichaelMai2000** [comment]
@OscarSheng 有道理。
![图片](https://user-images.githubusercontent.com/10582944/103237470-ce031880-499b-11eb-8ffa-e8199d7cbe83.png)
@wax951223
