### ISSUE TITLE
针对海外党的改进

### ISSUE THREAD

**Issue by CmmmmmmLau** [ipcjs/bilibili-helper#717]
海外党用云函数方式的时候需要同时用到大陆和港澳台服务器.
但目前脚本只能填一个服务器地址.
希望可以分出给大陆或港澳台填的地址栏
或者能自定义增加服务器地址,当一个返回服务器不可用或者当前地区无法观看的时候自动跳到下一个服务器继续

**Comment by NameLessKnight** [comment]
支持
