### ISSUE TITLE
在AV页面启用 无效

### ISSUE THREAD

**Issue by RunAway95** [ipcjs/bilibili-helper#719]
在设置里已勾选被永封的大会员 和在av页面启用   自己搭建的代理服务器也提交了大会员账号的Cookies

会员番剧可以正常播放 但是普通视频的4K大会员专享 仍然无法播放

浏览器抓包av页面 看到的确已经请求了代理地址 而且也返回了4K的播放地址 但是无法播放

最后发现 api.bilibili.com/x/player/v2 这个请求返回了会员状态 尝试用Fiddler抓包修改后 再选4K视频 不会再提示大会员专享 但是仍然提示切换失败

总之就是 av页面虽然已经请求了代理地址并且获取成功了播放地址 但是实际上还是没有用到从代理地址获取的播放地址 。。。

**Comment by windyhun** [comment]
emmmmmmmmmm我也是这个问题有没有办法解决
