### ISSUE TITLE
## 拉取视频地址失败  {"code":-10403,"message":"抱歉您所在地区不可观看！"}

### ISSUE THREAD

**Issue by HuangLuxuan** [ipcjs/bilibili-helper#725]
## 拉取视频地址失败
原因: {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
https://www.bilibili.com/bangumi/play/ep368703

原因: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
https://www.bilibili.com/bangumi/play/ss33094

补充：好像是所有的都不行

代理服务器试过
https://bili-proxy.98e.org
https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/
https://bili.tuturu.top
https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com
结果都不行

这是什么情况啊

**Comment by Elletear** [comment]
刚刚测试了一下我这里是可用的，建议尝试更新脚本以及切换浏览器试试。（另外再提供一个地址，可以切换试试：	
https://bili-hk.blossomplus.tk ）
建议提出issue时注明浏览器种类版本、脚本版本等信息也更有助于解决问题。

**Comment by HuangLuxuan** [comment]
啊，并不知道为什么，刚刚试了下发现除了https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/以外又都好了，着实奇怪

但是呢ss35583，ss35584，ep368703这一类还是看不成，就很奇怪

**Comment by Elletear** [comment]
这几个是东南亚地区版权了，脚本暂时不支持的😂

**Comment by HSIKE** [comment]
遇到同样的问题，浏览器Chrome 87.0.4280.88, 脚本8.0.9， 试了一圈只有 [https://bili.tuturu.top
](https://bili.tuturu.top) 能用，但是非常卡

**Comment by xy2401** [comment]
同问。我是自己看 腾讯云cdn的 发现不行。是不是 这几个ip被用滥的 被b站ban了？ 以下几个我都试过了

  | 18.163.83.127  [中国香港亚马逊云] 18.162.159.119  [中国香港亚马逊云] 18.166.25.109  [中国香港亚马逊云] 18.162.90.124  [中国香港亚马逊云]

**Comment by Elletear** [comment]
@xy2401 测试Tencent CDN无问题，使用的你给出的2和4号IP😂

**Comment by HuangLuxuan** [comment]
@Elletear 也不知道以后脚本能不能支持东南亚版权的……

**Comment by Elletear** [comment]
bili漫游（ https://github.com/yujincheng08/BiliRoaming ）已经支持了，想体验的话可以去试试，该项目是Xposed模块。

**Comment by HuangLuxuan** [comment]
@Elletear 不错，挺厉害的，但是还是很期待web端的解决方案

**Comment by xiba191729** [comment]
兄弟们，你们是怎么调的？我萌新，知道能调，但是不会，，，
我下载的脚本版本是8.0.9的，是直接在代码里面调还是咋整啊？？（你们都是自己搭了梯子吗？）

**Comment by Elletear** [comment]
@xiba191729 1.善用搜索，已有相关issue及回复；
2.可以参考我这个回复：https://github.com/ipcjs/bilibili-helper/issues/726#issuecomment-753826498
