### ISSUE TITLE
怎么让输入自定义服务器的界面弹出来？

### ISSUE THREAD

**Issue by whichbitchusemyname** [ipcjs/bilibili-helper#726]
那个界面不弹出来啊

**Comment by hujincheng2009** [comment]
我也是不知道在哪里输入自定义服务器，输在代码server/costom里感觉没用啊

**Comment by Elletear** [comment]
更新到8.0.9，然后可以参考我这个回复：https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6/discussions/71510
![image](https://user-images.githubusercontent.com/70796317/103514361-6c651180-4ea7-11eb-8072-c5e9a4068519.png)
另外点击图标后，将服务器地址输入自定义后面的空格即可。
