### ISSUE TITLE
2021年1月新番港澳台 {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}

### ISSUE THREAD

**Issue by Vurliy** [ipcjs/bilibili-helper#731]
脚本问题：@ipcjs

## 描述

估计就是 api 对不上吧: https://acgsecrets.hk/bangumi/202101/ 这里有所有的 1月新番港澳台的播放地址
所有播放均是 该错误.

番剧名称: [摇曳露营△ 第二季](https://www.bilibili.com/bangumi/media/md28233163/)
在 进击的巨人 The Final Season 可以播放的情况下确认无法播放. 1月番剧似乎没有收入到 Anime_Ongoing 账户中.
可以确认该番剧港台可以播放, 且大陆无法播放( Acfun 独占 ). 猜测可能是 Api 的问题.

- 问题网址：
地址: [https://www.bilibili.com/bangumi/play/ss37489](https://www.bilibili.com/bangumi/play/ss37489) 与进击的巨人 同样的 ss 地址
地址: [https://www.bilibili.com/bangumi/play/ep377376](https://www.bilibili.com/bangumi/play/ep377376)

## 日志
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
debug: [解除B站区域限制 v8.0.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss37489
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"YourLi","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/api/playurl?access_key=d48a925e9ef7a42eec54f0a7042f3611&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=278765105&device=android&ep_id=377376&fnval=0&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=0&track_path=0&ts=1610033704&sign=00737a94b10be3d81453e1b6da2bc3b1
debug: /x/web-interface/nav {"uname":"YourLi","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=278765105&qn=0&type=&otype=json&fourk=1&bvid=BV17T4y1N7LS&ep_id=377376&fnver=0&fnval=80&session=541f846c336341eba00b4b3d282e670b&module=bangumi&access_key=d48a925e9ef7a42eec54f0a7042f3611
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/api/playurl?access_key=d48a925e9ef7a42eec54f0a7042f3611&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=278765105&device=android&ep_id=377376&fnval=0&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=0&track_path=0&ts=1610033717&sign=bdfd64e3cc25c6029124b5ec0030d601
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=278765105&bvid=BV17T4y1N7LS&qn=0&type=&otype=json&ep_id=377376&fourk=1&fnver=0&fnval=80&session=55ca5243a12d65c975fd6063829f8347&module=bangumi&balh_ajax=1&access_key=d48a925e9ef7a42eec54f0a7042f3611
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
<details>
<summary>Verbose 日志</summary>
```
 
</details>

## 其他

1. 浏览器版本：Chrome 87.0.4280.88 (64-bit)
2. 国家/地区：中国/美国

**Comment by BraveSail** [comment]
1月新番目前绝大部分只有泰国区可以看，网页版脚本目前还没有解锁泰国区的功能，可以先用[哔哩哔哩漫游](https://github.com/yujincheng08/BiliRoaming)观看

**Comment by Vurliy** [comment]
> 1月新番目前绝大部分只有泰国区可以看，网页版脚本目前还没有解锁泰国区的功能，可以先用[哔哩哔哩漫游](https://github.com/yujincheng08/BiliRoaming)观看

该番剧确定是港澳台番剧, 而且提示并不是 区域无法播放

**Comment by BraveSail** [comment]
> > 1月新番目前绝大部分只有泰国区可以看，网页版脚本目前还没有解锁泰国区的功能，可以先用[哔哩哔哩漫游](https://github.com/yujincheng08/BiliRoaming)观看
> 
> 该番剧确定是港澳台番剧, 而且提示并不是 区域无法播放

是港澳台番剧，但不只是港澳台限定，[👉播出地區包括: 孟加拉，不丹， 汶萊，柬埔寨，香港，印度，印尼，老撾，澳門，馬來西亞，馬爾代夫，蒙古，緬甸，尼泊爾，巴基斯坦，菲律賓，台灣，泰國，越南，新加玻](https://www.youtube.com/watch?v=jycSbANT_qw&t=241s)，目前b站的番剧版权涉及到港澳台的都看不了，如果泰国有版权的话就只能看泰国的
![image](https://user-images.githubusercontent.com/49320262/103924493-0201da80-510e-11eb-831c-306bbff6434b.png)

**Comment by Vurliy** [comment]
> > > 1月新番目前绝大部分只有泰国区可以看，网页版脚本目前还没有解锁泰国区的功能，可以先用[哔哩哔哩漫游](https://github.com/yujincheng08/BiliRoaming)观看
> > 
> > 
> > 该番剧确定是港澳台番剧, 而且提示并不是 区域无法播放
> 
> 是港澳台番剧，但不只是港澳台限定，[👉播出地區包括: 孟加拉，不丹， 汶萊，柬埔寨，香港，印度，印尼，老撾，澳門，馬來西亞，馬爾代夫，蒙古，緬甸，尼泊爾，巴基斯坦，菲律賓，台灣，泰國，越南，新加玻](https://www.youtube.com/watch?v=jycSbANT_qw&t=241s)，目前b站的番剧版权涉及到港澳台的都看不了，如果泰国有版权的话就只能看泰国的
> ![image](https://user-images.githubusercontent.com/49320262/103924493-0201da80-510e-11eb-831c-306bbff6434b.png)

你的意思是说 这种多地播放的 包含了香港和泰国的 都将使用 泰国 Api  么?

**Comment by BraveSail** [comment]
@Vurliy 是目前港澳台api是锁着的，只能通过泰国api看泰国的

**Comment by Vurliy** [comment]
@BraveSail 进击的巨人是因为 港澳台限定 所以使用的是老的 API?

**Comment by Vurliy** [comment]
@BraveSail 你试试 https://www.bilibili.com/bangumi/media/md28232382/ 这个是港澳台地址, 可以播放不, 泰国页面也是提示区域不可播放, 你看看 app端可以不

**Comment by kevinsio** [comment]
絕對是B站那邊設定出問題了，因為我用人在澳門，用港澳台的APP，在番劇索引點開『本地區可觀看』的1月新番，直接顯示『視頻不見了』。完全看不了。我也試過用台灣VPN，一樣看不了

**Comment by AkiraTyou** [comment]
目前B站的Anime_Ongoing发布渠道仍旧在正常通知，但是点进去就先显示然后跳转到提示“视频不见了"。Anime_Ongoing的签名变成Verification in progress  楼上说澳门也看不了，那就是B站在搞新的审查！

**Comment by BraveSail** [comment]
> 目前B站的Anime_Ongoing发布渠道仍旧在正常通知，但是点进去就先显示然后跳转到提示“视频不见了"。Anime_Ongoing的签名变成Verification in progress 楼上说澳门也看不了，那就是B站在搞新的审查！

因为被隐藏了，签名一直都是Verification in progress

**Comment by BraveSail** [comment]
> @BraveSail 你试试 [bilibili.com/bangumi/media/md28232382](https://www.bilibili.com/bangumi/media/md28232382/) 这个是港澳台地址, 可以播放不, 泰国页面也是提示区域不可播放, 你看看 app端可以不

![Screenshot_2021-01-09-15-28-26-734_com bilibili a](https://user-images.githubusercontent.com/49320262/104086053-4bf0da80-524c-11eb-8b40-2f9fd300c33b.jpg)
![Screenshot_2021-01-09-15-29-39-066_com bilibili a](https://user-images.githubusercontent.com/49320262/104086079-7d69a600-524c-11eb-8931-94e0a5d66d2f.jpg)

**Comment by Vurliy** [comment]
@kevinsio 可以说明下两个的链接么?
我看了下 b站同个番剧有两个 链接 ss 以及 ep 结尾的链接

**Comment by Vurliy** [comment]
@BraveSail 好吧 应该是港台那边的问题..... 泰国这些番剧貌似都可以正常观看... 对了你这个泰区标签怎么调出来的?

**Comment by BraveSail** [comment]
> @BraveSail 好吧 应该是港台那边的问题..... 泰国这些番剧貌似都可以正常观看... 对了你这个泰区标签怎么调出来的?

https://github.com/yujincheng08/BiliRoaming

**Comment by ipcjs** [comment]
这些页面我直接404呀，从biliplus拉取season信息也拉不到，啥情况？

**Comment by Vurliy** [comment]
> 这些页面我直接404呀，从biliplus拉取season信息也拉不到，啥情况？

页面被做了 ip 地址验证 非 泰国, 新加坡 等 东南亚 ip 自动跳转到 404 页面(最近加的, 开讨论的时候没有)

只要是 泰国, 新加坡 等 东南亚 ip 就可以正常显示. 应该是 js 调用第三方判断IP位置 api 实现的, 你可以抓包 或者 浏览器 控制台看下.
https://www.bilibili.com/bangumi/media/md28233163/
https://www.bilibili.com/bangumi/play/ss37489
https://www.bilibili.com/bangumi/play/ep377376
目前来看, 港澳台 官方禁止观看了(应该只有1月新番这样), 无论是 手机端 app 还是 网页均不行, 被提示 该地区无法观看.
只有泰国app可以观看, 网页端的 api 与以往12月番剧 api 不同, 所以可解锁 12月番剧的 api 无法使用

**Comment by Vurliy** [comment]
@BraveSail  我知道是这个项目, 我直接下载了 Xposed 版本. 但是搜索没有后没有这个泰国拆分项, 所以想问下 你用的是什么版本, 或者 是怎么把这个泰国拆分项调出来的

**Comment by BraveSail** [comment]
> @BraveSail 我知道是这个项目, 我直接下载了 Xposed 版本. 但是搜索没有后没有这个泰国拆分项, 所以想问下 你用的是什么版本, 或者 是怎么把这个泰国拆分项调出来的

连续点击版本号
