### ISSUE TITLE
控件不显示

### ISSUE THREAD

**Issue by cool-delete** [ipcjs/bilibili-helper#732]
脚本问题：@ipcjs

## 描述

- 问题网址：https://www.bilibili.com/bangumi/play/ss33860 .https://www.bilibili.com/bangumi/play/ep330452

## 日志

<details>
<summary>Verbose 日志</summary>

```
warn: 解除B站区域限制 加载时机不对, 不能保证正常工作

1. 点击'确定', 刷新页面/重载脚本
2. 若依然出现该提示, 请尝试'硬性重新加载'(快捷键一般为ctrl+f5)
3. 若还是出现该提示, 请尝试关闭再重新打开该页面
4. 若反复出现该提示, 请尝试换个浏览器
```
 
</details>

![image](https://user-images.githubusercontent.com/13638610/104059375-340b5d80-5230-11eb-8c46-ad8ce5c10a92.png)

## 其他

1. 浏览器版本：87.0.4280.141（正式版本） （64 位）win(最新)
2. 国家/地区：国内

**Comment by ipcjs** [comment]
我这没复现，更新到最新版试试能不能用？
