### ISSUE TITLE
无法查询到ep信息

### ISSUE THREAD

**Issue by sxjzycwcy** [ipcjs/bilibili-helper#740]
脚本问题：@ipcjs

## 描述
无法查询到ep信息, 请先刷新动画对应的www.bilibili.com/bangumi/media/md页面

- 问题网址：https://www.bilibili.com/bangumi/play/ep251210

## 其他

1. 浏览器版本：Microsoft Edge  87.0.664.75
2. 国家/地区：中国大陆   台湾（代理服务器地址）

**Comment by ipcjs** [comment]
**请先刷新动画对应的www.bilibili.com/bangumi/media/md页面**

**Comment by sxjzycwcy** [comment]
但是通过搜索点开的时候会默认跳转到/play/ss界面，而不会跳转到md界面

**Comment by Elletear** [comment]
刚刚试了下你提供的地址，我这边使用港区服务器是正常解析的，但解析出来的东西好像有点问题（被杂交了？😂）
![image](https://user-images.githubusercontent.com/70796317/104796198-0f465580-57ef-11eb-92bd-4672ae7b61be.png)
播放界面的视频是Tokyo Guru: re 2，但下面番剧介绍配图和简介都是银魂，点进去详情页也是银魂，依据下方评论区这又应该是Tokyo Guru: re 2🤣

**Comment by ipcjs** [comment]
@sxjzycwcy biliplus的api限制，只能从season_id查询到页面信息。
如果你的自定义代理服务器支持代理api.bilibili.com，最新版会优先用自定义代理服务器查询页面信息了
