### ISSUE TITLE
bili.tuturu.top被不断风控，不要再用了

### ISSUE THREAD

**Issue by AisukaYuki** [ipcjs/bilibili-helper#743]
@ipcjs 我的服务器已经被风控，换ip活不过一天。暂时先关闭了，从帮助里撤掉吧。

**Comment by ipcjs** [comment]
阿B的那个404么？访问量达到多少就会404呀？

**Comment by miyouzi** [comment]
> 阿B的那个404么？访问量达到多少就会404呀？

@ipcjs 台湾最近风控的很紧，根据搭建漫游服务器群友反馈当请求下来了后又很快恢复，有点 “强制冷却” 的意思，开放的解析服务端使用缓存越来越有必要了。

据反馈，台湾请求 1 小时内 1k 请求可能被风控（可能不足 1k）

**Comment by AisukaYuki** [comment]
@ipcjs 解析被拦截412，确实是有冷却，短时间内请求过高会被风控。目需要在服务器端根据epid做缓存，我的服务器pv算几个里面大的了。被风控到基本没法用。

**Comment by AisukaYuki** [comment]
@ipcjs 复活了可以加回去了
