### ISSUE TITLE
如何授权自定义服务器使用b站账号

### ISSUE THREAD

**Issue by Matrix-J-H** [ipcjs/bilibili-helper#749]
我使用阿里云函数计算，在开通了大会员后，估计是因为没授权账户，无法观看新番第一集以外的内容。

点击了参数设置页面的账号“授权链接”链接只弹出了一个网页，内容是这个图：
![image](https://user-images.githubusercontent.com/33464122/105073876-8c87f980-5a7f-11eb-88bf-3238b2d36e36.png)

网页的连接是： https://www.mcbbs.net/template/mcbbs/image/special_photo_bg.png?access_key=为保密不展示&mid=为保密不展示&uname=为保密不展示&sign=01c800ca2e46a0fe5d8c314a2a9f8f0f

除此之外一点反应也没有，我记得之前用会弹出一个窗口，叫我把该网页的地址复制进去，然而现在不会再有这个窗口弹出。
实际测试也是发现并未授权我的b站账号至我的阿里云函数计算服务器。
请教各位大佬应该如何解决。

**Comment by Matrix-J-H** [comment]
是不是应该 @ipcjs

**Comment by vectorsss** [comment]
> 实际测试也是发现并未授权我的b站账号至我的阿里云函数计算服务器。
> 请教各位大佬应该如何解决。

请问解决了吗？我目前也是一样的问题

**Comment by Matrix-J-H** [comment]
> > 实际测试也是发现并未授权我的b站账号至我的阿里云函数计算服务器。
> > 请教各位大佬应该如何解决。
> 
> 请问解决了吗？我目前也是一样的问题

诶，我大会员也过期了，不在乎了 lmao
