### ISSUE TITLE
看不了国家队

### ISSUE THREAD

**Issue by cpcppcpcp** [ipcjs/bilibili-helper#75]
## 描述

突然看不了番了
## 日志
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183801
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"grahard","isLogin":true,"level":4,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183801,"last_ep_index":"3","last_time":0}}}
log: Redirected request: bangumi playurl ->  https://biliplus.ipcjs.win/BPplayurl.php?cid=30670211|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=f6cf78bfc546165f169fe2322efa0105
log: balh_server  =>  https://www.biliplus.com
log: balh_mode  =>  default
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：版本 63.0.3239.132（正式版本） （64 位
2. 国家/地区：中国大陆

**Comment by ipcjs** [comment]
后台崩了，等。

**Comment by Nullizer** [comment]
后台开源吗？有无自己搭建的方法？ @ipcjs
