### ISSUE TITLE
手机端可以用的代理服务器在网页端无法使用

### ISSUE THREAD

**Issue by fly-pigeon** [ipcjs/bilibili-helper#751]
脚本问题：@ipcjs

## 描述
自己在https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8上选的一个代理服务器
service-fi0gz11m-1252917345.hk.apigw.tencentcs.com
手机端可以正常使用，但是到了电脑端，在加了http://复制过去之后，无法测速
而且更换upon服务器时提示“保存出错”
在观看巨人第四季时，选集右上角出现“受限”提示
播放界面也变成了“非常抱歉，本视频可能由于以下原因导致无法正常播放...”

希望大大能帮忙解决一下

- 问题网址：
https://www.bilibili.com/bangumi/play/ep380159

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by AisukaYuki** [comment]
要https://

**Comment by fly-pigeon** [comment]
> 要https：//

我已经加了，而且，我发现用这个代理服务器看大陆的番也会出现“非常抱歉...”

**Comment by fly-pigeon** [comment]
> 要https：//

找到原因了，是和一个叫B站港澳台的插件冲突了，删了就好了

**Comment by fly-pigeon** [comment]
已经解决了，打扰了
