### ISSUE TITLE
阿里云反代电影只能显示六分钟

### ISSUE THREAD

**Issue by Persdre** [ipcjs/bilibili-helper#752]
试了提供的链接还有我自己搭的链接，进度条只有六分钟

**Comment by Matrix-J-H** [comment]
你开了大会员是吧，应该是账号没授权给服务器，我也有这样的问题，但不知道怎么解决。试了设置的账号授权也没用。

**Comment by Persdre** [comment]
> 你开了大会员是吧，应该是账号没授权给服务器，我也有这样的问题，但不知道怎么解决。试了设置的账号授权也没用。

嗯我开了，前几天还好好的啊

**Comment by Persdre** [comment]
问题已经解决
steps:
1. 降级到8.1.0
2. 重新授权

**Comment by ipcjs** [comment]
最新版不行吗？

**Comment by Persdre** [comment]
是的，最新版的问题是太慢了

**Comment by ipcjs** [comment]
🤔，日志发上来看看

**Comment by Persdre** [comment]
> 🤔，日志发上来看看
问题应该是出现在我的网速吧，我换了个网速好的地方最新版就可以用了
