### ISSUE TITLE
Mozilla Firefox + TamperMonkey无法运行脚本，B站电影无法观看

### ISSUE THREAD

**Issue by zhenzhongluo** [ipcjs/bilibili-helper#755]
脚本问题：@ipcjs

## 描述

Mozilla Firefox已经是最新版本了，装了“解除B站区域限制” version 8.1.1，用Tampermonkey装的，
B站所有电影都打不开，都说“非常抱歉，根据版权方要求，您所在的地区无法观看本片”。

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Mozilla Firefox, 85.0 (64-bit)
2. 国家/地区：美利坚合众国, Virginia

**Comment by zhenzhongluo** [comment]
为什么没有反馈一下我这个问题，火狐和脚本都是最新的了，依然无法使用，cookie也清理过了，已经过了快两个月了都用不了

**Comment by 7pwolf** [comment]
你仔细看作者greasyfork主页就知道了

**Comment by zhenzhongluo** [comment]
OK， 我用之前发的贴继续提问，因为是同一个问题。

通过使用 
“阿里云函数” 
区域：大陆 
网址：https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/

早段时间基本上可以观看大部分电影。
但是最近又不行了。几乎全部电影都不能看。

说MEDIA SEGMENT 下载错误。。

提问：
1. 为什么之前有部分电影能看，有部分不能看呢？
2. 为什么现在全部不能看呢？

其他域名都试过了，都不能用。只有上面那个之前能用。。
