### ISSUE TITLE
B站区域限制解除插件失效

### ISSUE THREAD

**Issue by wang911xy** [ipcjs/bilibili-helper#76]
## 描述

疑似服务器崩溃，刷新了好几次，换个服务器都没效果
服务器测速：https://biliplus.ipcjs.win:
	初次连接：30372ms
	复用连接：30118ms

## 日志
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183801
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"天之逆子","isLogin":true,"level":5,"vipType":1,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183801,"last_ep_index":"3","last_time":1}}}
log: setAreaLimitSeason ep183801 true
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=30670211|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=20d7229087c45ddce8daec51398f86a8
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by tearslee** [comment]
![插件截图](http://ov4eoci9y.bkt.clouddn.com/18-2-4/42394744.jpg)
![访问代理服务器截图](http://ov4eoci9y.bkt.clouddn.com/18-2-4/48586755.jpg)
浏览器是chrome  63.0.3239.132（正式版本） （64 位）
地区是中国四川
