### ISSUE TITLE
反代服务器问题

### ISSUE THREAD

**Issue by cool-delete** [ipcjs/bilibili-helper#760]
利用已有的机场

直接在本地跑一个服务器 拿到我的账号后利用机场的服务器去拿到解析地址返回可以吗

**Comment by ipcjs** [comment]
自定义代理服务器添，https://api.bilibili.com
然后让这个地址走代理，理论上来说应该可以

**Comment by cool-delete** [comment]
@ipcjs 不太理解 我试了一下
用switchOmega添加了https://api.bilibili.com走sock5代理
然后插件的自定义服务器填写https://api.bilibili.com 
弹窗提示 {"code":-10403,"message":"抱歉您所在地区不可观看！"}

**Comment by ipcjs** [comment]
看下请求的Remote Address，有没有变成本地代理的地址
![ScreenClip](https://user-images.githubusercontent.com/4396864/106608492-6c882800-659f-11eb-8cb5-9d838b684d9e.png)

**Comment by cool-delete** [comment]
> 看下请求的Remote Address，有没有变成本地代理的地址
> ![ScreenClip](https://user-images.githubusercontent.com/4396864/106608492-6c882800-659f-11eb-8cb5-9d838b684d9e.png)

不是的 显示110.43.33.147:443

**Comment by cool-delete** [comment]
![image](https://user-images.githubusercontent.com/13638610/106613160-dc4ce180-65a4-11eb-82ff-6cf9c8e56027.png)




> 看下请求的Remote Address，有没有变成本地代理的地址
> ![ScreenClip](https://user-images.githubusercontent.com/4396864/106608492-6c882800-659f-11eb-8cb5-9d838b684d9e.png)

**Comment by ipcjs** [comment]
那你SwitchOmega没配成功
记得选`域名通配符`，填`api.bilibili.com`，其他匹配模式在chrome下不支持

**Comment by cool-delete** [comment]
> 那你SwitchOmega没配成功
> 记得选`域名通配符`，填`api.bilibili.com`，其他匹配模式在chrome下不支持

![image](https://user-images.githubusercontent.com/13638610/106614900-d6f09680-65a6-11eb-866c-031496091137.png)
![image](https://user-images.githubusercontent.com/13638610/106615276-3f3f7800-65a7-11eb-9536-5429cf115d09.png)

**Comment by cool-delete** [comment]
> 那你SwitchOmega没配成功
> 记得选`域名通配符`，填`api.bilibili.com`，其他匹配模式在chrome下不支持

![image](https://user-images.githubusercontent.com/13638610/106615976-f936e400-65a7-11eb-807c-3467617d0911.png)
已经是127了 但是代码code还是10403

**Comment by ipcjs** [comment]
那可能是你代理不是台湾的？

**Comment by cool-delete** [comment]
> 那可能是你代理不是台湾的？

有可能 我用v2varyN 新版本后路有规则不是搞得很懂
log显示
`2021/02/03 01:10:55 tcp:127.0.0.1:8032 accepted tcp:api.bilibili.com:443 [direct] `
可能是由于默认了国内不翻墙吧 我就想知道 你这样设api.bilibili.com走sock代理后 真的能解析地址么 我看其他issue讨论是要跑一个py的脚本的 里面填入v2暴露的socket地址才行

**Comment by ipcjs** [comment]
理论上来说，可以

**Comment by cool-delete** [comment]
> 理论上来说，可以
`2021/02/03 02:05:25 tcp:127.0.0.1:11399 accepted tcp:ip111.cn:80 [proxy] `
我把一些国内测ip的域名放到路由规则后了 测出来是香港地区 
`2021/02/03 02:12:53 tcp:127.0.0.1:11821 accepted tcp:api.bilibili.com:443 [proxy] `
所以我想api.bilibili.com应该也是能查到我在香港的啊 但目前来说还是10403

**Comment by cool-delete** [comment]
我看你issue里面有人给出的方法 为什么他这个要跑脚本呢
 https://github.com/ipcjs/bilibili-helper/issues/710#issuecomment-751456367_
