### ISSUE TITLE
能不能添加多个自定义地址啊，海外的需要国内的也需要港澳台的，一个自定义地址不是很够用

### ISSUE THREAD

**Issue by ohtfbbxy33** [ipcjs/bilibili-helper#761]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by cool-delete** [comment]
自定义服务器的填写区域有历史记录功能的 虽然没法备注就是了

**Comment by wailliam-x** [comment]
请问你国内的怎么设置的，我也在海外，但是我按照写的设置了只能看港澳台，国内的还是不能看
