### ISSUE TITLE
## 拉取视频地址失败 原因: {}

### ISSUE THREAD

**Issue by jingming295** [ipcjs/bilibili-helper#764]
脚本问题：@ipcjs

## 描述

今天更新脚本后，阿里云函数计算就不能用了，尝试了其他服务器也不行
- 问题网址：

## 日志

<details>
<summary>debug: atRun: -1, loading
debug: [解除B站区域限制 v8.1.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep41309
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery  -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
debug: /x/web-interface/nav {"uname":"铭铭280","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"铭铭280","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Chrome 版本 88.0.4324.104
2. 国家/地区：Malaysia

**Comment by timi137137** [comment]
问题一致，经过XHR抓包发现playurl返回-10403地区封锁。

**Comment by timi137137** [comment]
降级脚本至8.1.0后可恢复正常，建议检查最新合并的PR代码中是否与php有冲突？

**Comment by ipcjs** [comment]
😵，我看下

**Comment by ipcjs** [comment]
看来是代码里变量名让人迷惑的锅（

**Comment by jianfei96** [comment]
同

**Comment by arimitx** [comment]
@ipcjs 是不是匹配地区的时候出错了，好像默认匹配到台湾区了。我填写了大陆和台湾的解析，结果大陆地区番剧也用的台湾代理。

**Comment by ipcjs** [comment]
修了，试下。

**Comment by arimitx** [comment]
@ipcjs 不行，判断逻辑不能写成先判断首选再按地区判断这种。自定义（首选服务器）解析失败后（比如地区不匹配），就直接返回error code了，不会进入第二阶段分地区判断；自定义（首选服务器）留空则会直接显示“非常抱歉，根据版权方要求您所在的地区无法观看本片”页面，也不会进入第二阶段解析。

**Comment by arimitx** [comment]
> @ipcjs 不行，判断逻辑不能写成先判断首选再按地区判断这种。自定义（首选服务器）解析失败后（比如地区不匹配），就直接返回error code了，不会进入第二阶段分地区判断；自定义（首选服务器）留空则会直接显示“非常抱歉，根据版权方要求您所在的地区无法观看本片”页面，也不会进入第二阶段解析。

抱歉脚本更新出了点问题，8.1.3已经可以正常分区解析了。只是 自定义（首选服务器）不能留空，否则还是直接跳“非常抱歉，根据版权方要求您所在的地区无法观看本片”页面

**Comment by ipcjs** [comment]
@arimitx 不会呀，它会按顺序试的

**Comment by arimitx** [comment]
> @arimitx 不会呀，它会按顺序试的

@ipcjs 问题应该出在balh_config.server_bilibili_api_proxy这个属性上了，balh_config.server_custom为空则balh_config.server_bilibili_api_proxy也为空，然后下面的判断逻辑就不适用了。

```
if (balh_config.server_bilibili_api_proxy && !templateArgs) {
    ...                   
```
Besides，pr #762 引入的替换cdn功能有些意外收获，港澳台番剧使用的Akamai CDN被换为境内CDN后也能正常播放（我用的金山CDN，测试番剧[ss33866](https://www.bilibili.com/bangumi/play/ss33866)）。我在HK，不知道大陆用户开启替换CDN选项后是否也能正常播放港澳台番剧，如果能播放应该比直接用Akamai节点好。

但是这对境外用户又是一种困扰，因为境外用户使用Akamai节点更好，所以这里可能也需要引入额外的判断条件。@johnmave126 

```
if (!window.__balh_app_only__ && balh_config.upos_server) {
    ...
```

**Comment by johnmave126** [comment]
> 但是这对境外用户又是一种困扰，因为境外用户使用Akamai节点更好，所以这里可能也需要引入额外的判断条件。@johnmave126
> 
> ```
> if (!window.__balh_app_only__ && balh_config.upos_server) {
>     ...
> ```
@arimitx 有点没懂什么意思，是要根据已匹配的地区自动override用户的upos替换选择吗?还是说在没有手动选择upos的时候，根据匹配的地区选择一个比较合适的默认upos?

**Comment by arimitx** [comment]
> > 但是这对境外用户又是一种困扰，因为境外用户使用Akamai节点更好，所以这里可能也需要引入额外的判断条件。@johnmave126
> > ```
> > if (!window.__balh_app_only__ && balh_config.upos_server) {
> >     ...
> > ```
> 
> @arimitx 有点没懂什么意思，是要根据已匹配的地区自动override用户的upos替换选择吗?还是说在没有手动选择upos的时候，根据匹配的地区选择一个比较合适的默认upos?

@johnmave126 意思就是对于**境外**用户，访问**境外地区限定**的动画，走Akamai应该比走境内CDN好。感觉自定义upos只对大陆区动画生效会不会更好一点？

**Comment by arimitx** [comment]
> > > 但是这对境外用户又是一种困扰，因为境外用户使用Akamai节点更好，所以这里可能也需要引入额外的判断条件。@johnmave126
> > > ```
> > > if (!window.__balh_app_only__ && balh_config.upos_server) {
> > >     ...
> > > ```
> > 
> > 
> > @arimitx 有点没懂什么意思，是要根据已匹配的地区自动override用户的upos替换选择吗?还是说在没有手动选择upos的时候，根据匹配的地区选择一个比较合适的默认upos?
> 
> @johnmave126 意思就是对于**境外**用户，访问**境外地区限定**的动画，走Akamai应该比走境内CDN好。感觉自定义upos只对大陆区动画生效会不会更好一点？

只对大陆区动画生效也不太好。。因为大陆用户也可以改CDN来加速境外动画访问，这里逻辑感觉不好设定，，

**Comment by johnmave126** [comment]
> 只对大陆区动画生效也不太好。。因为大陆用户也可以改CDN来加速境外动画访问，这里逻辑感觉不好设定，，

所以目前让用户自行选择upos是不是坠吼的...

**Comment by ryd994** [comment]
> 所以目前让用户自行选择upos是不是坠吼的.

问题是upos选不出Akamai啊

**Comment by arimitx** [comment]
> > 所以目前让用户自行选择upos是不是坠吼的.
> 
> 问题是upos选不出Akamai啊

akamai的upos实际上有，但是目录里没添加。不过不建议全部换akamai，大陆区番剧走akamai会403。

**Comment by johnmave126** [comment]
我之前是没改目录来着...倒是也可以把支持的upos都加上

**Comment by xmoiduts** [comment]
海外用户，几天前开始出现国内番剧加载不出来的情况，播放器界面黑屏并循环输出“拉取视频地址”等log。配置了“替换cdn”后番剧恢复可访问性。

**Comment by timi137137** [comment]
> 海外用户，几天前开始出现国内番剧加载不出来的情况，播放器界面黑屏并循环输出“拉取视频地址”等log。配置了“替换cdn”后番剧恢复可访问性。

@xmoiduts 这是因为有时候部分海外CDN不会同步番剧的原因，这个可能你需要手动切换upos服务器或者看看别的办法。这里指的番剧是指地区限制番剧
