### ISSUE TITLE
## 拉取视频地址失败 原因: 代理服务器临时不可用

### ISSUE THREAD

**Issue by qiyuanshijie** [ipcjs/bilibili-helper#768]
脚本问题：@ipcjs

## 描述

观看最新的一月港澳台地区的新番时，重新设置了全部的香港、台湾、泰国的公共服务器，以及自己在阿里云搭建的服务器，全部都有# 拉取视频地址失败 原因: 代理服务器临时不可用   {"code":-10403,"message":"抱歉您已被封锁"}这个错误
另外，根据测试地址的观察，其中提供成功率反馈的地址都出现了明显的成功率下降
- 问题网址：https://www.bilibili.com/bangumi/play/ss37783

## 日志

<details>
<summary>Verbose 日志</summary>

```
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.1.6 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss37783
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org?cid=285831739&qn=120&type=&otype=json&fourk=1&bvid=BV1e54y1s7Y6&ep_id=380810&fnver=0&fnval=80&session=8212446eef298c19813a874900e922a1&module=bangumi&access_key=f677fbf881033ab0fb6f4d8e44a22321
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"焱锬焱","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"焱锬焱","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?cid=285831739&qn=120&type=&otype=json&fourk=1&bvid=BV1e54y1s7Y6&ep_id=380810&fnver=0&fnval=80&session=8212446eef298c19813a874900e922a1&module=bangumi&access_key=f677fbf881033ab0fb6f4d8e44a22321
info: player msg: 代理服务器临时不可用
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org?avid=undefined&cid=285831739&bvid=BV1e54y1s7Y6&qn=120&type=&otype=json&ep_id=380810&fourk=1&fnver=0&fnval=80&session=16c6be543432a4827a956fc8b7885a54&module=bangumi&balh_ajax=1&access_key=f677fbf881033ab0fb6f4d8e44a22321
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=285831739&bvid=BV1e54y1s7Y6&qn=120&type=&otype=json&ep_id=380810&fourk=1&fnver=0&fnval=80&session=16c6be543432a4827a956fc8b7885a54&module=bangumi&balh_ajax=1&access_key=f677fbf881033ab0fb6f4d8e44a22321
info: player msg: 代理服务器临时不可用
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：chrome 88.0
2. 国家/地区：中国

**Comment by seeroffish** [comment]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.1.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss37759#380281
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: bos flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org?cid=293216268&qn=80&type=&otype=json&fourk=1&bvid=BV18y4y1Y7ds&ep_id=380281&fnver=0&fnval=80&session=f6b7e75ff5a438cf97ca0f4e897aa7f5&module=bangumi&access_key=deb46128ccf75e963c43febfdc9892c1
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"Little人鱼","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?cid=293216268&qn=80&type=&otype=json&fourk=1&bvid=BV18y4y1Y7ds&ep_id=380281&fnver=0&fnval=80&session=f6b7e75ff5a438cf97ca0f4e897aa7f5&module=bangumi&access_key=deb46128ccf75e963c43febfdc9892c1
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?cid=293216268&qn=80&type=&otype=json&fourk=1&bvid=BV18y4y1Y7ds&ep_id=380281&fnver=0&fnval=80&session=f6b7e75ff5a438cf97ca0f4e897aa7f5&module=bangumi&access_key=deb46128ccf75e963c43febfdc9892c1
debug: /x/web-interface/nav {"uname":"Little人鱼","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=293216268&bvid=BV18y4y1Y7ds&qn=80&type=&otype=json&ep_id=380281&fourk=1&fnver=0&fnval=80&session=65f2f02728310810ec5a2419baddc00f&module=bangumi&balh_ajax=1&access_key=deb46128ccf75e963c43febfdc9892c1
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=293216268&bvid=BV18y4y1Y7ds&qn=80&type=&otype=json&ep_id=380281&fourk=1&fnver=0&fnval=80&session=65f2f02728310810ec5a2419baddc00f&module=bangumi&balh_ajax=1&access_key=deb46128ccf75e963c43febfdc9892c1
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org?avid=undefined&cid=293216268&bvid=BV18y4y1Y7ds&qn=80&type=&otype=json&ep_id=380281&fourk=1&fnver=0&fnval=80&session=65f2f02728310810ec5a2419baddc00f&module=bangumi&balh_ajax=1&access_key=deb46128ccf75e963c43febfdc9892c1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
