### ISSUE TITLE
问个有点白痴的问题

### ISSUE THREAD

**Issue by gittohabo** [ipcjs/bilibili-helper#770]
今天想看个港澳台才发现打开什么都地区限制了，搞得我以为没开脚本。上来看才知道服务器不能用了，要自己搞了。
好在，作者留了教程，看着来搞感觉应该没问题。
然后第一步就卡住了。
设置界面怎么打开？对，就下面这个界面
![image](https://user-images.githubusercontent.com/50357956/107843472-487ddf80-6e06-11eb-94f1-d877ffadf479.png)
我的去广告插件关掉了，别的脚本关掉了，也找不到任何按钮，如下
![image](https://user-images.githubusercontent.com/50357956/107843557-2173dd80-6e07-11eb-8669-c975612341c5.png)

还是说我点错了啥……

1. 浏览器版本：chrome 88.0.4324.150
2. 国家/地区：CN

**Comment by miyouzi** [comment]
你进番剧介绍页，比如你点一下你上面那个页面的封面或者标题，有个土星的按钮

**Comment by gittohabo** [comment]
> 你进番剧介绍页，比如你点一下你上面那个页面的封面或者标题，有个土星的按钮

看到了，非常感谢！
