### ISSUE TITLE
Firefox 68.12.0esr上，使用8.1.5能在页面上看到土星图标，升级到8.1.8后消失

### ISSUE THREAD

**Issue by hugohehuan** [ipcjs/bilibili-helper#771]
## 描述
8.1.5能在页面上看到土星图标，升级到8.1.8后消失
叉子网站上也回退不了旧版本，404 Not Found，做不了对比了……

## 日志
只有控制台的……
第一部分
> Syntax error @ "解除B站区域限制"!
> ##########################
> JSHINT output:
> ##########################
> 
> F_a/T</<@eval:3:100
> N@eval:2:148
> E_u/<@eval:3:274
> Ka@eval line 1 > Function:61:375
> create@eval line 1 > Function:73:235
> run@eval line 1 > Function:12:325
> anonymous/</</<@eval line 1 > Function:74:505
> F_a/T</<@eval:3:100
> N@eval:2:148
> anonymous/</<@eval line 1 > Function:74:486
> anonymous/<@eval line 1 > Function:74:515
> TM_back@eval line 1 > Function:75:3
> anonymous@eval line 1 > Function:75:10
> F_a/T</<@eval:3:100
> exec_fn@eval:1:155
> @eval:12:470
> Aa@eval:11:177
>     Ka eval line 1 > Function:62
>     syntaxCheck eval line 1 > Function:22
>     Wa eval:11
>     Aa eval:11

第二部分
> SyntaxError: invalid identity escape in regular expression eval:1:14
>     T eval:3
>     N eval:2
>     E_u eval:3
>     Ka eval line 1 > Function:61
>     create eval line 1 > Function:73
>     run eval line 1 > Function:12
>     anonymous eval line 1 > Function:74
>     forEach self-hosted:266
>     T eval:3
>     N eval:2
>     anonymous eval line 1 > Function:74
>     anonymous eval line 1 > Function:74
>     TM_back eval line 1 > Function:75
>     anonymous eval line 1 > Function:75
>     T eval:3
>     exec_fn eval:1
>     <anonymous> eval:12
>     Aa eval:11
>     send moz-extension://42e42ec3-04d8-4bb5-b73b-ce4bacd8107a/content.js:7
>     next moz-extension://42e42ec3-04d8-4bb5-b73b-ce4bacd8107a/content.js:12
>     <anonymous> moz-extension://42e42ec3-04d8-4bb5-b73b-ce4bacd8107a/content.js:28
>     q moz-extension://42e42ec3-04d8-4bb5-b73b-ce4bacd8107a/content.js:25
>     apply self-hosted:4417
>     applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:588
>     applySafeWithoutClone self-hosted:1007
>     wrapPromise resource://gre/modules/ExtensionCommon.jsm:801

![图片](https://user-images.githubusercontent.com/10740498/107887337-651e3280-6f40-11eb-9ae9-c08643b545bf.png)

## 其他

1. 浏览器版本：Firefox 68.12.0esr
2. 猴子：TamperMonkey 4.11.6120
3. 国家/地区：China Mainland

**Comment by ipcjs** [comment]
最新版不都80+吗？你的怎么还是68.12.0？

应该是老版不支持匹配中文的正则导致的：https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/src/feature/r.ts#L55

**Comment by qbdiamond** [comment]
71.0
8.15能用，8.16就不行了

**Comment by ipcjs** [comment]
为啥不升级到最新版？

**Comment by hugohehuan** [comment]
> 
> 
> 最新版不都80+吗？你的怎么还是68.12.0？
> 
> 应该是老版不支持匹配中文的正则导致的：https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/src/feature/r.ts#L55

多谢大大，把这一行改回去果然就好了
不用最新的原因是ESR稳定，68也是最后一个Mactype能用的大版本了
