### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-10403,"message":"抱歉您所在地区不可观看

### ISSUE THREAD

**Issue by wailliam-x** [ipcjs/bilibili-helper#773]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：edge版本 88.0.705.74
2. 国家/地区： 日本

**Comment by wailliam-x** [comment]
有人吗  没人帮忙解答一下吗

**Comment by miyouzi** [comment]
你把 Log 补上吧
