### ISSUE TITLE
脚本无法加载视频图像

### ISSUE THREAD

**Issue by jingyuexing** [ipcjs/bilibili-helper#774]
脚本问题：@ipcjs

## 描述

当脚本启动时，视频只有音频而没有图像,当脚本关闭，重新刷新页面即可看到图像
脚本版本为:7.9.8
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：火狐：85.0
2. 国家/地区：

**Comment by jingyuexing** [comment]
正常页面上的视频无法加载图像,而非番剧

**Comment by miyouzi** [comment]
当前脚本版本最新为 8.1.8
