### ISSUE TITLE
泰区解析未正常工作，解析服务器在漫游模块运行正常

### ISSUE THREAD

**Issue by Merlyx** [ipcjs/bilibili-helper#775]
脚本问题：@ipcjs

## 描述
泰区解析未正常工作，解析服务器在漫游模块运行正常
已检查非跨域问题

- 问题网址：https://www.bilibili.com/bangumi/play/ep347666

## 日志

<details>
<summary>Verbose 日志</summary>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.1.8 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep347666
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=347666
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"xx","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://b1a8064d31c64eaaac10e7fb720d2f65.apig.ap-southeast-2.huaweicloudapis.com/br-thai?access_key=服务端替换&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=247331024&device=android&ep_id=347666&fnval=0&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=112&track_path=0&ts=1613986787&sign=c3224fe603c3c375c6c5f369a9cc87be
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://b1a8064d31c64eaaac10e7fb720d2f65.apig.ap-southeast-2.huaweicloudapis.com/br-thai?access_key=服务端替换&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=247331024&device=android&ep_id=347666&fnval=0&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=112&track_path=0&ts=1613986790&sign=e9eb4a6128957d4943af0c65966095e5
debug: /x/web-interface/nav {"uname":"xx","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"xx","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/player/v2 404 {"code":-404,"message":"啥都木有","ttl":1}
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.bilibili.com/x/v2/dm/view?oid=247331024&aid=927535296&bvid=BV15T4y1F7W8&season_id=35044&ep_id=347666&type=1
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://b1a8064d31c64eaaac10e7fb720d2f65.apig.ap-southeast-2.huaweicloudapis.com/br-thai/intl/gateway/v2/app/subtitle?oid=247331024&aid=927535296&bvid=BV15T4y1F7W8&season_id=35044&ep_id=347666&type=1
debug: /x/player/v2 rebuild {"code":0,"message":"啥都木有","ttl":1,"data":{"subtitle":{"lan":"","lan_doc":"","subtitles":[{"id":55051,"id_str":"55051","lan":"th","lan_doc":"ภาษาไทย","subtitle_url":"//i0.hdslb.com/bfs/intl-ogv-subtitle/db8e45af271b418b45ef28943854b1dfb00a2a78.json"},{"id":31941,"id_str":"31941","lan":"zh-Hans","lan_doc":"中文（简体）","subtitle_url":"//i0.hdslb.com/bfs/intl-ogv-subtitle/d233180d1b50e5f3a149d09df7d4089a07777c8f.json"},{"id":1952,"id_str":"1952","lan":"zh-Hant","lan_doc":"中文（繁体）","subtitle_url":"//i0.hdslb.com/bfs/intl-ogv-subtitle/90c64540811372527ebedef5e6f07bbdd1964631.json"}],"allow_submit":false}}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Edg/88.0.705.74
</details>

## 其他

1. 浏览器版本：edge 88.0.705.74
2. 国家/地区：cn

**Comment by Merlyx** [comment]
https://b1a8064d31c64eaaac10e7fb720d2f65.apig.ap-southeast-2.huaweicloudapis.com/br-thai

**Comment by miyouzi** [comment]
B站数据改动了，等更新吧

**Comment by Merlyx** [comment]
> B站数据改动了，等更新吧

辛苦大佬了，不过出包王女似乎字幕没有加载出来
link
https://www.bilibili.com/bangumi/play/ep372478

**Comment by miyouzi** [comment]
> > B站数据改动了，等更新吧
> 
> 辛苦大佬了，不过出包王女似乎字幕没有加载出来
> link
> https://www.bilibili.com/bangumi/play/ep372478

神奇，出包这部番 ```api.bilibili.com/x/player/v2``` 接口有返回数据（里面字幕为空），所以没有触发字幕补全（像巨人会返回404就可以触发）……

（这番有港澳台版？）

![image](https://user-images.githubusercontent.com/24269465/108933077-77594880-7685-11eb-817e-0b10812c5fac.png)

**Comment by Merlyx** [comment]
> > > B站数据改动了，等更新吧
> > 
> > 
> > 辛苦大佬了，不过出包王女似乎字幕没有加载出来
> > link
> > https://www.bilibili.com/bangumi/play/ep372478
> 
> 神奇，出包这部番 `api.bilibili.com/x/player/v2` 接口有返回数据（里面字幕为空），所以没有触发字幕补全（像巨人会返回404就可以触发）……
> 
> （这番有港澳台版？）
> 
> ![image](https://user-images.githubusercontent.com/24269465/108933077-77594880-7685-11eb-817e-0b10812c5fac.png)

说不准吧，像是东南亚下架的school days我拿参数请求也能得到

**Comment by Merlyx** [comment]
> > > B站数据改动了，等更新吧
> > 
> > 
> > 辛苦大佬了，不过出包王女似乎字幕没有加载出来
> > link
> > https://www.bilibili.com/bangumi/play/ep372478
> 
> 神奇，出包这部番 `api.bilibili.com/x/player/v2` 接口有返回数据（里面字幕为空），所以没有触发字幕补全（像巨人会返回404就可以触发）……
> 
> （这番有港澳台版？）
> 
> ![image](https://user-images.githubusercontent.com/24269465/108933077-77594880-7685-11eb-817e-0b10812c5fac.png)

说不准吧，像是东南亚下架的school days我拿参数请 求也能得到播放地址....
