### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

### ISSUE THREAD

**Issue by LYF-hub** [ipcjs/bilibili-helper#779]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.1.11 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss35495/?from=search&seid=6958696600716049009
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 2
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://hd.pilipili.com/pgc/player/web/playurl?cid=274533729&qn=0&type=&otype=json&fourk=1&bvid=BV1rK411g7zs&ep_id=376368&fnver=0&fnval=80&session=2dbe1bb4425770f21a149932c14ef008&module=bangumi&access_key=ce22fd373967662e2cacd1dff3cd5121
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://hd.bilibili.com/pgc/player/web/playurl?cid=274533729&qn=0&type=&otype=json&fourk=1&bvid=BV1rK411g7zs&ep_id=376368&fnver=0&fnval=80&session=2dbe1bb4425770f21a149932c14ef008&module=bangumi&access_key=ce22fd373967662e2cacd1dff3cd5121
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"poe0909","isLogin":true,"level":0,"vipType":0,"vipStatus":0,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 2
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://hd.pilipili.com/pgc/player/web/playurl?avid=undefined&cid=274533729&bvid=BV1rK411g7zs&qn=0&type=&otype=json&ep_id=376368&fourk=1&fnver=0&fnval=80&session=a04249744f3f7ac9ef4c1f24d5f19f77&module=bangumi&balh_ajax=1&access_key=ce22fd373967662e2cacd1dff3cd5121
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://hd.bilibili.com/pgc/player/web/playurl?avid=undefined&cid=274533729&bvid=BV1rK411g7zs&qn=0&type=&otype=json&ep_id=376368&fourk=1&fnver=0&fnval=80&session=a04249744f3f7ac9ef4c1f24d5f19f77&module=bangumi&balh_ajax=1&access_key=ce22fd373967662e2cacd1dff3cd5121
debug: /x/web-interface/nav {"uname":"poe0909","isLogin":true,"level":0,"vipType":0,"vipStatus":0,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36

**Comment by miyouzi** [comment]
服务器配置不对，请找可用的服务器或者自建。
