### ISSUE TITLE
番剧出差转到bv页面会提示视频不见了

### ISSUE THREAD

**Issue by cmmdwl** [ipcjs/bilibili-helper#787]
https://space.bilibili.com/11783021
https://www.bilibili.com/video/BV1y54y1a7fw
https://www.bilibili.com/bangumi/play/ss37762
可能需要在bv页面也启用

**Comment by Energy0124** [comment]
香港地區在這兩個頁面會顯示
"非常抱歉，根据版权方要求
您所在的地区无法观看本片"
看來這些頁面也要啟用
https://www.bilibili.com/bangumi/play/ss38214
https://www.bilibili.com/blackboard/topic/activity-JDsQFzS78v.html

**Comment by ahytanaka** [comment]
这个问题，建议您去搜bv转av脚本，配合在av页面启用
