### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

### ISSUE THREAD

**Issue by Mengzx88** [ipcjs/bilibili-helper#799]
脚本问题：@ipcjs

## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}
![QQ截图20210405172109](https://user-images.githubusercontent.com/27806444/113560579-c788da80-9635-11eb-831b-17bfa824115f.png)
这个是网站的设置
![QQ截图20210405172520](https://user-images.githubusercontent.com/27806444/113560875-4bdb5d80-9636-11eb-96e3-512289be93bd.png)

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.1.12 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep96708
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: undefined
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: atRun: 2, complete
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://自建服务器/?cid=11571816&qn=116&type=&otype=json&fourk=1&bvid=BV1xs411x7wo&ep_id=96708&fnver=0&fnval=80&session=336137f76d9f9840b8473b7da4eea656&module=bangumi&access_key=21042223c9bb5c2aa1ab16c8f917a041
debug: /x/web-interface/nav {"uname":"俺的名字","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"俺的名字","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://自建服务器/?avid=undefined&cid=11571816&bvid=BV1xs411x7wo&qn=116&type=&otype=json&ep_id=96708&fourk=1&fnver=0&fnval=80&session=6ef2f30505450706b58d0699e2bbc984&module=bangumi&balh_ajax=1&access_key=21042223c9bb5c2aa1ab16c8f917a041
debug: userAgent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by miyouzi** [comment]
你配置域名填啥？ `https://自建服务器` ？

**Comment by Winter-of-Cirno** [comment]
不会是服务器被BAN了吧？挂代理试试

**Comment by ztyzbb** [comment]
我这一样的错误，F12可以看到被CORS了，疑似跨域配置问题

**Comment by interestingLSY** [comment]
似乎确实是跨域配置的问题

```plain
已拦截跨源请求：同源策略禁止读取位于 https://...... 的远程资源。（原因：CORS 请求未能成功）。
```

**Comment by quanljh** [comment]
有解决的办法吗？

**Comment by rbbjgfk** [comment]
> 有解决的办法吗？

很神奇，edge不行，但是chrome可以。

**Comment by quanljh** [comment]
> > 有解决的办法吗？
> 
> 很神奇，edge不行，但是chrome可以。

我chrome 也不行。

**Comment by ztyzbb** [comment]
正确地配置跨域就行了呀，Nginx、httpd怎么配网上还是挺多的，现在帮助文档里的几个服务器随机抽风也挺痛苦的，有时候有跨域，有时候没跨域

**Comment by quanljh** [comment]
跨域解决了，又报了这个错： 拉取视频地址失败 {"code":-10403,"message":"抱歉您所在地区不可观看！"} 。。。

**Comment by BraveSail** [comment]
> 跨域解决了，又报了这个错： 拉取视频地址失败 {"code":-10403,"message":"抱歉您所在地区不可观看！"} 。。。

你这是没走上代理

**Comment by Mengzx88** [comment]
@miyouzi 不好意思 现在才回。。 我搭建的这个 在手机插件的那个哔哩漫游上面是能用的，这个脚本的就不行

**Comment by tangyisheng2** [comment]
> 跨域解决了，又报了这个错： 拉取视频地址失败 {"code":-10403,"message":"抱歉您所在地区不可观看！"} 。。。

请问能否提供一下跨域的Nginx配置？
