### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-412,"message":"请求被拦截","ttl":1,"data":null}

### ISSUE THREAD

**Issue by syr-123** [ipcjs/bilibili-helper#806]
## 拉取视频地址失败
原因: {"code":-412,"message":"请求被拦截","ttl":1,"data":null}

日志：
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss38237/?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.15
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?cid=322641718&qn=80&type=&otype=json&fourk=1&bvid=BV12X4y1g7Eb&ep_id=399508&fnver=0&fnval=80&session=1d8fd4ed090f55ff42ea9132c31f59b5&module=bangumi&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?cid=322641718&qn=80&type=&otype=json&fourk=1&bvid=BV12X4y1g7Eb&ep_id=399508&fnver=0&fnval=80&session=1d8fd4ed090f55ff42ea9132c31f59b5&module=bangumi&area=tw&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?cid=322641718&qn=80&type=&otype=json&fourk=1&bvid=BV12X4y1g7Eb&ep_id=399508&fnver=0&fnval=80&session=1d8fd4ed090f55ff42ea9132c31f59b5&module=bangumi&area=hk&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?cid=322641718&qn=80&type=&otype=json&fourk=1&bvid=BV12X4y1g7Eb&ep_id=399508&fnver=0&fnval=80&session=1d8fd4ed090f55ff42ea9132c31f59b5&module=bangumi&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=322641718&bvid=BV12X4y1g7Eb&qn=80&type=&otype=json&ep_id=399508&fourk=1&fnver=0&fnval=80&session=1924be009e3f550d26a57b8ae06798b0&module=bangumi&balh_ajax=1&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=322641718&bvid=BV12X4y1g7Eb&qn=80&type=&otype=json&ep_id=399508&fourk=1&fnver=0&fnval=80&session=1924be009e3f550d26a57b8ae06798b0&module=bangumi&balh_ajax=1&area=tw&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=undefined&cid=322641718&bvid=BV12X4y1g7Eb&qn=80&type=&otype=json&ep_id=399508&fourk=1&fnver=0&fnval=80&session=1924be009e3f550d26a57b8ae06798b0&module=bangumi&balh_ajax=1&area=hk&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=322641718&bvid=BV12X4y1g7Eb&qn=80&type=&otype=json&ep_id=399508&fourk=1&fnver=0&fnval=80&session=1924be009e3f550d26a57b8ae06798b0&module=bangumi&balh_ajax=1&access_key=0b08d1e6f91bd32bbfb311e6e5f49c21
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

## 其他

1. 浏览器版本： 89.0.4389.114（正式版本） （64 位）
2. 国家/地区：日本

**Comment by TIE666** [comment]
Experiencing the same

**Comment by TIE666** [comment]
现在应该好了，只有刚刚一会

**Comment by syr-123** [comment]
> 现在应该好了，只有刚刚一会

orz
又不行了
