### ISSUE TITLE
wiki`自建解析服务器`中的地址`/pgc/player/api/playurl`是否写错了。

### ISSUE THREAD

**Issue by heroboy** [ipcjs/bilibili-helper#808]
应该是`/pgc/player/web/playurl`吧。

实际访问api.bilibili.com的时候用的是`web`，而不是`api`。用`api`会400错误的。

**Comment by miyouzi** [comment]
两个都有，web 是网页接口，api 是移动端接口，两个接口调用方法不同（脚本在遇到APP限定的番剧会使用移动端接口）

**Comment by heroboy** [comment]
在脚本"解除B站区域限制"中应该写清楚吧。比如，访问的时候其实不会自动加上`/pgc/player/web/playurl`这段路径的。
反复试了好几次才成功的。

**Comment by miyouzi** [comment]
你自建服务器用的是哪一个方法？

**Comment by heroboy** [comment]
腾讯云函数，还是serverless什么的，上面写了一段代码。
我搞不清楚它们底层机制是怎么样的，就写了一段expressjs的代码。
反正是免费的。
```javascript
const express = require('express')
const path = require('path')
const app = express()
const {createProxyMiddleware} = require('http-proxy-middleware');

//app.use(proxy('/bili',{HOST:'https://api.bilibili.com'}))
app.use('/',(req,resp,next)=>{
  delete req.headers['accept-encoding'];
  next();
})
app.use('/',createProxyMiddleware('/',{target:'https://api.bilibili.com',changeOrigin: true}));
// Error handler
app.use(function (err, req, res, next) {
  console.error(err)
  res.status(500).send('Internal Serverless Error')
})
//http-proxy-middleware
app.listen(8080)

module.exports = app

```

**Comment by heroboy** [comment]
才发现，我说的wiki不是这个repo。https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8
不知道哪里链接过去的。

**Comment by miyouzi** [comment]
> 才发现，我说的wiki不是这个repo。https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8
> 不知道哪里链接过去的。

这个是移动端的项目，自然给的是移动端的接口，你要找接口的话，可以去看 Nginx 反代参考 配置（包含了Web和移动端） https://github.com/ipcjs/bilibili-helper/pull/711#issue-542876230

**Comment by heroboy** [comment]
我知道了，我点了 https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6 下面的 [公共解析服务器](https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8) ， 然后右侧 [自建解析服务器](https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8)，以为是这样自建服务器呢。
