### ISSUE TITLE
播放港澳台番剧加载视频内容失败，提示：[Dash] Call getCurrentPlayUrlFor function error

### ISSUE THREAD

**Issue by tangyisheng2** [ipcjs/bilibili-helper#809]
脚本问题：@ipcjs

## 描述

可以进入番剧播放页面，但是无法播放视频。
错误提示：[Dash] Call getCurrentPlayUrlFor function error
PS. 使用自己搭建的Nginx反向代理服务器API，测试直接访问插件请求的网址可以正常解析没有错误。
- 问题网址：
https://www.bilibili.com/bangumi/play/ep398320

## 日志
因为日志里面包含access_key，因此不太方便贴出，如果开发者有需要请提供邮箱我打包发送，感谢～
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

![image](https://user-images.githubusercontent.com/16578638/114652259-1ad6e900-9d18-11eb-8a16-60414d807236.png)

## 其他

1. 浏览器版本：Google Chrome Version 89.0.4389.114 (Official Build) (x86_64) (User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36)
2. 国家/地区：中国大陆

**Comment by miyouzi** [comment]
B站dash播放器加载失败（报404有点迷惑），尝试关闭广告过滤插件（如果有），关闭 Bilibili-Evolved 脚本，更换网络环境（比如用手机热点）看看

**Comment by tangyisheng2** [comment]
> B站dash播放器加载失败（报404有点迷惑），尝试关闭广告过滤插件（如果有），关闭 Bilibili-Evolved 脚本，更换网络环境（比如用手机热点）看看

![image](https://user-images.githubusercontent.com/16578638/114661961-78743100-9d2a-11eb-83e9-a7d61982f79a.png)
排查了一下，404原因为上面这个插件Orz。
感谢～

**Comment by chenxuuu** [comment]
一样的问题，一样的解决方案，好耶！
