### ISSUE TITLE
腾讯DNS ## 拉取视频地址失败 原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

### ISSUE THREAD

**Issue by YimingSun60** [ipcjs/bilibili-helper#811]
脚本问题：@ipcjs

## 描述
用的腾讯云DNS反代理，之前都正常，昨天开始提示拉取失败。求大佬教教怎么排查问题

- 问题网址：
api.bilibili.com

## 日志

<details>
<summary>Verbose debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss28055?from=search&seid=17794197699999645271
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"古战场又摸了","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://tw.ysun.ltd/pgc/player/web/playurl?cid=98975502&qn=112&type=&otype=json&fourk=1&bvid=BV1L441157vF&ep_id=276459&fnver=0&fnval=80&session=c715f2d5091cc4e4978e789086158b58&module=bangumi&area=&access_key=970a02fa7a7a998b1a7ef67284905e41
debug: /x/web-interface/nav {"uname":"古战场又摸了","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://tw.ysun.ltd/pgc/player/web/playurl?avid=undefined&cid=98975502&bvid=BV1L441157vF&qn=112&type=&otype=json&ep_id=276459&fourk=1&fnver=0&fnval=80&session=c76919b445c12f5c4cf9ac9d2180b56b&module=bangumi&balh_ajax=1&area=&access_key=970a02fa7a7a998b1a7ef67284905e41
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Chrome
2. 国家/地区：HK

**Comment by BraveSail** [comment]
腾讯云CDN？这是节点没走对吧，建议用阿里云函数（nodejs12）搭建：
```
const qs = require('querystring');
const https = require('https');

exports.handler = (req, resp, context) => {
    var newheaders = req.headers;
    newheaders.host = 'api.bilibili.com';
    newheaders.referer='https://www.bilibili.com/';
    newheaders = 'Access-Control-Allow-Credentials';
    delete newheaders['x-forwarded-proto'];
    const option = {
    hostname: 'api.bilibili.com',
    path: '/pgc/player/web/playurl?'+qs.stringify(req.queries),
    headers: newheaders
    };
    https.get(option, (res) => {
        var data='';
        res.on("data", function(chunk) {
            data += chunk;
            });
        res.on("end", () => {
            resp.setHeader('content-type','application/json');
            for (var key in res.headers) {
                var value = res.headers[key];
                resp.setHeader(key, value);
                }
            resp.send(data);
            });
    }).on('error', (e) => {
        console.error(e);
    });
}
```
