### ISSUE TITLE
抱歉您已被封锁

### ISSUE THREAD

**Issue by 1287470518** [ipcjs/bilibili-helper#814]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep380159?from=search&seid=7884561862604388818
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: undefined
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?cid=285278943&qn=116&type=&otype=json&fourk=1&bvid=BV17p4y1W7gP&ep_id=380159&fnver=0&fnval=80&session=1972cf8d703889f553ff938a9008b560&module=bangumi
debug: /x/web-interface/nav {"uname":"蜷缩SAMA","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"蜷缩SAMA","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=undefined&cid=285278943&bvid=BV17p4y1W7gP&qn=116&type=&otype=json&ep_id=380159&fourk=1&fnver=0&fnval=80&session=bfa8a7803317d35f2de4d4b36f0fe03a&module=bangumi&balh_ajax=1&area=
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=285278943&bvid=BV17p4y1W7gP&qn=116&type=&otype=json&ep_id=380159&fourk=1&fnver=0&fnval=80&session=bfa8a7803317d35f2de4d4b36f0fe03a&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

**Comment by JasonKhew96** [comment]
@1287470518 没授权登录 (大部分代理服务器需授权后才能使用)

**Comment by 1287470518** [comment]
> @ 1287470518没授权登录（大部分代理服务器需授权后才能使用）

我程序小白，多多包涵
意思是需要账号授权是吗，还是指别的什么授权

**Comment by JasonKhew96** [comment]
> > @ 1287470518没授权登录（大部分代理服务器需授权后才能使用）
> 
> 我程序小白，多多包涵
> 意思是需要账号授权是吗，还是指别的什么授权

就是下面这个 帐号授权，如果不想授权，你可以换另一个不用授权的 代理服务器
![image](https://user-images.githubusercontent.com/29531167/115348447-38f38c00-a1e5-11eb-8069-372a28cc4fe2.png)

**Comment by 1287470518** [comment]
> > > @ 1287470518没授权登录（大部分代理服务器需授权后才能使用）
> > 
> > 
> > 我程序小白，多多包涵的
> > 意思是需要账号授权是吗，还是指别的什么授权
> 
> 就是下面这个帐号授权，如果不想授权，你可以换另一个不用授权的代理服务器
> ![图像](https://user-images.githubusercontent.com/29531167/115348447-38f38c00-a1e5-11eb-8069-372a28cc4fe2.png)

了解了，貌似可以了，不过视频一直加载缓冲><

**Comment by JasonKhew96** [comment]
> > > > @ 1287470518没授权登录（大部分代理服务器需授权后才能使用）
> > > 
> > > 
> > > 我程序小白，多多包涵的
> > > 意思是需要账号授权是吗，还是指别的什么授权
> > 
> > 
> > 就是下面这个帐号授权，如果不想授权，你可以换另一个不用授权的代理服务器
> > ![图像](https://user-images.githubusercontent.com/29531167/115348447-38f38c00-a1e5-11eb-8069-372a28cc4fe2.png)
> 
> 了解了，貌似可以了，不过视频一直加载缓冲><

https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/README.md#%E6%92%AD%E6%94%BE%E5%8D%A1%E9%A1%BF

**Comment by 1287470518** [comment]
> > > > > @ 1287470518没授权登录（大部分代理服务器需授权后才能使用）
> > > > 
> > > > 
> > > > 我程序小白，多多包涵的
> > > > 意思是需要账号授权是吗，还是指别的什么授权
> > > 
> > > 
> > > 就是下面这个帐号授权，如果不想授权，你可以换另一个不用授权的代理服务器
> > > ![图像](https://user-images.githubusercontent.com/29531167/115348447-38f38c00-a1e5-11eb-8069-372a28cc4fe2.png)
> > 
> > 
> > 了解了，貌似可以了，不过视频一直加载缓冲> <
> 
> [https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/README.md#%E6%92%AD%E6%94%BE%E5%8D%A1 ％E9％A1％BF](https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/README.md#%E6%92%AD%E6%94%BE%E5%8D%A1%E9%A1%BF)

![B7NPGFHZ$A567SC1W50MB%C](https://user-images.githubusercontent.com/82863490/115351061-6c83e580-a1e8-11eb-8279-4ca6b7206406.png)
是指这个吗，这里默认一直是不替换的我没动过，我正在尝试改host
