### ISSUE TITLE
可以增加更多upos服务器吗？

### ISSUE THREAD

**Issue by RoachLin** [ipcjs/bilibili-helper#816]
看泰区番剧时，感觉现有的upos服务器都很卡，但是在手机上用哔哩漫游就不会

![Screenshot_2021-05-04-20-38-19-695_tv danmaku bili](https://user-images.githubusercontent.com/33180391/117005450-db4d5c80-ad19-11eb-8267-899b24f1966d.jpg)

**Comment by BraveSail** [comment]
脚本泰区的换upos目前是坏的
