### ISSUE TITLE
番剧搜索锁区

### ISSUE THREAD

**Issue by 5lx** [ipcjs/bilibili-helper#817]
大概两周前，新番的搜索已经被锁区。
目前有版权的新番无法直接搜到。
有没有什么好办法解决这个问题，比如加个搜索代理服务器地址设置之类的

**Comment by DanielGao97** [comment]
只能挂代理，或者关注哔哩哔哩番剧出差。

**Comment by BraveSail** [comment]
https://space.bilibili.com/11783021/video  繁体搜

**Comment by ironyx217** [comment]
人在香港现在只能搜到仅限香港地区的番剧，得要挂国内梯子才能搜大陆地区的，台湾的还要另外挂台湾的梯子，我再充大会员我一辈子找不到女朋友

**Comment by czhang-trinity** [comment]
用谷歌搜能搜得到
