### ISSUE TITLE
大佬，港澳台新番用默认和备选两个服务器都连接不上了

### ISSUE THREAD

**Issue by DDVRyujo** [ipcjs/bilibili-helper#82]
## 描述

到加载视频地址那一项就挂了，港澳台新番用默认和备选两个服务器都连接不上，脚本版本为6.4.9

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

![qq 20180204003142](https://user-images.githubusercontent.com/36109110/35769243-0729c54c-0943-11e8-956a-8e3c5675e448.png)

## 其他

1. 浏览器版本：Chrome   64.0.3282.140（正式版本） （64 位）
2. 国家/地区：中国大陆

**Comment by DDVRyujo** [comment]
绝了，刚反馈完又能用了

**Comment by ReijiAkaba** [comment]
然后又不能用了（
访问量太大了么这是

**Comment by ghost** [comment]
又不行了，跟一楼一样的情况

**Comment by SORROT** [comment]
一样的情况  抓狂了

**Comment by ReijiAkaba** [comment]
试了一下uwp版还能看，服务器日常大姨妈？

**Comment by DumoeDss** [comment]
楼上说的uwp版是什么，没有国家队看的我要死了

**Comment by ipcjs** [comment]
#100
