### ISSUE TITLE
海外解锁大陆番剧需area=cn参数

### ISSUE THREAD

**Issue by pokedo0** [ipcjs/bilibili-helper#820]
脚本问题：@ipcjs

## 描述

在海外解锁大陆番剧需area参数，
![image](https://user-images.githubusercontent.com/23151451/117835736-04b53d80-b270-11eb-9711-591ee73182bb.png)

查看请求后发现只有加上`&area=cn`才可以正常请求代理服务，或者代码处硬编码 `&area=cn` 可以正常解锁

![image](https://user-images.githubusercontent.com/23151451/117835034-92dcf400-b26f-11eb-8188-3750f8a1fdd3.png)

- 问题网址：

cn 国内番剧解锁失败，加上 `&area=cn` 可正常解锁
{"code":-10403,"message":"抱歉您所在地区不可观看！"}

https://哔哩.ink/pgc/player/web/playurl?cid=315332478&qn=112&type=&otype=json&fourk=1&bvid=BV1PX4y1g7cm&ep_id=396924&fnver=0&fnval=80&session=e2638f62b9ce7c51d3732f5d32da6b4c&module=bangumi&access_key={xxxxxxxx}

hk/tw 番剧解锁成功
{"code":0,"message":"success","result":xxx}

https://哔哩.ink/pgc/player/web/playurl?avid=undefined&cid=316622604&bvid=BV1ZU4y1a7PJ&qn=112&type=&otype=json&ep_id=380335&fourk=1&fnver=0&fnval=80&session=514779d140099f77e14dd1c0052feb3e&module=bangumi&balh_ajax=1&access_key={xxxxxxxxx}

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.ink/pgc/player/web/playurl?cid=281895222&qn=112&type=&otype=json&fourk=1&bvid=BV1MK411u7Vp&ep_id=374668&fnver=0&fnval=80&session=1935d43e8ee28470b5e43c83b7718d0a&module=bangumi&access_key=75xxxxxxxxxxxxxxxxxxxxxxxxxxxx
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
```
 
</details>

## 其他

1. 浏览器版本：90.0.4430.93
2. 国家/地区：海外

**Comment by JasonKhew96** [comment]
@pokedo0 
https://github.com/ipcjs/bilibili-helper/commit/ba2d3848e5729217a785039ce5a8fe6700abae50 加了的
都 8.2.0 了

**Comment by pokedo0** [comment]
好的 是我傻逼了 油猴之前没更新成功
