### ISSUE TITLE
bilibili显示：获取下载链接失败

### ISSUE THREAD

**Issue by DD1ng-c** [ipcjs/bilibili-helper#822]
脚本问题：@ipcjs

## 描述

提示：获取下载链接失败。
番剧受限，且被替换为16s视频

- 问题网址：

https://www.bilibili.com/bangumi/play/ss38455

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss38455
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: ks3 flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?cid=339854237&qn=0&type=&otype=json&fourk=1&bvid=BV1A44y1r7ED&ep_id=398313&fnver=0&fnval=80&session=5fa0c190cdcc62e3f5fade0b876d37cd&module=bangumi&area=hk&access_key=ae50a47791e4701a96fc89dfa383b461
debug: /x/web-interface/nav {"uname":"DD1ng-c","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=undefined&cid=339854237&bvid=BV1A44y1r7ED&qn=0&type=&otype=json&ep_id=398313&fourk=1&fnver=0&fnval=80&session=52b90c39827b662b34b11b23d29899de&module=bangumi&balh_ajax=1&area=hk&access_key=ae50a47791e4701a96fc89dfa383b461
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"DD1ng-c","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.41

**Comment by JasonKhew96** [comment]
@DD1ng-c 

```json
{"code":-10403,"message":"B站解除区域限制代理域名已由bili-proxy.98e.org更换为repost.98e.org"}
```

**Comment by DD1ng-c** [comment]
> @DD1ng-c
> 
> ```json
> {"code":-10403,"message":"B站解除区域限制代理域名已由bili-proxy.98e.org更换为repost.98e.org"}
> ```

谢谢，已解决

**Comment by syr-123** [comment]
> @DD1ng-c
> 
> ```json
> {"code":-10403,"message":"B站解除区域限制代理域名已由bili-proxy.98e.org更换为repost.98e.org"}
> ```

谢谢，不过能问下这个是在哪里改啊orz

**Comment by syr-123** [comment]
> > @DD1ng-c
> > ```json
> > {"code":-10403,"message":"B站解除区域限制代理域名已由bili-proxy.98e.org更换为repost.98e.org"}
> > ```
> 
> 谢谢，已解决

不好意思，可以问一下是如何解决的么，意思是需要“代理域名更换”吗？指的是“自定义服务器”的那里改地址的意思么？刚刚改了那里也没有反应orz

**Comment by syr-123** [comment]
> @DD1ng-c
> 
> ```json
> {"code":-10403,"message":"B站解除区域限制代理域名已由bili-proxy.98e.org更换为repost.98e.org"}
> ```

不好意思，可以问一下是如何解决的么，意思是需要“代理域名更换”吗？指的是“自定义服务器”的那里改地址的意思么？刚刚改了那里也没有反应orz（前面改了以下回错地方了...多发了几次实在抱歉）
