### ISSUE TITLE
今天突然看不了

### ISSUE THREAD

**Issue by wxp203** [ipcjs/bilibili-helper#824]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep398589
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"星洛Starlight","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"星洛Starlight","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

**Comment by JasonKhew96** [comment]
没设置 **自定义服务器** ?

**Comment by wxp203** [comment]
> 没设置 **自定义服务器** ?

我一直都有设置，港澳台只能看评论区。开了脚本，自动判断模式，大陆番剧也看不了，关闭脚本才能看大陆番剧。估计强制设置了走blilplus代理，选了自定义跟没选一样（我看见问题日志有biliplus）

**Comment by wxp203** [comment]
> > 没设置**自定义服务器**？
> 
>我一直都有设置，港澳台只能看评论区。开了脚本，自动判断模式，大陆番剧也看不了，关闭脚本才能看大陆番剧。估计强制设置了走blilplus代理，选了自定义跟没选一样（我看见问题日志有biliplus）

换了浏览器还是同样的问题

**Comment by ironyx217** [comment]
+1

**Comment by JasonKhew96** [comment]
应该是播放器的问题，都是 3.X beta 吧？

感觉是同一个问题：
https://github.com/ipcjs/bilibili-helper/issues/825

**Comment by wxp203** [comment]
> 应该是播放器的问题，都是3.X beta吧？
> 
> 是认为同一问题：
> #825
3.0.2 beta，怎么解决呢

**Comment by JasonKhew96** [comment]
> > 应该是播放器的问题，都是3.X beta吧？
> > 是认为同一问题：
> > #825
> > 3.0.2 beta，怎么解决呢

脚本不适配 beta 版，我也不知道怎么 体验 beta 版播放器，也不知道怎么降回去，所以没办法

**Comment by wxp203** [comment]
> > > 应该是播放器的问题，都是3.X beta吧？
> > > 是认为同一问题：
> > > #825
> > > 3.0.2 beta，怎么解决呢
> 
> 脚本不适配 beta 版，我也不知道怎么 体验 beta 版播放器，也不知道怎么降回去，所以没办法

不同用户用的播放器是不一样的吗，那我只能看盗版了

**Comment by GPBeta** [comment]
草，B 站还让用户抽奖当白老鼠的吗
普通视频播放器版本是 2.6.x 番剧视频播放器是 3.0.x

**Comment by OnlyCharacter** [comment]
https://github.com/ipcjs/bilibili-helper/issues/825#issuecomment-868682229

**Comment by wxp203** [comment]
今天清除cookie解决了，但我前几天也是清除cookie，登录原账户后仍是beta版，难道b站撤回测试了？

**Comment by syr-123** [comment]
> 今天清除cookie解决了，但我前几天也是清除cookie，登录原账户后仍是beta版，难道b站撤回测试了？

 不好意思问一下，你清除cookie是所有的数据全都清掉么？

**Comment by wxp203** [comment]
> > 今天清除cookie解决了，但我前几天也是清除cookie，登录原账户后仍是beta版，难道b站撤回测试了？
> 
> 不好意思问一下，你清除cookie是所有的数据全都清掉么？

bilibili相关的就行了。我的主要是播放器版本问题，退回以前版本就行了

**Comment by syr-123** [comment]
> > > 今天清除cookie解决了，但我前几天也是清除cookie，登录原账户后仍是beta版，难道b站撤回测试了？
> > 
> > 
> > 不好意思问一下，你清除cookie是所有的数据全都清掉么？
> 
> bilibili相关的就行了。我的主要是播放器版本问题，退回以前版本就行了

前面给我回复的大佬说我的也是播放器版本问题，但是之前我清了一下没起作用，不过也可能是我不会弄清cookie，只清除b站相关的能问下是要在哪里选吗，我在chrome的设置里清看只能选时间选项h......

**Comment by wxp203** [comment]
设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
现在看来你的可能不是版本问题，看下https://github.com/ipcjs/bilibili-helper/issues/822  解决吧

**Comment by syr-123** [comment]
> 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> 现在看来你的可能不是版本问题，看下#822 解决吧

香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成https://github.com/ipcjs/bilibili-helper/issues/829
变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？

**Comment by syr-123** [comment]
> > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > 现在看来你的可能不是版本问题，看下#822 解决吧
> 
> 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829的这个问题了，加载内容超时orz]是清理完cookie不能登回原来账号吗？

**Comment by wxp203** [comment]
> > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > 现在看来你的可能不是版本问题，看下#822 解决吧
> 
> 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？

可以登

**Comment by syr-123** [comment]
> > > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > > 现在看来你的可能不是版本问题，看下#822 解决吧
> > 
> > 
> > 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> > 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？
> 
> 可以登

我登了反而到3.0播放器了好像，之前港澳台的其实还可以打开，现在港澳台的也打不开了妈耶

**Comment by wxp203** [comment]
> > > > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > > > 现在看来你的可能不是版本问题，看下#822 解决吧
> > > 
> > > 
> > > 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> > > 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？
> > 
> > 
> > 可以登
> 
> 我登了反而到3.0播放器了好像，之前港澳台的其实还可以打开，现在港澳台的也打不开了妈耶

啊这，我清完cookie登录就好了，这么玄幻的吗，要么你跟客服说你要用2.6播放器

**Comment by GPBeta** [comment]
我也是在隐私模式下 2.6 版本的播放器，一登陆就 3.0 了

**Comment by syr-123** [comment]
> > > > > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > > > > 现在看来你的可能不是版本问题，看下#822 解决吧
> > > > 
> > > > 
> > > > 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> > > > 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？
> > > 
> > > 
> > > 可以登
> > 
> > 
> > 我登了反而到3.0播放器了好像，之前港澳台的其实还可以打开，现在港澳台的也打不开了妈耶
> 
> 啊这，我清完cookie登录就好了，这么玄幻的吗，要么你跟客服说你要用2.6播放器

这个和b站客服说还能改的吗？

**Comment by wxp203** [comment]
> > > > > > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > > > > > 现在看来你的可能不是版本问题，看下#822 解决吧
> > > > > 
> > > > > 
> > > > > 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> > > > > 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？
> > > > 
> > > > 
> > > > 可以登
> > > 
> > > 
> > > 我登了反而到3.0播放器了好像，之前港澳台的其实还可以打开，现在港澳台的也打不开了妈耶
> > 
> > 
> > 啊这，我清完cookie登录就好了，这么玄幻的吗，要么你跟客服说你要用2.6播放器
> 
> 这个和b站客服说还能改的吗？

测试资格绑定账号的话，就换账号吧，后台应该也可以取消测试吧

**Comment by syr-123** [comment]
主要是没其他账号唉，但是我清除cookie之后没登陆账号打开动画番剧发现也是3.0

**Comment by syr-123** [comment]
> > > > > > > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > > > > > > 现在看来你的可能不是版本问题，看下#822 解决吧
> > > > > > 
> > > > > > 
> > > > > > 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> > > > > > 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？
> > > > > 
> > > > > 
> > > > > 可以登
> > > > 
> > > > 
> > > > 我登了反而到3.0播放器了好像，之前港澳台的其实还可以打开，现在港澳台的也打不开了妈耶
> > > 
> > > 
> > > 啊这，我清完cookie登录就好了，这么玄幻的吗，要么你跟客服说你要用2.6播放器
> > 
> > 
> > 这个和b站客服说还能改的吗？
> 
> 测试资格绑定账号的话，就换账号吧，后台应该也可以取消测试吧

主要是没其他账号唉，但是我清除cookie之后没登陆账号打开动画番剧发现也是3.0

**Comment by wxp203** [comment]
> > > > > > > > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > > > > > > > 现在看来你的可能不是版本问题，看下#822 解决吧
> > > > > > > 
> > > > > > > 
> > > > > > > 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> > > > > > > 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？
> > > > > > 
> > > > > > 
> > > > > > 可以登
> > > > > 
> > > > > 
> > > > > 我登了反而到3.0播放器了好像，之前港澳台的其实还可以打开，现在港澳台的也打不开了妈耶
> > > > 
> > > > 
> > > > 啊这，我清完cookie登录就好了，这么玄幻的吗，要么你跟客服说你要用2.6播放器
> > > 
> > > 
> > > 这个和b站客服说还能改的吗？
> > 
> > 
> > 测试资格绑定账号的话，就换账号吧，后台应该也可以取消测试吧
> 
> 主要是没其他账号唉，但是我清除cookie之后没登陆账号打开动画番剧发现也是3.0

再清下cookie吧，要么换浏览器试试

**Comment by syr-123** [comment]
> > > > > > > > > 设置-->Cookie 及其他网站数据-->所有 Cookie 和网站数据-->搜索cookie-->bilibili-->全删掉
> > > > > > > > > 现在看来你的可能不是版本问题，看下#822 解决吧
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 香港服务器那个我之前就改了，谢谢你发的操作步骤，我之前还真删的地方不对。但是刚刚按这个清理完cookie，重新登录之前按变成#829
> > > > > > > > 变成加载内容超时这个问题了，orz 是清理完cookie不能登回原来账号吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 可以登
> > > > > > 
> > > > > > 
> > > > > > 我登了反而到3.0播放器了好像，之前港澳台的其实还可以打开，现在港澳台的也打不开了妈耶
> > > > > 
> > > > > 
> > > > > 啊这，我清完cookie登录就好了，这么玄幻的吗，要么你跟客服说你要用2.6播放器
> > > > 
> > > > 
> > > > 这个和b站客服说还能改的吗？
> > > 
> > > 
> > > 测试资格绑定账号的话，就换账号吧，后台应该也可以取消测试吧
> > 
> > 
> > 主要是没其他账号唉，但是我清除cookie之后没登陆账号打开动画番剧发现也是3.0
> 
> 再清下cookie吧，要么换浏览器试试

谢谢大佬！草 我又试了一次几乎全清除，现在大概是好了，希望是稳定的不要明天又不行了orz

**Comment by yuangezhizao** [comment]
可以通过替换`js`的方法使用旧版（2.60.6）播放器，https://github.com/ipcjs/bilibili-helper/issues/829#issuecomment-873350473
