### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by CyclonicPinna** [ipcjs/bilibili-helper#826]
无法播放番剧，显示：

## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":4,"responseText":"{\"ErrorCode\":\"AccessDenied\",\"ErrorMessage\":\"FC service is not enabled for current user.\"}","status":403,"statusText":"Forbidden"}}

日志如下：

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep21387
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: kodo flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: undefined
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"anonymous","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=2688917&bvid=BV19x411P7HR&qn=32&type=&otype=json&ep_id=21387&fourk=1&fnver=0&fnval=80&session=4fecbdabc56adc3a96613a98e89f5efb&module=bangumi&balh_ajax=1&access_key=88687dd952d2379cefd7efdd6f59cd31
debug: /x/web-interface/nav {"uname":"anonymous","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Comment by JasonKhew96** [comment]
不像是 b站 返回的东西，这代理挂了吧

**Comment by CyclonicPinna** [comment]
好像是。多谢。
