### ISSUE TITLE
解析失败？视频显示“非常抱歉，本视频可能由于以下原因导致无法播放”→更改香港代理服务器地址后变为”无法拉取视频“

### ISSUE THREAD

**Issue by syr-123** [ipcjs/bilibili-helper#827]
问题描述：
   之前就有的番打卡出现这个问题了，刚刚突然所有的都出现了这个问题。
   也不是显示“解析失败”，网页打开，视频下面的在线观看人数还都可以显示，但是视频替换显示出来的是b站那个“肥肠抱歉......”的机械语音+画面。
  这是出什么问题了么？
  拜托大佬了，大佬辛苦了！！

- 问题网址：
https://www.bilibili.com/bangumi/play/ss36167?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.52

日志：
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss36167?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.52
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?cid=293256894&qn=112&type=&otype=json&fourk=1&bvid=BV17o4y1d7Nq&ep_id=374624&fnver=0&fnval=80&session=adee37445789fe126e255f8226043941&module=bangumi&area=false&access_key=85dfdcfa80f181bb8fc01b767a7ff661
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=undefined&cid=293256894&bvid=BV17o4y1d7Nq&qn=112&type=&otype=json&ep_id=374624&fourk=1&fnver=0&fnval=80&session=bc2fcd01a4c45f17af1c8b36950b654e&module=bangumi&balh_ajax=1&area=false&access_key=85dfdcfa80f181bb8fc01b767a7ff661
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

## 其他

1. 浏览器版本：Google Chrome ，91.0.4472.114（正式版本） （64 位）
2. 国家/地区：日本，长崎

**Comment by JasonKhew96** [comment]
https://github.com/ipcjs/bilibili-helper/issues/822#issuecomment-855407698

**Comment by syr-123** [comment]
> [#822 (comment)](https://github.com/ipcjs/bilibili-helper/issues/822#issuecomment-855407698)

@JasonKhew96 自定义服务器列表那香港的刚刚改成说的那个新地址了，但是直接变成了”拉取视频失败“orz

日志：
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss36167?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.52
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: hw flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?cid=293256894&qn=112&type=&otype=json&fourk=1&bvid=BV17o4y1d7Nq&ep_id=374624&fnver=0&fnval=80&session=d490594ff97e4ceefe7874e7496930f8&module=bangumi&area=false&access_key=da26bed9aec202231e30df5238ebe061
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?cid=293256894&qn=112&type=&otype=json&fourk=1&bvid=BV17o4y1d7Nq&ep_id=374624&fnver=0&fnval=80&session=d490594ff97e4ceefe7874e7496930f8&module=bangumi&access_key=da26bed9aec202231e30df5238ebe061
debug: atRun: 2, complete
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?cid=293256894&qn=112&type=&otype=json&fourk=1&bvid=BV17o4y1d7Nq&ep_id=374624&fnver=0&fnval=80&session=d490594ff97e4ceefe7874e7496930f8&module=bangumi&area=tw&access_key=da26bed9aec202231e30df5238ebe061
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?cid=293256894&qn=112&type=&otype=json&fourk=1&bvid=BV17o4y1d7Nq&ep_id=374624&fnver=0&fnval=80&session=d490594ff97e4ceefe7874e7496930f8&module=bangumi&area=hk&access_key=da26bed9aec202231e30df5238ebe061
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?cid=293256894&qn=112&type=&otype=json&fourk=1&bvid=BV17o4y1d7Nq&ep_id=374624&fnver=0&fnval=80&session=d490594ff97e4ceefe7874e7496930f8&module=bangumi&access_key=da26bed9aec202231e30df5238ebe061
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?avid=undefined&cid=293256894&bvid=BV17o4y1d7Nq&qn=112&type=&otype=json&ep_id=374624&fourk=1&fnver=0&fnval=80&session=84688b7f596467c201ed34545f3045fb&module=bangumi&balh_ajax=1&area=false&access_key=da26bed9aec202231e30df5238ebe061
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=293256894&bvid=BV17o4y1d7Nq&qn=112&type=&otype=json&ep_id=374624&fourk=1&fnver=0&fnval=80&session=84688b7f596467c201ed34545f3045fb&module=bangumi&balh_ajax=1&access_key=da26bed9aec202231e30df5238ebe061
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=293256894&bvid=BV17o4y1d7Nq&qn=112&type=&otype=json&ep_id=374624&fourk=1&fnver=0&fnval=80&session=84688b7f596467c201ed34545f3045fb&module=bangumi&balh_ajax=1&area=tw&access_key=da26bed9aec202231e30df5238ebe061
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?avid=undefined&cid=293256894&bvid=BV17o4y1d7Nq&qn=112&type=&otype=json&ep_id=374624&fourk=1&fnver=0&fnval=80&session=84688b7f596467c201ed34545f3045fb&module=bangumi&balh_ajax=1&area=hk&access_key=da26bed9aec202231e30df5238ebe061
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=293256894&bvid=BV17o4y1d7Nq&qn=112&type=&otype=json&ep_id=374624&fourk=1&fnver=0&fnval=80&session=84688b7f596467c201ed34545f3045fb&module=bangumi&balh_ajax=1&access_key=da26bed9aec202231e30df5238ebe061
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

**Comment by lz37** [comment]
+1，我也碰到了这个问题

**Comment by wxp203** [comment]
就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看

**Comment by ironyx217** [comment]
> 就是新版播放器不兼容，看看你的是v3.0.2β播放器，脚本会强制调用胆绿素加代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除Cookie，换登录账号，换回v2.60播放器观看

怎麼看版本啊？我這邊播放器初始化後面沒有顯示，也右鍵不了

**Comment by syr-123** [comment]
> 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看

同问怎么看版本......清除Cookie是包括所有密码都清理掉么？看其他问题下的回复，这个新版播放器还不是每个账号都会遇到的意思？

**Comment by wxp203** [comment]
> > 就是新版播放器不兼容，看看你的是v3.0.2β播放器，脚本会强制调用胆绿素加代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除Cookie，换登录账号，换回v2.60播放器观看
> 
> 怎麼看版本啊？我這邊播放器初始化後面沒有顯示，也右鍵不了

找个能正常看的番剧（我这关闭代理看国内的就行），鼠标右键点击视频，有个更新历史。只有番剧区有新版的，投稿区都是旧版

**Comment by lz37** [comment]
> 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看

清除cookie以后就好了

**Comment by wxp203** [comment]
> > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> 
> 清除cookie以后就好了

我试了以下，换回去了，可能我一开始cookie没清干净吧

**Comment by syr-123** [comment]
> > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > 
> > 
> > 清除cookie以后就好了
> 
> 我试了以下，换回去了，可能我一开始cookie没清干净吧

不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？

**Comment by lz37** [comment]
> > > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > > 
> > > 
> > > 清除cookie以后就好了
> > 
> > 
> > 我试了以下，换回去了，可能我一开始cookie没清干净吧
> 
> 不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？

只要清理cookie就好了，我的是这样

**Comment by wxp203** [comment]
> > > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > > 
> > > 
> > > 清除cookie以后就好了
> > 
> > 
> > 我试了以下，换回去了，可能我一开始cookie没清干净吧
> 
> 不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？

现在可以登原来账号了，前几天好像是测试绑定账号的

**Comment by syr-123** [comment]
> > > > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > > > 
> > > > 
> > > > 清除cookie以后就好了
> > > 
> > > 
> > > 我试了以下，换回去了，可能我一开始cookie没清干净吧
> > 
> > 
> > 不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？
> 
> 现在可以登原来账号了，前几天好像是测试绑定账号的

大陆的代理服务器地址填的还是：https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/
这个么？我怎么感觉是因为这个不反应大陆的番？港澳的都还正常

**Comment by lz37** [comment]
> > > > > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > > > > 
> > > > > 
> > > > > 清除cookie以后就好了
> > > > 
> > > > 
> > > > 我试了以下，换回去了，可能我一开始cookie没清干净吧
> > > 
> > > 
> > > 不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？
> > 
> > 
> > 现在可以登原来账号了，前几天好像是测试绑定账号的
> 
> 大陆的代理服务器地址填的还是：https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/
> 这个么？我怎么感觉是因为这个不反应大陆的番？港澳的都还正常

这个你可以在github里搜哔哩漫游，里面的公共服务器有很多，自己选择合适的

**Comment by syr-123** [comment]
> > > > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > > > 
> > > > 
> > > > 清除cookie以后就好了
> > > 
> > > 
> > > 我试了以下，换回去了，可能我一开始cookie没清干净吧
> > 
> > 
> > 不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？
> 
> 只要清理cookie就好了，我的是这样

再问一下，你打开大陆源的番可以正常看么

> > > > > > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > > > > > 
> > > > > > 
> > > > > > 清除cookie以后就好了
> > > > > 
> > > > > 
> > > > > 我试了以下，换回去了，可能我一开始cookie没清干净吧
> > > > 
> > > > 
> > > > 不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？
> > > 
> > > 
> > > 现在可以登原来账号了，前几天好像是测试绑定账号的
> > 
> > 
> > 大陆的代理服务器地址填的还是：https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/
> > 这个么？我怎么感觉是因为这个不反应大陆的番？港澳的都还正常
> 
> 这个你可以在github里搜哔哩漫游，里面的公共服务器有很多，自己选择合适的



> > > > > > > 就是新版播放器不兼容，看看你的是v3.0.2beta播放器，脚本会强制调用biliplus代理，可能是灰度测试，脚本作者用不了新版播放器，所以暂时没法更新脚本。你可以通过清除cookie，换登录账号，换回v2.60播放器观看
> > > > > > 
> > > > > > 
> > > > > > 清除cookie以后就好了
> > > > > 
> > > > > 
> > > > > 我试了以下，换回去了，可能我一开始cookie没清干净吧
> > > > 
> > > > 
> > > > 不好意思问一下，是必须Cookie清理之后要换其他的账号才行么？
> > > 
> > > 
> > > 现在可以登原来账号了，前几天好像是测试绑定账号的
> > 
> > 
> > 大陆的代理服务器地址填的还是：https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/
> > 这个么？我怎么感觉是因为这个不反应大陆的番？港澳的都还正常
> 
> 这个你可以在github里搜哔哩漫游，里面的公共服务器有很多，自己选择合适的

谢谢，公共服务器找到了，但是试了很多发现还是出来那个“肥肠抱歉”....cookie也又清了的....是cookie内容全选所有都清掉么难道？

**Comment by ironyx217** [comment]
我打開僅限港澳區的番播放器顯示是2.6版本，清理cookie也沒有效果...

**Comment by syr-123** [comment]
> 我打開僅限港澳區的番播放器顯示是2.6版本，清理cookie也沒有效果...

我也是.....港澳台的打得开可以看到是2.6版本，但是大陆的都打不开，cookie我也清了好几次了都

**Comment by miraclestar43** [comment]
同楼上，已经一周没在b站看番了
