### ISSUE TITLE
加载内容超时... Possible reasons: hardware acceleration has been crashed or non-standard browser is employed

### ISSUE THREAD

**Issue by GPBeta** [ipcjs/bilibili-helper#829]
脚本问题：@ipcjs

## 描述
脚本启用时无法观看所有 B 站视频（番剧和视频投稿）
已尝试重新授权和清空 Cookies 均无解决。

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep398579
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"GPBeta","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"GPBeta","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

```
 
</details>

## 控制台错误

```
Uncaught TypeError: Cannot read property 'errorcid' of undefined
    at isAreaLimitForPlayUrl (userscript.html:3450)
    at XMLHttpRequest.value (userscript.html:3040)
```

## 其他

1. 浏览器版本：Chrome 91.0.4472.114 x64
2. 国家/地区：中国广州

**Comment by JasonKhew96** [comment]
盲猜 beta 播放器
https://github.com/ipcjs/bilibili-helper/issues/824#issuecomment-868169166

**Comment by yuangezhizao** [comment]
随手`F12`看到了旧版播放器的链接还写在了注释里 2333

`@jsc/video: 2.60.6-rc.8387.0-752ef8cc (2021-06-29T10:12:08.667Z)`：https://s1.hdslb.com/bfs/static/player/main/video.491babfa.js?v=20210111

`@jsc/nano: 3.0.2-beta.1-23efe12e (2021-05-26T18:24:49+08:00)`：
https://s1.hdslb.com/bfs/static/player/main/core.202105262.js

在考虑怎么个替换法，能去使用旧版的播放器`js`？

**Comment by yuangezhizao** [comment]
找了个拓展能替换资源，把所有与`video`相关的`js`统一替换掉就可以使用`2.60.6`旧版播放器了

![image](https://user-images.githubusercontent.com/16861681/124344107-204f1b80-dc03-11eb-81de-ffe967d3b949.png)

具体有如下`3`个`js`需要替换
1. `https://s1.hdslb.com/bfs/static/player/main/core.202105262.js`替换成`https://s1.hdslb.com/bfs/static/player/main/video.491babfa.js?v=20210111`
2. `https://s1.hdslb.com/bfs/static/pgc/nano/1.video-nano.d697c0f7475e2bf19cfd09de33725486075f8aa5.js`替换成`https://s1.hdslb.com/bfs/static/pgcv/1.video.cf1787dc5a52feeff87164aa8cff2d480b6ae24d.js`
3. `https://s1.hdslb.com/bfs/static/pgc/nano/video-nano.d697c0f7475e2bf19cfd09de33725486075f8aa5.js`替换成`https://s1.hdslb.com/bfs/static/pgcv/video.cf1787dc5a52feeff87164aa8cff2d480b6ae24d.js`

然后就可以正常播放了（因为我这里即使是清空缓存再重新登录，也是`beta`版播放器……

![image](https://user-images.githubusercontent.com/16861681/124344309-eb8f9400-dc03-11eb-9075-38bc4c0774b9.png)

**Comment by lgqdaxia** [comment]
> 找了个拓展能替换资源，把所有与`video`相关的`js`统一替换掉就可以使用`2.60.6`旧版播放器了
> 
> ![image](https://user-images.githubusercontent.com/16861681/124344107-204f1b80-dc03-11eb-81de-ffe967d3b949.png)
> 
> 具体有如下`3`个`js`需要替换
> 
> 1. `https://s1.hdslb.com/bfs/static/player/main/core.202105262.js`替换成`https://s1.hdslb.com/bfs/static/player/main/video.491babfa.js?v=20210111`
> 2. `https://s1.hdslb.com/bfs/static/pgc/nano/1.video-nano.d697c0f7475e2bf19cfd09de33725486075f8aa5.js`替换成`https://s1.hdslb.com/bfs/static/pgcv/1.video.cf1787dc5a52feeff87164aa8cff2d480b6ae24d.js`
> 3. `https://s1.hdslb.com/bfs/static/pgc/nano/video-nano.d697c0f7475e2bf19cfd09de33725486075f8aa5.js`替换成`https://s1.hdslb.com/bfs/static/pgcv/video.cf1787dc5a52feeff87164aa8cff2d480b6ae24d.js`
> 
> 然后就可以正常播放了（因为我这里即使是清空缓存再重新登录，也是`beta`版播放器……
> 
> ![image](https://user-images.githubusercontent.com/16861681/124344309-eb8f9400-dc03-11eb-9075-38bc4c0774b9.png)

用了你的方法可以看大陆的番了，但是港澳台的播放器加载不出来，也不显示任何信息。你也是这样吗？

**Comment by yuangezhizao** [comment]
@lgqdaxia emmm，港澳台有的番播放器可以加载出来有的不行就很奇怪（不太懂前端`webpack`打包什么的逻辑
并且印象里还碰到了有的大陆番播放器也加载不出来

举个例子：
`奇蛋物語 Wonder Egg Priority（僅限港澳台地區）` ✅
`女朋友and女朋友（僅限港澳台地區） ` ❎

并且`1.video-nano.d697c0f7475e2bf19cfd09de33725486075f8aa5.js`和`video-nano.d697c0f7475e2bf19cfd09de33725486075f8aa5.js`还更新了……
变成了`1.video-nano.9a869cf89c288201d351f8f9402d96cd3f8ac2f0.js`和`video-nano.9a869cf89c288201d351f8f9402d96cd3f8ac2f0.js`

**Comment by zymyxy** [comment]
相同问题，同样显示加载内容超时Possible reasons: hardware acceleration has been crashed or non-standard browser is employed

**Comment by AkkaXdXd** [comment]
不用整这么复杂 去油猴更新到最新8.2.4 就好了
