### ISSUE TITLE
你们能看https://www.bilibili.com/bangumi/play/ep398505吗？

### ISSUE THREAD

**Issue by Z-fly** [ipcjs/bilibili-helper#831]
https://www.bilibili.com/bangumi/play/ep398505

问完自关

**Comment by JasonKhew96** [comment]
> https://www.bilibili.com/bangumi/play/ep398505
> 
> 问完自关

可以，是总集篇，你可以选择不看
![image](https://user-images.githubusercontent.com/29531167/123802991-73348480-d91e-11eb-9d20-374f987da5fd.png)

**Comment by Z-fly** [comment]
> > https://www.bilibili.com/bangumi/play/ep398505
> > 问完自关
> 
> 可以，是总集篇，你可以选择不看
> ![image](https://user-images.githubusercontent.com/29531167/123802991-73348480-d91e-11eb-9d20-374f987da5fd.png)

为什么我这里不能用脚本看？

**Comment by LilHayah** [comment]
看不了， 不知道为什么SP页面不能 成功解锁

刷新一下又行了。。。
