### ISSUE TITLE
新的问题，加载内容超时（清理cookie并未退回播放器版本）

### ISSUE THREAD

**Issue by syr-123** [ipcjs/bilibili-helper#832]
- 问题网址：
https://www.bilibili.com/bangumi/play/ss36167?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.51

问题描述：
加载画面一直停留在：
获取视频参数... [成功]
播放器初始化... [成功] 3.0.2-beta.1-23efe12e
获取播放地址...
加载内容超时... Possible reasons: hardware acceleration has been crashed or non-standard browser is employed

之前可能是我cookie没清理完全，之前的问题（未解决 现在出现新问题orz）：https://github.com/ipcjs/bilibili-helper/issues/827

刚刚听了其他回复大佬的清理操作顺序，清理完bilibili相关的cookie之后，再次登录发现屏幕如上反应，并显示播放器3.0.2-beta.1-23efe12e（之前港澳台的还打得开，这下港澳台的也打不开了，港澳台代理服务器已换）

重新再次清理cookie，未登录播放发现播放器依旧是3.0.2-beta.1-23efe12e，并未退回。
求助大佬orz

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss36167?spm_id_from=333.851.b_62696c695f7265706f72745f616e696d65.51
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"浅間夏和","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36

## 其他

1. 浏览器版本：Google Chrome   （64 位）91.0.4472.124（正式版本） （64 位）
2. 国家/地区：日本/长崎

**Comment by wenxinxiang110** [comment]
用firefix和chrome遇到同样问题，没有找到回退播放器版本的方法

# 问题日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss39023
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"血口酱","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"血口酱","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

**Comment by syr-123** [comment]
> 用firefix和chrome遇到同样问题，没有找到回退播放器版本的方法
> 
> # 问题日志
> debug: atRun: -1, loading
> debug: [解除B站区域限制 v8.2.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss39023
> debug: window.**playinfo**
> debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
> info: mode: default blocked_vip: server: https://www.biliplus.com upos_server: flv_prefer_ws: remove_pre_ad: enable_in_av: readyState: loading isLogin: true isLoginBiliBili: true
> debug: atRun: 0, interactive
> debug: atRun: 1, interactive
> debug: set jQuery -> function(a,b){return new e.fn.init(a,b,h)}
> debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
> debug: atRun: 2, complete
> debug: /x/web-interface/nav {"uname":"血口酱","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
> debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
> debug: /x/web-interface/nav {"uname":"血口酱","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
> debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

你重新试着清除cookie了吗？我重新又删了一边之后变好了，挺奇怪的，之前怎么都变不回去
