### ISSUE TITLE
新番不能观看，四月动画可以观看

### ISSUE THREAD

**Issue by hyb093** [ipcjs/bilibili-helper#834]
## 描述
7月新番不能观看（非常抱歉），四月的动画可以正常观看

- 问题网址：
https://www.bilibili.com/bangumi/play/ep409230

## 描述
7月新番不能观看（非常抱歉），四月的动画可以正常观看

- 问题网址：
https://www.bilibili.com/bangumi/play/ep409230

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.0 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep409230
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...

info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://cn.XXXXX.xyz/pgc/player/web/playurl?cid=363124043&qn=112&type=&otype=json&fourk=1&bvid=BV1mv411H7Gi&ep_id=409230&fnver=0&fnval=80&session=2928521c483ec2bdd2bd35d1f42bdfed&module=bangumi&area=&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.ink/pgc/player/web/playurl?cid=363124043&qn=112&type=&otype=json&fourk=1&bvid=BV1mv411H7Gi&ep_id=409230&fnver=0&fnval=80&session=2928521c483ec2bdd2bd35d1f42bdfed&module=bangumi&area=tw&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: cn?cid=363124043&qn=112&type=&otype=json&fourk=1&bvid=BV1mv411H7Gi&ep_id=409230&fnver=0&fnval=80&session=2928521c483ec2bdd2bd35d1f42bdfed&module=bangumi&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.ink/intl/gateway/v2/ogv/playurl?area=th&access_key=22301ce40350b175c3b72d38ce0f8951&appkey=7d089525d3611b1c&build=1001310&cid=363124043&ep_id=409230&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=112&ts=1625282854&sign=e8bd6265615d1b4c11437dd38ba3cef7
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://cn.XXXXX.xyz/pgc/player/web/playurl?cid=363124043&qn=112&type=&otype=json&fourk=1&bvid=BV1mv411H7Gi&ep_id=409230&fnver=0&fnval=80&session=2928521c483ec2bdd2bd35d1f42bdfed&module=bangumi&area=cn&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=363124043&qn=112&type=&otype=json&fourk=1&bvid=BV1mv411H7Gi&ep_id=409230&fnver=0&fnval=80&session=2928521c483ec2bdd2bd35d1f42bdfed&module=bangumi&access_key=22301ce40350b175c3b72d38ce0f8951
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 读取番剧地区缓存，使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://cn.XXXXX.xyz/pgc/player/web/playurl?avid=undefined&cid=363124043&bvid=BV1mv411H7Gi&qn=112&type=&otype=json&ep_id=409230&fourk=1&fnver=0&fnval=80&session=1ace632303095359b16ee9308d9eca4a&module=bangumi&balh_ajax=1&area=false&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://cn.XXXXX.xyz/pgc/player/web/playurl?avid=undefined&cid=363124043&bvid=BV1mv411H7Gi&qn=112&type=&otype=json&ep_id=409230&fourk=1&fnver=0&fnval=80&session=1ace632303095359b16ee9308d9eca4a&module=bangumi&balh_ajax=1&area=&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.ink/pgc/player/web/playurl?avid=undefined&cid=363124043&bvid=BV1mv411H7Gi&qn=112&type=&otype=json&ep_id=409230&fourk=1&fnver=0&fnval=80&session=1ace632303095359b16ee9308d9eca4a&module=bangumi&balh_ajax=1&area=tw&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: cn?avid=undefined&cid=363124043&bvid=BV1mv411H7Gi&qn=112&type=&otype=json&ep_id=409230&fourk=1&fnver=0&fnval=80&session=1ace632303095359b16ee9308d9eca4a&module=bangumi&balh_ajax=1&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.ink/intl/gateway/v2/ogv/playurl?area=th&access_key=22301ce40350b175c3b72d38ce0f8951&appkey=7d089525d3611b1c&build=1001310&cid=363124043&ep_id=409230&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=112&ts=1625282861&sign=0b5009367d24fef3af18b09c8b1a55b3
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://cn.XXXXX.xyz/pgc/player/web/playurl?avid=undefined&cid=363124043&bvid=BV1mv411H7Gi&qn=112&type=&otype=json&ep_id=409230&fourk=1&fnver=0&fnval=80&session=1ace632303095359b16ee9308d9eca4a&module=bangumi&balh_ajax=1&area=cn&access_key=22301ce40350b175c3b72d38ce0f8951
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=363124043&bvid=BV1mv411H7Gi&qn=112&type=&otype=json&ep_id=409230&fourk=1&fnver=0&fnval=80&session=1ace632303095359b16ee9308d9eca4a&module=bangumi&balh_ajax=1&access_key=22301ce40350b175c3b72d38ce0f8951
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

```
 
</details>



## 其他

1. 浏览器版本：Chrome 91.0.4472.124
2. 国家/地区：US

**Comment by pokedo0** [comment]
我这边可以 是不是你代理不支持大陆的
