### ISSUE TITLE
在北美，看大陆番剧，8.2.1版本，没有显示3.0 beta，依然无法拉取视频地址

### ISSUE THREAD

**Issue by Fan-Mi** [ipcjs/bilibili-helper#836]
人在北美，想看大陆番剧，无法拉取视频地址。今天升级了 8.2.1 版本，播放器也没有显示 3.0 beta 之类的字样，也没开unblock youku, 然而还是看不了。首选服务器使用的主页中介绍的 `https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/` ，upos尝试了每一个选项，都不行。

> \#\# 拉取视频地址失败
> 原因: {"code":-1,"error":{"readyState":4,"responseText":"{\"ErrorCode\":\"AccessDenied\",\"ErrorMessage\":\"FC service is not > enabled for current user.\"}","status":403,"statusText":"Forbidden"}}

以下日志是先刷新页面，等出现错误以后，点击“复制日志”得来的。
~~~
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep403366
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: hw flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: undefined
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: atRun: 2, complete
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"mfrice","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"mfrice","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=363067506&bvid=BV1zy4y1M7FU&qn=0&type=&otype=json&ep_id=403366&fourk=1&fnver=0&fnval=80&session=bf98542055824858aff54e97327ab9bb&module=bangumi&balh_ajax=1&access_key=1af5dff9b7048ff942147929a6da7a71
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
~~~

**Comment by JasonKhew96** [comment]
@Fan-Mi 怀疑是代理问题，换个代理吧

**Comment by Fan-Mi** [comment]
> @Fan-Mi 怀疑是代理问题，换个代理吧

脚本首页提供的五个服务器都试过了，都不行。如果你知道现在哪个服务器+upos的组合在北美可用，可以跟我说一下嘛

**Comment by Fan-Mi** [comment]
> @Fan-Mi 怀疑是代理问题，换个代理吧

哇哦，我好像发现解决方案了。比如我现在用的`https://bili.tuturu.top`，如果只把它填进首选服务器就不能用，但是除了填进首选以外，再把它填进自定义服务器的大陆里，就能用了！这是bug吗？还是就这么设计的？如果就是这么设计的也太tricky了吧

**Comment by gayhub-com** [comment]
> > @Fan-Mi 怀疑是代理问题，换个代理吧
> 
> 哇哦，我好像发现解决方案了。比如我现在用的`https://bili.tuturu.top`，如果只把它填进首选服务器就不能用，但是除了填进首选以外，再把它填进自定义服务器的大陆里，就能用了！这是bug吗？还是就这么设计的？如果就是这么设计的也太tricky了吧

我的问题是脚本会优先调用香港服务器，然后显示区域不支持直接变16秒非常抱歉了（不会尝试其他区域的服务器地址）。我把香港代理地址删了就可以优先调用首选服务器然后再港澳台，这样就能看了。不知道这是个什么情况

**Comment by JasonKhew96** [comment]
都用 8.2.3 看看，前几个版本有点问题

**Comment by BraveSail** [comment]
ErrorCode":"AccessDenied","ErrorMessage":"FC service is not > enabled for current user."

这个是阿里云函数内部的返回错误，可能是这个服务器无效了

**Comment by AisukaYuki** [comment]
> > @Fan-Mi 怀疑是代理问题，换个代理吧
> 
> 哇哦，我好像发现解决方案了。比如我现在用的`https://bili.tuturu.top`，如果只把它填进首选服务器就不能用，但是除了填进首选以外，再把它填进自定义服务器的大陆里，就能用了！这是bug吗？还是就这么设计的？如果就是这么设计的也太tricky了吧

那是因为，我的服务器支持大陆的解析，你只在首选填了我的地址，又在大陆填了其他的地址，解析大陆就不会走我的服务器。你可以除了东南亚其他的都填我的服务器= =

**Comment by Fan-Mi** [comment]
> > > @Fan-Mi 怀疑是代理问题，换个代理吧
> > 
> > 
> > 哇哦，我好像发现解决方案了。比如我现在用的`https://bili.tuturu.top`，如果只把它填进首选服务器就不能用，但是除了填进首选以外，再把它填进自定义服务器的大陆里，就能用了！这是bug吗？还是就这么设计的？如果就是这么设计的也太tricky了吧
> 
> 那是因为，我的服务器支持大陆的解析，你只在首选填了我的地址，又在大陆填了其他的地址，解析大陆就不会走我的服务器。你可以除了东南亚其他的都填我的服务器= =

(8.2.1版本) 并不是，在我上面的回复里，我填了首选以后，其他区域全都没填。我反复测试了好几遍，只填首选（其他留空）确实不能用。必须要首选+大陆都填才能用。

**Comment by AisukaYuki** [comment]
> 其他区域全都没填。我反复测试了好几遍，只填首选（

这是因为，首选服务器没加area参数，在我分服务器上面，默认会分配到香港线路去解析。（我不可能默认大陆解析）
你再大陆那里填了，请求参数里面就会带有area=cn，我的服务器就会去用国内线路请求响应。
因为好几个服务器都是多个地区合一的，所以必须要有地区参数才能按地区正常解析。首选地址主要还是为了服务大陆解析其他地方的，所以也不会默认带cn参数。这是没办法的，你海外要解析大陆就必须在大陆那里填上。特别是漫游上面标明了多地区的服务器你就得在对应的地区栏填上。
