### ISSUE TITLE
泰区提示：{"code":10,"message":"地球上找不到该内容哦 (╥﹏╥) "}，无法加载播放页面

### ISSUE THREAD

**Issue by pokedo0** [ipcjs/bilibili-helper#839]
脚本问题：@ipcjs

## 描述

泰区提示：{"code":10,"message":"地球上找不到该内容哦 (╥﹏╥) "}
页面无法加载脚本设置页面

![image](https://user-images.githubusercontent.com/23151451/124822592-fd589a80-df67-11eb-9598-1f37c4b8b72c.png)

**服务器设置可以正常看网页港澳大陆 / 手机端同一个服务器可以看泰区，唯独泰区网页端失效**

- 问题网址：均为泰区，可以从番剧追番入口进去
- 
![image](https://user-images.githubusercontent.com/23151451/124821769-02691a00-df67-11eb-9d65-eba0cf80941a.png)

- https://www.bilibili.com/bangumi/play/ss34529 (禁书目录)
- https://www.bilibili.com/bangumi/play/ss37520 (出包女王) https://www.bilibili.com/bangumi/media/md28233196  (bangumi入口)
 

## 日志

<details>
<summary>Verbose 日志</summary>

```
播放页面无法加载，直接404

```
 
</details>

## 其他

**脚本设置：可以正常看港澳大陆**
![image](https://user-images.githubusercontent.com/23151451/124822412-c4202a80-df67-11eb-9d6a-1f8f95ab3f4b.png)

![image](https://user-images.githubusercontent.com/23151451/124824600-81ac1d00-df6a-11eb-8f66-5eea82124645.png)

1. 浏览器版本： 91.0.4472.124 chrome
2. 国家/地区：境外
3. 已排除ublock等其他拓展问题

**Comment by JasonKhew96** [comment]
上一个版本没问题 ([安装](https://github.com/JasonKhew96/bilibili-helper/raw/build/scripts/bilibili_bangumi_area_limit_hack.user.js)) ( https://github.com/ipcjs/bilibili-helper/commit/e0132b935d359fecf7895ade8970f091555e07d3 )，怀疑 https://github.com/ipcjs/bilibili-helper/pull/833 搞炸了


`https://www.bilibili.com/bangumi/play/ss34529`
![image](https://user-images.githubusercontent.com/29531167/124855865-2d418580-dfdc-11eb-9eec-44d699ea9fb1.png)

`https://www.bilibili.com/bangumi/play/ss37520`
![image](https://user-images.githubusercontent.com/29531167/124856112-8ad5d200-dfdc-11eb-8555-605a2dff9e24.png)
