### ISSUE TITLE
泰区网页播放卡顿

### ISSUE THREAD

**Issue by pokedo0** [ipcjs/bilibili-helper#841]
脚本问题：@ipcjs

## 描述

即使360p依然会卡，视频码率大概不过700kb，网速基本能保证1000kb以上，但还是不断卡顿。
同一服务器和番剧在手机端可正常播放。

![image](https://user-images.githubusercontent.com/23151451/124972798-af549d00-e022-11eb-8c02-46c1544bf185.png)

https://user-images.githubusercontent.com/23151451/124972481-52f17d80-e022-11eb-8c48-314704c915c9.mp4

- 问题网址：
- https://www.bilibili.com/bangumi/play/ss34529 (禁书目录)

## 日志

<details>
<summary>Verbose 日志</summary>

```
设置按钮无了

```
 
</details>

![image](https://user-images.githubusercontent.com/23151451/124973270-386bd400-e023-11eb-8015-2f6be751cdf5.png)

## 其他

1. 浏览器版本： 91.0.4472.124 chrome
2. 国家/地区：境外
3. 已排除ublock等其他拓展问题

**Comment by ShuiLinzi** [comment]
你怎么进去的泰国版番剧的网页啊？

**Comment by BraveSail** [comment]
正常情况 akamai的问题 [即使在官网看也是会卡](https://www.biliintl.com/en/play/34529) 不是脚本问题

可以等替换泰区upos的功能出来

或者用[漫游](https://github.com/yujincheng08/BiliRoaming)看
