### ISSUE TITLE
8.2.3打开番剧显示 非常抱歉，根据版权方要求 您所在的地区无法观看本片

### ISSUE THREAD

**Issue by 11Ye** [ipcjs/bilibili-helper#843]
脚本问题：@ipcjs

## 描述

从索引打开番剧后。播放器位置显示 非常抱歉，根据版权方要求 您所在的地区无法观看本片
访问时已挂好梯子。试过清理cookie及缓存。
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by 11Ye** [comment]
已解决，清理cookie及缓存后没有添加自定义服务器。

**Comment by feitiandedapao** [comment]
> 已解决，清理cookie及缓存后没有添加自定义服务器。

您好，清理了cookie没有解决，请问自定义服务器如何看

**Comment by 11Ye** [comment]
> > 已解决，清理cookie及缓存后没有添加自定义服务器。
> 
> 您好，清理了cookie没有解决，请问自定义服务器如何看

你好，视频页面右下方会有个小地球一样的图标，点进去之后就能看到自定服务器了，地址你可以在上方的蓝色小字的连接里找到。
