### ISSUE TITLE
增加对哔哩哔哩番剧出差空间页面支持

### ISSUE THREAD

**Issue by snowlocked** [ipcjs/bilibili-helper#846]
访问 https://space.bilibili.com/11783021

走代理时出差的空间是正常的
![image](https://user-images.githubusercontent.com/19562649/125293237-cf070080-e355-11eb-94b5-80a61859f901.png)

大陆访问时出差的空间就404了
![image](https://user-images.githubusercontent.com/19562649/125293487-0d042480-e356-11eb-91a9-15d86566af5b.png)

**Comment by BraveSail** [comment]
https://search.bilibili.com/upuser?keyword=%E7%95%AA%E5%89%A7%E5%87%BA%E5%B7%AE

https://bangumi.jasonkhew96.eu.org/bilibili/

**Comment by wxp203** [comment]
我也想来反馈的，能加一个空间调用代理就好了

**Comment by miyouzi** [comment]
@ipcjs 根据哔哩漫游那边了解的情况，稿件列表API正常，只是UP信息不返回了。漫游那边是通过把UP信息写死实现出差页面显示。脚本这边或许可以参考看看（又又又要重建页面了）

**Comment by HuangLuxuan** [comment]
要是有个代理服务器就好办了。。。

**Comment by HuangLuxuan** [comment]
检查了一下
获取投稿的api是可用的https://api.bilibili.com/x/space/arc/search?mid=11783021
获取动态的api是可用的https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?host_uid=11783021
只有获取up信息的api是不可用的https://api.bilibili.com/x/space/acc/info?mid=11783021

**Comment by HuangLuxuan** [comment]
我魔改了一个版本可以用https://pan.baidu.com/s/1SJRtG_hc3Bh1Wguo90dGFQ
提取码h3tu

**Comment by xxkknn** [comment]
> 我魔改了一个版本可以用https://pan.baidu.com/s/1SJRtG_hc3Bh1Wguo90dGFQ
> 提取码h3tu

~~老哥 我把你增加的那部分代码add到新版里面了，但未生效，不知问题出在哪里
看起来像是最初的判断部分不成立~~
解决了，漏了个include……

**Comment by HuangLuxuan** [comment]
> > 我魔改了一个版本可以用https://pan.baidu.com/s/1SJRtG_hc3Bh1Wguo90dGFQ
> > 提取码h3tu
> 
> 老哥 我把你增加的那部分代码add到新版里面了，但未生效，不知问题出在哪里
> 看起来像是最初的判断部分不成立

你把你改完的版本发我测试一下

以及你试试我发的这个版本直接能不能用

**Comment by xxkknn** [comment]
> > > 我魔改了一个版本可以用https://pan.baidu.com/s/1SJRtG_hc3Bh1Wguo90dGFQ
> > > 提取码h3tu
> > 
> > 
> > 老哥 我把你增加的那部分代码add到新版里面了，但未生效，不知问题出在哪里
> > 看起来像是最初的判断部分不成立
> 
> 你把你改完的版本发我测试一下
> 
> 以及你试试我发的这个版本直接能不能用

解决了，漏了个include…… 谢谢老哥

**Comment by xcr1234** [comment]
https://github.com/ipcjs/bilibili-helper/pull/873
