### ISSUE TITLE
电脑无法访问反代服务器，但手机可以

### ISSUE THREAD

**Issue by adamshawnmy** [ipcjs/bilibili-helper#847]
脚本问题：@ipcjs

## 描述
电脑无法访问反代服务器，但手机可以

- 问题网址：
https://www.bilibili.com/bangumi/play/ss39024

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss39024
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"仰望--空","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?cid=369561496&qn=116&type=&otype=json&fourk=1&bvid=BV1Pf4y1j79o&ep_id=408842&fnver=0&fnval=80&session=1a5229dd87339d3e34117c148cc6caad&module=bangumi&area=hk&access_key=bc81edd4aa614f39087a9bf0101a4f71
debug: atRun: 2, complete
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=undefined&cid=369561496&bvid=BV1Pf4y1j79o&qn=116&type=&otype=json&ep_id=408842&fourk=1&fnver=0&fnval=80&session=f36919e8b3d9151e1ef3f7d5a75fcdf1&module=bangumi&balh_ajax=1&area=hk&access_key=bc81edd4aa614f39087a9bf0101a4f71
debug: /x/web-interface/nav {"uname":"仰望--空","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：edge
2. 国家/地区：港澳台

**Comment by adamshawnmy** [comment]
这是自建的反代
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss39024
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"仰望--空","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.6z.fan/pgc/player/web/playurl?cid=369561496&qn=116&type=&otype=json&fourk=1&bvid=BV1Pf4y1j79o&ep_id=408842&fnver=0&fnval=80&session=34668d65f3ff0e3a74da5932381a6f64&module=bangumi&area=hk&access_key=262979752007b3ffb35e3f4c2ef80571
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.6z.fan/pgc/player/web/playurl?cid=369561496&qn=116&type=&otype=json&fourk=1&bvid=BV1Pf4y1j79o&ep_id=408842&fnver=0&fnval=80&session=34668d65f3ff0e3a74da5932381a6f64&module=bangumi&area=&access_key=262979752007b3ffb35e3f4c2ef80571
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.6z.fan/pgc/player/web/playurl?avid=undefined&cid=369561496&bvid=BV1Pf4y1j79o&qn=116&type=&otype=json&ep_id=408842&fourk=1&fnver=0&fnval=80&session=549a751be5cce2e3d8d0fcd16c5333fd&module=bangumi&balh_ajax=1&area=hk&access_key=262979752007b3ffb35e3f4c2ef80571
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.6z.fan/pgc/player/web/playurl?avid=undefined&cid=369561496&bvid=BV1Pf4y1j79o&qn=116&type=&otype=json&ep_id=408842&fourk=1&fnver=0&fnval=80&session=549a751be5cce2e3d8d0fcd16c5333fd&module=bangumi&balh_ajax=1&area=&access_key=262979752007b3ffb35e3f4c2ef80571
debug: /x/web-interface/nav {"uname":"仰望--空","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.6z.fan/pgc/player/web/playurl?avid=undefined&cid=365699191&bvid=BV1SV411W7fD&qn=116&type=&otype=json&ep_id=408841&fourk=1&fnver=0&fnval=80&session=48689174eb4ebe5eebc47e742602bf21&module=bangumi&balh_ajax=1&area=hk&access_key=262979752007b3ffb35e3f4c2ef80571
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.6z.fan/pgc/player/web/playurl?avid=undefined&cid=365699191&bvid=BV1SV411W7fD&qn=116&type=&otype=json&ep_id=408841&fourk=1&fnver=0&fnval=80&session=48689174eb4ebe5eebc47e742602bf21&module=bangumi&balh_ajax=1&area=&access_key=262979752007b3ffb35e3f4c2ef80571
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67

**Comment by JasonKhew96** [comment]
```json
{"code":1,"message":"代理服务器已转移至域名https://repost.98e.org"}
```

```
404 Not Found
```

**Comment by adamshawnmy** [comment]
已解决，vps配置问题
