### ISSUE TITLE
国内vps自建nginx反代是否需要取得备案？

### ISSUE THREAD

**Issue by gusya-soc** [ipcjs/bilibili-helper#848]
脚本问题：@ipcjs

## 描述

已经取得了证书，证书配置方面应该没什么问题。vps是腾讯云广东的，所以域名指向后会跳转到未备案。好像国内的ip地址都会有这个问题，各位都是备案了的吗？

我的理解是通过在国内的机器反代，得到解析地址从而播放的。还是说有境外vps也可以反代的方法？
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.3 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss36170
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://watchbilibili.bar/pgc/player/web/playurl?cid=277305964&qn=120&type=&otype=json&fourk=1&bvid=BV1oo4y1d7R7&ep_id=374000&fnver=0&fnval=80&session=f776c471fd4cd6fb528e01f80d49f036&module=bangumi&area=&access_key=2576de0ef49c612ac8d01a6b0ea8bb71
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"xxx","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://watchbilibili.bar/pgc/player/web/playurl?avid=undefined&cid=277305964&bvid=BV1oo4y1d7R7&qn=120&type=&otype=json&ep_id=374000&fourk=1&fnver=0&fnval=80&session=03dc8f0fbfa304b16fd6c9134e9d304f&module=bangumi&balh_ajax=1&area=&access_key=2576de0ef49c612ac8d01a6b0ea8bb71
debug: /x/web-interface/nav {"uname":"xxx","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```

</details>
<details>
 <summary>nginx.conf</summary>

        
         events
         {
             worker_connections 1024;
         }
         http
         {
         server
         {
             server_name watchbilibili.bar; # 设置域名为bili.example
        
             #listen 443 ssl http2;          # 务必使用https，如有需要也可以同时监听ipv6
             listen 443;
             client_max_body_size 128M;
        
             location /pgc/player/api/playurl {  # 只反向代理该路径的请求
               proxy_pass https://api.bilibili.com;  # 转发到b站服务器
             }
             location /pgc/player/web/playurl {
               proxy_pass https://api.bilibili.com;
             }
        
             ssl_certificate     /home/ubuntu/nginx/bilibiliproxy/cert/cert.pem;  # 证书路径
             ssl_certificate_key /home/ubuntu/nginx/bilibiliproxy/cert/key.pem;
             ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
             ssl_ciphers         HIGH:!aNULL:!MD5;
        
         }
         server
         {
             server_name watchbilibili.bar;
             listen 80;
        
             location / {
                 root .;
             }
         }
         }

</details>

## 其他

1. 浏览器版本： Chrome/91.0.4472.124
2. 国家/地区：日本

**Comment by adamshawnmy** [comment]
你是海外用户么，海外用户不清楚是否要备案

**Comment by AisukaYuki** [comment]
提供你一个可能可行的方法，使用非80，443端口搭建一个socks或者http代理，再去买个域名使用cloudflare接入，再使用cf的workrs反代ip:port转发请求到国内vps,蛮复杂的。或者，买一个国外的空间或vps做跳板，反代ip:port。如果只是你一个人用，更绝的方法，你直接本地host一个假的域名直接指向vps的ip。

**Comment by AisukaYuki** [comment]
尝试使用非80 443 端口搭建web服务反代bilibiliapi，应该就能跳过备案了吧，~~但是就是不知道脚本支不支持带端口的地址。~~
（#748）可以用

**Comment by gusya-soc** [comment]
> 你是海外用户么，海外用户不清楚是否要备案


用这个脚本肯定是海外用户啊。vps是腾讯云境内的。目前的政策是只要是目标服务器在国内，访问443，80端口，就会跳转到备案页面。和dns解析商，服务器在哪申请的没有关系。

**Comment by gusya-soc** [comment]
> 尝试使用非80 443 端口搭建web服务反代bilibiliapi，应该就能跳过备案了吧，~但是就是不知道脚本支不支持带端口的地址。~
> （#748）可以用

是的，我尝试使用自定义端口号，并且在防火墙里放行后，一切正常了。谢谢。

对于nginx来说，仅仅只需要把配置文件里的
`
listen 433;
`

改成你想要的端口就行了。
