### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by laaaanc** [ipcjs/bilibili-helper#849]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：91.0.4472.124
2. 国家/地区：中国
如图所示

**Comment by HuangLuxuan** [comment]
你这。。。问了个寂寞。。。
