### ISSUE TITLE
随机看到16秒影片

### ISSUE THREAD

**Issue by jacky96923** [ipcjs/bilibili-helper#850]
如题

最近经常遇到16秒的情况：
## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}
换了几个伺服器也于事无补

不过最奇怪的是這情况通常隔一两天，没有改任何东西就自己好起来了，可以正常播放。。。

多谢作者！

**Comment by hezheka** [comment]
近几天又这样了！！有一个别的类似的插件也是同步发生这个问题，然后它今天更新了一下就可以了。但我不想用那个，还是这个用自己的服务器放心。。。。
