### ISSUE TITLE
已下载最新版Chrome但是无法显示操作页面，脚本使用黑猴运行

### ISSUE THREAD

**Issue by xujames0704** [ipcjs/bilibili-helper#851]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by xujames0704** [comment]
我直接下载了脚本之后开的B站，是不是因为我开着VPN的关系
但是我把代理停了也打不开设置界面
查了一下代码，有好多报错的

**Comment by BraveSail** [comment]
为什么交白卷
