### ISSUE TITLE
Microsoft Edge浏览器没有设置界面，用不了

### ISSUE THREAD

**Issue by six220mao** [ipcjs/bilibili-helper#856]
确定是HTLM5播放器
Microsoft Edge
版本 92.0.902.62 (官方内部版本) (64 位)
Microsoft Edge 是最新版本。

**Comment by Happyday249** [comment]
同问，顺便问下怎么确认是HTML5 qwq

**Comment by six220mao** [comment]
> 同问，顺便问下怎么确认是HTML5 qwq

因为最新版Microsoft Edge浏览器已经把Flash完全移除了，只有HTML5，还有谷歌和火狐浏览器也是的。

**Comment by PrinceYueLu-Wang** [comment]
在浏览器控制台/console内输入  bangumi_area_limit_hack.showSettings()
