### ISSUE TITLE
无法使用脚本，电脑小白，看了一大圈github的连接一脸懵逼。

### ISSUE THREAD

**Issue by xiaoshuvole** [ipcjs/bilibili-helper#857]
脚本问题：@ipcjs

## 描述

- 问题网址：bilibili.com

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep409585
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"某只小鼠","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=889450908&cid=378835297&qn=0&fnver=0&fnval=80&fourk=1&ep_id=409585&session=d1eadb8a40176956be48c829b624e7b3&module=bangumi
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=889450908&cid=378835297&qn=0&fnver=0&fnval=80&fourk=1&ep_id=409585&session=d1eadb8a40176956be48c829b624e7b3&module=bangumi&area=cn
debug: /x/web-interface/nav {"uname":"某只小鼠","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=889450908&cid=378835297&qn=0&fnver=0&fnval=80&fourk=1&ep_id=409585&session=d1eadb8a40176956be48c829b624e7b3&module=bangumi
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
 
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他
我能看到评论，甚至开头的一些弹幕。但是看不了番剧。写的是内容不和谐。。。。。试了好久了不知道怎么解决。

1. 浏览器版本：Version 92.0.4515.107 (Official Build) (64-bit)
2. 国家/地区： USA

**Comment by AisukaYuki** [comment]
脚本设置下部分帐号授权一下，不授权不给看，还有aliyuncs这个已经失效了。

**Comment by xiaoshuvole** [comment]
> 脚本设置下部分帐号授权一下，不授权不给看，还有aliyuncs这个已经失效了。

设置了授权，还是不行。现在不知道哪个代理服务器能用。。。。

**Comment by AisukaYuki** [comment]
> > 脚本设置下部分帐号授权一下，不授权不给看，还有aliyuncs这个已经失效了。
> 
> 设置了授权，还是不行。现在不知道哪个代理服务器能用。。。。

你用的就是我的服务器tuturu.top这个 大陆请求是正常的，log贴一下，你上面的log里面，请求没有包含access_key请求会被我拒绝`{"code":-10403,"message":"抱歉您已被封锁:1.请检查登录授权状态;2.确认账号是否被服务器封禁;3.请勿使用非法方式获取解析;4.仅支持大陆、港澳台，不支持东南亚区。如有疑问请联系服务器提供者https://bili.tuturu.top;"}`

**Comment by xiaoshuvole** [comment]
> > > 脚本设置下部分帐号授权一下，不授权不给看，还有aliyuncs这个已经失效了。
> > 
> > 
> > 设置了授权，还是不行。现在不知道哪个代理服务器能用。。。。
> 
> 你用的就是我的服务器tuturu.top这个 大陆请求是正常的，log贴一下，你上面的log里面，请求没有包含access_key请求会被我拒绝`{"code":-10403,"message":"抱歉您已被封锁:1.请检查登录授权状态;2.确认账号是否被服务器封禁;3.请勿使用非法方式获取解析;4.仅支持大陆、港澳台，不支持东南亚区。如有疑问请联系服务器提供者https://bili.tuturu.top;"}`

噢噢噢噢，我发现问题了。现在能用了！！！！啊跪谢！！！！太感谢了！！！！

**Comment by xiaoshuvole** [comment]
> https://bili.tuturu.top

。。。。好像又出问题了。。。昨天重装了一次chrome，然后又用不上了。授权了还是有问题。。。


我有点晕了。。。。


debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.4 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep409819
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"某只小鼠","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=974620455&cid=381641256&qn=0&fnver=0&fnval=80&fourk=1&ep_id=409819&session=971d90fa018c8d15ed2a6c4b72a04374&module=bangumi&area=&access_key=0c7e512e5838c6c9234b440f18205981
debug: /x/web-interface/nav {"uname":"某只小鼠","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: atRun: 2, complete
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=974620455&cid=381641256&qn=0&fnver=0&fnval=80&fourk=1&ep_id=409819&session=971d90fa018c8d15ed2a6c4b72a04374&module=bangumi&access_key=0c7e512e5838c6c9234b440f18205981
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

**Comment by AisukaYuki** [comment]
你要在对应地区框填上我的地址，不仅仅是首选，因为首选默认不带area参数，经过我的服务器之后是我是默认分配到hk线路去解析的。然而你是在海外，请求大陆的番剧则需要area=cn的参数。所有必须要在对应的地区框内填上服务器地址我的支持港台大陆，你可以除了东南亚的框以外全都填上我的。

**Comment by AisukaYuki** [comment]
![9C8C112A-16C0-4A5E-A470-12FE2E214DC8](https://user-images.githubusercontent.com/17586327/128100269-86a68327-b642-410f-8387-39cea54a0e12.png)在你给的log里的解析链接加上&area=cn后，正常得到结果

**Comment by xiaoshuvole** [comment]
> ![9C8C112A-16C0-4A5E-A470-12FE2E214DC8](https://user-images.githubusercontent.com/17586327/128100269-86a68327-b642-410f-8387-39cea54a0e12.png)在你给的log里的解析链接加上&area=cn后，正常得到结果

😂😂😂😂我的妈，原来还要这样。。。填好了确实就行了。。太感谢了。。。这个真的弄得我头的秃了，以为又出什么差错了。。。

**Comment by seeroffish** [comment]
> ![9C8C112A-16C0-4A5E-A470-12FE2E214DC8](https://user-images.githubusercontent.com/17586327/128100269-86a68327-b642-410f-8387-39cea54a0e12.png)在你给的log里的解析链接加上&area=cn后，正常得到结果


大佬您好想问一下填了你的地址以后会不断重复这几个要怎么办鸭

获取视频参数... [成功]
播放器初始化... [成功] 3.0.4-rc.1-2c0dae5e
获取播放地址... [成功]
加载视频信息...
抛出一个错误... 4004;[Dash] 403 downloadError - https://upos-sz-mirrorbos.bilivideo.com/upgcxcode/37/77/140217737/140217737_da8-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1629264765&gen=playurlv2&os=vcache&oi=1943981518&trid=0001b090f975eaf14ed28465606b9c051b42p&platform=pc&upsig=5c23d3a036a2c5cbeff3feb97a639502&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&cdnid=22220&orderid=0,3&agrr=0&logo=80000000
获取播放地址... [成功]
加载内容超时... 请尝试禁用所有浏览器插件后，刷新本页面
加载视频信息...
抛出一个错误... 4004;[Dash] 403 downloadError - https://upos-sz-mirrorbos.bilivideo.com/upgcxcode/37/77/140217737/140217737_da8-1-30032.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1629264765&gen=playurlv2&os=vcache&oi=1943981518&trid=0001b090f975eaf14ed28465606b9c051b42p&platform=pc&upsig=8e9b030aea0e4d554cec1beefbe816a0&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&cdnid=6593&orderid=0,3&agrr=0&logo=80000000

**Comment by JasonKhew96** [comment]
@seeroffish 换 upos 试试
