### ISSUE TITLE
今天突然发现我大会员用不了结果是讲我ip换太多次给我冻结了这是怎么回事？

### ISSUE THREAD

**Issue by suiyidr** [ipcjs/bilibili-helper#862]
如题

**Comment by JasonKhew96** [comment]
都说是 代理服务器 了，你 授权 登录 后，将会用你的 大会员 帐号 在 代理服务器 里 请求 番剧 播放链接
帐号冻结 也不意外

**Comment by suiyidr** [comment]
> 都说是 代理服务器 了，你 授权 登录 后，将会用你的 大会员 帐号 在 代理服务器 里 请求 番剧 播放链接
> 帐号冻结 也不意外

原来如此，这个代理脚本我用了快大半年了才发生这种事

**Comment by suiyidr** [comment]
> > 都说是 代理服务器 了，你 授权 登录 后，将会用你的 大会员 帐号 在 代理服务器 里 请求 番剧 播放链接
> > 帐号冻结 也不意外
> 
> 原来如此，这个代理脚本我用了快大半年了才发生这种事，不过还好冻结了手机上还是可以快速解冻。
