### ISSUE TITLE
本地的vpn app没法作为代理服务器

### ISSUE THREAD

**Issue by miku1958** [ipcjs/bilibili-helper#864]
脚本问题：@ipcjs

## 描述
本地搭建的vpn没法作为代理服务器
使用的是clash, 代理地址是http://127.0.0.1:7890, 每次填入都会变成https, 但是本地代理应该是没法用https的

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by AisukaYuki** [comment]
网站https，http也没发用。你直接在clash里面对b站的api分流就行了。何必多此一举

**Comment by miku1958** [comment]
因为懒, 看国内能看的番和看港澳台的番得切来切去

**Comment by AisukaYuki** [comment]
你直接改http://127.0.0.1:7890 也没用，请求会走/pgc/player/web/playurl，要先反代路径，或者全局反代整个api.bilibili.com。不然请求发起的是http://127.0.0.1:7890 /pgc/player/web/ 结果也只会404而已。你可以本地做一个nginx反代，生成一个证书本地信任，然后hosts一个假域名，填到脚本里域名加到clash规则里面走代理。（反正就是多此一举，反而麻烦

**Comment by AisukaYuki** [comment]
脚本不是简单的走一个代理就完了的，发起的请求是先通过解析服务器处理转发请求到b站api再返回结果的。

**Comment by Jingyu-Yan** [comment]
@AisukaYuki 我想问下，在win10里使用clash代理，并且尝试代理哔哩哔哩或全局，都是显示“所在地区无法观看”，但是安卓app直接切换全局代理到香港马上就能看了，请问我电脑上还需要怎么操作吗
