### ISSUE TITLE
没有设置窗口或者对应的按钮选项

### ISSUE THREAD

**Issue by MilarvozM** [ipcjs/bilibili-helper#866]
脚本问题：@ipcjs

## 描述

用的的确是最新版的chrome，但是打开都没弹出那个设置窗口，也找不到地方。以前是记得确实有这个东西可以设置的

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Version 92.0.4515.131 (Official Build) (64-bit)
2. 国家/地区：美国西部

**Comment by jiaxinonly** [comment]
![image](https://user-images.githubusercontent.com/57223696/129202095-56bf0ffb-8d07-46ca-a457-fe55fc87b391.png)
