### ISSUE TITLE
能否给出一个正确简单的nginx配置？

### ISSUE THREAD

**Issue by jiaxinonly** [ipcjs/bilibili-helper#867]
脚本问题：@ipcjs

## 描述

请问能否给出一个正确简单的nginx配置，做为标准教程，放入README中？
我的服务器在香港，按照给出的nginx配置，无法正常使用
配置如下
```
server
{
    server_name bilibili.accepted.fun;
    
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    client_max_body_size 128M;

    location /pgc/player/api/playurl { 
                proxy_pass https://api.bilibili.com;
    }

    location /pgc/player/web/playurl {
                proxy_pass https://api.bilibili.com;
    }

    ssl_certificate /usr/local/nginx/conf/cert/bilibili.accepted.fun.pem;
    ssl_certificate_key /usr/local/nginx/conf/cert/bilibili.accepted.fun.key;
    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /usr/local/nginx/conf/cert/dhparam.pem; # managed by Certbot
}

```
能够看到弹幕，但是无法观看视频
![image](https://user-images.githubusercontent.com/57223696/129196431-f50ef5ab-660f-48a6-a0d9-2ee4055e1051.png)

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by JasonKhew96** [comment]
这里有，改一改就可以了，去掉参数验证（东南亚的好像不完整）
https://github.com/yujincheng08/BiliRoaming/wiki/%E8%87%AA%E5%BB%BA%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by JasonKhew96** [comment]
哦，忘了，有 CORS 问题，自己加返回头

**Comment by jiaxinonly** [comment]
已经弄好了，哪个视频是仅限台湾的，以为用不了。。。。

**Comment by JasonKhew96** [comment]
> 已经弄好了，哪个视频是仅限台湾的，以为用不了。。。。

https://www.bilibili.com/bangumi/media/md5551

**Comment by jiaxinonly** [comment]
对，就是这个，看不了，以为是配置的原因，搞了半天，结果是仅限台湾。。。。
