### ISSUE TITLE
本视频由以下原因导致无法播放

### ISSUE THREAD

**Issue by miraclestar43** [ipcjs/bilibili-helper#874]
脚本问题：@ipcjs

## 描述

看番剧黑屏，提示本视频由以下原因导致无法播放（个人猜测无法获取播放地址）
插件弹出以下错误

 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":4,"responseText":"\n\n\n\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n\n\n\n    
\n    
\n        
\n            \n            
\n              返回上一页\n            
\n        
\n        
\n        
\n        
\n        
\n    
\n    
\n        \"parse\n        
\n            Σ(oﾟдﾟoﾉ) 无法找到该页面~\n        
\n    
\n    \n    \n\n\n\n","status":404,"statusText":"error"}}

- 问题网址：
https://www.bilibili.com/bangumi/play/ep409824

## 日志

<details>
<summary>Verbose 日志</summary>

```
 debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep409824?spm_id_from=444.41.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"Star照我去战斗","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=462846737&bvid=BV13L411t7ir&cid=404200920&qn=116&fnver=0&fnval=80&fourk=1&ep_id=409824&session=d1c785d5a4204befa709dffbf01d7b5b&module=bangumi&area=&access_key=bce816e4962c6442f68b0ef0f724e491
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"Star照我去战斗","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://biligo.org/pgc/player/web/playurl?avid=462846737&bvid=BV13L411t7ir&cid=404200920&qn=116&fnver=0&fnval=80&fourk=1&ep_id=409824&session=d1c785d5a4204befa709dffbf01d7b5b&module=bangumi&area=tw&access_key=bce816e4962c6442f68b0ef0f724e491
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: 、?avid=462846737&bvid=BV13L411t7ir&cid=404200920&qn=116&fnver=0&fnval=80&fourk=1&ep_id=409824&session=d1c785d5a4204befa709dffbf01d7b5b&module=bangumi&access_key=bce816e4962c6442f68b0ef0f724e491
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
</details>

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：chrome
2. 国家/地区：美国

**Comment by miraclestar43** [comment]
我发现我另一台电脑可以，但这台还是不行
<details>
<summary>Verbose 日志</summary>


debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.7 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss36170?t=2
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: hw flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"Star照我去战斗","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=462846737&bvid=BV13L411t7ir&cid=404200920&qn=116&fnver=0&fnval=80&fourk=1&ep_id=409824&session=ae047c89124b06237b9495bc512728a9&module=bangumi&area=&access_key=bce816e4962c6442f68b0ef0f724e491
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=462846737&bvid=BV13L411t7ir&cid=404200920&qn=116&fnver=0&fnval=80&fourk=1&ep_id=409824&session=ae047c89124b06237b9495bc512728a9&module=bangumi&area=tw&access_key=bce816e4962c6442f68b0ef0f724e491
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=462846737&bvid=BV13L411t7ir&cid=404200920&qn=116&fnver=0&fnval=80&fourk=1&ep_id=409824&session=ae047c89124b06237b9495bc512728a9&module=bangumi&access_key=bce816e4962c6442f68b0ef0f724e491
debug: /x/web-interface/nav {"uname":"Star照我去战斗","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

</details>

**Comment by JasonKhew96** [comment]
可能没设置大陆代理服务器 或 代理服务器坏了

**Comment by miraclestar43** [comment]
将所有自定义服务器填入后解决

**Comment by AisukaYuki** [comment]
https://bili.tuturu.top/pgc/player/web/playurl?avid=462846737&bvid=BV13L411t7ir&cid=404200920&qn=116&fnver=0&fnval=80&fourk=1&ep_id=409824&session=ae047c89124b06237b9495bc512728a9&module=bangumi&area=cn&access_key=bce816e4962c6442f68b0ef0f724e491

请求带区域参数，日志里面area=tw改成cn 就有结果了（我的服务器请求还挺快的说
