### ISSUE TITLE
《平家物语》页面被拦截

### ISSUE THREAD

**Issue by wdssmq** [ipcjs/bilibili-helper#875]
脚本问题：@ipcjs

## 描述
未开播但是有 pv 的番剧页无法打开？？

- 问题网址：
https://www.bilibili.com/bangumi/play/ss39347

## 截图
![QQ截图20210909094251](https://user-images.githubusercontent.com/8186642/132609477-eba05cf7-2423-46cb-b6fd-8f9f337e6db3.png)
![QQ截图20210909100545](https://user-images.githubusercontent.com/8186642/132610272-3a628e55-0f19-4a6f-a52b-6615aec28716.png)

**Comment by JasonKhew96** [comment]
用 ep 链接：https://www.bilibili.com/bangumi/play/ep419394

**Comment by wdssmq** [comment]
> 用 ep 链接：https://www.bilibili.com/bangumi/play/ep419394

然而逻辑上，我要先打开一次才能知道里边有啥分 p 视频，然后才能拿到 ep 地址 - -

**Comment by JasonKhew96** [comment]
> > 用 ep 链接：https://www.bilibili.com/bangumi/play/ep419394
> 
> 然而逻辑上，我要先打开一次才能知道里边有啥分 p 视频，然后才能拿到 ep 地址 - -

用 md 链接：https://www.bilibili.com/bangumi/media/md28235039/

ss 链接不太行（目前 东南亚 用 ss 链接，可能会导致其他 ss 链接出问题，带 “A站独播” 的都是 重建页面）

**Comment by ipcjs** [comment]
看起来是上次改重建页面的逻辑判断改错了。。。

**Comment by wdssmq** [comment]
https://www.bilibili.com/video/BV1JZ4y1c7TA

↑↑ 然后电影页又受影响了。
