### ISSUE TITLE
同样的解析服务器PC看不了东南亚地区手机漫游却可以

### ISSUE THREAD

**Issue by jiangjiale884883** [ipcjs/bilibili-helper#876]
看了控制台的错误信息：
Uncaught SyntaxError: Unexpected identifier

Access to XMLHttpRequest at 'https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/6i/s8/m210518a2os8tr6llw75lbfm9735s86i-1-211210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859IB_&uipk=5&nbs=1&deadline=1631282299&gen=playurlv2&os=akam&oi=461612212&trid=b0d90b52d8904b47a8dda374f65f5deci&platform=android&upsig=8ab7fd553e2bad1bc18a9b38035c8d8c&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1631282299~hmac=362962873f0b0f2c96d681b0e29a1eb63ac8c8228fad01109183b7635cab8875&mid=2145878105&bvc=vod&nettype=0&orderid=0,1&logo=00000000' from origin 'https://www.bilibili.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Failed to load resource: net::ERR_FAILED

Failed to load resource: the server responded with a status of 404 ()

今天刚进去的时候还能看再刷新就看不了了

1. 浏览器版本：Chrome
2. 国家/地区：大陆

**Comment by JasonKhew96** [comment]
**CORS** 问题，暂时没人会修

**Comment by satan2333** [comment]
PC端看的了泰区番剧？我之前试了几次都不行，一直以为看不了的

**Comment by satan2333** [comment]
什么时候才可以在PC端看泰区番剧啊
