### ISSUE TITLE
请问一下现在哪个方法的代理服务器还可以用

### ISSUE THREAD

**Issue by jaywong966** [ipcjs/bilibili-helper#878]
阿里云函数已经用不了了

> > 阿里云函数已经用不了了
> 
> ？可以用啊

oh 可以了 刚才翻了一下 加上/playurl就ok了

**Comment by KurosakiRei** [comment]
> 阿里云函数已经用不了了

？可以用啊

**Comment by jaywong966** [comment]
> > 阿里云函数已经用不了了
> 
> ？可以用啊

不行啊 用了这个[方法](https://github.com/ipcjs/bilibili-helper/issues/710#issuecomment-748976481) 
> debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.8 (Violentmonkey)] run on: https://www.bilibili.com/bangumi/play/ep409589
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=409589
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /x/web-interface/nav {"uname":"_Jay_w","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep409589 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://5957531454641942.cn-beijing.fc.aliyuncs.com/2016-08-15/proxy/bilibili/bilibili/?access_key=28f525cd5fb0ec66d547182ab322ee91&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=397733546&device=android&ep_id=409589&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=120&track_path=0&ts=1631537918&sign=e916aaee9c7aa969e34378a6392a87f6
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"login":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":409591,"last_ep_index":"11","last_time":0},"real_price":"0","sponsor":0,"vip_info":{"due_date":1648828800000,"status":1,"type":2}}}
debug: setAreaLimitSeason ep409589 true
debug: /x/web-interface/nav {"uname":"_Jay_w","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://5957531454641942.cn-beijing.fc.aliyuncs.com/2016-08-15/proxy/bilibili/bilibili/?access_key=28f525cd5fb0ec66d547182ab322ee91&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=397733546&device=android&ep_id=409589&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=120&track_path=0&ts=1631537920&sign=fa15dc1185781be2ed7469f7e0a94651
debug: /x/player/v2 404 {"code":0,"message":"0","ttl":1,"data":{"aid":377731428,"bvid":"BV1Xf4y1N76N","allow_bp":false,"cid":397733546,"max_limit":3000,"page_no":1,"has_next":false,"ip_info":{"ip":"58.153.81.79","zone_ip":"","zone_id":1035993088,"country":"香港","province":"","city":""},"login_mid":1967562,"login_mid_hash":"90fb4d4d","is_owner":false,"name":"_Jay_w","permission":"10000,1001","level_info":{"current_level":5,"current_min":10800,"current_exp":27945,"next_exp":28800},"vip":{"type":2,"status":1,"due_date":1648828800000,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"年度大会员","label_theme":"annual_vip","text_color":"#FFFFFF","bg_style":1,"bg_color":"#FB7299","border_color":""},"avatar_subscript":1,"nickname_color":"#FB7299","role":3,"avatar_subscript_url":"http://i0.hdslb.com/bfs/vip/icon_Certification_big_member_22_3x.png"},"answer_status":0,"block_time":0,"role":"0","last_play_time":0,"last_play_cid":0,"now_time":1631537921,"online_count":519,"subtitle":{"allow_submit":false,"lan":"","lan_doc":"","subtitles":[]},"view_points":[],"is_ugc_pay_preview":false,"preview_toast":"为创作付费，购买观看完整视频|购买观看","pcdn_loader":{"flv":{"labels":{"pcdn_video_type":"flv","pcdn_stage":"release","pcdn_group":"nil","pcdn_version":"nil","pcdn_vendor":"nil"}},"dash":{"labels":{"pcdn_video_type":"dash","pcdn_stage":"release","pcdn_group":"nil","pcdn_version":"nil","pcdn_vendor":"nil"}}},"options":{"is_360":false,"without_vip":false},"guide_attention":[],"jump_card":[],"operation_card":[],"online_switch":{"enable_gray_dash_playback":"500","new_broadcast":"1","realtime_dm":"1","subtitle_submit_switch":"1"},"fawkes":{"config_version":10048,"ff_version":0},"show_switch":{"long_progress":false}}}
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.bilibili.com/x/v2/dm/view?oid=397733546&aid=377731428&bvid=BV1Xf4y1N76N&season_id=38922&ep_id=409589&type=1
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: /intl/gateway/v2/app/subtitle?oid=397733546&aid=377731428&bvid=BV1Xf4y1N76N&season_id=38922&ep_id=409589&type=1
error: /x/player/v2 {"readyState":4,"responseText":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html lang=\"zh-cn\">\n\n<head>\n    <meta http-equiv=\"Page-Enter\" content=\"blendTrans(Duration=0.5)\">\n    <meta http-equiv=\"Page-Exit\" content=\"blendTrans(Duration=0.5)\">\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\n    <meta name=\"spm_prefix\" content=\"333.937\">\n    <title>出错啦! - bilibili.com</title>\n    <style type=\"text/css\">\n\n        html,body {\n            vertical-align: middle;\n            padding: 0;\n            margin: 0;\n        }\n\n        div.center {\n            position: absolute;\n            top: 50%;\n            left: 50%;\n            margin: -25% 0 0 -320px;\n            width: 640px;\n            min-height: 427px;\n            padding: 0px;\n        }\n\n        div.errmsg {\n            text-align: left;\n            width: 640px;\n            line-height: 150%;\n        }\n\n        a {\n            text-decoration: none;\n            color: red;\n        }\n\n        .center {\n            display: none;\n        }\n\n        .h5-container {\n            display: none;\n        }\n        @media screen and (max-width: 500px) {\n            #biliMainHeader, #internationalHeader, .error-container {\n                display: none;\n            }\n\n            .h5-container {\n                display: block;\n                position:absolute;\n                top: 50%;\n                left: 50%;\n                transform: translate(-50%, -50%);\n            }\n\n            .h5__img {\n                display: block;\n                width: 300px;\n            }\n\n            .h5__desc {\n                color: #a0a0a0;\n                text-align: center;\n            }\n        }\n    </style>\n    <link rel=\"shortcut icon\" href=\"//static.hdslb.com/images/favicon.ico\">\n    <link href=\"//static.hdslb.com/error/dist/error.css\" rel=\"stylesheet\">\n    <script type=\"text/javascript\">\n        var options = {\n            type: 'defaultError'\n        }\n\n        window.spmReportData = {};\n        window.reportConfig = {\n            sample: 1,\n            msgObjects: \"spmReportData\",\n        };\n    </script>\n    <script src=\"//s1.hdslb.com/bfs/seed/log/report/log-reporter.js\"></script>\n    <script type=\"text/javascript\" src=\"//s1.hdslb.com/bfs/static/jinkela/long/js/jquery/jquery1.7.2.min.js\"></script>\n</head>\n\n<body style=\"direction: ltr;\">\n    <div id=\"biliMainHeader\" style=\"height: 56px; background-color: #fff;\"></div>\n    <div class=\"error-container\">\n        <div class=\"error-panel server-error\">\n            <img src=\"//static.hdslb.com/error/very_sorry.png\">\n            <div style=\"text-align: center; padding: 0 0 40px 0;\">\n              <a class=\"rollback-btn\" style=\"padding: 0 20px; float: none;\">返回上一页</a>\n            </div>\n        </div>\n        <div class=\"error-split\">\n        </div>\n        <div class=\"error-manga\">\n        </div>\n    </div>\n    <div class=\"h5-container\">\n        <img class=\"h5__img\" src=\"//s1.hdslb.com/bfs/static/jinkela/long/bitmap/error_01.png\" alt=\"parse failed\">\n        <div class=\"h5__desc\">\n            <span>Σ(oﾟдﾟoﾉ) 无法找到该页面~</span>\n        </div>\n    </div>\n    <script type=\"text/javascript\" src=\"//s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js\"></script>\n    <script type=\"text/javascript\" charset=\"utf-8\" src=\"//static.hdslb.com/error/dist/error.js\"></script>\n</body>\n\n</html>\n","status":404,"statusText":"error"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36

**Comment by JasonKhew96** [comment]
@jaywong966 您怎么用 **香港** 代理看 **大陆** 番？
