### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by B0509067** [ipcjs/bilibili-helper#880]
## 拉取视频地址失败
原因: {"code":-10403,"message":"区域限制，仅支持大陆及港澳台地区,不支持东南亚解锁！并确保你的脚本设置正确，能不能给爷把在AV页启用的钩去了，WDNMD！"}
今早还可以使用，但是下午更新的时候就出现了这个，还被转到了A站独播，不知道发生了什么
![螢幕擷取畫面 2021-09-16 174245](https://user-images.githubusercontent.com/40197127/133589919-0efbe37e-3de7-4407-bafd-82a447a94fe4.png)

我的设置
![螢幕擷取畫面 2021-09-16 174245](https://user-images.githubusercontent.com/40197127/133590121-a3f62db2-61ab-42cf-80eb-18cc77ca7f1c.png)

**Comment by Outsider962** [comment]
我也一样，你换其他服务器会提示被拦截。
我这目前又能看了，但点开的时候页面会自动刷新一下，然后只有播放器正常，右边和评论区完全不加载，下面的番剧还显示的是银魂（不影响播放器里的番剧，但没法选集）。
今天上午播放器还是之前3.几的版本，下午就变成了2.67版本，然后就出现了这些问题。

当天晚上播放器变回3.1.1版本后就全部正常了，脚本最近一次更新就提到a站独播这个问题，应该就是16号下午b站突然改了下播放器版本又出现了这bug。

**Comment by AisukaYuki** [comment]
服务器没问题，附上日志。不然请自行确认问题。还有你是再海外看大陆番剧，还是看港澳台限制番剧。情况描述清楚。
