### ISSUE TITLE
港澳台地區日剧title bug问题

### ISSUE THREAD

**Issue by paigupai** [ipcjs/bilibili-helper#887]
b站在做港澳台地區的同步日剧
目前只有三部部剧
日本沉沒ー希望之人ー
https://www.bilibili.com/bangumi/play/ep425765
最愛
https://www.bilibili.com/bangumi/play/ss39674
只是在結婚申請書上蓋個章而已
https://www.bilibili.com/bangumi/play/ss39675

目前只有日本沉沒更新了一集，出现了title里有【A站独播】日本沉沒ー希望之人ー（僅限港澳台地區） AcFun弹幕视频网 - 认真你就输啦 (?ω?)ノ- ( ゜- ゜)つロ的bug，希望修正

**Comment by JasonKhew96** [comment]
泰区番剧重建页面的锅

@miyouzi

**Comment by ipcjs** [comment]
这是feature！页面被脚本重建了，不重建播不出来
