### ISSUE TITLE
换了好几个解析服务器还是加载不了视频

### ISSUE THREAD

**Issue by insaco** [ipcjs/bilibili-helper#893]
所有限制区域视频都解析失败，一直在加载中，换了好几个解析地址都是一样的

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.1 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep414712
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"日渐崩坏的节操","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"日渐崩坏的节操","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

 浏览器版本：chrome 93.0

**Comment by JasonKhew96** [comment]
没有问题，你用的谁家的 解析服务器？
![image](https://user-images.githubusercontent.com/29531167/139573613-f0b0f1d6-8a65-4f17-bea1-e00ff226e16c.png)

**Comment by insaco** [comment]
https://api.qiu.moe和哔哩.ink

**Comment by JasonKhew96** [comment]
> [https://api.qiu.moe和哔哩.ink](https://api.qiu.moe%E5%92%8C%E5%93%94%E5%93%A9.ink)

授权了没？
![image](https://user-images.githubusercontent.com/29531167/139573730-c64139d4-792b-4b02-a874-6ecc72a0a238.png)

**Comment by insaco** [comment]
![image](https://user-images.githubusercontent.com/51488565/139573781-0c4911d7-30a9-489c-8cc2-d8231a49d233.png)
授权了

**Comment by insaco** [comment]
![image](https://user-images.githubusercontent.com/51488565/139573806-67cd878a-fe8a-4e4d-8549-92617950c2e9.png)
每个视频都是一直加载然后说超时

**Comment by JasonKhew96** [comment]
> ![image](https://user-images.githubusercontent.com/51488565/139573806-67cd878a-fe8a-4e4d-8549-92617950c2e9.png) 每个视频都是一直加载然后说超时

换一下 upos
![image](https://user-images.githubusercontent.com/29531167/139573824-3e27a677-b751-42e6-8073-69ca749c0855.png)

**Comment by insaco** [comment]
试了各种办法最后把插件删掉再下载就解决了，看来是我电脑的锅，感谢感谢

**Comment by amostang** [comment]
我想请问你们都是怎么用的啊，我https://api.qiu.moe和哔哩.ink 两个都填写在自定义里面，但还是16秒视频，是不是还有填其他东西？我已经授权了

**Comment by ayasa520** [comment]
昨天还是正常的，今天也不行了

> 我想请问你们都是怎么用的啊，我[https://api.qiu.moe和哔哩.ink](https://api.qiu.moe%E5%92%8C%E5%93%94%E5%93%A9.ink) 两个都填写在自定义里面，但还是16秒视频，是不是还有填其他东西？我已经授权了

**Comment by JasonKhew96** [comment]
@amostang @ayasa520 有无日志...?

**Comment by amostang** [comment]
@JasonKhew96 啊，解决了，原来在下面四个地区也填写了就可以，之前没填写的

**Comment by ayasa520** [comment]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.10 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28235244/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=39551&access_key=f8bddba327b5ae483fb13985016a7d91
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"島村絢沙","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"島村絢沙","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"follow_status":2,"login":1,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":424270,"last_ep_index":"5","last_time":87},"real_price":"0","sponsor":0,"vip_info":{"due_date":1657468800000,"status":1,"type":2}}}
debug: season39551 {"code":0,"message":"success","result":{"actor":[{"actor":"雨宮天","actor_id":0,"role":"四谷みこ"},{"actor":"本渡楓","actor_id":0,"role":"百合川ハナ"},{"actor":"佐倉綾音","actor_id":0,"role":"二暮堂ユリア"}],"alias":"","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"5732","bangumi_title":"陰陽眼見子（僅限港澳台地區）","brief":"某天，女高中生見子突然變得可以看見那些普通人看不見的鬼怪。面對一夜之間改變的日常，她選擇“視而不見”...","business_type":1,"coins":"0","copyright":"bilibili","cover":"https://i0.hdslb.com/bfs/bangumi/image/637aa8c875a5be5a222be01555f471310950af44.png","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"633774348","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/55a2d8aa0f3ff448e9c7da2f36121bd1a79a3ff6.png","danmaku":"432733573","episode_id":"424270","episode_status":2,"episode_type":0,"from":"bangumi","index":"5","index_title":"我也看得見","is_new":"1","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-31 22:00:01.0"},{"av_id":"806200296","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/9556155676470f71451f944ddfa2034597891368.png","danmaku":"429046442","episode_id":"424269","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"果然看得見","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-24 22:00:01.0"},{"av_id":"721036206","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/68910134a26b86dbc3e492618d9098af2a537a6c.png","danmaku":"425405147","episode_id":"424268","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"還是看得見","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-17 22:00:01.0"},{"av_id":"806033832","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/83da68f6d0e79b0edea30a8cd0692c9a4c71476f.png","danmaku":"422962184","episode_id":"424267","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"看得超清楚","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-10 22:00:01.0"},{"av_id":"890835316","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/777a75a9f3f5475e950057ce02bf37189f8d41e9.png","danmaku":"417509118","episode_id":"424266","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"看得見嗎","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-10-03 22:00:01.0"}],"evaluate":"某天，女高中生見子突然變得可以看見那些普通人看不見的鬼怪。面對一夜之間改變的日常，她選擇“視而不見”，假裝看不見那些東西來生活下去。","favorites":"0","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/637aa8c875a5be5a222be01555f471310950af44.png","episode_index":{"index_show":"连载中, 每週日更新"},"media_id":28235244,"publish":{"is_finish":0,"is_started":1},"title":"陰陽眼見子（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"424270","newest_ep_index":"5","origin_name":"","play_count":"0","pub_string":"","pub_time":"2021-10-03 00:00:01","pub_time_show":"10月3日 00:00 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"39551","season_status":2,"season_title":"TV","seasons":[{"bangumi_id":"5732","cover":"https://i0.hdslb.com/bfs/bangumi/image/637aa8c875a5be5a222be01555f471310950af44.png","is_finish":"0","is_new":"1","newest_ep_id":"424270","newest_ep_index":"5","season_id":"39551","season_status":2,"title":"TV"}],"share_url":"http://bangumi.bilibili.com/anime/39551/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/56d45e56bea3874bc131f1a7f3c33e6cc7276b52.png","staff":"原　　作：泉朝樹\n監　　督：小川優樹\n助監督　：間島祟寛\n監督補佐：松島慎太郎（魚雷映蔵）\n系列構成：猪原健太\n角色設定・總作畫監督：嘉手苅睦\n配角設定：亀谷響子、蟄居太、Tin\n怪物設定：うのまこと、森木靖泰、蟄居太、平田雄三、飯島弘也、小田裕康（スタジオもがな）\n道具設定：うめつゆきのり\n服裝設定：高品有桂\n總作畫監督：柳沢まさひで、橋本英樹、平田雄三、亀谷響子、高品有桂\n編　　集：丹彩子\n色彩設計：歌川律子\n美術設定：岩澤美翠（KUSANAGI）、渡辺伸（エカチエピルカ）\n美術監督：岡本綾乃（KUSANAGI）\n概念整合：高津純平\n撮影監督：楊暁牧（グラフィニカ）\n音　　樂：うたたね歌菜\n音樂製作：KADOKAWA\n音響監督：郷文裕貴\n音響効果：宅間麻姫（スワラ・プロ）\n音響制作：マジックカプセル\n動畫製作：Passione","tag2s":[],"tags":[],"title":"陰陽眼見子（僅限港澳台地區）","update_pattern":"每週日更新","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.18 Safari/537.36 Edg/96.0.1054.5

https://api.qiu.moe 试了一下是超时，不过坚持不懈地刷新能解析到。别的几个好像是“非常抱歉”的那个16秒视频
就在写这句话的时候，原本显示超时的视频解析出来了。。。应该不是脚本的问题

**Comment by JasonKhew96** [comment]
@ayasa520 可以试试换 upos 
![image](https://user-images.githubusercontent.com/29531167/139690280-2ae45eb6-46b5-4048-9ecd-16b7f234ae66.png)

**Comment by ayasa520** [comment]
挨个试了下，能解析出来，就是速度慢，可能今天网络不太好
