### ISSUE TITLE
阿里腳本失效了嗎?

### ISSUE THREAD

**Issue by linty1997** [ipcjs/bilibili-helper#899]
很久一段時間沒開上來看了, 今天打開就發現無法正常使用
![image](https://user-images.githubusercontent.com/40823034/140609392-d6dba406-6609-45ab-a373-04cbbcbe77a0.png)

**Comment by BraveSail** [comment]
https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by SimonChan1070** [comment]
我的阿里都掛了
