### ISSUE TITLE
用脚本打开進擊的巨人: Wall Sina,Goodbye会跳转到A站独播

### ISSUE THREAD

**Issue by suiyidr** [ipcjs/bilibili-helper#900]
用脚本打开進擊的巨人: Wall Sina,Goodbye会跳转到A站独播

**Comment by BraveSail** [comment]
feature

**Comment by ipcjs** [comment]
这不是feature嘛？显示不出来的页面会重建，有啥问题？

**Comment by suiyidr** [comment]
![image](https://user-images.githubusercontent.com/87166323/140903847-cf5f036e-6f77-4b38-b3f6-ec5520ef47f8.png)

**Comment by JasonKhew96** [comment]
> ![image](https://user-images.githubusercontent.com/87166323/140903847-cf5f036e-6f77-4b38-b3f6-ec5520ef47f8.png)
> 

可能是防广告插件问题，或者是重建内容 json 多了个符号，爆炸了

**Comment by BraveSail** [comment]
@suiyidr 你是卡在这里了？ 把 ublock 或者其他去广告插件关了试试

**Comment by suiyidr** [comment]
关了去广告插件变成这样了
![image](https://user-images.githubusercontent.com/87166323/140909127-8e9ad1f2-8f7b-4c57-bfc1-cc7811b0cc43.png)

**Comment by BraveSail** [comment]
@suiyidr https://github.com/ipcjs/bilibili-helper/pull/901 已经修复了
