### ISSUE TITLE
在一般的视频页面，会反复弹出错误

### ISSUE THREAD

**Issue by machine-doll** [ipcjs/bilibili-helper#905]
脚本问题：@ipcjs
在[一般的用户上传视频](https://www.bilibili.com/video/BV1xW411t7y7)上会反复出现如图的错误![错误1](https://i.bmp.ovh/imgs/2021/11/4948524b035477ba.png)
## 描述

在[一般的用户上传视频](https://www.bilibili.com/video/BV1xW411t7y7)上会反复出现如图的错误![错误1](https://i.bmp.ovh/imgs/2021/11/4948524b035477ba.png)
有时候甚至会使得播放器的清晰度和右键菜单无法打开
- 问题网址：
[被遗忘的孩子](https://www.bilibili.com/video/BV1xW411t7y7)
其他的网址也可以复现

## 日志

<details>
<summary>Verbose 日志</summary>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.12 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28233441/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: redirect blocked_vip:  server: https://www.biliplus.com upos_server: hw flv_prefer_ws:  remove_pre_ad: Y enable_in_av: Y readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=37762&access_key=9418d2e0672cfc943d6ef4bb29cac3b1
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"lxr2017","isLogin":true,"level":4,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"lxr2017","isLogin":true,"level":4,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":0,"follow_status":2,"login":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":380293,"last_ep_index":"5","last_time":5},"real_price":"0","sponsor":0,"vip_info":{"due_date":1601568000000,"status":0,"type":1}}}
debug: atRun: 2, complete
debug: season37762 {"code":0,"message":"success","result":{"actor":[{"actor":"內山夕実","actor_id":0,"role":"魯迪烏斯·格雷拉特"},{"actor":"茅野愛衣","actor_id":0,"role":"希露菲葉特·格雷拉特"},{"actor":"加隈亜衣","actor_id":0,"role":"艾莉絲·格雷拉特"},{"actor":"小原好美","actor_id":0,"role":"洛琪希·米格路迪亞·格雷拉特"},{"actor":"森川智之","actor_id":0,"role":"保羅·格雷拉特"},{"actor":"金元壽子","actor_id":0,"role":"塞妮絲·格雷拉特"},{"actor":"Lynn","actor_id":0,"role":"莉莉婭·格雷拉特"},{"actor":"浪川大輔","actor_id":0,"role":"瑞傑路德•斯佩路迪亞"},{"actor":"杉田智和","actor_id":0,"role":"前世"}],"alias":"無職転生 ～異世界行ったら本気だす～,無職轉生~在異世界認真地活下去~","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"5271","bangumi_title":"無職轉生（僅限港澳台等地區）","brief":"“我要在這個異世界拿出真本事！”\n34歲童貞且無職的家裡蹲男子，在父母的葬禮當天被趕出家門後，在路上...","business_type":1,"coins":"0","copyright":"bilibili","cover":"https://i0.hdslb.com/bfs/bangumi/image/f3e0132f2ca220d76369ed2316e903dfd63b25eb.png","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"929673924","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0b7d264fd1f6710b470ef4716dc5107c193be6ef.png","danmaku":"312261618","episode_id":"380299","episode_status":2,"episode_type":0,"from":"bangumi","index":"11","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-03-22 00:30:01.0"},{"av_id":"844606411","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/48588e705c5dd0e0d2786b9f9fc9f483e87b67df.png","danmaku":"309147768","episode_id":"380298","episode_status":2,"episode_type":0,"from":"bangumi","index":"10","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-03-15 00:30:01.0"},{"av_id":"416876069","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/4f754e7a265ae8c7d2779eeba73699ae5a83d8fb.png","danmaku":"306218142","episode_id":"380297","episode_status":2,"episode_type":0,"from":"bangumi","index":"9","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-03-08 00:30:01.0"},{"av_id":"501979295","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/2e6833a852e36a67c613da51573c9d6eddae74bf.png","danmaku":"304542522","episode_id":"380296","episode_status":2,"episode_type":0,"from":"bangumi","index":"8","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-03-01 00:30:01.0"},{"av_id":"289324040","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/98dc262ed7cc474e225f9b2346437712fd5e31c2.png","danmaku":"300191043","episode_id":"380295","episode_status":2,"episode_type":0,"from":"bangumi","index":"7","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-02-22 00:30:01.0"},{"av_id":"799233396","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/4b9b6e779664fb986c5dc8ee13f8210ef2a9cf44.png","danmaku":"298301010","episode_id":"380294","episode_status":2,"episode_type":0,"from":"bangumi","index":"6","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-02-15 00:30:01.0"},{"av_id":"586585312","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/9ad76300573e41113194753c117d87f709243c19.png","danmaku":"293248090","episode_id":"380293","episode_status":2,"episode_type":0,"from":"bangumi","index":"5","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-02-08 00:30:01.0"},{"av_id":"886419275","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/fb49c79102af395580c34882be899966c22e483c.png","danmaku":"289427720","episode_id":"380292","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-02-01 00:30:00.0"},{"av_id":"586433705","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/c5a46c1a3aba475170b1ffbd415199b55d9bc4a0.png","danmaku":"290969037","episode_id":"380291","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-01-25 00:30:00.0"},{"av_id":"458809406","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/aff0808bc7c2b88b1a1c5e156265383c687d6c0e.png","danmaku":"290910195","episode_id":"380290","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-01-18 00:30:00.0"},{"av_id":"971356972","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/c6021fea287c8c407c8a2cb2f91f6c88d66bb5ec.png","danmaku":"290909831","episode_id":"380289","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2021-01-11 00:30:00.0"}],"evaluate":"“我要在這個異世界拿出真本事！”\n34歲童貞且無職的家裡蹲男子，在父母的葬禮當天被趕出家門後，在路上被一輛卡車所撞死。意識清醒後，他發現自己居然作為一個剛出生的嬰兒轉生到了劍與魔法的異世界！像廢物一樣活過了前世的男子，發誓要作為少年·魯迪烏斯在異世界以認真的態度好好活下去！\n等待著魯迪烏斯的是，與嬌小魔術師、有著精靈長耳又很男孩子氣的美少女、兇暴的傲嬌大小姐以及其他性格各異的人們之間的邂逅，當然也還有殘酷的冒險與戰鬥。\n新的人生就要開始了！ “人生重來型”幻想冒險譚，在此開幕！","favorites":"0","has_unfollow":0,"is_finish":"1","is_guide_follow":1,"jp_title":"無職転生 ～異世界行ったら本気だす～","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/f3e0132f2ca220d76369ed2316e903dfd63b25eb.png","episode_index":{"index_show":"已完结, 全11话"},"media_id":28233441,"publish":{"is_finish":1,"is_started":1},"title":"無職轉生～到了異世界就拿出真本事～（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"380299","newest_ep_index":"11","origin_name":"無職転生 ～異世界行ったら本気だす～","play_count":"0","pub_string":"","pub_time":"2021-01-11 00:30:00","pub_time_show":"1月11日 00:30 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"37762","season_status":2,"season_title":"TV（僅港澳台）","seasons":[{"bangumi_id":"5271","cover":"https://i0.hdslb.com/bfs/bangumi/image/f3e0132f2ca220d76369ed2316e903dfd63b25eb.png","is_finish":"1","newest_ep_id":"380299","newest_ep_index":"11","season_id":"37762","season_status":2,"title":"TV（僅港澳台）","total_count":"11"}],"share_url":"http://bangumi.bilibili.com/anime/37762/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/311e24b5e8aba2cca33584349ab40241b41a6ed5.png","staff":"導演:岡本學\n人物設定:杉山和隆、齊藤佳子\n總作畫監督:杉山和隆\n原作:理不盡な孫の手\n系列構成:岡本學\n色彩設計:土居真紀子\n美術監督:三宅昌和\n音樂:藤澤慶昌","tag2s":[],"tags":[],"title":"無職轉生～到了異世界就拿出真本事～（僅限港澳台地區）","total_count":"11","update_pattern":"","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: balh_mode  =>  replace
debug: balh_mode  =>  default
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：<html>
<body>

Microsoft Edge | 96.0.1054.34 (官方内部版本) (64 位)
-- | --

</body>
</html>
2. 国家/地区：中国大陆

**Comment by Lucas-TY** [comment]
你是不是勾选在av视频启用了
