### ISSUE TITLE
[Tutorial] 修复泰区跨域问题

### ISSUE THREAD

**Issue by BraveSail** [ipcjs/bilibili-helper#906]
## 
泰区番剧由于`akamai`锁区导致`403`进而引起跨域问题，需要通过替换`upos`为脚本内置列表中的地址来解决，去除`header`中的`referer`并且保证`user-agent`不在黑名单里面。下面通过 ModHeader 来演示如何修复。（在`chrome 96.0.4664.45`中测试通过）
##
### 2. 打开 ModHeader 面板，点击右上角三个点，点击`Import profile(s)`，然后填入 [此链接](https://modheader.com/profile/5c3aaf97-a418-4811-8d1f-cbf5c2c19569) 后点击`Import`，成功导入后内容如下图所示。
![image](https://user-images.githubusercontent.com/49320262/167335797-0ebd4f01-a14a-49a6-ac19-54371b6fa2a9.png)
##
### 注意事项：
1. 升级脚本到最新版。
2. `user-agent`不在黑名单内（测试`chrome 96.0.4664.45`的默认`ua`已被拉黑，替换成`Mozilla`没问题）。
3. **`Redirect URLs`右边的框是`akamai`要替换成为的`upos`，`Filters`中`URL Pattern`是扩展要生效的`url`，因此要确保扩展替换的`upos`和脚本设置里替换的`upos`不一样，否则脚本和扩展会冲突，扩展同时去除了港澳台番剧的`referer`从而导致港澳台区番剧的跨域问题。**

**Comment by cirolchou** [comment]
你好想问一下，我这边用了这个方法以后，泰区的TV番剧确实绝大部分都能看了，但是泰区的剧场版依然是一律加载不出来，播放器底部提示416错误，想请问下这是怎么回事？多谢！

**Comment by BraveSail** [comment]
链接

**Comment by cirolchou** [comment]
> 链接

例子的话就太多了，所有泰区剧场版都不行。。这里举一个FSN HF剧场版第三部的例子吧：https://www.bilibili.com/bangumi/play/ep10071440

**Comment by BraveSail** [comment]
这个是脚本问题了，等 @miyouzi 修

**Comment by cirolchou** [comment]
> 这个是脚本问题了，等 @miyouzi 修

好的，多谢解答

**Comment by cirolchou** [comment]
接着昨天的反馈再补充一下：实际上无法播放的类别并不只是泰区的“剧场版”，而是泰区稍微长一点的动画都播不出来，我感觉大概只要视频时长超过30分钟就播不出来了，只是因为剧场版基本都超过30分钟，所以剧场版是肯定播不出来的。

**Comment by miyouzi** [comment]
> 接着昨天的反馈再补充一下：实际上无法播放的类别并不只是泰区的“剧场版”，而是泰区稍微长一点的动画都播不出来，我感觉大概只要视频时长超过30分钟就播不出来了，只是因为剧场版基本都超过30分钟，所以剧场版是肯定播不出来的。

https://github.com/ipcjs/bilibili-helper/commit/f87572dbdae74d9f909d8bbd7a335877bbf8e164

应该是这个时候改出问题了，我当时用算的就是考虑到剧场版，不是乱猜的，让 @JasonKhew96 想一下怎么修吧（

**Comment by JasonKhew96** [comment]
难，这得另外造一个更好一点的算法（~~但是跨域问题还没修~~ ）

我个人建议别用泰区看剧场版，下 bd 得了，还可以 dandanplay

**Comment by kawatabi** [comment]
最近好像又不行了
![屏幕截图 2022-05-08 001543](https://user-images.githubusercontent.com/105119751/167262846-871e9278-0e31-4edc-8955-8ce5ff123f86.png)
。

**Comment by BraveSail** [comment]
[试试这个](https://modheader.com/p/NobwRAhgDlCmB2ATAsge0bMAuAZhANgM6wA0YARhAMYDWA5gE6oCuSAwqvqg9mAMQBWAIwB2ABwiIYMjgCW+AC6wGhbKDBVUAWy0IFvaWAQRy+WImwKGzUmAaxCLBlVgAVAJ5w1AXTILPmFhgzAxEhiH4AEqwdLAAHrwAFgoKUIRYADoZAPRZ2cxQqIQAtOSEChAMQsVasgxMDBA0EFoAdE0tELIAXuat8LD6AL4k4Jo6egZkxqbm2HhEtvaOIS4eXljAvmD+G8GhqmQR0bEJQcmp6Xl5BUXFhN01dQ00hADMreTysgBushioVrjMAjMbaXTwfRBQwzMwWLBWGxkZZONYBHx+dFBCKHfZRGLxJIpNKZHI3QolB5PercTSEMoVKqfb5-AFA7Qg0YacGTaHTeAmOGWaxLByotxYraYvY48KhE6E87Eq5knK3SmPWo0hivN5UZn4X7-WCA4FDbaJWAQDAqNRgiaQqZGAWzeGI2wC3S8ew4ZTKQw-Ag2Ayg7kOqFgGEuoUIkVkT2BYLEBjFCCxR1kQP4YNBNDdeT4KSh8YQiNRwVzWNIsAJ3jcWR0WTwANBxMgi3Gjjh4XV5ZQAASVptqk29tLTthlfd8ZaieoLkIJU0kKY+FT+C4AHdipbrcpcVmc2AAFScse8yP8ituuM12e8ecOJeoFecddbmqDRLoA+t3gAcQAUVcEgAAIAAUAFUQIggB5ABlGCABFAIAGWAwCwP7QCAEEkLA2DwNcABJWCADl4LA8CcNcNh+yoyJCIAMWIsj8IgxjwOo2j6NA5AAGk2Fg1CwKE8CAE0wOQWCADVMNA1DYLYfizzDcc+Wda8ew9e8gkfRdimXKw3wID960bZtMz-IJT2LHlHQ0ycb2rWs9KoBdn1fNd4gpWAdyHfcW2zRNbK5EsL3LV1tJnL0ghw9yn2KDgvOKHCN1Qbc2HsDBIVkAhf2C3h3XbMhCG-BgFFcWQFDMXghEMJQ4gUDguB4II+BwTquoa6raqCDgoHcUDUBwCCmDkMxQPqo55VgKBCxcUsR3UcKHMvTSoqrHTYrAC4SWyfIKVKcpKmqLUGg6NpLq6XpEH6QYgqPPb0gO9V7k1Z5uF1fUvkNVkTXZLRVNWssr026c7x256sFeo6GUqakLuaK7kZuvoBn0KzCqVS4YcOu4qXOr73h+lljVNDk7O7RzoynW9XN25U8bewnPucIp4aZX6jTZYEsaepnYYJj7tW+g0eYBs1vHNIA)

**Comment by kawatabi** [comment]
> [试试这个](https://modheader.com/p/NobwRAhgDlCmB2ATAsge0bMAuAZhANgM6wA0YARhAMYDWA5gE6oCuSAwqvqg9mAMQBWAIwB2ABwiIYMjgCW+AC6wGhbKDBVUAWy0IFvaWAQRy+WImwKGzUmAaxCLBlVgAVAJ5w1AXTILPmFhgzAxEhiH4AEqwdLAAHrwAFgoKUIRYADoZAPRZ2cxQqIQAtOSEChAMQsVasgxMDBA0EFoAdE0tELIAXuat8LD6AL4k4Jo6egZkxqbm2HhEtvaOIS4eXljAvmD+G8GhqmQR0bEJQcmp6Xl5BUXFhN01dQ00hADMreTysgBushioVrjMAjMbaXTwfRBQwzMwWLBWGxkZZONYBHx+dFBCKHfZRGLxJIpNKZHI3QolB5PercTSEMoVKqfb5-AFA7Qg0YacGTaHTeAmOGWaxLByotxYraYvY48KhE6E87Eq5knK3SmPWo0hivN5UZn4X7-WCA4FDbaJWAQDAqNRgiaQqZGAWzeGI2wC3S8ew4ZTKQw-Ag2Ayg7kOqFgGEuoUIkVkT2BYLEBjFCCxR1kQP4YNBNDdeT4KSh8YQiNRwVzWNIsAJ3jcWR0WTwANBxMgi3Gjjh4XV5ZQAASVptqk29tLTthlfd8ZaieoLkIJU0kKY+FT+C4AHdipbrcpcVmc2AAFScse8yP8ituuM12e8ecOJeoFecddbmqDRLoA+t3gAcQAUVcEgAAIAAUAFUQIggB5ABlGCABFAIAGWAwCwP7QCAEEkLA2DwNcABJWCADl4LA8CcNcNh+yoyJCIAMWIsj8IgxjwOo2j6NA5AAGk2Fg1CwKE8CAE0wOQWCADVMNA1DYLYfizzDcc+Wda8ew9e8gkfRdimXKw3wID960bZtMz-IJT2LHlHQ0ycb2rWs9KoBdn1fNd4gpWAdyHfcW2zRNbK5EsL3LV1tJnL0ghw9yn2KDgvOKHCN1Qbc2HsDBIVkAhf2C3h3XbMhCG-BgFFcWQFDMXghEMJQ4gUDguB4II+BwTquoa6raqCDgoHcUDUBwCCmDkMxQPqo55VgKBCxcUsR3UcKHMvTSoqrHTYrAC4SWyfIKVKcpKmqLUGg6NpLq6XpEH6QYgqPPb0gO9V7k1Z5uF1fUvkNVkTXZLRVNWssr026c7x256sFeo6GUqakLuaK7kZuvoBn0KzCqVS4YcOu4qXOr73h+lljVNDk7O7RzoynW9XN25U8bewnPucIp4aZX6jTZYEsaepnYYJj7tW+g0eYBs1vHNIA)

可以正常看番剧了。感谢！！！

**Comment by GH-at** [comment]
谢谢大佬，找了半天原因

**Comment by bairixingchen** [comment]
此链接404了

**Comment by satan2333** [comment]
你好，我想问一下第二步那个导入的链接进去是403错误，该如何处理？能否解答一下，谢谢！

**Comment by kawatabi** [comment]
> 你好，我想问一下第二步那个导入的链接进去是403错误，该如何处理？能否解答一下，谢谢！

![屏幕截图 2022-11-10 172022](https://user-images.githubusercontent.com/105119751/201051286-93e515f3-7dfa-4e79-b514-4f14dc066d87.jpg)
👆此处Response headers 的第二项的内容是：GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK

![屏幕截图 2022-11-10 171939](https://user-images.githubusercontent.com/105119751/201052376-1f42f687-2aed-41de-89ef-4c67314a4d0a.jpg)
👆此处Response headers 的第二项的内容是：GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH, 

其它输入内容与楼主所发的图片大体相同
（计算机小白不知道有没有讲清楚😥😥😥，大家姑且先看看吧）

**Comment by satan2333** [comment]
> > 你好，我想问一下第二步那个导入的链接进去是403错误，该如何处理？能否解答一下，谢谢！
> 
> ![屏幕截图 2022-11-10 172022](https://user-images.githubusercontent.com/105119751/201051286-93e515f3-7dfa-4e79-b514-4f14dc066d87.jpg) 👆此处响应标头的第二项的内容是：GET， PUT， POST， DELETE， HEAD， OPTIONS， PATCH， PROPFIND， PROPPATCH， MKCOL， COPY， MOVE， LOCK
> 
> ![屏幕截图 2022-11-10 171939](https://user-images.githubusercontent.com/105119751/201052376-1f42f687-2aed-41de-89ef-4c67314a4d0a.jpg) 👆此处Response headers 的第二项的内容是：GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH,
> 
> 其它输入内容与楼主所发的图片大体相同 （计算机小白不知道有没有讲清楚😥😥😥，大家姑且先看看吧）

**Comment by BraveSail** [comment]
https://modheader.com/profile/5c3aaf97-a418-4811-8d1f-cbf5c2c19569

**Comment by satan2333** [comment]
> https://modheader.com/profile/5c3aaf97-a418-4811-8d1f-cbf5c2c19569

非常感谢!

**Comment by satan2333** [comment]
> > 你好，我想问一下第二步那个导入的链接进去是403错误，该如何处理？能否解答一下，谢谢！
> 
> ![屏幕截图 2022-11-10 172022](https://user-images.githubusercontent.com/105119751/201051286-93e515f3-7dfa-4e79-b514-4f14dc066d87.jpg) 👆此处Response headers 的第二项的内容是：GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK
> 
> ![屏幕截图 2022-11-10 171939](https://user-images.githubusercontent.com/105119751/201052376-1f42f687-2aed-41de-89ef-4c67314a4d0a.jpg) 👆此处Response headers 的第二项的内容是：GET, PUT, POST, DELETE, HEAD, OPTIONS, PATCH,
> 
> 其它输入内容与楼主所发的图片大体相同 （计算机小白不知道有没有讲清楚😥😥😥，大家姑且先看看吧）

谢谢你的解答！

**Comment by SupremeShu** [comment]
泰区的视频成功了，但是显示不了字幕怎么办

**Comment by satan2333** [comment]
有没有字幕取决于你所用解析服务器的服主有没有上传字幕，泰区本来就是没有中文字幕的。有一些解析服务器有，有一些没有；有一些番剧有，有一些没有。一般都是服主想看这部番剧了才可能会为这部番剧上传字幕。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ipcjs/bilibili-helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月18日(星期天) 晚上10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ipcjs/bilibili-helper] [Tutorial] 修复泰区跨域问题 (Issue #906)





 
泰区的视频成功了，但是显示不了字幕怎么办

**Comment by SupremeShu** [comment]
> 有没有字幕取决于你所用解析服务器的服主有没有上传字幕，泰区本来就是没有中文字幕的。有一些解析服务器有，有一些没有；有一些番剧有，有一些没有。一般都是服主想看这部番剧了才可能会为这部番剧上传字幕。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ipcjs/bilibili-helper" ***@***.***&gt;; 发送时间:&nbsp;2022年12月18日(星期天) 晚上10:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ipcjs/bilibili-helper] [Tutorial] 修复泰区跨域问题 (Issue #906) 泰区的视频成功了，但是显示不了字幕怎么办 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢！知道怎么回事了，把AdGuard关了就好了，应该是误拦截了

**Comment by Einck0** [comment]
用了这个方法，有的集可以看，有的集不可以看，是什么问题？基本所有番剧都是这样
![image](https://user-images.githubusercontent.com/91471683/215490173-72abaafe-b53b-4642-8a38-493c7e453795.png)
![image](https://user-images.githubusercontent.com/91471683/215490177-a0232671-e796-4751-a29f-1f09322d03fd.png)

**Comment by 2863929603** [comment]
好像又用不了了。

**Comment by ghost** [comment]
![N8~LW4 TI%29FIBW3W_@`6C](https://user-images.githubusercontent.com/108615198/227724869-0d1f0a9c-ad1b-4aaf-9e35-5265d14ee66e.png)
modheader寄了……

**Comment by anibuta** [comment]
＠[BraveSail](https://github.com/BraveSail)突然用不了了，modheader收费前能用，我解锁pro版还是用不了

**Comment by JasonKhew96** [comment]
洗洗睡，是 泰国/东南亚 B站 改了东西，现在有 IP:8000 的 upos 了，这个 ssl 有问题，另一个 upos 403，然后就播不出了，不知道怎么修

**Comment by anibuta** [comment]
域名方面，global.bilibili.com 现在已经无法重定向到 bilibili.tv。由于B站专栏不允许使用含 bilibili.com 以外域名的链接，从这期专栏开始，东南亚站的链接将会使用主站的格式 https://www.bilibili.com/bangumi/play/ss{{season_id}} 。 作者：101对双生儿 https://www.bilibili.com/read/cv21041370?spm_id_from=333.999.0.0 出处：bilibili
希望有帮助

**Comment by JeanneAlt** [comment]
现在网页是用不了了吗

**Comment by ForeverBRS** [comment]
modheader收费了，能用gooreplacer重新写一份规则吗？这两个插件导出的json规则不通用

**Comment by haoxiaoyueh** [comment]
没有教程，全网都没有这玩意的教程！！！！！！！！
我要怎么样把它导入到Header Editor中，而且为什么不用免费开源的插件，这种想捞钱想疯的玩意有什么好的！！！！！
我想自己把规则搬运过去，但是我看不懂，这玩意不仅收费还是全英文，还没有注释，没有教程！！！没有教程啊！！！！！
谁能帮忙搬一份Header Editor的json文件，或者帮忙解释一下这两个插件的功能分别是怎么对应的也好啊！！！
话说为什么不用Header Editor，这不仅免费，而且开源，还是全中文，作者你是想不开吗？
这两个插件的功能是怎么对应的啊？
“Request headers”对应修改请求头，那这项目里的name是哪个？是头名称吗？value又是哪个？是头内容？那comment又对应哪个？来个人帮帮忙吧！！

**Comment by JasonKhew96** [comment]
建议 close+lock 移除泰区相关代码，已经说了有问题，不会爬楼是吧？

想看的推荐其他平台:
`https://bilibili.tv` (这就是原来的泰区)
`https://ani.gamer.com.tw` (巴哈姆特动画疯)

**Comment by haoxiaoyueh** [comment]
http://m.qpic.cn/psc?/V53SUQ2e2FHKJS3HKAXc4FRjd01MLM9I/bqQfVz5yrrGYSXMvKr.cqUGhgGWkXyx1HgBnDDty99hyaQ.riqLX1v6nkNjmLRiFcBJCKYf.o4tlTDktjmXRSgXE45w.s.C40wIHd0tSyec!/b&bo=cwSfAnMEnwIDByI!&rf=viewer_4

http://m.qpic.cn/psc?/V53SUQ2e2FHKJS3HKAXc4FRjd01MLM9I/bqQfVz5yrrGYSXMvKr.cqfwRkB00p7O4wU5TiiJ*olAo.bML9ikYjdKauwr2kVkjEkqcd.nxzB6PFPfgE*CFD0gaHIq0JtHOSHWugb.U8cM!/b&bo=cwSfAnMEnwIDByI!&rf=viewer_4

http://m.qpic.cn/psc?/V53SUQ2e2FHKJS3HKAXc4FRjd01MLM9I/bqQfVz5yrrGYSXMvKr.cqYC3oGmwRnwQI*HWNHpnzPBtJqwsxeW4VZphpJtplcKVIIy4I52uygqRsMlACEfYz9tawfLpManYvej0FOp19MI!/b&bo=cwREAnMERAIDFzI!&rf=viewer_4

http://m.qpic.cn/psc?/V53SUQ2e2FHKJS3HKAXc4FRjd01MLM9I/bqQfVz5yrrGYSXMvKr.cqahZNChwqLHsrsqPEHNyFPwuLG*XmJ6ZJqRMtmTyWOOgggPDr07s40mGEbYVptKN1Zwyxjhd.Ec4fcDfiQTcQDY!/b&bo=cwTkAXME5AEDFzI!&rf=viewer_4

http://a1.qpic.cn/psc?/V53SUQ2e2FHKJS3HKAXc4FRjd01MLM9I/bqQfVz5yrrGYSXMvKr.cqcXv*RNf3d.3Tolb6x1QbDsCY41wjZhL857GzyxYtNBLE0lAVkJVAlohE7bI6zlid3saNnGqCKe738IGF4*vaVw!/b&ek=1&kp=1&pt=0&bo=YQXRAWEF0QEDFzI!&tl=1&vuin=335412676&tm=1681999200&dis_t=1681999772&dis_k=a7ade51c9c3004da44154ec8e7abbd6d&sce=60-1-1&rf=viewer_4
像是这些功能分别是怎么对应的？

**Comment by ForeverBRS** [comment]
> 建议 close+lock 移除泰区相关代码，已经说了有问题，不会爬楼是吧？
> 
> 想看的推荐其他平台: `https://bilibili.tv` (这就是原来的泰区) `https://ani.gamer.com.tw` (巴哈姆特动画疯)

不好意思，没有看到上面用户所回复的问题，我以为是modheader的问题。不过感谢推荐的追番网址

**Comment by ForeverBRS** [comment]
> 没有教程，全网都没有这玩意的教程！！！！！！！！ 我要怎么样把它导入到Header Editor中，而且为什么不用免费开源的插件，这种想捞钱想疯的玩意有什么好的！！！！！ 我想自己把规则搬运过去，但是我看不懂，这玩意不仅收费还是全英文，还没有注释，没有教程！！！没有教程啊！！！！！ 谁能帮忙搬一份Header Editor的json文件，或者帮忙解释一下这两个插件的功能分别是怎么对应的也好啊！！！ 话说为什么不用Header Editor，这不仅免费，而且开源，还是全中文，作者你是想不开吗？ 这两个插件的功能是怎么对应的啊？ “Request headers”对应修改请求头，那这项目里的name是哪个？是头名称吗？value又是哪个？是头内容？那comment又对应哪个？来个人帮帮忙吧！！

啊这，我没有考虑到不同插件移植配置文件的难度。抱歉让你感到困惑

**Comment by ForeverBRS** [comment]
> 没有教程，全网都没有这玩意的教程！！！！！！！！ 我要怎么样把它导入到Header Editor中，而且为什么不用免费开源的插件，这种想捞钱想疯的玩意有什么好的！！！！！ 我想自己把规则搬运过去，但是我看不懂，这玩意不仅收费还是全英文，还没有注释，没有教程！！！没有教程啊！！！！！ 谁能帮忙搬一份Header Editor的json文件，或者帮忙解释一下这两个插件的功能分别是怎么对应的也好啊！！！ 话说为什么不用Header Editor，这不仅免费，而且开源，还是全中文，作者你是想不开吗？ 这两个插件的功能是怎么对应的啊？ “Request headers”对应修改请求头，那这项目里的name是哪个？是头名称吗？value又是哪个？是头内容？那comment又对应哪个？来个人帮帮忙吧！！

啊这，我没有考虑到不同插件移植配置文件的难度。抱歉让你感到困惑

**Comment by ForeverBRS** [comment]
> 洗洗睡，是 泰国/东南亚 B站 改了东西，现在有 IP:8000 的 upos 了，这个 ssl 有问题，另一个 upos 403，然后就播不出了，不知道怎么修

我前几天用浏览器开发选项，发现返回的播放地址报ssl错误，端口号跟你说的一样，我以为是插件修改请求的问题，看来是网站那边的变动。如果有解决方法，能否告知一下？谢谢！

**Comment by anibuta** [comment]
去年根据#1221已经可以看东南亚了，但最近从3月开始的番剧都看不了，之前的正常，请大佬看到给予反馈，拯救东南亚

**Comment by JasonKhew96** [comment]
> 去年根据#1221已经可以看东南亚了，但最近从3月开始的番剧都看不了，之前的正常，请大佬看到给予反馈，拯救东南亚orz @BraveSail

@anibuta 我的建议是自己去 `bilibili.tv` 看，不然自己想办法去其他地方看
