### ISSUE TITLE
大佬看不了国家队了

### ISSUE THREAD

**Issue by yang343** [ipcjs/bilibili-helper#91]
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183802
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: redirect blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad: Y readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"ya丶ng","isLogin":true,"level":4,"vipType":0,"vipStatus":0}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":3}}}
log: Redirected request: bangumi playurl ->  https://www.biliplus.com/BPplayurl.php?cid=31144490|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=80&module=bangumi&season_type=1&qn=80&sign=0349937c4a22a6423f98b1e00fb119b3
log: balh_server  =>  https://biliplus.ipcjs.win
debug: userAgent Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by ipcjs** [comment]
#100
