### ISSUE TITLE
试了哔哩漫游公共解析服务器里的所有地址都是非常抱歉

### ISSUE THREAD

**Issue by noir1216** [ipcjs/bilibili-helper#910]
## 描述
已账号授权，试了哔哩漫游公共解析服务器里的所有地址都是非常抱歉

- 问题网址：所有港澳台番剧
- [https://s2.loli.net/2021/12/05/Zpciw9kgDXbQrvU.png](url)

## 日志

<details>
<summary>Verbose 日志</summary>

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss39013/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"Noir夜祀","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=805514844&bvid=BV1P34y1X7H2&cid=409594126&qn=112&fnver=0&fnval=80&fourk=1&ep_id=409297&session=d793df3dd01f81e005c3232a550ad1ba&module=bangumi&area=hk&access_key=37b8c1fa3b89a8835e633a27cc0ec1c1
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"Noir夜祀","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
 
</details>

## 其他

1. 浏览器版本：Chrome 86.0.4240.198
2. 国家/地区：中国大陆

**Comment by JasonKhew96** [comment]
@noir1216 换解析服务器地址
![image](https://user-images.githubusercontent.com/29531167/144745989-95f191b9-d5da-4022-adc2-07ad8c749a3a.png)

**Comment by noir1216** [comment]
> 

呃，多谢，可以了。
