### ISSUE TITLE
公共解析服务器大陆番剧解析失败

### ISSUE THREAD

**Issue by yuanyao56** [ipcjs/bilibili-helper#911]
脚本问题：@ipcjs

## 描述
大陆番剧无法解析，港台正常。 尝试了[公共解析服务器](https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8)里所有的，都不能使用。
拉取视频地址失败
原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}
比如bili.tuturu.top港台就可以使用 大陆就失败

- 问题网址：https://www.bilibili.com/bangumi/play/ep433963

## 日志

<details>
<summary>debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep433963
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: ks3 flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://cn.ellpew.xyz/pgc/player/web/playurl?avid=719510863&bvid=BV1VQ4y1i7Gj&cid=453883289&qn=80&fnver=0&fnval=80&fourk=1&ep_id=433963&session=7abb35f1287d705241f7861279b1dde1&module=bangumi&area=&access_key=d5a2bd7770f72caed166e5c69e7fa171
debug: /x/web-interface/nav {"uname":"一只泉泉","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"一只泉泉","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://cn.ellpew.xyz/pgc/player/web/playurl?avid=719510863&bvid=BV1VQ4y1i7Gj&cid=453883289&qn=80&fnver=0&fnval=80&fourk=1&ep_id=433963&session=7abb35f1287d705241f7861279b1dde1&module=bangumi&area=cn&access_key=d5a2bd7770f72caed166e5c69e7fa171
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=719510863&bvid=BV1VQ4y1i7Gj&cid=453883289&qn=80&fnver=0&fnval=80&fourk=1&ep_id=433963&session=7abb35f1287d705241f7861279b1dde1&module=bangumi&area=hk&access_key=d5a2bd7770f72caed166e5c69e7fa171
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=719510863&bvid=BV1VQ4y1i7Gj&cid=453883289&qn=80&fnver=0&fnval=80&fourk=1&ep_id=433963&session=7abb35f1287d705241f7861279b1dde1&module=bangumi&area=tw&access_key=d5a2bd7770f72caed166e5c69e7fa171
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：chrome  96.0.4664.45
2. 国家/地区：美国

**Comment by JasonKhew96** [comment]
@yuanyao56 ~请关闭 永封大会员 功能 再尝试~

编辑: 授权大概是掉了

**Comment by AisukaYuki** [comment]
如果关闭 永封大会员 功能还不行，请尝试重新登录B站并授权插件，~~访问密钥已过期或不存在~~（大概

**Comment by yuanyao56** [comment]
> 如果关闭 永封大会员 功能还不行，请尝试重新登录B站并授权插件，~访问密钥已过期或不存在~（大概

已解决 谢谢
