### ISSUE TITLE
日剧《日本沉没》只显示预告，不能选择集数，同账号下，其他剧能显示

### ISSUE THREAD

**Issue by Yalio** [ipcjs/bilibili-helper#912]
脚本问题：@ipcjs

## 描述

日剧《日本沉没》只显示预告，不能选择集数，同账号下，其他剧能显示
- 问题网址：
https://www.bilibili.com/bangumi/play/ss39621#427700

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>
![下载 (1)](https://user-images.githubusercontent.com/50227569/145031186-1913f61c-9970-4957-948e-2dfbb9176180.jpeg)

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by JasonKhew96** [comment]
草，跟 咒术 一样了

**Comment by Yalio** [comment]
> 草，跟 咒术 一样了

咒术之前的已经修好了，感觉都是个例

**Comment by JasonKhew96** [comment]
> > 草，跟 咒术 一样了
> 
> 咒术之前的已经修好了，感觉都是个例

大概是 b站 自己改回去的，根本没人修过这个问题
