### ISSUE TITLE
看鬼灭之刃的时候右下角不出现星球icon

### ISSUE THREAD

**Issue by andykeppel** [ipcjs/bilibili-helper#914]
脚本问题：@ipcjs

## 描述
看鬼灭之刃的时候右下角不出现星球icon，其他番剧可以出现。在其他番剧页面设置好后，还是看不了鬼灭之刃。

- 问题网址：https://www.bilibili.com/bangumi/play/ep434501?spm_id_from=444.41.0.0

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep434501?spm_id_from=444.41.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"0X0000002","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=434501
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?cid=458772912&qn=112&type=&otype=json&fourk=1&bvid=BV1mL411L7Pv&ep_id=434501&fnver=0&fnval=80&session=ec780ef9b07d5145800dbc46f2aa36e2&module=bangumi&area=&access_key=8b32eccab7edcbc894269a39ef8331c1
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?cid=458772912&qn=112&type=&otype=json&fourk=1&bvid=BV1mL411L7Pv&ep_id=434501&fnver=0&fnval=80&session=ec780ef9b07d5145800dbc46f2aa36e2&module=bangumi&access_key=8b32eccab7edcbc894269a39ef8331c1
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=undefined&cid=458772912&bvid=BV1mL411L7Pv&qn=112&type=&otype=json&ep_id=434501&fourk=1&fnver=0&fnval=80&session=43e9e6b53864f48840f15be880a47b72&module=bangumi&balh_ajax=1&area=&access_key=8b32eccab7edcbc894269a39ef8331c1
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=458772912&bvid=BV1mL411L7Pv&qn=112&type=&otype=json&ep_id=434501&fourk=1&fnver=0&fnval=80&session=43e9e6b53864f48840f15be880a47b72&module=bangumi&balh_ajax=1&access_key=8b32eccab7edcbc894269a39ef8331c1
debug: /x/web-interface/nav {"uname":"0X0000002","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
## 其他

1. 浏览器版本：Chrome 96.0.4664.93
2. 国家/地区：大陆
![491639457374_ pic_hd](https://user-images.githubusercontent.com/62137704/145935042-6e9a40ae-9b74-4b6e-9723-7527141fd8cf.jpg)

**Comment by JasonKhew96** [comment]
@andykeppel

没有设置按钮是预期行为，重建的页面没植入按钮，要打开可以用 javascript
```javascript
window.bangumi_area_limit_hack.showSettings();
```

至于 “看不了” 的问题，你重新授权一下帐号就可以了

**Comment by andykeppel** [comment]
重新授权之后还是看不了，很奇怪，貌似所有仅限台湾的番都看不了，港澳台的倒是正常

**Comment by JasonKhew96** [comment]
> 重新授权之后还是看不了，很奇怪，貌似所有仅限台湾的番都看不了，港澳台的倒是正常

@andykeppel 那就是 地区 填错 解析服务器

**Comment by AisukaYuki** [comment]
不要只填首选 下面的框框也都填上。log里面area参数都是空的，当然请求不到

**Comment by hhhwenjun** [comment]
我也是一样的填错了，问题解决了谢谢大佬们！😊
