### ISSUE TITLE
小白一个，想问问作者能不能用Clash fo Windows的翻墙代理服务器端口解除B站限制啊，我的端口是HTTP协议的，emmm不是很懂

### ISSUE THREAD

**Issue by SliverHydra** [ipcjs/bilibili-helper#915]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by JasonKhew96** [comment]
@SliverHydra  既然有梯子，直接代理 `*.bilibili.com` 就可以了，根本不用启用脚本

**Comment by SliverHydra** [comment]
哦谢谢，我试试

**Comment by SliverHydra** [comment]
有点奇怪，我用SwitchyOmega添加了条件，twitch和youtube都可以上，但是bilibili就是看不了

**Comment by SliverHydra** [comment]
进去后就变成了。。。非常抱歉的那个小视频

**Comment by SliverHydra** [comment]
刚刚捣鼓了一下弄好了，应该是EDGE的问题，用Chrome直接挂代理就上去了

**Comment by AisukaYuki** [comment]
你可以在脚本解析里面填 https://api.bilibili.com  ，然后clash规则api.bilibili.com走代理。放行upos相关域名，这样解析走代理，缓冲视频直连。节省你的梯子流量

脚本用到的upos↓
        ks3: 'upos-sz-mirrorks3.bilivideo.com',
        ks3b: 'upos-sz-mirrorks3b.bilivideo.com',
        ks3c: 'upos-sz-mirrorks3c.bilivideo.com',
        ks32: 'upos-sz-mirrorks32.bilivideo.com',
        kodo: 'upos-sz-mirrorkodo.bilivideo.com',
        kodob: 'upos-sz-mirrorkodob.bilivideo.com',
        cos: 'upos-sz-mirrorcos.bilivideo.com',
        cosb: 'upos-sz-mirrorcosb.bilivideo.com',
        bos: 'upos-sz-mirrorbos.bilivideo.com',
        wcs: 'upos-sz-mirrorwcs.bilivideo.com',
        wcsb: 'upos-sz-mirrorwcsb.bilivideo.com',
        /** 不限CROS, 限制UA */
        hw: 'upos-sz-mirrorhw.bilivideo.com',
        hwb: 'upos-sz-mirrorhwb.bilivideo.com',
        upbda2: 'upos-sz-upcdnbda2.bilivideo.com',
        upws: 'upos-sz-upcdnws.bilivideo.com',
        uptx: 'upos-sz-upcdntx.bilivideo.com',
        uphw: 'upos-sz-upcdnhw.bilivideo.com',
        js: 'upos-tf-all-js.bilivideo.com',
        hk: 'cn-hk-eq-bcache-01.bilivideo.com',
        akamai: 'upos-hz-mirrorakam.akamaized.net',

**Comment by SliverHydra** [comment]
好的！感谢大佬！

**Comment by ForeverBRS** [comment]
> 你可以在脚本解析里面填 https://api.bilibili.com ，然后clash规则api.bilibili.com走代理。放行upos相关域名，这样解析走代理，缓冲视频直连。节省你的梯子流量
> 
> 脚本用到的upos↓ ks3: 'upos-sz-mirrorks3.bilivideo.com', ks3b: 'upos-sz-mirrorks3b.bilivideo.com', ks3c: 'upos-sz-mirrorks3c.bilivideo.com', ks32: 'upos-sz-mirrorks32.bilivideo.com', kodo: 'upos-sz-mirrorkodo.bilivideo.com', kodob: 'upos-sz-mirrorkodob.bilivideo.com', cos: 'upos-sz-mirrorcos.bilivideo.com', cosb: 'upos-sz-mirrorcosb.bilivideo.com', bos: 'upos-sz-mirrorbos.bilivideo.com', wcs: 'upos-sz-mirrorwcs.bilivideo.com', wcsb: 'upos-sz-mirrorwcsb.bilivideo.com', /** 不限CROS, 限制UA */ hw: 'upos-sz-mirrorhw.bilivideo.com', hwb: 'upos-sz-mirrorhwb.bilivideo.com', upbda2: 'upos-sz-upcdnbda2.bilivideo.com', upws: 'upos-sz-upcdnws.bilivideo.com', uptx: 'upos-sz-upcdntx.bilivideo.com', uphw: 'upos-sz-upcdnhw.bilivideo.com', js: 'upos-tf-all-js.bilivideo.com', hk: 'cn-hk-eq-bcache-01.bilivideo.com', akamai: 'upos-hz-mirrorakam.akamaized.net',

dalao，你好
请问你回复里描述的clash规则是直接修改原有的clash规则吗？你所说的脚本是指哪一个脚本？
具体方式是如何配置？我能在SwitchyOmega配置条件规则来实现这个番剧代理的功能吗？

**Comment by 744695943** [comment]
代理填这个
![image](https://user-images.githubusercontent.com/46646524/150266555-1be0f3c9-f65d-4b9b-af82-7c24ca129787.png)
https://bili.tuturu.top
2022.1.20实测还可用
