### ISSUE TITLE
拉取视频失败，已经授权，更换多个代理服务器，代理服务器可以访问主页

### ISSUE THREAD

**Issue by haoma12138** [ipcjs/bilibili-helper#918]
脚本问题：@ipcjs

## 描述

在控制台显示跨域访问失败，无法拉取视频
Access to XMLHttpRequest at 'https://bilibili.myhosts.ml/pgc/player/web/playurl?avid=977207866&bvid=BV1h44y1a7Gx&cid=458190853&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=424276&session=7cc27121186494f840877995d66e9320&module=bangumi&area=&access_key=9665d97e61cc8627c7f7de9756eaee11' from origin 'https://www.bilibili.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

- 问题网址：

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep424276?spm_id_from=333.999.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"再也没有pc12138","isLogin":true,"level":5,"vipType":0,"vipStatus":0,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bilibili.myhosts.ml/pgc/player/web/playurl?avid=977207866&bvid=BV1h44y1a7Gx&cid=458190853&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=424276&session=7cc27121186494f840877995d66e9320&module=bangumi&area=&access_key=9665d97e61cc8627c7f7de9756eaee11
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"再也没有pc12138","isLogin":true,"level":5,"vipType":0,"vipStatus":0,"isFromReport":false}
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

![image](https://user-images.githubusercontent.com/49445073/148015551-ddcdcb25-e9d6-49f8-a2e2-5bf1c48d7165.png)

## 其他

1. 浏览器版本：Google chrome 96.0.4664.110（正式版本）
2. 国家/地区：大陆

**Comment by JasonKhew96** [comment]
解析服务器 相关，已通知 相关人士
