### ISSUE TITLE
无法获取播放页

### ISSUE THREAD

**Issue by 117649** [ipcjs/bilibili-helper#919]
脚本问题：@ipcjs

## 描述
一些BV地址开始无法获取播放页。
没有错误提示，一切就跟根本没有脚本一样。
![图片](https://user-images.githubusercontent.com/8281345/149197715-2807f5ad-4748-4540-b534-5e0836a18da9.png)

- 问题网址：https://www.bilibili.com/video/BV1Bm4y1D7Uv

## 日志

<details>
<summary>Verbose 日志</summary>

```
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/video/BV1Bm4y1D7Uv
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: fetch https://api.bilibili.com/x/web-interface/search/default {"params":{},"credentials":"include","method":"GET","headers":{"Accept":"application/json, text/plain, */*"}}
debug: fetch https://api.bilibili.com/x/web-show/res/locs?pf=0&ids=2837,2836,2870,2953,2954,2955,2956 {"params":{"pf":0,"ids":"2837,2836,2870,2953,2954,2955,2956"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: /x/web-interface/nav {"uname":"117649","isLogin":true,"level":5,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: fetch https://api.bilibili.com/x/web-interface/dynamic/entrance?alltype_offset=0&video_offset=0&article_offset=0 {"params":{"alltype_offset":0,"video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: fetch https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/web_homepage?alltype_offset=0&video_offset=0&article_offset=0 {"params":{"alltype_offset":0,"video_offset":0,"article_offset":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: fetch https://api.vc.bilibili.com/link_setting/v1/link_setting/get?build=0&mobi_app=web&msg_notify=1&show_unfollowed_msg=1 {"params":{"build":0,"mobi_app":"web","msg_notify":1,"show_unfollowed_msg":1},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: fetch https://api.bilibili.com/x/msgfeed/unread?build=0&mobi_app=web {"params":{"build":0,"mobi_app":"web"},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: fetch https://api.live.bilibili.com/xlive/web-interface/v1/index/RoomForWebMainHover {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: fetch https://api.vc.bilibili.com/session_svr/v1/session_svr/single_unread?build=0&mobi_app=web&unread_type=0 {"params":{"build":0,"mobi_app":"web","unread_type":0},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.55
debug: fetch https://message.bilibili.com/api/tooltip/query.list.do {"params":{},"method":"GET","headers":{"Accept":"application/json, text/plain, */*"},"credentials":"include"}
```
 
</details>

## 其他

1. 浏览器版本：最新的FF ，edge
2. 国家/地区：大陆

**Comment by AisukaYuki** [comment]
https://www.bilibili.com/bangumi/play/ss40084
https://www.bilibili.com/bangumi/media/md28235788
从season和md 链接进去。（话说台区不是都更新到第6集了吗

**Comment by magicdolls** [comment]
> [https://www.bilibili.com/bangumi/play/ss40084 ](https://www.bilibili.com/bangumi/play/ss40084) https://www.bilibili.com/bangumi/media/md28235788 从季节和md链接进去。（话说台区不是都更新到第6集呢

怎么找md页面呢？直接从前一集跳到下一集的ss确实没问题。不过如果找不到上一集的ss下一集也不知道号是多少吧

**Comment by JasonKhew96** [comment]
> > [https://www.bilibili.com/bangumi/play/ss40084 ](https://www.bilibili.com/bangumi/play/ss40084) https://www.bilibili.com/bangumi/media/md28235788 从季节和md链接进去。（话说台区不是都更新到第6集呢
> 
> 怎么找md页面呢？直接从前一集跳到下一集的ss确实没问题。不过如果找不到上一集的ss下一集也不知道号是多少吧

@magicdolls 点下面那个标题就是 md 页
![image](https://user-images.githubusercontent.com/29531167/149365329-e5d4cf99-eecc-4f66-b9b1-32d46d08b823.png)

**Comment by magicdolls** [comment]
> > > [https://www.bilibili.com/bangumi/play/ss40084 ](https://www.bilibili.com/bangumi/play/ss40084) https://www.bilibili.com/bangumi/media/md28235788从季和md链接进去。（话说台区不是都更新到第6集呢
> > 
> > 
> > 怎么找md？直接从前一集跳到下一集确实没问题。不过如果缺少下一集上一集的ss也不知道是多少吧
> 
> @magicdolls点下面那个标题就是md页 ![图片](https://user-images.githubusercontent.com/29531167/149365329-e5d4cf99-eecc-4f66-b9b1-32d46d08b823.png)

额……那是不是也要先进到某一集才能再从下面进md啊，拉取不了地址就进不去，从番剧页面找md就做不到吧。

**Comment by JasonKhew96** [comment]
> > > > [https://www.bilibili.com/bangumi/play/ss40084 ](https://www.bilibili.com/bangumi/play/ss40084) [https://www.bilibili.com/bangumi/media/md28235788从季和md链接进去。（话说台区不是都更新到第6集呢](https://www.bilibili.com/bangumi/media/md28235788%E4%BB%8E%E5%AD%A3%E5%92%8Cmd%E9%93%BE%E6%8E%A5%E8%BF%9B%E5%8E%BB%E3%80%82%EF%BC%88%E8%AF%9D%E8%AF%B4%E5%8F%B0%E5%8C%BA%E4%B8%8D%E6%98%AF%E9%83%BD%E6%9B%B4%E6%96%B0%E5%88%B0%E7%AC%AC6%E9%9B%86%E5%91%A2)
> > > 
> > > 
> > > 怎么找md？直接从前一集跳到下一集确实没问题。不过如果缺少下一集上一集的ss也不知道是多少吧
> > 
> > 
> > @magicdolls点下面那个标题就是md页 ![图片](https://user-images.githubusercontent.com/29531167/149365329-e5d4cf99-eecc-4f66-b9b1-32d46d08b823.png)
> 
> 额……那是不是也要先进到某一集才能再从下面进md啊，拉取不了地址就进不去，从番剧页面找md就做不到吧。

这个你得问 biliplus，biliplus 没记录就跳转不了，以前倒是能正常工作的（诶？biliplus 怎么挂了）

**Comment by snailium** [comment]
> > > > [https://www.bilibili.com/bangumi/play/ss40084 ](https://www.bilibili.com/bangumi/play/ss40084) [https://www.bilibili.com/bangumi/media/md28235788从季和md链接进去。（话说台区不是都更新到第6集呢](https://www.bilibili.com/bangumi/media/md28235788%E4%BB%8E%E5%AD%A3%E5%92%8Cmd%E9%93%BE%E6%8E%A5%E8%BF%9B%E5%8E%BB%E3%80%82%EF%BC%88%E8%AF%9D%E8%AF%B4%E5%8F%B0%E5%8C%BA%E4%B8%8D%E6%98%AF%E9%83%BD%E6%9B%B4%E6%96%B0%E5%88%B0%E7%AC%AC6%E9%9B%86%E5%91%A2)
> > > 
> > > 
> > > 怎么找md？直接从前一集跳到下一集确实没问题。不过如果缺少下一集上一集的ss也不知道是多少吧
> > 
> > 
> > @magicdolls点下面那个标题就是md页 ![图片](https://user-images.githubusercontent.com/29531167/149365329-e5d4cf99-eecc-4f66-b9b1-32d46d08b823.png)
> 
> 额……那是不是也要先进到某一集才能再从下面进md啊，拉取不了地址就进不去，从番剧页面找md就做不到吧。

如果之前曾经看过该番的前几集，可以从右上角“历史”里面找到，点击进入bangumi页

**Comment by Aobanana-chan** [comment]
除了从历史里面找到bangumi页面，也可以去番剧出差的动态，有部分番会在下面显示bangumi页，如果没有，可以进评论区，找找看有没有人把这个番加到了追番列表，也能从这里面进（biliplus 炸了 没法自动跳转的解决方法之一 不是特别好 但有一定的用处）

**Comment by czhang-trinity** [comment]
google 搜 番剧的名字 加上哔哩哔哩港澳台就能找到bangumi页面
