### ISSUE TITLE
观看页白屏，无法加载。

### ISSUE THREAD

**Issue by onecombo** [ipcjs/bilibili-helper#920]
## 描述
观看页白屏，无法加载。

![QBYIM$NNSN{LF7S4AWFHF7T](https://user-images.githubusercontent.com/33618120/149444150-12a8b5c9-a072-4571-97c2-e0039c85d641.png)

- 问题网址：
- https://www.bilibili.com/bangumi/media/md28236370
- https://www.bilibili.com/bangumi/play/ep458195

## 日志
这个状态不知道怎么拿到日志，因为没加载插件的图标

![image](https://user-images.githubusercontent.com/33618120/149444298-e9f3aca2-fa82-448f-8737-824b9619c41a.png)

## 其他

1. 浏览器版本：Microsoft Edge 版本 97.0.1072.55 (官方内部版本) (64 位)
2. 国家/地区：中国

**Comment by JasonKhew96** [comment]
adblock 问题

**Comment by onecombo** [comment]
> 

最初我自己排查的时候已经关掉了adb，但问题没得到解决。
而且奇怪的是，只有这个写着A站独播的番有这样的问题，其他港澳台限定可以正常观看。

**Comment by onecombo** [comment]
不好意思啊，插件更新到最新版一切问题都解决了  谢谢。
