### ISSUE TITLE
所有番剧都是“非常抱歉”

### ISSUE THREAD

**Issue by penguin-drum** [ipcjs/bilibili-helper#921]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：chrome
2. 国家/地区：

**Comment by JasonKhew96** [comment]
_代理服务器已转移至域名https://repost.98e.org_

**Comment by penguin-drum** [comment]
> _代理服务器已转移至域名https://repost.98e.org_

感谢！好了
