### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

### ISSUE THREAD

**Issue by suiyidr** [ipcjs/bilibili-helper#926]
## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

**Comment by JasonKhew96** [comment]
> ## 拉取视频地址失败
> 原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}

解析服务器被打了
