### ISSUE TITLE
页面跳转功能失效了

### ISSUE THREAD

**Issue by Akarii9** [ipcjs/bilibili-helper#927]
前几天还没事儿，这两天突然出现的问题，只能从别人给的ep号链接进入番剧首页，点击单集可以观看，从番剧出差直接点击某个单集无法从bv号跳转到ep号了，先是显示获取番剧页Url中...然后就是error:[object XMLHttpRequest]

**Comment by JasonKhew96** [comment]
> 前几天还没事儿，这两天突然出现的问题，只能从别人给的ep号链接进入番剧首页，点击单集可以观看，从番剧出差直接点击某个单集无法从bv号跳转到ep号了，先是显示获取番剧页Url中...然后就是error:[object XMLHttpRequest]

biliplus 挂了

**Comment by Akarii9** [comment]
> 

啊？那个不是之前早就挂了么，居然还一直活到了最近是么..

**Comment by Akarii9** [comment]
> > 前几天还没事儿，这两天突然出现的问题，只能从别人给的ep号链接进入番剧首页，点击单集可以观看，从番剧出差直接点击某个单集无法从bv号跳转到ep号了，先是显示获取番剧页Url中...然后就是error:[object XMLHttpRequest]
> 
> biliplus 挂了

啊？那个不是之前早就挂了么，居然还一直活到了最近是么..

**Comment by JasonKhew96** [comment]
> > 
> 
> 啊？那个不是之前早就挂了么，居然还一直活到了最近是么..

没，只是解析的挂了，现在全挂
油猴脚本还在用的BV 转 EP 的功能

**Comment by Akarii9** [comment]
> > 啊？那个不是之前早就挂了么，居然还一直活到了最近是么..
> 
> 没，只是解析的挂了，现在全挂 油猴脚本还在用的BV 转 EP 的功能

这ep号还有啥获取方法么？暂时只能从别人空间里找了，冷门点的就难了

**Comment by 5lx** [comment]
相同症状，bv->ep 挂了

**Comment by Yuuki-Rito** [comment]
> > > 啊？那个不是之前早就挂了么，居然还一直活到了最近是么..
> > 
> > 
> > 没，只是解析的挂了，现在全挂 油猴脚本还在用的BV 转 EP 的功能
> 
> 这ep号还有啥获取方法么？暂时只能从别人空间里找了，冷门点的就难了

![2022-01-24 11-24-05 的屏幕截图](https://user-images.githubusercontent.com/24408875/150717379-2b543bd8-6231-437d-8273-b8905b5189fa.png)
![2022-01-24 11-24-15 的屏幕截图](https://user-images.githubusercontent.com/24408875/150717492-ebf084de-900d-45da-be53-aad23bca65e2.png)

你说的挂了是指接口挂了吗？我看链接，bv已经转成ep了啊

**Comment by JasonKhew96** [comment]
> > > > 啊？那个不是之前早就挂了么，居然还一直活到了最近是么..
> > > 
> > > 
> > > 没，只是解析的挂了，现在全挂 油猴脚本还在用的BV 转 EP 的功能
> > 
> > 这ep号还有啥获取方法么？暂时只能从别人空间里找了，冷门点的就难了
> 
> ![2022-01-24 11-24-05 的屏幕截图](https://user-images.githubusercontent.com/24408875/150717379-2b543bd8-6231-437d-8273-b8905b5189fa.png)
> ![2022-01-24 11-24-15 的屏幕截图](https://user-images.githubusercontent.com/24408875/150717492-ebf084de-900d-45da-be53-aad23bca65e2.png)
> 
> 你说的挂了是指接口挂了吗？我看链接，bv已经转成ep了啊
> 
> 

它又好了，炸了一天多了
