### ISSUE TITLE
在AV页面启用功能似乎失效了？

### ISSUE THREAD

**Issue by owwkmidream** [ipcjs/bilibili-helper#930]
这个功能是让普通视频也走解析对吧，更换多个解析服务器都没法解析普通视频，似乎已经失效了

**Comment by JasonKhew96** [comment]
@owwkmidream 大部分 解析服务器 不支持 普通视频

**Comment by owwkmidream** [comment]
> @owwkmidream 大部分 解析服务器 不支持 普通视频

了解了，谢谢
