### ISSUE TITLE
安装脚本之后还是无法正常观看## 拉取视频地址失败 原因: {"code":-10403,"message":"抱歉您所在地区不可观看！","ttl":1}

### ISSUE THREAD

**Issue by YuBuc** [ipcjs/bilibili-helper#931]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep96704?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"YuBuck丶","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=6650172&bvid=BV1us41147pW&cid=11234416&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=96704&session=7a6d2ff0f73e9fd9e3b6b54e701a5a4f&module=bangumi&area=&access_key=e55bfe8014d9ae46ad98df6aac7b1811
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=6650172&bvid=BV1us41147pW&cid=11234416&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=96704&session=7a6d2ff0f73e9fd9e3b6b54e701a5a4f&module=bangumi&access_key=e55bfe8014d9ae46ad98df6aac7b1811
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"YuBuck丶","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：FireFox
2. 国家/地区：中国大陆

**Comment by JasonKhew96** [comment]
设置 解析服务器 了吗？
日志都没有（

**Comment by YuBuc** [comment]
设置了，日志是这样吗

**Comment by JasonKhew96** [comment]
> 设置了，日志是这样吗

播放出问题时候的日志（先看一下你设置的什么 公共解析服务器 吧，日志用处不大，有些东西没打印

**Comment by YuBuc** [comment]
这是播放出问题的日志debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep96704?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"YuBuck丶","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=6650172&bvid=BV1us41147pW&cid=11234416&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=96704&session=7a6d2ff0f73e9fd9e3b6b54e701a5a4f&module=bangumi&area=&access_key=e55bfe8014d9ae46ad98df6aac7b1811
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=6650172&bvid=BV1us41147pW&cid=11234416&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=96704&session=7a6d2ff0f73e9fd9e3b6b54e701a5a4f&module=bangumi&access_key=e55bfe8014d9ae46ad98df6aac7b1811
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"YuBuck丶","isLogin":true,"level":4,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0

**Comment by YuBuc** [comment]
这是用的服务器https://api.qiu.moe

**Comment by YuBuc** [comment]
其实换了好几个服务器了都不行

**Comment by JasonKhew96** [comment]
首选随便填，比如 `https://api.bilibili.com`
其他四个地区才填 解析服务器，现在大部分的 解析服务器 都分地区了，首选差不多可以扔了

例如: 
![image](https://user-images.githubusercontent.com/29531167/151168434-0bd07922-42e3-4b3c-b813-2d8bc23733f5.png)

**Comment by YuBuc** [comment]
可以了！太感谢了！！！！不好意思添麻烦了

**Comment by YuBuc** [comment]
我想再问一个问题就是搜索的话就变成只能搜索到大陆可以看得番剧，仅限港澳台的番剧搜索不到怎么办呢

**Comment by JasonKhew96** [comment]
> 我想再问一个问题就是搜索的话就变成只能搜索到大陆可以看得番剧，仅限港澳台的番剧搜索不到怎么办呢

https://github.com/gamekingv/bilibili-oversea-search

**Comment by YuBuc** [comment]
好的谢谢！

**Comment by MrAccelerator** [comment]
太有帮助了，感谢！！！
