### ISSUE TITLE
## 拉取视频地址失败 原因: {"code":-2,"message":"Access Key错误","ttl":1}

### ISSUE THREAD

**Issue by gwwydsb** [ipcjs/bilibili-helper#932]
脚本问题：@ipcjs

## 描述
安装脚本后无法观看

- 问题网址：https://www.bilibili.com/bangumi/play/ep380299?from_spmid=666.4.0.0

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep380299?from_spmid=666.4.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: undefined
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"是柰白哟","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=929673924&bvid=BV1kK4y1U7EU&cid=312261618&qn=116&fnver=0&fnval=2000&fourk=1&ep_id=380299&session=b3c478ede95341f6389051be05bde548&module=bangumi&area=hk
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=929673924&bvid=BV1kK4y1U7EU&cid=312261618&qn=116&fnver=0&fnval=2000&fourk=1&ep_id=380299&session=b3c478ede95341f6389051be05bde548&module=bangumi&area=
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=929673924&bvid=BV1kK4y1U7EU&cid=312261618&qn=116&fnver=0&fnval=2000&fourk=1&ep_id=380299&session=b3c478ede95341f6389051be05bde548&module=bangumi&area=cn
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/intl/gateway/v2/ogv/playurl?area=th&access_key=undefined&appkey=7d089525d3611b1c&build=1001310&cid=312261618&ep_id=380299&fnval=2000&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=116&ts=1643333857&sign=e8181153dc24b645f159a2e339178c1c
debug: /x/web-interface/nav {"uname":"是柰白哟","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/pgc/player/web/playurl?avid=929673924&bvid=BV1kK4y1U7EU&cid=312261618&qn=116&fnver=0&fnval=2000&fourk=1&ep_id=380299&session=b3c478ede95341f6389051be05bde548&module=bangumi&area=tw
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.69

## 其他

1. 浏览器版本：Edge
2. 国家/地区：中国

**Comment by JasonKhew96** [comment]
没授权

**Comment by gwwydsb** [comment]
解决了，谢谢！
