### ISSUE TITLE
同网络环境和同代理服务器 一台电脑可用另一台不可用

### ISSUE THREAD

**Issue by yuanyao56** [ipcjs/bilibili-helper#934]
脚本问题：@ipcjs

## 描述
在同样的网络环境下和同样的代理服务器 在windows的chrome里脚本可以正常运行， mac的chrome无法解析视频
windows的chrome版本是97.0.4692.99.
脚本版本都是v8.2.13
代理服务器用的是https://bili.lli.cx

已经尝试删除cookie重新授权

- 问题网址：
https://www.bilibili.com/bangumi/play/ep323659

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep323658
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: wcs flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"一只泉泉","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"一只泉泉","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep323658 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.lil.cx/pgc/player/web/playurl?avid=676758588&bvid=BV1KU4y1u7We&cid=184638145&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=323658&session=85386247828f6991969b0e4cebca2ec8&module=bangumi&area=&access_key=52935362b348fbffff7cfaecd5e13121
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

</details>

## 其他

1. 浏览器版本：Version 96.0.4664.55
2. 国家/地区：美国

**Comment by JasonKhew96** [comment]
~~这家 解析服务器 dns 好像 爆炸 了~~

**Comment by JasonKhew96** [comment]
撤回前言，不是 https://bili.lli.cx 吗

**Comment by yuanyao56** [comment]
不好意思弄错了。。。

<details>
<summary>Verbose 日志</summary>

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.13 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep322378
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: wcs flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"一只泉泉","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep322378 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.lli.cx/pgc/player/web/playurl?avid=719254499&bvid=BV1pQ4y1U7c5&cid=185370687&qn=0&fnver=0&fnval=2000&fourk=1&ep_id=322378&session=216d4ca31d8d158f1a449b1e1f59b403&module=bangumi&area=&access_key=52935362b348fbffff7cfaecd5e13121
debug: /x/web-interface/nav {"uname":"一只泉泉","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
</details>


弹窗错误和日志错误有些不一样

原因: {"code":-1,"error":{"readyState":4,"responseText":"
\nWarning:  Trying to access array offset on value of type bool in /www/wwwroot/bili.lli.cx/utils/functions_cache.php on line 473
\n{\"code\":-10403,\"message\":\"抱歉您所在地区不可观看！\"}","status":200,"statusText":"parsererror"}}

**Comment by JasonKhew96** [comment]
重新授权就可以了

**Comment by yuanyao56** [comment]
重新授权还是没用

**Comment by JasonKhew96** [comment]
那换个解析服务器（

**Comment by AisukaYuki** [comment]
area参数为空，请在下方地区填上解析服务器，首选没用随便填。
