### ISSUE TITLE
拉取视频地址失败，用的移动设备可以么

### ISSUE THREAD

**Issue by phasure** [ipcjs/bilibili-helper#935]
脚本问题：@ipcjs

## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}
- 问题网址：https://www.bilibili.com/bangumi/play/ss40713?from_spmid=666.49.0.0

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他
![IMG_2114](https://user-images.githubusercontent.com/99422675/153460641-3f03d7fb-a82b-4a89-ad95-bd1766c1784c.png)

1. 浏览器版本：foxok
2. 国家/地区：

**Comment by phasure** [comment]
不好意思，，换了个服务器现在
![IMG_2116](https://user-images.githubusercontent.com/99422675/153464561-48f572b5-93d0-4809-b0c9-cb063af96e5c.png)

**Comment by phasure** [comment]
日志：warn: 解除B站区域限制 interactive 加载时机不太对, 不能保证正常工作

1. 尝试刷新页面, 重载脚本
2. 若依然出现该提示, 请尝试'硬性重新加载'(快捷键一般为ctrl+f5)
3. 若还是出现该提示, 请尝试关闭再重新打开该页面
4. 若反复出现该提示, 那也没其他办法了_(:3」∠)_

debug: atRun: 1, interactive
debug: [解除B站区域限制 v8.2.13 (FoxokMonkey)] run on: https://www.bilibili.com/bangumi/play/ss40713?from_spmid=666.49.0.0
debug: window.__playinfo__ 
debug: retryUntil.ajaxBy$: function (e,t){return new k.fn.init(e,t)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=40713
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function (e,t){return new k.fn.init(e,t)}
info: mode: default blocked_vip: Y server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  enable_in_av:  readyState: interactive isLogin: false isLoginBiliBili: true
debug: __playinfo__ get
debug: atRun: 1, interactive
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ss40713 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function (e,t){return new k.fn.init(e,t)}
debug: ajax: https://api.qiu.moe/?cid=481962605&qn=0&type=mp4&otype=json&fourk=1&bvid=BV1iu41127P9&ep_id=455123&fnver=0&fnval=1&session=8dda160b9ba60ed970ae7b0025bb9b24&module=bangumi&access_key=804cd3d83a5898d9441f813e81578d21
debug: atRun: 1, interactive
debug: atRun: 1, interactive
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function (e,t){return new k.fn.init(e,t)}
debug: ajax: https://1592824905474106.cn-hongkong.fc.aliyuncs.com/2016-08-15/proxy/bilibili/blbl/?cid=481962605&qn=0&type=mp4&otype=json&fourk=1&bvid=BV1iu41127P9&ep_id=455123&fnver=0&fnval=1&session=8dda160b9ba60ed970ae7b0025bb9b24&module=bangumi&access_key=804cd3d83a5898d9441f813e81578d21
debug: __playinfo__ set
debug: set jQuery function (e,t){return new k.fn.init(e,t)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ss40713 true
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.qiu.moe/?avid=undefined&cid=481962605&bvid=BV1iu41127P9&qn=0&type=mp4&otype=json&ep_id=455123&fourk=1&fnver=0&fnval=1&session=57cb9428326aedd8d3e882c6c2ae4359&module=bangumi&balh_ajax=1&access_key=804cd3d83a5898d9441f813e81578d21
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1592824905474106.cn-hongkong.fc.aliyuncs.com/2016-08-15/proxy/bilibili/blbl/?avid=undefined&cid=481962605&bvid=BV1iu41127P9&qn=0&type=mp4&otype=json&ep_id=455123&fourk=1&fnver=0&fnval=1&session=57cb9428326aedd8d3e882c6c2ae4359&module=bangumi&balh_ajax=1&access_key=804cd3d83a5898d9441f813e81578d21
debug: /x/web-interface/nav {"uname":"衿央","isLogin":true,"level":2,"vipType":0,"vipStatus":0,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:63.0) Gecko/20100101 Firefox/63.0

**Comment by AisukaYuki** [comment]
去掉域名后面的尾斜杠，~~安卓平板为什么不用漫游呢？~~ ipad 那没事了
