### ISSUE TITLE
该脚本会限制B站自动播放功能以及系统自带的一些功能

### ISSUE THREAD

**Issue by CYLlinmaian** [ipcjs/bilibili-helper#941]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by MikuMikuMe** [comment]
我可以自动播放

“该脚本会限制B站自动播放功能以及系统自带的一些功能” 就靠这句话谁能解决你的问题。。。
