### ISSUE TITLE
转载请求

### ISSUE THREAD

**Issue by CodFrm** [ipcjs/bilibili-helper#942]
大佬您好：

我是油猴中文网的管理员[王一之](https://bbs.tampermonkey.net.cn/home.php?mod=space&uid=4&do=profile)，我想将您的脚本：[解除B站区域限制](https://github.com/ipcjs/bilibili-helper/blob/user.js/scripts/bilibili_bangumi_area_limit_hack.user.js)，转载至我们的论坛：[油猴中文网](https://bbs.tampermonkey.net.cn/)，您看可以吗？

关于更新，我们会使用您的脚本链接设置自动同步在我们的论坛上进行更新。如果您不愿意创建账号，我们会将转载的脚本放在一个脚本搬运工的账号上，未来如果您愿意来论坛玩耍会把权限返还给您。

期待大佬的回复^_^。

关于我们论坛是一个油猴脚本的开发与交流的社区；同时我们也提供脚本的发布和安装，另外我们有开发一个新的类油猴扩展：脚本猫，除了支持油猴脚本外，还支持后台与定时脚本，更多的功能和接口还在开发中。

**Comment by ipcjs** [comment]
目前Greasy Fork并不存在被墙的问题，没有建立专门的中文站的必要🤔

**Comment by CodFrm** [comment]
我们的性质更多是一个社区，可以进行交流，提问，分享；论坛的目的也是希望能吸引更多小白加入油猴开发，提供了学习资料和油猴开发工具，这些对大佬来说应该是不太需要啦。

gf更多是一个脚本市场，另外觉得gf的一些功能、审核机制，不太好用或者不合适现在的开发模式（比如打包、不能最小化发布），所以也有尝试做一个脚本市场

也有在做一些工具和新的扩展来丰富油猴脚本的生态之类，不过算是另外的东西了

**Comment by ipcjs** [comment]
脚本本来就提倡简洁，一般不需要打包，不需要“最小化”

如果像这个脚本一样需要打包，完全可以用gf的同步github功能

你论坛要转载，完全可以通过放gf链接的方式转载，没必要同步源码
