### ISSUE TITLE
番剧索引 

### ISSUE THREAD

**Issue by czhang-trinity** [ipcjs/bilibili-helper#946]
b站番剧索引好像也屏蔽海外了 脚本不在这个api生效 
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/35928300/156965639-c8999877-061a-43c2-9ba3-f79856f7fa16.png">

脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by BraveSail** [comment]
这要解析服务器支持，比较麻烦，建议通过搜索查找自己想看的番

**Comment by 34736384** [comment]
索引这个其实替换掉api接口就行了，不过这个脚本太长，我就不清楚在哪下手了
我就单独开了个脚本试了下
![image](https://user-images.githubusercontent.com/25654009/159114263-f4c89c4b-c30f-43b0-9e07-1529cf613e0a.png)
