### ISSUE TITLE
观看东南亚地区的番剧时视频资料下载错误

### ISSUE THREAD

**Issue by xujames0704** [ipcjs/bilibili-helper#947]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.15 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28236374/?spm_id_from=333.937.b_6d656469615f6d6f64756c65.2
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=40668&access_key=de8991f544ccc1045a36a8a61235a131
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"非洲联合舰队指挥官","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: /x/web-interface/nav {"uname":"非洲联合舰队指挥官","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":1,"follow_status":2,"login":1,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":452973,"last_ep_index":"8","last_time":578},"real_price":"0","sponsor":0,"vip_info":{"due_date":1681747200000,"status":1,"type":2}}}
debug: setAreaLimitSeason 000 true
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
debug: season40668 {"code":0,"message":"success","result":{"actor":[{"actor":"直田姬奈","actor_id":0,"role":"喜多川海夢"},{"actor":"石毛翔彌","actor_id":0,"role":"五條新菜"},{"actor":"種崎敦美","actor_id":0,"role":"乾紗壽葉"},{"actor":"羊宮妃那","actor_id":0,"role":"乾心壽"},{"actor":"斧篤","actor_id":0,"role":"五條薰"}],"alias":"その着せ替え人形は恋をする,換裝娃娃,My Dress-up Darling,戀上換裝娃娃","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"5929","bangumi_title":"戀上換裝娃娃（僅限港澳台地區）","brief":"男高中生五條新菜夢想著成為製作雛人形面部的「頭師」。\n全身心地投入到製作雛人形後，他離同齡人的流行話...","business_type":1,"coins":"0","copyright":"bilibili","cover":"https://i0.hdslb.com/bfs/bangumi/image/72885907367bb4cb970e53592a719e0c1d61ea8f.png","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"509479502","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0d20a72a424129d8d93313456dc504d342aa5260.png","danmaku":"541370125","episode_id":"452974","episode_status":2,"episode_type":0,"from":"bangumi","index":"9","index_title":"看了照片之後發生了些事","is_new":"1","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-03-06 00:30:01.0"},{"av_id":"296870763","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/ac68b0ba1a4319a364f0aac4367e9fa7649b73b5.png","danmaku":"516487999","episode_id":"452973","episode_status":2,"episode_type":0,"from":"bangumi","index":"8","index_title":"我推薦逆光拍","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-27 00:30:00.0"},{"av_id":"679188461","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/ef9e400480323de6f285cb845c54dbcc0ea9ec62.png","danmaku":"511607516","episode_id":"452972","episode_status":2,"episode_type":0,"from":"bangumi","index":"7","index_title":"和喜番的人在家約會太不妙了","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-20 00:30:01.0"},{"av_id":"978881920","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/55a480ccd4ac5bdfaead9f7a365618961e266005.png","danmaku":"506256288","episode_id":"452971","episode_status":2,"episode_type":0,"from":"bangumi","index":"6","index_title":"真假!?","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-13 00:30:01.0"},{"av_id":"766350080","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a3168b441f7d7d4ce7c523c713fd97e726366bf1.png","danmaku":"501050224","episode_id":"452970","episode_status":2,"episode_type":0,"from":"bangumi","index":"5","index_title":"因為這是在場最棒的乳袋吧?","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-06 00:30:00.0"},{"av_id":"678616443","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/ad28f3285e050565a6dc37e73a0fb7ad01905f06.png","danmaku":"494893021","episode_id":"452969","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"這是女朋友的嗎?","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-30 00:30:01.0"},{"av_id":"593327813","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/dd598a30e2d6c0c48697c7f67589b246497af9aa.png","danmaku":"489205507","episode_id":"452968","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"那就在一起吧?","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-23 00:30:01.0"},{"av_id":"380671053","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/74fad57db852ef350f211c0107de6508d21c835a.png","danmaku":"484149811","episode_id":"452967","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"馬上就來做吧?","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-16 00:30:01.0"},{"av_id":"422908737","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/5daf10727088f2f0bc31126d1af4d19b8177cdf1.png","danmaku":"479225036","episode_id":"452966","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"和自己生活在截然不同世界的人","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-09 00:30:01.0"}],"evaluate":"男高中生五條新菜夢想著成為製作雛人形面部的「頭師」。\n全身心地投入到製作雛人形後，他離同齡人的流行話題越來越遠，以至於遲遲無法融入班級。\n對於這樣的新菜來說，一直是班級中心人物的喜多川海夢簡直像是生活在完全不同世界的人。然而有一天，一件意想不到的事情讓他與海夢擁有了共同的秘密……！？\n兩人原本毫無交集的世界因此產生了聯繫！\n福田晉一連載于《YOUNG GANGAN》（史克威爾·艾尼克斯）的超人氣原作，終於要由CloverWorks做成動畫啦！\n由豪華的製作陣容獻給觀眾們的換裝萌妹故事！\n","favorites":"0","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"その着せ替え人形は恋をする","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/72885907367bb4cb970e53592a719e0c1d61ea8f.png","episode_index":{"index_show":"连载中, 每週日更新"},"media_id":28236374,"publish":{"is_finish":0,"is_started":1},"title":"戀上換裝娃娃（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"452974","newest_ep_index":"9","origin_name":"その着せ替え人形は恋をする","play_count":"0","pub_string":"","pub_time":"2022-01-09 00:30:00","pub_time_show":"1月9日 00:30 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"40668","season_status":2,"season_title":"TV","seasons":[{"bangumi_id":"5929","cover":"https://i0.hdslb.com/bfs/bangumi/image/72885907367bb4cb970e53592a719e0c1d61ea8f.png","is_finish":"0","newest_ep_id":"452974","newest_ep_index":"9","season_id":"40668","season_status":2,"title":"TV"}],"share_url":"http://bangumi.bilibili.com/anime/40668/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/4e801198d10d20051f23eac43f39616de94dc453.jpg","staff":"原作：福田晉一（連載于《YOUNG GANGAN》史克威爾·艾尼克斯刊物）\n導演：篠原啟輔\n劇本統籌、編劇：富田賴子\n角色設計、總作畫導演：石田一將\n音樂：中塚武\n音響監督：藤田亞紀子\n製作：CloverWorks\n\n","tag2s":[],"tags":[],"title":"戀上換裝娃娃（僅限港澳台地區）","update_pattern":"每週日更新","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}

**Comment by JasonKhew96** [comment]
你 这个 日志 没用
播放 失败 后，浏览器 打开 F12 console 那里 输入 `bangumi_area_limit_hack.showSettings();`
脚本菜单 会弹出来

**Comment by AisukaYuki** [comment]
#906
