### ISSUE TITLE
部分视频无法解析出番剧页面

### ISSUE THREAD

**Issue by kirayomato** [ipcjs/bilibili-helper#948]
脚本问题：@ipcjs

## 描述

- 问题网址：https://www.bilibili.com/video/BV1Xq4y1x7zA
- 提示：
```
[error:{"code":-403,"message":"访问权限不足","ttl":1}]()
```

## 其他

1. 浏览器版本：Edge 99.0
2. 国家/地区：中国大陆

**Comment by AisukaYuki** [comment]
限区的部分BV是废的
https://www.bilibili.com/bangumi/play/ep434530
https://www.bilibili.com/bangumi/media/md28235788
建议从出差空间或者搜索结果进去

**Comment by kirayomato** [comment]
> 限区的部分BV是废的 https://www.bilibili.com/bangumi/play/ep434530 https://www.bilibili.com/bangumi/media/md28235788 建议从出差空间或者搜索结果进去

这个链接就是在番剧出差的投稿里面找到的
要怎么搜索啊？站内搜索我搜不到港澳台的番剧

**Comment by AisukaYuki** [comment]
叔叔把网页改版了，出差空间只剩BV连接了。plus接口问题，BV跳转失败。搜索页面也改版了，搜索脚本也还没适配目前无解。
谷歌可以搜索关键字 XX 仅限港澳台。
站内搜索肯定没用
#919

**Comment by JSTks24** [comment]
想看番剧在这里搜就OK
https://bangumi.jasonkhew96.eu.org/bilibili/

**Comment by KurosakiRei** [comment]
> 叔叔

我今天正好也遇到同样的问题了，虽然搜索脚本还没有适配，但是网页右边有可以“回到旧版”的选项

**Comment by KurosakiRei** [comment]
> 叔叔把网页改版了，出差空间只剩BV连接了。plus接口问题，BV跳转失败。搜索页面也改版了，搜索脚本也还没适配目前无解。 谷歌可以搜索关键字 XX 仅限港澳台。 站内搜索肯定没用 #919

我今天正好也遇到同样的问题了，虽然搜索脚本还没有适配，但是网页右边有可以“回到旧版”的选项

**Comment by Asendaushoe** [comment]
现在MD和SS连接也打不开了？

**Comment by JSTks24** [comment]
> 现在MD和SS连接也打不开了？

刚刚试了一下，可以打开

**Comment by JasonKhew96** [comment]
> 现在MD和SS连接也打不开了？

@o81018o  部分地区会跳转 404，或许是暂时抽风

EDIT: 看了一眼代码，脚本自己修了，不会跳 404
