### ISSUE TITLE
跳转之后显示  16s非常抱歉视频

### ISSUE THREAD

**Issue by qhmorz** [ipcjs/bilibili-helper#951]
脚本问题：@ipcjs

## 描述

跳转正常但是跳转到播放页面是一个16s的
非常抱歉
本视频可能由于以下原因无法播放
- 问题网址：
哔哩哔哩所有港澳台番剧

## 日志

<details>
<summary>Verbose 日志</summary>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.15 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28236421
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"李依李好きですOfficial","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=40715&access_key=05aa0f9c257283e1483554ec47496831
debug: atRun: 1, interactive
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":1,"follow_status":2,"login":1,"pay":0,"pay_pack_paid":0,"progress":{"last_ep_id":455169,"last_ep_index":"10","last_time":-1},"real_price":"0","sponsor":0,"vip_info":{"due_date":1678809600000,"status":1,"type":2}}}
debug: /x/web-interface/nav {"uname":"李依李好きですOfficial","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: season40715 {"code":0,"message":"success","result":{"actor":[{"actor":"鈴木崚汰","actor_id":0,"role":"赤星畢斯可"},{"actor":"花江夏樹","actor_id":0,"role":"貓柳美祿"},{"actor":"近藤玲奈","actor_id":0,"role":"貓柳帕烏"},{"actor":"富田美憂","actor_id":0,"role":"大茶釜滋露"},{"actor":"齋藤志郎","actor_id":0,"role":"賈維（ジャビ）"}],"alias":"錆喰いビスコ,食鏽末世錄","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"5945","bangumi_title":"食鏽末世錄（僅限港澳台地區）","brief":"穿梭於能夠銹蝕一切，使人類陷入死亡威脅的“銹蝕風”中，迅猛粗暴的“蕈菇守護者”赤星畢斯可。他為了拯救...","business_type":1,"coins":"0","copyright":"bilibili","cover":"https://i0.hdslb.com/bfs/bangumi/image/23e1fb40e1ae989327010ae3f18d724daa57dfd7.png","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"809911819","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/1cbec770d665a0faa5e1a7d323b71ddb330de740.png","danmaku":"554944605","episode_id":"455170","episode_status":2,"episode_type":0,"from":"bangumi","index":"11","index_title":"我就是畢斯可!","is_new":"1","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-03-21 23:35:01.0"},{"av_id":"724799564","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0ef41e01e2e5ffa06fa12dd477f43dab16913ed8.png","danmaku":"549184636","episode_id":"455169","episode_status":2,"episode_type":0,"from":"bangumi","index":"10","index_title":"復活的鐵人","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-03-14 23:35:00.0"},{"av_id":"382029230","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/2b3adb5f672ddda7038adc9103b97709fa234dce.png","danmaku":"543874973","episode_id":"455168","episode_status":2,"episode_type":0,"from":"bangumi","index":"9","index_title":"我會愛著你","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-03-07 23:35:00.0"},{"av_id":"509383000","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/ac6b3ad811f561038dbe15c8b4dae9d2e4408bfb.png","danmaku":"518691024","episode_id":"455167","episode_status":2,"episode_type":0,"from":"bangumi","index":"8","index_title":"邪魔歪道的陷阱","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-28 23:35:01.0"},{"av_id":"636649364","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/8c02fdb275d3e851d2fef9fdd88f14a990c757db.png","danmaku":"513706333","episode_id":"455166","episode_status":2,"episode_type":0,"from":"bangumi","index":"7","index_title":"被奪走的食鏽","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-21 23:35:01.0"},{"av_id":"681518402","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/378e869086525b003abcd7f3b5e0d3f48dcd27b9.png","danmaku":"508586302","episode_id":"455165","episode_status":2,"episode_type":0,"from":"bangumi","index":"6","index_title":"旅伴與收穫","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-14 23:35:00.0"},{"av_id":"723802470","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/597237a4c15a8acc207d1d65410bed30442ded2f.png","danmaku":"503203755","episode_id":"455164","episode_status":2,"episode_type":0,"from":"bangumi","index":"5","index_title":"孩子們的堡壘","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-02-07 23:35:01.0"},{"av_id":"681158155","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f02763bc88a242f58d7d8769c2b4b479a4f32498.png","danmaku":"498295551","episode_id":"455163","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"乘坐螃蟹","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-31 23:35:01.0"},{"av_id":"337984797","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/1bab7dbef19f913743b885ecf781e2034a028410.jpg","danmaku":"477213553","episode_id":"457805","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV3","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-09 18:00:01.0"},{"av_id":"765895461","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d5fb91b33426de966b5c70cab5bfe6f0f01515cd.png","danmaku":"491379613","episode_id":"455162","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"搭檔","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-24 23:35:01.0"},{"av_id":"808141167","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/983c45b8656ffce6f619ae633356c92c6f436938.png","danmaku":"486226983","episode_id":"455161","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"用杏鮑菇飛越","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-17 23:35:01.0"},{"av_id":"935422030","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/1e8b2a23a5b7e059b59f1be813f34e85e8dc8be2.jpg","danmaku":"477213437","episode_id":"457804","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV2","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-07 18:00:01.0"},{"av_id":"677876102","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/b6ae78ef291292f212735c4cd2991b38e1871c3b.jpg","danmaku":"477213303","episode_id":"457803","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-05 18:00:01.0"},{"av_id":"380532608","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/08eca00be82f8b2ffbb7e9c4141038a86e1b16b7.png","danmaku":"481291612","episode_id":"455160","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"八十萬日貨的男人","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-01-10 23:35:01.0"}],"evaluate":"穿梭於能夠銹蝕一切，使人類陷入死亡威脅的“銹蝕風”中，迅猛粗暴的“蕈菇守護者”赤星畢斯可。他為了拯救師父，而踏上尋找靈藥蕈菇「食鏽」的旅程。\n畢斯可帶著搭檔──美貌的少年醫師美祿，投身波瀾萬丈的冒險中。他們行經寬廣的埼玉鐵沙漠、由毀滅文明的防衛兵器殘骸架構而成的城鎮、大章魚盤據的廢棄地下鐵路線──嚴苛路途中面臨的各種威脅，都以美祿的靈機一動，與畢斯可的必中蕈菇箭一舉貫穿！但旅途的前方卻有邪惡縣知事的奸計等著他們──\n奪下第24屆電擊小說大賞「銀賞」的疾風怒濤冒險劇，就此開幕！\n","favorites":"0","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"錆喰いビスコ","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/23e1fb40e1ae989327010ae3f18d724daa57dfd7.png","episode_index":{"index_show":"连载中, 每週一更新"},"media_id":28236421,"publish":{"is_finish":0,"is_started":1},"title":"食鏽末世錄（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"455170","newest_ep_index":"11","origin_name":"錆喰いビスコ","play_count":"0","pub_string":"","pub_time":"2022-01-10 23:35:00","pub_time_show":"1月10日 23:35 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"40715","season_status":2,"season_title":"TV","seasons":[{"bangumi_id":"5945","cover":"https://i0.hdslb.com/bfs/bangumi/image/23e1fb40e1ae989327010ae3f18d724daa57dfd7.png","is_finish":"0","is_new":"1","newest_ep_id":"455170","newest_ep_index":"11","season_id":"40715","season_status":2,"title":"TV"}],"share_url":"http://bangumi.bilibili.com/anime/40715/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/58f3ebefc253f5e944e9d9379c417c928491a80f.jpg","staff":"原作：瘤久保慎司《食鏽末世錄》（電擊文庫刊）\n原作插畫：赤岸K\n原作世界觀插畫：mocha\n監督：碇穀敦\n副監督：又賀大介\n系列構成、劇本：村井貞之\n角色設計：淺利步惟、碇穀敦\n總作畫監督：淺利步惟、井川典惠\n主要動畫師：松原豐、河合桃子、豆塚あす香、竹知仁美\n動畫監督：張逸暉\n美術監督：三宅昌和\n美術、生物設定：曾野由大\n色彩設計：千葉繪美\n特效監修：穀口久美子\n攝影監督：高木翼\nCG導演：三田邦彥\n編集：木村祥明\n音樂：上田剛士（AA=）、椿山日南子\n音樂製作：FlyingDog\n音響監督：小泉紀介\n動畫製作：OZ\n題字：蒼喬\n\n","tag2s":[],"tags":[],"title":"食鏽末世錄（僅限港澳台地區）","update_pattern":"每週一更新","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: atRun: 2, complete
debug: balh_enable_in_av  =>  Y
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Microsoft Edge
版本 99.0.1150.46 (正式版本) (64 位)
2. 国家/地区：中国

**Comment by AisukaYuki** [comment]
#949 参考相同问题，自查服务器有效性
