### ISSUE TITLE
兼容性没有问题

### ISSUE THREAD

**Issue by aaronyu-sift** [ipcjs/bilibili-helper#952]
脚本问题：@ipcjs
解除b站区域限制
## 描述
Safari可以通过Tampermonkey运行这个脚本
greasyfork.org的Q&A里写着不支持
- 问题网址：https://greasyfork.org/zh-CN/scripts/25718-解除b站区域限制

## 其他
1. 浏览器版本：Safari Version 15.4 (17613.1.17.1.6)
2. 国家/地区：北美
3. 系统版本：macOS 12.3
4. 机器：m1 Apple Silicon
5. Tampermonkey架构：Apple (非Intel)

**Comment by ipcjs** [comment]
Safari 不支持Windows或者Linux平台，没法测试，所以没有声明“支持”
