### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by Wenroudeyee** [ipcjs/bilibili-helper#953]
脚本问题：@ipcjs

## 描述
今天凌晨一点的时候还是可以正常观看，上午起来之后随便打开一个番剧页就不行了，显示“拉取视频地址失败”。
随后根据提示更换了好几个代理服务器，在点击了账号授权后，显示“存储失败：网络错误。”
![图片](https://user-images.githubusercontent.com/102643263/160758110-f3c6f626-b3ee-490a-8bdd-b3326a31addc.png)
![图片](https://user-images.githubusercontent.com/102643263/160758168-a98ccf09-b2b5-48f7-a3d8-6485d79f3e9c.png)
![图片](https://user-images.githubusercontent.com/102643263/160758262-0a7fe78b-9b93-44a7-9ae5-1b3429517228.png)

- 问题网址：
https://www.bilibili.com/bangumi/play/ss39462/?from=search&seid=417037727205733670&spm_id_from=333.337.0.0

## 日志

[1.txt](https://github.com/ipcjs/bilibili-helper/files/8377329/1.txt)

</details>

## 其他

1. 浏览器版本：火狐
2. 国家/地区：大陆

**Comment by Wenroudeyee** [comment]
问题网址那我只是随便找了一个番剧页，进行服务器更换

**Comment by AisukaYuki** [comment]
~~哪个服务器，日志正常获取到播放链了，看不出有什么问题。~~
在出问题的页面保存日志，你这发了个国王排名的正常日志上来，没任何参考价值。

如果是标有A站的后渲染页面，没有星球按钮设置框
F12控制台，刷新页面在控制台输入window.bangumi_area_limit_hack.showSettings(); 会打开设置框

**Comment by Wenroudeyee** [comment]
不好意思....
[1.txt](https://github.com/ipcjs/bilibili-helper/files/8378825/1.txt)
不过他视频页面直接写的是null

**Comment by AisukaYuki** [comment]
盲猜 biliplus 崩了

**Comment by AisukaYuki** [comment]
你的解析服务器怎么填的，我没看到有解析服务器的请求

**Comment by Wenroudeyee** [comment]
![图片](https://user-images.githubusercontent.com/102643263/160794404-16593577-ff26-40d0-a396-47037b797ee7.png)
可能是因为账号授权的时候就已经失败了

**Comment by AisukaYuki** [comment]
没事了BV跳转失败，plus的接口问题。现在只能从ss和md才能正常进去页面。~~（叔叔对海外番剧动了手脚。~~
#948 #919 
试试从索引跳转试试 https://bangumi.jasonkhew96.eu.org/bilibili/

**Comment by Wenroudeyee** [comment]
kuso 鼠鼠是真可恶啊。问题解决了，谢谢你！
