### ISSUE TITLE
无法切换视频编码方式

### ISSUE THREAD

**Issue by Gemhana** [ipcjs/bilibili-helper#955]
脚本问题：@ipcjs

## 描述

启用脚本后视频编码方式被锁定为avc，无法启用av1和hevc，本来这并不算一个问题，但最近B站大大降低了avc编码的码率，导致视频模糊.
![image](https://user-images.githubusercontent.com/102907304/161430433-301b3119-d07b-4381-a67d-0eab7f4504b8.png)

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>
```


```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by JasonKhew96** [comment]
后端暂时没考虑这个问题（

**Comment by JasonKhew96** [comment]
经过调查，解析服务器好像支持，最后看你的浏览器支不支持

**Comment by Gemhana** [comment]
测试过edge 99和chrome 100，挂梯可正常切换，使用脚本则无法切换，edge 100有点问题，任何情况都不能切换

**Comment by misaka20002** [comment]
我去对比了一下，还真的是，avc本来压缩率就比av1低，结果码率还比av1低，画质糊的明显，如图：
![屏幕截图(150)](https://user-images.githubusercontent.com/40714502/162263170-df0fd319-932b-4437-91a5-58b926994843.png)
![屏幕截图(151)](https://user-images.githubusercontent.com/40714502/162263201-8d32cf3a-cc3b-43d7-995d-a80da6d66556.png)

**Comment by ipcjs** [comment]
叔叔有毒吧，avc带会员还不到1500Kbps的码率🙃

**Comment by JasonKhew96** [comment]
> 叔叔有毒吧，avc带会员还不到1500Kbps的码率🙃

新番 开播 半小时（大概？） 后 自动二压

**Comment by misaka20002** [comment]
不會拿捏距離的阿波連同學（僅限港澳台地區）的最近几集只有1000Kbps的码率了

**Comment by misaka20002** [comment]
![image](https://user-images.githubusercontent.com/40714502/166098668-ef854883-56c0-4693-b939-a8200f4ad6dd.png)
[不會拿捏距離的阿波連同學（僅限港澳台地區）最近几集只有1000Kbps的码率了

**Comment by Howard20181** [comment]
脚本重建的页面的播放器版本是2.49.2，仅支持HEVC和AVC编码
![image](https://user-images.githubusercontent.com/40033067/167836724-839f195c-36a9-4d33-8fe7-c761277294cb.png)

**Comment by Howard20181** [comment]
> 脚本重建的页面的播放器版本是2.49.2，仅支持HEVC和AVC编码 
> ![image](https://user-images.githubusercontent.com/40033067/167836724-839f195c-36a9-4d33-8fe7-c761277294cb.png)

临时解决办法
将https://s1.hdslb.com/bfs/static/player/main/core.*.js 请求重定向到https://s1.hdslb.com/bfs/static/player/main/core.js
将https://s1.hdslb.com/bfs/static/player/main/video.*.js 请求重定向到https://s1.hdslb.com/bfs/static/player/main/video.js
成功使用新版播放器
![image](https://user-images.githubusercontent.com/40033067/168241579-ffd78533-c830-4c90-bf04-6bb44ebe564d.png)
![image](https://user-images.githubusercontent.com/40033067/168241659-3c5f8a00-ebf2-4597-9937-89ab83fbbf7f.png)
![image](https://user-images.githubusercontent.com/40033067/168241714-98b35567-e2ae-40d8-8481-d77f14abd35d.png)

**Comment by misaka20002** [comment]
> 

能给个教程吗

**Comment by misaka20002** [comment]
> > 脚本重建的页面的播放器版本是2.49.2，仅支持HEVC和AVC编码
> > ![image](https://user-images.githubusercontent.com/40033067/167836724-839f195c-36a9-4d33-8fe7-c761277294cb.png)
> 
> 临时解决办法 将https://s1.hdslb.com/bfs/static/player/main/core.*.js 请求重定向到https://s1.hdslb.com/bfs/static/player/main/core.js 将https://s1.hdslb.com/bfs/static/player/main/video.*.js 请求重定向到https://s1.hdslb.com/bfs/static/player/main/video.js 成功使用新版播放器 ![image](https://user-images.githubusercontent.com/40033067/168241579-ffd78533-c830-4c90-bf04-6bb44ebe564d.png) ![image](https://user-images.githubusercontent.com/40033067/168241659-3c5f8a00-ebf2-4597-9937-89ab83fbbf7f.png) ![image](https://user-images.githubusercontent.com/40033067/168241714-98b35567-e2ae-40d8-8481-d77f14abd35d.png)

能给个教程吗

**Comment by aria001** [comment]
安装一个可以重定向请求的浏览器插件，再按照楼上的方法添加规则就好了，我在Edge上使用的是[Goorepacer](https://microsoftedge.microsoft.com/addons/detail/cidbonnpjopamnhfjdgfcmjmlmehjnej)

**Comment by misaka20002** [comment]
> 安装一个可以重定向请求的浏览器插件，再按照楼上的方法添加规则就好了，我在Edge上使用的是[Goorepacer](https://microsoftedge.microsoft.com/addons/detail/cidbonnpjopamnhfjdgfcmjmlmehjnej)

感谢，已经用上了，清晰了2倍

**Comment by JasonKhew96** [comment]
其实改这里就可以了，但是不知道有没有 bug

https://github.com/ipcjs/bilibili-helper/blob/228a642fae4ab5404828c8be0118e96380849e1d/packages/unblock-area-limit/src/feature/bili/bangumi-play-page-template.html#L43
