### ISSUE TITLE
## 拉取视频地址失败

### ISSUE THREAD

**Issue by paracetamol-raz** [ipcjs/bilibili-helper#957]
脚本问题：@ipcjs

## 描述
 跟着阿里云函数的教程做了自己的函数 添加了http触发器 放到脚本的每个列表里 但是一直“非常抱歉”

- 问题网址：https://www.bilibili.com/bangumi/play/ep478665

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep478665
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: bos flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://b-b-vvsvylrfcx.cn-hangzhou.fcapp.run/pgc/player/web/playurl?avid=810484298&cid=569742427&qn=116&fnver=0&fnval=4048&fourk=1&ep_id=478665&session=b8d3d4487ec6f5e86662cd733018dc4d&module=bangumi&area=&access_key={{access_key}}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: /x/web-interface/nav {"uname":"复方对乙酰氨基酚-Raz","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"复方对乙酰氨基酚-Raz","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 

## 其他

1. 浏览器版本：Chrome 100.0
2. 国家/地区：jp

**Comment by AisukaYuki** [comment]
area参数为空。填到大陆的框内

**Comment by AisukaYuki** [comment]
502 Bad Gateway 似乎你并没有没有配置正确（
~~自己配置有困难的话，建议公共服务器~~

**Comment by paracetamol-raz** [comment]
> 

就 在阿里的配置就是按照教程一步步来的啊
btw 那五个公共服务器都试了也都不好使 就很怪

**Comment by AisukaYuki** [comment]
> > 
> 
> 就 在阿里的配置就是按照教程一步步来的啊 btw 那五个公共服务器都试了也都不好使 就很怪

脚本的5个没几个活着了，除那五个还有很多，你没仔细看。另外tuturu是我的，全区可用一切正常。你在境外，要看大陆的番剧，必须要在大陆的框框内填上可用的服务器，建议下面四个框都填上。多数公共服务器都需要area参数来区分地区，所以使用公共服务器时首选的框就没有卵用了。

**Comment by paracetamol-raz** [comment]
> > > 
> > 
> > 
> > 就 在阿里的配置就是按照教程一步步来的啊 btw 那五个公共服务器都试了也都不好使 就很怪
> 
> 脚本的5个没几个活着了，除那五个还有很多，你没仔细看。另外tuturu是我的，全区可用一切正常。你在境外，要看大陆的番剧，必须要在大陆的框框内填上可用的服务器，建议下面四个框都填上。多数公共服务器都需要area参数来区分地区，所以使用公共服务器时首选的框就没有卵用了。

哦哦 才发现可以点进去 试了这个tuturu的可以了 感谢
