### ISSUE TITLE
换了好几个服务器拉去地址都会出现小电视，非常抱歉,jpg的那个

### ISSUE THREAD

**Issue by kanadehusband** [ipcjs/bilibili-helper#958]
脚本问题：@ipcjs

## 描述

换了好几个服务器拉去地址都会出现小电视，非常抱歉.jpg的那个
- 问题网址：https://www.bilibili.com/bangumi/media/md28237168/?spm_id_from=333.937.b_6d656469615f6d6f64756c65.2

## 日志
 日志：
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28237168/?spm_id_from=333.937.b_6d656469615f6d6f64756c65.2
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=41459&access_key={{access_key}}
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"立華奏的老公","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /x/web-interface/nav {"uname":"立華奏的老公","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":3,"follow":0,"follow_status":2,"login":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":475899,"last_ep_index":"2","last_time":0},"real_price":"0","sponsor":0,"vip_info":{"due_date":1662652800000,"status":1,"type":2}}}
debug: setAreaLimitSeason 000 true
debug: atRun: 2, complete
debug: season41459 {"code":0,"message":"success","result":{"actor":[{"actor":"置鯰龍太郎 / 諏訪部順一 / 小西克幸（三國志大戰）","actor_id":0,"role":"諸葛孔明"},{"actor":"本渡楓(歌唱","actor_id":0,"role":"月見英子"},{"actor":"千葉翔也","actor_id":0,"role":"KABE太人"},{"actor":"山村響(歌唱","actor_id":0,"role":"久遠七海"},{"actor":"福島潤","actor_id":0,"role":"OWNER小林"}],"alias":"パリピ孔明,パリピ孔明","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"6024","bangumi_title":"派對咖孔明（僅限港澳台地區）","brief":"「丞相，穿越了！？」\n三國時代的孔明在五丈原抱憾離世，\n如今他恢復成年輕時的模樣，以一身古時打扮來到...","business_type":1,"coins":"0","copyright":"dujia","cover":"https://i0.hdslb.com/bfs/bangumi/image/f2f5e0118d338a57420b599780dd5c54d1470ec1.jpg","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"298172262","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/afb2806cdcee0f88e99369a73fcd80ed267527df.png","danmaku":"575543732","episode_id":"475900","episode_status":13,"episode_type":0,"from":"bangumi","index":"3","index_title":"孔明 看清前進之路","is_new":"1","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-14 22:00:01.0"},{"av_id":"937924663","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f5e5f123aef7399156a6fe74d4cb7aaf97604a20.png","danmaku":"569612278","episode_id":"475899","episode_status":13,"episode_type":0,"from":"bangumi","index":"2","index_title":"孔明 施展計謀","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-04-07 22:00:00.0"},{"av_id":"640203054","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/5c41229094037cb43d053c772555fd9aa698bb58.png","danmaku":"569910677","episode_id":"475898","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"孔明 降臨於澀谷","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-03-31 22:00:01.0"},{"av_id":"725195846","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/347232ebd106426a25cee87a253d97cb6bc70d35.jpg","danmaku":"562852278","episode_id":"477513","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV","index_title":"","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2022-03-30 20:00:00.0"}],"evaluate":"「丞相，穿越了！？」\n三國時代的孔明在五丈原抱憾離世，\n如今他恢復成年輕時的模樣，以一身古時打扮來到現代日本涉谷。\n突兀的裝扮讓人以為他在Cosplay，\n後來被人帶往夜店狂歡，\n\n孔明在那裡認識了一心想成為歌手的月見英子。\n聽了她的歌聲大為感動，於是自告奮勇擔任她的軍師！\n來到現代，孔明要如何發揮他的軍事長才來協助英子完成「霸業」呢…？\n","favorites":"0","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"パリピ孔明","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/f2f5e0118d338a57420b599780dd5c54d1470ec1.jpg","episode_index":{"index_show":"连载中, 每週四更新"},"media_id":28237168,"publish":{"is_finish":0,"is_started":1},"title":"派對咖孔明（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"475900","newest_ep_index":"3","origin_name":"パリピ孔明","payment":{"price":"0","promotion":"","tip":"大会员专享观看特权哦~","vip_promotion":"成為大會員搶先看"},"play_count":"0","pub_string":"","pub_time":"2022-03-31 22:00:00","pub_time_show":"3月31日 22:00 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"41459","season_status":13,"season_title":"TV","seasons":[{"bangumi_id":"6024","cover":"https://i0.hdslb.com/bfs/bangumi/image/f2f5e0118d338a57420b599780dd5c54d1470ec1.jpg","is_finish":"0","is_new":"1","newest_ep_id":"475900","newest_ep_index":"3","season_id":"41459","season_status":13,"title":"TV"}],"share_url":"http://bangumi.bilibili.com/anime/41459/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/fcc270cd407ee4c831fb8b647982715a1fc11e60.png","staff":"監督：本間修\n系列構成：米內山陽子\n角色設計：關口可奈味\n道具設定：宮岡真弓、牧野博美\n美術監督：東潤一\n美術設定：藤井祐太\n色彩設計：江口亞紗美\n3D監督：市川元成\n攝影監督：富田喜允\n編集：高橋步\n特殊效果：村上正博\n音響監督：飯田裡樹\n音樂：彥田元氣（Hifumi,inc.）\n音樂製作：Avex Pictures\n動畫製作：P.A.WORK\n製作：《派對孔明》製作委員會\n\n","tag2s":[],"tags":[],"title":"派對咖孔明（僅限港澳台地區）","update_pattern":"每週四更新","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：EDGE100.0.1185.39 (正式版本)  最新版本
2. 国家/地区：大陆
3.

**Comment by JasonKhew96** [comment]
哪家解析服务器？
麻烦提供播放页面时的日志

**Comment by kanadehusband** [comment]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep475900?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"立華奏的老公","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=475900
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: setAreaLimitSeason ep475900 true
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?cid=575543732&qn=112&type=&otype=json&fourk=1&bvid=BV1HF411g7NW&ep_id=475900&fnver=0&fnval=80&session=02486f1231acf2a5d1681f0fb297a98e&module=bangumi&area=hk&access_key={{access_key}}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=undefined&cid=575543732&bvid=BV1HF411g7NW&qn=112&type=&otype=json&ep_id=475900&fourk=1&fnver=0&fnval=80&session=99fe6e16196a00ec630620529af40e72&module=bangumi&balh_ajax=1&area=hk&access_key=e49f336a622719995285758075d6d641
debug: /x/web-interface/nav {"uname":"立華奏的老公","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39

**Comment by kanadehusband** [comment]
![image](https://user-images.githubusercontent.com/47624644/163671044-6aff6235-a756-44a5-8d18-81c31b14c897.png)
这几个代理服务器

**Comment by kanadehusband** [comment]
问题网址 https://www.bilibili.com/bangumi/play/ep475900?from_spmid=666.19.0.0

**Comment by JasonKhew96** [comment]
> 问题网址 https://www.bilibili.com/bangumi/play/ep475900?from_spmid=666.19.0.0

@kanadehusband `{"code":1,"message":"代理服务器已转移至域名https://repost.98e.org"}`

**Comment by kanadehusband** [comment]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep475898?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=475898
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"立華奏的老公","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?cid=569910677&qn=112&type=&otype=json&fourk=1&bvid=BV1BY4y1p7S7&ep_id=475898&fnver=0&fnval=80&session=a25bcbe244d226a40772f60e80252d5c&module=bangumi&area=hk&access_key={{access_key}}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili-proxy.98e.org/pgc/player/web/playurl?avid=undefined&cid=569910677&bvid=BV1BY4y1p7S7&qn=112&type=&otype=json&ep_id=475898&fourk=1&fnver=0&fnval=80&session=527b34c1146f6135c23e4d31cdf6da28&module=bangumi&balh_ajax=1&area=hk&access_key=1ffd74ed1dd1ec8f6b5aa94d8fd65941
debug: /x/web-interface/nav {"uname":"立華奏的老公","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39
更换了服务器地址还是不行
