### ISSUE TITLE
请问有番剧搜索功能吗

### ISSUE THREAD

**Issue by HonkaiHanabi** [ipcjs/bilibili-helper#959]
限定港澳台番剧播放界面脚本显示已启用，播放没有问题。
但搜索界面search.bilibili.com没有脚本被启用，无法搜索番剧，请问是没有这个功能吗？还是设置有误?
望解答。

**Comment by JasonKhew96** [comment]
这个脚本不支持

请移步: https://github.com/gamekingv/bilibili-oversea-search/blob/main/bilibili-oversea-search_new.user.js
点击右上 `Raw` 安装

**Comment by HonkaiHanabi** [comment]
好的，感谢
