### ISSUE TITLE
服务器炸了？还是我脚本出错？

### ISSUE THREAD

**Issue by 2ez4rtzEE** [ipcjs/bilibili-helper#96]
## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by 2ez4rtzEE** [comment]
![image](https://user-images.githubusercontent.com/36111117/35769902-515d3edc-094d-11e8-8b11-b5ce57ab0499.png)

**Comment by 2ez4rtzEE** [comment]
log: [解除B站区域限制 v6.4.9 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep183802
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: replace blocked_vip:  server: https://biliplus.ipcjs.win flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"花咲つぼみSKL","isLogin":true,"level":5,"vipType":1,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":183802,"last_ep_index":"4","last_time":-1}}}
log: {"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz-dx-v-10.acgvideo.com/vg1/upgcxcode/43/69/8986943/8986943-1-16.mp4?expires=1517687100&platform=ios&ssig=D04I58K0oDW6Ov7myKlcmQ&oi=3078818617&nfa=QY4gbJYKJs7cixEssSU8nA==&dynamic=1&hfa=2017907842&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM="}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: error {"0":{"readyState":0,"responseText":"","status":0,"statusText":"error"},"1":"error","2":""} {"url":"https://biliplus.ipcjs.win/BPplayurl.php?cid=31144490|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=112&module=bangumi&season_type=1&qn=112&sign=2aff30cceabd1b473523122f2e312190","isLocal":false,"global":true,"type":"GET","contentType":"application/x-www-form-urlencoded; charset=UTF-8","processData":true,"async":true,"accepts":{"xml":"application/xml, text/xml","html":"text/html","text":"text/plain","json":"application/json, text/javascript","*":"*/*","script":"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},"contents":{"xml":{},"html":{},"json":{},"script":{}},"responseFields":{"xml":"responseXML","text":"responseText"},"converters":{"text html":true},"flatOptions":{"context":true,"url":true},"jsonp":"callback","xhrFields":{"withCredentials":true},"dataTypes":["text"],"crossDomain":true,"hasContent":false}
log: {"accept_format":"mp4","accept_quality":[16],"bp":0,"code":0,"durl":[{"length":15126,"order":1,"size":124627,"url":"http://cn-zjwz3-dx-v-05.acgvideo.com/vg3/e/4d/8986943-1.mp4?expires=1517687100&platform=ios&ssig=wX1RMDPQM-KsNBquiuej3Q&oi=3078818617&nfa=QY4gbJYKJs7cixEssSU8nA==&dynamic=1&hfa=2017907853&hfb=ZWI2ODUxMTI1YmRhNTcxZjcwNTFjMTUwOTdkZTc0ZDM="}],"format":"mp4","from":"local","has_paid":false,"quality":16,"result":"suee","seek_param":"start","seek_type":"second","timelength":15126}
log: error {"0":{"readyState":0,"responseText":"","status":0,"statusText":"error"},"1":"error","2":""} {"url":"https://biliplus.ipcjs.win/BPplayurl.php?cid=31144490|bangumi&appkey=84956560bc028eb7&otype=json&type=&quality=16&module=bangumi&season_type=1&qn=16&sign=512a852e358e82454b8398342d0138bd","isLocal":false,"global":true,"type":"GET","contentType":"application/x-www-form-urlencoded; charset=UTF-8","processData":true,"async":true,"accepts":{"xml":"application/xml, text/xml","html":"text/html","text":"text/plain","json":"application/json, text/javascript","*":"*/*","script":"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},"contents":{"xml":{},"html":{},"json":{},"script":{}},"responseFields":{"xml":"responseXML","text":"responseText"},"converters":{"text html":true},"flatOptions":{"context":true,"url":true},"jsonp":"callback","xhrFields":{"withCredentials":true},"dataTypes":["text"],"crossDomain":true,"hasContent":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by w-kun** [comment]
ep183802 国家队第四集
+1

**Comment by 986547004** [comment]
+1

**Comment by ipcjs** [comment]
#100
