### ISSUE TITLE
港澳台播放只有6min

### ISSUE THREAD

**Issue by amlkiller** [ipcjs/bilibili-helper#960]
## 描述
和bilirowing一样的6min限制
网站不知道如何处理
- 问题网址：https://www.bilibili.com/bangumi/play/ep475899

## 其他

1. 浏览器版本：chrome102
2. 国家/地区：China

**Comment by amlkiller** [comment]
已经尝试换服务器和其他方法。

**Comment by JasonKhew96** [comment]
有没有 可能，你没有 大会员

**Comment by amlkiller** [comment]
> 有没有可能，你没有大会员

港澳台就是不要会员啊，6分钟过后客户端会抛出地域限制，最近bilirowing才解决的问题。

**Comment by JasonKhew96** [comment]
谁说的，部分 独家 番 要 大会员 的，最近的 都 第一集 免费 而已，孔明 就是 其中一部

**Comment by david082321** [comment]
@amlkiller 独家的要大会员 
> 有没有可能，你没有大会员

![Screenshot_20220415-225930](https://user-images.githubusercontent.com/7046617/163586759-ef8069c6-d201-4875-bce6-ec7bd223c43b.png)

**Comment by amlkiller** [comment]
> 

刚发现的我是用小号，大号大会员，以为是碰上bilirowing碰上地域限制了。sorry，closed。
