### ISSUE TITLE
无法观看仅限台湾的番剧，也访问不了番剧出差空间，并且也不能使用字幕繁化简功能

### ISSUE THREAD

**Issue by excalibur502** [ipcjs/bilibili-helper#961]
脚本问题：@ipcjs

## 描述

两台电脑在同网络环境用同版本浏览器，插件设置也一样，都是win10，就只有版本稍有差别，一个20H2一个21H2，公共解析服务器也是用的一样的，前8个解析服务器都有尝试，效果都是一样的，就是其中一台电脑无法观看仅限台湾的番剧，也访问不了番剧出差空间，并且也不能使用字幕繁化简功能，另一台电脑则完全可以访问这边不能访问的所有界面也能开启字幕繁化简，不知道怎么才能让不能访问的那台访问到
![image](https://user-images.githubusercontent.com/52108075/163593099-f678249f-b783-4eb5-984c-14fe43045310.jpg)
![image](https://user-images.githubusercontent.com/52108075/163593115-6a096550-0de9-4784-8f36-6ae92d33314f.jpg)
![image](https://user-images.githubusercontent.com/52108075/163593193-d41b65ce-3404-4fe4-9775-41df04a4539f.png)
![image](https://user-images.githubusercontent.com/52108075/163593253-d2b3e269-84a5-444c-a728-41964fb24f0c.png)

- 问题网址：
https://www.bilibili.com/bangumi/play/ep96703

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep96703
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.39
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：版本 100.0.1185.39 (正式版本) (64 位)
2. 国家/地区：中国大陆

**Comment by excalibur502** [comment]
edge 100.0.1185.39 (正式版本) (64 位) 和 谷歌 98.0.4758.102（正式版本） （64 位）两个浏览器都试过，能看的那台都能看，不能看的那台都不能看

**Comment by excalibur502** [comment]
经过排除其他插件干扰，只保留解除区域限制，对其他插件逐个开启对比发现，是在同时开启本插件和Bilibili-Evolved插件时会出现部分番剧无法观看、无法访问番剧出差空间以及不能使用字幕繁化简等功能，但是奇怪的是，另一台电脑上也同时安装有这两个插件且配置基本一样，但却可以访问，而无法访问的这边经测试发现多次刷新有一定概率能正常进入无法观看的页面和番剧出差的空间，不清楚到底是什么原因导致的

**Comment by TomShen-shyir** [comment]
请问一下这个插件是哪里下载的

**Comment by excalibur502** [comment]
> 请问一下这个插件是哪里下载的

https://github.com/the1812/Bilibili-Evolved
