### ISSUE TITLE
輝夜姬想讓人告白 提示我所在地区不可观看

### ISSUE THREAD

**Issue by G535681092** [ipcjs/bilibili-helper#963]
脚本问题：@ipcjs

## 描述

其他新番番剧的都可以顺利观看，但唯独辉夜大小姐始终提示我，原因: {"code":-10403,"message":"抱歉您所在地区不可观看！"} 
- 问题网址：
https://www.bilibili.com/bangumi/play/ep476243?from_spmid=666.19.0.0

## 日志

<details>
<summary>Verbose 日志</summary>
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep476243?from_spmid=666.19.0.0
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: false isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=476243
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"樱色二重火","isLogin":true,"level":6,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?cid=576395095&qn=0&type=&otype=json&fourk=1&bvid=BV1Tr4y1H7Jd&ep_id=476243&fnver=0&fnval=80&session=792f13b6d5aa9d4e85003ff6ffff30eb&module=bangumi&area=tw
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: atRun: 2, complete
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?cid=576395095&qn=0&type=&otype=json&fourk=1&bvid=BV1Tr4y1H7Jd&ep_id=476243&fnver=0&fnval=80&session=792f13b6d5aa9d4e85003ff6ffff30eb&module=bangumi&area=
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?cid=576395095&qn=0&type=&otype=json&fourk=1&bvid=BV1Tr4y1H7Jd&ep_id=476243&fnver=0&fnval=80&session=792f13b6d5aa9d4e85003ff6ffff30eb&module=bangumi&area=hk
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?cid=576395095&qn=0&type=&otype=json&fourk=1&bvid=BV1Tr4y1H7Jd&ep_id=476243&fnver=0&fnval=80&session=792f13b6d5aa9d4e85003ff6ffff30eb&module=bangumi
debug: __playinfo__ set
debug: /x/web-interface/nav {"uname":"樱色二重火","isLogin":true,"level":6,"vipType":1,"vipStatus":1,"isFromReport":false}
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid={{access_key}}&cid=576395095&bvid=BV1Tr4y1H7Jd&qn=0&type=&otype=json&ep_id=476243&fourk=1&fnver=0&fnval=80&session=52c0d7ff785eac6c2f521f202c5baebb&module=bangumi&balh_ajax=1&area=tw
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=undefined&cid=576395095&bvid=BV1Tr4y1H7Jd&qn=0&type=&otype=json&ep_id=476243&fourk=1&fnver=0&fnval=80&session=52c0d7ff785eac6c2f521f202c5baebb&module=bangumi&balh_ajax=1&area=
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://repost.98e.org/pgc/player/web/playurl?avid=undefined&cid=576395095&bvid=BV1Tr4y1H7Jd&qn=0&type=&otype=json&ep_id=476243&fourk=1&fnver=0&fnval=80&session=52c0d7ff785eac6c2f521f202c5baebb&module=bangumi&balh_ajax=1&area=hk
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=576395095&bvid=BV1Tr4y1H7Jd&qn=0&type=&otype=json&ep_id=476243&fourk=1&fnver=0&fnval=80&session=52c0d7ff785eac6c2f521f202c5baebb&module=bangumi&balh_ajax=1
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Google Chrome版本 99.0.4844.51（正式版本） （64 位）
2. 国家/地区：中国大陆

**Comment by JasonKhew96** [comment]
@G535681092 这部 番剧 仅限 台湾，你 填的 解析服务器 不支持 台湾
