### ISSUE TITLE
解锁番剧后BiliBili  Evolved不可用 

### ISSUE THREAD

**Issue by TicoTock** [ipcjs/bilibili-helper#964]
脚本问题：@ipcjs

## 描述

就是解锁番剧后BiliBili  Evolved的侧栏打不开
我想下载视频来着
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：Cent Browser 版本 4.3.9.248（正式版本） （32 位） 
2. 国家/地区：CN

**Comment by TicoTock** [comment]
问题网址： https://www.bilibili.com/bangumi/play/ep480346

**Comment by JasonKhew96** [comment]
预期行为，重建页面的问题，无能为力

**Comment by TicoTock** [comment]
> 预期行为，重建页面的问题，无能为力

好的，非常感谢
