### ISSUE TITLE
设置好了无法使用，已尝试多个服务器

### ISSUE THREAD

**Issue by anyeer** [ipcjs/bilibili-helper#966]
<img width="641" alt="屏幕截图 2022-04-24 105917" src="https://user-images.githubusercontent.com/104288488/164955515-426a0b44-8dd6-4852-974c-b3cb9af67dba.png">
<img width="818" alt="屏幕截图 2022-04-24 110006" src="https://user-images.githubusercontent.com/104288488/164955572-96e426ec-a951-4269-8ec1-6105d5af2226.png">

- 问题网址：
设置好了无法使用，已尝试多个服务器

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss2680?from_spmid=666.4.0.0
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: ks3 flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50
<details>
<summary>Verbose 日志</summary>

```

</details>

**Comment by anyeer** [comment]
问题网址：https://www.bilibili.com/bangumi/play/ss41477?from_spmid=666.4.0.0

**Comment by JasonKhew96** [comment]
首选服务器随便填上一个域名就可以了

**Comment by anyeer** [comment]
> 首选服务器随便填上一个域
谢谢，问题解决了，没注意哈哈
