### ISSUE TITLE
Re：从零开始的异世界生活 新编集版 不可观看

### ISSUE THREAD

**Issue by gwwydsb** [ipcjs/bilibili-helper#967]
脚本问题：@ipcjs

## 描述

如图
![image](https://user-images.githubusercontent.com/98566957/165979881-6813606a-1c9d-4b2b-8745-ed4b9c36cb43.png)
![image](https://user-images.githubusercontent.com/98566957/165979938-e34b6279-bbdb-4d82-a215-6216ed90f676.png)

- 问题网址：https://www.bilibili.com/bangumi/play/ep362492

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28229293/?spm_id_from=666.25.b_6d656469615f6d6f64756c65.2
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=33860&access_key={{access_key}}
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"不背完cfop不改名","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"follow_status":2,"login":1,"pay":0,"pay_pack_paid":0,"real_price":"0","sponsor":0,"vip_info":{"due_date":1680364800000,"status":1,"type":2}}}
debug: setAreaLimitSeason 000 false
debug: season33860 {"code":0,"message":"success","result":{"actor":[{"actor":"小林裕介","actor_id":0,"role":"菜月昴"},{"actor":"高橋李依","actor_id":0,"role":"艾米莉婭"},{"actor":"內山夕實","actor_id":0,"role":"帕克"},{"actor":"能登麻美子","actor_id":0,"role":"艾爾莎·葛蘭希爾黛"},{"actor":"村川梨衣","actor_id":0,"role":"拉姆"},{"actor":"水瀨祈","actor_id":0,"role":"蕾姆"},{"actor":"新井裏美","actor_id":0,"role":"碧翠絲"},{"actor":"子安武人","actor_id":0,"role":"羅茲瓦爾·L·梅劄斯"},{"actor":"高野麻裏佳","actor_id":0,"role":"佩特拉·雷蒂"}],"alias":"Re:ゼロから始める異世界生活　2期","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"5033","bangumi_title":"Re:從零開始的異世界生活（僅限港澳台等地區）","brief":"我壹定會拯救妳。\n在打倒了魔女教大罪司教「怠惰」擔當——培提其烏斯·羅曼尼康帝之後，菜月昴和愛蜜莉雅...","business_type":1,"coins":"0","copyright":"bilibili","cover":"https://i0.hdslb.com/bfs/bangumi/image/fcc3d8562115f5a22e6d5f2c5ef688fb394df59d.png","danmaku_count":"6672","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"969825240","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/2bf681dcfa8c4422bb831795091ba06a010cc71f.jpg","danmaku":"240539163","episode_id":"338300","episode_status":2,"episode_type":0,"from":"bangumi","index":"13","index_title":"泫然欲泣的聲音","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-09-30 23:00:01.0"},{"av_id":"414699321","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e8c0b02ea40fd6edd8fc8c656bd4476ee7db8fc2.jpg","danmaku":"238263274","episode_id":"330821","episode_status":2,"episode_type":0,"from":"bangumi","index":"12","index_title":"魔女們的茶會","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-09-23 23:00:01.0"},{"av_id":"414546595","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/b3f68ca2a529a4fda47a1464fa3688ee9f2abd3d.jpg","danmaku":"235916885","episode_id":"330820","episode_status":2,"episode_type":0,"from":"bangumi","index":"11","index_title":"死亡的味道","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-09-16 23:00:01.0"},{"av_id":"584605402","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/3135555d96ab078416581f73ffb9012d20ce0195.jpg","danmaku":"233729633","episode_id":"330819","episode_status":2,"episode_type":0,"from":"bangumi","index":"10","index_title":"地獄的話我已經體驗過了","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-09-09 23:00:01.0"},{"av_id":"371935264","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f1a533253aeb2e696f62e0a6ffa1bd2864c8156d.jpg","danmaku":"231564256","episode_id":"330818","episode_status":2,"episode_type":0,"from":"bangumi","index":"9","index_title":"愛愛愛愛愛愛你","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-09-02 23:00:01.0"},{"av_id":"926915812","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/a2c2ae48aebb315fe5e2dc03e32404f5afb66a61.jpg","danmaku":"229112040","episode_id":"330817","episode_status":2,"episode_type":0,"from":"bangumi","index":"8","index_title":"生命的價值","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-08-26 23:00:01.0"},{"av_id":"669317052","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/0b5988db9de403e169b62ddafd4587d86c136df8.jpg","danmaku":"226309958","episode_id":"330816","episode_status":2,"episode_type":0,"from":"bangumi","index":"7","index_title":"友人","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-08-19 23:00:01.0"},{"av_id":"201696511","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/2e295e06b115f5372383518d8cd747716d869046.jpg","danmaku":"223584455","episode_id":"330815","episode_status":2,"episode_type":0,"from":"bangumi","index":"6","index_title":"少女的福音","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-08-12 23:00:01.0"},{"av_id":"499113160","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/3091e7a4dfbd25c809ee9afd16a935dbb587dc1a.jpg","danmaku":"220784257","episode_id":"330814","episode_status":2,"episode_type":0,"from":"bangumi","index":"5","index_title":"踏出的一步","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-08-05 23:00:01.0"},{"av_id":"626555778","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f3f3a33758efb710b084af6af22bc868ff9d4bc1.jpg","danmaku":"218035550","episode_id":"330813","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"親子","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-07-29 23:00:01.0"},{"av_id":"838948195","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/8b7857c87a703847bd6bde84284d70af63bf2ef1.jpg","danmaku":"215391481","episode_id":"330812","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"等待許久的再會","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-07-22 23:00:01.0"},{"av_id":"456368295","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/72bbedd9e16095efc48ba8301e1a781634867d29.jpg","danmaku":"212747253","episode_id":"330811","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"下一個地方","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-07-15 23:00:01.0"},{"av_id":"583770876","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f8ebe74891f4c04a27ff2c65eaedd4953b268eb0.jpg","danmaku":"210224041","episode_id":"330810","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"各自的誓言","is_webplay":"0","mid":"11783021","page":"1","premiere":false,"up":{},"update_time":"2020-07-08 23:00:01.0"}],"evaluate":"我壹定會拯救妳。\n在打倒了魔女教大罪司教「怠惰」擔當——培提其烏斯·羅曼尼康帝之後，菜月昴和愛蜜莉雅又得以重新開始。\n克服了艱難的訣別，兩人終於和解，然而這只是新壹輪風波的序幕。\n超乎想象的絕境危機，接踵而至的殘酷現實。\n少年將再次直面殘酷的命運。","favorites":"0","has_unfollow":0,"is_finish":"1","is_guide_follow":1,"jp_title":"Re:ゼロから始める異世界生活　2期","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/fcc3d8562115f5a22e6d5f2c5ef688fb394df59d.png","episode_index":{"index_show":"已完结, 全13话"},"media_id":28229293,"publish":{"is_finish":1,"is_started":1},"rating":{"count":998,"score":9.4},"title":"Re：從零開始的異世界生活 第二季（僅限港澳台地區）","type_id":1,"type_name":"动画"},"newest_ep_id":"338300","newest_ep_index":"13","origin_name":"Re:ゼロから始める異世界生活　2期","play_count":"466550","pub_string":"","pub_time":"2020-07-08 23:00:00","pub_time_show":"7月8日 23:00 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"33860","season_status":2,"season_title":"前半","seasons":[{"bangumi_id":"5033","cover":"https://i0.hdslb.com/bfs/bangumi/image/fcc3d8562115f5a22e6d5f2c5ef688fb394df59d.png","is_finish":"1","newest_ep_id":"338300","newest_ep_index":"13","season_id":"33860","season_status":2,"title":"前半","total_count":"13"},{"bangumi_id":"5033","cover":"https://i0.hdslb.com/bfs/bangumi/image/14d994821f7a6cd4bbfcd025075b003e52b3bbe3.png","is_finish":"1","newest_ep_id":"380500","newest_ep_index":"25","season_id":"37794","season_status":2,"title":"後半","total_count":"12"}],"share_url":"http://bangumi.bilibili.com/anime/33860/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/b3211f93d0d72cc720a6ae88d99e43a7b4f8a139.png","staff":"原作: 長月達平\n導演: 渡邊政治\n音樂: 末廣健壹郎\n人物原案: 大塚真壹郎\n人物設定: 阪井久太\n系列構成: 橫谷昌宏\n美術監督: 高峯義人\n色彩設計: 阪本いづみ\n總作畫監督: 阪井久太\n攝影監督: 峰岸健太郎\n道具設計: 巖畑剛壹、鈴木典孝\n剪輯: 須藤瞳\n音響監督: 明田川仁\n音效: 古谷友二\n音樂制作: KADOKAWA\n動畫制作: WHITE FOX\nCG 導演: 輕部優\n美術設計: 金城沙綾","tag2s":[],"tags":[],"title":"Re：從零開始的異世界生活 第二季（僅限港澳台地區）","total_count":"13","update_pattern":"每周三 23:00更新","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50
debug: balh_server_custom_th  =>  https://bili.baba.plus
debug: balh_server_custom_th  =>  https://bili.baba.plus

## 其他

1. 浏览器版本：edge
2. 国家/地区：泰国/东南亚

**Comment by JasonKhew96** [comment]
@gwwydsb 怪了，换个 解析服务器 好了，他家 解析 (`https://bili.baba.plus`) 怎么了...

**Comment by gwwydsb** [comment]
试了好多服务器都是说加载视频内容失败诶
![image](https://user-images.githubusercontent.com/98566957/166089962-a2bb9e57-01d1-418a-b190-cdc9e94a5cdb.png)

**Comment by JasonKhew96** [comment]
> 试了好多服务器都是说加载视频内容失败诶 ![image](https://user-images.githubusercontent.com/98566957/166089962-a2bb9e57-01d1-418a-b190-cdc9e94a5cdb.png)

@gwwydsb 这个就正常了，见 #906

**Comment by gwwydsb** [comment]
解决了，谢谢！

**Comment by gwwydsb** [comment]
好像还是不行，之前打不开的俩泰区的倒是能打开了，但唯独这番打不开，很奇怪
![image](https://user-images.githubusercontent.com/98566957/166090849-2b7d05c3-87d7-408c-ab37-71b93250d2c4.png)
![image](https://user-images.githubusercontent.com/98566957/166090848-fb16161a-ff02-4b6b-a54c-4c490e96ca9b.png)
![image](https://user-images.githubusercontent.com/98566957/166090850-d4cb0773-0695-4bfe-a8fa-41774232f951.png)
