### ISSUE TITLE
不知道为什么今天突破不了了，每次一突破都是null，在视频正在安装就不行了，重装了脚本也不行

### ISSUE THREAD

**Issue by zqyde2012** [ipcjs/bilibili-helper#97]
log: [解除B站区域限制 v6.4.9 (Greasemonkey.injector)] run on: https://www.bilibili.com/bangumi/play/ep192288
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
log: mode: default blocked_vip:  server: https://www.biliplus.com flv_prefer_ws:  remove_pre_ad:  readyState: loading isLogin: false isLoginBiliBili: true
log: /x/web-interface/nav {"uname":"肥熊一声吼","isLogin":true,"level":5,"vipType":2,"vipStatus":1}
log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":0,"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":192287,"last_ep_index":"1","last_time":1291}}}
log: setAreaLimitSeason ep192288 false
log: {"accept_format":"hdflv2,flv,flv720,flv480,mp4","accept_quality":[112,80,64,32,16],"bp":0,"code":0,"durl":[{"backup_url":["http://cn-sdyt-cu-v-08.acgvideo.com/vg1/upgcxcode/86/79/31167986/31167986-1-80.flv?expires=1517687400&platform=pc&ssig=7g25ZeFyzW6qbbigZlwQNg&oi=3733190575&nfa=ZCnmGjU+wtN0N/FiKfPQuA==&dynamic=1&hfa=2017909272&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://upos-hz-mirrorkodo.acgvideo.com/upgcxcode/86/79/31167986/31167986-1-80.flv?e=ig8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5to8euxZM2rNcNbUVhwdVhoM1hwdVhwdVNCM%3D&platform=pc&uipk=5&uipv=5&deadline=1517687583&gen=playurl&um_deadline=1517687583&rate=500977&um_sign=52808057af60152922b511558018334d&dynamic=1&os=kodo&oi=3733190575&upsig=862d774886e38d5e2bb4d7f1f501ac3e"],"length":363134,"order":1,"size":90960991,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg1/upgcxcode/86/79/31167986/31167986-1-80.flv?expires=1517687400&platform=pc&ssig=7g25ZeFyzW6qbbigZlwQNg&oi=3733190575&nfa=ZCnmGjU+wtN0N/FiKfPQuA==&dynamic=1&hfa=2017909272&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="},{"backup_url":["http://cn-sdyt-cu-v-08.acgvideo.com/vg3/upgcxcode/86/79/31167986/31167986-2-80.flv?expires=1517687400&platform=pc&ssig=GSLuNDsJT4s5rEGwRNHclw&oi=3733190575&nfa=+NZ4hXW31WpZC0Yq5fuLow==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://upos-hz-mirrorkodo.acgvideo.com/upgcxcode/86/79/31167986/31167986-2-80.flv?e=ig8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5to8euxZM2rNcNbUVhwdVhoM1hwdVhwdVNCM%3D&platform=pc&uipk=5&uipv=5&deadline=1517687583&gen=playurl&um_deadline=1517687583&rate=491516&um_sign=69c10892c2c65e0a7fe207dda668d3ab&dynamic=1&os=kodo&oi=3733190575&upsig=ba019b3957a25dda5071bbf844d18ce2"],"length":376896,"order":2,"size":92625391,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg0/upgcxcode/86/79/31167986/31167986-2-80.flv?expires=1517687400&platform=pc&ssig=jALSJP0rPGWTPeLFXg-K6w&oi=3733190575&nfa=+NZ4hXW31WpZC0Yq5fuLow==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="},{"backup_url":["http://cn-sdyt-cu-v-08.acgvideo.com/vg4/upgcxcode/86/79/31167986/31167986-3-80.flv?expires=1517687400&platform=pc&ssig=ViVbHjSmbr4OLDgX03qOag&oi=3733190575&nfa=9q8b/hSbk7eNko+RS1wAcw==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://upos-hz-mirrorkodo.acgvideo.com/upgcxcode/86/79/31167986/31167986-3-80.flv?e=ig8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5to8euxZM2rNcNbUVhwdVhoM1hwdVhwdVNCM%3D&platform=pc&uipk=5&uipv=5&deadline=1517687583&gen=playurl&um_deadline=1517687583&rate=493821&um_sign=8d939bc3185709f3b322e519390d5359&dynamic=1&os=kodo&oi=3733190575&upsig=ea91b25aa53ab23674d717dfb97d55c2"],"length":289685,"order":3,"size":71526383,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg4/upgcxcode/86/79/31167986/31167986-3-80.flv?expires=1517687400&platform=pc&ssig=ViVbHjSmbr4OLDgX03qOag&oi=3733190575&nfa=9q8b/hSbk7eNko+RS1wAcw==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="},{"backup_url":["http://cn-sdyt-cu-v-08.acgvideo.com/vg2/upgcxcode/86/79/31167986/31167986-4-80.flv?expires=1517687400&platform=pc&ssig=JnTOIIektyOSujK0yMHEsQ&oi=3733190575&nfa=XCwu/ov0pLz3F1jvpXwRaA==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://upos-hz-mirrorkodo.acgvideo.com/upgcxcode/86/79/31167986/31167986-4-80.flv?e=ig8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNC8xNEVE9EKE9IMvXBvE2ENvNCImNEVEK9GVqJIwqa80WXIekXRE9IMvXBvEuENvNCImNEVEua6m2jIxux0CkF6s2JZv5x0DQJZY2F8SkXKE9IB5to8euxZM2rNcNbUVhwdVhoM1hwdVhwdVNCM%3D&platform=pc&uipk=5&uipv=5&deadline=1517687583&gen=playurl&um_deadline=1517687583&rate=515720&um_sign=d0a128518fb4754e817397f84ba70d3a&dynamic=1&os=kodo&oi=3733190575&upsig=e0f3ec91f8ea459fa02acfa051edf7f7"],"length":390422,"order":4,"size":100674354,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg2/upgcxcode/86/79/31167986/31167986-4-80.flv?expires=1517687400&platform=pc&ssig=JnTOIIektyOSujK0yMHEsQ&oi=3733190575&nfa=XCwu/ov0pLz3F1jvpXwRaA==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="}],"format":"flv","from":"local","has_paid":false,"quality":80,"result":"suee","seek_param":"start","seek_type":"offset","status":7,"timelength":1420137,"vip_status":1,"vip_type":2}
log: setAreaLimitSeason ep192288 false
log: {"accept_format":"hdflv2,flv,flv720,flv480,mp4","accept_quality":[112,80,64,32,16],"bp":0,"code":0,"durl":[{"backup_url":["http://cn-sxty1-cu.acgvideo.com/vg1/9/65/31167986-1-112.flv?expires=1517687400&platform=pc&ssig=kXD7mBcY077nIsrMgBBSrA&oi=3733190575&nfa=u/HgQv04Oj8rZym8sq+a1Q==&dynamic=1&hfa=2017909338&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://cn-sdyt-cu-v-01.acgvideo.com/vg1/8/84/31167986-1-112.flv?expires=1517687400&platform=pc&ssig=JCFS7Nmdlb6HiDICwnEGZA&oi=3733190575&nfa=u/HgQv04Oj8rZym8sq+a1Q==&dynamic=1&hfa=2017909338&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="],"length":272918,"order":1,"size":204998327,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg1/upgcxcode/86/79/31167986/31167986-1-112.flv?expires=1517687400&platform=pc&ssig=m7KeUQuQaaoFDzU-l898OQ&oi=3733190575&nfa=u/HgQv04Oj8rZym8sq+a1Q==&dynamic=1&hfa=2017909338&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="},{"backup_url":["http://cn-sxty1-cu.acgvideo.com/vg1/9/65/31167986-2-112.flv?expires=1517687400&platform=pc&ssig=7beB6MgMHEHRzMvO7Ya68w&oi=3733190575&nfa=Mks7zf4UdqtPGxh+HwpuAw==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://cn-sdyt-cu-v-01.acgvideo.com/vg1/8/84/31167986-2-112.flv?expires=1517687400&platform=pc&ssig=nOiT06Wy75n3CzY_Z4EH1w&oi=3733190575&nfa=Mks7zf4UdqtPGxh+HwpuAw==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="],"length":466112,"order":2,"size":130446753,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg1/upgcxcode/86/79/31167986/31167986-2-112.flv?expires=1517687400&platform=pc&ssig=-Vrgc7zyCR37pQidw7E8bQ&oi=3733190575&nfa=Mks7zf4UdqtPGxh+HwpuAw==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="},{"backup_url":["http://cn-sxty1-cu.acgvideo.com/vg1/9/65/31167986-3-112.flv?expires=1517687400&platform=pc&ssig=Vu_yFE69vYgWKlJNtfhmbw&oi=3733190575&nfa=3lvtwAw0G8TFadV+DrGDqg==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://cn-sdyt-cu-v-01.acgvideo.com/vg1/8/84/31167986-3-112.flv?expires=1517687400&platform=pc&ssig=JpHlB5x6zn0qFz462Ad7RQ&oi=3733190575&nfa=3lvtwAw0G8TFadV+DrGDqg==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="],"length":340694,"order":3,"size":88315579,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg2/upgcxcode/86/79/31167986/31167986-3-112.flv?expires=1517687400&platform=pc&ssig=Mzrt8mrAn4EQ3JppojlR_w&oi=3733190575&nfa=3lvtwAw0G8TFadV+DrGDqg==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="},{"backup_url":["http://cn-sxty1-cu.acgvideo.com/vg1/9/65/31167986-4-112.flv?expires=1517687400&platform=pc&ssig=x_PuAgMhRT5d3Fh782eMnw&oi=3733190575&nfa=q0oETFckjAWOdyUUDVZgBg==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI=","http://cn-sdyt-cu-v-01.acgvideo.com/vg1/8/84/31167986-4-112.flv?expires=1517687400&platform=pc&ssig=39I56nfd__6xtLkCwo4OgQ&oi=3733190575&nfa=q0oETFckjAWOdyUUDVZgBg==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="],"length":340331,"order":4,"size":175644547,"url":"http://cn-sdqd-cu-v-02.acgvideo.com/vg4/upgcxcode/86/79/31167986/31167986-4-112.flv?expires=1517687400&platform=pc&ssig=tK0H_vYmFKbk9l2Nwx_YVQ&oi=3733190575&nfa=q0oETFckjAWOdyUUDVZgBg==&dynamic=1&hfb=Yjk5ZmZjM2M1YzY4ZjAwYTMzMTIzYmIyNWY4ODJkNWI="}],"format":"hdflv2","from":"local","has_paid":false,"quality":112,"result":"suee","seek_param":"start","seek_type":"offset","status":7,"timelength":1420055,"vip_status":1,"vip_type":2}
log: setAreaLimitSeason ep192288 false
debug: userAgent Mozilla/5.0 (Windows NT 6.1; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
```

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by ipcjs** [comment]
#100
