### ISSUE TITLE
添加的公共代理服务器都不可用

### ISSUE THREAD

**Issue by saintnoven** [ipcjs/bilibili-helper#973]
![屏幕截图 2022-05-07 105537](https://user-images.githubusercontent.com/83714084/167235514-f2d71577-b314-466b-b829-e55ad642958f.jpg)

**Comment by JasonKhew96** [comment]
没日志，没说用的哪个解析服务器，算命都算不出

**Comment by saintnoven** [comment]
> 没日志，没说用的哪个解析服务器，算命都算不出

小问题大佬已经解决了

**Comment by saintnoven** [comment]
> 没日志，没说用的哪个解析服务器，算命都算不出

小问题大佬，已经解决了

**Comment by Mikebarela** [comment]
难受啊他现在显示我账户未登录，可我明明登了
