### ISSUE TITLE
拉取视频地址失败

### ISSUE THREAD

**Issue by collkey-cys** [ipcjs/bilibili-helper#975]
脚本问题：@ipcjs
进如番剧页面后，无法加载出视频，只有（小电视非常抱歉，无法使用.jpg）

## 拉取视频地址失败
原因: {"code":-1,"error":{"readyState":0,"responseText":"","status":0,"statusText":"error"}}
进如番剧页面后，无法加载出视频，只有（小电视非常抱歉，无法使用.jpg），但是字幕已经加载出来了，鼠标移到进度条上出现小画面
![image](https://user-images.githubusercontent.com/105166074/167305723-34d75c86-5177-4700-b98c-d919872aec8e.png)

- 问题网址：
https://www.bilibili.com/bangumi/play/ss41485

## 日志
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.17 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss41485
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"--爱吃香菜--","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=41485
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?cid=572199685&qn=120&type=&otype=json&fourk=1&bvid=BV1w34y1v7YB&ep_id=476893&fnver=0&fnval=80&session=87158d081cbde465116b5bbb6acf9b22&module=bangumi&area=&access_key={{access_key}}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: atRun: 2, complete
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=572199685&bvid=BV1w34y1v7YB&qn=120&type=&otype=json&ep_id=476893&fourk=1&fnver=0&fnval=80&session=f411a8500486e9f5c9b69eb0fa290593&module=bangumi&balh_ajax=1&area=&access_key=2b6e1124586451eeb993de849a215151
debug: /x/web-interface/nav {"uname":"--爱吃香菜--","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.17 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss41485
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"--爱吃香菜--","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=41485
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?cid=572199685&qn=120&type=&otype=json&fourk=1&bvid=BV1w34y1v7YB&ep_id=476893&fnver=0&fnval=80&session=87158d081cbde465116b5bbb6acf9b22&module=bangumi&area=&access_key={{access_key}}
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: atRun: 2, complete
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=572199685&bvid=BV1w34y1v7YB&qn=120&type=&otype=json&ep_id=476893&fourk=1&fnver=0&fnval=80&session=f411a8500486e9f5c9b69eb0fa290593&module=bangumi&balh_ajax=1&area=&access_key=2b6e1124586451eeb993de849a215151
debug: /x/web-interface/nav {"uname":"--爱吃香菜--","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://app.bili.link/pgc/player/web/playurl?avid=undefined&cid=578119361&bvid=BV1wT4y1a7zL&qn=120&type=&otype=json&ep_id=476894&fourk=1&fnver=0&fnval=80&session=db521e8f2c88b4a5650588a85bcabf52&module=bangumi&balh_ajax=1&area=&access_key=2b6e1124586451eeb993de849a215151
```
 
</details>

![image](https://user-images.githubusercontent.com/105166074/167305743-aa5aee46-d3f9-430d-8450-eb9ea81498e3.png)

## 其他

1. 浏览器版本：Chrome最新版
2. 国家/地区：中国/大陆

**Comment by AisukaYuki** [comment]
脚本里说明的某几个服务器早跑路了，去公共服务器里面找

**Comment by collkey-cys** [comment]
换服务器解决了，感谢大佬

**Comment by funikty** [comment]
想问一下大佬们哪个服务器好用的
