### ISSUE TITLE
尝试帐号授权无效，只会跳转mcbbs.net的链接，这正常吗

### ISSUE THREAD

**Issue by MY1L** [ipcjs/bilibili-helper#976]
脚本问题：@ipcjs

## 描述

昨天之前脚本运作还是正常的。今天看到提示：
#### 拉取视频地址失败
原因: {"code":-101,"message":"帐号未登录","ttl":1}

又刷新了下确认b站登录没掉，于是去“设置页面”点“帐号授权”，结果跳转到 https://www.mcbbs.net/template/mcbbs/image/special_photo_bg.png?access_key=****&uname=****&sign=****
看上去没有授权上（也确实没有，更改服务器重复操作多次仍然如此提示）。
这情况正常吗（尤其是，为什么会跳转到mcbbs.net的special_photo图片？）

## 日志

<details>
<summary>Verbose 日志</summary>

```
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.16 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep****
debug: userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

```
 如果日志缺少什么请告诉我，我会补充的。
</details>

## 其他

1. 浏览器版本：userAgent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
2. 国家/地区：大陆

**Comment by AisukaYuki** [comment]
按理说会从mcbbs跳转回来的，更新或者换个浏览器试试

**Comment by MY1L** [comment]
好，我更新到v8.2.17等重启浏览器试试（这几天浏览器忙乎着不能关😓）

**Comment by MY1L** [comment]
更新和重启系统均未从mcbbs跳转回来，是否类Chrome浏览器配置问题:sweat:

**Comment by cccitu** [comment]
我也遇到了这个问题，授权失败，提示 存储失败：网络错误。重试次数超过3次，登录失败

-----
已恢复正常
