### ISSUE TITLE
问个问题啊，为什么我那个仅限台湾地区的番看不了（其他的是可以的）？一个月前还能看来着。是不是那个台湾的代理服务器不行了？如果是的话，能给一个能用的吗？

### ISSUE THREAD

**Issue by lmqdlxy** [ipcjs/bilibili-helper#978]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by JasonKhew96** [comment]
你得 提供 一下 日志，还有用的 哪个 公共解析服务器，不然 不知道是 谁的问题

**Comment by lmqdlxy** [comment]
debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.17 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss41470#476246
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"夜明の流星群","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=41470
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?cid=570482550&qn=80&type=&otype=json&fourk=1&bvid=BV1494y1Z7GJ&ep_id=476242&fnver=0&fnval=80&session=6ec023b65efebb7d0fc52ce2c4ba96a2&module=bangumi&area=tw&access_key={{access_key}}
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://哔哩.ink/pgc/player/web/playurl?cid=570482550&qn=80&type=&otype=json&fourk=1&bvid=BV1494y1Z7GJ&ep_id=476242&fnver=0&fnval=80&session=6ec023b65efebb7d0fc52ce2c4ba96a2&module=bangumi&area=&access_key=03756540c99e2a8f54642da663af3f51
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?cid=570482550&qn=80&type=&otype=json&fourk=1&bvid=BV1494y1Z7GJ&ep_id=476242&fnver=0&fnval=80&session=6ec023b65efebb7d0fc52ce2c4ba96a2&module=bangumi&access_key=03756540c99e2a8f54642da663af3f51
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://api.qiu.moe/intl/gateway/v2/ogv/playurl?area=th&access_key=03756540c99e2a8f54642da663af3f51&appkey=7d089525d3611b1c&build=1001310&cid=570482550&ep_id=476242&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=80&ts=1652859367&sign=b16d0c1ec6303e51804c8dfd39ae3164
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?cid=570482550&qn=80&type=&otype=json&fourk=1&bvid=BV1494y1Z7GJ&ep_id=476242&fnver=0&fnval=80&session=6ec023b65efebb7d0fc52ce2c4ba96a2&module=bangumi&area=hk&access_key=03756540c99e2a8f54642da663af3f51
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?cid=570482550&qn=80&type=&otype=json&fourk=1&bvid=BV1494y1Z7GJ&ep_id=476242&fnver=0&fnval=80&session=6ec023b65efebb7d0fc52ce2c4ba96a2&module=bangumi&access_key=03756540c99e2a8f54642da663af3f51
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 捕获标题提示，使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=undefined&cid=570482550&bvid=BV1494y1Z7GJ&qn=80&type=&otype=json&ep_id=476242&fourk=1&fnver=0&fnval=80&session=c1c21379fa77c51af5870bf5ddf31647&module=bangumi&balh_ajax=1&area=tw&access_key=03756540c99e2a8f54642da663af3f51
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://哔哩.ink/pgc/player/web/playurl?avid=undefined&cid=570482550&bvid=BV1494y1Z7GJ&qn=80&type=&otype=json&ep_id=476242&fourk=1&fnver=0&fnval=80&session=c1c21379fa77c51af5870bf5ddf31647&module=bangumi&balh_ajax=1&area=&access_key=03756540c99e2a8f54642da663af3f51
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://1985592077837091.cn-shanghai.fc.aliyuncs.com/2016-08-15/proxy/bili/bili_prox/?avid=undefined&cid=570482550&bvid=BV1494y1Z7GJ&qn=80&type=&otype=json&ep_id=476242&fourk=1&fnver=0&fnval=80&session=c1c21379fa77c51af5870bf5ddf31647&module=bangumi&balh_ajax=1&access_key=03756540c99e2a8f54642da663af3f51
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://api.qiu.moe/intl/gateway/v2/ogv/playurl?area=th&access_key=03756540c99e2a8f54642da663af3f51&appkey=7d089525d3611b1c&build=1001310&cid=570482550&ep_id=476242&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=80&ts=1652859369&sign=8870010e0152ad56b3b07bc6b6438b49
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=undefined&cid=570482550&bvid=BV1494y1Z7GJ&qn=80&type=&otype=json&ep_id=476242&fourk=1&fnver=0&fnval=80&session=c1c21379fa77c51af5870bf5ddf31647&module=bangumi&balh_ajax=1&area=hk&access_key=03756540c99e2a8f54642da663af3f51
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-tw-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=570482550&bvid=BV1494y1Z7GJ&qn=80&type=&otype=json&ep_id=476242&fourk=1&fnver=0&fnval=80&session=c1c21379fa77c51af5870bf5ddf31647&module=bangumi&balh_ajax=1&access_key=03756540c99e2a8f54642da663af3f51
debug: /x/web-interface/nav {"uname":"夜明の流星群","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47

**Comment by lmqdlxy** [comment]
代理服务器全是用的你提供的那个

**Comment by lmqdlxy** [comment]
![QQ图片20220518154347](https://user-images.githubusercontent.com/103895254/168985145-79a43aab-65e8-49f0-923c-2332cc0f1f73.png)

**Comment by JasonKhew96** [comment]
@lmqdlxy 查了一下，你帐号 解析服务器 黑名单 了

**Comment by lmqdlxy** [comment]
那怎么办

**Comment by lmqdlxy** [comment]
能给一个其他能用的解析服务器吗
