### ISSUE TITLE
今天忽然显示我所在的地区不可观看，请问是怎么回事啊- -

### ISSUE THREAD

**Issue by wld123** [ipcjs/bilibili-helper#984]
脚本问题：@ipcjs

## 描述

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.17 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep477916?spm_id_from=333.851.dynamic.content.click
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip:  server: https://www.biliplus.com upos_server: hw flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"浣溪沙eX","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=477916
debug: atRun: 1, interactive
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所在地区不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://陈睿.我爱你/pgc/player/web/playurl?cid=731057076&qn=116&type=&otype=json&fourk=1&bvid=BV1Zr4y1s7tt&ep_id=477916&fnver=0&fnval=80&session=cab7cca25e31d5e0405469cdaa5ea0e4&module=bangumi&area=&access_key=43a776d18ce6669aa1c136937ffa3651
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-hk-api.kghost.info/pgc/player/web/playurl?cid=731057076&qn=116&type=&otype=json&fourk=1&bvid=BV1Zr4y1s7tt&ep_id=477916&fnver=0&fnval=80&session=cab7cca25e31d5e0405469cdaa5ea0e4&module=bangumi&access_key=43a776d18ce6669aa1c136937ffa3651
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://陈睿.我爱你/pgc/player/web/playurl?avid=undefined&cid=731057076&bvid=BV1Zr4y1s7tt&qn=116&type=&otype=json&ep_id=477916&fourk=1&fnver=0&fnval=80&session=a6ac08d37b5058419e3f6144118b47cd&module=bangumi&balh_ajax=1&area=&access_key=43a776d18ce6669aa1c136937ffa3651
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-hk-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=731057076&bvid=BV1Zr4y1s7tt&qn=116&type=&otype=json&ep_id=477916&fourk=1&fnver=0&fnval=80&session=a6ac08d37b5058419e3f6144118b47cd&module=bangumi&balh_ajax=1&access_key=43a776d18ce6669aa1c136937ffa3651
debug: /x/web-interface/nav {"uname":"浣溪沙eX","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：

**Comment by wld123** [comment]
浏览器版本，最新版google

**Comment by AisukaYuki** [comment]
你光填一个首选可不就这样吗，你下面的框不填，服务器怎么区分该走那个区域解析。

**Comment by wld123** [comment]
解决了，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月29日(星期天) 上午9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ipcjs/bilibili-helper] 今天忽然显示我所在的地区不可观看，请问是怎么回事啊- - (Issue #984)





 
你光填一个首选可不就这样吗，你下面的框不填，服务器怎么区分该走那个区域解析。
