### ISSUE TITLE
泰区的视频看不了，港澳台的都可以

### ISSUE THREAD

**Issue by akuasikei** [ipcjs/bilibili-helper#986]
脚本问题：@ipcjs

## 描述

- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.17 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep367177
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: replace blocked_vip: Y server: https://www.biliplus.com upos_server:  flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"胡桃喜欢七七","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?ep_id=367177
debug: atRun: 1, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/intl/gateway/v2/ogv/view/app/season?area=th&access_key={{access_key}}&appkey=7d089525d3611b1c&build=1001310&ep_id=367177&force_host=2&mobi_app=bstar_a&platform=android&s_locale=zh_SG&ts=1654020961&sign=09ebd0d1e5d3230bd3adb5402b0d777b
debug: atRun: 2, complete
debug: __playinfo__ get
debug: /pgc/player/web/playurl origin block: undefined {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020967&sign=f9a3e767df691bdbf9efafddf51d994b
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=cn&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020967&sign=61fefeefee6cf1d92a2bed6cb6f68219
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/intl/gateway/v2/ogv/playurl?area=th&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=7d089525d3611b1c&build=1001310&cid=0&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=80&ts=1654020967&sign=c38d53861f473a4a6e24533f994f6654
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=hk&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020967&sign=19eb937384104cddf2523daa2e54159c
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=tw&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020967&sign=b47f81dbcef052d6b01db2535f2a0967
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?cid=0&qn=80&type=&otype=json&fourk=1&bvid=undefined&ep_id=367177&fnver=0&fnval=80&session=f89457c71446e75b6f0ea63303b6475f&module=bangumi&access_key=f4948009b6098019fcb4422a2fd4eb61
debug: /x/web-interface/nav {"uname":"胡桃喜欢七七","isLogin":true,"level":5,"vipType":1,"vipStatus":0,"isFromReport":false}
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
debug: {"code":-10403,"message":"抱歉您所使用的平台不可观看！"}
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020989&sign=2d36a72bc8eab10fe4f2b335dc58711c
info: player msg: 使用大陆代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=cn&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020989&sign=e4f825a5f5f6eacd10ea14758187b40b
info: player msg: 使用泰国（东南亚）代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/intl/gateway/v2/ogv/playurl?area=th&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=7d089525d3611b1c&build=1001310&cid=0&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=bstar_a&platform=android&qn=80&ts=1654020990&sign=0ebe66a45f96f1953f50b2a6a1716c5c
info: player msg: 使用香港代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=hk&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020990&sign=140e63bf5530cb48ec44b89d71c52c16
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/api/playurl?area=tw&access_key=f4948009b6098019fcb4422a2fd4eb61&appkey=07da50c9a0bf829f&build=5380700&buvid=XY418E94B89774E201E22C5B709861B7712DD&cid=0&device=android&ep_id=367177&fnval=80&fnver=0&force_host=2&fourk=1&mobi_app=android_b&platform=android_b&qn=80&track_path=0&ts=1654020990&sign=7c277acbe06355def0be7a5dce20c319
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-cn-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=0&bvid=undefined&qn=80&type=&otype=json&ep_id=367177&fourk=1&fnver=0&fnval=80&session=6db5aaea99c4006d9e9077414261669b&module=bangumi&balh_ajax=1&access_key=f4948009b6098019fcb4422a2fd4eb61
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/intl/gateway/v2/app/subtitle?cid=0&aid=0&bvid=undefined&season_id=36199&ep_id=367177
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53
 
</details>

## 其他

1. 浏览器版本：
2. 国家/地区：
![屏幕截图(45)](https://user-images.githubusercontent.com/106491933/171259351-0828178a-36dd-444a-993c-2e70cc05af68.png)

**Comment by akuasikei** [comment]
![屏幕截图(48)](https://user-images.githubusercontent.com/106491933/171259909-3aa8a90f-4e13-4100-900b-80d170c03619.png)
这个是服务器

**Comment by JasonKhew96** [comment]
已经修了 https://github.com/ipcjs/bilibili-helper/pull/980 ，但是 @ipcjs 没更新版本号

**Comment by ipcjs** [comment]
merge师失格了🥲

重新build了，已经

**Comment by akuasikei** [comment]
好的
