### ISSUE TITLE
[功能建议]希望增加可以选择的upos服务器地址

### ISSUE THREAD

**Issue by jiang-yuan** [ipcjs/bilibili-helper#987]
我在新加坡,在安卓端哔哩漫游模块里进行upos测速的时候发现香港的upos cdn速度最快,但是在油猴脚本里面没办法选择这个cdn
是否能够增加一些哔哩漫游模块有的cdn?

另外,想知道在此油猴脚本设置的upos服务器会应用到普通大陆视频上面吗?还是只应用到需要解锁的大陆视频?如何检查是否切换upos是否生效了?

**Comment by JasonKhew96** [comment]
CORS/UA 问题吧，你可以用这种方法 https://github.com/ipcjs/bilibili-helper/issues/906 ，改一改应该可以用

另外原本有个 PR https://github.com/ipcjs/bilibili-helper/pull/909 修这类问题的，可是已经咕了

**Comment by jiang-yuan** [comment]
我这边不是解析失败403什么的,单纯就是
https://www.bilibili.com/video/BV19U4y1s7cv
这个视频非常卡顿只有几百kb的速度,但是我看别的视频又不卡,想调下cdn看看能不能解决

**Comment by JasonKhew96** [comment]
> 我这边不是解析失败403什么的,单纯就是 https://www.bilibili.com/video/BV19U4y1s7cv 这个视频非常卡顿只有几百kb的速度,但是我看别的视频又不卡,想调下cdn看看能不能解决

可以试试这里的方法 https://github.com/ipcjs/bilibili-helper/blob/user.js/packages/unblock-area-limit/README.md#替换upos视频服务器选项

**Comment by jiang-yuan** [comment]
不大喜欢为了一个功能装一大堆的包和依赖库
想看看这个脚本自带的功能能不能解决
而且我用b站自带的测速测这个视频它分配的ip延迟都不怎么高,就是加载速度慢,我想单纯通过延迟选择ip改hosts的方法也许不适用
![image](https://user-images.githubusercontent.com/36291537/171547635-7586cee5-88ad-4ff5-8b6f-7659b57fde98.png)
不知道是不是b站对这种冷门的长视频限速了导致延迟很低加载速度也很慢
