### ISSUE TITLE
泰区视频加载不出来是什么问题

### ISSUE THREAD

**Issue by 1lkei** [ipcjs/bilibili-helper#988]
服务器换了好多都没用
<img width="1124" alt="屏幕截图 2022-06-02 124255" src="https://user-images.githubusercontent.com/62320562/171554830-568e6b14-b7eb-4982-9da1-59f66cd265f5.png">

**Comment by JasonKhew96** [comment]
https://github.com/ipcjs/bilibili-helper/issues/906

**Comment by Enemu0** [comment]
用了，没有用
<img width="263" alt="屏幕截图 2022-06-02 125033" src="https://user-images.githubusercontent.com/62320562/171555163-98dcdb00-8fb3-4f37-91c0-f94c70f27cb4.png">

**Comment by 1lkei** [comment]
> #906

用了，但是没有用。手机端都好好的，港澳台也没事，就泰区加载不出来，番剧设置页面也打不开

**Comment by JasonKhew96** [comment]
> > #906
> 
> 用了，但是没有用。手机端都好好的，港澳台也没事，就泰区加载不出来，番剧设置页面也打不开

那就不知道了，用的这个吗？ https://github.com/ipcjs/bilibili-helper/issues/906#issuecomment-1120599600

**Comment by 1lkei** [comment]
> > > #906
> > 
> > 
> > 用了，但是没有用。手机端都好好的，港澳台也没事，就泰区加载不出来，番剧设置页面也打不开
> 
> 那就不知道了，用的这个吗？ [#906 (comment)](https://github.com/ipcjs/bilibili-helper/issues/906#issuecomment-1120599600)

破案了。。。。
  Listen 1   这个浏览器脚本冲突了。。。。
大家注意下。。。。。
