### ISSUE TITLE
显示-403 权限不足

### ISSUE THREAD

**Issue by snicoe** [ipcjs/bilibili-helper#989]
脚本问题：@ipcjs

## 描述

- 问题网址：https://www.bilibili.com/video/BV1wv4y1A7SG?spm_id_from=444.41.list.card_archive.click

## 日志

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.18 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/media/md28235419
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: cos flv_prefer_ws:  remove_pre_ad:  generate_sub:  enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: atRun: 0, interactive
warn: danmukuBox not found!
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://www.biliplus.com/api/bangumi?season=39725&access_key={{access_key}}
debug: atRun: 1, interactive
debug: /x/web-interface/nav {"uname":"DXCNS_Studio","isLogin":true,"level":5,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: /season/user/status: {"code":0,"message":"success","result":{"area_limit":0,"ban_area_show":1,"follow":1,"follow_status":2,"login":1,"pay":1,"pay_pack_paid":0,"progress":{"last_ep_id":477101,"last_ep_index":"1","last_time":0},"real_price":"0","sponsor":0,"vip_info":{"due_date":1654444800000,"status":1,"type":2}}}
debug: setAreaLimitSeason 000 false
debug: season39725 {"code":0,"message":"success","result":{"actor":[{"actor":"内田雄马","actor_id":0,"role":"雪村心夜"},{"actor":"雨宫天","actor_id":0,"role":"冰室菖蒲"},{"actor":"原奈津子","actor_id":0,"role":"奏言叶"},{"actor":"大森日雅","actor_id":0,"role":"棘田惠那"},{"actor":"福岛润","actor_id":0,"role":"犬饲虎辅"},{"actor":"置鲇龙太郎","actor_id":0,"role":"池田教授"},{"actor":"梶裕贵","actor_id":0,"role":"克里斯·弗洛雷特"},{"actor":"山田麻里奈","actor_id":0,"role":"藤原翠雨"},{"actor":"麻仓桃","actor_id":0,"role":"理科熊"}],"alias":"理系が恋に落ちたので証明してみた。2期,理科生 第二季,理科生坠入情网，故尝试证明。[r=1-sinθ]","allow_bp":"0","allow_download":"0","area":"日本","arealimit":0,"bangumi_id":"4755","bangumi_title":"理科生坠入情网，故尝试证明。","brief":"在冲绳合宿中，在由于朝阳的云隙光而达到了最高氛围值的桥上，雪村和冰室进行了理论值最高的亲吻，但由于采...","business_type":1,"coins":"0","copyright":"dujia","cover":"https://i0.hdslb.com/bfs/bangumi/image/68aee547fc85b1eab8be3d5c7e946276e4252b79.png","danmaku_count":"0","dm_seg":1,"ed_jump":5,"episodes":[{"av_id":"299271518","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_7c8a9295be30b0076eba1f958ab409b_firsti.jpg","danmaku":"728563750","episode_id":"512427","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第6话","index_title":"理科生坠入情网，故尝试结束证明。 精彩看点 1","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:15:19.0"},{"av_id":"981860916","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_8bd02dde687fb038a3dbc3d1bb6d79b_firsti.jpg","danmaku":"728568527","episode_id":"512448","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第5话","index_title":"理科生坠入情网，故尝试分析喜欢的证据。 精彩看点 2","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:21:13.0"},{"av_id":"469364198","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_6e57261cc2b46b792b2f4e052ea628b_firsti.jpg","danmaku":"728565237","episode_id":"512437","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第5话","index_title":"理科生坠入情网，故尝试分析喜欢的证据。 精彩看点 1","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:16:52.0"},{"av_id":"769350657","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_8143812a860d2ee17c3ba145d6ebf7b_firsti.jpg","danmaku":"728574328","episode_id":"512492","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第4话","index_title":"理科生坠入情网，故尝试去看演唱会。 精彩看点 3","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:28:55.0"},{"av_id":"641814473","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_70c2f5e73ea571488bbd235dd84f4ab_firsti.jpg","danmaku":"728574826","episode_id":"512489","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第4话","index_title":"理科生坠入情网，故尝试去看演唱会。 精彩看点 2","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:28:31.0"},{"av_id":"641801783","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_e8b513c19fda85d001bc99376172b2b_firsti.jpg","danmaku":"728572886","episode_id":"512464","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第4话","index_title":"理科生坠入情网，故尝试去看演唱会。 精彩看点 1","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:24:49.0"},{"av_id":"299285982","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_dd997d5bbb04b4791170e987bf16c8b_firsti.jpg","danmaku":"728570803","episode_id":"512451","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第2话","index_title":"理科生坠入情网，故尝试寻找新的理论。 精彩看点 1","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:21:55.0"},{"av_id":"639326921","coins":"0","cover":"https://i0.hdslb.com/bfs/vc/ogvres/_b1bd3af5c024a93174edbba888156ab_firsti.jpg","danmaku":"728574296","episode_id":"512478","episode_status":2,"episode_type":-1,"from":"bangumi","index":"第1话","index_title":"理科生坠入情网，故尝试与情侣进行对比。 精彩看点 1","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2022-05-24 16:26:19.0"},{"av_id":"678593604","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/56ae674c92f35d27c17f81222d71f45e7cf520c6.jpg","danmaku":"495570019","episode_id":"469712","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场18","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-02-09 12:30:00.0"},{"av_id":"978603617","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/56ae674c92f35d27c17f81222d71f45e7cf520c6.jpg","danmaku":"495529814","episode_id":"469708","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场17","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-02-05 12:30:01.0"},{"av_id":"211070554","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/56ae674c92f35d27c17f81222d71f45e7cf520c6.jpg","danmaku":"495529812","episode_id":"469705","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场16","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-02-01 12:30:01.0"},{"av_id":"978523443","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/56ae674c92f35d27c17f81222d71f45e7cf520c6.jpg","danmaku":"495529806","episode_id":"469702","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场15","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-30 12:30:01.0"},{"av_id":"508085167","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/9f7dd68211cf877bac7358082e775910e118e25f.jpg","danmaku":"482804641","episode_id":"465862","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场14","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-26 12:30:01.0"},{"av_id":"210554919","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"482803853","episode_id":"465861","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场13","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-24 12:30:01.0"},{"av_id":"635599916","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"482803229","episode_id":"465860","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场12","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-22 12:30:01.0"},{"av_id":"935533522","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"482802580","episode_id":"465859","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场11","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-20 12:30:01.0"},{"av_id":"210587051","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"482799233","episode_id":"465858","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场10","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-18 12:30:01.0"},{"av_id":"939590486","badge":"抢先","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/af05c9af35c9025b00506930a3be409cb5dc267a.png","danmaku":"732726669","episode_id":"514109","episode_status":13,"episode_type":0,"from":"bangumi","index":"10","index_title":"理科生坠入情网，故尝试参与校庆。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-06-04 00:30:01.0"},{"av_id":"426399286","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/6849e32ac4e5b64bc2f92892ddfaf02c3c46f143.png","danmaku":"716839363","episode_id":"510569","episode_status":2,"episode_type":0,"from":"bangumi","index":"9","index_title":"理科生坠入情网，故尝试准备校庆。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-05-28 00:30:01.0"},{"av_id":"253022146","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"482798726","episode_id":"465857","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场9","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-16 12:30:01.0"},{"av_id":"338065783","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"482796731","episode_id":"465856","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场8","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-14 12:30:01.0"},{"av_id":"468966954","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/57cec7f38865519c254ce62b9f7023b6c410dc71.jpg","danmaku":"730854233","episode_id":"510568","episode_status":2,"episode_type":0,"from":"bangumi","index":"8","index_title":"理科生坠入情网，故尝试向后辈告白。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-05-21 00:30:01.0"},{"av_id":"508021627","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"482785580","episode_id":"465713","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场7","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-13 12:30:01.0"},{"av_id":"641387343","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/511c6a0fdeb315e5391f03769fda8cd974c85575.jpg","danmaku":"720179168","episode_id":"510567","episode_status":2,"episode_type":0,"from":"bangumi","index":"7","index_title":"理科生坠入情网，故尝试集体约会。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-05-14 00:30:01.0"},{"av_id":"896282598","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f9e698376ee5552bb738845d0a9b35d7957e5479.jpg","danmaku":"713291972","episode_id":"509469","episode_status":2,"episode_type":0,"from":"bangumi","index":"2022年","index_title":"Anime Japan 理科恋舞台","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-05-06 17:02:00.0"},{"av_id":"468778922","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/6a942c9451961a6539c2ca316ed17b29315b385f.jpg","danmaku":"716074632","episode_id":"477107","episode_status":2,"episode_type":0,"from":"bangumi","index":"6","index_title":"理科生坠入情网，故尝试结束证明。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-05-07 00:30:00.0"},{"av_id":"850286002","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"473742546","episode_id":"457297","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场6","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-11 12:30:01.0"},{"av_id":"213616735","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d13f970901ad548cc0a836eaa1ba9b468cbf00a8.jpg","danmaku":"587613077","episode_id":"477106","episode_status":2,"episode_type":0,"from":"bangumi","index":"5","index_title":"理科生坠入情网，故尝试分析喜欢的证据。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-04-30 00:30:01.0"},{"av_id":"640231531","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/74932bd71a06c0f80a080aac39a1979033c6465f.jpg","danmaku":"563480823","episode_id":"477627","episode_status":2,"episode_type":0,"from":"bangumi","index":"NCED","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-03-31 19:00:01.0"},{"av_id":"550341519","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"473740845","episode_id":"457296","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场5","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-09 12:30:01.0"},{"av_id":"640188982","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/7b56864204cb5f568ffd962d1896da35e05869fe.jpg","danmaku":"563479289","episode_id":"477626","episode_status":2,"episode_type":0,"from":"bangumi","index":"NCOP","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-03-31 19:00:01.0"},{"av_id":"340920795","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/3fd1980d4cee719b1e766c5efc3ffa0e2bf45774.jpg","danmaku":"582140270","episode_id":"477105","episode_status":2,"episode_type":0,"from":"bangumi","index":"4","index_title":"理科生坠入情网，故尝试去看演唱会。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-04-23 00:30:01.0"},{"av_id":"892804501","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"473738402","episode_id":"457295","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场4","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-07 12:30:01.0"},{"av_id":"295327001","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"473736673","episode_id":"457294","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场3","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-05 12:30:01.0"},{"av_id":"934848895","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e8ab1531d2ca98d508b6ea5fab81f5b5fa2d3b7d.jpg","danmaku":"460345136","episode_id":"440692","episode_status":2,"episode_type":0,"from":"bangumi","index":"声优特番","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2021-12-14 12:30:01.0"},{"av_id":"768233459","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/f1e5169992d656cfe8031810f06f3d6508cd6c92.jpg","danmaku":"578995140","episode_id":"477104","episode_status":2,"episode_type":0,"from":"bangumi","index":"3","index_title":"理科生坠入情网，故尝试睡午觉。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-04-16 00:30:01.0"},{"av_id":"510382873","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/234057e11f4d54c97fa1e6ef0f0fe80e40392c75.jpg","danmaku":"585345953","episode_id":"477103","episode_status":2,"episode_type":0,"from":"bangumi","index":"2","index_title":"理科生坠入情网，故尝试寻找新的理论。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-04-09 00:30:01.0"},{"av_id":"935327696","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"473734649","episode_id":"457293","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场2","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-03 12:30:01.0"},{"av_id":"211883540","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/78be4b5d5b6736f4657e0d476ed3a9cb234e4404.jpg","danmaku":"540673636","episode_id":"473269","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV2","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-03-07 09:00:00.0"},{"av_id":"806206222","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/bd6beee065d0f314e71492999b784e9a0730b1e1.jpg","danmaku":"428647714","episode_id":"426702","episode_status":2,"episode_type":0,"from":"bangumi","index":"PV","index_title":"","is_webplay":"0","mid":"408002864","page":"1","premiere":false,"up":{},"update_time":"2021-10-23 17:00:01.0"},{"av_id":"640272344","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/e4f5213df9d74a9e73a6a67b7df7e0e3a22736b8.jpg","danmaku":"567739354","episode_id":"477101","episode_status":2,"episode_type":0,"from":"bangumi","index":"1","index_title":"理科生坠入情网，故尝试与情侣进行对比。","is_webplay":"0","mid":"928123","page":"1","premiere":false,"up":{},"update_time":"2022-04-01 19:00:01.0"},{"av_id":"892818694","coins":"0","cover":"https://i0.hdslb.com/bfs/archive/d0ec7304bbbf24540c9be7366cb15ba183a090f8.jpg","danmaku":"473658321","episode_id":"457292","episode_status":2,"episode_type":0,"from":"bangumi","index":"回顾小剧场1","index_title":"","is_webplay":"0","mid":"1217289199","page":"1","premiere":false,"up":{},"update_time":"2022-01-01 12:30:01.0"}],"evaluate":"在冲绳合宿中，在由于朝阳的云隙光而达到了最高氛围值的桥上，雪村和冰室进行了理论值最高的亲吻，但由于采集的唾液量并不充足，于是决定再次测量。\n为拜访唾液检测的专家，一行人动身前往理工部生命科学学院。而他们面前出现的是花魁打扮配一袭白衣的艳丽女子翠雨，以及她的恋人克里斯。\n雪村邀请翠雨二人帮助他们一起完成「证明喜欢的实验」，却因此见识了翠雨他们压倒性的爱之气场……","favorites":"0","has_unfollow":0,"is_finish":"0","is_guide_follow":1,"jp_title":"理系が恋に落ちたので証明してみた。2期","limit_info":{"code":0,"data":{"down":0,"play":2},"message":"success"},"media":{"area":[{"id":2,"name":"日本"}],"cover":"https://i0.hdslb.com/bfs/bangumi/image/68aee547fc85b1eab8be3d5c7e946276e4252b79.png","episode_index":{"index_show":"连载中"},"media_id":28235419,"publish":{"is_finish":0,"is_started":1},"rating":{"count":5049,"score":8.6},"title":"理科生坠入情网，故尝试证明。 第二季","type_id":1,"type_name":"动画"},"newest_ep_id":"514109","newest_ep_index":"10","origin_name":"理系が恋に落ちたので証明してみた。2期","payment":{"price":"0","promotion":"","tip":"大会员专享观看特权哦~","vip_promotion":"成为大会员抢先看"},"play_count":"0","pub_string":"","pub_time":"2022-04-01 19:00:00","pub_time_show":"4月1日 19:00 ","related_seasons":[],"rights":{"arealimit":0,"is_started":1},"season_id":"39725","season_status":13,"season_title":"第二季","seasons":[{"bangumi_id":"4755","cover":"https://i0.hdslb.com/bfs/bangumi/image/977d915210fda50930ca824bd0711a11dda945ab.png","is_finish":"1","newest_ep_id":"307487","newest_ep_index":"12","season_id":"29110","season_status":13,"title":"第一季","total_count":"12"},{"bangumi_id":"4755","cover":"https://i0.hdslb.com/bfs/bangumi/image/44c8c6a4fa7a2a6f3083d7e5ea21915c8266922f.png","is_finish":"1","newest_ep_id":"411758","newest_ep_index":"12","season_id":"38878","season_status":13,"title":"第一季 中配版","total_count":"12"},{"bangumi_id":"4755","cover":"https://i0.hdslb.com/bfs/bangumi/image/68aee547fc85b1eab8be3d5c7e946276e4252b79.png","is_finish":"0","is_new":"1","newest_ep_id":"514109","newest_ep_index":"10","season_id":"39725","season_status":13,"title":"第二季"}],"share_url":"http://bangumi.bilibili.com/anime/39725/","spid":"0","squareCover":"https://i0.hdslb.com/bfs/bangumi/image/a4fa3f4ecaa4efc883aa1ef2ca7ed736edb38b8c.png","staff":"原作：山本阿里弗雷德（《COMIC Meteor》连载）\n监督：喜多幡彻\n系列构成·脚本：池田临太郎\n总作画监督：牛岛勇二\n道具设计：狩野都\n美术监督：坂上裕文\n色彩设计：松山爱子\n摄影监督：田中浩介\n剪辑：宇都宫正记\n音响监督：今泉雄一\n音乐：平田祥一郎、hisakuni、曾木琢磨、高桥祐子、高桥修平、横地健太、Uio、大塚郁\nBGM制作：SUPA LOVE\n监制：斋藤俊辅\n动画制作：ZERO-G\n制作总指挥：夏目公一朗","tag2s":[],"tags":[],"title":"理科生坠入情网，故尝试证明。 第二季","update_pattern":"","user_season":{"attention":"0","bp":0,"last_ep_index":"","last_time":"0","report_ts":0},"viewRank":0,"vip_quality":0,"watchingCount":"0","weekday":"-1"}}
debug: atRun: 2, complete
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
debug: balh_server_custom  =>  https://bili-proxy.98e.org
debug: balh_server_custom  =>  https://bili-proxy.98e.org
debug: balh_server_custom_hk  =>  https://bili-proxy.98e.org
debug: balh_server_custom_hk  =>  https://bili-proxy.98e.org
```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

##其他
已经尝试自己的服务器和公共服务器均报-403

**Comment by AisukaYuki** [comment]
plus BV获取番剧出问题，不管解析服务器的事，建议不要用BV号访问港澳台番剧

**Comment by snicoe** [comment]
@AisukaYuki 好的，谢谢回复
