### ISSUE TITLE
突破黑洞失败 null

### ISSUE THREAD

**Issue by JolyneAnasui** [ipcjs/bilibili-helper#99]
## 描述
突破黑洞失败 null

## 日志

```
直接复制太乱了...见下面截图...麻烦了...谢谢

```

![image](https://user-images.githubusercontent.com/36111319/35770026-25afbf92-094f-11e8-9578-69e70c20ee92.png)

## 其他

1. 浏览器版本：60.0.3112.90（正式版本） （64 位）
2. 国家/地区：中国大陆

**Comment by ipcjs** [comment]
#100
