### ISSUE TITLE
黑画面无法观看

### ISSUE THREAD

**Issue by B0509067** [ipcjs/bilibili-helper#996]
比较新的番都是黑画面无法观看，服务器应该没问题，因为旧番可以看，现在是比较新的番都是黑画面无法观看。
![image](https://user-images.githubusercontent.com/40197127/173113970-75c259c9-6dc4-4730-8b43-69399c984c9e.png)

**Comment by cxw620** [comment]
> 比较新的番都是黑画面无法观看，服务器应该没问题，因为旧番可以看，现在是比较新的番都是黑画面无法观看。 ![image](https://user-images.githubusercontent.com/40197127/173113970-75c259c9-6dc4-4730-8b43-69399c984c9e.png)

最近大B给upos的鉴权参数改了改, 可能不兼容

**Comment by B0509067** [comment]
有办法修好吗?

**Comment by cxw620** [comment]
> 有办法修好吗?

6月初的问题, 最近应该各个公共服务器都更新了吧. 我自己编译的`biliroaming-go-server` 目前测试没有问题.
另外我看你访问的这个`https://www.bilibili.com/bangumi/play/ep515700`也不是港澳台的啊, 可能是你选的服务器不完全支持中国大陆的解析, 又或者是脚本不兼容新版播放器. 可以换个解析服务器或者换个脚本试一下.

**Comment by NoWorldYesiR** [comment]
> 最近大B给upos的鉴权参数改了改, 可能不兼容

确实，关了upos替换就好了
