### ISSUE TITLE
脚本安装时出现编码错误，错误800A03EA

### ISSUE THREAD

**Issue by Cherishie** [ipcjs/bilibili-helper#997]
脚本问题：@ipcjs

## 描述
脚本安装时出现编码错误
- 问题网址：

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

## 其他
![image](https://user-images.githubusercontent.com/107306600/173186467-4dba744a-f1a5-48d7-80bb-5e6c294ba6f8.png)

1. 浏览器版本：Chrome 版本 102.0.5005.115（正式版本） （64 位）
2. 国家/地区：中国

**Comment by JasonKhew96** [comment]
@Cherishie 你觉得这东西应该怎么安装？

**Comment by KyuubiRan** [comment]
你是怎么办到的？！

**Comment by KurosakiRei** [comment]
蚌埠住了

**Comment by AisukaYuki** [comment]
README是一点都不看了 属于是
