### ISSUE TITLE
一部新的一部港澳台番剧，无法播放左下角出现从来没见过的kghost服务器

### ISSUE THREAD

**Issue by zangliu2077** [ipcjs/bilibili-helper#998]
脚本问题：@ipcjs

## 描述

点开番剧，
左下角显示：
播放器初始化...
加载视频内容...
[解除B站区域限制]从自定义服务器拉去视频地址中...
[解除B站区域限制]使用首选代理服务器拉去视频地址...
[解除B站区域限制]使用台湾代理服务器拉去视频地址...
[解除B站区域限制]尝试使用kghost的服务器拉去视频地址...
然后弹窗：
{"code":-10403,"message":"抱歉您所在地区不可观看!"}
其他番剧只要不出现kghost都能正常播放，就辉夜大小姐第三季港澳台不行，但是这个番台湾限定的又可以正常播放
因为这个季度我同时追了不少番剧，但是突然发现就这个不可以
- 问题网址：
https://www.bilibili.com/bangumi/play/ss41550/

## 日志

<details>
<summary>Verbose 日志</summary>

debug: atRun: -1, loading
debug: [解除B站区域限制 v8.2.22 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ss41550/
debug: window.__playinfo__ 
debug: XMLHttpRequest的描述符: {"writable":true,"enumerable":false,"configurable":true}
info: mode: default blocked_vip:  server: https://www.biliplus.com upos_server: kodo flv_prefer_ws:  remove_pre_ad:  generate_sub: Y enable_in_av:  readyState: loading isLogin: true isLoginBiliBili: true
debug: set jQuery  -> function(a,b){return new e.fn.init(a,b,h)}
debug: injectAjax at: function(a,b){return new e.fn.init(a,b,h)}
debug: /x/web-interface/nav {"uname":"藏六青羽","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: atRun: 0, interactive
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bangumi.bilibili.com/view/web_api/season?season_id=41550
debug: atRun: 1, interactive
debug: __playinfo__ get
debug: /pgc/player/web/playurl
debug: season_type: 1
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?cid=582125085&qn=112&type=&otype=json&fourk=1&bvid=BV1W541117xe&ep_id=477911&fnver=0&fnval=80&session=c74a2aa72fb7625d1d367cdaf19f9a1a&module=bangumi&area=&access_key={{access_key}}
debug: atRun: 2, complete
debug: /pgc/player/web/playurl origin block: true {"code":-10403,"message":"抱歉您所在地区不可观看！"}
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?cid=582125085&qn=112&type=&otype=json&fourk=1&bvid=BV1W541117xe&ep_id=477911&fnver=0&fnval=80&session=c74a2aa72fb7625d1d367cdaf19f9a1a&module=bangumi&area=tw&access_key=1cf46bf271e446adbd0655a253497b41
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function(a,b){return new e.fn.init(a,b,h)}
debug: ajax: //bilibili-hk-api.kghost.info/pgc/player/web/playurl?cid=582125085&qn=112&type=&otype=json&fourk=1&bvid=BV1W541117xe&ep_id=477911&fnver=0&fnval=80&session=c74a2aa72fb7625d1d367cdaf19f9a1a&module=bangumi&access_key=1cf46bf271e446adbd0655a253497b41
debug: __playinfo__ set
debug: set jQuery function(a,b){return new e.fn.init(a,b,h)} -> function i(t,a){return new i.fn.init(t,a,e)}
debug: injectAjax at: function i(t,a){return new i.fn.init(t,a,e)}
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: __playinfo__ get
debug: season_type: 1
debug: playurl add 'module=bangumi' param
info: player msg: 从自定义服务器拉取视频地址中...
info: player msg: 使用首选代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://service-fi0gz11m-1252917345.hk.apigw.tencentcs.com/pgc/player/web/playurl?avid=undefined&cid=582125085&bvid=BV1W541117xe&qn=112&type=&otype=json&ep_id=477911&fourk=1&fnver=0&fnval=80&session=3cca0d62a0746bc678c6d1959aab575a&module=bangumi&balh_ajax=1&area=&access_key=1cf46bf271e446adbd0655a253497b41
info: player msg: 使用台湾代理服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: https://bili.tuturu.top/pgc/player/web/playurl?avid=undefined&cid=582125085&bvid=BV1W541117xe&qn=112&type=&otype=json&ep_id=477911&fourk=1&fnver=0&fnval=80&session=3cca0d62a0746bc678c6d1959aab575a&module=bangumi&balh_ajax=1&area=tw&access_key=1cf46bf271e446adbd0655a253497b41
info: player msg: 尝试使用kghost的服务器拉取视频地址...
debug: retryUntil.ajaxBy$: function i(t,a){return new i.fn.init(t,a,e)}
debug: ajax: //bilibili-hk-api.kghost.info/pgc/player/web/playurl?avid=undefined&cid=582125085&bvid=BV1W541117xe&qn=112&type=&otype=json&ep_id=477911&fourk=1&fnver=0&fnval=80&session=3cca0d62a0746bc678c6d1959aab575a&module=bangumi&balh_ajax=1&access_key=1cf46bf271e446adbd0655a253497b41
debug: /x/web-interface/nav {"uname":"藏六青羽","isLogin":true,"level":6,"vipType":2,"vipStatus":1,"isFromReport":false}
debug: userAgent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36 Edg/101.0.1210.32
</details>

## 其他

1. 浏览器版本：edge 和chrome
2. 国家/地区：广东电信

**Comment by AisukaYuki** [comment]
仅限港澳，台的服务器肯定提示不支持，然后港的云函数的服务器早寄了，去公共列表找能用的服务器。

**Comment by zangliu2077** [comment]
感谢回复，刚发现标题的港澳限制，已经换代替的服务器了，能用了
